### ISSUE TITLE
[5.6] assertDatabaseHas MySQL Bug

### ISSUE THREAD

**Issue by LoveKoBebz** [laravel/framework#24769] opened 2018-07-07 18:11 UTC
- Laravel Version: 5.6.26
- PHP Version: 7.2.6
- Database Driver & Version: sqlite3 & mysql 5.7.22

### Description:

I'm testing a delete post feature and using `assertDatabaseHas` with MySQL database I get a weird error.

```
1) Tests\Feature\PostDeleteTest::testGuestUsersCannotDeletePost
Failed asserting that a row in the table [posts] matches the attributes {
    "user_id": 1,
    "title": "Example Title",
    "meta": "{\"description\":\"Example Description\"}",
    "updated_at": "2018-07-07 17:54:46",
    "created_at": "2018-07-07 17:54:46",
    "id": 1
}.

Found: [
    {
        "id": 1,
        "user_id": 1,
        "title": "Example Title",
        "meta": "{\"description\": \"Example Description\"}",
        "created_at": "2018-07-07 17:54:46",
        "updated_at": "2018-07-07 17:54:46"
    }
].
```

When I run the test using sqlite in memory the test pass.

### Steps To Reproduce:

1. Create new laravel project.
2. Create the post model.

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $casts = [
        'meta' => 'array',
    ];
}
```

3. Create posts migration.

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePostsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('posts', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->unsigned();
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->string('title');
            $table->json('meta')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('posts');
    }
}
```

4. Create posts controller.

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PostsController extends Controller
{
    public function destroy($id)
    {
        //
    }
}
```

5. Create post delete route.

```
<?php

return [
    Route::delete('posts/{post}', 'PostsController@destroy')->name('posts.destroy')->middleware('auth');
];
```

6. Define post factory.

```
<?php

$factory->define(App\Post::class, function (Faker $faker) {
    return [
        'user_id' => function () {
            return factory(App\User::class)->create()->id;
        },
        'title' => 'Example Title',
        'meta' => [
            'description' => 'Example Description'
        ]
    ];
});
```

7. The post test case.

```
<?php

namespace Tests\Feature;

use App\Post;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class PostDeleteTest extends TestCase
{
    use RefreshDatabase;

    public function testGuestUsersCannotDeletePost()
    {
        $post = factory(Post::class)->create();

        $response = $this->deleteJson(route('posts.destroy', $post));

        $response->assertStatus(401);
        $this->assertDatabaseHas('posts', $post->getAttributes());
    }
}
```

**Comment by laurencei** [comment] 2018-07-08 00:33
Looks like the issue is

`"meta": "{\"description\":\"Example Description\"}",`
vs
`"meta": "{\"description\": \"Example Description\"}",`

**Comment by staudenmeir** [comment] 2018-07-09 00:37
When inserting JSON values, MySQL automatically adds a whitespace after each key:

    {"foo":"bar"} → {"foo": "bar"}

You could exclude the `meta` column:

```php
$this->assertDatabaseHas('posts', Arr::except($post->getAttributes(), ['meta']));
```

Or maybe checking the `id` is sufficient in your case:

```php
$this->assertDatabaseHas('posts', ['id' => $post->id]);
```

**Comment by themsaid** [comment] 2018-07-09 15:00
Closing since it's not actually a bug.

**Closed by themsaid** 2018-07-09 15:00 UTC

**Comment by almokhtarbr** [comment] 2018-07-26 10:35
hahahahha @themsaid again what the hell is going on here
