### ISSUE TITLE
Validator::extend returns function doesn't exists

### ISSUE THREAD

**Issue by Juanacv** [laravel/framework#24874] opened 2018-07-17 12:09 UTC
Hello everybody:

I am trying to extend Validation, following the docs:

https://laravel.com/docs/5.6/validation#using-extensions

But when i use it, always return this error:
"message": "Method Illuminate\\Validation\\Validator::validateInRange does not exist.",

My code:

```
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Validator;
use Carbon\Carbon;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Validator::extend('in_range', function ($attribute, $value, $parameters, $validator) {
            $input = $validator->getData();
            $timeFrom = Carbon::createFromTimeString($input['time_from'], 'Europe/Madrid');
            $timeUntil = Carbon::createFromTimeString($value, 'Europe/Madrid');
            if ($timeFrom > $timeUntil) {
                return false;
            }

            if ($timeFrom->diffInMinutes($timeUntil, false) > 480) {
                return false;
            }
            return true;
        });

        Validator::replacer('in_range', function($message, $attribute, $rule, $parameters){
            return str_replace(':time', $attribute, $message);
        });
    
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```

I am trying with even more simple functions (just returning true) and I always get same error.

I have been scanning the web and the answers are the same, and i can't fix it.

If i put the function on web.php routes it works, but i don't want to mix code with routes.

thank you in advance.

**Comment by staudenmeir** [comment] 2018-07-17 12:17
Please format the whole code.

How do you use the `in_range` rule?

**Comment by Juanacv** [comment] 2018-07-17 12:24
I use like this:

`$input = $request->all();
$validatedData = Validator::make($input, [...] 'time_from'=>'required','time_until'=>'required|in_range'));`

**Comment by staudenmeir** [comment] 2018-07-17 13:03
What's the result of `dd(Validator::make(...)->extensions);`?

**Comment by Juanacv** [comment] 2018-07-17 13:12
Excuse me, I had to use var_dump, but here is the result:

```
<pre class='xdebug-var-dump' dir='ltr'>
<small>/Users/jcalderon/proyectos/Proyecto/app/Http/Controllers/OrderController.php:18:</small>
<b>array</b> <i>(size=0)</i>
  <i><font color='#888a85'>empty</font></i>
</pre>
```

**Comment by staudenmeir** [comment] 2018-07-17 13:19
What's your Laravel version?

**Comment by Juanacv** [comment] 2018-07-17 13:24
Laravel 5.6

Maybe is AppServiceProvider not properly loaded?

**Comment by staudenmeir** [comment] 2018-07-17 13:31
The rule is available in `web.php`, so `AppServiceProvider` must be loaded.

Your code works for me. Can you reproduce the problem on a fresh Laravel installation?

I'm pretty sure we had the same problem a while ago, but I can't find the issue.

**Comment by Juanacv** [comment] 2018-07-17 13:49
Oh my god, i am so ashamed...

I had 2 projects opened at the same time, i was writing on the project i wasn't testing....

I fell so embarrassed and so sorry...

Thanks for your patience...

**Comment by staudenmeir** [comment] 2018-07-17 13:53
Can you close the issue?

**Closed** 2018-07-17 13:54 UTC
