### ISSUE TITLE
Global HTTP client middleware being forgotten after every queue job

### ISSUE THREAD

**Issue by cleptric** [laravel/framework#47738] opened 2023-07-13 12:39 UTC
### Laravel Version

10.15.0

### PHP Version

8.1.19

### Database Driver & Version

MySQL 8.0.33

### Description

All Facades are reset after each queue job, https://github.com/laravel/framework/blob/3cd9bcb25dbfb4e70c9b96dd5b9c2ce109583217/src/Illuminate/Queue/QueueServiceProvider.php#L214.

This causes a global HTTP client middleware, applied in my app's ServiceProvider, not to be applied anymore when using `Http::get()` etc.

### Steps To Reproduce

`app/Providers/AppServiceProvider::boot()`

```php
public function boot()
{
    Http::globalRequestMiddleware(fn ($request) => $request->withHeader(
        'User-Agent', 'Example Application/1.0'
    ));
}
```

`app/Jobs/DoStuff::handle()`

```php
public function handle() {
    Http::get('https://example.com/1');
}
```

**Comment by ajmeireles** [comment] 2023-07-13 16:43
> 

I was not able to reproduce the issue using a fresh Laravel installation **(v10.15.0)**

1. `app/Providers/AppServiceProvider`:

![image](https://github.com/laravel/framework/assets/60591772/688e15c6-dae5-4cc9-8619-5c753ef39750)

2. `app/Job/TestJob`:

![image](https://github.com/laravel/framework/assets/60591772/5737656a-6b6c-4261-aca5-22ac782b5cdf)

3. Result:

![image](https://github.com/laravel/framework/assets/60591772/a844df5e-3cc9-433c-b06a-5dc1f37b2f7d)

**Comment by cleptric** [comment] 2023-07-13 16:46
Did you run multiple jobs and all of the requests have the header ls attached?

**Comment by noor1yasser9** [comment] 2023-07-14 09:28
this problem U R facing is W/ Laravel queue system and Facades. By default, Laravel resets Facade instances after each queue job, including the global HTTP client middleware. This means that when using Http::get() in a queued job, the middleware is not applied, to fix this, modify ur queued job to manually include the middleware before making HTTP requests. This ensures consistent application of the global middleware.

Maybe this code can explain what I mean

```
  use Illuminate\Support\Facades\Http;
  
  class UrQ implements ShouldQueue
  {
      public function handle()
      {
          $httpClient = Http::withOptions([
              'middleware' => [
                  function ($request, $next) {
                      $request = $request->withHeader('User-Agent', 'Example Application/1.0');
                      return $next($request);
                  }
              ]
          ]);
  
          $response = $httpClient->get('https://example.com/1');
          
          // ..
  }  

 ```

**Comment by cleptric** [comment] 2023-07-14 09:38
Yep, already found a workaround. But as this is hard to discover/debug, I opted to open an issue to see if we can fix the actual issue 😀

**Comment by timacdonald** [comment] 2023-07-31 23:38
@cleptric thanks for raising the issue. I think the quickest fix for this would be to add the following in your Service provider...

```php
$this->app->singleton(\Illuminate\Http\Client\Factory::class);
```

I'm going to look into the best fix for the framework.

**Comment by timacdonald** [comment] 2023-08-01 00:37
I've opened a PR to address this issue #47915

I will close this issue and we can follow along with the PR instead.

**Closed by timacdonald** 2023-08-01 00:37 UTC
Labels: help wanted
