### ISSUE TITLE
[5.4] Memory usage increased since v5.4.16

### ISSUE THREAD

**Issue by rimace** [laravel/framework#18806] opened 2017-04-14 13:43 UTC
- Laravel Version: 5.4.18
- PHP Version: 7.1.3
- Database Driver & Version: - (isn't needed)
- Homestead: 5.0

### Description:
Memory usage increased with commit 5d9b363448b9aac83b610166141b8bba9f1807f8 (included since v5.4.16).
I have commands which imports data from CSV files. These commands all use under 7 MB RAM with v5.4.15. Since Laravel 5.4.16 the memory usage has increased to about 300 MB RAM.

### Steps To Reproduce:
I could not reduce the code and reproduce the increase to 300 MB, but this code still shows that the memory usage is multiple times higher with 5.4.16 than with older versions:
https://paste.laravel.io/9q1PA

**Comment by tillkruss** [comment] 2017-04-15 14:36
Ping @taylorotwell.

**Comment by arcanedev-maroc** [comment] 2017-04-15 16:36
I've just tested your snippet and indeed there is an increased usage in memory:

  * `5.4.15`: **8.6 MB**
  * `5.4.16`: **18.6 MB**
  * `5.4.18` (latest): **18.6 MB**

**Comment by laurencei** [comment] 2017-04-15 16:37
I've found the cause.

I'm submitting a PR now

**Comment by laurencei** [comment] 2017-04-16 13:59
@rimace - Taylor has accepted the PR - so this should be fixed and this issue can be closed. If you have any more issues please advise.

**Comment by themsaid** [comment] 2017-04-16 17:48
Thanks everyone :)

**Closed by themsaid** 2017-04-16 17:48 UTC
