### ISSUE TITLE
[5.4] whereHas on polymorphic relations not work

### ISSUE THREAD

**Issue by lkmadushan** [laravel/framework#18523] opened 2017-03-27 18:04 UTC
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: PostgreSQL 9

### Description:
when try whereHas method on a polymorphic relation does not works as expected.

```
Statistics::whereHas('applicable', function ($query) {
        $query->where('employee.id', 1);
    })->toSql();
```

```
select * from "statistics" where exists (select * from "statistics" as "laravel_reserved_0" where "laravel_reserved_0"."id" = "laravel_reserved_0"."applicable_id" and "employee"."id" = ?)
```

**Comment by Dylan-DPC** [comment] 2017-03-27 19:42
@lkmadushan what's the output? any error? or does it give an empty response?

**Comment by themsaid** [comment] 2017-03-27 20:35
Please provide more details, `doesn't work` is not a bug report.

**Comment by lkmadushan** [comment] 2017-03-28 04:04
Sorry. I have updated the description. Currently whereHas on polymorphic relations doesn't add constraints to the relationship query. It always check existence in same table.

**Comment by themsaid** [comment] 2017-03-30 16:33
This won't be an easy fix afaik, we'll need to run several queries on several related tables in order for this work.

**Comment by paulofreitas** [comment] 2017-03-30 20:35
This is related to #5429. There are some workarounds discussed there, like this one: https://github.com/laravel/framework/issues/5429#issuecomment-268178279

It's a known limitation that won't probably be easy to fix. Workarounds indeed work but they involve some tricky engineering.

**Comment by aios** [comment] 2017-04-01 11:49
Marked as No-fix when polimorph relations has not intersect collumns

**Comment by bunnypro** [comment] 2017-04-13 04:57
i'm currently using this code in my own project

my Model (Producion Model)

    public function detail()
    {
        return $this->morphTo('detail');
    }

    public function scopeDetailable($query, $callable = null)
    {
        list($type, $key) = $this->getPolymorphicFields();

        $this->newQuery()->distinct()->get([$type])->keyBy($type)->map(function ($model) {
            return (new $model->detail_type)->getTable();
        })->each(function ($table, $modelClass) use (&$query, $type, $key, $callable) {
            $model = new $modelClass;

            $query = $query->orWhereExists(function ($query) use ($table, $model, $type, $key, $callable) {
                $query->select('*')->from($table)->whereRaw("{$this->getTable()}.{$key} = {$table}.{$model->getKeyName()}")
                    ->when($callable instanceof \Closure, $callable);
            });
        });

        return $query;
    }

    protected function getPolymorphicFields()
    {
        $relation = $this->detail();

        return [$relation->getMorphType(), $relation->getForeignKey()];
    }

my Controller

    \App\Production\Models\Production::detailable(function ($query) {
        $query->whereDate('panen_future_date', '2017-02-08');
    })->with('detail')->get()

and it works for my use case.

**Comment by Dylan-DPC** [comment] 2017-04-13 06:46
@bunnypro can you try it on a new project with just the STR (steps to reproduce), it will be better :)

**Comment by bunnypro** [comment] 2017-04-13 07:30
i forgot to compare the _type filed.

ok i'll try to repoduce it with fresh laravel project and also comparing the _type filed.

**Comment by bunnypro** [comment] 2017-04-13 09:20
i have reproduced in a fresh laravel project. here is the [https://github.com/bunnypro/querying-polymorphic](https://github.com/bunnypro/querying-polymorphic)

just migrate and use DummySeeder class for seeding.
i didn't write any unit testing, but i wrote a route in web route (web.php) for testing, just serve and access /?search=<your search>

**Comment by Dylan-DPC** [comment] 2017-04-13 09:21
Do you get the same issue or not?

**Comment by bunnypro** [comment] 2017-04-13 09:23
yes i do
that's just my temporary solution for this issue.

**Comment by vesteves** [comment] 2017-05-01 02:18
Ppl,
I solve it with  strange way but it's working... I'll try explain:

code:

```
$clientes = Cliente::whereHas('credito',
            function ($query) {
                $query->where('administrador_id', Auth::user()->userable_id);
            })
        ->get();
```
and It's the code to return object to view:

```
return view('agendamentos.lista', [
            'agendamentos' => $agendamentos,
            'clientes' => $clientes->pluck('users.name', 'id'),
            'listaClientes' => $clientes
        ]);
```
The hint and the strange thing on the same is:

`'clientes' => $clientes->pluck('users.name', 'id'),`
If I put this code **BEFORE** send the object `'listaClientes' => $clientes`, It work fine and if i remove it             `'clientes' => $clientes->pluck('users.name', 'id'),`, don't work...
Ps: I dont use `'clientes' => $clientes->pluck('users.name', 'id'),` for nothing in my view.

**Comment by phroggyy** [comment] 2017-08-06 17:14
@themsaid I've thought of a semi-solution after discussing this with another developer. It does have a fairly big caveat, but I still think it's better than nothing... Basically:

Prerequisite:
The user must use `morphMap` _at least_ for the target model (the relation we want to query our `whereHas` on).

Solution:
If the `Relation::morphMap()` is indexed, that is, has the following structure:

```php
[
    User::class,
    Post::class,
    Comment::class,
]
```
We *know* that the `{morphable}_type` is the _name of the related table_. As such, the subquery performed by laravel should be able to use that value straight away for the `select`.

If the `Relation::morphMap()` is not indexed, that is, has a structure like:

```php
[
    'user' => User::class,
    'post' => Post::class,
    'comment' => Comment::class,
]
```

We cannot be sure what the table name is. As such, the solution is... Ugly. We can loop over the morph map, running `(new $model)->getTable()` on each of them. After that, construct a SQL `SWITCH` statement that runs on the `{morphable}_type` column. That's pretty ugly, but it was the only solution I could think of that'd solve it for both scenarios (as long as morph map is present).

**Comment by morningmemo** [comment] 2018-02-12 05:11
@bunnypro your solution is good.
but it is do not support for whereHas in polymorphic whereHas.
so i send to 'pull request' that solution for this problem to that repository.

**Comment by laurencei** [comment] 2018-09-20 01:52
@staudenmeir - does your merged PR fix this issue? Can I close it?

**Closed** 2018-09-20 02:31 UTC
Labels: Action needed

**Comment by staudenmeir** [comment] 2019-06-20 19:35
We are working on a solution for this issue: https://github.com/laravel/ideas/issues/1651

The current [draft](https://github.com/staudenmeir/framework/compare/5.8...where-has-polymorphic) focusses on use cases where the *same* constraint should be applied for all types:

```php
Event::whereHasPolymorphic('eventable', [Post::class, Video::class], function ($query) {
    $query->where('title', 'like', '%'.$search.'%');
});
```

You can also provide a wildcard and let Laravel get the possible types from the database:

```php
Event::whereHasMorph('eventable', '*', function ($query) {
    $query->where('title', 'like', '%'.$search.'%');
});
```

A concern with this approach is that it makes applying *different* constraints more complicated:

```php
Event::where(function ($query) {
    $query->whereHasMorph('eventable', Post::class, function ($query) {
        //
    })->orWhereHasMorph('eventable', Video::class, function ($query) {
        //
    });
});
```

An alternative solution could be an associative array. This would simplify different constraints but complicate cases with the same constraint for multiple types:

```php
Event::whereHasMorph('eventable', [
    Post::class => function ($query) {
        //
    },
    Video::class => function ($query) {
        //
    },
]);
```

What's your option on this? Would you typically use the method with a single or multiple constraints?

**Comment by staudenmeir** [comment] 2019-06-27 14:17
Laravel 5.8.27 will add `whereHasMorph()`: #28928
