### ISSUE TITLE
Laravel 5.6 validator always returns 200 instead of 422 while ajax using. 

### ISSUE THREAD

**Issue by Pashkinz92** [laravel/framework#24276] opened 2018-05-22 12:38 UTC
I made a custom validator like in docs, but I always get a 200 ok even a validator throw errors. No 422, only 200 ok. How can I use ajax and validator for getting a response with error http code?

**Comment by staudenmeir** [comment] 2018-05-22 12:59
Please post the relevant parts of your code.

**Comment by Pashkinz92** [comment] 2018-05-22 13:11
```
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreQuestion extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'email' => 'required',
            'text' => 'required'
        ];
    }

    public function messages()
    {
        return [
            'email.required' => 'Email is empty!',
            'text.required'  => ':-( text is empty',
        ];
    }
}

```

and 
```
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreQuestion;

class QuestionController extends Controller
{
    public function index() {

    }

    public function store(StoreQuestion $request) {

        $user = Auth::user();

        return response()->json(['user' => $user], 200);
    }
}

```

**Comment by laurencei** [comment] 2018-05-22 13:26
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by Pashkinz92** [comment] 2018-05-22 13:29
> issues/bugs with the framework code itself.
I thinks this is a bug. Because in 5.4 all works fine

**Comment by staudenmeir** [comment] 2018-05-22 14:00
It works for me. Does the invalid request reach `return response()->json(['user' => $user], 200);`?

**Comment by Pashkinz92** [comment] 2018-05-22 14:07
I don't even get to this part of code. 
I get an error message, but with status 200. two local machines - the same result

**Closed** 2018-05-22 14:06 UTC

**Comment by Pashkinz92** [comment] 2018-05-22 14:07
![image](https://user-images.githubusercontent.com/4114995/40367668-a0e077d2-5de2-11e8-8e07-6911aee9b77b.png)
![image](https://user-images.githubusercontent.com/4114995/40367686-ab042344-5de2-11e8-970c-67b1f795f4b7.png)

**Comment by Pashkinz92** [comment] 2018-05-22 14:08
Validator works, if empty fields. But status code....always 200

**Comment by arbabi2010** [comment] 2018-12-22 11:54
I have the same problem. before cpanel updated everything work  fine. but after update cpanel . my validation get 200 status to me

**Comment by vfa-quangnx** [comment] 2019-07-26 06:38
I also meet the same problem, I'm in stuck and can't find the solution. This is strange and very bad things for me because of the closest deadline. Anybody can help me please.

**Comment by Pashkinz92** [comment] 2019-07-26 06:47
> I also meet the same problem, I'm in stuck and can't find the solution. This is strange and very bad things for me because of the closest deadline. Anybody can help me please.

Hi! What laravel version do you use?

**Comment by vfa-quangnx** [comment] 2019-07-26 08:54
Hi, I use Laravel 5.5.45
Kindly help me solve this.

**Comment by arbabi2010** [comment] 2019-07-26 08:54
> I also meet the same problem, I'm in stuck and can't find the solution. This is strange and very bad things for me because of the closest deadline. Anybody can help me please.

I change my validate message file and i work fine right now

**Comment by Pashkinz92** [comment] 2019-07-26 10:01
> Hi, I use Laravel 5.5.45
> It's always response with status 200 despite of validation error.

Maybe you will write to me an email?

**Comment by swastin** [comment] 2019-09-09 06:24
### 

> 

- `_**

1.  @@

**_`

**Comment by iraklisg** [comment] 2020-09-17 07:10
Late to the party, but in case someone else encounters this problem, you should make sure you're sending the request with the `Accept: application/json` header, otherwise Laravel >5.6 won't detect that it's an API request, and won't generate the 422 response.

**Comment by techguydev** [comment] 2020-10-08 17:16
> Late to the party, but in case someone else encounters this problem, you should make sure you're sending the request with the `Accept: application/json` header, otherwise Laravel >5.6 won't detect that it's an API request, and won't generate the 422 response.

Thanks a lot it worked for me

**Comment by benndip** [comment] 2020-10-14 20:36
> Late to the party, but in case someone else encounters this problem, you should make sure you're sending the request with the `Accept: application/json` header, otherwise Laravel >5.6 won't detect that it's an API request, and won't generate the 422 response.

Thanks a lot. This worked for me too!

**Comment by avandermeer** [comment] 2020-12-11 16:32
@iraklisg I have an issue which may be related to the fact that >5.6 won't detect it's an API request. What is causing this change? Could you point to some documentation?

**Comment by iraklisg** [comment] 2020-12-14 18:40
@avandermeer could you please provide more context related to your issue?

**Comment by ousid** [comment] 2022-07-16 10:34
Late in here, but if you faced this error in the latest Laravel versions, when you are testing, use `$this->postJson(...)` instead of `$this->post` to send `Accept: application/json` header along with your request.

**Comment by XedinUnknown** [comment] 2023-10-04 11:32
Laravel 10, experiencing the same problem, using `postJson()`.

**Comment by casey977** [comment] 2024-02-22 21:49
Took me about eight hours to identify the cause of this error in my Laravel project. Is this even mentioned in the documentation, that you must send a "Accept: application/json" header?!
