### ISSUE TITLE
[5.3] Forgot password email template change not working.

### ISSUE THREAD

**Issue by atapatel** [laravel/framework#15321] opened 2016-09-07 14:53 UTC
- Laravel Version: 5.3.6
- PHP Version: 7.0.8
- Database Driver & Version:

### Description:
By default Auth functionality which comes with default forgot password flow. in previous version we can easily change the template of forgot password email by changing values in config/auth.php . now in new version 5.3 it is not using those config variable. it is using auth Default template notification::email.blade.php.

**Comment by themsaid** [comment] 2016-09-07 14:57
You can publish this view and edit it as you wish.

Closing since it's not a bug report, but feel free to bing me if you need more details.

**Closed by themsaid** 2016-09-07 14:57 UTC
