### ISSUE TITLE
Getting wrong SQL generated with "!= 0" in statement since v8.81.0 

### ISSUE THREAD

**Issue by martin-pfeiffer-dibooq** [laravel/framework#40757] opened 2022-02-02 10:42 UTC
- Laravel Version: > 8.81
- PHP Version: used > 7.4.16 
- Database Driver & Version: pgsql & postgresql v12-14 

### Description:

Since this commit https://github.com/laravel/framework/commit/a9c50095980e6f24ca23c811fa55752e0f50dd6c 
we get unnecessary "!= 0" in SQL statements. 

### Steps To Reproduce:

In Tinker: 
`App\Models\Occupation::query()->where('real_estate_id',59)->where('date_range', '>>','[2022-01-08 00:00:00,2022-01-09 00:00:00)')->toSql();`

SQL output with >v8.81: 

=> "select * from "occupations" where "real_estate_id" = ? and ("date_range" >> ?) **!= 0** and "occupations"."deleted_at" is null"

SQL output with <v8.81: 

=> "select * from "occupations" where "real_estate_id" = ? and "date_range" >> ? and "occupations"."deleted_at" is null"

### Error:

Illuminate\Database\QueryException with message 'SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean <> integer
LINE 1: ...re "real_estate_id" = $1 and ("date_range" >> $2) **!= 0** and "...

HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. (SQL: select * from "occupations" where "real_estate_id" = 226 and ("date_range" >> [2022-01-08 00:00:00,2022-01-09 00:00:00)) != 0 and "occupations"."deleted_at" is null limit 1)'

Why changes are made on https://github.com/laravel/framework/commit/a9c50095980e6f24ca23c811fa55752e0f50dd6c#r65853324 e.G. ?

**Comment by BrandonSurowiec** [comment] 2022-02-02 14:05
@martin-pfeiffer-dibooq  I know nothing about the differences between PgSQL and PostgresSQL when compared to MySql. Is it normal to open the `date_rangse` argument with a square bracket "[" and then close it with parenthesis ")" `'[2022-01-08 00:00:00,2022-01-09 00:00:00)'` ? Should it close with a square bracket? `'[2022-01-08 00:00:00,2022-01-09 00:00:00]'`

**Comment by martin-pfeiffer-dibooq** [comment] 2022-02-02 14:13
@BrandonSurowiec its not about the date range. Its just about the "!= 0" what is added afterwords. 

This causes an SQL error like shown.

**Comment by BrandonSurowiec** [comment] 2022-02-02 14:37
Seems like it would be a good idea to verify that the error isn't thrown due to your argument though. If that is the cause, then the `!= 0` works, whether you like the syntax or not. Just trying to help verify the bug is actually a bug.

**Closed** 2022-02-03 16:29 UTC
Labels: bug
