### ISSUE TITLE
Strange characters after artisan optimize

### ISSUE THREAD

**Issue by Macsch15** [laravel/framework#14197] opened 2016-07-01 13:24 UTC
Hello,
I have issue on my vagrant box (php7dev), after ```php artisan optimize``` (via composer install/update) I got strange characters on any page (CLI/phpunit too):
![2016-07-01_15-08-11](https://cloud.githubusercontent.com/assets/1592053/16522361/4fb6a3e4-3f95-11e6-8143-68bc976954b4.png)
 
Everything is fine when I remove file:
```
/bootstrap/cache/compiled.php
```

Laravel Framework version 5.2.39
PHP 5.6.16-dev (cli) (built: Oct 22 2015 16:13:30)
Debian GNU/Linux 8.2 (jessie)
Composer version 1.1.3 2016-06-26 15:42:08

Can someone explain this? I can't reproduce this on my shared hosting.
Thanks

**Comment by GrahamCampbell** [comment] 2016-07-01 14:22
What does your compiled file look like?

**Comment by Macsch15** [comment] 2016-07-02 23:08
[compiled.zip](https://github.com/laravel/framework/files/344783/compiled.zip)

**Comment by GrahamCampbell** [comment] 2016-07-03 08:09
Looks fine to me. Did you compile that file on the same server you're running the code on?

**Comment by GrahamCampbell** [comment] 2016-07-03 08:09
What happens if you run optimize with the force flage?

**Comment by Macsch15** [comment] 2016-07-03 11:45
> Did you compile that file on the same server you're running the code on?

Yes.

> What happens if you run optimize with the force flag?

The same results.

**Comment by JoostK** [comment] 2016-07-03 13:06
It has probably something to do with the file encoding. Your `compiled.php` shows the following under OS X:

```sh
$ file -I compiled.php 
# compiled.php: application/octet-stream; charset=binary
```

When ran on a different PHP file I get `text/x-php; charset=us-ascii`.

**Comment by JoostK** [comment] 2016-07-03 18:55
Try creating the file yourself with the contents copied over. I'm not convinced the file is what it should be 😅

**Comment by thecrypticace** [comment] 2016-07-04 01:22
Just a guess but it seems to me that the file is being interpreted as UTF-16BE (BE = Big Endian) and not UTF-8. Though, I'm not sure why. Perhaps there's a setting your php.ini file that's causing this?

Try running `php -i | grep encoding` on your vagrant box and report the details back here. I'm guessing one of the settings is going to say UTF-16.

<img width="463" alt="screen shot 2016-07-03 at 21 20 49" src="https://cloud.githubusercontent.com/assets/614993/16548750/0aa7cb2c-4164-11e6-82f8-343da818e180.png">

**Comment by Macsch15** [comment] 2016-07-04 14:12
```php -i | grep encoding``` output:
![2016-07-04_16-11-09](https://cloud.githubusercontent.com/assets/1592053/16563384/a581fe34-41f9-11e6-93e9-d4c2f7da9277.png)

**Comment by thecrypticace** [comment] 2016-07-04 15:32
That's definitely strange. Not sure what the issue is.

**Comment by Macsch15** [comment] 2016-07-04 15:51
I discover something, when I fire ```artisan optimize``` on PHP 5.5 (PHP 5.5.31-dev (cli) (built: Oct 22 2015 16:24:08)) everything is fine.

compiled.php from PHP 5.6:
[compiled56.zip](https://github.com/laravel/framework/files/346570/compiled56.zip)

and PHP 5.5
[compiled55.zip](https://github.com/laravel/framework/files/346571/compiled55.zip)

![2016-07-04_17-50-56](https://cloud.githubusercontent.com/assets/1592053/16565790/8b813ae6-4207-11e6-8b7a-542fe085b066.png)


PHP 7.0 - the same problem

**Comment by themsaid** [comment] 2016-10-04 12:51
Hello everyone, any updates on this issue? Still facing the problem? is it fixed? Don't seem to be able to regenerate and the thread makes it look like it happens randomly :)

**Comment by Macsch15** [comment] 2016-10-14 13:46
After this update:
```

Updating dependencies (including require-dev)
  - Removing symfony/var-dumper (v3.1.4)
  - Installing symfony/var-dumper (v3.1.5)
    Downloading: 100%

  - Removing symfony/translation (v3.1.4)
  - Installing symfony/translation (v3.1.5)
    Downloading: 100%

  - Removing symfony/routing (v3.1.4)
  - Installing symfony/routing (v3.1.5)
    Loading from cache

  - Removing symfony/process (v3.1.4)
  - Installing symfony/process (v3.1.5)
    Downloading: 100%

  - Removing symfony/http-foundation (v3.1.4)
  - Installing symfony/http-foundation (v3.1.5)
    Downloading: 100%

  - Removing symfony/event-dispatcher (v3.1.4)
  - Installing symfony/event-dispatcher (v3.1.5)
    Loading from cache

  - Removing psr/log (1.0.0)
  - Installing psr/log (1.0.2)
    Downloading: 100%

  - Removing symfony/debug (v3.1.4)
  - Installing symfony/debug (v3.1.5)
    Downloading: 100%

  - Removing symfony/http-kernel (v3.1.4)
  - Installing symfony/http-kernel (v3.1.5)
    Downloading: 100%

  - Removing symfony/finder (v3.1.4)
  - Installing symfony/finder (v3.1.5)
    Downloading: 100%

  - Removing symfony/console (v3.1.4)
  - Installing symfony/console (v3.1.5)
    Downloading: 100%

  - Removing ramsey/uuid (3.5.0)
  - Installing ramsey/uuid (3.5.1)
    Downloading: 100%

  - Removing nikic/php-parser (v2.1.0)
  - Installing nikic/php-parser (v2.1.1)
    Downloading: 100%

  - Removing league/flysystem (1.0.27)
  - Installing league/flysystem (1.0.28)
    Downloading: 100%

  - Removing laravel/framework (v5.3.6)
  - Installing laravel/framework (v5.3.18)
    Downloading: 100%

  - Removing symfony/yaml (v3.1.4)
  - Installing symfony/yaml (v3.1.5)
    Downloading: 100%

  - Removing phpunit/phpunit-mock-objects (3.2.7)
  - Installing phpunit/phpunit-mock-objects (3.4.0)
    Downloading: 100%

  - Removing phpdocumentor/reflection-docblock (3.1.0)
  - Installing phpdocumentor/reflection-docblock (3.1.1)
    Downloading: 100%

  - Removing myclabs/deep-copy (1.5.2)
  - Installing myclabs/deep-copy (1.5.4)
    Downloading: 100%

  - Removing phpunit/phpunit (5.5.4)
  - Installing phpunit/phpunit (5.6.1)
    Downloading: 100%

  - Removing symfony/css-selector (v3.1.4)
  - Installing symfony/css-selector (v3.1.5)
    Downloading: 100%

  - Removing symfony/dom-crawler (v3.1.4)
  - Installing symfony/dom-crawler (v3.1.5)
    Loading from cache
```

This issue is not existing anymore. I still have no idea why.

**Comment by themsaid** [comment] 2016-10-14 13:47
Let's close it then since there were zero progress anyways :) Please feel free to ping me if the problem re-appeared in a 5.3 installation.

**Closed by themsaid** 2016-10-14 13:47 UTC
