### ISSUE TITLE
[5.1] [5.2] queue:listen and queue:work not working on windows

### ISSUE THREAD

**Issue by waylaidwanderer** [laravel/framework#11714] opened 2016-01-06 05:38 UTC
I can't figure out why this is happening. I'm am running `redis-cli monitor` to check for output, and while calling `$this->dispatch(JOB)` works (I can see the job being `RPUSH`ed), neither running `php artisan queue:listen` or `php artisan queue:work` appears to be doing anything in redis (no change in the monitored output).

There is no output for `php artisan queue:work` before it terminates (or for `queue:listen` before I terminate it).

I've tried specifying the connection with `php artisan queue:listen/work redis` but this doesn't help either.

The above description was for redis, but using the database driver has the same issue. It's inserted in the database correctly, but is never processed (`attempts` is always `0`).

I tried upgrading to 5.2 but with the same result. I used `php artisan make:job ClassName --queued` in 5.1 to create the command. In 5.2 I've removed `SelfHandling` from the class as well.

One other thing to note, it works fine when I set `QUEUE_DRIVER=sync` in `.env`. The queue used is `default` (i.e. I didn't specify a different queue).

**Comment by GrahamCampbell** [comment] 2016-01-06 10:35
I can't replicate. I use redis in production, and I'm pretty sure Taylor uses database, and we both have no issues.

**Comment by waylaidwanderer** [comment] 2016-01-06 19:47
Might be worth to note that I just tried it on my Debian 8 VPS (Laravel 5.1) which works, but still does not work on my Windows 10 computer. Is there anything which would prevent the queue from working depending on what OS the script is running from?

**Comment by GrahamCampbell** [comment] 2016-01-06 20:11
That's very likely. The code we have is OS specific. Ping @taylorotwell.

**Comment by GrahamCampbell** [comment] 2016-01-06 20:11
I've updated the description.

**Comment by zho** [comment] 2016-03-01 03:33
![screen shot 2016-03-01 at 10 31 59](https://cloud.githubusercontent.com/assets/316174/13416907/dc59bd3e-df98-11e5-8492-be948697ca57.png)

me too, not working in MAC as well, i use database driver, and the job is not processed... even after i run the command line, the job still there...

**Comment by Xingggg** [comment] 2016-04-14 07:54
I have the same problem.

**Comment by gmatkowski** [comment] 2016-04-28 10:06
Also, same problem

**Comment by aiddroid** [comment] 2016-07-05 05:29
same problem on CentOS 7 x64,job records already added to the `jobs` tables,but queue:listen and queue:work didn't make any output,and the records in `jobs` didn't change too.

**Comment by Taytus** [comment] 2016-07-18 17:20
Same problem. Jobs are added to the jobs table but they are never excecuted

**Comment by brazenvoid** [comment] 2016-07-30 15:59
Same problem. Half of our dev team is on windows.

**Comment by ismailcaakir** [comment] 2016-09-01 23:02
Aynı sorunu bende yaşıyorum. Laravel 5.3 ile tabloya veri ekliyorum fakat o verileri queue:listen ile çalıştıramıyorum.

**Comment by grepollo** [comment] 2016-10-12 07:20
Any updates on this issue, i'm having this problem too. thanks.

**Comment by themsaid** [comment] 2016-10-13 14:15
@grepollo on Windows? Laravel 5.3?

**Comment by Taytus** [comment] 2016-10-13 15:03
Haven't tested on 5.3, I had issues on 5.2

**Comment by TesseractG** [comment] 2016-10-16 20:34
I just ran into the same issue, but I knew for sure it worked before... so I did some digging and found out that the queue:work command does not return ANY errors to the console. In my case I first did not have Redis running and after that there was a problem serializing a model, because a value was not available.

Both errors showed up on the laravel.log, but queue:work never told me anything.

Not sure if this helps anyone, but do check your laravel.log just in case it's crapping out somewhere.

**Comment by huglester** [comment] 2016-10-17 20:00
I do not see errors on queue:work either. that's why I use : queue:listen, for me it shows exceptions, etc. but is all this connected? isn't this another issue @TesseractG ? /cc @themsaid

**Comment by TesseractG** [comment] 2016-10-20 08:21
@huglester I am not sure if it is the same issue at all, I am just saying that I ran into similar symptoms and this is how they were fixed. Perhaps it helps other people.

**Comment by behind-design** [comment] 2016-11-15 21:35
Any idea why this is happening? I'm running into the same problem and database queueing...

**Comment by shadoWalker89** [comment] 2016-11-16 09:05
Having the same problem, when i do `queue:work` or `queue:listen` nothing happens.

Laravel version : 5.3.23
Mysql : 5.6.31
OS: Windows 8.1 64bits

**Comment by Donkfather** [comment] 2016-12-05 14:20
I get this in the log : 
local.ERROR: Predis\Response\ServerException: ERR unknown command 'EVAL' in C:\PROJECTS\hypesquare\vendor\predis\predis\src\Client.php:370

windows 10 here :)

**Comment by lioannou** [comment] 2016-12-12 01:08
@zho - that is not a bug - you must put `queue:work --queue:sendNotification`

**Comment by behind-design** [comment] 2016-12-13 10:25
@lioannou I no longer have the problem with `queue:work`. But I must say that I went from database queuing to SQS.

But you're right, my co-worker had the same problem and doing `queue:restart` and specifying the queue like you said: `queue:work --queue:sendNotification` (for example), worked or so I'm told :)

**Comment by sachinsolanki** [comment] 2017-01-13 10:25
I have same problem my jobs are inserted into job table but never execute by php artisan queue::work or php artisan queue::listen

**Comment by reno1979** [comment] 2017-01-26 10:18
Almost the same here, only on Homestead.

The listen method works, but using the work method causes the jobs not to be started anymore.

**Comment by themsaid** [comment] 2017-03-02 12:11
Can someone confirm the issue still exists in laravel 5.4?

**Comment by lioannou** [comment] 2017-03-02 12:15
@themsaid - for me - running Windows 10, on Homestead v1.0, using both database and redis drivers, it is working for me on Laravel 5.1 -> 5.4 (I've tried all versions).

**Comment by hafeez1042** [comment] 2017-03-19 07:37
Having same issue, 
Laravel version=5.4
QUEUE_DRIVER=beanstalkd
OS = MacOS

**Comment by mrliptontea** [comment] 2017-03-21 23:21
You need to be specific about which queue(s) your worker is going to process.

The default queue is called `default`. If you run `php artisan queue:work` it will **only** process the `default` queue. Laravel does not magically know what queues you want to use. So, if for example, you dispatched a job on the `emails` queue, then make sure to pass `--queue=emails,default` to the worker/listener command.

Although I would agree that the [documentation](https://laravel.com/docs/5.4/queues#queue-priorities) could be clearer on this topic.

**Comment by sachinsolanki** [comment] 2017-03-23 06:18
I think you should be define queue name first then process to queue. 

**$job = (new ProcessPodcast($podcast))->onQueue('email');**

Then check your code within constructor of job if every thing do well then you can add your queue code below in handle function.

Sometime if your code have any error then queue not working.

**Comment by laurencei** [comment] 2017-04-15 21:19
@hafeez1042 - can you please paste your queue config, and also what command you are using to run the queue?

**Comment by wdda** [comment] 2017-05-12 09:01
I did it!

Working example:
`artisan queue:work database --queue=emails`

Required parameter: database and --queue

**Comment by laurencei** [comment] 2017-05-16 23:17
@themsaid - I feel this should/can be closed.

When you read many of the comments in this thread saying theirs is not working - many of them were incorrectly not applying the right queue name to be processed. I count at least 5 of them.

No one is able to provide any config that truly fails despite repeated requests. I've run lots of tests on Windows - and it works fine.

If it was a framework/Windows issue - we've had hundreds of people reporting it by now.

**Comment by ursuleacv** [comment] 2017-05-20 12:42
Having the same problem: 
Laravel 5.4.23
Windows 10 Home
Redis 2.8.17

There is no output for php artisan `queue:work`, or for `queue:listen`

When using `QUEUE_DRIVER=database` everything works fine

.env
```
BROADCAST_DRIVER=redis
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=redis

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
```
in redis queues->default
```
{
  "displayName": "App\\Jobs\\MailMessage",
  "job": "Illuminate\\Queue\\CallQueuedHandler@call",
  "maxTries": null,
  "timeout": null,
  "data": {
    "commandName": "App\\Jobs\\MailMessage",
...
```

**Comment by mrliptontea** [comment] 2017-05-20 23:06
@ursuleacv just to confirm, could you paste the exact command(s) which you run in redis-cli (or whatever you use to get that JSON you provided) to check what's in the queue?

Also, check if it works when you pass the queue name, and try to experiment with different queue names:
`php artisan queue:work redis --queue=default`

**Comment by ursuleacv** [comment] 2017-05-24 17:20
@mrliptontea I am using `Redis Desktop Manager`. I tried with the queue name and it's the same, still not working.

![redis](https://cloud.githubusercontent.com/assets/1458222/26416362/9bdc9e64-4083-11e7-98be-9539af78bf84.png)

**Comment by mrliptontea** [comment] 2017-05-24 18:05
@ursuleacv only just now I have noticed Redis version which you use. Generally, Redis isn't officially supported on Windows, so where you got that actual build might be important.

I've just tried it on [Redis 3.0.504 from MSOpenTech](https://github.com/MSOpenTech/redis/releases), and it all definitely works for me (Windows 10, Laravel 5.4.23).

**Comment by themsaid** [comment] 2017-05-25 15:10
Reading all comments in this thread I find that it's most probably an environment misconfiguration since many people report that it's working or got it to work themselves. For that I'm closing this issue since I don't see a point in keeping it since no laravel core changes would be applied.

I suggest that people visiting this thread later to read all the comments and make sure they applied all the suggestions.

**Closed by themsaid** 2017-05-25 15:10 UTC
Labels: bug

**Comment by mrliptontea** [comment] 2018-02-26 18:36
@mirko77 No errors on these commands will mean that queues you listen to are empty/don't exist, and that is expected. So far nothing proved there is an actual issue with the framework, it's always misconfiguration/misunderstanding.

Please, quadruple check:
- Queue driver you use.
- Queue name(s) you dispatch jobs on.

If you still don't find the cause:
- Trace what's being executed when you run `queue:work` (using a remote debugger or `dd();` in the code).
- Whether you can manually see jobs in your queue driver.

**Comment by mirko77** [comment] 2018-02-26 19:18
@mrliptontea the same exact code and commands run flawlessly on Ubuntu 16.04, just locally on a Mac High Sierra it does not.

While I could chase ghosts and witches for hours, I would just use `sync` when testing locally and live with that.

**Comment by mrliptontea** [comment] 2018-02-26 20:47
But that's the point; it's not the code that's at fault but your environment, dependencies and their configuration, which is why I suggested checking your queue driver.

Maybe try Docker. If you're trying Redis then literally all you need is `docker run -p 6379:6379 redis`.

**Comment by mrliptontea** [comment] 2018-07-04 20:33
@pmochine just like back in February, please check the following:

> * Trace what's being executed when you run queue:work (using a remote debugger or dd(); in the code).
> * Whether you can manually see jobs in your queue driver.

Honestly, I just tested this:

1. Install Laravel 5.2
    ```shell
    git clone https://github.com/laravel/laravel.git laravel52
    cd laravel52
    composer install
    composer require predis/predis
    cp .env.example .env
    php artisan key:generate
    ```
2. Create a test job
    ```shell
    php artisan make:job TestQueue
    ```
3. Edit `app/Console/Commands/Inspire.php` - add inside `handle()`:
    ```php
    dispatch(new \App\Jobs\TestQueue);
    ```
4. Edit app/Jobs/TestQueue.php:- add inside `handle()`:
    ```php
    \Log::info('Hello from the queue');
    ```
5. Run
    ```shell
    docker run --rm -p 6379:6379 -d redis
    php artisan inspire
    php artisan queue:work
    ```
6. Check the log
    ```shell
    tail storage/logs/laravel.log
    ```
    Should show something like
    ```
    [2018-07-04 20:20:20] local.INFO: Hello from the queue
    ```

**Comment by CoderFish8** [comment] 2018-07-21 08:01
In my case php artisan queue:listen/work  not worked while site in maintance mode
https://laravel.com/docs/5.6/configuration#maintenance-mode

**Comment by pmochine** [comment] 2018-07-21 20:39
@CoderFish8 ... it was the same reason... stupid me

**Comment by Thirdwrist** [comment] 2018-09-29 08:01
> If you specified the connection or the queue when you add the job,you should run the listen or work command with connection and --queue,examples here:
> php artisan queue:listen database --queue emails

This worked for me, Thanks!

**Comment by Qh0stM4N** [comment] 2019-02-16 09:06
@themsaid It's not a Bug, but there's something missing.  --queue parameters like optional but the default value is heavily assigned to 'default'.
https://github.com/laravel/framework/blob/5042846eb0bdd0ade2e760015b1e5c57013225d5/src/Illuminate/Queue/DatabaseQueue.php#L50

When people give this optional parameter they intentionally only want certain queues to run. At the same time, it is developing in order of priority. doc: https://laravel.com/docs/5.4/queues#queue-priorities
expected: if a priorty is not specified, first in first out 
happening: run only default queue. Not exist default; people googling 

> laravel queue not working

Neded wildcard support and defalut queue name = "*"
`php artisan queue:work --queue=super,high,*`  1. super 2. hing 3. other... 
`php artisan queue:work`  run All queue

**Comment by edytajordan** [comment] 2020-01-03 16:06
The issue still exists on Windows in Laravel 5.8. Have no problems on MAC.

**Comment by veniseactivation** [comment] 2020-05-14 20:32
> In my case php artisan queue:listen/work not worked while site in maintance mode
> https://laravel.com/docs/5.6/configuration#maintenance-mode

Thank you @CoderFish8 that worked for me like magic after 5 hours of searching the problem was just in the maintenance mode

**Comment by M0nik** [comment] 2020-10-27 05:11
I have the same problem. Wildcard support is really needed. Good solution @Qh0stM4N. The current behavior is not obvious. I use a lot of queues and why specify the name of each queue?

**Comment by helturkey** [comment] 2020-11-02 23:25
> In my case php artisan queue:listen/work not worked while site in maintance mode
> https://laravel.com/docs/5.6/configuration#maintenance-mode

you saved my day, thanks, after more than 3 hours searching for.

**Comment by HoseinHaqiqian** [comment] 2021-04-04 20:20
same issue, no tips helped, also i am not in maintenance mode

**Comment by Qh0stM4N** [comment] 2021-05-04 19:21
> I have the same problem. Wildcard support is really needed. Good solution @Qh0stM4N. The current behavior is not obvious. I use a lot of queues and why specify the name of each queue?

@M0nik Is there still the same problem in newest version of laravel? 
If still same, maybe I can create a PR to end this.

**Comment by donmbelembe** [comment] 2022-01-28 10:26
`php artisan optimize:clear` on laravel 8 solved my issue

**Comment by zohaibcrewlogix** [comment] 2023-01-10 08:03
> If you specified the connection or the queue when you add the job,you should run the listen or work command with connection and --queue,examples here: php artisan queue:listen database --queue emails

Literally saved my day.
