### ISSUE TITLE
[L5] Cronjob out in SimpleMessage fails 

### ISSUE THREAD

**Issue by Jaspur** [laravel/framework#7639] opened 2015-02-27 07:58 UTC
There goes something wrong when trying to mail the Scheduled output:
![schermafdruk 2015-02-27 08 55 00](https://cloud.githubusercontent.com/assets/4254854/6409064/612c02ea-be5e-11e4-9683-ec2a758a9995.png)

```
$schedule
  ->command('foo:bar')
  ->dailyAt('01:00')
  ->sendOutputTo(storage_path().'/logs/cron.log')
  ->emailOutputTo('backup@mail.com'); 
```

Output is send to the log-file.

@taylorotwell

**Comment by Jaspur** [comment] 2015-03-08 17:08
http://stackoverflow.com/questions/28737452/laravel-5-scheduler-cronjob-output-to-mail?noredirect=1#comment46082228_28737452

**Comment by orrd** [comment] 2015-03-09 05:49
I'm using sendmail to send mail and I'm seeing the same error, so I think the problem is unrelated to the mail service type.

**Comment by dwightwatson** [comment] 2015-03-12 04:27
Unrelated, what handler is producing that stack trace?

**Comment by GrahamCampbell** [comment] 2015-04-11 22:41
Did you ever get this sorted>

**Comment by orrd** [comment] 2015-04-12 00:18
I just did a composer update and the issue appears to have been fixed in a recent update.  (Possibly thanks to the update from SwiftMailer v5.3.1 to v5.4.0?)

**Closed** 2015-04-12 10:16 UTC
