### ISSUE TITLE
Error using receivesBroadcastNotificationsOn

### ISSUE THREAD

**Issue by kiwina** [laravel/framework#17883] opened 2017-02-10 21:53 UTC
- Laravel Version: 5.4.#
- PHP Version: 7.0
- Database Driver & Version: 5.7

### Description:
Error using receivesBroadcastNotificationsOn()
### Steps To Reproduce:
i tried adding to the user model
`    public function receivesBroadcastNotificationsOn()
    {
        return [
            new PrivateChannel('users.'.$this->id),
        ];
    }`
then a simple notifications class

`class NewMessage extends Notification
{
    use Queueable;
    protected $message;
    public function __construct($message)
    {
        $this->message = $message;
    }
    public function via($notifiable)
    {
        return ['broadcast'];
    }
    public function toBroadcast($notifiable)
    {
        return new BroadcastMessage([
            'message' => $this->message
        ]);
    }
}
`
then fire the event
`
$user = User::find(1);
$message = 'test message';
        $user->notify(new NewMessage($message));
`
and i get
`
ErrorException: Array to string conversion in vendor\laravel\framework\src\Illuminate\Broadcasting\PrivateChannel.php:17
`

but if i use
`public function receivesBroadcastNotificationsOn()
    {
        return'users.'. $this->id
    }`
all works as expected
not sure whats the right behavior

**Comment by marcoocram** [comment] 2017-02-14 08:52
i have the same issue and i got the same solution but.....i think that this adds an extra "private" isn't it?

in your case the channel will be 'private-private-users.{id}' right?

**Comment by alexsoft** [comment] 2017-02-14 19:23
@kiwina @marcoocram If exists on model, method `receivesBroadcastNotificationsOn` is only called in `Illuminate\Notifications\Events\BroadcastNotificationCreated@channelName` method. And `channelName` returns `string`. So I guess you cannot specify an array of channels, only one channel

**Comment by themsaid** [comment] 2017-02-15 13:58
+1 @alexsoft answer. Closing then. Feel free to ping me though.

**Closed by themsaid** 2017-02-15 13:58 UTC

**Comment by andysoa** [comment] 2017-03-16 17:19
I don't know why this has been closed, it's a bug that is worth fixing.

**Comment by alexsoft** [comment] 2017-03-16 22:40
@andysoa it is not a bug. 
But I have to admit that it is inconsistent with docs. 
@themsaid, would you agree?
https://laravel.com/docs/5.4/notifications#listening-for-notifications

**Comment by jamesgraham** [comment] 2017-05-15 13:45
Can the documentation get fixed please? Or the framework be implemented as the docs describe?
