### ISSUE TITLE
Eloquent Modal Automatically appenging letter "s" in table name.

### ISSUE THREAD

**Issue by rakshitbharat** [laravel/framework#30755] opened 2019-12-04 12:26 UTC
- Laravel Version: 5 to 6.
- PHP Version: 7^
- Database Driver & Version: MySQL

### Description:
Eloquent Modal Automatically appending letter "s" in table name.

### Steps To Reproduce:
Eloquent have feature in which you can go ahead with just creating Class file extending Eloquent Modal Class where you don't have to write table name (Default from class name to lowercase and snack case separated), primary key (Default id) and guarded variable (Default id).

When you just remove table name you will find error that eloquent is adding extra s at last of the table name which is created automatically from class name now what happens that this feature becomes useless with tables which don't have s at last of its name.

![photo_2019-12-04_17-49-02](https://user-images.githubusercontent.com/17176729/70142209-bbe27800-16be-11ea-8842-652574dab74a.jpg)
![photo_2019-12-04_17-49-06](https://user-images.githubusercontent.com/17176729/70142212-bbe27800-16be-11ea-934e-24f6a641f1a0.jpg)

**Comment by kmd1992** [comment] 2019-12-04 12:31
Bug confirmed by me.

**Comment by 36864** [comment] 2019-12-04 12:44
This is a feature, not a bug. https://laravel.com/docs/6.x/eloquent#eloquent-model-conventions

You can override the table name by setting a `public $table` property in your models.

**Comment by rakshitbharat** [comment] 2019-12-04 13:42
> This is a feature, not a bug. https://laravel.com/docs/6.x/eloquent#eloquent-model-conventions
> 
> You can override the table name by setting a `public $table` property in your models.

please completely read my comment i better known its a feature i think you don't know that eloquent can predict the name by class name and that prediction feature have a big in which prediction of table name gets extra "s" at last which is not useful for tablet which are not ending which letter "s".

**Comment by 36864** [comment] 2019-12-04 14:00
You have not posted any actual code, so it is difficult to tell what your actual problem is.

From the exception message, I assume your model's class name is InquiryLead

I also assume that you created this class by calling `php artisan make:model InquiryLead -m` to generate a migration file. The migration file should have created a table called `inquiry_leads`. The `InquryLead` model will by default look for that table, `inquiry_leads` as demonstrated by the exception message.

Which part of this process went wrong for you?

>When you just remove table name you will find error 

I don't understand what you're trying to tell us here. Where did you remove the table name from? Why did you expect things to still work after removing the table name?

**Comment by martinbean** [comment] 2019-12-04 14:22
@rakshitbharat Not a bug. If you have an `InquiryLead` model, then Eloquent by default will look in an `enquiry_leads` table.

**Comment by rakshitbharat** [comment] 2019-12-04 15:32
> @rakshitbharat Not a bug. If you have an `InquiryLead` model, then Eloquent by default will look in an `enquiry_leads` table.

do you think that it is good practice to add extra s after table name ?
I mean why people are not understand my point !
okay lets move ahead tell me why you think that extra s is a good practice to automatically appended ? please answer with a strong reason.

WHY extra S ???

**Comment by rakshitbharat** [comment] 2019-12-04 15:34
> You have not posted any actual code, so it is difficult to tell what your actual problem is.
> 
> From the exception message, I assume your model's class name is InquiryLead
> 
> I also assume that you created this class by calling `php artisan make:model InquiryLead -m` to generate a migration file. The migration file should have created a table called `inquiry_leads`. The `InquryLead` model will by default look for that table, `inquiry_leads` as demonstrated by the exception message.
> 
> Which part of this process went wrong for you?
> 
> > When you just remove table name you will find error
> 
> I don't understand what you're trying to tell us here. Where did you remove the table name from? Why did you expect things to still work after removing the table name?

then why extra s ????
why extra s ???
tell me with strong reason . . .

**Comment by rakshitbharat** [comment] 2019-12-04 15:36
assume i have a table which have name quotation then why i want extra s at end ?
i think laravel community think that every table name should be with plural form and in this world know one should write table name with singular form.

**Comment by rojtjo** [comment] 2019-12-04 15:38
It's just a convention which has been there for years. If you don't like it, just define the `$table` property on your model and set it manually.

Changing it now would only cause everyone's application to break.

**Comment by 36864** [comment] 2019-12-04 15:46
By convention, table names in laravel applications are the pluralized form of the corresponding model. I think of it as "This model represents a `Thing`. The table contains many `things`.

If you have a model `InquiryLead`, your table contains multiple `inquiry_leads`.

It is worth noting that it doesn't just "add an s", it pluralizes the name. The `Inquiry` would be kept in a table names `inquiries`.

>assume i have a table which have name quotation then why i want extra s at end ?

If you are using laravel with an existing database, you can continue to use same table names by simply setting the `$table` property on the models. This is all explained in the documentation that I linked. 

If you are starting a project from scratch, and using laravel's migrations, you won't even need to worry about table names in 90% of cases.

Please read the documentation before using a framework.

**Comment by joshuadegier** [comment] 2019-12-04 15:46
They should add Giphy's to Github for these kind of threads.

**Comment by browner12** [comment] 2019-12-04 15:46
😮 🍿 🍿 🍿

**Comment by rakshitbharat** [comment] 2019-12-04 16:38
> By convention, table names in laravel applications are the pluralized form of the corresponding model. I think of it as "This model represents a `Thing`. The table contains many `things`.
> 
> If you have a model `InquiryLead`, your table contains multiple `inquiry_leads`.
> 
> It is worth noting that it doesn't just "add an s", it pluralizes the name. The `Inquiry` would be kept in a table names `inquiries`.
> 
> > assume i have a table which have name quotation then why i want extra s at end ?
> 
> If you are using laravel with an existing database, you can continue to use same table names by simply setting the `$table` property on the models. This is all explained in the documentation that I linked.
> 
> If you are starting a project from scratch, and using laravel's migrations, you won't even need to worry about table names in 90% of cases.
> 
> Please read the documentation before using a framework.

why you want to add extra code to tell which table is it if you eloquent can predict it from its class name ?
tell me deep from your heart if you have 100 table and model of it then you don't think that adding extra 100 lines to tell which table is good ???
answer with a strong reason.
don't worry i have already done a supreme RND before opening this issue , i have strong reasons to answer any questions.

people here should stop commenting on this and find way to solve this extra "s" issue.

ignoring this type of issues will make freshers more difficult to understand what to consider right and what is wrong.

**Comment by rakshitbharat** [comment] 2019-12-04 16:42
> It's just a convention which has been there for years. If you don't like it, just define the `$table` property on your model and set it manually.
> 
> Changing it now would only cause everyone's application to break.

this comment is write i can understand.
but we can add configuration option to remove extra s in configuration file.
this will be a great solution for extra s.

**Comment by 36864** [comment] 2019-12-04 16:54
>but we can add configuration option to remove extra s in configuration file.
this will be a great solution for extra s.

This already exists. It's the `$table` property you can set on models. 

There is also a `getTable()` method that you can override. If your entire database structure follows a different convention to laravel's, you are free to make a base Model class that overrides the `getTable()` method to use whatever logic you want it to, and make sure all of your models extend that base model. Or you can add a trait to do it.

You keep calling it "extra s" as if that's a random letter that is appended to model names arbitrarily. The "extra s" is there because someone, at some point, decided that table names should be plural and then built an entire framework that builds table names that way.

**Comment by rakshitbharat** [comment] 2019-12-04 17:18
> > but we can add configuration option to remove extra s in configuration file.
> > this will be a great solution for extra s.
> 
> This already exists. It's the `$table` property you can set on models.
> 
> There is also a `getTable()` method that you can override. If your entire database structure follows a different convention to laravel's, you are free to make a base Model class that overrides the `getTable()` method to use whatever logic you want it to, and make sure all of your models extend that base model. Or you can add a trait to do it.
> 
> You keep calling it "extra s" as if that's a random letter that is appended to model names arbitrarily. The "extra s" is there because someone, at some point, decided that table names should be plural and then built an entire framework that builds table names that way.

okay then suggest solution to remove extra s globally.

**Comment by rojtjo** [comment] 2019-12-04 17:21
> > > but we can add configuration option to remove extra s in configuration file.
> > > this will be a great solution for extra s.
> > 
> > 
> > This already exists. It's the `$table` property you can set on models.
> > There is also a `getTable()` method that you can override. If your entire database structure follows a different convention to laravel's, you are free to make a base Model class that overrides the `getTable()` method to use whatever logic you want it to, and make sure all of your models extend that base model. Or you can add a trait to do it.
> > You keep calling it "extra s" as if that's a random letter that is appended to model names arbitrarily. The "extra s" is there because someone, at some point, decided that table names should be plural and then built an entire framework that builds table names that way.
> 
> okay then suggest solution to remove extra s globally.

Create a base model class and overwrite the `getTable()` method on it, then extend it from all your models.

**Comment by rakshitbharat** [comment] 2019-12-04 17:28
> > > > but we can add configuration option to remove extra s in configuration file.
> > > > this will be a great solution for extra s.
> > > 
> > > 
> > > This already exists. It's the `$table` property you can set on models.
> > > There is also a `getTable()` method that you can override. If your entire database structure follows a different convention to laravel's, you are free to make a base Model class that overrides the `getTable()` method to use whatever logic you want it to, and make sure all of your models extend that base model. Or you can add a trait to do it.
> > > You keep calling it "extra s" as if that's a random letter that is appended to model names arbitrarily. The "extra s" is there because someone, at some point, decided that table names should be plural and then built an entire framework that builds table names that way.
> > 
> > 
> > okay then suggest solution to remove extra s globally.
> 
> Create a base model class and overwrite the `getTable()` method on it, then extend it from all your models.

share code here then we will put in main eloquent modal and make it configurable globally so that beginner can understand and use it easily.
answer with strong reason if i am wrong.
please remember this thread will help future laravel artisans (new comers)

**Comment by 36864** [comment] 2019-12-04 17:31
Just to clarify here, are you using laravel to interact with an existing database, or is this a new project where you have created the tables specifically to use with laravel?

**Comment by rojtjo** [comment] 2019-12-04 17:41
> > > > > but we can add configuration option to remove extra s in configuration file.
> > > > > this will be a great solution for extra s.
> > > > 
> > > > 
> > > > This already exists. It's the `$table` property you can set on models.
> > > > There is also a `getTable()` method that you can override. If your entire database structure follows a different convention to laravel's, you are free to make a base Model class that overrides the `getTable()` method to use whatever logic you want it to, and make sure all of your models extend that base model. Or you can add a trait to do it.
> > > > You keep calling it "extra s" as if that's a random letter that is appended to model names arbitrarily. The "extra s" is there because someone, at some point, decided that table names should be plural and then built an entire framework that builds table names that way.
> > > 
> > > 
> > > okay then suggest solution to remove extra s globally.
> > 
> > 
> > Create a base model class and overwrite the `getTable()` method on it, then extend it from all your models.
> 
> share code here then we will put in main eloquent modal and make it configurable globally so that beginner can understand and use it easily.
> answer with strong reason if i am wrong.
> please remember this thread will help future laravel artisans (new comers)

Here is an example on how to achieve what you want:

```php
use Illuminate\Database\Eloquent\Model;

class BaseModel extends Model
{
    public function getTable()
    {
        return $this->table ?? Str::snake(class_basename($this));
    }
}

class FooBar extends BaseModel
{
}

$fooBar = new FooBar();

dump($fooBar->getTable()); // foo_bar
````

I understand that you'd like to see a configuration option for this, but there are many ways to structure a table name. Maybe I want my table names to be all in uppercase without any underscores in it, or maybe I even want an extra `s` at the end.

Where do you draw the line on this?

**Comment by browner12** [comment] 2019-12-04 17:42
OP, I would recommend moving this conversation to the appropriate platform for support questions. 

The issue tracker is for bugs, and it's now clear that this is not a bug.

Here are some good places to start.

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

**Comment by rakshitbharat** [comment] 2019-12-04 18:13
> > > > > > but we can add configuration option to remove extra s in configuration file.
> > > > > > this will be a great solution for extra s.
> > > > > 
> > > > > 
> > > > > This already exists. It's the `$table` property you can set on models.
> > > > > There is also a `getTable()` method that you can override. If your entire database structure follows a different convention to laravel's, you are free to make a base Model class that overrides the `getTable()` method to use whatever logic you want it to, and make sure all of your models extend that base model. Or you can add a trait to do it.
> > > > > You keep calling it "extra s" as if that's a random letter that is appended to model names arbitrarily. The "extra s" is there because someone, at some point, decided that table names should be plural and then built an entire framework that builds table names that way.
> > > > 
> > > > 
> > > > okay then suggest solution to remove extra s globally.
> > > 
> > > 
> > > Create a base model class and overwrite the `getTable()` method on it, then extend it from all your models.
> > 
> > 
> > share code here then we will put in main eloquent modal and make it configurable globally so that beginner can understand and use it easily.
> > answer with strong reason if i am wrong.
> > please remember this thread will help future laravel artisans (new comers)
> 
> Here is an example on how to achieve what you want:
> 
> ```
> use Illuminate\Database\Eloquent\Model;
> 
> class BaseModel extends Model
> {
>     public function getTable()
>     {
>         return $this->table ?? Str::snake(class_basename($this));
>     }
> }
> 
> class FooBar extends BaseModel
> {
> }
> 
> $fooBar = new FooBar();
> 
> dump($fooBar->getTable()); // foo_bar
> ```
> 
> I understand that you'd like to see a configuration option for this, but there are many ways to structure a table name. Maybe I want my table names to be all in uppercase without any underscores in it, or maybe I even want an extra `s` at the end.
> 
> Where do you draw the line on this?

this reply is matching what i want to tell the world, this snippet will definitely help others to overcome this problem in future i agree with this.

One can make global modal and extend it instead eloquent.

**Comment by rakshitbharat** [comment] 2019-12-04 18:15
> OP, I would recommend moving this conversation to the appropriate platform for support questions.
> 
> The issue tracker is for bugs, and it's now clear that this is not a bug.
> 
> Here are some good places to start.
> 
> Laravel Slack (https://larachat.co/)
> Laravel.io Forum (https://laravel.io/forum)
> Laracasts Forum (https://laracasts.com/discuss)
> StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

not needed i have closed the issue, now new comers will definitely find this thread helpful.

Thanks all . . . .

**Closed** 2019-12-04 18:15 UTC
