### ISSUE TITLE
Guard should implement StatefulGuard

### ISSUE THREAD

**Issue by Deall0c** [laravel/framework#12232] opened 2016-02-10 10:27 UTC
correct me if I'm mistaken, but it seems to me the [Guard](https://laravel.com/api/5.2/Illuminate/Auth/Guard.html) class implements the [Guard](https://laravel.com/api/5.2/Illuminate/Contracts/Auth/Guard.html) contract but it's effective implementation seems to be that of [StatefulGuard](https://laravel.com/api/5.2/Illuminate/Contracts/Auth/StatefulGuard.html). This prevents the StatefulGuard from being instantiated (I don't seem to find it's implementation either).
Is this intentional or is this a small mistake? As I see it, the Guard class could easily implement the StatefulGuard as it extends the Guard interface that the Guard class implements.

**Comment by GrahamCampbell** [comment] 2016-02-12 21:49
Thanks. Feel free to ask on slack and/or send a PR. Our issues aren't a direct contact to the core.

**Comment by Deall0c** [comment] 2016-02-13 11:33
seems there's an issue in the documentation, it still mentions the Guard class in the dev and 5.2 documentation but that class has been renamed to SessionGuard, which does implement the StatefulGuard. That's probably what caused my confusion

**Comment by taylorotwell** [comment] 2016-02-16 21:27
If this is a bug, it needs to be open @GrahamCampbell

**Comment by EliasZ** [comment] 2016-02-19 11:43
Related https://github.com/laravel/framework/issues/11465

**Comment by hasyimibhar** [comment] 2016-02-21 05:43
This is not a bug, since `Illuminate\Auth\SessionGuard` already implements `Illuminate\Contracts\Auth\StatefulGuard` in 5.2. Maybe it should be fixed in 5.1.

**Comment by GrahamCampbell** [comment] 2016-02-21 09:59
I don't think we need to backport the auth changes to 5.1.

**Closed** 2016-02-21 09:58 UTC

**Comment by Deall0c** [comment] 2016-02-21 10:32
So the option to inject interfaces for authentication is simply removed since 5.2? What's the reasoning behind that decision?

**Comment by GrahamCampbell** [comment] 2016-02-21 11:02
It's because there are now multiple instances of the implementation in 5.2, so we can't guess which ones you want.

**Comment by Deall0c** [comment] 2016-02-21 11:04
Shouldn't the system be somehow capable of figuring that out? Usually there's only a session auth and an API auth (I can't think of a scenario where there'd be more than one of each) and then you should be able to inject StatefulGuard for session auth for example.
It'd make it a lot more fluent to use than having to inject a factory as Taylor already suggested.
