### ISSUE TITLE
Policies must now be explicit even with before() method

### ISSUE THREAD

**Issue by nokios** [laravel/framework#21409] opened 2017-09-26 21:42 UTC
- Laravel Version: 5.5.13
- PHP Version: 7.1

### Description:

Policy from Lumen/previous laravel (5.4.*) is not working as expected in the latest 5.5.13 version.  There was a change on `\Illuminate\Auth\Access\Gate::resolvePolicyCallback(...)` that now requires the permission you're checking for to exist on the policy class before it even bothers to attempt the `before()` call.

I was able to get around this by adding a `__call()` method to my Policy class so that this check on line 437 passes.

See: https://github.com/illuminate/auth/commit/cef2657b1eff37af8aface946f4b8b47eff52092#diff-4961f9aec0e370756f4b21e4191b9f69R399

If this change is not a bug and is expected behavior, then the documentation needs to be updated to account for this behavior change.  It really is quite a change.

### Steps To Reproduce:

My AuthServiceProvider:
```php
class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        Issue::class => IssuePolicy::class,
        Letter::class => LetterOptionPolicy::class,
        Magazine::class => OpenPolicy::class,
        MagazineVersion::class => AccountIdMatchesPolicy::class,
        PrintInstance::class => OpenPolicy::class,
        PrintInstanceApprover::class => OpenPolicy::class,
        PrintInstanceStatus::class => OpenPolicy::class,
    ];

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

    }
}
```

My OpenPolicy class looks like such:
```php
class OpenPolicy
{
    public function before()
    {
        return true;
    }

    /**
     * This fixes change from 5.5 which requires the ability you're checking for to exist as a callable method on the policy to even bother
     * with calling 'before'
     *
     * @see https://github.com/illuminate/auth/commit/cef2657b1eff37af8aface946f4b8b47eff52092
     *
     * @param $name
     * @param $arguments
     */
    public function __call($name, $arguments)
    {
        // Do nothing
    }
}
```

**Comment by Dylan-DPC** [comment] 2017-09-26 22:03
Duplicate of #20943  

 From the upgrade guide:

The before Policy Method
The before method of a policy class will not be called if the class doesn't contain a method with name matching the name of the ability being checked.

Also 5.5 isn't guaranteed to be fully compatible with 5.4.

**Comment by nokios** [comment] 2017-09-26 22:08
Thanks for the quick response, @Dylan-DPC . I understand they're not guaranteed.  I searched open issues and did not see one but obviously I did not search hard enough.

As to the upgrade guide, another incident where I did not search well enough for it.  Thanks.

I'll close.

**Closed** 2017-09-26 22:09 UTC

**Comment by Dylan-DPC** [comment] 2017-09-26 22:10
No issues mate. Next time search in closed issues as well :+1:

**Comment by Kyslik** [comment] 2017-09-26 23:31
Is there a discussion thread where this was decided?
