### ISSUE TITLE
Change on route binding logic breaks test

### ISSUE THREAD

**Issue by khalyomede** [laravel/framework#42608] opened 2022-06-01 17:17 UTC
- Laravel Version: 9.15.0
- PHP Version: 8.1.5
- Database Driver & Version: MySQL 8.0

### Description:

One of my test passes on 9.14.1, fails on 9.15.0, I think this comes from the changes on these files

- src/Illuminate/Routing/RouteUri.php
- src/Illuminate/Routing/Route.php
- src/Illuminate/Routing/ImplicitRouteBinding.php

<details>
    <summary>The error stack trace is:</summary>

```
ErrorException: Undefined array key 1 in /home/www-data/vendor/laravel/framework/src/Illuminate/Routing/Route.php:542
  Stack trace:
  #0 /home/www-data/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
  #1 /home/www-data/vendor/laravel/framework/src/Illuminate/Routing/Route.php(542): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
  #2 /home/www-data/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php(482): Illuminate\Routing\Route->bindingFieldFor()
  #3 [internal function]: Illuminate\Routing\UrlGenerator->Illuminate\Routing\{closure}()
  #4 /home/www-data/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(558): array_map()
  #5 /home/www-data/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(723): Illuminate\Support\Arr::map()
  #6 /home/www-data/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php(485): Illuminate\Support\Collection->map()
  #7 /home/www-data/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php(463): Illuminate\Routing\UrlGenerator->toRoute()
  #8 /home/www-data/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(739): Illuminate\Routing\UrlGenerator->route()
  #9 /home/www-data/storage/framework/views/927bb105fa5e8ebb9f587d639c364b46cdc7e807.php(48): route()
  #10 /home/www-data/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('...')
  #11 /home/www-data/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
  #12 /home/www-data/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
  #13 /home/www-data/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
  #14 /home/www-data/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
  #15 /home/www-data/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View->getContents()
  #16 /home/www-data/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
  #17 /home/www-data/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\View\View->render()
  #18 /home/www-data/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response->setContent()
  #19 /home/www-data/vendor/laravel/framework/src/Illuminate/Routing/Router.php(833): Illuminate\Http\Response->__construct()
  #20 /home/www-data/vendor/laravel/framework/src/Illuminate/Routing/Router.php(802): Illuminate\Routing\Router::toResponse()
  #21 /home/www-data/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Router->prepareResponse()
  #22 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
  #23 /home/www-data/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #24 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Auth\Middleware\Authorize->handle()
  #25 /home/www-data/vendor/laravel/framework/src/Illuminate/Auth/Middleware/EnsureEmailIsVerified.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #26 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Auth\Middleware\EnsureEmailIsVerified->handle()
  #27 /home/www-data/app/Http/Middleware/NoPageCache.php(17): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #28 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\Http\Middleware\NoPageCache->handle()
  #29 /home/www-data/app/Http/Middleware/SetLocale.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #30 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\Http\Middleware\SetLocale->handle()
  #31 /home/www-data/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #32 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
  #33 /home/www-data/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #34 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
  #35 /home/www-data/app/Http/Middleware/ThrottleWebRequests.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #36 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\Http\Middleware\ThrottleWebRequests->handle()
  #37 /home/www-data/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #38 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\AuthenticateSession->handle()
  #39 /home/www-data/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #40 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Auth\Middleware\Authenticate->handle()
  #41 /home/www-data/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #42 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
  #43 /home/www-data/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #44 /home/www-data/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
  #45 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
  #46 /home/www-data/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #47 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
  #48 /home/www-data/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #49 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
  #50 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #51 /home/www-data/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then()
  #52 /home/www-data/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router->runRouteWithinStack()
  #53 /home/www-data/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router->runRoute()
  #54 /home/www-data/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router->dispatchToRoute()
  #55 /home/www-data/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch()
  #56 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
  #57 /home/www-data/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestIpMiddleware.php(45): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #58 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Sentry\Laravel\Http\SetRequestIpMiddleware->handle()
  #59 /home/www-data/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestMiddleware.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #60 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Sentry\Laravel\Http\SetRequestMiddleware->handle()
  #61 /home/www-data/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #62 /home/www-data/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
  #63 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
  #64 /home/www-data/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #65 /home/www-data/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
  #66 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
  #67 /home/www-data/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #68 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
  #69 /home/www-data/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #70 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
  #71 /home/www-data/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #72 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle()
  #73 /home/www-data/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #74 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
  #75 /home/www-data/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
  #76 /home/www-data/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
  #77 /home/www-data/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
  #78 /home/www-data/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(526): Illuminate\Foundation\Http\Kernel->handle()
  #79 /home/www-data/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(293): Illuminate\Foundation\Testing\TestCase->call()
  #80 /home/www-data/tests/Feature/Page/MyTest.php(160): Illuminate\Foundation\Testing\TestCase->get()
  #81 /home/www-data/vendor/phpunit/phpunit/src/Framework/TestCase.php(1545): Tests\Feature\Page\MyTest->testExample()
  #82 /home/www-data/vendor/phpunit/phpunit/src/Framework/TestCase.php(1151): PHPUnit\Framework\TestCase->runTest()
  #83 /home/www-data/vendor/phpunit/phpunit/src/Framework/TestResult.php(726): PHPUnit\Framework\TestCase->runBare()
  #84 /home/www-data/vendor/phpunit/phpunit/src/Framework/TestCase.php(903): PHPUnit\Framework\TestResult->run()
  #85 /home/www-data/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run()
  #86 /home/www-data/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run()
  #87 /home/www-data/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run()
  #88 /home/www-data/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(673): PHPUnit\Framework\TestSuite->run()
  #89 /home/www-data/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run()
  #90 /home/www-data/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run()
  #91 /home/www-data/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
  #92 {main}
```

</details>

It happens on my view, I am calling this:

```php
route('shopping-list.invite-link.index', $shoppingList)
```

These two models use a trait (`Sluggable`, see https://github.com/khalyomede/laravel-eloquent-uuid-slug) which by default change the key to use to `slug`, so the route should look like this:

```
/shopping-list/5f6dfh5/invite-link
```

But in the error it seems like the key "1" (the primary key id) is used instead (hence the error trying to access index 1). Hope it can help figuring what's wrong.

### Steps To Reproduce:

The project is not open source, but I can give you a read only access if you want to reproduce the error by running tests on your side.

**Comment by ksassnowski** [comment] 2022-06-01 23:09
I believe this is a duplicate of #42605 which as mentioned should be fixed by #42606.

**Comment by khalyomede** [comment] 2022-06-02 06:35
Thanks for the effort you put to quickly fix this issue. Is there a way for me to test the fix before you publish it the next tag? Should I require "laravel/framework:master"?

**Comment by ksassnowski** [comment] 2022-06-02 07:19
You can test it by requiring `laravel/framework: 9.x-dev`

**Comment by driesvints** [comment] 2022-06-02 07:33
Fixed on 9.x, we'll do a hotfix as soon as possible. Thanks

**Closed by driesvints** 2022-06-02 07:33 UTC

**Comment by khalyomede** [comment] 2022-06-02 16:54
I just required 9.x-dev (c5c97e4) and it successfuly fixed my failing test, thanks again to everyone involved!
