### ISSUE TITLE
Eloquent model terrible bug (Delete all table rows!)

### ISSUE THREAD

**Issue by ahmadazimi** [laravel/framework#12038] opened 2016-01-27 07:07 UTC
Hi there,

Last day I found a terrible bug (I guess) in Laravel Eloquent model which cause loosing all of my data!

Imagine you have a model called `Invoice`, and you want to `forceDelete` one of its records.

If you get an instance of `Invoice` and save it in a variable called `$invoice`, then you `forceDelete` that instance, and somewhere later, you make an update to that instance, Eloquent execute that update on all of your model rows!!!

``` php
$invoice = Invoice::find(541);
$invoice->forceDelete();

//... somewhere later

// These lines of code cause all rows in Invoice table updated with 'status'=>'failed'
$invoice->update([
    'status' => 'failed',
]);
```

So, Is this really a bug?

**Comment by crynobone** [comment] 2016-01-27 07:11
Looks more like a usage bug to me. Why would you still want to update a deleted record?

**Comment by crynobone** [comment] 2016-01-27 07:13
When you run `delete()` or `forceDelete()` it would change the `Invoice::$exists` value to `false`, and then when you attempt to run `update()` it would run the update on all the records because of the `Invoice::$exists` value.

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L1478-L1513

**Comment by GrahamCampbell** [comment] 2016-01-27 08:24
This is indeed just a bug in your code.

**Comment by theduke** [comment] 2018-01-20 10:51
To me, this is clearly a bug in Eloquent.

It is very dangerous behaviour IMO.

**Comment by duxthefux** [comment] 2018-01-20 11:07
I'm totally with @theduke and @ahmadazimi . Just this week this behaviour caused soft deleting all our accounts (5000+) in a heavily used system.

```
$invoice = Account::find(541);
$invoice->update([
    'deleted' => 1
]);
```

This updates all records in the table.

**Comment by mfn** [comment] 2018-01-20 15:08
@duxthefux I just tested this and I **cannot** reproduce this with 5.5.31. It only updated the record in question.

**Comment by ahmadazimi** [comment] 2018-01-21 06:21
@GrahamCampbell I think this is so better to **reopen** this issue ;-)

**Comment by GuidoHendriks** [comment] 2018-01-21 09:34
@ahmadazimi What version of Laravel are you using? The issue template is there for a reason.

**Comment by ahmadazimi** [comment] 2018-01-21 13:42
@GuidoHendriks 
5.3.30

**Comment by duxthefux** [comment] 2018-01-21 13:47
@mfn 
You need to use a scope for that. Check that out:
```
# Account.php model
   public function scopeSoftDelete(Builder $query)
    {
        return $query->update(array("c_deleted" => 1));
    }
```


```
Psy Shell v0.8.17 (PHP 7.1.11 — cli) by Justin Hileman
>>> $account = Account::find(63)
[!] Aliasing 'Account' to 'ready2order\Database\Model\Account' for this Tinker session.
=> ready2order\Database\Model\Account {#1215
     c_id: "63"
   }
>>> $account->SoftDelete()
=> 4
```

**Comment by GuidoHendriks** [comment] 2018-01-21 13:51
Can’t reproduce it. Based on the code I’d say it’s impossible that it does anything when calling `update` after it’s been deleted. It will immediately return false if it doesn’t exist.

**Comment by a-komarev** [comment] 2018-01-21 14:20
The best case for guys who found this bug will be create repository on github where this issue will be in affect or create unit tests which cover this case.

**Comment by GuidoHendriks** [comment] 2018-01-21 14:54
So this is an issue with soft deleting? The original issue doesn’t mention that at all.

**Comment by duxthefux** [comment] 2018-01-21 15:16
@GuidoHendriks  no in my case it has nothing to do with soft deletes...the `->SoftDelete()` is just a `scope*`-magic-laravel-method and the model does not use the `SoftDeletes`-trait.

I'll make tests for that as suggested.

**Closed** 2018-04-08 15:40 UTC
