### ISSUE TITLE
Paginate method doesn't work if key contains array notation

### ISSUE THREAD

**Issue by eithed** [laravel/framework#20624] opened 2017-08-18 10:55 UTC
- Laravel Version: 5.4
- PHP Version: 7.1

### Description:

If pagination key is of array notation (ie. `page[published]`, `page[unpublished]`) when on `?page[published]=5` the value is not taken into consideration (it still displays first page)

### Steps To Reproduce:

1. Paginate given dataset using `paginate(10, ['*'], 'page[published]')`
2. Display given dataset on view using `links()`
3. Go to one of the urls generated by the pagination

**Comment by rgehan** [comment] 2017-08-18 22:01
I'm quite sure it wasn't designed with array notation in mind. Have a look at the page resolver code:

https://github.com/laravel/framework/blob/78b3fe6bdc6d8219c4b6aca5a160e27c9e65b3d8/src/Illuminate/Pagination/PaginationServiceProvider.php#L40-L48

It will look for a parameter called `page[published]` in the request, but the parameter has been parsed into an array.

In your case, the input is `['page' => ['published' => 123]]` while you'd need `['page[published]' => 123]` for it to work.

The issue is fixable, and I'd be happy for it to be my first contribution, but I'm not sure it is really necessary.

**Comment by eithed** [comment] 2017-08-18 22:12
The key can be as `page-published` and `page-unpublished` so while yes, there're workarounds for it, it lacks certain... elegance (and array notation is useful altogether, while indeed not being necessary). Either way, a note in the documentation would suffice that such notation is not supported.

**Comment by rgehan** [comment] 2017-08-18 23:13
I've fiddled with the page resolver and added support for array-noted page names.

https://github.com/rgehan/framework/blob/8b32d8e7842a9a8eff45214a0e8fafabc4d65557/src/Illuminate/Pagination/PaginationServiceProvider.php#L41-L47

I'd very much like to test this method, since it is now a bit more complicated, but I have absolutely no clue where to start.

**Comment by n7olkachev** [comment] 2017-08-20 12:15
`input` method on request accepts dot notation, so it should work with `page.published`

**Comment by rgehan** [comment] 2017-08-20 16:00
My PR was closed by Taylor; as I suspected, there are no plans to support this kind of notation

**Comment by n7olkachev** [comment] 2017-08-21 08:37
Dot notation is standard in Laravel for a long time, so there is just no need for other notations.

**Comment by lindyhopchris** [comment] 2017-08-21 09:31
You can override the page resolver using `AbstractPaginator::currentPageResolver()`, then add in support yourself. That would at least means you can support it in your own application even if it is not to be supported in the framework.

**Comment by n7olkachev** [comment] 2017-08-21 09:35
In which case dot notation doesn't work? As I understand, it should work for page resolving.
For rendering, you can use `setPageName` with array notation before using `links` method.

**Comment by eithed** [comment] 2017-08-21 09:39
`->paginate(10, ['*'], 'page.published')` produces `?page.published=2` links. Trying to go to given link doesn't advance the pagination. After proceeding to given page, hovering on the link gives me `?page_published=2&page.published=2`. I guess there's some escaping going on.

**Comment by n7olkachev** [comment] 2017-08-21 09:42
Try `->setPageName('page[published]')` after `->paginate()`

**Comment by eithed** [comment] 2017-08-21 09:45
I'm confused - I thought that third parameter in `paginate` method did just that.

Either way - nope, the pagination doesn't advance. After proceeding to the page, and hovering on the link it gives me: `?page%5Bpublished%5D=2&page%5Bpublished%5D=2`

**Comment by n7olkachev** [comment] 2017-08-21 09:54
Yep, you use dot notation in `paginate` for correct page resolving. After that, you use `setPageName` for generating correct link.
`page%5Bpublished%5D=2` will work, don't be afraid of `%5B'.

**Comment by rgehan** [comment] 2017-08-21 09:55
There seems to be escaping yes, someone bumped into the same issue with cookies.

It seems like replacing dots by underscore in incoming variables is [standard PHP behavior](php.net/variables.external#language.variables.external.dot-in-names).

The issue in question: #16167

**Comment by eithed** [comment] 2017-08-21 09:59
@n7olkachev I'm sorry but I don't understand (or we don't understand each other).

Doing `[dataset]->paginate(10, ['*'], 'page[published]')->setPageName('page[published]')` retains the same behaviour (escaped links, duplicated links: `?page%5Bpublished%5D=2&page%5Bpublished%5D=2`  and pagination not respecting passed value).

**Comment by n7olkachev** [comment] 2017-08-21 10:11
Use `page.published` in `paginate` method and `page[published]` in `setPageName`.

**Comment by eithed** [comment] 2017-08-21 10:23
Thank you! That indeed does the trick.

Can you by any chance point me to where I can read about this (as why does that work)? Looking at the `paginate` method third argument is `pageName` and then is passed to paginator, so doing `setPageName` shouldn't do anything (unless there's trickery in `resolveCurrentPage`)

**Comment by n7olkachev** [comment] 2017-08-21 10:31
You pass `page.published` to `paginate` method. `PageResolver` will use it in `input` method on `request` to retrieve current page. `input` method is working with dot notation, that is why we pass `page.published` here.
So, we created `Paginator` with `page.published` `pageName`. If we will use `links` method on such paginator, it creates smth like `page.published=2` which is not what we want. So, we change its name to `page[published]` for correct link generation.
Does it make sense now? :)

**Comment by eithed** [comment] 2017-08-21 10:43
Aaah - yup, thank you very much! It works, because Laravel will use dot notation and `[]` notation interchangeably when retrieving from request; it will only in this scenario though, and indeed the matter was with display, not retrieval.

**Comment by n7olkachev** [comment] 2017-08-21 11:42
Yes, `page[published]` isn't working in `paginate` method because `input` method on `request` expects only dot notation.

**Comment by themsaid** [comment] 2017-08-21 15:01
Closing since there are no plans in supporting this for now, please feel free to continue the discussions tho.

**Closed by themsaid** 2017-08-21 15:01 UTC
