### ISSUE TITLE
[Suggest] Disable overloading query

### ISSUE THREAD

**Issue by kocoten1992** [laravel/framework#14989] opened 2016-08-24 04:12 UTC
I come across this sometime, it magiclly do a query when there is a time I don't want to, example:

```
$u = User::first();
$u->profile;
```
There is a profile method on User class:
```
public function profile()
{
    return $this->haveOne(Profile::class);
}
```
Sometime I didn't want it to overloading query it (I do have logical base on that), so my suggest be like:
```
    /**
     * Disable auto overloading query
     * 
     * @var boolean
     */
    protected $overloadingQuery = true; //can set to false if needed

    /**
     * Get a relationship.
     *
     * @param  string  $key
     * @return mixed
     */
    public function getRelationValue($key)
    {
        if ($this->relationLoaded($key)) {
            return $this->relations[$key];
        }

        if (method_exists($this, $key) && $this->overloadingQuery) { //Adding here
            return $this->getRelationshipFromMethod($key);
        }
    }
```
What do you think?

**Comment by fernandobandeira** [comment] 2016-08-24 16:16
So with this you would have the power to load the relation whenever you want and get null if it's not loaded yet. Indeed it's something that we can't do right now but this seems an edge case, yet  maybe we do need to change this.

May I ask you which kind of situation this would be useful?

**Comment by themsaid** [comment] 2016-09-05 21:40
Not sure what could be the use case for this, if you never called `$u->profile` the relationship won't be loaded.

I'm closing this since it's not a bug report, however you may continue the discussion on https://github.com/laravel/internals

**Closed by themsaid** 2016-09-05 21:40 UTC
