### ISSUE TITLE
[L5.6] User model use __construct() and softdelete

### ISSUE THREAD

**Issue by gzai** [laravel/framework#25399] opened 2018-09-01 07:18 UTC
- Laravel Version: 5.6
- PHP Version: 7.1.7
- Database Driver & Version: 10.1.25-MariaDB

### Description:

Model User use softdelete ( row data field deleted_at is not null ) the data not come out
when Model User use softdelete and public function __construct() ( row data field deleted_at is not null ) the data come out 

how to solve model user use function __construct() and softdelete to make data not come out ?

### Steps To Reproduce:

```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;

    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $dates = ['deleted_at'];

}

```
$user = User::get();
print_r( $user ) // data ( deleted ) not come out

```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;

    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $dates = ['deleted_at'];

    public function __construct() {}

}

```
$user = User::get();
print_r( $user ) // data ( deleted ) come out

**Comment by X-Coder264** [comment] 2018-09-01 09:55
Of course you don't get the soft deleted users when you do `User::get();`, that's like the whole point of soft deleting. If you want to get all users, including those that are soft deleted you must call the `withTrashed` method before the `get` method. Everything is clearly documented [here](https://laravel.com/docs/5.6/eloquent#soft-deleting).

The reason you get the soft deleted user in the second example is because you defined a constructor in your model and you didn't call the parent constructor so the `SoftDeletes` trait didn't boot which means that the entire soft deleting functionality doesn't work with that code.

**Comment by gzai** [comment] 2018-09-01 18:02
Okay, It works. Thanks, @X-Coder264 .

```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;

    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $dates = ['deleted_at'];

    public function __construct() {

        parent::__construct();

    }

}
```

**Comment by juancarmo** [comment] 2018-09-03 00:07
this should be closed. Also ... I would kindly suggest to post things like this in the laracasts forum for example. Regards

**Comment by TBlindaruk** [comment] 2018-09-16 10:00
@taylorotwell , @GrahamCampbell , please close this issue, since the problem is fixed;

**Closed** 2018-09-18 00:55 UTC
