### ISSUE TITLE
[Request] UrlRoutable to be used for route model finding

### ISSUE THREAD

**Issue by dwightwatson** [laravel/framework#8771] opened 2015-05-16 01:53 UTC
At the moment, if you attempt to use route model binding it will still only search for a model by it's primary key.

    $router->model('posts' ,'App\Post');

This is still the case if you use `UrlRoutable` to change the route key name of the model.

    class Post extends Model {
        public function getRouteKey() 
        {
            return $this->slug;
        }
    }

You could use a closure to manually bind the model to the route using the slug, but it is a problem the `UrlRoutable` interface is perfect to solve. It should attempt to load a model from it's route key name and value, rather than just it's primary key (if the route key name and value aren't set manually of course, Eloquent already falls back to the primary key).

**Comment by Sladewill** [comment] 2015-05-16 12:42
There is a router bind function for this already that allows a closure.

```php
$router->bind('name', function($id, $route) {  });
```

**Comment by dwightwatson** [comment] 2015-05-16 12:47
I know that exists, I mentioned that in my original post. The thought process is that if you adjust the route key for a model then it's route model binding should automatically match that change.

**Comment by lukasgeiter** [comment] 2015-05-18 08:29
The problem is that you can currently specify an *attribute* to be used for routing (or at least generating URLs). However you can not always use an attribute in a WHERE query since there might be an attribute accessor in use. And loading all models to filter using the actual attribute later would be pretty bad on performance.

**Comment by dwightwatson** [comment] 2015-05-18 11:13
Sure, it's not going to work if you're using attribute accessors. But in the use case that a custom route key is used for a model slug it's generally going to come from a database column. It goes hand-in-hand with the `UrlRoutable` interface.

**Comment by lukasgeiter** [comment] 2015-05-18 11:43
Hmm. Considering that slugs from an attribute accessor haven't ever worked it shouldn't be a problem I guess. I'll probably write a PR soon...

**Comment by lukasgeiter** [comment] 2015-05-25 16:30
I think this can be closed now, as #8863 has been merged.

**Closed** 2015-05-25 16:31 UTC
