### ISSUE TITLE
Create standard/artisan command/magic feature that will automatically add Composer Laravel package service provider to app service providers list

### ISSUE THREAD

**Issue by Lisennk** [laravel/framework#15059] opened 2016-08-26 06:36 UTC
Create standard/artisan command/magic feature or all these things at once to automate laravel packages installation. For example, it can be implemented as artisan command like so:
```
php artisan add vendor-name/package --provider=PackageServiceProviderName
```
This command can connect to composer, install package then look for file with name "PackageServiceProviderName" inside package and add it to `providers[]` `config/app.php`. 

It will be awesome, since package developers will reduce big readme's to one simple command.

**Comment by mpociot** [comment] 2016-08-26 10:25
I'm not sure if such an artisan command would be good. Because people would assume that it installs the package correctly, which in general might be more complicated than just a composer require and adding the service provider.
Like publishing vendor files , migrating, etc.

And when the command is part of the framework, the framework will receive issues because people can't properly install 3rd party tools.

**Comment by Lisennk** [comment] 2016-08-26 11:56
@mpociot standard about it will solve the problem

**Comment by srmklive** [comment] 2016-08-29 07:39
I agree with @mpociot. Having a command structure like the one you mentioned may be problematic. Some packages you may install might have service providers, migrations & vendor files.

One thing may be done is to ask the user to give service provider class name, and inquire about publishing vendor files, running migrations etc OR simply show a message telling user how to add service providers, publishing assets & running migrations etc.

@mpociot What do you think about this?

**Comment by Lisennk** [comment] 2016-08-29 08:13
@srmklive or this command can also run `vendor:publish`

**Comment by themsaid** [comment] 2016-09-05 21:23
Since it's not a bug report I'm going to close the issue, but please feel free to continue discussions in the [Internals Repository](https://github.com/laravel/internals), it was created for such type of discussions.

**Closed by themsaid** 2016-09-05 21:23 UTC
