### ISSUE TITLE
MIME type for uploaded JSON-file always wrong

### ISSUE THREAD

**Issue by JValck** [laravel/framework#23143] opened 2018-02-13 09:12 UTC
- Laravel Version: 5.6.3
- PHP Version: 7.0.22
- Database Driver & Version: MySql

### Description:
When you upload a JSON-file and validate it through the `mimetypes` [rule](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L972), it always returns that the 
MIME type is wrong.

I noticed that the `getClientMimeType()` method returns the correct MIME type, but the `getMimeType` returns `text/plain`. I know that one should not rely on the `getClientMimeType` as it is retrieved from the headers and can be modified easily.

### Steps To Reproduce:
1. Create a basic JSON-file
2. Upload it through a form
3. Validate with rule:
```php
['customFile' => 'required|file|mimetypes:application/json',]
```

**Comment by windqyoung** [comment] 2018-02-13 09:54
json文件就是个普通文本文件吧. 在浏览器里面, 上传的时候, 他也不可能知道这个是json.

**Comment by ItsAndy** [comment] 2018-05-16 16:51
Also doesn't work with 

`['customFile' => 'required|file|mimes:json']`

**Comment by JValck** [comment] 2018-05-18 13:26
@ItsAndy I ended up with creating my own custom validator. As json is plaintext it returns `text/plain`.

**Comment by ItsAndy** [comment] 2018-05-18 13:53
@JValck But the problem is that json should have the mimeType of application/json.  I've been chasing this for a few days now and it's been discussed over at Symphony as well as PHP.  The core problem is that the mime_content_type function uses the file command
`file -b --mime-type`
And that returns text/plain instead of application/json like mimetype would.
The php docs say

> Returns the MIME content type for a file as determined by using information from the magic.mime file. 

You CAN add json to your magic.mime file and that seems to be the only way to go about it if you really need the mime guesser to work right with json files as well as any other formats not returned "correctly".

[Here's a Stack about it.](https://stackoverflow.com/questions/7236191/how-to-create-a-custom-magic-file-database)

**Comment by JValck** [comment] 2018-05-18 14:12
@ItsAndy Thanks for the update! Currently it seems like we have to wait on an update in PHP. But I don't think it will be implemented soon. As I was unable to wait (deadline), I implemented a simple custom validator myself.

**Comment by laurencei** [comment] 2018-10-03 05:36
> Definitely not a laravel issue though. It's more of a php issue if it's even an issue at all.

Thanks - I'll close the issue here. If you feel its Laravel related let us know.

**Closed by laurencei** 2018-10-03 05:36 UTC
