### ISSUE TITLE
Laravel 9 is not working with PHP 8.2.6

### ISSUE THREAD

**Issue by sharif779** [laravel/framework#47032] opened 2023-05-11 10:05 UTC
### Laravel Version

9

### PHP Version

8.2.6

### Description

When I run laravel 9 in PHP 8.2.6 .I am getting following error.

`Call to a member function bindTo() on null {"exception":"[object] (Error(code: 0): Call to a member function bindTo() on null at /var/www/html/project/vendor/laravel/serializable-closure/src/Serializers/Native.php:195)`

### Steps To Reproduce

Just run any laravel command

**Comment by nunomaduro** [comment] 2023-05-11 10:19
I've just run `php artisan list`, on fresh Laravel 9 installation, and it's working on my side:

```
➜ php -v
PHP 8.2.6 (cli) (built: May 10 2023 06:14:09) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.6, Copyright (c), by Zend Technologies
➜ php artisan --version
Laravel Framework 9.52.7
```

Can you give me more information about how to reproduce this issue?

**Comment by sharif779** [comment] 2023-05-11 10:24
this issue showing in log when I try to browse. Can you please check your web is working or not?

**Comment by nunomaduro** [comment] 2023-05-11 10:43
After installing Jetstream, I was able to browse my Laravel application without any problems. I extensively used all the features that rely on the "serializable-closure" packages, including caching routes and dispatching closures as queue jobs. However, I did not encounter any issues while using these features.

Could you kindly provide me with the complete stack trace of the error you are experiencing?

**Comment by sharif779** [comment] 2023-05-11 11:03
Here it is. For your information `sg_load` is sourceguardian loader. I tried without sourceguardian , got same issue.
```
[2023-05-11 11:01:12] local.ERROR: Call to a member function bindTo() on null {"exception":"[object] (Error(code: 0): Call to a member function bindTo() on null at /var/www/html/project/vendor/laravel/serializable-closure/src/Serializers/Native.php:195)
[stacktrace]
#0 [internal function]: Laravel\\SerializableClosure\\Serializers\\Native->__unserialize()
#1 /var/www/html/project/vendor/laravel/serializable-closure/src/Serializers/Signed.php(87): unserialize()
#2 [internal function]: Laravel\\SerializableClosure\\Serializers\\Signed->__unserialize()
#3 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(234): unserialize()
#4 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(208): Illuminate\\Routing\\Route->runCallable()
#5 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#6 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#7 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#9 /var/www/html/project/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#11 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#13 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#14 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#16 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#18 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Pipeline\\Pipeline->then()
#20 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#21 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#22 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#23 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#24 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#25 /var/www/html/project/vendor/genealabs/laravel-caffeine/src/Http/Middleware/LaravelCaffeineDripMiddleware.php(11): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): GeneaLabs\\LaravelCaffeine\\Http\\Middleware\\LaravelCaffeineDripMiddleware->handle()
#27 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#29 /var/www/html/project/vendor/api-ecosystem-for-laravel/dingo-api/src/Http/Middleware/Request.php(109): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dingo\\Api\\Http\\Middleware\\Request->handle()
#31 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#33 /var/www/html/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#34 /var/www/html/project/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#35 /var/www/html/project/public/index.php(2): sg_load()
#36 {main}

```

**Comment by nunomaduro** [comment] 2023-05-11 11:38
It's definitely related to the route caching. If possible, can you share your routes file, and the fullstack trace without the `sourceguardian` loader.

**Comment by nunomaduro** [comment] 2023-05-11 13:39
Closing this issue for now! Once you share more information with us, I will re-open the issue. Thank you!

**Closed by nunomaduro** 2023-05-11 13:39 UTC
Labels: needs more info

**Comment by abhiburk** [comment] 2024-06-11 11:10
I got the same error but for the Jobs

```
10 /home/stackconsole/cmp-app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Modules\\VirtualMachine\\Http\\Controllers\\ImportVMController->import()
#11 /home/stackconsole/cmp-app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#12 /home/stackconsole/cmp-app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#13 /home/stackconsole/cmp-app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#14 /home/stackconsole/cmp-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#15 /home/stackconsole/cmp-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#16 /home/stackconsole/cmp-app/app/Http/Middleware/AccessControlMiddleware.php(35): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/stackconsole/cmp-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\AccessControlMiddleware->handle()
#18 /home/stackconsole/cmp-app/app/Http/Middleware/EnsureTwoFactorAuthentication.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/stackconsole/cmp-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\EnsureTwoFactorAuthentication->handle()
#20 /home/stackconsole/cmp-app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
[2:53](https://stackconsole.slack.com/archives/D04D732AHS5/p1718097781087759)
[2024-06-11 11:20:18] production.ERROR: Call to a member function bindTo() on null {“userId”:“9b1d3aab-5367-46e5-811e-0e0b3e67c9d6",“exception”:“[object] (Error(code: 0): Call to a member function bindTo() on null at /home/stackconsole/cmp-app/vendor/laravel/serializable-closure/src/Serializers/Native.php:195)
[stacktrace]
```

**Comment by crynobone** [comment] 2024-06-11 11:19
We no longer providing support for Laravel 9.

**Comment by abhiburk** [comment] 2024-06-11 11:22
Well, the the version I am using is `"laravel/framework": "^10.0",` and this issue I found is relatable to mine. What could be the possible reasons for the error ?

This comes when I do `Bus::batch($importsJob)->dispatch();`

**Comment by crynobone** [comment] 2024-06-11 11:33
You need to submit new bug report with reproducing repository. This issue was closed due to lack of information and above information isn't enough.
