### ISSUE TITLE
[5.4] Custom Intermediate (Pivot) Models not instantiable

### ISSUE THREAD

**Issue by JuanDMeGon** [laravel/framework#17770] opened 2017-02-05 00:09 UTC
- Laravel Version: 5.4.9
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.16

### Description:
When trying to use a custom intermediate model (a model that extends from `Illuminate\Database\Eloquent\Relations\Pivot`) as a regular model (`Pivot `extends from Model), it fails, because is not able to create an instance.

`Too few arguments to function Illuminate\Database\Eloquent\Relations\Pivot::__construct(), 0 passed`

I checked the commit but did not found anything would help on this: 4439576c9a9da5d6dcf8d4fd3ab4210576450eb6

### Steps To Reproduce:
Create a model that extends from Pivot instead of Model directly:

```
...
use Illuminate\Database\Eloquent\Relations\Pivot;
...
class CustomIntermediate extends Pivot
{
    ......
}
```

Then try to use the model for some specific functions like all(), with(), query(), etc.

```
Route::get('test', function() {
    return CustomIntermediate::all();
});
```

**Comment by GrahamCampbell** [comment] 2017-02-05 01:38
Please post your entire custom class code.

**Comment by JuanDMeGon** [comment] 2017-02-05 02:44
Hello @GrahamCampbell,
I just checked it again on a fresh Laravel project: `composer create-project laravel/laravel testing 5.4`

Then, created a Test model: `php artisan make:model Test`

Modified the Test to extends from pivot:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Relations\Pivot;

class Test extends Pivot
{
    //
}
```

Then on the web.php routes issued this:
 
```
Route::get('/', function () {
    return App\Test::all();
});
```

Then going to my browser obtained this:

`Type error: Argument 1 passed to Illuminate\Database\Eloquent\Relations\Pivot::__construct() must be an instance of Illuminate\Database\Eloquent\Model, none given, called in {somePath}\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php on line 335`

**Comment by arjasco** [comment] 2017-02-05 13:50
Reason for wanting to instantiate a custom pivot model on its own?

My understand is it's for use within a relationship with the `->using()` method on your relationship definition. You may as well extend Model?

**Comment by JuanDMeGon** [comment] 2017-02-05 14:00
If you check the definition of Illuminate\Database\Eloquent\Relations\Pivot it extends from eloquent Model, so in my understanding it still being a regular model. 
The custom pivot model acts, as as you said, like a pivot AND is a model too I should be able to use it directly or to resolve the many to many relationship through it. 
Maybe I am misunderstanding something here  but it does not seem logic for me to use a custom pivot model and not be able to use it as a regular model as well.
Possibly @pstephan1187 can give us some orientation for this?

**Comment by arjasco** [comment] 2017-02-05 14:25
I see your logic, it may extend Model but doesn't mean it completely reflects the same behaviour.

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Relations/Pivot.php#L47

Looks like the Pivot requires a parent model, and this is provided when the relationship builds that pivot here:

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L378

I might be wrong so i would be interested too. I think the idea is so you can define some further logic on your custom pivot model. Eg when updating a property your might want to use a mutator or maybe define some helper methods on that pivot model which you couldn't do before.

**Comment by JuanDMeGon** [comment] 2017-02-05 14:38
Yeah, it is possible that it does not need to reflects the same behaviour but so it should not extends directly from model but from a modified model or similar. 
Let see if someone can clarify this for us. 
Thanks for commenting.

**Comment by dees040** [comment] 2017-02-28 16:47
Is there any progress? Getting this issue as well.

**Comment by JuanDMeGon** [comment] 2017-02-28 18:18
@dees040 Unfortunately not. It seems like a not important issue yet.
I decided to do not use it for now and use the conventional old approach.
Hopefully, later this will be treated.

**Comment by rsdrsd** [comment] 2017-03-13 09:27
I have the same issue and error. The docs aren't really clear about the purpose of the $relation->using('model') functionality.

For example is it possible to do something like this with that functionality:

users
- id
- belongsToMany posts

posts
- id
- belongsToMany users

post_user
- id
- post_id
- user_id
- hasMany roles (post_user_role)

post_user_role
- id
- post_user_id
- role

$user->load('posts.pivot.roles');

That would be awesome, but can't get it to function.

**Comment by pstephan1187** [comment] 2017-03-13 17:51
@rsdrsd you need to load in `post_user_role` field on the pivot table:

    function posts(){
        return $this->belongsToMany(\App\Post::class)->withPivot('post_user_role');
    }

**Comment by minhchu** [comment] 2017-03-23 13:04
I think the document should show a practical example using intermediate table.

**Comment by JuanDMeGon** [comment] 2017-03-23 13:25
You are probably right. I would like to add an example to the documentation, but it seems like it does not work like I think it does, so may is a matter of time.

**Comment by cjaoude** [comment] 2017-04-02 15:58
Guys, agreed, some documentation would be nice, but after toying with it, here's how it works.

Let's say M-M for User and Books. And you're also adding a 'store_id' attribute to the pivot table. How can you get that Store model based on the `store_id`?

```
// User.php

public function books()
{
    return $this->belongsToMany(Book::class)
                ->withPivot('store_id')
                ->using(BookUser::class);
}
```

So now when you hit `$user->books->first()->pivot` you're getting the `BookUser` model. Remember, `$user->books` returns a collection. You want a `Book` from the collection to make use of `BookUser`. (...so above i just used `-first()`)

```
// BookUser.php

public function store()
{
    return $this->belongsTo(Store::class);
}
```

Bingo. Now.... ``$user->books->first()->pivot->store` yields the Store of `store_id`.

So now you might use it for something like this...

```
@foreach ($user->books as $books)
  Store name: {{ $book->pivot->store->name }}
@endforeach
```

**Comment by JuanDMeGon** [comment] 2017-04-02 16:27
Yes, it is the expected behavior here.
In your example, you should be able to use the BookUser model as the pivot, that is good. In fact, when you use the pivot property it returns an instance of BookUser, but when you want to directly create an instance of BookUser instead of go trough the other models, it just fails.

**Comment by cjaoude** [comment] 2017-04-02 17:51
Yes, BookUser can't be instanced directly. Remember it extends Pivot class, not Model.

It's 'intermediary' and we just need to use it that way. It's very useful.

**Comment by JuanDMeGon** [comment] 2017-04-02 18:07
@cjaoude Yes, it is a Pivot class, wich extends from Model.
Check the definition of [here](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Relations/Pivot.php#L8). It extends directly from Model.
If you think about that is the reason why you can obtain an instance when using the pivot property.

I clearly understand that Pivot is like a "special model," but it is extending from Model and should provide the same behavior expected from a regular model. In another case, it should extend from another kind of "Model."

That is, in fact, the main reason for the discussion here.

**Comment by cjaoude** [comment] 2017-04-02 18:58
I understand what you mean. My posts are to answer how to use a It which some people have asked about

**Comment by JuanDMeGon** [comment] 2017-04-02 19:05
Yes, you are right. Surely that will be very helpful for all.

💯 :)

**Comment by DiakosavvasN** [comment] 2017-04-05 18:13
Hello guys, I've tried on @cjaoude  example, and helped me understand the logic of this problem. 
In my case, I need a hasMany method on my pivot Model. 

Instead of,  
`public function store() { return $this->belongsTo(Store::class);}` 
I need 
`public function store() { return $this->hasMany(Store::class);}`. 

I've tried to retrieve the collection like this : 
`user->books->first()->pivot->store`

but it doesnt returns anything. Can anyone help me ?

**Comment by DiakosavvasN** [comment] 2017-04-05 18:16
I have, a M-M relationship for Status and Jobs. A status has many Jobs and a Job is splitted into many statuses. Now, I need to retrieve the Status_job_items which belongsTo Status_Job Pivot model. 
How can I, create a custom pivot model with hasMany method in it ?

**Comment by rdpascua** [comment] 2017-04-27 01:56
How how can we eagerload the intermediate table? 

`$foo->with('bar.pivot.baz');` doesn't work since `pivot` relation doesn't exists.

**Comment by DiakosavvasN** [comment] 2017-04-27 05:56
I spend at least one week trying to find that question @rdpascua.
Anyways, after a long efford I tried a threeway pivot and works just fine. I don't know if it helps you.

**Comment by rdpascua** [comment] 2017-04-27 10:45
I've created a concerete class instead of using the pivot :/

Sent from my iPhone

On 27 Apr 2017, at 1:56 PM, DiakosavvasN <notifications@github.com<mailto:notifications@github.com>> wrote:


I spend at least one week trying to find that question @rdpascua<https://github.com/rdpascua>.
Anyways, after a long efford I tried a threeway pivot and works just fine. I don't know if it helps you.

**Comment by dherran** [comment] 2017-06-10 22:35
@Dreambox13@rdpascua can you provide an example of how you solved the problem of eager loading the intermediate table?

**Comment by rdpascua** [comment] 2017-06-11 02:14
i haven't, I just created a new model name based on the relation

Sent from my iPhone

On 11 Jun 2017, at 6:35 AM, Danny Herran <notifications@github.com<mailto:notifications@github.com>> wrote:


@Dreambox13<https://github.com/dreambox13> @rdpascua<https://github.com/rdpascua> can you provide an example of how you solved the problem of eager loading the intermediate table?

**Comment by decadence** [comment] 2017-06-12 07:21
I face similar issue but it's expected behavior because Pivot constructor needs some values indeed. Would be nice if we can use it as normal Model.

**Comment by a-komarev** [comment] 2017-06-12 11:10
Faced same issue recently.

**Comment by dherran** [comment] 2017-06-12 14:00
This proposal solved it for me @decadence @a-komarev :
https://github.com/laravel/internals/issues/175

Read the comments all the way through. It explains the changes required to eager load a pivot model relationships on 5.4.

**Comment by a-komarev** [comment] 2017-06-12 14:21
@dherran Thanks for pointing to the solution.

**Comment by decadence** [comment] 2017-06-12 14:24
@dherran thanks. But would be nice to have this out of box.

**Comment by darkylmnx** [comment] 2017-06-23 10:44
i'm having the same issue, i can't instantiate a pivot model, here's my structure and the use case

posts (belongsToMany tags)
 - id
 - name

tags  (belongsToMany posts)
 - id
 - name

post_tag (pivot)
 - id
 - post_id
 - tag_id
 - votes_count

votable (polymorphic)
 - id
 - votable_id
 - votable_type

and as the tables explain by themselves, you can vote for a **post_tag** just like the **likedin tag recommandation feature**

the api would be something like : **POST** /post-tag/{post_tag}/likes
And inside this something like 

```
$post_tag = PostTag::find($id);
$post_tag->votes()->save(new Vote)
```
But this doesn't work because you can't instantiate, the only thing i can do now is

**POST** /post/{post}/tag/{tag}/likes

```
$post = Post::find($id);
$post_tag = $post->tags()->find($tag)->pivot;
$post_tag->votes()->save(new Vote);
```

that's so much cumbersome

**Comment by brunocascio** [comment] 2017-07-05 18:13
Take a look at https://stackoverflow.com/a/44932979/2723301

I've implemented in a better way.

**Comment by darkylmnx** [comment] 2017-07-05 19:30
@brunocascio the solution in your link doesn't make the pivot model instantiable sinc the pivot are gotten from the related query `Banner`

What we want here is `BannerRegion` to be in instantiable (based on your link)

**Comment by decadence** [comment] 2017-07-20 14:01
Merged in 5.5.

**Closed** 2017-07-20 14:22 UTC

**Comment by JuanDMeGon** [comment] 2017-07-20 14:28
Awesome! Thank you @BertvanHoekelen

**Comment by dwyer14** [comment] 2017-07-22 22:20
@JuanDMeGon +1 for posting. I've gone hunting for this a couple of times; glad to see it make its way into the 5.5 release. Can anyone confirm if this addition to 5.5 will also allow for eager loading? 

eg, @rdpascua's example: `$foo->with('bar.pivot.baz');`

**Comment by pnlinh-ivc** [comment] 2018-04-02 10:02
@cjaoude  How can I return data relate with pivot table to json without loop?

**Comment by mazyvan** [comment] 2018-12-23 21:44
I don't clearly understand why this issue gets to long in comments. I mean AFAIK following the [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle) the behavior this was is not correct. Now I'm looking a way to go workaround with this in 5.4. I have a `MorphPivot` class and I need it to relation with another class. But I can't. Any idea? 
BTW I know this isn't the proper place to ask the question, but I bet some of you guys had facing the same problem
