### ISSUE TITLE
distinct , join with paginate  dose not work properly due to missing column parameter

### ISSUE THREAD

**Issue by alhad15** [laravel/framework#19039] opened 2017-05-03 11:26 UTC
- Laravel Version: 5.4.#
- PHP Version:
- Database Driver & Version:

### Description:
distinct , join with paginate  dose not work properly 
file framework/src/Illuminate/Database/Eloquent/Builder.php 
line 690 getCountForPagination() function has column parameter is missing

**Comment by Dylan-DPC** [comment] 2017-05-03 12:18
can you share some code?

**Comment by alhad15** [comment] 2017-05-03 12:24
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Builder.php
line 690 
$results = ($total = $this->toBase()->getCountForPagination())
i think be should be
$results = ($total = $this->toBase()->getCountForPagination($columns))

**Comment by themsaid** [comment] 2017-05-05 06:32
Duplicate of: https://github.com/laravel/framework/pull/18186

**Closed by themsaid** 2017-05-05 06:32 UTC
