### ISSUE TITLE
Eager loading relationship attribute conflict with the same name getXxxAttribute when calling toArray

### ISSUE THREAD

**Issue by ganlvtech** [laravel/framework#20743] opened 2017-08-24 23:44 UTC
- Laravel Version: 5.4.32
- PHP Version: 7.0.22
- Database Driver & Version: mysqld  Ver 10.0.31-MariaDB-0ubuntu0.16.04.2 for debian-linux-gnu on x86_64 (Ubuntu 16.04)

### Description:

If I have a `User` model with relation to `Post` `eager-loaded` by `with` and it also has `getPostsAttribute` method `appends` to output array, then when `toArray()`, I get the original data of the relationship.

### Steps To Reproduce:

```php
<?php
class User extends Model
{
    protected $with = ['posts'];
    protected $appends = ['posts'];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function getPostsAttribute()
    {
        return $this->posts()->pluck('title');
    }
}
?>
```

With `php artisan tinker`
```php
<?php
$user = App\User::first();
$user->posts; // That is ok, only title.
$user->toArray(); // That will get original data
?>
```

### Probably solution

Override `Model` `toArray` method with

```php
<?php
class MyModel extends Model {
    public function toArray()
    {
        return $this->attributesToArray() + $this->relationsToArray();
    }
}
?>
```

#### My test

```php
<?php
array_merge(['foo' => 1], ['foo' => 2]); // ['foo' => 2]
['foo' => 1] + ['foo' => 2]; // ['foo' => 1]
?>
```

**Comment by Dylan-DPC** [comment] 2017-08-25 12:12
AFAIK you can't have accessors/mutators for a relationship

**Comment by themsaid** [comment] 2017-08-25 15:24
This is a major breaking change, I don't think you should ever do that, use mutators only for attributes but not relations.

Closing since it's not a bug, 
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Closed by themsaid** 2017-08-25 15:24 UTC

**Comment by ganlvtech** [comment] 2017-09-01 04:03
In https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php , in method getAttribute(),

    /**
     * Get an attribute from the model.
     *
     * @param  string  $key
     * @return mixed
     */
    public function getAttribute($key)
    {
        if (! $key) {
            return;
        }
        // If the attribute exists in the attribute array or has a "get" mutator we will
        // get the attribute's value. Otherwise, we will proceed as if the developers
        // are asking for a relationship's value. This covers both types of values.
        if (array_key_exists($key, $this->attributes) ||
            $this->hasGetMutator($key)) {
            return $this->getAttributeValue($key);
        }
        // Here we will determine if the model base class itself contains this given key
        // since we do not want to treat any of those methods are relationships since
        // they are all intended as helper methods and none of these are relations.
        if (method_exists(self::class, $key)) {
            return;
        }
        return $this->getRelationValue($key);
    }


It would try get mutator first, and then try to get value form the relation.

So I think that may be a bug instead of feature request.

**Comment by devcircus** [comment] 2017-09-01 04:48
At the end of the day, you have complete control over how things are named. If your names are bumping into each other, consider different names. Otherwise, this seems like perfectly expected behavior.
