### ISSUE TITLE
Eloquent where('column') and whereColumn() without value should behave like boolean

### ISSUE THREAD

**Issue by powelski** [laravel/framework#26333] opened 2018-10-31 19:07 UTC
Currently, skipping value for `where('column')` will behave as `IS NULL`, like this:

```php
$games = Game::where('is_active')->get();
```

This will make a query:

```sql
select * from `games` where `is_active` is null
```

If we try with magic `where`:

```php
$games = Game::whereIsActive()->get();
```

It will produce an error:
> Undefined offset: 0

I think it would be much more intuitive, if it behave as boolean, running the following query:

```sql
select * from `games` where `is_active`
```

I understand what was the thinking pattern behind making `null` default, but reading line `Game::where('is_active')` really doesn't make it obvious that we are actually looking for a `null`.

**Comment by hichxm** [comment] 2018-11-01 17:30
Try to tape this code:

```php
$games = Game::where('is_active')->toSql();
$games = Game::whereIsActive()->toSql();
```

and compare it to view difference.

**Comment by powelski** [comment] 2018-11-06 16:14
@hichxm what's your point?

**Comment by driesvints** [comment] 2018-11-08 14:49
I really don't think not passing a value makes much sense even if the default behavior of the current `where` method allows this. Since it doesn't influences the query at all by just doing a where on a column without a check I don't consider this as an actual bug.

**Comment by powelski** [comment] 2018-11-08 14:54
It does make a lot of sense for boolean values, which are also supported by SQL (WHERE without any operator).

**Comment by driesvints** [comment] 2018-11-08 14:55
@powelski you'd still need to pass a value in this case?

**Comment by powelski** [comment] 2018-11-08 14:55
Closing upvoted ticket with improvement suggestion, because one person thinks „it’s not a bug”? Wow.

**Comment by powelski** [comment] 2018-11-09 01:10
@driesvints no, you would not need to pass a value. Just like you can do it in a query:

```
SELECT * FROM people WHERE is_alive
```

It would feel natural to express this way, especially that it's on par with PHP's non-empty truthfulness.

**Comment by driesvints** [comment] 2018-11-09 10:14
Alright, wel feel free to send in a PR and see if it gets accepted.

**Comment by toniperic** [comment] 2018-11-11 23:01
I wouldn't necessarily classify this as a bug but rather enhancement.

**Comment by phroggyy** [comment] 2018-11-13 16:00
@driesvints could we have this relabelled as an improvement? This is not a bug – there is no documented behaviour for not passing an argument, and it will result in a breaking change. I agree that it syntactically makes more sense, but it is not a bug.

**Comment by driesvints** [comment] 2018-11-13 16:05
Yup, I agree. Relabelled.

**Comment by devcircus** [comment] 2019-03-02 18:21
Definitely not a bug as this was never the intended behavior. This is a feature request or enhancement.

**Comment by driesvints** [comment] 2019-03-04 15:36
Closing since the PR was closed.

**Closed by driesvints** 2019-03-04 15:36 UTC
Labels: enhancement
