### ISSUE TITLE
Union via Eloquent fails with many-to-many/belongsToMany due to "different number of columns"

### ISSUE THREAD

**Issue by bridgeport** [laravel/framework#23862] opened 2018-04-12 14:22 UTC
- Laravel Version: 5.6.16
- PHP Version: 7.1.14
- Database Driver & Version: MySQL 5.7.21 (same result with Postgresql 10.3)

### Description:

Many-to-many (belongsToMany) union (or unionAll) join via eloquent generates SQL that adds pivot columns for the first select but not for the subsequent select resulting in the following error:
```
local.ERROR: SQLSTATE[21000]: Cardinality violation: 1222 The used SELECT statements have a different number of columns
```

### Steps To Reproduce:

Create migrations:
```php
// Business categories
Schema::create('categories', function (Blueprint $table) {
    $table->increments('id');
    $table->string('name');
    $table->timestamps();
});

// Large businesses
Schema::create('large_businesses', function (Blueprint $table) {
    $table->increments('id');
    $table->string('name');
    $table->string('city');
    $table->string('state');
    $table->timestamps();
});

// Small Businesses
Schema::create('small_businesses', function (Blueprint $table) {
    $table->increments('id');
    $table->string('name');
    $table->string('city');
    $table->string('state');
    $table->timestamps();
});

// Pivot table for categories and large businesses
Schema::create('category_large_business', function (Blueprint $table) {
    $table->integer('category_id')->unsigned();
    $table->integer('large_business_id')->unsigned();
    $table->timestamps();
    $table->primary(['category_id', 'large_business_id']);
});

// Pivot table for categories and small businesses
Schema::create('category_small_business', function (Blueprint $table) {
    $table->integer('category_id')->unsigned();
    $table->integer('small_business_id')->unsigned();
    $table->timestamps();
    $table->primary(['category_id', 'small_business_id']);
});
```
Seed some data:
```php
class DatabaseSeeder extends Seeder
{
    public function run()
    {
        \App\Category::insert([
            [
                'name' => 'Painters',
            ],
        ]);

        \App\LargeBusiness::insert([
            [
                'name'  => 'Large Acme Painters',
                'city'  => 'Phoenix',
                'state' => 'AZ',
            ],
        ]);

        \App\SmallBusiness::insert([
            [
                'name'  => 'Small Acme Painters',
                'city'  => 'Tempe',
                'state' => 'AZ',
            ],
        ]);

        DB::table('category_large_business')->insert(['category_id' => 1, 'large_business_id' => 1]);

        DB::table('category_small_business')->insert(['category_id' => 1, 'small_business_id' => 1]);
    }
}
```

Create relationships in Category model:
```php
class Category extends Model
{
    public function largeBusinesses()
    {
        return $this->belongsToMany('\App\LargeBusiness');
    }

    public function smallBusinesses()
    {
        return $this->belongsToMany('\App\SmallBusiness');
    }
}
```

Perform the following union query:
```php
Route::get('/testing', function () {
    $category = \App\Category::first();

    $large_businesses = $category->largeBusinesses();
    $small_businesses = $category->smallBusinesses();

    $union_businesses = $large_businesses->union($small_businesses);

    return $union_businesses->get();
});
```

The above query generates the following SQL:
```sql
-- output of $union_businesses->get()
(select
    `large_businesses`.*,
    `category_large_business`.`category_id` as `pivot_category_id`,
    `category_large_business`.`large_business_id` as `pivot_large_business_id`
    from `large_businesses` inner join `category_large_business` on `large_businesses`.`id` = `category_large_business`.`large_business_id` where `category_large_business`.`category_id` = 1)
union
(select
    *
    from `small_businesses` inner join `category_small_business` on `small_businesses`.`id` = `category_small_business`.`small_business_id` where `category_small_business`.`category_id` = 1)
```
The first select is adding two extra columns with `pivot_category_id` and `pivot_large_business_id` causing the union query to fail. The second select is left untouched by adding only one column.

Here's the odd thing: If you were to return `$union_businesses->toSql();` instead of `$union_businesses->get();` the ouputted SQL would be perfectly valid, as such:

```sql
-- output of $union_businesses->toSql()
(select * from `large_businesses` inner join `category_large_business` on `large_businesses`.`id` = `category_large_business`.`large_business_id` where `category_large_business`.`category_id` = ?)
union
(select * from `small_businesses` inner join `category_small_business` on `small_businesses`.`id` = `category_small_business`.`small_business_id` where `category_small_business`.`category_id` = ?)
```

I would think the second select columns _should_ match the first select in order to access the pivot table values, if required. For instance, the following code...
```php
class Category extends Model
{
    protected $hidden = ['pivot'];

    public function largeBusinesses()
    {
        return $this->belongsToMany('\App\LargeBusiness')->withTimestamps();
    }

    public function smallBusinesses()
    {
        return $this->belongsToMany('\App\SmallBusiness')->withTimestamps();
    }
}
```
...would only return the timestamp columns for the `large_businesses` for the first select in the union, while omitting them for the second select. I presume `withPivot()` would fail as well.

Thanks.

**Comment by GabrielaSaldana** [comment] 2018-07-30 14:55
I recommend you to not using Laravel relations, most of the times is better to bring data from database using Eloquent instead of the model.

**Comment by driesvints** [comment] 2018-11-20 13:29
Heya. There have been some fixes merged for UNION bugs in the last couple of weeks. Can you try updating to the latest version to see if this fixes your problem? If not feel free to report back!

**Comment by driesvints** [comment] 2018-11-20 16:41
Okay, re-opening.

**Comment by NicksonYap** [comment] 2019-01-10 18:36
I have the same issue with Union for belongsToMany() or many-to-many relations

Have tried with 5.7.20 and 5.8.x (https://github.com/laravel/framework/commit/cb1fbdc4e43526fc2baed59c2c1f027a1c14c6dc)

It seems using query builder is the way to go.

**Comment by driesvints** [comment] 2019-02-21 10:43
Did https://github.com/laravel/framework/pull/27589 fix this?

**Comment by staudenmeir** [comment] 2019-02-21 11:29
@driesvints No.

**Comment by staudenmeir** [comment] 2019-06-25 22:57
I don't think this is something that Laravel should support.

You can use the underlying query:

```php
$union_businesses = $large_businesses->getQuery()->union($small_businesses)->get();

return $union_businesses->get();
```

If you want to select columns from the pivot table, you'll need to add them manually.

@driesvints I suggest we close this as a no-fix.

**Comment by driesvints** [comment] 2019-06-27 08:10
@staudenmeir thanks for checking in on this. I also believe this is a bit out of scope as to what Eloquent was intended for.

**Closed by driesvints** 2019-06-27 08:10 UTC
Labels: bug

**Comment by ken717w** [comment] 2023-01-08 22:45
@staudenmeir I came all the way here and you just saved my day, hats off to you.
