### ISSUE TITLE
Route caching breaks the Model Route Binding in Middleware

### ISSUE THREAD

**Issue by gthedev** [laravel/framework#32052] opened 2020-03-20 18:40 UTC
- Laravel Version: 7.2.1
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 8.0.18

### Description:
After caching the routes using `artisan route:cache` the Route Model Binding does not work.

### Steps To Reproduce:
Route:
```
Route::group(
    [
        'prefix' => '{country}',
    ],
    function () {
        Route::get('/', 'PageController@homepage')->name('homepage.country');
    }
);
```

Middleware:
```
public function handle($request, Closure $next)
    {
        $country = $request->route()->parameter('country');
        $request->attributes->set('country', $country);

        return $next($request);
    }
```

Controller:
```
   public function homepage(Request $request)
    {
        /** @var Country|null $country */
        $country = $request->attributes->get('country');

        dd($country);
    }
```

RouteServiceProvider:
```
        Route::bind(
            'country',
            function ($value) {
                return Country::where('slug', $value)->firstOrFail();
            }
        );
```

Before caching (`country` is an `Object`):
![image](https://user-images.githubusercontent.com/19326428/77195804-971cdf80-6ab8-11ea-8d4b-d88b3a09002d.png)

After running `php artisan route:cache` (`country` is just the `slug`):
![image](https://user-images.githubusercontent.com/19326428/77195841-a7cd5580-6ab8-11ea-9c74-29477c79686c.png)

**Comment by taylorotwell** [comment] 2020-03-20 19:26
Where is that middleware placed in the stack?

**Comment by gthedev** [comment] 2020-03-20 19:30
It's the last in the `web` group:
```
            'web' => [
                EncryptCookies::class,
                AddQueuedCookiesToResponse::class,
                StartSession::class,
                // \Illuminate\Session\Middleware\AuthenticateSession::class,
                ShareErrorsFromSession::class,
                VerifyCsrfToken::class,
                SubstituteBindings::class,
                ResolveCountry::class, // <----
            ],
```

**Comment by taylorotwell** [comment] 2020-03-20 19:31
I can't recreate this on 7.2.2.

**Comment by driesvints** [comment] 2020-03-20 19:34
I can't recreate this on 7.2.0 either.

**Comment by gthedev** [comment] 2020-03-20 19:35
Just updated to 7.2.2 and still getting the same results.

**Comment by taylorotwell** [comment] 2020-03-20 19:38
Well, your best bet might be to write a failing test for the framework then. I can't recreate it.

**Comment by Rainnerz** [comment] 2020-03-23 22:50
Getting a similar issue with route caching ever since Laravel 7
[Link to Laracasts](https://laracasts.com/discuss/channels/code-review/laravel-7-breaks-my-index-route-whenever-the-routes-are-cached)

**Comment by Pyker** [comment] 2020-04-02 11:12
I'm able of reproducing this issue, but it's unrelated to middleware. I'm using explicit route model bindings and, after caching, it raises an exception because apparently the model bindings cease to work.

In the web routes:
`Route::model('user', App\User::class);`

Then a bit further down:
`Route::get('profile/{user}', 'UserController@showProfile');`

When route caching isn't used, the profile page loads fine. When route caching is used, this exception is raised instead:
`must be an instance of App\User, string given`

Looking at the route parameters in the exception page reveals that it simply passsed the "user" portion as the int, rather than resolving it to the User model (the string mentioned in the exception is the user ID, "123").

**Comment by Pyker** [comment] 2020-04-02 11:14
Looking again at the documentation, this is probably because my model binding is being declared inside the routes file itself, rather than in RouteServiceProvider, but I honestly wasn't expecting it to blow up like this once routes were cached.

**Comment by driesvints** [comment] 2020-04-14 13:54
Closing this as we can't reproduce this.

**Closed by driesvints** 2020-04-14 13:54 UTC
Labels: needs more info

**Comment by mortenscheel** [comment] 2021-11-15 12:19
In case it can help someone else in the future, I had a similar issue which was caused by a Laravel Shift moving my custom route bindings into the route registration callback:
```php
public function boot()
{
    $this->configureRateLimiting();
    $this->routes(function() {
        // If you put Route::bind() calls here, they won't work when routes are cached.
        Route::prefix('api')
            ->middleware('api')
            ->namespace($this->namespace)
            ->group(base_path('routes/api.php'));

        Route::middleware('web')
            ->namespace($this->namespace)
            ->group(base_path('routes/web.php'));
    }
}
```
Which works, but only if you don't cache the routes.
Moving the bindings to the "root" of the boot method fixed it, but it took a while to figure out why.

**Comment by jcdennen** [comment] 2022-01-24 05:36
> RouteServiceProvider

wow thanks, I was scratching my head for hours trying to figure out what the issue was. this feels like something that should be documented more clearly

**Comment by jcdennen** [comment] 2022-01-24 05:36
> In case it can help someone else in the future, I had a similar issue which was caused by a Laravel Shift moving my custom route bindings into the route registration callback:
> 
> ```
> public function boot()
> {
>     $this->configureRateLimiting();
>     $this->routes(function() {
>         // If you put Route::bind() calls here, they won't work when routes are cached.
>         Route::prefix('api')
>             ->middleware('api')
>             ->namespace($this->namespace)
>             ->group(base_path('routes/api.php'));
> 
>         Route::middleware('web')
>             ->namespace($this->namespace)
>             ->group(base_path('routes/web.php'));
>     }
> }
> ```
> 
> Which works, but only if you don't cache the routes. Moving the bindings to the "root" of the boot method fixed it, but it took a while to figure out why.

wow thanks, I was scratching my head for hours trying to figure out what the issue was. this feels like something that should be documented more clearly!

**Comment by vectorkey** [comment] 2023-11-25 22:01
I have same issue on Laravel 10, after cache. all my bind from RouteServiceProvider not available.
