### ISSUE TITLE
MorphedByMany does not exclude SoftDeleted elements

### ISSUE THREAD

**Issue by mbariola** [laravel/framework#20307] opened 2017-07-28 20:04 UTC
- Laravel Version: 5.4.28
- PHP Version: 7.1.1
- Database Driver & Version:
mysqli - MySQL 5.6.35 - MySQL Community Server (GPL)

### Description:

Sorry, I am not framework-savvy enough to submit a fixing pull request.

I have a model Attore which morphToMany three different models: Procedimento, Sessione, Documento. In turn, those three models morphToMany Attore.

The name of the pivot model / table is Attoreable / attoreable, which has softDeletes. the pivot table has an extra field and I need the id for other reasons.

When I delete() any Attoreable element, deleted_at is correctly set, and when Tinkering, the model is correctly not returned. However, it is returned from morphToMany, disregarding the soft deletion.

### Steps To Reproduce:

Create Models with morphedByMany, e.g. like so

```
// in Attore
    public function documentos()
    {
        return $this->morphedByMany('App\Documento', 'attoreable')->withPivot('ruolo', 'id')->orderBy('attoreable_id', 'asc');
    }

    public function sessiones()
    {
        return $this->morphedByMany('App\Sessione', 'attoreable')->withPivot('ruolo', 'id')->orderBy('attoreable_id', 'asc');
    }

    public function procedimentos()
    {
        return $this->morphedByMany('App\Procedimento', 'attoreable')->withPivot('ruolo', 'id')->orderBy('attoreable_id', 'asc');
    }


// in any among Procedimento, Sessione, Documento
    public function attores()
    {
        return $this->morphToMany('App\Attore', 'attoreable')->withPivot('ruolo', 'id');
    }


```

1. (i.e. using Tinker) find a valid Attoreable record $attoreable (e.g. $attoreable = Attoreable::find(100), corresponding to attore_id = 10, attoreable_id = 20 and attoreable_type = 'App\Documento'). 
2. get $attore = Attore::find(10)
1. $attore->documentos->toArray() will include the Attoreable record with ID 100.
2. $attoreable->delete();
3. try to find it again, i.e. Attoreable::find(100) , NULL should (correctly) be returned. deleted_at is correctly set on model.
4. $attore->documentos->toArray() will still include the Attoreable record with ID 100, apparently ignoring the deleted_at field.

### Expected
$attore->documentos to not include the deleted model.

I can provide the full migrations / db dump and code if needed to reproduce.

**Comment by srmklive** [comment] 2017-08-01 20:41
To be honest, i don't think there is a way if the referenced model actually uses soft deletes in case of a MorphToMany relationship.

**Comment by srmklive** [comment] 2017-08-02 14:41
![screenshot from 2017-08-02 19 35 57](https://user-images.githubusercontent.com/839335/28878910-1c109988-77ba-11e7-9a19-df847a277fc5.png)
![screenshot from 2017-08-02 19 37 37](https://user-images.githubusercontent.com/839335/28878915-1eec564c-77ba-11e7-9f28-475b74e34c73.png)

@mbariola As you can see above a Tag has morphedToMany relation with Post & Video. Both Post & Video has `softDeletes` enabled. The issue you described i haven't been able to replicate on both PostgreSQL 9.6 & MySQL 5.7.

**Comment by mbariola** [comment] 2017-08-10 17:23
hello @srmklive , my apologies for taking so much to answer, I am relocating.

this is my situation from Tinker. Please check attached screenshots. here's what to look for in them.

I pull up an Attore, id 195.

I check its procedimentos, there's one, ID 103. Please note that pivot element has ID 555.

I find the pivot element with ID 555, and save it in $attoreable.

I delete it once, tinker answers true.

I delete it a second time, Tinker says null. phpMyAdmin correctly marks the record's deleted_at field with datetime.

I fetch again $attore's first procedimento. same Procedimento comes up, pivot record is again ID 555.

One weird thing is, Attoreable records's created_at  are not set, and updated_at is only set when record is deleted.

![screenshot 2017-08-10 19 03 21](https://user-images.githubusercontent.com/4893151/29182899-f904f9be-7e00-11e7-924a-878374f3bb6f.png)

![screenshot 2017-08-10 19 11 46](https://user-images.githubusercontent.com/4893151/29182909-02da309e-7e01-11e7-8ea8-258517e4d93b.png)


![screenshot 2017-08-10 19 12 41](https://user-images.githubusercontent.com/4893151/29182939-1c99da52-7e01-11e7-8444-8d23c1ce5e88.png)


![screenshot 2017-08-10 19 19 04](https://user-images.githubusercontent.com/4893151/29183012-68c17192-7e01-11e7-94ae-f84ff3846afc.png)

**Comment by staudenmeir** [comment] 2018-08-19 02:10
`SoftDeletes` is currently not supported on pivot tables: #14008

**Comment by mbariola** [comment] 2018-08-19 17:27
Maybe just updating the documentation would be enough..

**Comment by laurencei** [comment] 2018-10-03 00:42
@mbariola - please feel free to submit a PR to the Laravel Docs with your idea.

I'll close this, as it seems the issue is resolved (the feature is not supported).

**Closed by laurencei** 2018-10-03 00:42 UTC
