### ISSUE TITLE
Composer fails for laravel version > 5.7.15

### ISSUE THREAD

**Issue by sawisia** [laravel/framework#26896] opened 2018-12-18 16:03 UTC
- Laravel Version: >=5.7.16 
- PHP Version:  7.2.11
- Database Driver & Version: MariaDb 10.3.11

### Description:
Composer fails for any version of Laravel > 5.7.15

### Steps To Reproduce:
Run composer up
Error:
_In Container.php line 960:
Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\Manager_ 

It looks like it is failing on NexmoChannelServiceProvider.php

Log:

![image](https://user-images.githubusercontent.com/10868578/50166404-fdfb8980-02b4-11e9-88bc-dd5072a4adde.png)

**Comment by X-Coder264** [comment] 2018-12-18 16:22
You must add `Illuminate\Notifications\NotificationServiceProvider::class` to your `config/app.php` file.

**Comment by ahinkle** [comment] 2018-12-18 16:23
Duplicate of #15304.

**Closed** 2018-12-18 16:24 UTC

**Comment by sawisia** [comment] 2018-12-18 16:59
Awesome thank you!

**Comment by satya7289** [comment] 2020-05-01 11:09
Great, Thankyou  !!
