### ISSUE TITLE
Session randomly expiring too early

### ISSUE THREAD

**Issue by DanielKeeble** [laravel/framework#15555] opened 2016-09-22 09:31 UTC
- Laravel Version: v5.2.45
- PHP Version: 7.0.3-3
- Database Driver & Version: MySQL 5.7.10
- Cache engine: Memcached 2.2.0

### Description:
I have my session lifetime set to 60 minutes. However sessions seem to be expiring after only about 20 minutes. We haven't been able to find a specific value after which the sessions seem to be expiring but it would appear to be anywhere from about that 20 minute mark.

As far as I can tell I have no error logs in memcached and New Relic does not appear to be reporting any problems either.

Also may be worth noting that the production server this is occurring on was provisioned via Forge.

### Steps To Reproduce:
1. Login to website
2. Visit any page
3. Leave inactive for approximately 20-30 mins
4. Refresh page
5. See you have been logged out

Many thanks.

**Comment by themsaid** [comment] 2016-09-22 10:11
Is that a new issue or are you experiencing this since the beginning?

**Comment by DanielKeeble** [comment] 2016-09-22 10:20
@themsaid I want to say a new issue, however as I wasn't handling unauthorised requests properly, it could have been around for a while. Sorry I can't be more specific.

**Comment by DanielKeeble** [comment] 2016-09-22 10:23
@themsaid Do you think any of these might be related/of use?

https://github.com/laravel/framework/issues/9787

https://github.com/laravel/framework/commit/0831312aec47d904a65039e07574f41ab7492418

**Comment by themsaid** [comment] 2016-09-22 10:28
Could be :) Hard to tell without being able to reproduce the issue.

**Comment by DanielKeeble** [comment] 2016-09-22 10:30
@themsaid I appreciate it's basically impossible to debug without being able to replicate the issue.

So there are no known issues with Laravel and memcached?

**Comment by themsaid** [comment] 2016-09-22 13:13
Not that I know of, these "random" stuff are very hard to debug. I appreciate if you can take a look at the problem at your end since you can replicate.

**Comment by DanielKeeble** [comment] 2016-09-22 18:45
@themsaid Yeah I completely understand. I'll be sure to report back if I find anything.

**Comment by prasanthsd** [comment] 2016-09-23 13:35
Not sure if the issue that I'm facing is related but thought its worth mentioning. I had an app which used to use laravel 5.1. It kept on logging out users and we discovered file driver was the problem. We switched to the DB driver and it never really occurred.

Later we updated Laravel to 5.2 and made many changes to the application. Now it randomly logs out users. I THINK the place where the logout occurs is a part of the application that does a lot of DB processing.

Currently we are using Laravel 5.2.45

**Comment by ysupr** [comment] 2016-10-08 13:15
Have same issue, and same like @DanielKeeble, i can't tell the way to replicated it.

The app are works well on my local development, and on regular VPS. But when i deployed on production physical server, the session randomly expired and make user log out randomly. 

Using 5.2

**Comment by themsaid** [comment] 2016-10-12 08:35
Looks like all reports are for v5.2 which is not supported anymore, if you can replicate the issue on a 5.3 or 5.1 application we can start looking into it. But please share steps to reproduce as the ones in the original comment doesn't replicate the issue it all.

**Comment by DanielKeeble** [comment] 2016-10-12 08:40
@themsaid I would agree with this being v5.2 specific. Currently developing a v5.3 app and don't seem to be having the same issue.

Is it also worth suggesting maybe it's an environment problem, as opposed to a Laravel specific issue?

**Comment by themsaid** [comment] 2016-10-12 08:42
@DanielKeeble yes that might be the case as well, can't really decide since I'm unable to replicate :)

**Comment by themsaid** [comment] 2016-10-13 14:11
Closing this then, please feel free to ping me if you ever had the problem on a 5.3 installation.

**Closed by themsaid** 2016-10-13 14:11 UTC

**Comment by joelmatisa** [comment] 2020-02-17 17:06
Hello everyone, I'm facing the same problem but I'm on laravel 5.5, other times did you have any solutions ?
