### ISSUE TITLE
Tinker is not working "" php-xdg-runtime-dir-fallback-): Directory not empty "" 

### ISSUE THREAD

**Issue by abdolrhman** [laravel/framework#21777] opened 2017-10-22 08:31 UTC
- Laravel Version: 5.5.*
- PHP Version:7.0.10
- Database Driver & Version: mysql

### Description:
every thing was working fine , even tinker ,
when i used php artisan make:transformer
the Error come to life !!!
"rmdir(C:\Users<user>\AppData\Local\Temp\php-xdg-runtime-dir-fallback-): Directory not empty"
when i use php artisan tinker

**Comment by bloggervista** [comment] 2017-10-22 08:34
can you tell us how to reproduce this issue. It seems like you are using Laravel fractal right?

**Comment by abdolrhman** [comment] 2017-10-22 11:06
i Don't know how , Yes am using Fractal , am not sure if this problem because of it, but this error is new to me , didn't happen before . 
i fixed the problem by deleting the folder "php-xdg-runtime-dir-fallback"
i think there 's  a conflict in Laravel 55

**Comment by Mattiullah** [comment] 2017-10-22 13:46
yes! i am also facing same error every time when i use tinker.
but i delete that folder every time then it's works ...otherwise it's displays above mentioned error.

**Comment by bloggervista** [comment] 2017-10-22 14:14
Yeah I can understand you gies its frustrating but we need to find how to create such issue so that we find what is causing problem. There can be various reason like package, config, cache

**Comment by devcircus** [comment] 2017-10-22 15:23
This is a problem with windows compatibility with a dependency. See: https://github.com/bobthecow/psysh/issues/430

They are working on a permanent fix, however they offer a temporary fix in that thread.

My workaround is below. (This edits a vendor file, so if you're not comfortable with that, see the recommended workaround in the linked thread above)

I added this to the bottom of Xdg.php, then replaced all references to ```rmdir($fallback)``` with ```$this->deleteDirectory($fallback);```
```php
    /*
     * php delete function that deals with directories recursively
     */
    private function deleteDirectory($dir) {
        if (!file_exists($dir)) {
            return true;
        }

        if (!is_dir($dir)) {
            return unlink($dir);
        }

        foreach (scandir($dir) as $item) {
            if ($item == '.' || $item == '..') {
                continue;
            }

            if (! $this->deleteDirectory($dir . DIRECTORY_SEPARATOR . $item)) {
                return false;
            }

        }

        return rmdir($dir);
    }
```

**Comment by Mattiullah** [comment] 2017-10-22 15:32
I got a solution. we need to overwrite a function in "\vendor\dnoegel\php-xdg-base-dir\tests\XdgTest.php". line 83 to 119

on Windows OS a folder created inside "php-xdg-runtime-dir-fallback-" named "psysh" so we need to remove delete inner folder first then delete outer folder..

```

    public function getRuntimeDir($strict=true)
    {
        if ($runtimeDir = getenv('XDG_RUNTIME_DIR')) {
            return $runtimeDir;
        }

        if ($strict) {
            throw new \RuntimeException('XDG_RUNTIME_DIR was not set');
        }

        $fallback = sys_get_temp_dir() . DIRECTORY_SEPARATOR . self::RUNTIME_DIR_FALLBACK . getenv('USER');
        echo $fallback;
        $create = false;

        if (!is_dir($fallback)) {
            mkdir($fallback, 0700, true);
        }

        $st = lstat($fallback);

        # The fallback must be a directory
        if (!$st['mode'] & self::S_IFDIR) {
            rmdir($fallback."/psysh");
            rmdir($fallback);
            $create = true;
        } elseif ($st['uid'] != getmyuid() ||
            $st['mode'] & (self::S_IRWXG | self::S_IRWXO)
        ) {

            rmdir($fallback."/psysh");
            rmdir($fallback);
            $create = true;
        }

        if ($create) {
            mkdir($fallback, 0700, true);
        }

        return $fallback;
    }
```

**Comment by bloggervista** [comment] 2017-10-22 16:12
Strange I never got such problem. Got vanilla PHP from windows.php.net .

**Comment by bobthecow** [comment] 2017-10-22 21:09
`composer update` should do it. It's fixed in PsySH v0.8.13.

**Comment by devcircus** [comment] 2017-10-22 23:27
Great. Thanks!

**Comment by abdolrhman** [comment] 2017-10-23 06:52
worked Great , but what was the problem ?

**Comment by bobthecow** [comment] 2017-10-23 06:59
There’s a bug in an underlying library (PHP XDG BaseDir) when running on Windows. v0.8.13 just reverts the one change from v0.8.12 that triggers the bug. A future release will fix it fully.

**Comment by abdolrhman** [comment] 2017-10-23 07:12
Cool , Thank You . ^^

**Comment by themsaid** [comment] 2017-10-23 11:39
Closing since it's not a laravel issue.

**Closed by themsaid** 2017-10-23 11:39 UTC

**Comment by mulugu** [comment] 2017-10-26 17:06
I also got the same error after installing Python

**Comment by lk77** [comment] 2017-11-07 13:47
hello, i have the same issue on linux server after a composer update :
rmdir(/tmp/php-xdg-runtime-dir-fallback-root): Directory not empty

**Comment by devcircus** [comment] 2017-11-08 15:31
If you've confirmed you have the latest psysh version, then submit an issue to that repo. This isn't a Laravel issue. After updating psysh, I no longer have this issue.

**Comment by renatoagomes** [comment] 2017-11-14 01:49
Temporary fix is downgrading psysh to v0.8.11

Just specify the `psy/psysh` package and version in your composer.json like this

     "laravel/tinker": "~1.0",
     "psy/psysh": "0.8.11",

And run a `composer update`

https://github.com/bobthecow/psysh/issues/430#issuecomment-344118543

**Comment by devcircus** [comment] 2017-11-14 02:37
Temp fix not needed. Problem was corrected.

**Comment by Cospel1** [comment] 2018-02-03 19:38
i've fixed it with "Sudo php artisan tinker" :thinking:

**Comment by bobthecow** [comment] 2018-02-03 19:54
ooh. don't do that :-/

**Comment by Cospel1** [comment] 2018-02-03 19:56
Why? is it bad? thanks

**Comment by bobthecow** [comment] 2018-02-03 20:52
The reason you're having trouble is that your current user can't write to your temp directory. Running as `sudo` bypasses this, but will leave even more files there that your current user can't write to. It's better to fix the temp directory permissions :)

**Comment by Cospel1** [comment] 2018-02-03 20:54
Oh didn't know that! i'll try to fix it then! thanks you very much!
