### ISSUE TITLE
[5.2] Cannot run withTrashed on Laravel Relationship

### ISSUE THREAD

**Issue by Madawar** [laravel/framework#11456] opened 2015-12-22 09:58 UTC
I could previously return a trashed relationship with the below code 

```
public function supplier()
    {
        
        return $this->hasOne('App\Supplier', 'id', 'polSupplierId')->withTrashed();
    }
```
but since upgrading to 5.2 it gives the below error 

```
BadMethodCallException in Builder.php line 2092:
Call to undefined method Illuminate\Database\Query\Builder::withTrashed()
```

**Comment by BradleyDeLar** [comment] 2015-12-22 10:54
I'm getting this also, I haven't looked close enough to figure out why yet...

**Comment by GrahamCampbell** [comment] 2015-12-22 11:29
This is intended, because withTrashed belongs to a trait that doesn't exist on that relation.

**Comment by GrahamCampbell** [comment] 2015-12-22 11:30
Oh, you're saying it used to work in 5.1 though. Hmmm. Ping @taylorotwell.

**Comment by danmatthews** [comment] 2015-12-22 15:03
:+1: for this - it's breaking my tests as it used to work on some of the relations in my app.

```php
public function garage()
{
   return $this->hasMany(\App\VehicleGarage::class)->withTrashed();
}
```

**Comment by taylorotwell** [comment] 2015-12-22 15:05
Can you show me how you are actually querying "garage" when it doesn't work?

**Comment by danmatthews** [comment] 2015-12-22 15:08
Literally just asserting a count on it in a test, to make sure the user only has one vehicle in their garage:

```php
$this->assertCount(1,$user->garage);
```

**Comment by danmatthews** [comment] 2015-12-22 15:08
I know i can rewrite it - which is fine, but it does seem to be a non-documented breaking change.

**Comment by acasar** [comment] 2015-12-22 15:18
@taylorotwell I think I know where the problem is.... Previously we always called apply on global scope, which calls extend. But now, if Global Scope is not applied, it is not extended.

We can probably always call extend on global scope if it exists?

**Comment by taylorotwell** [comment] 2015-12-22 15:20
Yeah I see that issue as well. How would we fix that? What builder would we pass it?

**Comment by acasar** [comment] 2015-12-22 15:21
We can upgrade `withGlobalScope` on the Builder. If $scope is instance of `Scope` we can check if `extends` method exists. If it does we call it.

**Comment by taylorotwell** [comment] 2015-12-22 15:22
Yeah my quick test does seem to indicate that works.

**Comment by taylorotwell** [comment] 2015-12-22 15:23
I'll push it up.

**Comment by acasar** [comment] 2015-12-22 15:23
Great. We should probably still document that behaviour. So that people can check their custom scopes (some may be using the same structure as SoftDeletingScope).

**Comment by taylorotwell** [comment] 2015-12-22 15:24
Yeah.

**Comment by taylorotwell** [comment] 2015-12-22 15:26
Can someone that has the problem test out the fix on "minimum-stability":
"dev" and verify the fix?

**Comment by danmatthews** [comment] 2015-12-22 15:52
Fixes it for me guys, thanks for that.

![screen shot 2015-12-22 at 15 52 19](https://cloud.githubusercontent.com/assets/149426/11959203/010f0032-a8c4-11e5-96ad-d6670300553a.png)

**Comment by kistank** [comment] 2015-12-22 15:59
It broke my  code as well. I use polymorphic relationship and I have to get soft deleted models. Can anyone suggest me a workaround?

      $download = \App\Download::find(9);
      $quotation = $download->load([
          'downloadable' => function($query){
              $query->withTrashed();
          }
      ]);

**Comment by taylorotwell** [comment] 2015-12-22 16:00
This should be fixed now.

**Closed** 2015-12-22 16:16 UTC
Labels: bug, database

**Comment by scott-admin** [comment] 2016-03-14 12:44
Same bug occurs for laravel 5.1.31.

Will the fix be backported?

**Comment by mysteryos** [comment] 2016-03-14 12:45
Same bug occurs in laravel 5.1.31

Will it be backported?

**Comment by Septagram** [comment] 2016-04-15 16:55
Just like @kistank, I ran into this. I need to get the soft-deleted models too, is there a workaround while we haven't yet upgraded to Laravel 5.3?
