### ISSUE TITLE
ValidationException throwing an error in withMessages method

### ISSUE THREAD

**Issue by bionicmaster** [laravel/framework#21413] opened 2017-09-27 06:20 UTC
- Laravel Version: 5.5.13
- PHP Version: 7.1
- Database Driver & Version:Mysql 5.6

### Description:
When you try to throw an error because validation is not right, when tries to send the messages, it's finding an error trying to use Arr as a class of Illuminate\Validation instead of Illuminate\Support

### Steps To Reproduce:
Try to login with incorrect credentials and voila, the error appears

### How to solve it
Try to add use Illuminate\Support\Arr;

**Comment by Dylan-DPC** [comment] 2017-09-27 19:56
I think you have made some mistake in your code. I tried it but cannot reproduce it.

**Comment by bionicmaster** [comment] 2017-09-27 20:01
It was already solved in PR 21414 / 21418 that was integrated a few hour ago

**Comment by Dylan-DPC** [comment] 2017-09-27 20:06
Well i tried it on an app i installed earlier. Either way you can close this issue

**Closed** 2017-09-27 20:07 UTC
