### ISSUE TITLE
Unable to use query builder results in Api Resource class

### ISSUE THREAD

**Issue by kevinpijning** [laravel/framework#31703] opened 2020-03-03 10:04 UTC
- Laravel Version: 6.17.1
- PHP Version: 7.4.2
- Database Driver & Version: mysql  & pgsql

### Description:
When i use the result of a query builder and i put it in a API Resource class i get an error that the stdClass object cannot be used as an array. When i die dump the resource, it wil give me a valid resource back, but it generates an error when i want to return the resource in my controller
I've tested it with the mysql and pgsql driver, both have the same issue.

### Steps To Reproduce:
Create a controller with this in it:
```php
$builder = DB::table('users')->select('id');
return UserResource::collection($builder->paginate());
```

Put this in the `toArray` method of the `UserResource`:
```php
        return [
            'id' => $this->id
        ];
```

**Comment by LastDragon-ru** [comment] 2020-03-03 11:29
Seem duplicate of #29916?

**Comment by driesvints** [comment] 2020-03-03 11:44
Resources only work with eloquent models.

**Closed by driesvints** 2020-03-03 11:44 UTC

**Comment by f-ricci** [comment] 2020-06-06 11:31
@driesvints If resource work only with eloquent model, then why passing a `Illuminate\Database\Eloquent\Collection Model::all()` is transformed into a `Illuminate\Support\Collection Resource` and therefore breaking behaviour like the following.

this works
```
$categories = Category::get();
$categories->append('hierarchicalName');
$collection = CategoryResource::collection($categories);
```

this doesn't
```
$categories = Category::get();
$collection = CategoryResource::collection($categories);
$collection->append('hierarchicalName');
```

A solution would be to create a ModelResourceCollection and extend de framework's behaviour but this doesn't sound like future proof to me.

Would such a class be helpful?
