### ISSUE TITLE
Duplicates of issues reported to Rollbar, incomplete implementation of PsrLoggerInterface?

### ISSUE THREAD

**Issue by gregrobson** [laravel/framework#14390] opened 2016-07-20 11:05 UTC
**Problem**
When following the Rollbar instructions for implementing logging [here](https://github.com/jenssegers/laravel-rollbar) you are advised to do the following:

```php
public function report(Exception $e)
{
    \Log::error($e);
    return parent::report($e);
}
```
However this results in **two copies of each error arriving with Rollbar.** I believe @jenssegers put this in as you sometimes wish to report error context:

```php
\Log::error('Something went wrong', [
    'person' => ['id' => 123, 'username' => 'John Doe', 'email' => 'john@doe.com']
]);
```

**`parent::report($e)` doesn't support this currently**.

### Possible Resolution?

In `Illuminate\Foundation\Exceptions\Handler` change
```php
    public function report(Exception $e)
    {
        if ($this->shouldReport($e)) {
            $this->log->error($e);
        }
    }
```

to

```php
    public function report(Exception $e, $context = [])
    {
        if ($this->shouldReport($e)) {
            $this->log->error($e, $context);
        }
    }
```

…to match the signature in `Psr\Log\LoggerInterface` then users can either use ` return parent::report($e)` or `return parent::report($e, $context)` as required.

I have tested this locally and it appears to work, with only one copy appearing in Rollbar with the correct context, I'm unfamiliar with the exception handling mechanisms though so I haven't done a pull request - hopefully someone else can check my working and make the change if it's correct.

**Applies to:** 5.2, 5.3 (the handling method is different, but the principle is the same, the extra param needs to be added).

Related:
jenssegers/laravel-rollbar#61

**Comment by GrahamCampbell** [comment] 2016-07-20 16:50
Rollbar's recommendation looks wrong. If you're calling log first, then report, you're calling log twice because the report parent function calls it again.

**Comment by GrahamCampbell** [comment] 2016-07-20 16:51
Feel free to discuss this on the forums, or with rollbar, but closing this since it's not a bug in laravel's core. Thanks for getting in touch though.

**Closed** 2016-07-20 16:50 UTC

**Comment by gregrobson** [comment] 2016-07-20 19:38
Hi @GrahamCampbell, the quick response is much appreciated. Unfortunately my coding spidey-sense still feels like something is wrong so I did some more digging. I don't think I've explained the issue clearly enough :pensive: Perhaps if I take it from a different angle...

> Rollbar's recommendation looks wrong. If you're calling log first, then report, you're calling log twice because the report parent function calls it again.

Agreed! It is wrong, but that's only because I believe they are working around an incomplete implementation of `Psr\Log\LoggerInterface`.

Rollbar are detecting any errors by listening for any `'illuminate.log' events when they boot their service provider (I think this is the appropriate method for libraries to add additional logging outputs, but I will freely admit that I could be wrong :wink: )

```php
        $app['log']->listen(function ($level, $message, $context) use ($app) {
            $app['Jenssegers\Rollbar\RollbarLogHandler']->log($level, $message, $context);
        });
```

So far, so good. Any call to `\Log::debug($e, $context), Log::info($e, $context)` etc goes to any of the configured logging outputs (including Bugsnag... and it happens just the once).

Here's where it get's iffy when you trace it through from parent::report($e)... [apologies if this sounds pedantic, I just working this through in my own mind to make sure I haven't overlooked something.]

```php
// app/Exceptions/Handler.php calls
parent::report(Exception $e)

// …in Illuminate/Foundation/Exceptions/Handler which in the report() method does
$this->log->error($e); // where $this->log implements the interface Psr\Log\LoggerInterface - supposedly!

// this results in the following method call in Illuminate/Log/Writer.php
public function error($message, array $context = []) { // <–– Hang on, $context appeared from somewhere and can't offer it up???
}

// This then results in writeLog(…) and fireLogEvent(…) being called and then we fire an event
$this->dispatcher->fire('illuminate.log', compact('level', 'message', 'context'));
//                                                                       ^but how can
// it fire any context across? We never had the chance at the start of the trace to pass it in!
```

This slightly irks me as it just looks odd to not expose all of the interface. I'm left with an awkward choice in `app/Exceptions/Handler.php`:

1. Do I only send to Rollbar in production and ignore all other forms of logging?
2. Just call `parent::report($e)` and know that I cannot pass any context to Rollbar?
3. Call both and get duplicates in Rollbar?

^ All of these options don't seem right when there's already a feature that allows me to pass on error context and it's part of the PSR Logging spec?

I appreciate that's it's not a bug, but any logging service provider that's added to Laravel cannot take any context information unless it exposes additional methods and ignores what PSR3 offers already. It's also backwards compatible from what I can see.

If I'm still wrong, then can you advise in what general direction the Rollbar library should be angling to take context on the my error handler? I can always look to see if I can fix it from that end if required.

Thanks in advance for your time - if this comes across in any way argumentative, it's not intended that way - I'm just trying to satisfy some curiosity! (On the plus side, I now know more about Laravel's internals!)

**Comment by rdrnnr87** [comment] 2017-03-19 15:12
@GrahamCampbell perhaps we can reopen this for another look?  I agree with @gregrobson and I believe what he is trying to say is that he wishes to remove `\Log::error($e)` from the [jenssegers/laravel-rollbar](https://github.com/jenssegers/laravel-rollbar) implementation.  It's only being called because `parent::report($e)` does not support passing context which is desired when reporting errors to Rollbar.  If we modify `Illuminate\Foundation\Exceptions\Handler` report method to support passing context then `\Log::error($e)` can be removed from the [jenssegers/laravel-rollbar](https://github.com/jenssegers/laravel-rollbar) repo.

If @gregrobson is still hanging around he can send a PR or else I can.

**Comment by patrick-proulx** [comment] 2018-05-25 15:04
This is old, but I've found a solution if you're using the Rollbar Service Provider. In `report(Exception $e)`, you can add:
```
if ($user = Auth::user()) {
            app('Rollbar\RollbarLogger')->configure([
                'person' => [
                    'id'       => $user->id,
                    'username' => $user->first_name . ' ' . $user->last_name,
                    'email'    => $user->email,
                ],
            ]);
        }
```
