### ISSUE TITLE
Sometimes validation in Windows always triggered 

### ISSUE THREAD

**Issue by Jaspur** [laravel/framework#16635] opened 2016-12-03 00:59 UTC
- Laravel Version: 5.1.45
- PHP Version: 7
- Database Driver & Version: pgsql 

### Description:
The ```sometimes``` validation is in Windows (10 I tested) always triggered in Chrome, IE and Egde. Even when the fields are empty/untouched. It returns a 422 when I have the field added with: ```sometimes|required``` in the validation. 
On MacOS it works perfectly in all browsers, but not in Windows. 

### Steps To Reproduce:
- Make form
- Set validation to a random field to ```sometimes|required```
- Submit form with the field where you added _sometimes_ to and leave it untouched
- Expectation: field is ok, validation is ok
- Reality on Windows: Returns that field is required..

Looks like the field is always send in the request, even when it's not filled in.

**Comment by KKSzymanowski** [comment] 2016-12-03 18:45
If you add an input to an HTML form it will always appear in the request, even if it's empty/untouched.

**Comment by Jaspur** [comment] 2016-12-03 21:40
Then it's different on Windows and MacOS? Because tested the same form on both OS, with different results as noted in the issue.

**Comment by KKSzymanowski** [comment] 2016-12-04 16:57
I'm unable to test it on a Mac, but you can setup a simple raw PHP test to check it.
Create a pure html form which points to a PHP script and in that script just `var_dump($_POST);` to see what's getting passed into the interpreter. 

I think it's highly unlikely that it's a matter of an operating system, but if you say so, just test it.

**Comment by themsaid** [comment] 2016-12-05 13:15
This is OS dependent, HTML forms will send an empty string as a value and thus cause the fields to get validated, please print `$request->all()` and you'll see that the fields exist.

Closing since it's not a bug with laravel, further investigation on your end will make it more clear, dump the request parameters and see the request payload on different Operating Systems and please feel free to ping me if you find a difference, include the results in the comment as well.

Thanks.

**Closed by themsaid** 2016-12-05 13:15 UTC
