### ISSUE TITLE
microsoft sqlsrv driver

### ISSUE THREAD

**Issue by hamidparchami** [laravel/framework#16986] opened 2016-12-26 12:47 UTC
- Laravel Version: 5.4.#
- PHP Version: 7.0
- Database Driver & Version:

### Description:
Microsoft has released official driver for php developers and linux distributions.
Current version of database connector replaces "sqlsrv" wtih "dblib" and does not have "sqlsrv" connection string so we can not use "sqlsrv" as database driver. Please change this behavior in next version of the framework.
Thanks

**Comment by fernandobandeira** [comment] 2016-12-26 14:05
```php
if (in_array('dblib', $this->getAvailableDrivers())) {
    return $this->getDblibDsn($config);
} elseif ($this->prefersOdbc($config)) {
    return $this->getOdbcDsn($config);
} else {
    return $this->getSqlSrvDsn($config);
}
```

As you can see sqlsrv is being used when dblib isn't available, what's your suggestion here, change the order of preferrence?

**Comment by GrahamCampbell** [comment] 2016-12-26 15:30
Duplicate of previous issue.

**Comment by GrahamCampbell** [comment] 2016-12-26 15:31
Feel free to send a PR.

**Closed by GrahamCampbell** 2016-12-26 15:30 UTC
