### ISSUE TITLE
[5.2] Custom validation messages for array attributes fail on rules with multiple types

### ISSUE THREAD

**Issue by danieliancu** [laravel/framework#11614] opened 2015-12-29 22:06 UTC
When validating arrays using `*` character, if the rule applies to multiple types (numeric, file, string etc.), then even if you have defined a custom rule message for the attribute the default rule message is used.

```php
$this->validate($request, [
    'persons.*.email' => 'string|between:8,50',
]);

// validation.php
'between' => [
    'string' => 'This gets displayed',
],

'custom' => [
    'persons.*.email' => [
        'between' => [
            'string' => 'Does not work',
        ],
        'between.string' => 'Does not work',
    ],
],
```

**Comment by danieliancu** [comment] 2015-12-29 22:12
Did some further testing and it seems some logic was left out.

```php
$this->validate($request, [
    'persons.*.email' => 'string|between:8,50',
]);

// validation.php
'between' => [
    'string' => 'Message',
],

'custom' => [
    'persons.*.email' => [
        'between' => 'This works',
    ],
],
```

**Comment by danieliancu** [comment] 2015-12-29 22:15
Even though you know the type of the fields that you validate when writing the custom messages for array attributes, I think this should be correctly implemented.

```php
$this->validate($request, [
    'persons.*.email' => 'string|between:8,50',
]);

// validation.php
'between' => [
    'string' => 'This gets displayed',
],

'custom' => [
    'persons.*.email' => [
        'between' => [
            'string' => 'This should get displayed',
        ],
    ],
],
```

**Comment by progmars** [comment] 2016-01-14 08:09
I was debugging another issue described in https://github.com/laravel/framework/issues/11869
and also stumbled upon the same isse that custom messages ignore attribute types.

Currently Validator resolves custom messages as follows:

```
$customKey = "validation.custom.{$attribute}.{$lowerRule}";
$customMessage = $this->translator->trans($customKey);
```

Notice - there is no attribute type anywhere.

But if you look at the code of resolving default messages, it contains type:

```
if no custom message exists:

        elseif (in_array($rule, $this->sizeRules)) {
            return $this->getSizeMessage($attribute, $rule);
        }
...

    protected function getSizeMessage($attribute, $rule)
    {
    ...
        $type = $this->getAttributeType($attribute);
        $key = "validation.{$lowerRule}.{$type}";

```

This is the cause of the issue - with custom texts there is no code similar to getSizeMessage() for adding attribute type to the message key, and I'm not sure why it was not added to custom messages also. I'm afraid that currently it would be dangerous to change the code because it would break backwards-compatibility, but still I agree that something compatible should be implemented to check also if the custom message resolved with "validation.custom.{$attribute}.{$lowerRule}" is an array, and if it is, then try to extract type key from it.

Maybe something as follows might work:

```
$customKey = "validation.custom.{$attribute}.{$lowerRule}";

if(is_array($customKey) &&
    in_array($rule, $this->sizeRules)){
        $type = $this->getAttributeType($attribute);
        $customKey .= ".$type";
}
```

**Closed** 2016-08-12 14:30 UTC
