### ISSUE TITLE
[L5.4] Eloquent Builder getModels() function bug

### ISSUE THREAD

**Issue by overg** [laravel/framework#18538] opened 2017-03-28 12:36 UTC
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Builder.php#L461

Most likely **$this->hydrate()** should be used, instead of **$this->model->hydrate()**

**Comment by Dylan-DPC** [comment] 2017-03-28 19:32
@overg can you make a PR that rectifies the bug?

**Comment by themsaid** [comment] 2017-03-30 15:58
I guess it was done that way to allow you to define a `hydrate` method in your model if you want to change behaviour.

Closing since it's not a bug in the core, feel free to ping me though.

**Closed by themsaid** 2017-03-30 15:58 UTC
