### ISSUE TITLE
[9.x] memory exhausted because JSON payload is unwanted parsed twice by Illuminate\Http\Request::createFromBase

### ISSUE THREAD

**Issue by MircoBabin** [laravel/framework#42403] opened 2022-05-16 14:33 UTC
- Laravel Version: 9.12.2
- PHP Version: PHP 8.1.4 (cli) (built: Mar 16 2022 09:33:31) (ZTS Visual C++ 2019 x64)
- Database Driver & Version: MySql 8.0.16

### Description:

I have an api POST route with json contents. Very unexpected this route was giving  Allowed memory size of 134217728 bytes exhausted (tried to allocate ... bytes) errors.

To debug this issue:

1) I adjusted public/index.php so the request would run to the end and would not be aborted by memory exhausted errors.

```php
ini_set("memory_limit", "-1");
```

2) I attached XDEBUG in profile mode.

3) I replayed the request.

4) I used QCacheGrind to visualize the profile:

![image](https://user-images.githubusercontent.com/8981285/168610088-c9810ebd-85f7-4560-8fe5-7750d6c1a85f.png)

As the profile shows, ```Illuminate\Http\Request::createFromBase``` via ```Request->json()``` calls ```json_decode()``` twice. Which is unwanted, because I don't use the ```Request::json()``` to retrieve the json contents. I do my own ```json_decode((string) Request::getContents())```.

I did some digging in the Laravel History and found the commit introducing the json_decode behaviour in [9.x]: https://github.com/laravel/framework/commit/13e4a7ff1799ee51698faa10161b2d2af889b713 The commit message states: _... This commit solves the underlying issue without breaking compatibility with the original functionality. ..._

**This commit is breaking compatibility, because it does not take memory consumption into account. Neither does it take performance into account, decoding the same request body twice is performance degradation.** For large JSON (in my case Content-Length: 6428178) this can easily lead to memory exhausted errors. In Laravel 7.x there was no memory exhausted error.

**Comment by lk77** [comment] 2022-05-16 15:45
You can remove your json_decode and use the decoded data in the request instead

**Comment by rodrigopedra** [comment] 2022-05-17 02:44
@driesvints after doing research to answer @MircoBabin , I noted PR #37921 , which introduced the check if a request is a JSON request before replacing its `$request` property, apparently didn't change anything as `Request@getInputSource` already did that check internally.

Actually the tests (one changed, and one added) on that PR, both passes if one reverts the change made by it.

I am not sure it makes any change if reverted, as for non-JSON requests `Request@getInputSource` would return the contents of `$request->request` anyways which are already populated on the `Request@duplicate` call some lines above, but it is curious tests passed without the proposed change.

I have no idea on how to do so, but maybe there is a way to automate to check if any added tests fail before committing a PR's proposed change?

**Comment by driesvints** [comment] 2022-05-17 07:20
Thanks @rodrigopedra.

@LukeTowers could you weigh in here?

**Comment by MircoBabin** [comment] 2022-05-17 07:55
I have taken @IK77 advice and do not json_decode() myself anymore. Instead i'm using Request::json() now.

But still I'm getting memory exhausted because Laravel is **decoding twice**. Here is new the profile:

![image](https://user-images.githubusercontent.com/8981285/168759435-de55e1b8-5ba4-4662-87dc-7eff6c11d6f1.png)

**Comment by MircoBabin** [comment] 2022-05-17 08:14
@rodrigopedra thanks for you detailed explanation. So it seems I'm wrong concluding https://github.com/laravel/framework/commit/13e4a7ff1799ee51698faa10161b2d2af889b713 was the commit introducing wrong behaviour.

Your solution to extend the ```Illuminate/Http/Request```, while being a very creative solution, is not really a viable solution. Upon each Laravel update I still would have to compare the ```Request::createFromBase``` with the extended class. 

Walking this path it would be easier to just directly modify the ```Illuminate/Http/Request.php``` source file, what would break with each Laravel update. I could write a test for this, that would fail after update. But I'm not going to take this path, as it is not maintainable in the long run. (Yep against all best practices, I am committing the ```vendor``` directory. Because on shared webhosting you can't  ```composer install```, there is no shell. Using DeployHQ ftp deployment with a committed ```vendor``` directory is the easiest solution.)

**Comment by driesvints** [comment] 2022-05-17 11:21
To be fair, isn't the real issue that your JSON payloads are simply too large? What kind of payloads are you handling?

**Comment by MircoBabin** [comment] 2022-05-17 12:43
The payloads are order request payloads for renting a touringcar. In the payload also is the calculated Google Maps route present. That together constitutes a lot of bytes.

The http-payload is ~7 MB, which is not that big. Json_decoded() it becomes ~69MB, which still is not beyond default PHP limits.

But then comes Laravel, deciding to **decode twice** and keeping 2 copies in memory. So claiming 2 times 69MB which is beyond the default PHP limits.

**Comment by LukeTowers** [comment] 2022-05-17 16:36
> after doing research to answer @MircoBabin , I noted PR #37921 , which introduced the check if a request is a JSON request before replacing its `$request` property, apparently didn't change anything as `Request@getInputSource` already did that check internally.

> I am not sure it makes any change if reverted, as for non-JSON requests Request@getInputSource would return the contents of $request->request anyways which are already populated on the Request@duplicate call some lines above, but it is curious tests passed without the proposed change.

@rodrigopedra thanks for your detailed response! My change however is absolutely critical, although it might not appear so at first glance which is why the original behaviour was so dangerous. 

The problem is that the internal `request` property is intended to only hold POST parameters; while `Request@getInputSource` will return GET parameters (the `query` property) if the request method is GET or HEAD. This means that any calls to Laravel's methods asking for POST data on a GET request would return GET data previously (i.e. `Request::post('somevar');` would return the value of `?somevar=bad` on GET requests). The `Request@duplicate` call above does not have this problem because the `request` and `query` parameters are properly separated during the duplication process.

Ultimately there are two things to keep in mind:
1. The `Request->request` property should ONLY ever hold POST data
2. The `Request@getInputSource()` method returns data from different locations depending on the type of request made.

**Comment by LukeTowers** [comment] 2022-05-17 16:39
@MircoBabin where is Laravel calling json_decode twice? I'm not seeing it in the source.

**Comment by rodrigopedra** [comment] 2022-05-17 21:31
@MircoBabin , I am not familiar with the call trace visualization tool you are using, but comparing the two screenshots you posted, it is not clear to me, in the last one, that `json_decode()` is called twice.

I apologize in advance if it is a lack of familiarity with the tool. 

On the other hand, if you can provide a clearer spot where `json_decode()` is called multiple times, it would be helpful to help you out on this.

**Comment by LukeTowers** [comment] 2022-05-18 00:14
@rodrigopedra I also find it odd that the test passed without the change applied, when I made the PR the test failed without the change.

**Comment by MircoBabin** [comment] 2022-05-18 05:14
@rodrigopedra @LukeTowers I have adjusted ```\Illuminate\Http\Request.php - function json()``` to write logging:

```php
/**
     * Get the JSON payload for the request.
     *
     * @param string|null $key
     * @param mixed       $default
     *
     * @return \Symfony\Component\HttpFoundation\ParameterBag|mixed
     */
    public function json($key = null, $default = null)
    {
        if (!isset($this->json)) {
            static $calledCount = 0;
            ++$calledCount;
            file_put_contents('c:\\incoming\\out-of-memory.'.$calledCount.'.log', (strval(new \Exception('\Illuminate\Http\Request.php function json() is called - executing json_decode()'))));
            $this->json = new ParameterBag((array) json_decode($this->getContent(), true));
        }

        if (is_null($key)) {
            return $this->json;
        }

        return data_get($this->json->all(), $key, $default);
    }

```

2 files are written:

1)
```
Exception: \Illuminate\Http\Request.php function json() is called - executing json_decode() in D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Http\Request.php:377
Stack trace:
#0 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Http\Request.php(462): Illuminate\Http\Request->json()
#1 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Http\Request.php(67): Illuminate\Http\Request::createFromBase(Object(Symfony\Component\HttpFoundation\Request))
#2 D:\Projects\Webpage\tripportals\public\index.php(83): Illuminate\Http\Request::capture()
#3 {main}
```

2)
```
Exception: \Illuminate\Http\Request.php function json() is called - executing json_decode() in D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Http\Request.php:377
Stack trace:
#0 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Http\Request.php(462): Illuminate\Http\Request->json()
#1 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Routing\CompiledRouteCollection.php(155): Illuminate\Http\Request::createFromBase(Object(Illuminate\Http\Request))
#2 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Routing\CompiledRouteCollection.php(114): Illuminate\Routing\CompiledRouteCollection->requestWithoutTrailingSlash(Object(Illuminate\Http\Request))
#3 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Routing\Router.php(680): Illuminate\Routing\CompiledRouteCollection->match(Object(Illuminate\Http\Request))
#4 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Routing\Router.php(667): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#5 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Routing\Router.php(656): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#6 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#7 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#8 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 D:\Projects\Webpage\tripportals\app\Http\Middleware\CheckDatabaseConnections.php(79): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): App\Http\Middleware\CheckDatabaseConnections->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 D:\Projects\Webpage\tripportals\app\Http\Middleware\Cors.php(32): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): App\Http\Middleware\Cors->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Http\Middleware\TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Http\Middleware\TrustHosts.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Http\Middleware\TrustHosts->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 D:\Projects\Webpage\tripportals\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#23 D:\Projects\Webpage\tripportals\public\index.php(83): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#24 {main}
```

**Comment by MircoBabin** [comment] 2022-05-18 06:23
The problem is in ```Illuminate\Routing\CompiledRouteCollection.php - function requestWithoutTrailingSlash()```. 

```php
    /**
     * Get a cloned instance of the given request without any trailing slash on the URI.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Request
     */
    protected function requestWithoutTrailingSlash(Request $request)
    {
        $trimmedRequest = Request::createFromBase($request);

        $parts = explode('?', $request->server->get('REQUEST_URI'), 2);

        $trimmedRequest->server->set(
            'REQUEST_URI', rtrim($parts[0], '/').(isset($parts[1]) ? '?'.$parts[1] : '')
        );

        return $trimmedRequest;
    }
```

1) it calls ```Request::createFromBase``` with an ```\Illuminate\Http\Request```, which already did a internal ```json()``` and so already contains 69MB.
2) ```Request::createFromBase``` expects a ```Symfony\Component\HttpFoundation\Request```. Because it is unaware of the already decoded json body, it's decoding again. Claiming again 69MB memory.

Adjusting ```Request::createFromBase``` prevents the double json_decode(). But because the ParameterBag is not really copied/cloned I'm unsure if this is really a valid solution.

```php
    /**
     * Create an Illuminate request from a Symfony instance.
     *
     * @return static
     */
    public static function createFromBase(SymfonyRequest $request)
    {
        $newRequest = (new static())->duplicate(
            $request->query->all(), $request->request->all(), $request->attributes->all(),
            $request->cookies->all(), $request->files->all(), $request->server->all()
        );

        $newRequest->headers->replace($request->headers->all());

        $newRequest->content = $request->content;

        if ($newRequest->isJson()) {
            if ($request instanceof self) {
                $newRequest->request = $request->json();
                $newRequest->json = $request->json; // Unsure if this is allowed, because this is a ParameterBag
            } else {
                $newRequest->request = $newRequest->json();
            }
        }

        return $newRequest;
    }
```

**Comment by rodrigopedra** [comment] 2022-05-18 06:41
@MircoBabin can you test changing the first line of `CompiledRouteCollection@requestWithoutTrailingSlash`

from:

~~~php
$trimmedRequest = Request::createFromBase($request);
~~~

to:

~~~php
$trimmedRequest = $request->duplicate();
~~~

And see if it fixes it?

**Comment by MircoBabin** [comment] 2022-05-18 06:47
@rodrigopedra I can confirm after changing ```function requestWithoutTrailingSlash()```, there is no double json_decode() anymore.

**Comment by rodrigopedra** [comment] 2022-05-18 07:09
@MircoBabin I sent PR #42420 to make this change.

Thanks for tracing the spots so we could find where the double encoding happened =)

**Comment by MircoBabin** [comment] 2022-05-18 07:22
@rodrigopedra The PR targets the [8.x] branch. Can it also target the [9.x] branch ? Because that's the version I'm using.

Or must the PR first be accepted on the [8.x] branch and will then later be targeted at the [9.x] branch and future [10.x] branch ? Sorry for the question, I don't know how the Laravel project is handling patches on multiple versions.

**Comment by driesvints** [comment] 2022-05-18 07:35
@MircoBabin all fixes for 8.x are merged upstream to newer versions.

**Comment by rodrigopedra** [comment] 2022-05-18 07:38
@MircoBabin as it is a bugfix it should target the 8.x, as this branch is still in bugfix support. 

Complementing what @driesvints said, changes in 8.x are merged into 9.x before each weekly release.

**Comment by LukeTowers** [comment] 2022-05-18 20:27
@MircoBabin excellent work tracking down the issue and great final solution @rodrigopedra! Glad to see the issue resolved with a general win for Laravel performance :)

**Comment by driesvints** [comment] 2022-05-19 07:19
Will be fixed in the next release. Thanks all.

**Closed by driesvints** 2022-05-19 07:19 UTC
Labels: bug, help wanted
