### ISSUE TITLE
Using other column(s) instead of 'name' while sending mail

### ISSUE THREAD

**Issue by gauravmak** [laravel/framework#15329] opened 2016-09-08 06:12 UTC
- Laravel Version: 5.3.6
- PHP Version: 7.0.9

### Description:
If model has `first_name` + `last_name` columns instead of `name` column, how could we use them for specifying recipient name while [sending mail](https://laravel.com/docs/5.3/mail#sending-mail)

**Comment by themsaid** [comment] 2016-09-08 06:32
In that case you need to do:

```
Mail::to($request->user()->email, $request->user()->fullName)
```

Or something similar.

Laravel is shipped with some conventions to cover the most common case, but it's flexible enough for changes.

Closing since it's not a bug report :)

Thank you

**Closed by themsaid** 2016-09-08 06:32 UTC

**Comment by gauravmak** [comment] 2016-09-08 06:43
Thanks, @themsaid. I had managed to do it other way when I wanted to send an email to single customer.

```
...
$customer->name = $customer->first_name.' '.$customer->last_name;
Mail::to($customer)->send(new ConfirmCustomerRegistration($customer, $verifyToken));
```

What can be done when there is need to send an email to multiple customers?

**Comment by themsaid** [comment] 2016-09-08 07:06
hmmm I guess you can do it similarly, map on the collection of users and generate a name.

**Comment by luke-nehemedia** [comment] 2017-12-11 18:28
I ran into the same problem. 

It would be great to have a `getName() `and `getEmail()` method on the model that returns "`$this->name/email`" by default but is overwritable.
