### ISSUE TITLE
Forcing A Unique Rule To Ignore A Given ID 

### ISSUE THREAD

**Issue by iamayaz** [laravel/framework#15518] opened 2016-09-20 12:00 UTC
- Laravel Version: 5.2.
- PHP Version: 5.4.6

### Description:

I have table in which i'm trying to store email addresses. These email addresses will be save with user_id.

For example in email_list table

```
|ID | user_id |         email          |
...............................
| 1 | 101     | john@gmail.com |
...............................
| 2 | 102     | john@gmail.com |
```
In above table you can see same email addresses save with different user_id, that's it what i'm trying to do.

Currently i'm trying simple laravel validation like this.

```
$this->validate($request, [
            'email' => 'unique:email_list,email,102,user_id ',
]);
```

So is there any way to check already exist email addresses if row has same user_id? I'm using laravel 5.2. I would like to appreciate if someone guide me. Thank you

**Comment by themsaid** [comment] 2016-09-20 12:01
`'email' => 'unique:email_list,email,'.$user->id` ?

**Comment by iamayaz** [comment] 2016-09-20 12:03
What value has $user-> ?

**Comment by themsaid** [comment] 2016-09-20 12:04
Replace `$user->id` with the primary key you want to ignore, here it's the user_id.

I'm closing since this is not a bug report, however feel free to ask on the forums or ping me if you need further help.

**Comment by iamayaz** [comment] 2016-09-20 12:05
@themsaid  i'm not validating with primary id as you can see in the table

**Closed by themsaid** 2016-09-20 12:04 UTC

**Comment by themsaid** [comment] 2016-09-20 12:59
You example was correct then:

```
'email' => 'unique:email_list,email,102,user_id ',
```

**Comment by iamayaz** [comment] 2016-09-20 13:03
@themsaid yes that's why i'm asking here, because when i'm trying to add same email (john@gmail.com) with user_id = 105 then its return error 'The email has already been taken.'. However it should not return error because i'm adding with different user_id

**Comment by themsaid** [comment] 2016-09-20 13:09
You're ignoring `102` but there's another record with ID `101`

**Comment by iamayaz** [comment] 2016-09-20 13:10
@themsaid Aaahhhh... it's means i have to mentioned all exist id's as well ?

**Comment by themsaid** [comment] 2016-09-20 13:28
I don't think you can ignore multiple IDs, only 1.

I guess you'll need to create your own validation rule.

**Comment by iamayaz** [comment] 2016-09-20 13:33
@themsaid Thank you so much, i'm going to try. If you have time then kindly save my time, I would like to appreciate. 👍
