### ISSUE TITLE
using Redis driver for queue, and problem with notifications.

### ISSUE THREAD

**Issue by igunultas** [laravel/framework#29260] opened 2019-07-22 21:11 UTC
- Laravel Version: 5.8
- PHP Version: 7.3.6
- Database Driver & Version: MARIADB

### Description:

While using Redis as a queue driver, and trying to send notification to broadcast it just ignores **receivesBroadcastNotificationsOn** on the model that has notifiable trait.

it keeps sending notifications to channel App.User.{userid} 
instead of what **receivesBroadcastNotificationsOn** returns

if I use **sync** or **sqs** driver it just work fine.

### Steps To Reproduce:

Create notification
Add **receivesBroadcastNotificationsOn** to model
set queue driver to Redis

**Comment by samuhay** [comment] 2019-07-23 11:11
https://laravel.com/docs/5.4/notifications#listening-for-notifications

**Comment by igunultas** [comment] 2019-07-23 11:22
@samuhay

Thanks for your reply BUT

The version im currently on is 5.8 and you are sending me the 5.4 docs, which doesn't resolve my issue since the code works with sqs and sync drivers.

**Comment by samuhay** [comment] 2019-07-23 14:16
I think it is because you have customized the Notification channel using receivesBroadcastNotificationsOn() in User model and you are listening event on App.User.* not on user.*

So just remove receivesBroadcastNotificationsOn() from the User model and check again.

Hope this helps Can you share code ?

**Comment by igunultas** [comment] 2019-07-23 14:43
`notifications.${this.userdata.userid}.${this.userdata.company}`
this is the channel im listening.

`  public function receivesBroadcastNotificationsOn()
    {
        return "notifications.".$this->id.".".$this->company;
    }`

this is the function on user model that uses Notifiable trait.

you are misunderstanding what im saying.

if I have something misconfigured it would not work on sqs or sync driver aswell.

**Comment by driesvints** [comment] 2019-08-01 12:47
Maybe related to https://github.com/laravel/framework/issues/28701 ?

**Comment by igunultas** [comment] 2019-08-04 23:02
@drievints 

I have tried couple more combinations, but there was no luck at all. it was showing the same behavior. 

and I moved on didn't change anything about it since I decided to give it a try for Redis once more. rebooted both Redis and ec2 than it started working, no idea why but I think there is some caching going on.

I tried to dig deeper on framework and checked the files that are responsible for queueing but didn't see any caching so far. 

since you are Laravel maintainer would you please try to guess what would be causing the issue, I would love to read your comments.

thank you.

**Comment by driesvints** [comment] 2019-08-05 11:13
@igunultas did you read the issue I linked to?

**Comment by LarryMckuydee** [comment] 2019-08-07 10:17
@igunultas

It's work for me though, I'm using laravel 5.8.27
perhaps you should check if the **queue connection and broadcast driver** really using **redis**. 
Also **specify** that custom **private channel** in **routes/channel.php**

**Comment by driesvints** [comment] 2019-08-08 13:38
I'm going to close this as a duplicate of https://github.com/laravel/framework/issues/28701

I've already looked into it but currently stuck on figuring out where the messages get pulled back out from Redis. Any help is appreciated.

**Closed by driesvints** 2019-08-08 13:38 UTC
Labels: needs more info
