### ISSUE TITLE
Laravel 5.1+ PHP7 Error - Uncaught ReflectionException: Class log does not exist

### ISSUE THREAD

**Issue by allanfreitas** [laravel/framework#11724] opened 2016-01-06 18:01 UTC
I'm getting this error when I try to deploy my app with rocketeer:

Situations with **PHP 7** - Centos7 (all extensions required installed):
* create a fresh laravel app with composer: **ERROR**
* create a fresh laravel app with laravel installer: **ERROR**
* clone my app, and execute composer install(with and without options): **ERROR**

Situations with **PHP 5.6** - Centos7 (all extensions required installed):
* create a fresh laravel app with composer: **OK**
* create a fresh laravel app with laravel installer: **OK**
* clone my app, and execute composer install(with and without options): **OK**

```php
> php artisan clear-compiled
[USER@IP] (production) PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /home/apps/deploy/MYAPP/releases/20160106145128/vendor/laravel/framework/src/Illuminate/Container/Container.php:736
Stack trace:
#0 /home/apps/deploy/MYAPP/releases/20160106145128/vendor/laravel/framework/src/Illuminate/Container/Container.php(736): ReflectionClass->__construct('log')
#1 /home/apps/deploy/MYAPP/releases/20160106145128/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('log', Array)
#2 /home/apps/deploy/MYAPP/releases/20160106145128/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('log', Array)
#3 /home/apps/deploy/MYAPP/releases/20160106145128/vendor/laravel/framework/src/Illuminate/Container/Container.php(845): Illuminate\Foundation\Application->make('log')
#4 /home/apps/deploy/MYAPP/releases/20160106145128/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): Illuminate\Containe in /home/apps/deploy/MYAPP/releases/20160106145128/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 736
[USER@IP] (production) Script php artisan clear-compiled handling the post-install-cmd event returned with an error
```

**Comment by GrahamCampbell** [comment] 2016-01-06 18:10
Is there any chance you could intercept the exception so we can see the real error, instead of the error caused when we try and fail to log the actual error.

**Comment by dhardtke** [comment] 2016-01-06 18:27
I am running Laravel 5.2 with PHP 7.0 without any problems. Composer also runs fine.

**Comment by EliasZ** [comment] 2016-01-06 19:01
@GrahamCampbell What exactly is the issue with that log failure? A lot of stacktraces are showing that 'class log does not exist' stuff.

**Comment by GrahamCampbell** [comment] 2016-01-06 19:23
> What exactly is the issue with that log failure? A lot of stacktraces are showing that 'class log does not exist' stuff.

It's because an exception is thrown before the logger is setup, then we try to use the logger to log the exception which causes another exception.

> I am running Laravel 5.2 with PHP 7.0 without any problems. Composer also runs fine.

So am I, but it's not working for @allanfreitas.

**Comment by allanfreitas** [comment] 2016-01-06 19:40
@GrahamCampbell Its executed the  "php artisan clear-compiled" right after the "composer install" how can I intercept in this case??rsrs

**Comment by GrahamCampbell** [comment] 2016-01-06 20:10
Just run composer with `--no-scripts`, then edit the exception handler, then run that command manually.

**Comment by schulzefelix** [comment] 2016-01-07 08:06
Sounds familiar to my problem, maybe you should check that solution too .... https://github.com/laravel/framework/issues/11673

If not, just ignore me.

**Comment by GrahamCampbell** [comment] 2016-01-07 10:35
> Sounds familiar to my problem, maybe you should check that solution too .... #11673

No it doesn't, because it works just fine on php 5.

**Comment by allanfreitas** [comment] 2016-01-07 11:15
@GrahamCampbell I needed to downgrade the php to 5.6 for this case, but I will deploy another centos 7 server in 5 days(12/jan), so I will make this test of --no-scripts with the same code, and report back.

**Comment by gildniy** [comment] 2016-01-13 17:32
I meet the same problem, I use Windows 10 with Laravel Homestead7 (on Vagrant Homestead) with L.5.2.6 and L5.2.8. Some people said this is caused by the space in .env file but I think here it's something else (I have no space nor special charactor in my .env file). Could any one find a durable solution!?

**Comment by GrahamCampbell** [comment] 2016-01-13 17:34
Until someone can give me the ACTUAL error message, there's nothing I can do to fix this.

**Comment by gildniy** [comment] 2016-01-13 17:40
IDK really if am wrong to ask this, but how/which other message we may show apart from that give by @allanfreitas starting this threat?

**Comment by GrahamCampbell** [comment] 2016-01-13 18:54
> IDK really if am wrong to ask this, but how/which other message we may show apart from that given by @allanfreitas starting this threat?

That error message is the one thrown when we fail to log the actual exception. You need to intercept the actual exception and give us the details.

**Comment by gildniy** [comment] 2016-01-13 20:05
How can I intercept that? steps to follow!

**Comment by GrahamCampbell** [comment] 2016-01-13 20:08
> How can I intercept that? steps to follow!

Mess with the error handler.

**Comment by gildniy** [comment] 2016-01-14 02:57
Got it working on the new build 5.2.10 and I moved on Xampp!

**Comment by ericbarnes** [comment] 2016-01-16 20:07
I ran into this today and this was the problem for me:

> Some people said this is caused by the space in .env file

**Comment by GrahamCampbell** [comment] 2016-01-16 20:32
@ericbarnes  That's definitely not the issue, because such a problem would also be failing on php 5.x, and this issue specifically says that it's only happening on 7.x. You were running into a different issue which also ends up crashing the exception handler.

**Comment by GrahamCampbell** [comment] 2016-01-17 10:47
@allanfreitas Are you able to provide me with the details of your original error? If not, there's nothing we can do, and I'll have to close this.

**Comment by allanfreitas** [comment] 2016-01-17 11:19
@GrahamCampbell I don't setup the another server yet, you can close this issue for now, but I will setup the server as soon as I can, i will post what you asked here. Thanks for now.

**Closed** 2016-01-17 11:35 UTC

**Comment by JaffParker** [comment] 2016-02-02 19:00
I intercepted the error handler and the actual error is quite similar:

> Class env does not exist

Trace shows that it happens when I try to call `\App::environment()` in the config file. Everything worked when I removed it.

**Comment by kadinho** [comment] 2016-02-03 12:11
I don know if helps but i got the same issue and i solved the issue changing config/services.php :

from:

```
    'facebook' => [
        'redirect' => env('FACEBOOK_REDIRECT_URL',url('/login/facebook')) 
    ],
```

to:

```
    'facebook' => [
        'redirect' => env('FACEBOOK_REDIRECT_URL','http://site.com/login/facebook') 
    ],
```

env() function is not supporting url() inside default value :/

**Comment by geea789** [comment] 2016-02-14 08:36
this means some error occurred but laravel was unable to write the error to the log. 
which means some php error occurred that laravel or the composer cant display. 
thus you need to check your server error log. find the problem and fix it. :)

**Comment by timfeid** [comment] 2016-02-23 15:10
Make sure you've installed PDO, Memcached, and all the required extensions for php7
