### ISSUE TITLE
[5.4] ambiguous updated_at column on relationship

### ISSUE THREAD

**Issue by derpoho** [laravel/framework#18142] opened 2017-02-27 21:14 UTC
- Standalone illuminate/database: 5.4.13
- PHP Version: 7.1
- Database Driver & Version: Mysql 5.7

### Description:
When creating a BelongsToMany Relationship and then trying to delete all related models, it fails with: 
```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'updated_at' in field list is ambiguous (SQL: update `group` inner join `user_group` on `group`.`id` = `user_group`.`group_id` set `group`.`deleted_at` = 2017-02-27 21:04:25, `updated_at` = 2017-02-27 21:04:25 where `user_group`.`user_id` = 1 and `group`.`deleted_at` is null)
```

### Steps To Reproduce:
- Create a User Model
- Create a belongsToMany Relationship with a X Model
- Create a belongsToMany Relationship with a Y Model
- Timestamps on all Models enabled (created_at, updated_at, deleted_at)
- enable Softdeletes for all Models
- cast as dates: (created_at, updated_at, deleted_at)
- attach some X Models and some Y Models to the User
- add a reset method to the User Model
- execute within reset:
```
$this->x()->delete();
$this->y()->delete();
```

Both queries fail with the ambiguous updated_at. If you look at the error you can see the missing `group`. in front of updated_at.

Edit: 
When i execute `->forceDelete()` instead of `->delete()` it works like a charm.

Thanks!

**Comment by themsaid** [comment] 2017-03-02 14:14
Duplicate of https://github.com/laravel/framework/issues/13909

**Closed by themsaid** 2017-03-02 14:14 UTC

**Comment by molliapu** [comment] 2019-03-14 16:01
Thanks!
