### ISSUE TITLE
ResetsPassword

### ISSUE THREAD

**Issue by kaxias** [laravel/framework#18273] opened 2017-03-09 01:58 UTC
it is possible to create this function on ResetsPasswords.php
```PHP
    /**
     * The user has been authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  mixed  $user
     * @return mixed|void
     */
    protected function authenticated(Request $request, $user)
    {
        //
    }
```
and change this too

```PHP
    /**
     * Get the response for a successful password reset.
     *
     * @param  string  $response
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function sendResetResponse($response)
    {
        return $this->authenticated(request(), request()->user()) ?: redirect($this->redirectPath())
                            ->with('status', trans($response));
    }
```

thanks

**Comment by themsaid** [comment] 2017-03-09 06:47
You can override the `sendResetResponse` in your ResetPasswordController if you wish. Closing since it's not a bug report.

**Closed by themsaid** 2017-03-09 06:47 UTC
