### ISSUE TITLE
Syntax Error with Laravel 5.5 and PHP 7.0.27 within Mail function

### ISSUE THREAD

**Issue by kikky7** [laravel/framework#22955] opened 2018-01-29 20:46 UTC
- Laravel Version: 5.5.32
- PHP Version: 7.0.27

### Description:
`Parse error: syntax error, unexpected '?', expecting variable`
in
`/vendor/symfony/css-selector/XPath/Extension/AttributeMatchingExtension.php`

### Steps To Reproduce:
It happens when I am trying to send an email using Mail::to()...

It doesn't happen with PHP 7.1.8.
How to fix this issue without downgrading Laravel version (with 5.4 worked, as I recall) or changing PHP (because this version is on shared server and I am unable to change it)

**Comment by laurencei** [comment] 2018-01-29 21:37
Did it give a line number?

Are you sure your running PHP7? That looks alot like PHP5.6 trying to run PHP7 code...

**Comment by kikky7** [comment] 2018-01-29 21:42
Yes, it is 7.0.27.
The error is occurred on lines: 46, 51, 56
`?string $value`
this new nullable type syntax is introduced since php 7.1, but Laravel 5.5 requires at least 7.0, not 7.1, hence the issue...

**Comment by laurencei** [comment] 2018-01-29 21:58
ping @GrahamCampbell - your the composer expert 😄 .

**Comment by laurencei** [comment] 2018-01-29 22:00
actually - @kikky7  - did you run `composer install` on the PHP7.1 system, then copy this to a PHP7.0 system?

Because technically the `composer.json` of `css-selector` has a restraint of `PHP7.1` - so you shouldnt get that version anyway.

**Comment by kikky7** [comment] 2018-01-29 22:11
Composer packages are only installed and updated locally on 7.1 and copied to server, where is 7.0.
I ran fresh composer install and still getting css-selector with 7.1 syntax.

I will manage to get 7.1 on server, but it would be nice to have some other solution also.

**Comment by laurencei** [comment] 2018-01-29 22:13
> Composer packages are only installed and updated locally on 7.1 and copied to server, where is 7.0.

Yeah - you cant do this. The problem is composer is installing packages that need PHP `7.1` - because you are running `PHP7.1`.

If you want to run on `PHP7.0`- then you *must* run composer on the `PHP7.0` machine, and it will handle it correctly for you.

**Comment by GrahamCampbell** [comment] 2018-01-29 22:22
You need to use the platform config to lock to the version of php you want to use:

```json
{
    ...
    "config": {
        "platform": {
            "php": "7.0.27"
        },
    ...
    },
    ...
}
```

**Comment by GrahamCampbell** [comment] 2018-01-29 22:22
That way, when you generate a lock file on a newer version of php, you dependencies will still work on php 7.0.27.

**Comment by GrahamCampbell** [comment] 2018-01-29 22:23
You can also require `"symfony/lts": "^3.0",` to stop composer from resolving any symfony 4 dependencies. It'll make it resolve 3.4 LTS.

**Closed by GrahamCampbell** 2018-01-29 22:22 UTC

**Comment by nathanpurcell** [comment] 2018-03-15 13:03
As far as I can see nullable types were only added to PHP in v7.1, but the required version is >=7.0.0
The issue appears to be with Symfony, but if Laravel 5.5 is a LTS version perhaps the PHP requirement should be updated to 7.1?

**Comment by devcircus** [comment] 2018-03-15 13:43
See the above comments. The dependencies are correct.

**Comment by pixelzdesign** [comment] 2018-03-17 19:52
@GrahamCampbell Where to put this "symfony/lts": "^3.0"?

**Comment by laurencei** [comment] 2018-08-31 06:44
@Rolice - no, because Composer will detect those packages and install PHP 7.0 equilivant for Symfony.

**Comment by Rolice** [comment] 2018-08-31 11:27
It is strage as it is brand new Docker image with `composer install` and it breaks. Could be some version overlapping issue, though. I have used `composer new project` to create the project with specific version of Laravel.
