### ISSUE TITLE
Route caching makes new improved Automatic Scoping not work for more than 2 bindings.

### ISSUE THREAD

**Issue by AramZahedi** [laravel/framework#31785] opened 2020-03-06 00:47 UTC
- Laravel Version: 7.0.4
- PHP Version: 7.4.3

### Description:
Laravel 7 comes with a new feature called Automatic Scoping that allows users to bind a child model to the parent model in that specific route using CUSTOM KEY parameters.
For example, look at the route below:

`'profile/{user:username}/posts/{post:id}'`

That means the action only executes if the provided post belongs to the user in that route, or throws NotFound exception if it doesn't.
This can be used for any level of binding this way, like:

`'profile/{user:username}/posts/{post:id}/comments/{comment:id}'`

Here we have 3 custom parameters that each one must correspond to the parent parameter.

**THIS WORKS PERFECTLY UNTIL WE CACHE THE ROUTES**

This feature is not supported for multiple bindings after the routes have been cached.
It still supports `'profile/{user:username}/posts/{post:id}'` that has 2 custom keyed parameters, but no longer this one, which has 3:
`'profile/{user:username}/posts/{post:id}/comments/{comment:id}'`

### Steps To Reproduce:

1. Add this block of code to your web.php router file:
```php
Route::get('profile/{user:username}/posts/{post:id}/comments/{comment:id}',
    'HomeController@show')->name('custom-route');
```

2. Prepare your models, factories, controllers, and migrations like the ones in this gist:

> https://gist.github.com/AramZahedi/7b5dfd730f9bd5bfcff1548712228826

3. Run the migrations using:

`php artisan migrate`

4. Run the test in `Test.php` file. Output:

**It should pass.**

5. Now cache the routes in the command line using:

`php artisan cache:route`

6. Then run the test in `Test.php` file again now.

**YOU'LL GET AN ERROR.** HTTP status 200 returned instead of 404. That means it passes the 2nd check for route parameters automatic scoping WHICH MUST FAIL. We have provided a comment which doesn't belong to the provided post.

That would work if we provided the username of a user that the post didn't belong to.

> '{user1}/posts/{postOfUser2}'

Yes, that would throw NotFound exception.
But that's wouldn't when the URL was as follows:

> '{user1}/posts/{post1OfUser1}/{commentOfNotPost1}'

Because the bug doesn't appear for the two first bindings. It shows up for 3+ bindings with automatic scoping.

**Comment by driesvints** [comment] 2020-03-06 13:59
@AramZahedi I can't reproduce with the above example. The test passes for me with route caching. Can you maybe create a test repo which I can pull down?

**Comment by AramZahedi** [comment] 2020-03-06 14:22
@driesvints Ah, that's weird. Sure, I'll create a test and let you know.

**Comment by driesvints** [comment] 2020-03-06 14:27
@AramZahedi we also just released 7.0.5, can you try with that version as well?

**Comment by AramZahedi** [comment] 2020-03-06 14:35
@driesvints I upgraded and rechecked it right now. I can still see the bug. Let me create a test repo so you can see the bug in action.

**Comment by iamine** [comment] 2020-03-06 14:42
@AramZahedi the test must be something like that, one for a valid 200 response, and one for invalid 404 response

you are right without route:cache, it works fine, but with route:cache the test fail

```php
        $user = factory(User::class)->create();
        
        $post_1 = factory(Post::class)->create([
            'user_id' => $user->id
        ]);

        $post_2 = factory(Post::class)->create([
            'user_id' => $user->id
        ]);

        $comment_for_post_1 = factory(Comment::class)->create([
            'post_id' => $post_1->id
        ]);

        $comment_for_post_2 = factory(Comment::class)->create([
            'post_id' => $post_2->id
        ]);

        $validUrl = route('custom-route', [
            'user' => $user->username,
            'post' => $post_1->id,
            'comment' => $comment_for_post_1->id
        ]);

        $invalidUrl = route('custom-route', [
            'user' => $user->username,
            'post' => $post_1->id,
            'comment' => $comment_for_post_2->id
        ]);

        $this->get($validUrl)->assertStatus(200);
        $this->get($invalidUrl)->assertStatus(404);
```

**Comment by AramZahedi** [comment] 2020-03-06 14:46
@iamine Thanks for the test update. I'll include that in the test repo I'm creating.
Exactly as you say. It works perfectly without caching but breaks after the routes have been cached.

**Comment by driesvints** [comment] 2020-03-06 14:59
@AramZahedi make sure you commit your custom changes in a different commit from the base Laravel skeleton.

**Comment by AramZahedi** [comment] 2020-03-06 16:14
I created a repo and added every necessary files and test to it. Here is the link:

> https://github.com/AramZahedi/laravel-7-route-caching-bug

One weird thing is that I cannot reproduce the problem I had,
**You ask why?!** Because there is now another bug in routes model binding.
This new bug always appears, no matter you cache the routes or not.

Custom keys parameters don't work now, at least for the route I've written in the router. You get a ModelNotFound when you call the route with the custom parameter you've defined instead of ID.

Please clone my repo and run both of the tests I have put in the repo.
You can see the new bug clearly if you run `CustomKeyBugTest.php` test file.

**Comment by taylorotwell** [comment] 2020-03-06 19:23
Works fine for me...

![image](https://user-images.githubusercontent.com/463230/76115393-b2162c80-5fad-11ea-878d-d7a122cab016.png)

**Comment by taylorotwell** [comment] 2020-03-06 19:27
Actually I get a 404 when cached.

**Comment by AramZahedi** [comment] 2020-03-06 19:41
@taylorotwell I get 404 even when not cached.

Did you clone my repo and run the tests?

It didn't show up when not cached before, but now I see it even without caching the routes.

**Comment by taylorotwell** [comment] 2020-03-06 19:42
Sorry don't get 404 when not cached.

**Comment by taylorotwell** [comment] 2020-03-06 19:49
Can you pull down my latest commit to framework and try it: https://github.com/laravel/framework/commit/af806851931700e8dd8de0ac0333efd853b19f3d

**Comment by AramZahedi** [comment] 2020-03-06 19:52
Let me test. I'll update you in a minute

**Comment by AramZahedi** [comment] 2020-03-06 20:04
@taylorotwell That commit seems to have solved the problem.

I added the lines manually on my main project (which had the bug only when routes were cached) and now it works even when cached.

But I wonder why it didn't have any effect on my test repo! Does it lack something maybe?!

Anyway, that solved the problem in the main project I'm working on. Wanna release it as a new update?

**Comment by iamine** [comment] 2020-03-06 20:11
@AramZahedi the issue has been fixed now

**Comment by AramZahedi** [comment] 2020-03-06 20:15
Yeah, I edited the relationships on my test repo and managed to get it working flawlessly now.

@taylorotwell That tweas works.

**Comment by driesvints** [comment] 2020-03-06 20:51
Thanks for all the feedback

**Closed by driesvints** 2020-03-06 20:51 UTC
Labels: needs more info
