### ISSUE TITLE
HasManyThrough, final Model id overwritten by intermediate Model id

### ISSUE THREAD

**Issue by michalisantoniou6** [laravel/framework#20805] opened 2017-08-28 19:39 UTC
- Laravel Version: 5.4.35
- PHP Version: 7.0.12
- Database Driver & Version: MySql 5.5.5

### Description:
When using a HasManyThrough relationship, the `id` column of the final table is overwritten by the `id` column of the intermediate table.

For example, given the structure below, when I do `$caller->calls->first()`, the Call's id is overwritten by the User's id. 

Thanks for your help in advance.

### Steps To Reproduce:

    class Caller extends Model {
          //relevant fields: id, user_id

          public function calls()
          {
              return $this->hasManyThrough(Call::class, User::class, 'id', 'outbound_user_id', 'user_id');
          }
    }

    class User extends Model {
          //relevant fields: id

          public function caller()
          {
              return $this->hasOne(Caller::class, 'user_id');
          }
    }

    class Call extends Model {
          //relevant fields: id, outbound_user_id

          public function outboundUser()
          {
                return $this->belongsTo(User::class, 'outbound_user_id');
          }
    }

**Comment by themsaid** [comment] 2017-08-29 10:00
Please ask on the forums and check the docs for hasManyThrough https://laravel.com/docs/5.4/eloquent-relationships#has-many-through

Closing since it's not a bug. Feel free to ping me on Laracasts and I'll try to help once I get a chance :)

**Closed by themsaid** 2017-08-29 10:00 UTC
