### ISSUE TITLE
@php bug -- Inline/Multiline

### ISSUE THREAD

**Issue by zacksmash** [laravel/framework#21405] opened 2017-09-26 20:12 UTC
- Laravel Version: 5.5.13
- PHP Version: 7.2
- Database Driver & Version: MySQL v5.7.19

### Description:
Using the `@php` directive inline followed by a multiline results in the compiled view not rendering properly.

### Steps To Reproduce:
```blade
@php($var = 1)
<div>
  Stuff In Here
</div>
@php
  $new_var = 2;
@endphp
```

**Comment by stayallive** [comment] 2017-09-27 15:11
Same here, the `@php($var = 1)` is not documented... wonder if it was supposed to be supported at all (https://laravel.com/docs/5.4/blade#php).

**Comment by devcircus** [comment] 2017-09-27 19:48
Maybe similar to #20994

**Comment by josephtaylor-mn** [comment] 2017-09-27 21:32
From what I can tell you cannot format your php code this way with blade.
As you see here: https://github.com/laravel/framework/blob/9d0f23deed323710fa8b7c57b502f8c07b2b61ba/src/Illuminate/View/Compilers/BladeCompiler.php#L217

The compiler looks for any instance of @php then parses out the php code with a regular expression (e.g. everything between @php and @endphp)

I believe this is a request for a new feature, not a bug.

**Comment by stayallive** [comment] 2017-09-28 07:42
This worked in 5.4 so that is where the confussion is, if it should have worked is another thing :)

https://github.com/laravel/framework/blob/5.4/src/Illuminate/View/Compilers/Concerns/CompilesRawPhp.php#L15

But yeah it does seem it's no longer supported, would be very handy to have mentioned in the upgrade guide.

**Comment by ShahidH** [comment] 2017-09-28 20:53
If `@php($var = 1)` no longer supported 5.5, I have to update many places in the blade :)

**Comment by zacksmash** [comment] 2017-09-28 23:08
@stayallive @ShahidH That's exactly the issue. It used to work, and 5.5 broke it without mentioning it in the upgrade docs. I'm not sure why it shouldn't be a feature... It's convenient to do an inline php tag, for quick variables.

**Comment by devcircus** [comment] 2017-09-28 23:51
No one realized it was broken until after 5.5 was released ( see #20994) and was marked as a no-fix. That's the problem with all these blade helpers that get added. They are limited by how laravel parses blade and are not useful in many use-cases. Best to not use the helpers outside the most basic use-case.

**Comment by jmarcher** [comment] 2017-09-29 06:55
If this is no longer supported you can still use Custom Laravel Directives in order to bring this functionality back

**Comment by stayallive** [comment] 2017-09-29 08:11
Yep, for the easy copy pasta solutions, I added this to the boot method of my app serviceprovider:

```php
\Blade::directive('raw', function ($expression) {
    return "<?php {$expression}; ?>";
});
```

And replaced `@php(` with `@raw(` in my code using a quick search and replace.

**Comment by Dylan-DPC** [comment] 2017-10-01 21:40
Since it is no longer supported I think we can close this issue and make a PR to the upgrade guide/docs

**Comment by DCzajkowski** [comment] 2017-10-05 23:03
It has been added to the Upgrade Guide here: https://github.com/laravel/docs/blame/5.5/upgrade.md#L338

Can be closed.

**Closed** 2017-10-07 10:07 UTC
