### ISSUE TITLE
Typo in BusServiceProdiver.php

### ISSUE THREAD

**Issue by StanMenten99** [laravel/framework#34309] opened 2020-09-12 14:32 UTC
- Laravel Version: 8.0.0
- PHP Version: 7.4
- Database Driver & Version: MySQL

### Description:
There is a typo in BusServiceProvider.php line 50 on the end. You have to remove the comma.

### Steps To Reproduce:
Go to vendor/laravel/framework/src/bus and open BusServiceProvider.php.
Go to line 50 and remove the comma at the end.

**Comment by basmilius** [comment] 2020-09-12 14:42
Duplicate of #34234 I think :)

**Comment by GrahamCampbell** [comment] 2020-09-12 14:44
PHP supports trailing commas now.

**Closed** 2020-09-12 14:44 UTC

**Comment by GrahamCampbell** [comment] 2020-09-12 14:45
Laravel 8's minimum PHP version is 7.3. https://wiki.php.net/rfc/trailing-comma-function-calls

**Comment by StanMenten99** [comment] 2020-09-12 14:47
> Laravel 8's minimum PHP version is 7.3. https://wiki.php.net/rfc/trailing-comma-function-calls

If you read my issue, you see that my current PHP version is 7.4.

**Comment by taylorotwell** [comment] 2020-09-12 14:49
It's likely that your CLI PHP is not PHP 7.3 or higher.

**Comment by StanMenten99** [comment] 2020-09-12 14:51
> It's likely that your CLI PHP is not PHP 7.3 or higher.

I've removed the comma anyways and reinstalled php 7.4. Hope that that did the job.
Thank you anyway.
