### ISSUE TITLE
[5.8] Weird issues with Sqs driver?

### ISSUE THREAD

**Issue by arthur798** [laravel/framework#29920] opened 2019-09-09 12:57 UTC
- Laravel Version: 5.8
- PHP Version: 7.3
- Database Driver & Version: Mysql

### Description:
I seem to have issues with sending email with sqs, no matter if I queue the mail or try to use `sendNow` it still seems to go through sqs and throwing

```
local.ERROR: Error executing "SendMessage" on "https://sqs.eu-west-2.amazonaws.com/952502652332/awseb-e-y2rpc8gunp-stack-AWSEBWorkerQueue-1TXAEX916ZXD6"; AWS HTTP error: Client error: `POST https://sqs.eu-west-2.amazonaws.com/952502652332/awseb-e-y2rpc8gunp-stack-AWSEBWorkerQueue-1TXAEX916ZXD6` resulted in a `400 Bad Request` response:
<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>I (truncated...)
 InvalidParameterValue (client): One or more parameters are invalid. Reason: Message must be shorter than 262144 bytes. - <?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>InvalidParameterValue</Code><Message>One or more parameters are invalid. Reason: Message must be shorter than 262144 bytes.</Message><Detail/></Error><RequestId>4a8f99e4-0663-516d-8607-cc086e5c38ce</RequestId></ErrorResponse> {"userId":1,"exception":"[object] (Aws\\Sqs\\Exception\\SqsException(code: 0): Error executing \"SendMessage\" on \"https://sqs.eu-west-2.amazonaws.com/952502652332/awseb-e-y2rpc8gunp-stack-AWSEBWorkerQueue-1TXAEX916ZXD6\"; AWS HTTP error: Client error: `POST https://sqs.eu-west-2.amazonaws.com/952502652332/awseb-e-y2rpc8gunp-stack-AWSEBWorkerQueue-1TXAEX916ZXD6` resulted in a `400 Bad Request` response:
<?xml version=\"1.0\"?><ErrorResponse xmlns=\"http://queue.amazonaws.com/doc/2012-11-05/\"><Error><Type>Sender</Type><Code>I (truncated...)
```

The mail has a few attachments which is fine but if I do

`Mail::to($case->reply_to)->sendNow(new SendQuestionnaire($questionnaire, 'questionnaires/' . $folder_name . '/' . $form . '.pdf', $organisation, $case->external_case_ref, $update->title, $attachments, auth()->user()->email));`

why does it send it to sqs? 

my SendQuestionnaire class looks like this

```
    class SendQuestionnaire extends Mailable
    {
        use Queueable, SerializesModels;

        /**
         * @var Questionnaire
         */
        protected $questionnaire;

        /**
         * @var Organisation
         */
        protected $organisation;

        /**
         * @var string
         */
        protected $questionnaire_path;

        /**
         * @var
         */
        public $external_case_ref;

        /**
         * @var
         */
        protected $title;

        /**
         * @var
         */
        protected $file_attachments;

        /**
         * @var
         */
        public $user_email;

        /**
         * Create a new message instance.
         *
         * @param Questionnaire $questionnaire
         * @param string $questionnaire_path
         * @param Organisation $organisation
         * @param string $external_case_ref
         * @param string $title
         * @param $file_attachments
         */
        public function __construct(Questionnaire $questionnaire, string $questionnaire_path, Organisation $organisation, string $external_case_ref, string $title, $file_attachments, $user_email)
        {
            $this->questionnaire = $questionnaire;
            $this->questionnaire_path = $questionnaire_path;
            $this->organisation = $organisation;
            $this->external_case_ref = $external_case_ref;
            $this->title = $title;
            $this->file_attachments = $file_attachments;
            $this->user_email = $user_email;
        }

        /**
         * Build the message.
         *x
         * @return $this
         * @throws \Illuminate\Contracts\Filesystem\FileNotFoundException
         */
        public function build(): self
        {
            $case = $this->questionnaire->updates()->first()->cases()->first();

            if ($this->organisation->email_subjects) {
                $email_subject = $this->organisation->email_subject()->where('type', 'questionnaire')->where('email_type', 'SendQuestionnaire')->where('name', 'LIKE', "%{$this->questionnaire->name}%")->first();
                $timestamp = time();
                if (!empty($email_subject)) {
                    if ($email_subject->datetime) {
                        $subject = $email_subject->tag . $this->external_case_ref . '_' . $timestamp . ' - '. $this->title;
                    } else {
                        $subject = $email_subject->tag . $this->external_case_ref . ' _ '. $this->title;
                    }
                } else {
                    $subject = 'GE' . $this->external_case_ref . '_' . $timestamp . ' _ '. $this->title;
                }
            } else {
                $case_id = $case->id;
                $email_integration = EmailIntegration::where('case_id', $case_id)
                    ->whereNull('update_id')->first();
                if ($email_integration instanceof EmailIntegration) {
                    $subject = $this->title . ' - '.$email_integration->tag;
                } else {
                    $subject = $this->title . ' - '.$this->external_case_ref;
                }
            }


            $questionnaire = Storage::disk('s3')->get($this->questionnaire_path);
            $questionnaire_local = Storage::disk('local')->put($this->questionnaire_path, $questionnaire);
            if ($questionnaire_local) {
                $email = $this->markdown('email.send_questionnaire')
                    ->subject($subject)
                    ->attach(storage_path('app/' . $this->questionnaire_path))
                    ->with([
                        'organisation' => $this->organisation->name,
                        'organisation_id' => $this->organisation->id,
                        'org_identifier' => $this->organisation->branded ? $this->organisation->identifier : 'incase'
                    ]);
                $email->from(config('mail.from.address'), $this->organisation->name);
                if (!empty($this->file_attachments)) {
                    foreach ($this->file_attachments as $attachment) {
                        $attachment_full_path = $attachment->path . '/' . $attachment->filename;

                        $attachment_binary = Storage::disk('s3')->get($attachment_full_path);
                        $attachment_local = Storage::disk('local')->put($attachment_full_path, $attachment_binary);

                        if(!$attachment_local){
                            \Log::critical('Failed to send document to law firm', ['attachment_path' => $attachment_full_path, 'external_case_ref' => $this->external_case_ref]);
                            continue;
                        }

                        $email->attach(storage_path('app/' . $attachment_full_path));

                    }
                }
                return $email;
            }
            Log::critical('Failed to send questionnaire', ['questionnaire_path' => $this->questionnaire_path, 'external_case_ref' => $this->external_case_ref]);
        }
```

I even tried to schedule a job 

```   
 class SendEmailSqs implements ShouldQueue
    {
        use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
        /**
         * @var string
         */
        protected $to;

        /**
         * @var
         */
        protected $questionnaire;

        /**
         * @var
         */
        protected $questionnaire_path;

        /**
         * @var
         */
        protected $organisation;

        /**
         * @var
         */
        protected $external_case_ref;

        /**
         * @var
         */
        protected $update;

        /**
         * @var
         */
        protected $attachments;

        /**
         * @var
         */
        protected $user_email;

        /**
         * Create a new job instance.
         *
         * @param string $to
         * @param Questionnaire $questionnaire
         * @param $questionnaire_path
         * @param $organisation
         * @param $external_case_ref
         * @param $update
         * @param $attachments
         * @param $user_email
         */
        public function __construct(string $to, Questionnaire $questionnaire, $questionnaire_path, $organisation, $external_case_ref, $update, $attachments, $user_email)
        {
            $this->to = $to;
            $this->questionnaire = $questionnaire;
            $this->questionnaire_path = $questionnaire_path;
            $this->organisation = $organisation;
            $this->external_case_ref = $external_case_ref;
            $this->update = $update;
            $this->attachments = $attachments;
            $this->user_email = $user_email;
        }

        /**
         * Execute the job.
         *
         * @return void
         */
        public function handle(): void
        {
            Mail::to($this->to)->send(new SendQuestionnaire($this->questionnaire, $this->questionnaire_path, $this->organisation, $this->external_case_ref, $this->update, $this->attachments, $this->user_email));
        }
```

to try and move the attachments attach after the job is scheduled so that the size of the job is smaller.

So the questions are:

1. Why even with `sendNow` method it tries to schedule the job on sqs?
2. How do you manage sending multiple attachments even if moving the logic to the job doesn't sort it? The images are not even on the job, they are just the path surely that cannot be massive.

**Comment by aleferreiranogueira** [comment] 2019-09-10 17:42
We also got some weird issues with the SQS driver when trying to upgrade to PHP 7.2 using Laravel 5.7.28. We rolled back and I'll post here any findings while debuging

**Comment by arthur798** [comment] 2019-09-11 19:50
did you have any luck @aleferreiranogueira

**Comment by aleferreiranogueira** [comment] 2019-09-16 18:30
I did not got any valueable info; the only thing that I noticed is that sometimes a message is processed with no issues, but sometimes it consumes the message, but it does not process nor log anything. My current theory is that messages produced by the application in 7.1 sometimes break when the application tries to consume on 7.2 (we have a worker server that process messages and a web that generates some of those messages) and when we rolled the queue still had messages generated when the application was on 7.1. I say this because I saw a closed issue that said that when PHP is not able to parse the SQS message Illuminate throws a Exception (unfortunetly I forgot the issue number).

Now we' ll try to roll server once again but this time we'll create a new queue that the application on 7.2 will listen and therefore no older messages created by the 7.1 version will be consumed by 7.2, will update here soon after, if it goes well I'll assume that those issues are caused by the 7.2 trying to consume messages that were generated by older versions. I know, in theory this shouldn't happen and it does not make sense to an extent, but it's the only lead that we have right now.

**Comment by aleferreiranogueira** [comment] 2019-09-17 18:38
We're getting that strange exception again
![image](https://user-images.githubusercontent.com/13805078/65069477-2528d980-d961-11e9-8a6f-0edc726bd56b.png)

Sometimes when it is processing a SQS job it throws this, I don't know why yet

**Comment by themsaid** [comment] 2020-01-02 11:16
Make sure you're not implementing `ShouldQueue` in your mailable as it'll be queued even if you use `sendNow`.

Closing the issue since it's not related to SQS, please open a new issue if you have an SQS specific issue.

**Closed by themsaid** 2020-01-02 11:16 UTC
Labels: needs more info

**Comment by lionslair** [comment] 2020-02-01 03:08
The original post is because the message as a whole is longer than 256kb. Soon as you hit that SQL will reject the message. We  are having the same issue. Mainly when we chain jobs. The final result is all jobs are put into one message and it will be too large. 

https://github.com/e0ipso/amazon-sqs-php-extended-client-lib
We are trying to create our own SQS extended driver to handle messages larger than 256kb but now trying to solve .


`public function attempts()
{
 return (int) $this->job['Attributes']['ApproximateReceiveCount'];
 }`

in laravel/framework/src/Illuminate/Queue/Jobs/SqsJob.php:82

My initial thought is that SQS appears to return not Attributes but AttributeNames 
https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-sqs-2012-11-05.html#receivemessage

**Comment by SimplyCorey** [comment] 2021-10-07 19:29
Has anyone managed to solve this?  We are running into this issue a lot when using chained jobs.

**Comment by SimplyCorey** [comment] 2021-10-09 04:50
I wasn't able to find anyway to do this so I created a laravel driver that should handle the larger payloads.  Feel free to take a look: https://github.com/SimpleSoftwareIO/simple-sqs-extended-client
