### ISSUE TITLE
[5.2] WhereHas on polymorphic relation

### ISSUE THREAD

**Issue by pallmallshow** [laravel/framework#13585] opened 2016-05-17 14:47 UTC
Hi guys.

I'm trying to make a Eloquent request with polymorphic relations and conditions.
So, I have models : 
- MainClass (`$this->morphTo())` => detail method)
- FirstClass (`$this->morphOne(MainClass::class)`)
- SecondClass (`$this->morphOne(MainClass::class)`)

In my example, I must get only MainClass where 'column' in my polymorphic relation was null. So, i wrote this : 
```php
$results = MainClass::whereHas('detail', function($query){
                $query->whereNotNull('column');
            })->get();
```

But a QueryException was thrown: 
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'column' in 'where clause' (SQL: 
    select * from `main_class` where exists (
        select * from `main_class` as `laravel_reserved_0` where `laravel_reserved_0`.`id` = `laravel_reserved_0`.`type_id` and `parent_id` is not null
    )
)
```

Except this conditions, all polymorphic relations works perfectly.

I'm sorry if it's not a bug, but all my app works well without this condition !
Thanks (and good luck :) )

PS: I'm using Laravel 5.2.32.

**Comment by Milewski** [comment] 2016-08-04 06:25
i have the some problem.....

**Comment by ericmagnuson** [comment] 2016-08-12 22:16
+1

From what I've read, whereHas doesn't support polymorphic relations. Did anyone else come to that conclusion?

**Comment by Milewski** [comment] 2016-08-13 01:01
well at the time i was looking for this whereHas stuff... and it wasnt working the way i expected... i come out with a different approach which works great for my case.. have a look.

```
public function scopeActive(Builder $query)
    {
        foreach ($stages = ['idea', 'synapse', 'script'] as $stage) {

            $query->orWhereHas(array_shift($stages), function (Builder $query) {
                $query->where('active', true)->orHas('submission');
            });

            foreach ($stages as $model) {
                $query->whereDoesntHave($model);
            }

        }

        $query->where('active', true);
    }
```

**Comment by ericmagnuson** [comment] 2016-08-13 20:30
Thanks for sharing this.  Something like this might fit my needs, too.

**Comment by jolora** [comment] 2016-08-28 12:02
+1  ...I would love to be able to use whereHas on polymorphic relations

**Comment by ayaka209** [comment] 2016-09-26 07:53
+1 here.

**Comment by GrahamCampbell** [comment] 2016-09-27 11:14
Closing since this is a feature request, not a bug report. If you have an implementation idea, please open an issue on internals.

**Closed** 2016-09-27 11:14 UTC

**Comment by sergey-rud** [comment] 2016-12-07 09:56
Hi!

I use Laravel 5.2.45, seems it haven't fixed yet. Perhaps in future will be good to throw Exception or write a note in the documentation about such behaviour.

Best regards.

**Comment by nacr** [comment] 2016-12-12 16:21
+1 for this please!

**Comment by MikeMnD** [comment] 2017-05-25 08:31
+1

**Comment by DakIyq** [comment] 2017-07-27 15:38
+1

**Comment by allanzi** [comment] 2017-08-18 13:13
+1

**Comment by skcin7** [comment] 2018-04-08 00:28
Hi +1
