### ISSUE TITLE
`migrate:fresh` artisan command does not drop schema from non-default databases in a multiple database usecase before attempting to create schema

### ISSUE THREAD

**Issue by coolamit** [laravel/framework#51777] opened 2024-06-11 22:13 UTC
### Laravel Version

11.10.0

### PHP Version

8.3.0

### Database Driver & Version

MariaDB on Ubuntu

### Description

If you have a Laravel app with multiple database setup then the artisan command `migrate:fresh` drops schema only in the default database before it tries to create schema. This results in `QueryException` being thrown and the execution halting as the command is unable to run the SQL with CREATE TABLE for a table name which already exists.

I did some search & came across #21009 which seems to be similar issue reported back in 2017 which was closed without a resolution with the reply that `--database=<DB2>` option should be used with `migrate:fresh` for second & subsequent databases. While that might work, its not optimal or the right solution because it creates all the tables in the database specified.

Please read for a more detailed explanation of what is happening.

To verify this issue, I created a new project using Laravel and created 3 Models, migrations, factories & seeders as below:

- mariadb (default connection)
  - table_a_s
  - table_b_s
- mariadb2 (second connection)
  - table_c_s

For the `table_c_s` migration, I added `connection('mariadb2')` on the `Schema` both when creating the table (in `up()` method) & when dropping the table (in `down()` method). I also specified the connection name in `TableC` model via the `$connection`.

My thinking was that since the connection is explicitly defined for the schema in migration, it should work.

But it works only the first time. It does not work if table already exists in second database. `migrate:fresh` is supposed to work irrespective of whether tables already exist or not because it calls the `down()` method on every migration class before calling its `up()` method - so tables are dropped (if they exist) before they are created.

It seems that for some reason the `down()` method was not being called for `table_c_s` migration in my case which meant table was not dropped before Laravel tried to create it & that results in an error. To test my hypothesis, I called the `down()` within the `up()`. That worked and now running `migrate:fresh` dropped & re-created `table_c_s` without any issue at all.

For reference, here's the migration for `table_c_s`.

```php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // uncommenting this will run `migrate:fresh` command alright
        // even if this table already exists
//        $this->down();

        Schema::connection('mariadb2')->create('table_c_s', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->text('description')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::connection('mariadb2')->dropIfExists('table_c_s');
    }
};
```

### Steps To Reproduce

1. Create a new Laravel project.
2. In the database config file, setup a default connection and a secondary connection.
3. Create 3 migrations for 3 tables.
4. In one of the migrations, use `connection()` on `Schema` in both `up()` & `down()` and specify the secondary database connection in the `connection()`.
5. Run `php artisan migrate` on the terminal in your Laravel project folder & then run `php artisan migrate:fresh`.
6. `php artisan migrate:fresh` will throw an exception because it does not call `down()` method for the migration configured to run on the secodary connection which results in the table in that secondary database not being dropped before an attempt is made to create it.

**Comment by crynobone** [comment] 2024-06-12 00:17
Duplicate of https://github.com/laravel/framework/issues/51735

**Closed by crynobone** 2024-06-12 00:17 UTC
