### ISSUE TITLE
Testresponse->assertSessionHasNoErrors not working as intended

### ISSUE THREAD

**Issue by ben182** [laravel/framework#25206] opened 2018-08-14 10:52 UTC
- Laravel Version: 5.6.33
- PHP Version: 7.1.9
- Database Driver & Version: sqlite memory

### Description:
In HTTP Testing the method assertSessionHasNoErrors is not working as you would expect. It should check if the session has no errors. But insted it checks if the session has no errors key. But when you send a response like this: `back()->withErrors($errors)` and $errors is empty or an empty messagebag, the session will get an errors key with an empty message bag. The assertSessionHasNoErrors method will fail because it checks if the session has no errors key.

### Steps To Reproduce:
Write a controller logic with `back()->withErrors([]);` The parameter is an empty array because at this point your validation does not contain any errors. Then write a testcase and check the response of the controller method with `$response->assertSessionHasNoErrors();`. The test will fail. Instead it should pass because their are no errors.

### Proposed Solution:
The assertSessionHasNoErrors Method should not check if the session errors key is not set but check if the session errors key is not set OR if the error key is set but the message bag is empty.

**Comment by staudenmeir** [comment] 2018-08-14 14:55
What would be a real-life scenario where you redirect the user back and use `withErrors()`, even when there are no errors?

**Comment by ben182** [comment] 2018-08-14 15:01
I have a controller where I add errors to an errorbag and send this bag `->withErrors($messageBag)` back to the view. These errors get added conditionally so it is possible that an empty errorbag will be send.

**Comment by devcircus** [comment] 2018-08-14 15:27
Seems like you should just be using your session, as needed, for this situation. "withErrors" is for a specific use-case that, by definition, has errors.

**Comment by staudenmeir** [comment] 2018-08-14 16:18
I'm not sure a case like this justifies changing `assertSessionHasNoErrors()`. You could override it in your test:

```php
public function assertSessionHasNoErrors()
{
    $this->assertTrue(! $this->session()->has('errors')
        || $this->session()->get('errors')->isEmpty());

    return $this;
}
```

**Comment by ben182** [comment] 2018-08-29 13:32
@devcircus @staudenmeir What would be the "laravel" way to solve this? Pass the withErrors function on condition seems not very clean.

**Comment by staudenmeir** [comment] 2018-08-29 13:49
That's what I would do. Why do think that it's not a clean solution?

**Comment by ben182** [comment] 2018-08-29 13:59
A bit because I have to overwrite a core function in a way. What would be the solution to pass this errorbag to the redirect function conditionally?

**Comment by staudenmeir** [comment] 2018-08-29 14:08
Something like this:

```php
$redirect = redirect()->back();
if ($hasErrors) {
    $redirect->withErrors($errors);
}
return $redirect;
```

**Comment by laurencei** [comment] 2018-09-18 09:00
I'll be closing this ticket, as this is intended behavior that has been well discussed here.

**Closed by laurencei** 2018-09-18 09:00 UTC
