### ISSUE TITLE
Incompatibility remember me and AuthenticateSession

### ISSUE THREAD

**Issue by shadrvlad** [laravel/framework#20790] opened 2017-08-28 07:13 UTC
- Laravel Version: 5.4.35
- PHP Version: 7.1.9

### Description:
Why remember me and middleware AuthenticateSession incompatible? If you use AuthenticateSession that remember me is pointless because resets authorization if you can not find session password_hash,
if (!$request->session()->has('password_hash') && $this->auth->viaRemember()) {
     $this->logout($request);
}
because the authorization record password_hash in a cookie and in the absence of session password_hash to write her cookies.

**Comment by themsaid** [comment] 2017-08-29 10:03
duplicate of https://github.com/laravel/framework/issues/18689

**Closed by themsaid** 2017-08-29 10:03 UTC

**Comment by elasticsteve** [comment] 2018-02-15 15:35
In the other threat you've closed it, pointing to this one, and in this threat you closed it, pointing to the other one! This is going in circles! Where is the fix?
