### ISSUE TITLE
[5.3] Unable to Fire Database Notifications for Archived/Soft Deleted Models

### ISSUE THREAD

**Issue by rishi-ramawat** [laravel/framework#16980] opened 2016-12-26 06:18 UTC
- Laravel Version: 5.3.22
- PHP Version: 7.0.8
- Database Driver & Version: MariaDB 10.1.18

### Description:
I have been trying to fire database notifications after an employee is archived. But the notification never gets saved into the notifications table of the database if the employee is archived.

### Steps To Reproduce:
My model looks like this:
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;

class Employee extends Model {
    use SoftDeletes, Notifiable;
    // Other functions here...
}
```
Now if I try this:
```php
$employee = Employee::find($employeeId);
if (!$employee) {
    // do something here
}
try {
    $employee->delete();
    $employee->notify(new EmployeeArchived($employee));
} catch (\Exception $e) {
    // do something here
}
```
The message returned by the `toDatabase()` function of the `EmployeeArchived` Notification class never gets saved in the database an No Exception is thrown too.

Was there a specific reason for not allowing database notifications on soft deleted models???

**Comment by themsaid** [comment] 2016-12-27 15:22
It works with no problem, but I see you're passing the $employee to the notification class, not sure why you're doing this since the employee is already available as `$notifiable`.

Please refer to the forums for assistance, this is not a bug in the framework but something wrong with your code.

Closing this, but please feel free to ping me if you need further explanation.

**Closed by themsaid** 2016-12-27 15:22 UTC
