### ISSUE TITLE
Blade HTML escaping bug

### ISSUE THREAD

**Issue by beyondlimits** [laravel/framework#12126] opened 2016-02-02 13:21 UTC
HTML entities are not escaped.
Code: `{{ '&lt; >' }}`
Expected result: `&amp;lt; &gt;` (as htmlentities does)
Actual result: `&lt; &gt;`

I expected my strings to be escaped in such way that they're reliably displayed in a browser. For now when I type `&lt &gt` into text field and get the value back after page reload, it ibecomes `< >`.

You're right - it's a dupe of #11390 in which @GrahamCampbell claimed that the behavior is correct, issue was closed and we're done. However, the function clearly does not do its job well or does it by reason which wasn;t explained.

If it's first, the problem seems to be related to the last parameter of `htmlentities` function, which is `true` by default in plain PHP, but Laravel explicitly defines it `false`.
If it's second, I would expect a better explanation why this function/parameters were used. This will possibly save time of me and others falling into this. Thank you.

**Comment by GrahamCampbell** [comment] 2016-02-02 16:38
This is a duplicate of a duplicate of a duplicate. Thanks for reporting, but it's not a bug.

**Comment by GrahamCampbell** [comment] 2016-02-02 16:38
Taylor commented on another one of the issues recently but I can't remember which one. Feel free to have a search around.

**Closed** 2016-02-02 16:37 UTC

**Comment by beyondlimits** [comment] 2016-09-14 06:50
Bump.

I couldn't find the issue you mentioned.

Everyone at the office has hit this problem and I have to tell them they need to override `e` function because provided one just doesn't work as intended.

I put `&lt;` into database and I want the same, properly escaped value back (that is `&amp;lt;` if someone is wondering) - any other behaviour is a *bug*. Don't fool me.

I can't see the reason of current behavior other that "we screwed it up in the first place and now it stays for backward compatibility". If so, I would be happy even with such explanation.

Thanks.
