### ISSUE TITLE
`artisan test` inconsistencies using PHPUnit + Paratest

### ISSUE THREAD

**Issue by shehi** [laravel/framework#47867] opened 2023-07-28 01:07 UTC
### Laravel Version

10.16.1

### PHP Version

8.1.20

### Database Driver & Version

MariaDb 10.6

### Description

Running `./artisan test -h` tells us:

```
Description:
  Run the application tests

Usage:
  test [options]

Options:
      --without-tty         Disable output to TTY
      --compact             Indicates whether the compact printer should be used
      --coverage            Indicates whether code coverage information should be collected
      --min[=MIN]           Indicates the minimum threshold enforcement for code coverage
  -p, --parallel            Indicates if the tests should run in parallel
      --profile             Lists top 10 slowest tests
      --recreate-databases  Indicates if the test databases should be re-created
      --drop-databases      Indicates if the test databases should be dropped
      --without-databases   Indicates if database configuration should be performed
  -h, --help                Display help for the given command. When no command is given display help for the list command
  -q, --quiet               Do not output any message
  -V, --version             Display this application version
      --ansi|--no-ansi      Force (or disable --no-ansi) ANSI output
  -n, --no-interaction      Do not ask any interactive question
      --env[=ENV]           The environment the command should run under
  -v|vv|vvv, --verbose      Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

Running `./artisan test --parallel --compact` tells us:

```
  The "--compact" option does not exist.  
```

The same is true for `--no-interaction` as well.

Running `XDEBUG_MODE=coverage ./artisan test --parallel` (without `--coverage` option) still creates coverage reports.

Running `XDEBUG_MODE=coverage ./artisan test --parallel --coverage` started causing:

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 44323440 bytes) in /builds/guildplanner.pro/backend/vendor/nunomaduro/collision/.temp/coverage on line 3
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 44323440 bytes) in /builds/guildplanner.pro/backend/vendor/nunomaduro/collision/.temp/coverage on line 3
[2023-07-28 00:48:47] testing.ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 44323440 bytes) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Allowed memory size of 134217728 bytes exhausted (tried to allocate 44323440 bytes) at /builds/guildplanner.pro/backend/vendor/nunomaduro/collision/.temp/coverage:3)
[stacktrace]
#0 {main}
"} 
In coverage line 3:
                                                                               
  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4432344  
  0 bytes)                 
```
which wasn't happening few minor versions ago. The latter is happening despite this setting in `phpunit.xml` file:

```
<php>
    <ini name="memory_limit" value="512M" />
</php>
```

### Steps To Reproduce

Details in description.

**Comment by nunomaduro** [comment] 2023-07-31 08:31
Can you try again? I think the issue should be fixed, because I've just tried it in a fresh Laravel application (with Pest and PHPUnit) and it seems to be working as expected.

**Comment by nunomaduro** [comment] 2023-07-31 12:43
Well, I've made a few changes on Pest. So, if you were using Pest, it's fixed now!

**Comment by shehi** [comment] 2023-07-31 13:28
> Well, I've made a few changes on Pest. So, if you were using Pest, it's fixed now!

No, I am not using Pest. Just PhpUnit through Paratest that comes bundled with Laravel.

**Comment by shehi** [comment] 2023-07-31 23:31
How do I upload large file as a comment? Can't see attachment button anywhere...

**Comment by nunomaduro** [comment] 2023-08-01 09:48
You can this service: https://gist.github.com/.

**Comment by shehi** [comment] 2023-08-01 10:47
https://gist.github.com/shehi/b83a9d25fa3fe5582e3060da2ca8dad7

**Comment by nunomaduro** [comment] 2023-08-01 13:02
Here are some points to consider:

1. When running tests in parallel, the `compact` option is not available, however the feedback could be indeed better on the output.
2. The `--no-interaction`  option cannot be used with the test command, however the feedback could be indeed better on the output.
3. Running `XDEBUG_MODE=coverage ./artisan test --parallel` does not generate a coverage report, or at least, I can't reproduce that.
4. If you encounter an "Allowed memory size" error, simply increase the PHP memory in your PHP settings (php.ini).

For points 1) and 2), you can pull request improvements directly on the Collision repository itself: https://github.com/nunomaduro/collision/blob/v7.x/src/Adapters/Laravel/Commands/TestCommand.php.

**Closed by nunomaduro** 2023-08-01 13:02 UTC
Labels: needs more info

**Comment by shehi** [comment] 2023-08-15 21:46
Regarding point (4): as mentioned in my original post above, setting memory limit doesn't help. At least when set via `phpunit.xml` config file. Is it correct to understand that PHPUnit config `<ini name="memory_limit" value="512M" />` doesn't apply to coverage report creation stage? Because memory outage doesn't happen **during** test executions; it happens after tests have run and coverage report is being created.

**Comment by edilsoncichon** [comment] 2024-11-06 22:27
This article can be useful (as it was to me): https://aregsar.com/blog/2020/laravel-run-parallel-tests-with-mysql-in-docker/
