### ISSUE TITLE
Saving a model with non-default connection

### ISSUE THREAD

**Issue by vladsrynty** [laravel/framework#19030] opened 2017-05-02 10:45 UTC
- Laravel Version: 5.4.21
- PHP Version: 5.6.30
- Database Driver & Version: Informix

### Description:

Eloquent model with property $connection set to non-default fails on saving

### Steps To Reproduce:

class Test extends \Eloquent {

  protected $connection = 'non-default';
}

$test = Test::find($testID);
$test->prop = '123';

$test->save();

SQL error stating that table does not exist. (because it tries to save on a default connection)

**Comment by themsaid** [comment] 2017-05-02 10:51
Unable to replicate your issue, the model saves with respect to the specified non-default connection successfully, please check your code for further details about the failure.

**Comment by faralimite** [comment] 2017-05-04 11:03
+1 here. I'm using yajra/laravel-oci8 and I have models with connection = 'oracle'; and I have error on saving. Select works.

I rolled back to 5.4.16 and it works.

**Comment by themsaid** [comment] 2017-05-04 11:09
I'm still unable to replicate, please share some steps to reproduce that I can use on a fresh laravel instance.

**Comment by faralimite** [comment] 2017-05-04 11:28
https://github.com/yajra/laravel-oci8/issues/279 have a look here.

**Comment by themsaid** [comment] 2017-05-05 06:35
Closing since we are unable to replicate, please report to the package maintainers.

**Closed by themsaid** 2017-05-05 06:35 UTC
Labels: Unable to Replicate
