### ISSUE TITLE
scheduled tasks dont run if the previous instance of the task is still running

### ISSUE THREAD

**Issue by abbasudo** [laravel/framework#53640] opened 2024-11-23 18:52 UTC
### Laravel Version

11.30

### PHP Version

8.3.2

### Database Driver & Version

SQLite

### Description

Hello,

Thanks for your awesome work at Laravel.

I came across an unexpected behavior when using the schedule feature, as stated at [this link](https://laravel.com/docs/11.x/scheduling#preventing-task-overlaps) "By default, scheduled tasks will be run even if the previous instance of the task is still running.". However, this is not working as expected in the scope of seconds.
Notice how the 3rd operation started at 18:30:30 and took 5 seconds to finish and the 4th operation didnt start until the 3rd one finished at 18:30:35.
```shell
php artisan schedule:work

  2024-11-23 18:30:28 Running ["artisan"  broadcast:send 1] ................................................................................ 1s DONE
  ⇂ "C:\php\php-8.3.2-Win32-vs16-x64\php.exe" "artisan" broadcast:send 1 > "NUL" 2>&1
  2024-11-23 18:30:29 Running ["artisan"  broadcast:send 1] ................................................................................ 1s DONE
  ⇂ "C:\php\php-8.3.2-Win32-vs16-x64\php.exe" "artisan" broadcast:send 1 > "NUL" 2>&1
  2024-11-23 18:30:30 Running ["artisan"  broadcast:send 1] ................................................................................ 5s DONE
  ⇂ "C:\php\php-8.3.2-Win32-vs16-x64\php.exe" "artisan" broadcast:send 1 > "NUL" 2>&1
  2024-11-23 18:30:36 Running ["artisan"  broadcast:send 1] ................................................................................ 1s DONE
  ⇂ "C:\php\php-8.3.2-Win32-vs16-x64\php.exe" "artisan" broadcast:send 1 > "NUL" 2>&1
  2024-11-23 18:30:38 Running ["artisan"  broadcast:send 1] ................................................................................ 1s DONE
```

### Steps To Reproduce

create normal new laravel app
```shell
laravel new test
cd test
php artisan make:command broadcastCommand
```
broadcastCommand.php:
```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class BroadcastCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'broadcast:send {brokerId}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Send broadcast messages to channel.';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        sleep(random_int(1, 5));
    }
}

```
console.php :
```php
Schedule::command(' broadcast:send 1')->everySecond();
```
run the schedule:
```shell
php artisan schedule:work
```

**Comment by Mdhesari** [comment] 2024-11-23 22:02
This issue already exists! https://github.com/laravel/framework/issues/53342

**Comment by crynobone** [comment] 2024-11-25 03:26
Duplicate of #53342

**Closed by crynobone** 2024-11-25 03:26 UTC
