### ISSUE TITLE
Laravel broke after app:name -v 5.7.6

### ISSUE THREAD

**Issue by gharabaghi** [laravel/framework#26546] opened 2018-11-17 08:37 UTC
after running app:name laravel throws an exception:
message: Class 'App\Providers\AppServiceProvider' not found
file: vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php
line: 208: return new $provider($this->app);

config:cache and composer dump-autoload not working.

**Comment by staudenmeir** [comment] 2018-11-17 16:05
It works for me. Can you reproduce this on a fresh Laravel installation?

**Comment by gharabaghi** [comment] 2018-11-18 06:14
> It works for me. Can you reproduce this on a fresh Laravel installation?

i will try.

**Comment by ahinkle** [comment] 2018-11-18 17:17
Try to run `config:cache` command, if you can't delete file `bootstrap/cache/config.php` and then re-run `config:cache` command and everything will be fine again.

**Comment by laurencei** [comment] 2018-11-18 23:18
Closing as not framework related.

**Closed by laurencei** 2018-11-18 23:18 UTC

**Comment by 9555643857** [comment] 2019-08-01 06:35
Class 'App\Providers\AppServiceProvider' not found error 
![image](https://user-images.githubusercontent.com/17945452/62270846-a7624a80-b454-11e9-8d0e-581c960c4395.png)

**Comment by brunogaspar** [comment] 2019-08-01 10:07
@9555643857 Your `AppServicerProvider.php` file has the wrong class inside.

Composer is warning you about it on the yellow box.
