### ISSUE TITLE
[L5] Manual Pagination returns the entire collection of raw query instead of only the paginated data

### ISSUE THREAD

**Issue by sureshbala** [laravel/framework#8230] opened 2015-03-31 07:48 UTC
```
use Illuminate\Pagination\LengthAwarePaginator as Paginator;

$query = "SELECT id FROM tasks";

if($request->employee_id)
 $query.=" WHERE assigned_to = $request->employee_id";

$results = DB::select( DB::raw($query));

$paginated = new Paginator($results, count($results), 5, 1, [
             'path'  => $request->url(),
             'query' => $request->query()
           ]);

```
`$paginated['data']` contains the entire `$results` set instead of 5 results.

**Comment by dhardtke** [comment] 2015-04-02 17:32
Duplicate of #8156

**Closed** 2015-04-02 17:44 UTC
