### ISSUE TITLE
php artisan migrate --pretend not working on ChangeColumn

### ISSUE THREAD

**Issue by lk77** [laravel/framework#36629] opened 2021-03-17 10:32 UTC
- Laravel Version: 8.32.1
- PHP Version: 7.2.27
- Database Driver & Version: mysql 5.7

### Description:

When doing `php artisan migrate --pretend` i have an exception :

```
AddColumnNameToTableName alter table `tableName` add `columName` varchar(100) null

In SchemaException.php line 86:
                                                                  
  There is no column with name 'columnName' on table 'tableName'. 
```

using `->change()` does not seems to work

### Steps To Reproduce:

1 / add a column with a migration
2 / change that column in another migration
3 / see that second migration fail when running pretend

thanks.

**Comment by sonja-turo** [comment] 2021-03-18 21:34
I could reproduce this, and I believe it's an issue regardless of the database or php version ( and probably other laravel versions).

I was able to address the issue by changing `src\Illuminate\Database\Scheme\Grammar\ChangeColumn.php` on line `27` from:

```
public static function compile($grammar, Blueprint $blueprint, Fluent $command, Connection $connection)
{       
    if (! $connection->isDoctrineAvailable()) {
        throw new RuntimeException(sprintf(
            'Changing columns for table "%s" requires Doctrine DBAL. Please install the doctrine/dbal package.',
            $blueprint->getTable()
        ));
    }
```

to

```
public static function compile($grammar, Blueprint $blueprint, Fluent $command, Connection $connection)
{
    if ($connection->pretending()) {
        return [];
    }
    
    if (! $connection->isDoctrineAvailable()) {
        throw new RuntimeException(sprintf(
            'Changing columns for table "%s" requires Doctrine DBAL. Please install the doctrine/dbal package.',
            $blueprint->getTable()
        ));
    }
```

All tests still pass, and I'd do a pull request, but I'm not confident enough in my ability to ensure this doesn't break fundamental functionality.

**Comment by driesvints** [comment] 2021-03-19 08:40
Hmm this is a tricky one. I think it's unfeasible that the pretend flag will ever work with column migrations for the reasons @sonja-turo stated above.

**Comment by sonja-turo** [comment] 2021-03-19 09:17
To add to this, yes, it's probably not feasible, because pretend _does_ work if the table and column are already physically in the database. To confirm this:

- Make table `foo` with column `bar` manually, or via migration. Run the migration as normal to add the table to the db
- Create migration to change the column
- Run the migration with the `--pretend` flag

The exception will not appear because Doctrine has done physical table discovery of a previously created schema, and can find the fields it expects to see.

I think it comes down to the use case of `--pretend`, which really seems intended to say "I have a known set database state A, and want to ensure moving to state B works before I physically alter anything", rather than doing a pretend migration of every blueprint in one hit. If you want to do the latter, prepare an empty db and run the migrations as normal rather than pretending.

**Comment by lk77** [comment] 2021-03-19 10:55
Well,

perhaps it's not feasible to display the query that will be done, but i think in such scenario, this exception should be catch and a simple message "query string not available" should be displayed. It should not interrupt the migration pretending process and just go on with the next one.

**Comment by sonja-turo** [comment] 2021-03-20 01:31
Reviewed this again, and now think @lk77 is right, and my assumptions about `--pretend` were wrong. This prompts me to then ask the question:
_What are the historical and/or technical reasons for having ChangeColumn and RenameColumn as separate classes and not part of the *Grammar classes, where the majority of the SQL statements are generated?_

In other words, what's the case for NOT building the alter statements into the grammar?

**Comment by driesvints** [comment] 2021-03-20 06:37
Because we don't want to maintain that code ourselves. DBAL already handles that for us.

**Comment by Sandman83** [comment] 2021-06-06 12:50
Does this mean a ticket on the DBAL repository should be opened? 
I'm just wondering what is the best operational way to fix the "--pretend" option.

**Comment by lk77** [comment] 2021-06-07 06:47
No i don't think so, there is nothing they can do.
There is no such thing as pretending in DBAL

**Comment by driesvints** [comment] 2021-07-01 13:14
Hey al. I sent a PR where I implemented the suggestion to display a warning message. I also think that solving the underlying issues would be hard to do.

https://github.com/laravel/framework/pull/37879

**Closed** 2021-07-01 17:07 UTC
Labels: bug, help wanted
