### ISSUE TITLE
Code in filesystem will cause memory exhausted issue

### ISSUE THREAD

**Issue by peinhu** [laravel/framework#24453] opened 2018-06-05 09:47 UTC
- Laravel Version: 5.6.23
- PHP Version: 7.0.26
- Database Driver & Version:

### Description:  
The code that causes this issue:
https://github.com/laravel/framework/blob/5.6/src/Illuminate/Filesystem/FilesystemAdapter.php#L278

When I use the 'local' driver to append a large file, e.g. `Storage::disk('local')->append('large_file.txt',$content)`, the memory of my server will be exhausted very soon.

<img width="737" alt="2018-06-05 17 37 27" src="https://user-images.githubusercontent.com/8167724/40968141-662ccd56-68e7-11e8-94fd-c6e81ad2a7da.png">

### Steps To Reproduce:
In web.php:  
`Route::get('/', function () {
    Storage::disk('local')->append("large_file.txt", "test content");
});`  

The size of large_file.txt is more than 500MB.

**Comment by peinhu** [comment] 2018-06-05 09:50
same issue #24439

**Comment by sisve** [comment] 2018-06-05 18:37
Well, if this is a duplicate of #24439, can you perhaps close this issue?

**Closed** 2018-06-10 02:26 UTC
