### ISSUE TITLE
Support\Collection::unique() private object attribute access - what is expected behavior?

### ISSUE THREAD

**Issue by redthor** [laravel/framework#26033] opened 2018-10-10 04:08 UTC
- Laravel Version: 5.7
- PHP Version: 7.1.22
- Database Driver & Version: N/A

### Description:
I am unsure of the expected behaviour in relation to Collection::unique() and a Collection of objects. If I pass objects that have a public attribute it will return the right unique count based on a key that matches the attribute name.

However if the attribute is private it only returns unique()->count() == `1` as the response.

Possible resolutions:
1. Collection::unique() does not support object attributes in any form (throws an error?)
1. Collection::unique() supports only *public* object attributes (throws an error if attribute is not visible)
1. Collection::unique() supports object attributes regardless of visibility (returns the correct result in test)

### Steps To Reproduce:

Steps to reproduce are here in the PR (just for demonstration purposes):
https://github.com/redthor/framework-1/pull/1/files#diff-f565fa2deb7f67254a3a052a4f1d214bR819

**Comment by redthor** [comment] 2018-10-10 05:00
I think the expected behavior should be motivated by the name of the method and functional consistency. If it isn't consistent then it should throw an error. I don't think it is right that the expected behavior is driven by an understanding of the internal implementation.

It then follows that valid use-cases for accessing private properties are:

1. to provide consistency with the way it behaves when accessing public properties; and
1. support projects that insist classes are implemented with private attributes reachable via accessors and mutators (many will argue that objects should be immutable)

**Comment by staudenmeir** [comment] 2018-10-10 05:12
If a property is private/protected, it either has an accessor or shouldn't be accessed from the outside.

Accessors are supported via closures:

```php
$collection->unique(function($value) {
    return $value->accessor();
});
```

**Comment by redthor** [comment] 2018-10-10 05:49
FWIW I have this code for finding if all objects share the same value for a property. I does not handle all cases. Just a first version...

```php
        Collection::macro('isConsistent', function ($key = null) {
            if ($this->count() === 0) {
                return false;
            }

            // Looking for a private property?
            // This will work for regardless of visibility
            // @see https://github.com/laravel/framework/issues/26033
            $first = $this->first();
            if (\is_string($key) && \is_object($first)) {
                $key = function ($item) use ($key) {

                    $getProp = function () use ($key) {
                        return $this->{$key};
                    };

                    return $getProp->call($item);
                };
            }

            $items = $this->unique($key);

            return $items->count() === 1;
        });
```

**Comment by mfn** [comment] 2018-10-10 07:41
Having `->unique` implicitly being able to access protected/private property information is a WT… in my book and would be unexpected.

**Comment by redthor** [comment] 2018-10-10 07:46
@mfn so you are ruling out my third option in my original post.

What do you think of existing behavior? It appeared to be a WT moment for me.

**Comment by mfn** [comment] 2018-10-10 07:55
> What do you think of existing behavior? It appeared to be a WT moment for me.

Debatable, I'm not saying it's the perfect result.

I mean: there's always some responsibility on the developers side to some degree, accessing a non-public property _to me_ looks like an error on the developer side. Probably found/covered in a test in the project. Fixed in the code. Moved on.

Not saying to ignore this but it seems an edgy case and it's not a blocker for anything.

Which brings me back to: maybe it's a documentation thing 🤷‍♀️

Because _then_ you can't say it's unexpected 😄

**Comment by redthor** [comment] 2018-10-10 08:02
Ha, actually, I just came back in to github to say let's call it a documentation thing :)

It could say at the start of https://laravel.com/docs/5.7/collections something like:

> `Collection` works with an array of arrays or an array of objects. When working with objects properties are treated in *<enter description>*

**Comment by driesvints** [comment] 2018-11-13 16:36
The current behavior seems the expected behavior. I agree with @staudenmeir and @mfn that accessing private/protected properties is unwanted in this situation.

**Closed by driesvints** 2018-11-13 16:36 UTC
