### ISSUE TITLE
Batch job never finished or cancelled with job failures

### ISSUE THREAD

**Issue by stephenstack** [laravel/framework#36180] opened 2021-02-08 10:18 UTC
- Laravel Version: 8.26.1
- PHP Version: 7.4.9
- 10.3.17-MariaDB

### Description:
Running a batch job with jobs that fail, the batch never completes as "finished" or "cancelled".  Code below and will explain after;

### Steps To Reproduce:
```

        foreach ($this->records as $records) {
            $jobs[] = new DownloadJob($records);
        }

        $batch = Bus::batch($jobs)->then(function (Batch $batch) {
            // All jobs completed successfully...
            $msg = 'Batch [' . $batch->id . ']/[' . $batch->name . '] has been finished succesfully';
            info($msg);
        })->catch(function (Batch $batch, \Throwable $e) {
            // First batch job failure detected...
            $msg = 'Batch [' . $batch->id . ']/[' . $batch->name . '] failed to process all jobs';
            info($msg);
        })->finally(function (Batch $batch) {
            // The batch has finished executing...
            $msg = 'Batch [' . $batch->id . ']/[' . $batch->name . '] finished proccessing';
            info($msg);
        })->name('Process TestBatchJob')
            ->allowFailures()
            ->onQueue('downloadqueue')
            ->name('downloadjob')
            ->dispatch();

        $progress = $this->output->createProgressBar(100);
        $this->info('Total device download jobs: ' . $batch->totalJobs);
        $this->info('');

        while (($batch = $batch->fresh()) && !$batch->finished()) {
            dump('Pending: ' . $batch->pendingJobs);
            dump('status: ' . $batch->finished());
            $progress->setProgress($batch->progress());
            sleep(5);
        }
        dump('done');
        $progress->finish();
```

So I run this block from an artisan command. The batch runs a total of 7 jobs, and the last job that is dispatch from the batch to the queue is designed to be a failed job (i.e. record does not exist so it fails). Output from the while loop shows the following;

```
  71/100 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░]  71%^ "Pending: 2"
^ "status: "
^ "Pending: 1"
^ "status: "
  86/100 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░]  86%^ "Pending: 1"
^ "status: "
^ "Pending: 1"
```

So 86% is where it gets too . But the 'finally' callback is actually called because I get a log entry from the closure;
```[2021-02-08 10:08:55] local.INFO: Batch [92ae6f64-6cc4-4e4e-9d19-b34d244b0c8b]/[downloadjob] finished processing```

The DB record for the job has null values for 'cancelled_at' and 'finished_at'. Which would explain why $batch->finished() always returns null as does $batch->cancelled(). So my while loop becomes infinite. 

Final point, in horizon, all jobs for the batch are either completed or failed, nothing in pending. So the batch is working as expected, but realtime feedback that the batch is done is not working as expected even though allowFailures() is set.

Hope this make sense.

**Comment by themsaid** [comment] 2021-02-08 10:54
It wasn't cancelled because you have `allowFailures()`, and it didn't finish because there are failing jobs. That's the expected behaviour.

**Comment by stephenstack** [comment] 2021-02-08 11:18
OK, so not sure this is an education or documentation issue.  The docs say "When a job within a batch fails, Laravel will automatically mark the batch as "cancelled". If you wish, you may disable this behavior so that a job failure does not automatically mark the batch as cancelled. "

So I think its a use case issues. If a job in the batch fails my options should be 
1. cancel the job - this appears to be default behavior
2. Continue the other jobs, and ignore any failures - this appears to be allow with the allowFailures() method

I've just rerun the above with allowFailures() removed and the batch does not return cancelled or finished either. I think in the second case, some flag to say the job completed with errors is prudent. But currently that does not occur. 

So two things, 
1. a flag to say job completed/ finished with errors
2. With the allowFailures() method removed and a job error happens, the batch does NOT return cancelled per further testing

**Comment by themsaid** [comment] 2021-02-08 11:32
The job fails when all its retries are consumed. Only then the batch will be cancelled and get marked as finished.

**Comment by stephenstack** [comment] 2021-02-08 11:37
Have 0 retires on my jobs, first attempt is the only attempt and fails the job. allowFailures() not chained to batch. 

![image](https://user-images.githubusercontent.com/7944609/107214410-c6ef1180-6a01-11eb-8a84-05c418cc6a3c.png)

![image](https://user-images.githubusercontent.com/7944609/107214458-dbcba500-6a01-11eb-9768-8ea57e3604b6.png)

Batch does not return cancelled.

**Comment by themsaid** [comment] 2021-02-08 11:39
A value is set for Cancelled At and Finished At as per the screenshot. The batch was cancelled.

**Comment by stephenstack** [comment] 2021-02-08 11:54
ok, my mistake on the allowFailures() removal for the batch. That works as expected. I

 think a silent failure when this is set still needs a review. a 'finished_with_failures' flag of some sort is required.

**Comment by themsaid** [comment] 2021-02-08 12:33
As long as there are pending jobs, the batch is not finished. There's no way we can detect accurately if the batch has jobs in the queue or all has settled. You can check `$batch->pendingJobs - $batch->failedJobs == 0` to find if the first round was done. However on retrying failed jobs, the failedJobs count can be larger than the pending jobs count.

**Closed by themsaid** 2021-02-08 12:33 UTC
Labels: needs more info

**Comment by jiechaowang** [comment] 2023-05-17 19:25
I feel the conversion has not reached a conclusion. The remaining question is, after one job failed, how can we make it continue to process the other jobs without failing or cancelling the whole batch? To simplify the question, let's say I don't want any kind of retry.

**Comment by rod-lima** [comment] 2023-07-21 07:09
I know this is old, but I was facing the same scenario, where I wanted to use allowFailures() and still decrease the number of pending jobs if one the jobs fail, so that the progress would always end at 100%. The workaround I've done to get that done is the below.

Inside of your job add the following code:

```php
public function failed()
{
    $this->batch()->decrementPendingJobs($this->batch()->id);
}
```
This seems to work well if you are only looking to have your batch marked as 100% when it's completed, but might not work if you are planning to re-run failed jobs, etc.

**Comment by rod-lima** [comment] 2023-07-21 07:11
I know this is old, but I was facing the same scenario, where I wanted to use allowFailures() and still decrease the number of pending jobs if one the jobs fail, so that the progress would always end at 100%. The workaround I've done is the below.

Inside of your job add the following code:

```php
public function failed()
{
    $this->batch()->decrementPendingJobs($this->batch()->id);
}
```
This seems to work well if you are only looking to have your batch marked as 100% when it's completed, but might not work if you are planning to re-run failed jobs, etc.

**Comment by tylernathanreed** [comment] 2023-07-24 15:49
I just ran into this issue as well.

Here's how I solved it:
```php
use Illuminate\Bus\BatchRepository;

$batch->finally(function (Batch $batch) {
    if (! $batch->finished()) {
        resolve(BatchRepository::class)->markAsFinished($batch->id);
    }
});
```

The whole reason why this was important to us was that we wanted to know when the so called, "first pass" was completed. We also don't support retrying jobs as-is, as the solution is often never that straight-forward. We instead support the concept of "completed with failures", and have the ability to address the failures as a secondary operation that doesn't modify the original batch.

**Comment by bernardwiesner** [comment] 2025-06-12 07:07
@tylernathanreed 

As is mentioned here: https://github.com/laravel/framework/issues/44111, and elsewhere, `finally()` is not called on a job failure, unless `->allowFailures()` has been used. 

If you do not use `->allowFailures()`, it will never enter the finally.

So it should be:

```php
$batch->allowFailures()
->finally(function (Batch $batch) {
    if (! $batch->finished()) {
        resolve(BatchRepository::class)->markAsFinished($batch->id);
    }
});
```

As a side note, if you are using Bus::chain with Bus::batch this will cause issues. For example:

```php
Bus::chain([
    $batch->allowFailures()
      ->finally(function (Batch $batch) {
          if (! $batch->finished()) {
              resolve(BatchRepository::class)->markAsFinished($batch->id);
          }
    }),
    fn () => ... // Flow will continue here even if a job fails in above batch
])
    ->catch(function () {
        // Catch will not be called even if a Job fails in above batch
    })
    ->dispatch();
```
