### ISSUE TITLE
App::environment() ignores APP_ENV when --env option is used on cli

### ISSUE THREAD

**Issue by redelschaap** [laravel/framework#28854] opened 2019-06-15 10:29 UTC
- Laravel Version: 5.8.15
- PHP Version: 7.3.4

### Description:
[The documentation](https://laravel.com/docs/5.8/configuration#retrieving-environment-configuration) says that "The current application environment is determined via the APP_ENV variable from your .env file.". It also says that "The current application environment detection can be overridden by a server-level  APP_ENV environment variable."

However, when using artisan with the `--env` option, `App::environment()` will return the value of the `--env` option. To me as a developer, I find it logical that the `--env` option is used to determine the `.env` file to use, not to overrule the environment. After all, the name of the `.env` file can differ from the `APP_ENV` value in that file.

### Steps To Reproduce:
1. Copy the `.env` file to `.env.foo`;
2. Change the value of `APP_ENV` within `.env.foo` to `bar`;
3. Run `php artisan tinker`;
4. Execute the command `App::environment()`, the value of `APP_ENV` should be returned;
5. Quit Tinker and run `php artisan tinker --env=foo`;
6. Execute the command `App::environment()`;
7. `foo` is now returned, instead of `bar`.

**Comment by khflab** [comment] 2019-06-16 02:33
* Laravel Version: 5.8.17
* PHP Version: 7.1.13

I was able to reproduce it

**Comment by driesvints** [comment] 2019-06-24 11:55
I can't test this atm because my tinker environment is still broken after https://github.com/bobthecow/psysh/issues/540 so it would be cool if some more people could verify this.

**Comment by rdarcy1** [comment] 2019-06-24 12:43
I can reproduce

- Laravel Version: 5.8.24
- PHP Version: 7.2.17
- OS: MacOS 10.14

It seems like this is expected functionality (see [Illuminate\Foundation\EnvironmentDetector](https://github.com/laravel/framework/blob/85137e065eeae76656fa07a9f4eb459e2e64d907/src/Illuminate/Foundation/EnvironmentDetector.php#L19)) but perhaps there should be different flags for the .env file and the value of APP_ENV?

**Comment by redelschaap** [comment] 2019-06-24 16:39
I think that will be a good solution.

**Comment by Tarasovych** [comment] 2019-06-26 07:27
https://github.com/laravel/ideas/issues/1559

**Comment by Tarasovych** [comment] 2019-06-26 07:28
https://github.com/laravel/framework/pull/28668 related a bit

**Comment by driesvints** [comment] 2019-07-01 14:44
Going to close this as we don't consider this a bug. Please see the remark by Taylor here: https://github.com/laravel/framework/pull/28982#issuecomment-507294744

**Closed by driesvints** 2019-07-01 14:44 UTC
Labels: bug
