### ISSUE TITLE
Request allFiles() Method Returns Wrong Data After Modification

### ISSUE THREAD

**Issue by zschuessler** [laravel/framework#27386] opened 2019-02-01 19:32 UTC
- Laravel Version: 5.7.19
- PHP Version: 7.2
- Database Driver & Version: MySql 5.7

### Description:
The InteractsWithInput.php Concern will return the wrong files array if a user has at any point modified the files of the request.

I'm fine submitting a PR for this, I wanted to check first if this is considered a bug.

### Steps To Reproduce:

1. Access a controller's filled Request param that has one or more files:
```
public function saveModel(Request $request)
```
2. Modify the FileBag by calling the `replace` method
```
// Modify files in whichever way you wish; remove, add, or edit
$newFiles = $request->allFiles();
$newFiles = $files->forget('some-key')

// Now call the replace method
$problemRequest = (clone $request)->files->replace($newFiles);
```
3. Observe that the files array is wrong when calling allFiles()
```
dd($problemRequest->allFiles());
```

### Steps To Reproduce: Why It Happens

Here's the method code:
https://github.com/illuminate/http/blob/master/Concerns/InteractsWithInput.php#L308
```
 public function allFiles()
    {
        $files = $this->files->all();
        return $this->convertedFiles
                    ? $this->convertedFiles
                    : $this->convertedFiles = $this->convertUploadedFiles($files);
    }
```

This method will return the cached convertedFiles property instead of the actual updated files (as would be correct with the $files variable there).

Happy to submit a PR on a preferred solution. Cheers.

**Comment by driesvints** [comment] 2019-02-04 10:59
Your example doesn't seems to be valid. Where does `$files` come from?

**Comment by driesvints** [comment] 2019-02-04 11:00
It's probably best to just copy/paste the entire controller method.

**Comment by zschuessler** [comment] 2019-02-04 14:43
Sorry about that, here's a working example I just tested:

        // Original request has a single file by key `image`
        $requestFile = $request->files->get('image');

        // Let's clone the request and copy the file, but change its key
        $modifiedRequest = clone $request;
        $modifiedRequest->files->replace([
            'modifiedKey' => $requestFile
        ]);

        // Here, $modifiedRequest correctly shows the changed key
        var_dump($modifiedRequest->files);
        
        // Here, the `allFiles` method shows the original cached array, with key `image`
        dd($modifiedRequest->allFiles());

**Comment by driesvints** [comment] 2019-02-05 09:52
You're 100% sure that this is **all** the code that's involved? Because from looking at the code I believe it should indeed return the modified key. The only exception being if an internal or external call was made to the `allFiles` method.

**Comment by driesvints** [comment] 2019-02-07 09:59
@zschuessler I haven't tried it out yet manually because I need to focus on other things atm. I'll try to look into this at a later time.

Any help with this is much appreciated.

**Comment by mxss** [comment] 2019-06-09 06:14
@driesvints 
Just tested with laravel 5.7.19, used code from snippet above
![Screenshot from 2019-06-09 09 11 42](https://user-images.githubusercontent.com/21367904/59155634-b224e280-8a96-11e9-9c64-516e77e029ec.png)

Here's full controller code:
```php
<?php


namespace App\Http\Controllers;


use Illuminate\Http\Request;

class MiscController extends Controller
{
    public function post(Request $request)
    {
        // Original request has a single file by key `image`
        $requestFile = $request->files->get('image');

        // Let's clone the request and copy the file, but change its key
        $modifiedRequest = clone $request;
        $modifiedRequest->files->replace([
            'modifiedKey' => $requestFile
        ]);

        // Here, $modifiedRequest correctly shows the changed key
        var_dump($modifiedRequest->files);

        // Here, the `allFiles` method shows the original cached array, with key `image`
        dd($modifiedRequest->allFiles());
    }
}
```

**Comment by driesvints** [comment] 2019-06-14 15:33
I get the correct modified key in the latest Laravel 5.8 release with the snippet above:

![Screen Shot 2019-06-14 at 17 32 24](https://user-images.githubusercontent.com/594614/59520548-80fb4680-8eca-11e9-9a89-7c878ad22db1.png)

Can you try to upgrade to 5.8 and see if the problem persists?

**Comment by iBotPeaches** [comment] 2019-07-25 19:56
Duplicated this, so glad after googling someone else had ran into this. In our instance, we developed a trait to convert base64 image strings into an actual image. Was a hacky fix to prevent breaking validation for old/new clients.

So after we did the conversion, we would shove that new image into the files array using.

```
        $this->files->add($fileArray);
        $this->merge($fileArray);
```

Not helpful without full context, but `$fileArray` is just a bunch of `UploadedFiles`, indexed by the same key that the posted base64 image string was. 

Why this became an issue is beyond me. The only change to the area was refactoring to a null-coalescing operator - https://github.com/laravel/framework/commit/7a7cacc3fd02d7d4c596c1a0f8af3c5b7a2990b4

After more digging though - I think we need to revert it. It is not the same check. The first one is a "truthy" check and 2nd is a "emptyness" check.

**Comment by driesvints** [comment] 2019-09-30 16:00
Going to close this as I can't reproduce this.

**Comment by zschuessler** [comment] 2019-09-30 19:51
@driesvints I can still reproduce by calling the `allFiles()` method before modifying the request. This method caches files into an internal class property, which is then used regardless of any modified contents thereafter.

@iBotPeaches is correct in that the null coalescing operator does not fix the problem, only changes the nature in which the problem presents itself with the truthy vs emptiness check.

Add a simple html form with an input named "original_uploaded_file", here's the route to duplicate:

```php
Route::post('test', function(\Illuminate\Http\Request $request) {
    // If we call this here, files get cached and causes problems
    $request->allFiles();

    // Original request has a single file by key `original_uploaded_file`
    $requestFile = $request->files->get('original_uploaded_file');

    // Let's clone the request and add another file to the array
    $modifiedRequest = clone $request;
    $modifiedRequest->files->add([
        'modified_request_file' => $requestFile
    ]);

    // Here, $modifiedRequest correctly shows two keys: the original, and the one we just added
    var_dump($modifiedRequest->files->all());

    // Here, the `allFiles` method shows the original cached array only, with key `original_uploaded_file`
    dd($modifiedRequest->allFiles());
});
```

So either we don't cache the files internally, or we make it evident that `allFiles` really means get a copy of the cached files.

**Comment by zschuessler** [comment] 2019-10-06 22:10
@driesvints this should be reopened. Let me know if you need anything, I confirmed in latest major version of Laravel.

**Comment by driesvints** [comment] 2019-10-11 14:56
@zschuessler I finally managed to reproduce this with you code snippet and I think I know what's going wrong. I'll send in a PR.

**Comment by driesvints** [comment] 2019-10-11 15:27
Actually, the actual problem is something different. You don't even need to clone the object to reproduce this:

```php
    // If we call this here, files get cached and causes problems
    $request->allFiles();

    // Original request has a single file by key `original_uploaded_file`
    $requestFile = $request->files->get('original_uploaded_file');

    $request->files->add([
        'modified_request_file' => $requestFile
    ]);

    // Here, $modifiedRequest correctly shows two keys: the original, and the one we just added
    dump($request->files->all());

    // Here, the `allFiles` method shows the original cached array only, with key `original_uploaded_file`
    dd($request->allFiles());
```

The thing is that the caching happens and then the underlying `$files` property is modified but because of the caching it can't be changed anymore. The caching is needed because converting the files property to `UploadedFile` instances can be quite intensive if that's done several times during a request.

I've also just realized that you're not meant to manipulate the request in this way as the files property is more like a read-only property. What I suggest you do is that you pull the files from it in a separate self-owned variable or object and then add any files you want there.

So I'm sorry to say but this will be a no-fix.

**Closed by driesvints** 2019-10-11 15:27 UTC
Labels: bug

**Comment by akauhovs** [comment] 2024-04-25 20:36
Some work around for this, to make a new Request, and push incoming request to it with manipulated files. Some code example:

` $updated_file = new UploadedFile($request->file('file_name')->path(),$manipulated_file->file_name,$request->file('file_name')->getClientMimeType());
        $incoming_request = $request;
        $request = new \Illuminate\Http\Request();
        $request->replace($incoming_request->except('file_name'));
        $request->files->replace(['file_name' => $updated_file]);
        $request['file_name'] = $updated_file;`

$request->all() will give you edited file. Dont forget also to put edited files to FileBag ($request->files), as it will be empty in new Request.
