### ISSUE TITLE
Composer install failed!

### ISSUE THREAD

**Issue by Cyw1104** [laravel/framework#18183] opened 2017-03-02 01:05 UTC
- Laravel Version: 5.1.*
- PHP Version: 7.0.7
- Database Driver & Version:

### Description:
There is an error when I  install Laravel Framework via Composer.

```
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
PHP Fatal error:  Class Illuminate\Container\Container contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Container\Container::factory) in /srv/www/autodsp/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 15

Fatal error: Class Illuminate\Container\Container contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Container\Container::factory) in /srv/www/autodsp/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 15

```

### Steps To Reproduce:

Here is my `composer.json` file:

```json
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*", 
        "predis/predis":"1.0.*",
        "anchu/ftp": "~2.0",
        "mookofe/tail": "1.*",
        "indatus/laravel-ps-redis": "^1.2"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1",
        "teepluss/theme": "dev-master"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
```

**Comment by masterwto** [comment] 2017-03-02 05:12
This is probably an php configure error.
I got this error on my production system. I managed to track the problem and solved my problem by making some optimizations.

In my apache log, I found 'Allowed memory size of... bytes exhausted' and then an error of 'Zend memory heap' before the error happens.

Whenever memory exhausts, your error happens.

Check your php.ini file and error log please.

**Comment by Cyw1104** [comment] 2017-03-02 08:36
I think  this is not a php config error. Here is the trace information:

```
PHP Fatal error:  Class Illuminate\Container\Container contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Container\Container::factory) in /srv/www/autodsp/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 15

```

**Comment by themsaid** [comment] 2017-03-02 11:52
Looks like you started the project with a different version and then dropped down to 5.1, please try to clear the compiled cache and try again.

Closing since it's not a bug, you can continue support on the forums or feel free to ping me.

**Closed by themsaid** 2017-03-02 11:52 UTC

**Comment by masterwto** [comment] 2017-03-02 15:09
@Cyw1104 这个不是Laravel框架的问题。你查看报错那个文件，类中的方法是存在的（继承于父类）。

**Comment by masterwto** [comment] 2017-03-02 15:13
@themsaid 给出的应该是正解。

php artisan clear-compiled
php composer update
php composer dump-autoliad --optimize

**Comment by Cyw1104** [comment] 2017-03-03 06:28
@masterwto  估计是，应该是我的 Laravel 框架的版本和 Laravel Framework 的版本不一致。

**Comment by Cyw1104** [comment] 2017-03-03 06:30
@masterwto 我使用 Composer 安装的 5.1.* 和 5.2.* 框架，那个文件中确实没有实现 factory 方法

**Comment by Cyw1104** [comment] 2017-03-03 07:01
@masterwto 我找到原因了，我是用的的其他 package 也引用了 laravel 的包，但是他们引用的不是 5.1 的版本，所以产生了冲突

**Comment by Cyw1104** [comment] 2017-03-03 07:08
@themsaid Thinks for replay.

THIS IS NOT LARAVEL ISSUE.

I've found the reason. I use other package requires `illuminate/support` package, its `composer.json` file is 

```
"illuminate/support" : 5.*
``` 

when i use `composer install` instruction，download  `illuminate/support`  and `illuminate/contract` package of version `5.4.9`.
