### ISSUE TITLE
"Model::preventAccessingMissingAttributes()" Causes Exception During Pagination with ResourceCollection

### ISSUE THREAD

**Issue by Karem-sobhy** [laravel/framework#52214] opened 2024-07-21 16:10 UTC
### Laravel Version

11.16.0

### PHP Version

8.3.9

### Database Driver & Version

MariaDB 11.4.2

### Description

When using pagination with `ResourceCollection` while `Model::preventAccessingMissingAttributes()` is activated, an attempt to access `resource` attributes occurs. This access results in a violation of the prevent access to missing attributes policy, causing an exception to be thrown.

```
"message": "The attribute [resource] either does not exist or was not retrieved for model [App\\Models\\User].",
"exception": "Illuminate\\Database\\Eloquent\\MissingAttributeException"
```

### Steps To Reproduce

- install new laravel instance
- create 1 user using the default seeder `php artisan db:seed`
- in `AppServiceProvider` add in the register method this `Model::shouldBeStrict();` or this `Model::preventAccessingMissingAttributes();`
- make a UserCollection `php artisan make:resource UserCollection`
- in any route now return this `return new UserCollection(User::paginate());`

**Comment by lrljoe** [comment] 2024-07-28 00:57
Hmm, in a route:

```
return UserResource::collection(User::paginate(2))
```

Then UserResource looks like:
```
class UserResource extends \Illuminate\Http\Resources\Json\JsonResource
{
    /**
     * Indicates if the resource's collection keys should be preserved.
     *
     * @var bool
     */
    public $preserveKeys = true;

    public function toArray(\Illuminate\Http\Request $request): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'email' => $this->email,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }

}

```

Does that work?  Trying to narrow down what the issue is!

**Comment by Karem-sobhy** [comment] 2024-07-28 06:54
@lrljoe this will work the problem is not with the `JsonResource` it's with `Illuminate\Http\Resources\Json\ResourceCollection` because it tries to access `resource` attribute

the cause of the problem is in this line
https://github.com/laravel/framework/blob/8ca1b5bbb9811585b58154a9e69aa0c67583e097/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php#L31
but i don't have the experience to understand how to fix it

**Comment by Katalam** [comment] 2024-07-29 08:16
I tried to fix it. I will fix the problem. I don't really know if the scope of the test is ok. But the problem would be fixed with referenced PR

**Comment by Karem-sobhy** [comment] 2024-07-29 10:56
> I tried to fix it. It will fix the problem. I don't really know if the scope of the test is ok. But the problem would be fixed with referenced PR

@Katalam I think u are using `JsonResource` with collection method and that didn't have the problem but did you try with `ResourceCollection`?
```php
php artisan make:resource UserCollection
return new UserCollection(User::paginate());
```

**Comment by Katalam** [comment] 2024-07-29 10:58
I did. to fix the problem, but not to write the test

**Closed** 2024-07-30 06:57 UTC
Labels: help wanted
