### ISSUE TITLE
Job::withChain - chained jobs dispatched to default queue.

### ISSUE THREAD

**Issue by Artistan** [laravel/framework#21528] opened 2017-10-04 15:21 UTC
- Laravel Version: 5.5.13
- PHP Version: 7.1
- Database Driver & Version: N/A

### Description:
Job::withChain does not retain the queue that the initial job was queued on.
is this intentional. It seems that it should default to the same queue only specifically changed.

### Steps To Reproduce:
Chain the jobs using withChain, all chained jobs will be on the 'default' queue.
```php
            JobA::withChain([
                   ( new JobB($a,$b,$c) ),
                   ( new JobB($x,$y,$z) ),
                   ( new JobC($a,$b,$c) ),
                   new JobD
            ])->dispatch($param1,$param2,$param3)->onConnection('custom-connection')->onQueue('custom-queue');
```

**Comment by Artistan** [comment] 2017-10-04 16:07
currently I have to do....

```php

            JobA::withChain([
                   ( new JobB($a,$b,$c) ))->onConnection('custom-connection')->onQueue('custom-queue'),
                   ( new JobB($x,$y,$z) ))->onConnection('custom-connection')->onQueue('custom-queue'),
                   ( new JobC($a,$b,$c) ))->onConnection('custom-connection')->onQueue('custom-queue'),
                   (new JobD))->onConnection('custom-connection')->onQueue('custom-queue')
            ])->dispatch($param1,$param2,$param3)->onConnection('custom-connection')->onQueue('custom-queue');

```

**Comment by themsaid** [comment] 2017-10-04 16:11
Check https://github.com/laravel/framework/pull/21530

**Comment by Artistan** [comment] 2017-10-04 16:59
Looking good. Thanks!

**Comment by Artistan** [comment] 2017-10-04 17:07
Ok, upon further testing....  my second example does not actually work for queued jobs.   It loses that information when in queue!

**Comment by themsaid** [comment] 2017-10-04 21:04
Closing since you already consider this as a breaking change, thus not a bug. I suggest that you continue discussion on the PR or open a proposal on https://github.com/laravel/internals.

**Closed by themsaid** 2017-10-04 21:04 UTC

**Comment by Artistan** [comment] 2017-10-06 19:07
I believe this is still an issue.
having a cue default to the null queue after setting the primary job to a connection or queue seems odd to me.

**Comment by benyanke** [comment] 2018-01-11 18:14
I agree - this is an issue. Personally, it's stopping me from using chaining, since I will have lots of activity in my app and prioritizing the queue between semi synchronous and low priority jobs is critical.
