### ISSUE TITLE
Laravel 11.10 "artisan about" issue

### ISSUE THREAD

**Issue by jduan00** [laravel/framework#51869] opened 2024-06-20 21:37 UTC
### Laravel Version

11.10

### PHP Version

8.3.8

### Database Driver & Version

mariadb 10.11

### Description

After upgrading to v11.10, the following command fails:

**php artisan about**

```
   Symfony\Component\Process\Exception\ProcessStartFailedException 

  The command "'composer' '-V' '--no-ansi'" failed.

Working directory: /app/site/laravel

Error: proc_open(): posix_spawn() failed: No such file or directory

  at vendor/symfony/process/Process.php:371
    367▕             restore_error_handler();
    368▕         }
    369▕ 
    370▕         if (!\is_resource($process)) {
  ➜ 371▕             throw new ProcessStartFailedException($this, $lastError);
    372▕         }
    373▕         $this->process = $process;
    374▕         $this->status = self::STATUS_STARTED;
    375▕ 


      +9 vendor frames 

  10  [internal]:0
      Illuminate\Foundation\Console\AboutCommand::Illuminate\Foundation\Console\{closure}()
      +3 vendor frames 

  14  [internal]:0
      Illuminate\Foundation\Console\AboutCommand::Illuminate\Foundation\Console\{closure}()

```

### Steps To Reproduce

`php artisan about`

**Comment by hafezdivandari** [comment] 2024-06-20 21:42
Duplicate of #51820

**Closed** 2024-06-20 21:47 UTC
