### ISSUE TITLE
Laravel 11 artisan serve issue ( SIGINT ) 

### ISSUE THREAD

**Issue by parasshah438** [laravel/framework#50027] opened 2024-02-09 10:35 UTC
### Laravel Version

11

### PHP Version

8.3

### Description

I Install laravel latest version 11

Start artisan serve then display error

>  Undefined constant "Illuminate\Foundation\Console\SIGINT"

vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php

$this->trap([SIGTERM, SIGINT, SIGHUP, SIGUSR1, SIGUSR2, SIGQUIT], function ($signal) use ($process) {
            if ($process->isRunning()) {
                $process->stop(10, $signal);
            }
            exit;
        });

### Steps To Reproduce

I also find solution for that
File path
vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php

I commit this trap code

$this->trap([SIGTERM, SIGINT, SIGHUP, SIGUSR1, SIGUSR2, SIGQUIT], function ($signal) use ($process) {
            if ($process->isRunning()) {
                $process->stop(10, $signal);
            }
            exit;
        });
        
Now its working perfect

**Comment by crynobone** [comment] 2024-02-09 10:39
Duplicate of #50022

**Closed by crynobone** 2024-02-09 10:39 UTC
