### ISSUE TITLE
Error after successful registration

### ISSUE THREAD

**Issue by projct1** [laravel/framework#21916] opened 2017-11-01 13:59 UTC
- Laravel Version: 5.5.19

### Description:
After fill data and press register button http://joxi.ru/EA4pyLjcD9p15A
I got error http://joxi.ru/52aQPgEfGnkoO2

**Comment by laurencei** [comment] 2017-11-01 16:00
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Closed** 2017-11-01 17:18 UTC

**Comment by projct1** [comment] 2017-11-01 18:49
Hi)
But registration is internal functionality and is part of the framework...

**Comment by laurencei** [comment] 2017-11-01 18:58
the problem is not with the framework - but with your implementation somehow...

**Comment by browner12** [comment] 2017-11-01 18:59
To begin with, your error is showing in a Symfony file, so if there was a problem, it would be with them.

If you can show the *framework* code is behaving incorrectly, then definitely post in here.  Based on this error that you've shown us, it is much more likely you have an error in your code.

If you post in a forum, they should be able to help you right quickly.

**Comment by projct1** [comment] 2017-11-01 19:33
After install laravel, i nothing to change about registration.
I just publich auth templates and put `Route::auth()` in `web.php`.

**Comment by browner12** [comment] 2017-11-01 19:37
Again, please head over to one of the platform's @laurencei has suggested to you. *most likely* it is a problem with your implementation, and someone should be able to help you.  **If** you find out that is indeed a problem with the framework, come back here and open a new issue, and provide a detailed explanation of what is wrong, and why it is wrong.

Thanks,

**Comment by projct1** [comment] 2017-11-01 19:40
Ok, thanks)

**Comment by projct1** [comment] 2017-11-02 10:32
I fixed this problem, thanks this thread https://laracasts.com/discuss/channels/laravel/header-may-not-contain-more-than-a-single-header-new-line-detected

I just replaced `return redirect()->home()` to `return route('home')` in my `redirectTo` method in `RegisterController.php`

Thanks for assistance ;)
