### ISSUE TITLE
auth:api not working - Redirecting to login page in Postman

### ISSUE THREAD

**Issue by viraj-khatavkar** [laravel/framework#13311] opened 2016-04-26 04:12 UTC
I have an Laravel app wherein, my routes file looks like below, but whenever I send a Postman request to `store.customer.complaint`, I am redirected to the login route rather than sending an unauthorized response : 

```
Route::get('/login', function () {
    return 'Login';
});

Route::group(['prefix' => 'api/v1'], function () {

    Route::group(['prefix' => 'customer'], function () {

        Route::post('register', ['as' => 'register.customer', 'uses' => 'Api\Customer\CustomerController@store']);
        Route::post('login', ['as' => 'login.customer', 'uses' => 'Api\Customer\CustomerController@login']);

        Route::group(['middleware' => 'auth:api'], function () {

            Route::post('complaint', [
                'as'   => 'store.customer.complaint',
                'uses' => 'Api\Customer\ComplaintController@store',
            ]);

        });

    });

});
```

#Postman Screenshot

![screen shot 2016-04-26 at 9 45 00 am](https://cloud.githubusercontent.com/assets/5693836/14806780/aa4f1ef2-0b93-11e6-9b21-396ffc464478.png)

**Comment by srmklive** [comment] 2016-04-26 06:35
My suggestion would be to create a duplicate of auth:api middleware, and modify it accordingly to give the response you want.

**Comment by rkgrep** [comment] 2016-04-26 06:50
Send `Accept: application/json`with Postman

**Comment by viraj-khatavkar** [comment] 2016-04-26 07:01
If you see I am giving a application/json in raw body

--
Viraj Khatavkar

**Comment by rkgrep** [comment] 2016-04-26 07:35
Ok. I see now. It is not provided in Laravel. You need to modify the middleware and add `$request->wantsJson()` condition manually.

**Comment by viraj-khatavkar** [comment] 2016-04-26 07:40
It is already there in `Authenticate.php`

--
Viraj Khatavkar

**Closed** 2016-04-26 07:41 UTC

**Comment by viraj-khatavkar** [comment] 2016-04-26 07:43
Why is it closed, I am not able to solve it yet.

--
Viraj Khatavkar

**Comment by rkgrep** [comment] 2016-04-26 07:43
> If you see I am giving a application/json in raw body

I just realized, it is not `Accept`, but `Content-type` header

**Comment by GrahamCampbell** [comment] 2016-04-26 08:19
> Why is it closed, I am not able to solve it yet.

With respect, this is not a laravel bug, thus we're closing it. Our GitHub is not a support forum.

**Comment by viraj-khatavkar** [comment] 2016-04-26 08:22
Sure, not an issue :)

--
Viraj Khatavkar

**Comment by viraj-khatavkar** [comment] 2016-04-26 08:30
@rkgrep Yes, you were correct, I sent an Accept header, it worked. Thanks for the tip :)

@GrahamCampbell Sorry for the trouble as it was my mistake

**Comment by vedmant** [comment] 2019-05-28 10:04
I personally for convenience use ForceJson middleware for all api routes:

```
class ForceJson
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        // Force Json accept type
        if (! Str::contains($request->header('accept'), ['/json', '+json'])) {
            $request->headers->set('accept', 'application/json,' . $request->header('accept'));
        }

        return $next($request);
    }
}
```

**Comment by robertmylne** [comment] 2019-07-05 07:19
@vedmant that is such a good idea, should get this merged into the main framework.

**Comment by khooz** [comment] 2019-10-20 19:32
@GrahamCampbell Say this is not a bug?! This little presumption in code bugged me an hour to find and I now have to find a way to gracefully shut it up.

Why am I forced to accept to redirect to `'login'` even if I don't, and explicitly said so in the `RedirectTo` function? Worst of all, in the process of raising an exception, The Exceptions are meant for the programmer to catch and figure out what's what. I am working on a REST API, but not all users gonna be respectful and send `Accept` and my API is not going to send them only JSON.

![image](https://user-images.githubusercontent.com/8382714/67164928-3e6fdc00-f38c-11e9-8bb5-0cfdca661333.png)

**Comment by nerwowy** [comment] 2020-02-06 18:42
Laravel shoud separate API layer from View layer. Its is very confusing. I cant consume default behaviour becouse i am creating Laravel API and i dont have any Views

**Comment by Gaurang5590** [comment] 2020-02-13 06:35
Same issue for me I facing 419 error

**Comment by prodaniucpavel** [comment] 2020-09-26 18:59
We really need a clear separation between API usage and normal usage. I've lost a few hours today trying to figure out why Laravel reacts so wrong to my requests. As @khooz said, why am I abusively redirected to login when I use it as an API? Lumen is not a solution. I need functionalities from Laravel for my needs.

auth:api is a joke.

**Comment by srmklive** [comment] 2020-09-27 06:56
> We really need a clear separation between API usage and normal usage. I've lost a few hours today trying to figure out why Laravel reacts so wrong to my requests. As @khooz said, why am I abusively redirected to login when I use it as an API? Lumen is not a solution. I need functionalities from Laravel for my needs.
> 
> auth:api is a joke.

So you don't review a default implementation, and just start developing your api. You can also implement your own login functionality by overriding the default one. How is that so difficult? If you don't review something, how come its a bug with framework,

**Comment by AaronWeb** [comment] 2021-03-15 15:13
I found top answer here helpful: https://stackoverflow.com/questions/45015586/laravel-request-expectsjson/57758245

**Comment by bsienn** [comment] 2021-07-28 11:28
@vedmant reply is great, I've a detailed step by step answer on [SO here](https://stackoverflow.com/a/68559483/4311336) using that middleware pattern with a bit more explanation.

**Comment by hasif5** [comment] 2023-03-12 06:36
> Send `Accept: application/json`with Postman

This what solved my problem after trying a lot of other ways.

**Comment by augusto-dmh** [comment] 2024-09-18 01:23
I've lost hours trying to find out:

- why validation errors were not retrieving 422 errors and json responses, but apparently trying to return a redirect to '/'
- why authentication errors were returning a redirect to the login route instead of simply 401

"Why there's html here?"

Ok i get, i need to add 'Accept: application/json' to ALL requests MANUALLY in any client i use, or i need to make a WORKAROUND to have a middleware to just force only json responses in all my application routes. But it wouldn't be better to have a clear separation between full-stack and back-end development?

I thinks it's nice that we can do both "web" and "api" routes and use them in the same context, but Laravel still lacks a way to build a project that is only supposed to be an api consumed by a client-side application. I know that the main focus is on full-stack development, but i'm sure that having this option would attract more people to Laravel.

PS: Also in the official docs there's no explicit section mentioning these Laravel characteristics related to needs for back-end development presented in an easy way to find. I had to see third party forums to find information about.
