### ISSUE TITLE
php artisan serve crushing

### ISSUE THREAD

**Issue by enonjovu** [laravel/framework#53185] opened 2024-10-16 12:58 UTC
### Laravel Version

11.28.0

### PHP Version

8.3.9

### Database Driver & Version

postgres

### Description

![Screenshot (144)](https://github.com/user-attachments/assets/9baa6a6f-1b5a-4a36-b437-b49fe9bd92a7)

### Steps To Reproduce

php artisan serve 
then launch the localhost url

**Comment by crynobone** [comment] 2024-10-16 13:06
Duplicate of https://github.com/laravel/framework/issues/53175#issuecomment-2415323646

**Closed by crynobone** 2024-10-16 13:06 UTC
