### ISSUE TITLE
\Illuminate\Database\Query\Builder autocomplete not working

### ISSUE THREAD

**Issue by matteoorefice-it** [laravel/framework#18713] opened 2017-04-07 15:39 UTC
- Laravel Version: 5.4.17
- PHP Version: 5.6
- Database Driver & Version: MySQL
- PHPStorm: 2017.1.1
- Laravel ide helper : 2.3.2

### Foreword:

**Laravel team has no liability for this misbehaviour but with this very simple fix many users of Laravel and PhpStorm will benefit cause the class is one of most frequently used in queries**

https://laravel.com/docs/5.4/queries#introduction

**It could happen Jetbrains fixes the bug on theirs side in the meantime**

### Description:

This is not a true bug but a suggested workaround exists to solve the annoying behaviour of PHPStorm, I have already opened an issue on jetbrain bug tracker. 

The `\Illuminate\Database\Query\Builder` class use traits conflict resolution syntax that confuses phpstorm during autocomplete , see the following :

```php
class \Illuminate\Database\Query\Builder {
  use BuildsQueries, Macroable {
    __call as macroCall;
  }

}
```

every variable of this type cannot be auto completed in phpstorm, but if the code is modified like this the error disappears:

```php
class \Illuminate\Database\Query\Builder {
  use BuildsQueries;
  use Macroable {
    __call as macroCall;
  }
}
```

it is not a true bug but a simple workaround could fix the problem.

### Steps To Reproduce:

```php

app('db')->connection()->table()->  // trigger autocomplete

DB::connection()->table('test')-> // trigger autocomplete

```

I submitted some generic steps to reproduce on jetbrains tracker  , the laravel's class include the same class-traits hierarchy , follow https://youtrack.jetbrains.com/issue/WI-35884

**Comment by themsaid** [comment] 2017-04-10 18:59
I don't think the code should be altered to please this or that IDE :) Maybe the change is a workaround for PHPStorm but another IDE complaints. Better keep this as a concern for the IDE builders.

**Comment by matteoorefice-it** [comment] 2017-04-11 05:40
There already was an open issue on jetbrains, follow this link https://youtrack.jetbrains.com/issueMobile/WI-35766

**Comment by themsaid** [comment] 2017-04-11 06:59
ok thank you for updates, going to close the issue now since it's not a bug.

**Closed by themsaid** 2017-04-11 06:59 UTC
Labels: Under Discussion
