### ISSUE TITLE
Can't mock an object resolved with some constructor arguments

### ISSUE THREAD

**Issue by osteel** [laravel/framework#37706] opened 2021-06-16 17:39 UTC
- Laravel Version: 8.44.0
- PHP Version: 8.0.2
- Database Driver & Version: MySQL 8.0

### Description:

When resolving an object with constructor parameters using the service container, it seems that subsequently trying to mock that object fails.

### Steps To Reproduce:

Say I've got an interface `FooContract`, with a `bar` method:

```php
<?php

namespace App;

interface FooContract
{
    public function bar(): string;
}
```

And a class `Foo` implementing that interface, with a constructor expecting a `$baz` string, and the `bar` method returning 'qux':

```php
<?php

namespace App;

class Foo implements FooContract
{
    public function __construct(public string $baz)
    {
    }

    public function bar(): string
    {
        return 'qux';
    }
}
```

And I bind `FooContract` to `Foo` in `AppServiceProvider`:

```php
public function register()
{
    $this->app->bind(FooContract::class, Foo::class);
}
```

Say I write a simple test.

Using the service container to resolve `FooContract` works as expected:

```php
public function testFoo()
{
    resolve(FooContract::class, ['baz' => 'baz'])->bar(); // "qux"
}
```

But then if I create a mock and bind it to `FooContract`, the mock seems to be ignored:

```php
public function testFoo()
{
    $this->mock(FooContract::class, function (MockInterface $mock) {
        $mock->shouldReceive('bar')->once()->andReturn('corge');
    });

    resolve(FooContract::class, ['baz' => 'baz'])->bar(); // still "qux"
}
```

Without changing the test, and simply by removing the arguments when resolving `FooContract` using the service container, the mock is not ignored anymore:

```php
public function testFoo()
{
    $this->mock(FooContract::class, function (MockInterface $mock) {
        $mock->shouldReceive('bar')->once()->andReturn('corge');
    });

    //resolve(FooContract::class, ['baz' => 'baz'])->bar();
    resolve(FooContract::class)->bar(); // "corge"
}
```

I would expect the bind to work whether there are constructor parameters or not.

**Comment by driesvints** [comment] 2021-06-17 08:12
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

After you've posted the repository, I'll try to reproduce the issue.

Thanks!

**Comment by osteel** [comment] 2021-06-17 09:35
Hi @driesvints, I'm having trouble with the bug-report codebase for some reason (e.g. the `$this->mock()` method doesn't seem to be recognised from test classes, and binding resolution seems to fail) but here is [the repository](https://github.com/osteel/laravel-mock-bug-report), with a couple of instructions in the README file.

Let me know if you need anything else.

**Comment by driesvints** [comment] 2021-06-17 09:42
Hey @osteel. It seems you committed all your code as a single commit. I need a separate commit with your custom changes to see what you've modified.

**Comment by osteel** [comment] 2021-06-17 09:43
@driesvints yeah I did, my bad. Also found the issue, now fixed. Let me just redo this, one sec

**Comment by osteel** [comment] 2021-06-17 09:51
@driesvints [there you go](https://github.com/osteel/laravel-mock-bug-report)

**Comment by driesvints** [comment] 2021-06-17 16:22
I have to throw in the towel here. I just can't figure it out. When I debug the container it returns the correct mocked instance but it arrives as the actual concrete implementation in the test somehow? No idea why that happens...

**Comment by osteel** [comment] 2021-06-17 16:33
@driesvints well, in a way it's comforting that I wasn't just doing something stupid 😄 

Thanks for looking into this – hopefully some reinforcements will help crack the case

**Comment by donnysim** [comment] 2021-06-18 05:59
Container.php:740
```php
if (isset($this->instances[$abstract]) && ! $needsContextualBuild) {
    return $this->instances[$abstract];
}
```

My 2 cents here, it is determined as `$needsContextualBuild` so it skips returning the registered instance (which is the mock) and builds it again, thus receiving the original concrete instead of the mocked one. I'm not sure what the purpose of the contextual build is so can't really tell what the correct way to fix this should be.

**Comment by driesvints** [comment] 2021-06-18 09:34
@donnysim I checked into that piece of code and it did return the mocked instance for me. It just comes out as the concrete implementation. I have no idea why that is.

**Comment by donnysim** [comment] 2021-06-18 09:44
@driesvints interesting, for me it didn't - `$needsContextualBuild` is true and it skips that part, if I remove the context check, the mocked instance is returned in the test and it passes.

**Comment by driesvints** [comment] 2021-06-18 09:55
```php
        if (isset($this->instances[$abstract]) && ! $needsContextualBuild) {
            if ($abstract === \App\FooContract::class) dd($this->instances[$abstract]);

            return $this->instances[$abstract];
        }
```

Gives

```bash
$ phpunit tests/Unit                                                                                                                                                                                                                ~/Sites/test-mocking
PHPUnit 9.5.5 by Sebastian Bergmann and contributors.

Mockery_0_App_FooContract {#432
  #_mockery_expectations: array:1 [
    "bar" => Mockery\ExpectationDirector {#433
      #_name: "bar"
      #_mock: Mockery_0_App_FooContract {#432}

...
```

**Comment by donnysim** [comment] 2021-06-18 10:01
But that is triggered on
```php
// Would expect to get "corge"...
$this->mock(FooContract::class, function (MockInterface $mock) {
    $mock->shouldReceive('bar')->once()->andReturn('corge');
});
```

when it calls 
```php
$result = resolve(FooContract::class, ['baz' => 'baz'])->bar(); // ... but still getting "qux"
```
it does not trigger that code.

**Comment by driesvints** [comment] 2021-06-18 10:30
Thanks @donnysim, that was helpful. I didn't realize the container also resolved the mocked dependency immediately.

I currently got it working with:

```php
        if (isset($this->instances[$abstract]) &&
            ($this->instances[$abstract] instanceof MockInterface || ! $needsContextualBuild)) {
            return $this->instances[$abstract];
        }
```

But that wires the `MockInterface` to the container and I'm not sure that's wanted.

**Comment by Nacoma** [comment] 2021-06-19 20:37
[replicating the issue in the service provider (no mock)](https://github.com/Nacoma/laravel-mock-bug-report/commit/baff0a70e4d7cbaf8a6ee9d40e623136e6a592a3)

In the non-working version - a concrete `FooContract` is registered as an instance in the container. This action does not replace the original binding. 

The documentation does state that:

> The given instance will always be returned on subsequent calls into the container

but instances are not registered as actual singletons. A new instance will be returned if it's explicitly requested (eg telling it to use new constructor arguments).

[working version](https://github.com/Nacoma/laravel-mock-bug-report/blob/main/app/Providers/AppServiceProvider.php#L25)

Replacing the call to `instance` with an explicit `singleton` binding [here](https://github.com/laravel/framework/blob/952f84a3a5449a5f80190479240fce15bdaad558/src/Illuminate/Foundation/Testing/Concerns/InteractsWithContainer.php#L53) should fix this.

If we do expect a mocked instance to be bound as a singleton then we simply need to register it as one.

**Comment by driesvints** [comment] 2021-07-02 16:50
We're reverting the PR that fixed this because it's breaking other people's test suites. We'll need to look at an alternative approach.

@donnysim can you please try out my approach from above?

**Comment by donnysim** [comment] 2021-07-02 18:17
@driesvints can't vouch for other use cases but it does work for us - both the contract and the concrete, including aliases is received as mocked instance despite the provided parameters.

**Comment by donnysim** [comment] 2021-07-02 18:39
For some reason I just can't stop the feeling that mocking all instances is just wrong, like this will lead yet again to other issues like resolving multiples of the same contract but with different parameters leave you with the same mock. Somehow I'd want to say that an instance resolve callback should be the way to go to decide if you want to return a mocked instance or a real one, maybe something in the line of:

```php
$this->mockInstance(FooContract::class, function (FooContract $instance, MockInterface $mock) {
    if ($something) {
        return $foo;
    }
    
    return $mock->shouldReceive('bar')->once()->andReturn('corge');
});
```

but not sure if I'm way off the target or not.

**Comment by sentiasa** [comment] 2021-07-04 15:25
I have had the same issue - reverted back to `"laravel/framework": "8.49.0"` and the mocking works again.

**Comment by driesvints** [comment] 2021-07-05 09:54
@donnysim I'm going to close this now. Feel free to reply when you've found time to test that out.

**Closed by driesvints** 2021-07-05 09:54 UTC
Labels: bug, help wanted

**Comment by osteel** [comment] 2021-08-19 16:16
Hey,

I couldn't find a way to solve this without changing `Container.php` so I went for an approach inspired by @Nacoma's comments and PR. Registering the mock as a singleton solves the issue so I opened a [PR](https://github.com/laravel/framework/pull/38453) adding a method to the `InteractsWithContainer` trait to make that easier.

It's all new code so won't affect existing test suites.

**Comment by osteel** [comment] 2021-08-19 16:27
PR was closed 🤷

**Comment by supunkavinda** [comment] 2022-07-02 22:23
Still have this issue on Laravel 9.14.1. @osteel Found any workarounds?

**Comment by jameshulse** [comment] 2024-07-26 02:14
Same issue in Laravel 11 all this time later. Would love to know if there is a resolution as it can be a real time sink trying to debug why a mock isn't working.

The issue can be resolved manually by changing:

```php
$this->mock(MyClass::class, ...);
```

To:

```php
$this->app->singleton(MyClass::class, function () {
    $mock = $this->mock(MyClass::class)
    ...setup mock
    return $mock;
```

But this obviously isn't very discoverable, or ideal. Hopefully we can come to some resolution between Laravel tests, and the container.

**Comment by jobyh** [comment] 2024-10-08 08:40
+1 Also experiencing this issue. Hey @osteel 👋 fancy meeting you here! 😄
