### ISSUE TITLE
No tests found in class treated as an error, yet not reported via php artisan test

### ISSUE THREAD

**Issue by kassah** [laravel/framework#49152] opened 2023-11-28 01:19 UTC
### Laravel Version

10.33.0

### PHP Version

8.2.11

### Database Driver & Version

none

### Description

`php artisan test` does not report files without unit tests, but the exit code returned is 1. This makes CI fail when the output says everything succeeded.

### Steps To Reproduce

1. Create Laravel site
2. In bash (or zsh) run `php artisan test`
3. Run `echo $?`
4. Observe 0 - Indicating all tests succeeded.
5. Edit `tests/Unit/ExampleTest.php`
6. Change method name from "test_that_true_is_true" to "ensure_that_true_is_true"
7. In bash (or zsh) run `php artisan test`
8. Observer that all looks good, and all tests passed.
9. Run `echo $?`
10. Observe 1 - Indicating a failure somewhere.
11. Run `php vendor/bin/phpunit`
12. Observer a warning: No tests found in class "Tests\Unit\ExampleTest".
13. Run `echo $?`
14. Observe 1 - Indicating a failure

**Comment by crynobone** [comment] 2023-11-28 01:38
Duplicate of https://github.com/nunomaduro/collision/issues/293 and it seems a PR is already available pending review.

**Comment by kassah** [comment] 2023-11-28 07:07
Excellent! Thank you for identifying that.

**Closed** 2023-11-28 08:40 UTC
