### ISSUE TITLE
Container::when does not work for handling Jobs.

### ISSUE THREAD

**Issue by frankdejonge** [laravel/framework#23602] opened 2018-03-18 14:32 UTC
- Laravel Version: 5.6.12
- PHP Version: 7.2.1
- Database Driver & Version: Not relevant

### Description:

I want to contextually bind a service to the `handle` method of a `Job`. When 

### Steps To Reproduce:

1. Have a Job that takes a service defined as an interface.
2. Bind a service contextually to the job.

```php
$this->app->when(Job::class)->needs(Contract::class)->give(function () { return Concrete(); });
```

### Result

The queue worker endlessly tries to process the message, failing and then retrying. It was not easy to determine this was the problem either. When wiring cannot be resovled I don't expect it to be handled the same way "failed job processing" is handled.

<img width="513" alt="screen shot 2018-03-18 at 15 30 11" src="https://user-images.githubusercontent.com/534693/37567038-53a9f78a-2ac1-11e8-8b4c-5103e38cda1b.png">

**Comment by devcircus** [comment] 2018-03-18 18:17
I may be wrong, but I believe the contextual binding only applies to constructor injection. 

I know it isn't exactly what you're looking for, but check out [this PR](https://github.com/laravel/framework/pull/16800). It may help.

**Comment by frankdejonge** [comment] 2018-03-18 19:51
@devcircus that does the trick. There's no documentation for that feature it seems and the IDE helpers didn't hint that method, so I had no clue. But, besides that I think think the error in resolving the job should not result in a retry loop.

**Comment by driesvints** [comment] 2018-11-20 16:15
@devcircus I'll try to send in a PR to the docs for this because this hasn't been documented it seems. 

@frankdejonge you're right. I'll update the docs to clarify this in the contextual binding section and link to the new docs which I'm going to send in for the referenced PR.

You're also right that the retry perhaps isn't wanted for a container resolving issue. Do you perhaps know which exception is thrown? We might be able to catch it and properly handle it.

**Comment by driesvints** [comment] 2018-11-20 16:16
@frankdejonge nvm. Just saw https://github.com/laravel/framework/issues/23599 :)

**Comment by driesvints** [comment] 2018-12-05 14:41
@devcircus @frankdejonge it's not documented at least: https://github.com/laravel/docs/commit/d17e70151139a8e41e1cd7fe809af110d693a201

Will further investigate this issue as soon as I get to it.

**Comment by nmokkenstorm** [comment] 2019-11-08 15:11
The PR seeks that references this bug seeks to resolve this issue. The specific case for jobs is something that I run into regularly.

@devcircus seems to disagree with my approach, please share your thoughts in the PR if you can.

**Comment by driesvints** [comment] 2019-11-11 15:43
@nmokkenstorm the actual issue here is that the worker endlessly retries the job for a container resolver failure.

**Comment by nmokkenstorm** [comment] 2019-11-11 15:49
@driesvints I'm aware that that's why the issue was raised. The cause of the specific failure however, is a problem I've encountered before, and am trying to solve in the PR.

**Comment by taylorotwell** [comment] 2020-04-23 15:40
There is not really an issue. The retry loop isn't endless when tries is set:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/463230/80118995-be9b1800-854e-11ea-870b-4f515ff46d69.png">

There are situations when retrying would indeed be warranted for example if the constructor of the injected service connects to an external resource like Redis and fails to resolve because Redis is down. I'm not saying that is great design but in that case retry would be warranted.

**Closed by taylorotwell** 2020-04-23 15:40 UTC
Labels: bug
