### ISSUE TITLE
[7.x] Comment {{-- <x-tag>--}} | Compile it NOT exclude

### ISSUE THREAD

**Issue by djcode-it** [laravel/framework#31714] opened 2020-03-03 18:51 UTC
- Laravel Version: 7.x
- PHP Version: 7.3
- Database Driver & Version: na

### Description:
i create new component, then if a exclude from code with comment. Te system compile it in blade.

### Steps To Reproduce:
php artisan make:component contact

>in resources: {{-- <x-contact></x-contact> --}}

>in component:
```
<div>
    <h1>Component</h1>
</div>
```

> in render:
```
{{--
Component
--}}
```

**Comment by driesvints** [comment] 2020-03-03 19:09
Duplicate of https://github.com/laravel/framework/issues/31711

**Closed by driesvints** 2020-03-03 19:09 UTC
