### ISSUE TITLE
Collection type casting does not accept modification

### ISSUE THREAD

**Issue by darron1217** [laravel/framework#24561] opened 2018-06-12 11:10 UTC
- Laravel Version: 5.5.40
- PHP Version: 7.1.6
- Database Driver & Version: mysql 5.7

### Description:
Collection type casting was added to framework
Now I can cast attribute to collection like this:
```
protected $casts = [
    'options' => 'collection',
];
```

But whenever I try to modify collection using `put()` method:
```
$user->options->put('birthday', '2018-06-12');
$user->save();
```
It never save changes.

I should have to save it like this way:
```
$options = $user->options;
$options->put('birthday', '2018-06-12');
$user->options = $options;
$user->save();
```

It's too verbose.
It seems like bug I thought. How can we fix it?

**Comment by staudenmeir** [comment] 2018-06-12 12:22
Eloquent internally stores the attribute as a JSON string. Every time you access the attribute, Eloquent creates a new `Collection` instance. When you mutate the attribute, it gets converted back to JSON.

I don't think there's a way for Eloquent to detect changes on the `Collection` instance.

**Comment by themsaid** [comment] 2018-06-12 19:33
duplicate of https://github.com/laravel/framework/issues/19743

**Closed by themsaid** 2018-06-12 19:33 UTC

**Comment by darron1217** [comment] 2018-06-13 00:58
@themsaid I think it's different problem.
There's comment about this issue, but it's quite different issue

This is about manipulating, and issue #19743 is about null value
(Recently I created PR #24527 about the issue and got rejected)

**Comment by linaspasv** [comment] 2019-02-28 17:25
@darron1217 I have run in the same issue. The problem is that Eloquent creates a new collection each time you try to access it directly. It's also a performance issue if you try to access cast attributes directly. I doubt this would be accepted as PR (I have not tried) but I do use the following caching for default Model and extend my models with the following class.

```php
use Illuminate\Database\Eloquent\Model as BaseModel;

abstract class Model extends BaseModel
{
    protected $castAttributeCache = [];

    /**
     * cache cast attributes
     *
     * @param string $key
     * @param mixed $value
     * @return mixed
     */
    protected function castAttribute($key, $value)
    {
        if (! isset($this->castAttributeCache[$key])) {
            $this->castAttributeCache[$key] = parent::castAttribute($key, $value);
        }

        return $this->castAttributeCache[$key];
    }

}
```
