### ISSUE TITLE
Using implode() method, with " or " glue, in blade template throws exception

### ISSUE THREAD

**Issue by bridgeport** [laravel/framework#12488] opened 2016-02-25 23:08 UTC
Using Laravel 5.2.21, here's how to reproduce it:

Pass the following collection variable to a view:
```php
$collection= collect([
    [
        'name' => 'Jane'
    ],
    [
        'name' => 'John'
    ]
]);
```

Try to output the following in a blade template view:

```
{{ $collection->implode('name', ' or ') }}
```

It throws

> FatalErrorException ... syntax error, unexpected 'name' (T_STRING)

Could this be happening due to Laravel's Blade ternary statement, as documented here:
https://laravel.com/docs/5.2/blade#displaying-data

> However, instead of writing a ternary statement, Blade provides you with the following convenient short-cut:
> 
> `{{ $name or 'Default' }}`

Thanks.

**Comment by danieliancu** [comment] 2016-02-25 23:10
Duplicate of #10135

**Comment by bridgeport** [comment] 2016-02-25 23:22
@danieliancu I saw that, but posted this issue as it seems a little different. The output of the implode() returns a string, the `$glue` can only be a string, yet it doesn't appear to be treated like a regular string.

For instance, these work
```
{{ implode(' or ', ['Jane', 'John']) }}

{{ implode(' or ', array_column($collection->toArray(), 'name')) }}

{{ 'Jane or John' }}
```

while Laravel's `implode()` doesn't.

**Comment by danieliancu** [comment] 2016-02-25 23:24
@bridgeport can you please post the generated output?

**Comment by danieliancu** [comment] 2016-02-25 23:29
@bridgeport it has nothing to do with the `implode` method, it's because of the `or` keyword usage.

**Comment by GrahamCampbell** [comment] 2016-02-25 23:59
This is a known bug, and there is no known fix, sorry.

**Closed** 2016-02-25 23:59 UTC
