### ISSUE TITLE
Router caching: navigate to url with trailing '/' gets different result from non cached router

### ISSUE THREAD

**Issue by Snowing** [laravel/framework#31768] opened 2020-03-05 15:16 UTC
- Laravel Version: 7.0.4 and 7.0.5
- PHP Version: 7.4.2 // 7.3

### Steps To Reproduce:

1. start new laravel site

2. Remove default Closure routes

3. Adding two routes that simply echoes their content ( 2nd overrides 1st, they are same)

```
Route::get('/test','TestController@withoutTrailing');  //echo withoutTrailingRoute
Route::get('/test/','TestController@withTrailing');  //echo withTrailingRoute
```
`$ php artisan:serve`
Navigate to "/test" and "/test/" both giving same result  "withTrailingRoute"

4. Cache routes
 `$ php artisan optimize `  (or route:cache)

Navigate to "/test" giving result  "withTrailingRoute"
Navigate to "/test/" throws ResourceNotFoundException

### Quick workaround
add middleware with earliest start  //Before checkMaintenanceMode for ex.
`$request->server->set('REQUEST_URI', rtrim($request->server->get('REQUEST_URI'), '/'));`

**Comment by rognales** [comment] 2020-03-05 18:26
I have similar issue too.
My index route will return 404 when route in cached mode
````php
Route::get('/', 'DashboardController@index')->name('index');
````

````php php artisan route:list```` confirmed that this single particular route is not registered if route is being cached.

**Comment by driesvints** [comment] 2020-03-05 20:40
We're investigating this

**Comment by rognales** [comment] 2020-03-09 07:55
7.0.7 seems to fix this even though 7.0.8 change-log is referring to this bug

**Comment by msonowal** [comment] 2020-03-09 09:39
@rognales 
i dont think so

**Comment by driesvints** [comment] 2020-03-09 20:04
We've pushed a fix that will get tagged tomorrow. Thanks for reporting.

**Closed by driesvints** 2020-03-09 20:04 UTC
Labels: bug

**Comment by msonowal** [comment] 2020-03-11 08:19
Hi @driesvints ,
Are you referring to the release `laravel  7.1.0`,
I have just checked it is still not working

**Comment by miken32** [comment] 2020-03-11 12:56
7.1.0 resolved this problem for me. Make sure to clear and rebuild your route cache.

**Comment by driesvints** [comment] 2020-03-11 14:37
@msonowal are you sure? Because that definitely should have fixed it.

**Comment by nielspeen** [comment] 2020-03-11 14:49
I have the same issue, even with 7.1.0.

```
Route::get('/test','TestController@show');
```

Using example.com/test works, using example.com/test**/** results in a 404.

Disabling route cache fixes the issue.

**Comment by msonowal** [comment] 2020-03-11 22:27
> @msonowal are you sure? Because that definitely should have fixed it.

Yes I am sure,
I have cleared cache and recached

**Comment by Raymonf** [comment] 2020-03-13 15:17
@driesvints I'd like to confirm that the bug still occurs. Could you reopen the issue?

**Comment by msonowal** [comment] 2020-03-16 07:29
ping @GrahamCampbell @driesvints  any update on this?

**Comment by driesvints** [comment] 2020-03-16 10:25
Open up a new issue with exact steps to reproduce please.

**Comment by oprypkhantc** [comment] 2020-03-18 16:15
Can confirm. Still relevant with 7.2.0.
