### ISSUE TITLE
Nested arrays with same key names pick up incorrect validation message

### ISSUE THREAD

**Issue by mattford** [laravel/framework#22499] opened 2017-12-21 09:21 UTC
- Laravel Version: 5.4.36
- PHP Version: 5.6.32
- Database Driver & Version: Mongo

### Description:
When validating nested arrays with the same keys and rules, an incorrect error message will be picked up, for example, if the rules are:

`
$rules = [
    'item.*.text' => 'required',
    'item.*.subitem.text' => 'required',
];
`

and the messages:

`
$messages = [
    'item.*.text.required' => 'top level item required',
    'item.*.subitem.text.required' => 'sub item required',
];
`

"top level item required" will be returned as the error message for both items

I believe this is due to an error in the \Illuminate\Support\Str line 152

The pattern is currently:

`$pattern = str_replace('\*', '.*', $pattern);`

I think it needs to be:

`$pattern = str_replace('\*', '[^.]*', $pattern);`

Edit: above only really applies to validation, so perhaps Str.php isn't the best location for the change

### Steps To Reproduce:
Define the rules specified above, and provide invalid input for both fields

**Comment by mattford** [comment] 2017-12-21 09:25
Workaround: put the more restrictive regex first in the rules and messages arrays

**Comment by Dylan-DPC** [comment] 2017-12-21 09:58
Note that 5.4 is no longer supported. Can you reproduce the issue in a 5.5 environment?

**Comment by mattford** [comment] 2018-04-09 07:47
@Dylan-DPC I can reproduce in 5.5 yes, my controller code:

```
public function thisRouteRequiresValidation(Request $request)
{
    $rules = [
        'hello.*.text' => 'required',
        'hello.*.world.text' => 'required',
    ];

   $messages = [
        'hello.*.text.required' => 'hello.*.text required',
        'hello.*.world.text.required' => 'hello.*.world.text required',
   ];

    $res = Validator::make($request->all(), $rules, $messages);
    $fail = $res->fails();
    $messages = $res->errors();
    return response()->json(['hello' => 'world', 'fail' => $fail, 'messages' => $messages]);
}
```

I sent a request with the content:

```
{
	"hello": [
		{
			"text": "Hello World"
		}
	]
}
```

and the response is:

```
{
    "hello": "world",
    "fail": true,
    "messages": {
        "hello.0.world.text": [
            "hello.*.text required"
        ]
    }
}
```

as you can see, the rule fired is the hello.0.world.text rule, but the message for hello.*.text has been given

**Comment by staudenmeir** [comment] 2018-04-24 01:26
`Str::is()` is called in [`FormatsMessages::getFromLocalArray()`](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Validation/Concerns/FormatsMessages.php#L101).

We can't use `str_replace('*', '[^.]*', $sourceKey)` because it gets escaped by `preg_quote()`.

We could:

  - Add a `$wildcard = '.*'` parameter to `Str::is()` and override it with `'[^.]*'`.
  - Add a `$escape = true` parameter to `Str::is()` and override it with `false` (Taylor is not fan of those).
  - Add something like `Str::isRaw()` which doesn't escape the pattern(s).

**Comment by mattford** [comment] 2019-03-01 08:41
@staudenmeir Been thinking about this (for almost a year apparently)

Not sure it's worth doing `Str::isRaw` since it would basically be a direct passthrough to `preg_match` 

What do you think about changing `FormatsMessages::getFromLocalArray` to use preg_match directly?

Happy to do the work and submit a PR once we decide on a solution

**Comment by mattford** [comment] 2019-03-01 09:52
Scratch that, `$wildcard` seems the most elegant to me, will submit a PR today!

**Comment by staudenmeir** [comment] 2019-03-01 10:07
Remember to target Laravel 5.9, as this is a breaking change.

**Comment by mattford** [comment] 2019-03-01 10:10
I considered it non breaking as existing usage of `Str::is` will function as normal.

But I suppose this will change the behaviour of validation (to be correct), so that is why?

**Comment by staudenmeir** [comment] 2019-03-01 10:22
Adding the new parameter to `Str::is()` is the breaking change. It's optional, but still breaks code that overrides the `Str::is()` method.

**Comment by mattford** [comment] 2019-03-01 10:23
@staudenmeir I see what you mean, targeted to 5.9

**Comment by driesvints** [comment] 2019-03-04 15:05
Since the PR was rejected I'm also closing this issue. Feel free to create your own macro with this specific behavior.

**Closed by driesvints** 2019-03-04 15:05 UTC
Labels: bug, lts
