### ISSUE TITLE
Prevent lazy load hasMany optional relation when foreign_key is null

### ISSUE THREAD

**Issue by dvlpp** [laravel/framework#5289] opened 2014-07-31 16:18 UTC
I've got a hasMany relationship defined this way, in a <code>Command</code> Eloquent model:

    public function rows()
    {
        return $this->hasMany('\Acme\Models\Row')
    }

In my case, rows can be linked to Commands, or not. So my Row migration file contains a nullable foreign key:

    $table->integer('command_id')->unsigned()->nullable()->index();
    $table->foreign('command_id')->references('id')->on('commands')->onDelete('set null');

I realize thought that if I instantiate a new Command object and call <code>$command->rows</code>, instead of an empty Collection, I get all the rows with a null command_id.

This is perfectly explained by the SQL generated by this <code>$command->rows</code> call:

    select * from `rows` where `rows`.`command_id` is null

I think it's strange that Laravel choose to consider valid a null foreign key... What do you think: is this a bug? Am I missing something? What could be the best way to prevent this behavior?

(pasted from http://stackoverflow.com/questions/25063201/laravel-4-prevent-lazy-load-hasmany-relation-when-foreign-key-is-null-optional)

**Comment by mnpenner** [comment] 2015-01-31 23:22
:+1: This occurs whenever I use `->with()` to precache some data, but the FK is `null`. In fact, it's worse because it converts the `null` to `0`. e.g.,

```sql
select * from `users` where `users`.`id` in ('0')
```

**Comment by GrahamCampbell** [comment] 2015-04-11 23:18
Is anyone able to PR this?

**Comment by Douglasdc3** [comment] 2015-05-04 20:19
Tested this bug in both L5 & L4.2 below you'll find my results

#Laravel 5

Performing in your setup `$command->rows` returns an empty collection

#Laravel 4.2

Running the following code:

```php
    $command = Acme\Models\Command::first();
    dd($command->rows);
```

Returns

```php
     string 'select * from `commands` limit 1' (length=32)
     string 'select * from `rows` where `rows`.`id` is null' (length=46)

     object(Illuminate\Database\Eloquent\Collection)[168]
         protected 'items' => 
             array (size=0)
                 empty 
```

*conclusion* both L4 & L5 have now the same behaviour, only the SQL statement differs where L5 will search on `string 'select * from `rows` where `rows`.`id` is not null'`.
 
After more testing it seems this issue has been fixed and can be closed @GrahamCampbell

**Comment by lukasgeiter** [comment] 2015-05-12 21:45
I agree with @Douglasdc3, this has been fixed with [this commit](https://github.com/laravel/framework/commit/1e80162e9a3a4c42a0079bd9f34e785197a66c07) and can be closed.

**Comment by mnpenner** [comment] 2015-05-12 21:52
@lukasgeiter Are you sure that fixes it? That looks like it prevents loading unrelated models, but it still runs the query. If I have a collection of `$users`, and users have a nullable `profile_id` column, and *all* the users in my collection have `profile_id=null`, then when I do `$users->with('profiles')` it shouldn't search profiles with id `0`, or even run the query at all.

**Comment by lukasgeiter** [comment] 2015-05-12 21:58
I couldn't reproduce the bug with eager loading because I fail to see how it is possible to eager load a relationship of a model without primary key (meaning not saved / loaded from the db). Please add a more verbose code sample of your code.

I agree that it could be optimized so that the query doesn't even run and I will look into that. However that's more of a optimization issue and not a bug.

**Closed** 2015-05-13 13:43 UTC
Labels: bug, database
