### ISSUE TITLE
Components breaks when passing '(' and ')'

### ISSUE THREAD

**Issue by rdpascua** [laravel/framework#18355] opened 2017-03-15 18:42 UTC
- Laravel Version: 5.4.15
- PHP Version: 7.0
- Database Driver & Version: Not applicable

### Description:

Passing a parenthesis breaks the blade compiler.

```
Parse error: syntax error, unexpected '>' (View: /home/rdpascua/Projects/experimental/components-bug/resources/views/welcome.blade.php)
```

### Steps To Reproduce:

Create two blade files, one for the component and one for the base file.

**test.blade.php**
```html
<div>
    {{ $title }}
    {{ $slot }}
</div>
```

**welcome.blade.php**
```html
@component('test', ['title' => 'foo :('])
    <h1>Hello</h1>
@endcomponent
```

**Comment by Kyslik** [comment] 2017-03-15 18:44
This might be related https://github.com/laravel/framework/issues/18317.

**Comment by rdpascua** [comment] 2017-03-15 18:47
@Kyslik This works in sections too?

**Comment by themsaid** [comment] 2017-04-06 07:07
Yes it's related to https://github.com/laravel/framework/issues/18317, it's a generate Blade limitation :)

Closing this since the issue is already reported there.

**Closed by themsaid** 2017-04-06 07:07 UTC
