### ISSUE TITLE
[5.5] Blade @php directive

### ISSUE THREAD

**Issue by MCMatters** [laravel/framework#20994] opened 2017-09-04 23:37 UTC
- Laravel Version: 5.5.1
- PHP Version: 7.1.8
- Database Driver & Version: mysql 5.7.19

### Description:
Previously there was an ability to create php code with single line of using `@php` directive. Now I can't use it without `@endphp`. I didn't see any mentions about it in Upgrade guide or documentation. Is it bug?

### Steps To Reproduce:
Try to create view with next code:

```
@if (isset($team))
    @php ($some = true)
@else
    @php ($some = false)
@endif

@php
    $someElse = true;
@endphp
```

And you will get

```
<?php if(isset($team)): ?>
    <?php ($some = true)
@else
    @php ($some = false)
@endif

@php
    $someElse = true;
?>
```

**Comment by themsaid** [comment] 2017-09-05 10:34
@sileence please check, this PR broke the given case: https://github.com/laravel/framework/pull/20065

**Comment by sileence** [comment] 2017-09-05 11:15
@themsaid agh, I can see why. I'm working on it.

**Comment by themsaid** [comment] 2017-09-05 11:16
@sileence thanks :)

**Comment by jmarcher** [comment] 2017-09-09 07:34
Shouldn't it be like this?
```
@if(isset($team))
    @php($some = true)
@else
    @php($some = false)
@endif

@php
    $someElse = true;
@endphp
```

**Comment by themsaid** [comment] 2017-09-13 13:21
Closing as a no-fix.

You can use regular PHP opening and closing tags.

**Closed by themsaid** 2017-09-13 13:21 UTC
Labels: Action needed

**Comment by MCMatters** [comment] 2017-09-13 18:05
Add to documentation this info and to upgrade guide as well

**Comment by ShahidH** [comment] 2017-09-28 20:58
@jmarcher  It appear `@php($some = true)` is longer supported in 5.5

**Comment by judgej** [comment] 2018-03-14 10:25
`@php(blah)` is working in 5.6. Is it back by design, or an anomaly?

**Comment by jmarcher** [comment] 2018-03-14 10:42
@judgej It should not be working.

**Comment by judgej** [comment] 2018-03-14 10:48
@jmarcher Thanks. I'll put it down to an anomaly, and move to the block format before it stops working on the next update.

**Comment by Log1x** [comment] 2019-02-11 09:23
I really wish this wasn't removed...

**Comment by driesvints** [comment] 2019-02-11 11:10
`@php()` is still supported, just the inline version was removed.

**Comment by Hazzard13** [comment] 2019-07-12 15:30
Hey, can we at least see this added to the upgrade guide? Definitely unhelpful to end up here after nearly an hour of debugging an "Unexpected endforeach".

Don't really understand why the single-line @php was removed, as it makes for much cleaner templates, but it should at least be clear in the guide, as I almost didn't catch this in testing, and followed the upgrade guide to the letter.

**Comment by devcircus** [comment] 2019-07-12 20:32
The change was made in 5.5 and mentioned in the upgrade guide. There was a lot of discussion prior to the change due to numerous issues that were not practical to resolve. https://laravel.com/docs/5.5/upgrade

**Comment by Hazzard13** [comment] 2019-07-12 20:49
Ah, my apologies. I must've missed while upgrading, because I was upgrading an angular app and probably skimmed the blade section. Sorry to waste your time!

**Comment by kapitannwel** [comment] 2020-07-15 00:53
@Hazzard13 - I too like this shortcut format as it seems to be more simple. i usually use this in counting rows @php($counter=0) @foreach() @php($counter++) @endforeach. Sad to know it's gone. thanks for this thread, as i was informed!

**Comment by Log1x** [comment] 2020-07-15 02:24
> @Hazzard13 - I too like this shortcut format as it seems to be more simple. i usually use this in counting rows @php($counter=0) @foreach() @php($counter++) @Endforeach. Sad to know it's gone. thanks for this thread, as i was informed!

From me experience, you can still use shorthanded `@php()` in blade views, you just can't mix it with the long-handed (`@php @endphp`) version in the same view.

**Comment by kapitannwel** [comment] 2020-07-15 23:53
> > @Hazzard13 - I too like this shortcut format as it seems to be more simple. i usually use this in counting rows @php($counter=0) @foreach() @php($counter++) @Endforeach. Sad to know it's gone. thanks for this thread, as i was informed!
> 
> From my experience, you can still use shorthanded `@php()` in blade views, you just can't mix it with the long-handed (`@php @endphp`) version in the same view.

i am actually using it on some of my blade files, but it is not working on some blade files that is why i searched on it, thus the reason why i arrived on this thread. knowing this, i think i shouldn't use it anymore to be safe.

**Comment by mirafzal** [comment] 2022-10-05 19:51
regex replace:
https://github.com/php((.*))
https://github.com/php $1 @endphp
