### ISSUE TITLE
view:clear should be run after postInstall / Laravel upgrades.

### ISSUE THREAD

**Issue by AdenFraser** [laravel/framework#15322] opened 2016-09-07 15:56 UTC
- Laravel Version: 5.2.44
- PHP Version: 7.0.*
- Database Driver & Version: MySQL

### Description:
Illuminate\\Foundation\\ComposerScripts::postInstall should clear views (php artisan view:clear).

Otherwise changes to blade compiler which aren't compatible between versions result in unexpected errors.

As far as I'm aware this currently isn't an issue if moving forward between versions (I havn't tested confirm) but it is an issue if moving BACKWARD. Obviously that's somethign that would never actually happen in production but given it can happen going backwards it could happen when upgrading on a server.

Alternatively, mentioning in the upgrade process that after an upgrade view:clear should be run would make sense.

**Comment by themsaid** [comment] 2016-09-07 20:15
I'd say go ahead and create a PR that runs the command after the `post-update-cmd`.

Closing since it's not a bug report :)

**Closed by themsaid** 2016-09-07 20:15 UTC

**Comment by crynobone** [comment] 2016-09-08 00:05
In earlier releases or 4.x or 5.0 Laravel does include this under `post-install-cmd`, however with the introduction of Envoyer and zero downtime deployment (in general) this does create some issue because:

* composer is executed very early in the deployment.
* `storage/framework/views` is shared between builds.

For app that has high concurrent access, it's very likely the views will still be loaded from the older build (as deployment still continues in the background) and hence you still getting the old code, which might not work when the deployment completed.

> I'd say go ahead and create a PR that runs the command after the `post-update-cmd`.

Post update command is only executed locally (for development), production should only run `composer install`.
