### ISSUE TITLE
[5.4] UrlWindow problem in getUrlSlider() method

### ISSUE THREAD

**Issue by colorkeks** [laravel/framework#20699] opened 2017-08-23 11:50 UTC
- Laravel Version: 5.4
- PHP Version: 7.1

When i set the parameter $onEachSide = 1, i have a problem in this part of code:
`elseif ($this->currentPage() > ($this->lastPage() - $window)) {`
`        return $this->getSliderTooCloseToEnding($window);`
`}`

For example, if we have 16 pages, and current page is 14, slider looks like |<|1|2|...|13|14|**15**|...|**15**|16|>|
It's happens, because condition is not correct?
In this situation: currentPage() = 14, lastPage() = 16 $window = $onEachSide * 2. 
So we have condition 14 > 16 - 2  - returns false, and getUrlSlider() method will return getFullSlider() method data;

P.S. sorry for bad english )

**Comment by Dylan-DPC** [comment] 2017-08-23 14:29
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by colorkeks** [comment] 2017-08-23 14:39
@Dylan-DPC How forums should help me fix the bug in laravel-pagination ?

**Comment by Dylan-DPC** [comment] 2017-08-23 14:47
Can you give more details on how it is a bug? It isn't clear so far

**Comment by Kyslik** [comment] 2017-08-23 14:47
@colorkeks Where is the code from? Provide a link to correct file + line.

**Comment by colorkeks** [comment] 2017-08-23 15:01
@Kyslik
file: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Pagination/UrlWindow.php
line: 92-94

**Comment by colorkeks** [comment] 2017-08-23 15:12
@Dylan-DPC  when i'm use this class like:
`UrlWindow::make($this->paginator , 1)`
and current page is 14 of 16, data will be returned like: 
```
first => [
1 => 'link',
2 => 'link'
],
slider => [
3 => 'link'
...
15 => 'link' <-
],
last => [
15 => 'link', <-
16 => 'link'
]
```

**Comment by colorkeks** [comment] 2017-08-23 15:26
@Kyslik pagination looks like this:
![screen shot 2017-08-23 at 19 21 24 2](https://user-images.githubusercontent.com/7909324/29623859-b8d7172c-8838-11e7-9078-6aaf20be7cd8.png)

**Comment by themsaid** [comment] 2017-10-18 18:04
Closing since no one was able to replicate also issue is not very clear, I hope you found help in the forums for your issue.

**Closed by themsaid** 2017-10-18 18:04 UTC

**Comment by UksusoFF** [comment] 2018-01-24 19:40
Hi @Dylan-DPC @Kyslik @themsaid 

Please take a look again on this issue.

You can get this repo for quick check this bug: https://github.com/UksusoFF/laravel-demo

Step to reproduce: 
Install Laravel
Seed 5000 users. 
Create custom pagination such as: 
```
$window = UrlWindow::make(User::paginate($perPage = 5, $columns = ['*'], $pageName = 'page', $page = 3), 1);
return response()->json($window);
```
You can see:

First page:
```
{"first":{"1":"http:\/\/laravel.app\/demo?page=1","2":"http:\/\/laravel.app\/demo?page=2","3":"http:\/\/laravel.app\/demo?page=3","4":"http:\/\/laravel.app\/demo?page=4"},"slider":null,"last":{"999":"http:\/\/laravel.app\/demo?page=999","1000":"http:\/\/laravel.app\/demo?page=1000"}}
```
Second page: 
```
{"first":{"1":"http:\/\/laravel.app\/demo?page=1","2":"http:\/\/laravel.app\/demo?page=2","3":"http:\/\/laravel.app\/demo?page=3","4":"http:\/\/laravel.app\/demo?page=4"},"slider":null,"last":{"999":"http:\/\/laravel.app\/demo?page=999","1000":"http:\/\/laravel.app\/demo?page=1000"}}
```
Third page:
```
{"first":{"1":"http:\/\/laravel.app\/demo?page=1","2":"http:\/\/laravel.app\/demo?page=2"},"slider":{"2":"http:\/\/laravel.app\/demo?page=2","3":"http:\/\/laravel.app\/demo?page=3","4":"http:\/\/laravel.app\/demo?page=4"},"last":{"999":"http:\/\/laravel.app\/demo?page=999","1000":"http:\/\/laravel.app\/demo?page=1000"}}
```
Fourth page:
```
{"first":{"1":"http:\/\/laravel.app\/demo?page=1","2":"http:\/\/laravel.app\/demo?page=2"},"slider":{"3":"http:\/\/laravel.app\/demo?page=3","4":"http:\/\/laravel.app\/demo?page=4","5":"http:\/\/laravel.app\/demo?page=5"},"last":{"999":"http:\/\/laravel.app\/demo?page=999","1000":"http:\/\/laravel.app\/demo?page=1000"}}
```
As we can see `first` and `slider` contains duplicate on third page.
