### ISSUE TITLE
[5.2] problem with see method in InteractsWithPages.php

### ISSUE THREAD

**Issue by LarsN** [laravel/framework#12734] opened 2016-03-15 12:45 UTC
I used to be able to test API with post and see methods. The following code example uses post and see methods to check the HTML response but now it doesn't work anymore. It is as if the post method doesn't create a new HTML anymore through the see method.

    public function testBasicExample()
    {
        $this->post('/calculations', ['date' => '2016-01-10'])
             ->see('<td>5,000,000.00
                           </td>
                           <td>0.00
                           </td>');
    }

**Comment by kyranb** [comment] 2016-03-15 12:56
I'm also seeing an issue with InteractsWithPages. For me, `see` works, but `press` does not.

```php

1) AuthTest::testRegistration
Error: Call to undefined method Illuminate\Http\Response::getTargetUrl()

/Users/~/Sites/app/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithPages.php:120
/Users/~/Sites/app/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithPages.php:72
/Users/~/Sites/app/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithPages.php:95
/Users/~/Sites/app/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithPages.php:788
/Users/~/Sites/app/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithPages.php:775
/Users/~/Sites/app/tests/acceptance/AuthTest.php:45

```

**Comment by LarsN** [comment] 2016-03-15 15:29
Reverting back to Laravel Framework version 5.2.6 fixes my issue

**Comment by vlakoff** [comment] 2016-03-15 18:30
ping @sileence :)

**Comment by sileence** [comment] 2016-03-15 19:16
Can you make sure you are using the latest version of Laravel? (5.2.23) If it still doesn't work, I will have a look in some hours (I'm not in front of the computer right now)

The refactor I did on the interact with pages trait should also solve this issue, but this hasn't been merged yet

**Comment by sileence** [comment] 2016-03-16 00:22
@LarsN yes, your test is working in Laravel 5.2.23. I just put the following in routes.php:

```
Route::post('/calculations', function () {
    return '<td>5,000,000.00
                       </td>
                       <td>0.00
                       </td>';
});
```

Please take care with the blank spaces, or you can also test using the methods `seeInElement` or `seeElement` or call `see` twice, one for each row.

**Comment by sileence** [comment] 2016-03-16 00:27
@kyranb I have some AuthTest working for Laravel 5.2.23, the bug in your test is probably being caused by something else but I'd need more information to help you.

**Comment by kyranb** [comment] 2016-03-16 01:12
@sileence Interesting, what information would you like me to provide?

Here's the form itself:

```html
<form class="form-horizontal" role="form" method="POST" action="{{ route('postRegister') }}">
    {!! csrf_field() !!}


<button type="submit" name="submit" class="btn btn-primary">
    <i class="fa fa-btn fa-user"></i>Register
</button>
```

**Comment by LarsN** [comment] 2016-03-16 05:29
@sileence my tests work for all versions up to 5.2.16 but following 5.2.17->5.2.23 all my tests fail. I only tested with `see `method.

**Comment by sileence** [comment] 2016-03-16 10:33
@LarsN this test passes in Laravel 5.2.19 and above: 

```
public function testBasicExample()
{
    $this->post('/calculations', ['date' => '2016-01-10'])
         ->see('<td>5,000,000.00
                       </td>
                       <td>0.00
                       </td>');
}    
```

They only way I managed to break the test, was calling the `visit` method above everything else, like this: 

```
```
public function testBasicExample()
{
    $this->visit('/');

    $this->post('/calculations', ['date' => '2016-01-10'])
         ->see('<td>5,000,000.00
                       </td>
                       <td>0.00
                       </td>');
}    
```

Please verify that is not your case, also can you please verify that your test fails even if you run it like this:

`vendor/bin/phpunit --filter testBasicExample`

You can also PM on Slack (I'm @sileence) to continue to review this further. 

@kyranb I'm also reviewing how to improve that error message you've got :)

**Comment by tomturton** [comment] 2016-03-16 12:17
Not sure if this is related but I have noticed the new `seeElement` method in 5.2.23 does not return `$this` when successful, causing the chaining to break

**Comment by sileence** [comment] 2016-03-16 12:51
@tomturton not related, but good catch, this is all solved in the pending pull request: https://github.com/laravel/framework/pull/12707

**Comment by LarsN** [comment] 2016-03-16 16:24
@sileence without visit method my tests also work in 5.2.19. So it must be the visit method that changes after 5.2.16?

**Comment by sileence** [comment] 2016-03-16 18:27
@LarsN so you are using visit and then post in the same test method? Could you please send me more examples of your tests, maybe in private on Slack or to i@duilio.me. I believe what the problem is and how to solve it, but I'd like to have more information first to be extra sure.

**Comment by sileence** [comment] 2016-03-16 23:36
Fixed here: https://github.com/laravel/framework/pull/12707

**Comment by sileence** [comment] 2016-03-16 23:38
@LarsN instead of using `post` you could try using methods like `seeInDatabase` or create your custom assertions, to check that the data was inserted in the database. Remember that you have the power of PHP when using this framework. If you were using CodeceptJS or other similar frameworks, then you'd need to call another request since you won't be able to access the database etc. from that test context...

**Comment by andremellow** [comment] 2016-03-24 15:19
@sileence, I´ve got other issuer. 

I would not be able to figured out yet, but when I have accent in see text, the e() helper is returning an empty string. 

The problem is, $escapedPattern become blank and regex is testing a empty group

for 
->see('Já existe um usuário com esse email.')

The pattern is : "(J├í existe um usu├írio com esse email\.|)" 

As there is a "|", the second group in the pettern is empty and the regex is looking also for a empty string in the page code, and returning true.

The test is passing even when the string is not found. 

It should test if $escapedPattern is empty, so if e() helpers return an empty string the test will fail;

        $pattern = ( $rawPattern == $escapedPattern || empty($escapedPattern) )
                ? $rawPattern : "({$rawPattern}|{$escapedPattern})";

Hope I've explained well.

**Comment by sileence** [comment] 2016-03-24 16:07
Understood, I will test this and create a PR to solve the issue, thank you for reporting @andremellow

**Comment by sileence** [comment] 2016-03-25 10:11
You need to make sure the encoding of your HTML is UTF-8 as well. See this as an example:

https://github.com/laravel/framework/pull/12852

The tests will pass as long as the charset is set. If I delete `<meta charset="UTF-8">` then the test fails. Since my encoding is UTF-8 but Symfony will default to ISO.

If you still find an issue with this please send more information so I can try/test again.

@GrahamCampbell this bug should be solved now so you can close this if you want to.

**Closed** 2016-03-25 10:50 UTC
Labels: bug
