### ISSUE TITLE
Custom Request Validated() Will Cause Validation Twice

### ISSUE THREAD

**Issue by gofish543** [laravel/framework#25942] opened 2018-10-05 04:05 UTC
Hopefully everything makes sense. This is my first bug report with Laravel, bear with me. If you need any additional information or screenshots please let me know and I'll happily provide them.

- Laravel Version: 5.7.6
- PHP Version:7.2.10
- Database Driver & Version: MySql - 5.7.23

### Description:
A custom Request class in Laravel will validate before entering a controller action, but when the user calls the function $request->validated() the validation instance will re-validate the data. This is a fatal flaw in custom validation rules like Google Recaptcha because once a toke is used in validation it is invalidated. So, when the second validation attempt is made because of the $request->validated() the validation will fail. 

Example Request
```
<?php

namespace App\Http\Requests\Auth;

use App\Rules\CaptchaRule;
use Illuminate\Foundation\Http\FormRequest;

class RegisterRequest extends FormRequest {

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize() {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules() {
        return [
            'recaptchaToken' => ['required', new CaptchaRule()],
        ];
    }
}
```
With the Controller action
```
public function register(RegisterRequest $request) {
        $validData = array_merge($request->validated(), []);
        array_forget($validData, ['recaptchaToken', 'password_confirmation']);

        $user = User::create($validData);

        $user->sendEmailVerificationNotification();

        return $user;
    }
```
I went digging into the request validated method and can confirm that it will also call the validate
```
   /**
     * Get the validated data from the request.
     *
     * @return array
     */
    public function validated()
    {
        return $this->getValidatorInstance()->validate();
    }
```
Below is a screen shot of the rule dumping twice, showing that is validated against twice.
![image](https://user-images.githubusercontent.com/10394554/46515506-d7878f80-c829-11e8-8ab3-3019b5673f0e.png)

**Comment by gofish543** [comment] 2018-10-05 04:09
A potential solution would maybe to make the getValidatorInstance() function create a new validation instance and save it in a class variable within FormRequest.php. Then any subsequent calls to getValidatorInstance() would return that validator instance rather than creating a new one that needs to be validated?

**Comment by ankurk91** [comment] 2018-10-05 04:18
Similar https://github.com/laravel/framework/issues/25736

**Comment by laurencei** [comment] 2018-10-05 05:02
Yeah - this looks like a duplicate of https://github.com/laravel/framework/issues/25736.

If you think this is a different issue, please let us know.

**Closed by laurencei** 2018-10-05 05:02 UTC
