### ISSUE TITLE
SparkPost Transport not storing transmission id before firing sendPerformed

### ISSUE THREAD

**Issue by CyrilMazur** [laravel/framework#18581] opened 2017-03-30 16:26 UTC
- Laravel Version: 5.4.16
- PHP Version: 7.0
- Database Driver & Version: n/a

### Description:

Just like this PR https://github.com/laravel/framework/pull/16366 was merged that stores the Message Id returned by SES, I would need the same behaviour for SparkPost, should I code it and submit a PR?

The same could be done for Mandrill and the other drivers by the way.

**Comment by themsaid** [comment] 2017-03-30 17:36
Yes please feel free to send a PR :)

Closing since it's not a bug report but please go ahead and open a PR.

**Closed by themsaid** 2017-03-30 17:36 UTC
