### ISSUE TITLE
required_without_all bug

### ISSUE THREAD

**Issue by derakoola** [laravel/framework#11795] opened 2016-01-10 10:09 UTC
![screen shot 2016-01-10 at 1 32 06 pm](https://cloud.githubusercontent.com/assets/5869562/12221018/8bd84ffe-b79f-11e5-8cf5-206c6484f3dc.png)
![screen shot 2016-01-10 at 1 32 25 pm](https://cloud.githubusercontent.com/assets/5869562/12221020/8e295fe6-b79f-11e5-8b76-e27b6a4cf2c6.png)

**Comment by andrew-s** [comment] 2016-01-17 03:49
I agree that this is an issue, it's incredibly confusing and doesn't match the description of the validation at all, a similar issue was closed earlier this year #9724 marked as "intended behaviour".

I think either;

A) The documentation clearly needs to explain that this doesn't prevent validation failing when other fields are present (which is what the documentation insinuates)
B) Actually make the validation fail when the other field is present (like what the documentation insinuates)
C) Update the documentation and add another validation rule that actually does this (yes, you can write custom validation rules but I still haven't got them running under Lumen in a Test Case)

I hope you guys agree - it's very confusing.

**Comment by sebdesign** [comment] 2016-01-18 21:40
I have submitted a PR #11927 which fixes this issue.

**Closed** 2016-06-01 09:10 UTC

**Comment by appelsiini** [comment] 2017-12-22 11:44
@sebdesign @GrahamCampbell @derakoola 

Was this issue actually fixed with the linked PR? We're still encountering a situation with the latest stable version, where the following setup succeeds even when none of the `required_without_all` fields are present.

```
    protected $rules = [
        'job_id'     => 'int|nullable|required_without_all:company_id,user_id|exists:job,id|aclJob',
        'company_id' => 'int|nullable|required_without_all:job_id,user_id|exists:company,id|aclCompany',
        'user_id'    => 'int|nullable|required_without_all:company_id,job_id|exists:user,id|aclUser',
    ];
```

**Comment by nmeri17** [comment] 2020-02-04 10:38
> @sebdesign @GrahamCampbell @derakoola
> 
> Was this issue actually fixed with the linked PR? We're still encountering a situation with the latest stable version, where the following setup succeeds even when none of the `required_without_all` fields are present.
> 
> ```
>     protected $rules = [
>         'job_id'     => 'int|nullable|required_without_all:company_id,user_id|exists:job,id|aclJob',
>         'company_id' => 'int|nullable|required_without_all:job_id,user_id|exists:company,id|aclCompany',
>         'user_id'    => 'int|nullable|required_without_all:company_id,job_id|exists:user,id|aclUser',
>     ];
> ```

Yours should be the intended behavior, so if it works, you have no issues. Your complaint is different from OP's issue
