### ISSUE TITLE
Application @ registerCoreContainerAliases

### ISSUE THREAD

**Issue by zhyswan** [laravel/framework#18596] opened 2017-03-31 12:13 UTC
- Laravel Version 5.4.16
- PHP Version:5.6
- Database Driver & Version:

### Description:
Parameter name is not reasonable

### Steps To Reproduce:

Illuminate\Foundation\Application   @ registerCoreContainerAliases

        /* old
        foreach ($aliases as $key => $aliases) {
            foreach ($aliases as $alias) {
                $this->alias($key, $alias);
            }
        }
        */
        //new
        foreach ($aliases as $alias => $abstracts) {
            foreach ($abstracts as $abstract) {
                $this->alias($alias, $abstract);
            }
        }

**Comment by Dylan-DPC** [comment] 2017-03-31 12:25
Reason why it is not reasonable?

**Comment by zhyswan** [comment] 2017-03-31 12:51
look at new

**Comment by themsaid** [comment] 2017-03-31 17:57
It's fine, closing since it's not a bug. Thanks anyways.

**Closed by themsaid** 2017-03-31 17:57 UTC

**Comment by zhyswan** [comment] 2017-04-01 04:54
Of course, it's not a bug, but it will make the reader misunderstand

**Comment by amosmos** [comment] 2017-05-29 07:21
I agree this is the most confusing part of laravel. What is the alias and what is the implementation and why are there multiple implementations per alias and how are they are registered and how are they resolved.

This function, and then the Container alias function are going back and forth between the alias and the classes, calling them in different names each time..

For example - when I ask for the router service class, which one do I get? Where is that one registered?

Thanks,
Amos
