### ISSUE TITLE
Laravel Multi Insert issue with quotes in value

### ISSUE THREAD

**Issue by mirzaawais** [laravel/framework#15626] opened 2016-09-27 07:01 UTC
- Laravel Version: 5.2.45
- PHP Version: 5.5.37
- Database Driver & Version: MySqli, Server type: MariaDB, Server version: 10.1.13-MariaDB - mariadb.org binary distribution, Protocol version: 10, Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 

### Description:
I need t insert a large set of records in database. I am getting data from a csv then I need to insert in database. I thought to do it using multi insert statement for good performance. So I did like following:

    foreach($data as $key => $value) {

    $insert[] = [
                'id' => $value->id, 'is_published' => $value->is_published,
                "first_name" => $value->first_name, "middle_name" => $value->middle_name, "last_name" => $value->last_name,
                "description" => $value->description,
                "created_at" => date("Y-m-d H:i:s",strtotime($value->created_at)),
                "updated_at" => date("Y-m-d H:i:s",strtotime($value->changed_at))
            ];
    }

    if(!empty($insert)){
        Model::insert($insert);
    }

By doing show I always get mysql server gone away error. I have debugged it by printing query and I observed that by doing so, Laravel doesn't take care of single quotes, double quotes in description column as it automatically does while doing $model::save(); way. The printed query version breaks if description column have single quote ' or double quote in it. 
But if I do some thing like:
   
     foreach($data as $key=>$value){
        $model = new Model();
        $model->id = $value->id;
        $model->description = $value->description;
        blah blah bla

       $model->save();
    }  

### Steps To Reproduce:

Prepare a multi insert statement with a column that contains single quotes and double quotes in the content. Try to insert with `Model::insert($dataArray)`.

**Comment by srmklive** [comment] 2016-09-27 07:15
You can always use `addslashes` to the values with single/double quotes before inserting them in the database.

**Comment by srmklive** [comment] 2016-09-27 07:15
How many records are you trying to insert when you get the MySQL has gone away error?

**Comment by mirzaawais** [comment] 2016-09-27 07:19
Around 4000

**Comment by srmklive** [comment] 2016-09-27 07:20
@mirzaawais  My suggestion would be that divide the data you get from CSV into chunks. Suppose you have 10k records in your CSV file, you can import them by dividing records into chunks of 50 and then multi-insert each chunk.

**Comment by mirzaawais** [comment] 2016-09-27 07:26
@srmklive I have always that option to do that thing. But I want to know why the default behavior of Laravel Multi Insert isn't taking care of quotes of itself?

**Comment by srmklive** [comment] 2016-09-27 07:32
@mirzaawais It is something i believe you need to handle on your own.

**Comment by mirzaawais** [comment] 2016-09-27 07:35
But Laravel should know this thing and clarify if its bug at their end or some thing I am not understanding.

**Comment by themsaid** [comment] 2016-09-27 07:47
Please share full stack trace of the exception you get.

**Comment by mirzaawais** [comment] 2016-09-27 08:05
QueryException in Connection.php line 729: PDOStatement::execute(): MySQL server has gone away (SQL: insert into 
in Connection.php line 729
at Connection->runQueryCallback('r', 'S') in Connection.php line 753
at Connection->tryAgainIfCausedByLostConnection('r', 'S') in Connection.php line 693
at Connection->run('r', 'S') in Connection.php line 458
at Connection->statement


ErrorException in Connection.php line 457: PDOStatement::execute(): MySQL server has gone away

    in Connection.php line 457
    at HandleExceptions->handleError('2', 'PDOStatement::execute(): MySQL server has gone away'

**Comment by themsaid** [comment] 2016-09-27 08:08
The stack trace doesn't mention anything related to quotes? Why do you think it's related to it?

**Comment by mirzaawais** [comment] 2016-09-27 08:10
Let me put that again

**Comment by srmklive** [comment] 2016-09-27 08:14
@mirzaawais Can you divide data into chunks and use `addslashes` on each item to see whether you see the same error again?

**Comment by themsaid** [comment] 2016-09-27 08:21
as a side note, I think using one query to insert large number isn't anywhere better than using several queries, I 'm not a DB expert at all I just remember I did some research before and decided to do 1 query per record inside a chunk closure.

**Comment by mirzaawais** [comment] 2016-09-27 08:22
@themsaid See the following trace for one section of query

  QueryException in Connection.php line 729: PDOStatement::execute(): MySQL server has gone away (SQL: insert into `artists` (`column1`, `column2`, `column3`, `description`, `column1`, `id`, `column5`, `column6`, `column7`, `column8`, `column9`, `column10`, `column11`) values (1234, 2008-10-29 06:49:18, , he has been considered one of the most influential artists. 

Ali's work is included in collections worldwide, some d'Art Museum, Paris, in some other museum, , 26, 1, 1, test, 2647, , Polish, 2013-03-07 20:46:46)


------------------------------------------------------------------------------------------
As you can see the description column can have `,`, `'`. I have just replaced some confidential data with some testing data but `commas and single quotes` are there.  But this works fine when I do in second part of my issue.

**Comment by themsaid** [comment] 2016-09-27 08:25
Need to see the exception :) Please try to regenerate in a test application if you don't want to share your data, preferably a 5.3 application since 5.2 is closed. We'll only consider fixing if it exists in 5.3 or 5.1

**Comment by themsaid** [comment] 2016-09-28 18:33
Ping @mirzaawais

**Comment by sisve** [comment] 2016-09-28 19:05
This looks like you've hit max_allowed_packet in mysql, not an issue with slashes. Can you execute the queries one-by-one to check 1) if smaller queries works, and if not, 2) which exact string data causes the failure?

> When a MySQL client or the mysqld server receives a packet bigger than max_allowed_packet bytes, it issues an ER_NET_PACKET_TOO_LARGE error and closes the connection. 
>
> --- snip ---
>
> The server's default max_allowed_packet value is 1MB. 

https://dev.mysql.com/doc/refman/5.5/en/packet-too-large.html

**Comment by themsaid** [comment] 2016-09-28 19:27
Closing since there's no indication that the issue is related to quotes, please check @sisve's comment and ping me if you ever found what your issue is.

**Closed by themsaid** 2016-09-28 19:27 UTC
Labels: needs more info

**Comment by alagiesellu** [comment] 2019-12-19 10:07
Illuminate\Database\QueryException {#257 ▼
  #sql: "insert into `courses` (`code`, `credit_hours`, `department_id`, `description`, `name`) values (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?) ▶"
  #bindings: array:19545 [▶]
  #message: """
    SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'code' at row 266 (SQL: insert into `courses` (`code`, `credit_hours`, `department_id`, `description`, `name`)  ▶
   CPS101, 3, 1, The problem is there is a comma, here which will break the description string, before having the final parameter name, Introduction to ICT ......
