### ISSUE TITLE
AlphaDash validate rule. 

### ISSUE THREAD

**Issue by ChiVincent** [laravel/framework#18485] opened 2017-03-25 09:23 UTC
- Laravel Version: 5.4.15
- PHP Version: 7.1.3
- Database Driver & Version: MySQL 5.7.16

### Description:
The alpha_dash validate rule which defined in Illuminate\Validation\Concerns\ValidatesAttributes@validateAlphaDash is using preg_match('/^[\pL\pM\pN_-]+$/u', $value) > 0

However, it will allow input when input is non-english, for example, typing "豆子" in Chinese, it is a valid content. 

I think it should remove "\pL" to allow any languages in regex rule.

**Comment by Dylan-DPC** [comment] 2017-03-25 11:10
@ChiVincent steps to reproduce? is there any other validation rule on that filed or just alphadash?

**Comment by ChiVincent** [comment] 2017-03-25 11:41
app/Http/Controllers/TestController: 

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Validator;

class TestController extends Controller
{
    public function getIndex(Request $request)
    {
        $validator = Validator::make($request->query(), [
            'name' => 'alpha_dash',
        ]);

        dd($validator->fails());
    }
}

```

router/web.php

```php
<?php

Route::get('/test', 'TestController@getIndex');
```

When I use `test.app/test?name=aaa`, it show `false`; 

When I use `test.app/test?name=aaa!`, it show `true`;

When I use `test.app/test?name=豆子`, it show `false`, however, the word "豆子" should not an alpha-numeric character, should it?

**Comment by themsaid** [comment] 2017-03-26 08:45
> however, the word "豆子" should not an alpha-numeric character

Why not?

**Comment by ntzm** [comment] 2017-03-26 16:46
"Alphanumeric" doesn't just refer to Latin letters https://en.wikipedia.org/wiki/Alphanumeric

**Comment by ChiVincent** [comment] 2017-03-27 05:45
> Alphanumeric is a combination of alphabetic and numeric characters, and is used to describe the **collection of Latin letters and Arabic digits** or a text constructed from this collection.
> -- [Alphanumeric Wikipedia](https://en.wikipedia.org/wiki/Alphanumeric)

Although the merriam-webster said that "alphanumeric" may often additionally refer to other symbols (such as punctuation marks and mathematical symbols), in POSIX/C there are either 36 (A-Z + 0-9, case insensitive) or 62 (A-Z + a-z + 0-9, case-sensitive)

What rule definition of validation in Laravel use? Is merriam-webster dictionary or POSIX/C?

**Comment by themsaid** [comment] 2017-03-30 18:57
@ChiVincent you can create your own validation rule or override the current to meet your expectations if you want, this looks like an opinionated issue and keeping the discussion may lead us to nowhere :)

Closing this issue but will try to keep track if others shared your concern and reported the same thing as an issue.

Thanks

**Closed by themsaid** 2017-03-30 18:57 UTC
Labels: more info?

**Comment by ijeffro** [comment] 2019-09-20 13:18
There seems to be a bug here...

Post with json ```""``` and validateAlphaDash() returns

**Comment by dong-sir** [comment] 2021-11-05 09:00
## alpha_dash
> The field under validation may have alpha-numeric characters, as well as dashes and underscores.

Try this rule instead of **alpha_dash**

```
[
    'username' => ['regex:/^[0-9a-zA-Z_\-]*$/']
]
```
