### ISSUE TITLE
Naming consistency: getForeignKey vs getForeignKeyName

### ISSUE THREAD

**Issue by jamierumbelow** [laravel/framework#18409] opened 2017-03-18 19:36 UTC
- Laravel Version: 5.4.15
- PHP Version: 7.0.8

### Description:

294c006288ee182eeddf3c6deb23a35032a9219d renamed `getForeignKey`, a public method on `HasOneOrMany` relations, to `getForeignKeyName`. `Eloquent\Model` still has a `getForeignKey` method. Should one or both of these methods be renamed for consistency?

**Comment by themsaid** [comment] 2017-03-24 08:19
That's a method on a Relation while the other is on a Model class, I don't think we should care about unifying names between two different classes, more over that would be a breaking change that'll require very caution upgrade steps.

Closing this since it's not a bug, however feel free to open that on laravel/internals as it's the place we keep suggestions and feature requests.

**Closed by themsaid** 2017-03-24 08:19 UTC
