### ISSUE TITLE
laravel new projectname.gr returns errors

### ISSUE THREAD

**Issue by merianos** [laravel/framework#21162] opened 2017-09-13 09:41 UTC
- Laravel Version: 1.4.1
- PHP Version: PHP 7.0.22-0ubuntu0.16.04.1
- Database Driver & Version: MySQL ( not remember version )

### Description:
I try to make installation of a new Laravel project, and unfortunately, I cannot.

Once I run the command `laravel new projectname.gr` I get the following errors at the end of the command output:

```
Generating optimized autoload files
You made a reference to a non-existent script @php -r "file_exists('.env') || copy('.env.example', '.env');"
You made a reference to a non-existent script @php artisan key:generate
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
You made a reference to a non-existent script @php artisan package:discover
```
Then when I go in the project folder, and I run the command `php artisan serve` in the browser I get the following error:

`Whoops, looks like something went wrong`

**Note:** _I already did a global remove of the laravel, and I did again a new global installation of the laravel._

### Steps To Reproduce:
No steps to describe

**Comment by merianos** [comment] 2017-09-13 09:46
What I did, and now the Laravel run's was to manually rename the `.env.example` to `.env` and then manually I run the command `php artisan key:generate`.

But yet, this it seems like being a problem. I do not close the ticket, just to let the dev review it. If you think it is not an issue that you should check, then feel free to close :).

**Comment by Dylan-DPC** [comment] 2017-09-13 11:02
I just did it yesterday and it works fine. Ensure that you have updated `laravel/installer` and `composer`. You can close this as it is not a bug

**Comment by themsaid** [comment] 2017-09-13 12:08
`composer selfupdate`

`composer global update "laravel/installer"`

**Closed by themsaid** 2017-09-13 12:08 UTC
