### ISSUE TITLE
Null compatibility broken

### ISSUE THREAD

**Issue by jc-skurman** [laravel/framework#43705] opened 2022-08-15 10:11 UTC
- Laravel Version: 9.24.0
- PHP Version: 8.1.0
- Database Driver & Version:
MySql 8
Description:
When we use a cast of type 'object', 'collection' and we have the original value null, we get an error when trying to decode json.
This change appeared in the [PR](https://github.com/laravel/framework/pull/42793/files#diff-59d24f1a8f0dd1e51ee7dffc8778133711634e928ecef4a91b63fc3851cb1579) and is still relevant even for version 9.
PR
We get the warning

> PHP Deprecated: json_decode(): Passing null to parameter https://github.com/laravel/framework/issues/1 ($json) of type string is deprecated

**Comment by driesvints** [comment] 2022-08-15 10:16
@tpetry since you originally created https://github.com/laravel/framework/issues/37961 which sparked https://github.com/laravel/framework/pull/41337: do you know of a way to do a fix so both issues are resolved?

Also want to ping you @JBtje since you're the author of https://github.com/laravel/framework/pull/41337.

@jc-skurman this change has been in the framework now for several months. Did you only update Laravel now recently?

**Comment by jc-skurman** [comment] 2022-08-15 10:23
I just now caught this bug on the old version and after indicating that you no longer support it, I checked it on the latest version

**Comment by MasterRO94** [comment] 2022-08-15 10:30
@driesvints 

I've checked issues can be reproduced if you have `null` original value for `object` or/and `collection` cast. This can be fixed replacing `fromJson` call to `castAttribute`
 

 ```php
 } elseif ($this->hasCast($key, ['object', 'collection'])) {
            return $this->fromJson($attribute) ===
                $this->fromJson($original);
 ```
change to 
 ```php
 } elseif ($this->hasCast($key, ['object', 'collection'])) {
            return $this->castAttribute($key, $attribute) ===
                $this->castAttribute($key, $original);             
 ```

**Comment by tpetry** [comment] 2022-08-15 10:31
I replaced the dirty check with my custom implementation because in my projects I found a lot more edge cases, e.g. different order of object keys.

But based on the implementation of the PR the null value has to be handled too. `null != json, null = null`.

**Comment by JBtje** [comment] 2022-08-15 10:51
First and foremost, `null` is not valid `json`, so the warning is correct. If you seed your empty JSON fields with a valid JSON value (e.g. empty string), the warning is solved.
I have come across this warning a few times, just to realize i did something wrong (i.e. not seeding JSON field properly).

But if you think `null` should be a valid value for a JSON field, then this could easily be solved:
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1203
```
        return json_decode($value ?? '', ! $asObject);
```
solves the warning.

**Comment by driesvints** [comment] 2022-08-15 10:54
@JBtje that's not true actually. `null` is definitely valid JSON: https://stackoverflow.com/questions/8526995/is-null-valid-json-4-bytes-nothing-else

**Comment by driesvints** [comment] 2022-08-15 10:54
Would appreciate a PR to fix this.

**Comment by driesvints** [comment] 2022-08-15 13:58
We merged a fix for this. Thanks

**Closed by driesvints** 2022-08-15 13:58 UTC
Labels: bug
