### ISSUE TITLE
No description for the "migrate" command in the output of "php artisan"

### ISSUE THREAD

**Issue by teo1978** [laravel/framework#25265] opened 2018-08-19 16:06 UTC
The output of `php artisan` looks like this:
![image](https://user-images.githubusercontent.com/542107/44310616-c4d00d00-a3d9-11e8-97d0-c765063c283e.png)

(...)

![image](https://user-images.githubusercontent.com/542107/44310632-df09eb00-a3d9-11e8-9423-4e125f0b68d1.png)

First of all, there's no way to tell, from that, that the commands `app` or `make` don't exist (they are common prefixes to commands such as `app:name`, `make:xxxx`, ...) while a command called `migrate` (not followed by `:anything`) does exist.

Actually that's a bad design of command names in itself. The `migrate` command should be called `migrate:something`, e.g. `migrate:migrate` or `migrate:update` or whatever.

But since it is not, there should be a **DESCRIPTION** next to it in the output of `php artisan`, such as "Perform all pending migrations" or something.

I was looking for that very command, looking at the list of commands, and couldn't find it, because I expected it to be called `migrate:something`, none of the existing `migrate:xxxx` commands was what I was looking for, and since there is nothing next to the header `migrate`, I thought `migrate:` was just a prefix for a group of commands just like `app` or `make`, and not a command itself.

**Comment by devcircus** [comment] 2018-08-19 21:57
But "migrate" is in the list of commands while the others like "app" are not:
![image](https://user-images.githubusercontent.com/18542852/44313591-b4676480-a3d0-11e8-8bd8-3a505380db72.png)

The headers are just namespaces for more commands. All actual commands are listed as they should be. It's a common convention across many console apps to setup commands and namespaces like this.

**Comment by teo1978** [comment] 2018-08-19 22:16
Oh, I see, I missed that, my bad.

However, 
> It's a common convention across many console apps to setup commands and namespaces like this.

Is it also common, for console apps that follow this convention, to have both a command and a namespace with the same name? It seems to me a pretty bad practicce, and "migrate" in this case is the only one.

It feels natural to look for all the migrate-related commands under the "migrate:" namespace and it's easy to miss that there's also a non-namespaced command with the same name as the namespace.

Since it exists now (and has for years, I suppose) and it is unthinkable to rename either the command or the namespace, I think it would be a good idea to create an alias for it within the `migrate` namespace, e.g. `migrate:migrate`.

**Comment by mfn** [comment] 2018-08-20 06:07
This is not a bug. Please close it and move it to https://github.com/laravel/ideas if you want discuss this.

**Closed** 2018-09-18 01:12 UTC
