### ISSUE TITLE
Mocks are not properly resolved

### ISSUE THREAD

**Issue by abellion** [laravel/framework#25372] opened 2018-08-29 10:47 UTC
- Laravel Version: 5.6
- PHP Version: 7.2

### Description:

When testing, some mocks are not properly resolved. This is because the providers are booted before mocks get bound to the container. 

If one of the provider uses a singleton, it gets resolved and is saved inside the container. If the singleton depends, in its constructor, of a service that should be a mock, it doesn't receive the mock (because it's not created yet) and the singleton stays as it in the container.

It means that when testing (using the `WithoutEvents` trait for example) if a test uses the singleton the trait has no effect because the singleton doesn't have the Mockery mock. 

### Steps To Reproduce:

- 1 - Create a class requesting the `Illuminate\Contracts\Events\Dispatcher` in its constructor and define it as a singleton.

- 2 - Inside a service provider's `boot` method, request the singleton.

- 3 - In one of a `WithoutEvents` test, run some test against the singleton and you'll notice events are still dispatched.

It also happens when using events subscribers because they are resolved in order to retrieve their subscribed events. So if one of them use the singleton as a dependency, the issue appears too.

**Comment by laurencei** [comment] 2018-10-03 07:15
Hi,

Can you please give some exact steps/code to reproduce this on a fresh 5.7 install?

**Comment by driesvints** [comment] 2018-11-15 15:15
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Closed by driesvints** 2018-11-15 15:15 UTC

**Comment by noglitchyo** [comment] 2022-03-15 14:37
Still experiencing this issue with Laravel 8. 

Booting of providers is executed before the mocks can be bind to the container.

E.g. using a EventServiceProvider which contains the following:

```php
class EventServiceProvider extends \Illuminate\Foundation\Support\Providers\EventServiceProvider
{
    protected $subscribe = [
        MyEventSubscriber::class,
    ];
}
```
and a subscriber declared as follow:

```php
class MyEventSubscriber
{
    private MyDependencyClass $dependency;

    public function __construct(
      MyDependencyClass $dependency
    ) {
        $this->dependency = $dependency;
    }

    public function subscribe(Dispatcher $dispatcher): void
    {
        $dispatcher->listen(SomeEvent::class, [$this, 'onEvent']);
    }
}
```
In my tests, I need to mock `MyDependencyClass` but this class is resolved during boot which does not allow me to replace the dependency with the mocked instance.
