### ISSUE TITLE
File validation returns no error on PHP 7

### ISSUE THREAD

**Issue by lino10** [laravel/framework#12335] opened 2016-02-17 05:00 UTC
Because the issue seems to be abandoned after it's closed, I decided to create a new one.
https://github.com/laravel/framework/issues/12118

After doing several testing, I conclude that the problem appears in PHP 7, it's working fine on PHP 5.

Please use Homestead for testing.

**Comment by GrahamCampbell** [comment] 2016-02-17 09:51
Could you add a test case that fails please?

**Comment by stevebauman** [comment] 2016-02-17 20:35
I experience the same issue running php 7.Will debug and update shortly.

**Comment by stevebauman** [comment] 2016-02-17 21:07
## More Information

What's even more strange in PHP 7, is when I submit the form while dumping the errors in PHP 5.6, and switch PHP versions on the fly to PHP 7, and re-submit the form, I receive the correct error bag instance.

**Comment by lino10** [comment] 2016-02-18 04:21
@stevebauman 
Thank you for providing through test

@GrahamCampbell 
I already gave the info on the other issue and stevebauman above also already gave his test but I'll just paste my comment from the other issue here.

```
I just tested using the fresh 5.2.14, there's still no error messages. So why is this issue closed?

Here's the app and resources folder, you just need to replace them to test. Just empty the name field and upload image other than gif.
http://s000.tinyupload.com/index.php?file_id=71431977644503943832

Tested using xampp and homestead
```

Temporary fix:
Replace the withInput method in the Illuminate\Http\RedirectResponse
```
    public function withInput(array $input = null)
    {
        $input = $input ?: $this->request->input();

        $this->session->flashInput($data = array_filter($input, $callback = function (&$value) use (&$callback) {
            if (is_array($value)) {
                $value = array_filter($value, $callback);

                if (empty($value))
                return false;
            }

            return ! $value instanceof UploadedFile;
        }));

        return $this;
    }
```

I'm running Windows 10 64 bit

**Comment by GrahamCampbell** [comment] 2016-02-18 08:52
What about 5.2.19?

**Comment by lino10** [comment] 2016-02-18 10:04
I just tried it, still not working. The temporary fix also need to be modified, before it returned single empty object, now it returns 3 null object. (array 2 and 4 are filled with file)
```
array:3 [▼
  0 => null
  1 => null
  3 => null
]
```

The new temporary fix
```
    public function withInput(array $input = null)
    {
        $input = $input ?: $this->request->input();

        $this->session->flashInput($data = array_filter($input, $callback = function (&$value) use (&$callback) {
            if (is_array($value)) {
                $value = array_filter($value, $callback);
				return false;
            }

            return ! $value instanceof SymfonyUploadedFile;
        }));

        return $this;
    }
```

**Comment by renanpro03** [comment] 2016-03-31 22:24
It seems not fixed yet.
I'm using L 5.2.24 and got this problem with Homestead and PHP 7

**Comment by cloudratha** [comment] 2016-04-24 10:21
I did a fresh update on 5.2.*.
After inspecting the RouteServiceProvider I saw that the web middleware group is included by default.
Removing the web middleware from my own routes resolved this issue. Seems like it gets actioned twice which causes the message bags to freak out.

**Comment by GrahamCampbell** [comment] 2016-04-24 11:05
Closing since this is a user error caused by adding middlewares more than once.

**Comment by xpert13** [comment] 2016-04-24 11:10
I didn't add any middlewares except "auth" to my routes and have the same issue. Temporary solution from @lino10 helps me, but I don't want to edit framework files after each update.

**Comment by cloudratha** [comment] 2016-04-24 16:17
I used the Auth scaffolding. It injected Route:auth(); to my routes, which sat outside of my route group. I noticed the errors were showing on the Auth pages, but not my own. That's when I saw the RouteServiceProvider included web by default. Using 5.2.29 I don't get any errors including auth middleware on homestead with php7.

**Closed** 2016-06-17 16:18 UTC
Labels: bug

**Comment by lino10** [comment] 2016-06-20 03:40
@GrahamCampbell is this issue already fixed?

**Comment by xpert13** [comment] 2016-07-20 08:06
@lino10 it seems to be fixed in 5.2.40

**Comment by lino10** [comment] 2016-07-23 03:25
@xpert13 Have you tried it?
From what I see it they're still debating whether it's bug or not..

**Comment by xpert13** [comment] 2016-07-25 06:35
@lino10 Yes, I did. It works fine for me now.

**Comment by lino10** [comment] 2016-07-28 04:51
@xpert13 Hi, I just tested it. It works now. Thanks for notifying me! :)

@3alampro Are you the one providing the patch? Thanks for providing the patch :)

**Comment by 3alampro** [comment] 2016-07-28 09:47
@lino10 yes i did provide working patch but @taylorotwell provided a better and clean solution for the bug 10 days ago here
https://github.com/laravel/framework/commit/85249beed1e4512d71f7ae52474b9a59a80381d2

**Comment by robjbrain** [comment] 2016-11-07 14:06
Hi this is still an issue on the 5.1 branch.

I've tested it and the @taylorotwell fix from https://github.com/laravel/framework/commit/85249beed1e4512d71f7ae52474b9a59a80381d2 works fine on the 5.1 branch.

Is it possible to update the RedirectResponse class with those changes in the 5.1 branch as well?
