### ISSUE TITLE
Implicitly model binding should be Model or null?

### ISSUE THREAD

**Issue by mark86092** [laravel/framework#12959] opened 2016-04-01 05:11 UTC
In the [laravel doc](https://laravel.com/docs/5.2/routing#route-model-binding), a route
```
Route::get('users/{user}', function (App\User $user) { ... });
with request of '/users/1'
```
will resolve the type-hinted Eloquent models.

But what if 
```
Route::get('users/{user?}', function (App\User $user = null) { ... });
with request of '/users'
```
The $user in function should be **null** or **instance of App\User** ?

## Detail

While I was working on #12888, I added test for implicit model binding. Current behavior of resolver will make 
```
Route::get('users/{user?}', function (App\User $user = null) {
// $user is an instance of App\User even request of /users
});
```

In #12630,
```
Route::get('/calendar/{user}/{department?}/{year?}/{month?}/{team?}', function show(Request $request, User $user, Department $department = null, $year = null, $month = null, Team $team = null) {
// $year is an instance of App\Team, but it should be null
// $team here is null
// with request /calendar/1/2
}
```

A default value in function argument suggests if no argument passed, the parameter will be the default value, for example, `$month` is **null**

The problem is `$team` should be **null** or type-hinted `Team` instance

Ref: if you are interest in what cases I test, have a look here mark86092/laravel-framework#5

**Comment by GrahamCampbell** [comment] 2016-04-01 10:00
I'd say the optional one should be a user instance to be consistent with method injection,

**Comment by GrahamCampbell** [comment] 2016-04-03 13:22
Looks like a duplicate of that other issue.

**Closed** 2016-04-03 13:22 UTC
