### ISSUE TITLE
5.1.* Dirty or not Dirty, save method always returns true

### ISSUE THREAD

**Issue by jrean** [laravel/framework#9697] opened 2015-07-21 08:26 UTC
Hi,

I open this issue without being 100% sure of my tests but when I update a model the `->save()` method always returns `true`, model dirty or not dirty.

In `Illuminate\Database\Eloquent\Model`

`public function save(array $options = [])`

My model exists so we perform the update.

```
...
if ($this->exists) {
    $saved = $this->performUpdate($query, $options);
}
```

But my model is not dirty, so it will always return `true`.

```
protected function performUpdate(Builder $query, array $options = [])
    {
        $dirty = $this->getDirty();

        if (count($dirty) > 0) {
            // If the updating event returns false, we will cancel the update operation so
            // developers can hook Validation systems into their models and cancel this
            // operation if the model does not pass validation. Otherwise, we update.
            if ($this->fireModelEvent('updating') === false) {
                return false;
            }

            // First we need to create a fresh query instance and touch the creation and
            // update timestamp on the model which are maintained by us for developer
            // convenience. Then we will just continue saving the model instances.
            if ($this->timestamps && Arr::get($options, 'timestamps', true)) {
                $this->updateTimestamps();
            }

            // Once we have run the update operation, we will fire the "updated" event for
            // this model instance. This will allow developers to hook into these after
            // models are updated, giving them a chance to do any special processing.
            $dirty = $this->getDirty();

            if (count($dirty) > 0) {
                $this->setKeysForSaveQuery($query)->update($dirty);

                $this->fireModelEvent('updated', false);
            }
        }

        return true;
    }
```

Then:

```
...
if ($saved) {
    $this->finishSave($options);
}

return $saved;
```

With a not dirty model the `save()` method always returns `true` and so with a dirty model it also returns `true`.

Am I totally wrong?

**Comment by lukasgeiter** [comment] 2015-07-21 08:53
That's correct and the expected behavior. The `save` method only returns `false` if the operation has been cancelled by an event.

**Comment by jrean** [comment] 2015-07-21 09:07
@lukasgeiter thank you.

**Comment by lukasgeiter** [comment] 2015-07-21 09:49
Without knowing any more details I'd suggest you check with `isDirty()` before actually calling `save()`. You could also listen to certain model events but that would just make things more complicated.

**Comment by GrahamCampbell** [comment] 2015-07-21 10:34
Feel free to continue discussing here, or ask on the forums. I'm just closing this is we know it's not a bug.

**Closed** 2015-07-21 10:34 UTC

**Comment by jrean** [comment] 2015-07-21 10:49
Yeah sorry about that @GrahamCampbell :)
