### ISSUE TITLE
Api Resource - Eager loading not found

### ISSUE THREAD

**Issue by scortes1989** [laravel/framework#21739] opened 2017-10-19 02:30 UTC
- Laravel Version: 5.5.17
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:

To generate a api resource the eager loading not found and return null, only when modify the resource

### Steps To Reproduce:

-Airport Model

```
public function country()
 {
        return $this->belongsTo(Country::class);
}
```

-Airport Resource

//not found
```
public function toArray($request)
{
      return [
            'id' => $this->id,
           'country_id' => new CountryResource($this->whenLoaded('country')),
      ];
} 
```

//found
```
public function toArray($request)
    {
        return parent::toArray($request);
    }

```
-Controller

```
public function index()
    {
        $airports = Airport::with(['country', 'city'])->get();

        return AirportResource::collection($airports);
    }
```

**Comment by pactode** [comment] 2017-10-19 06:42
I'm not able to reproduce your issue. It's working fine for me.

**Comment by themsaid** [comment] 2017-10-19 16:08
Works fine for me as well, closing since nobody is able to replicate, please seek help on the forums.

**Closed by themsaid** 2017-10-19 16:08 UTC
