### ISSUE TITLE
Missing spaces in subject email Mailgun driver

### ISSUE THREAD

**Issue by absemetov** [laravel/framework#15791] opened 2016-10-06 19:28 UTC
- Laravel Version: 5.2.38
- PHP Version: 5.5.9

Sometimes I receive emails without the first one or two spaces.
Lang russian.

Example:
ИндыкИгорь (без регистрации) ...
ИндыкИгорь(без регистрации) ....

**Comment by themsaid** [comment] 2016-10-12 08:29
What emails? Can you please explain how is this a bug in the framework?

**Comment by absemetov** [comment] 2016-10-12 09:03
This error does not always happen, I do not understand where to look for the cause?

````
Mail::send('shop.emails.new_order', compact('order'), function ($message) use ($user, $order) {
  if($user) {
   $message->to($user->email, $user->firstname . ' ' . $user->lastname)->subject($order->name_user . ', ваш заказ #' . $order->id . ' (' . $order->summ . ' руб.) на сайте rzk.com.ru принят.');
  $message->bcc('nadir@absemetov.org.ua', $name = null);
} else {
  $message->to('nadir@absemetov.org.ua', 'Nadir Absemetov')->subject($order->name_user . ' (guest), ваш заказ #' . $order->id . ' (' . $order->summ . ' руб.) на сайте rzk.com.ru принят.');
}

$message->bcc('nadir.absemetov@ya.ru', $name = null);	            
});
````

**Comment by themsaid** [comment] 2016-10-12 19:45
I'm sorry but I have no idea what the issue is :)

**Comment by absemetov** [comment] 2016-10-12 19:55
Maybe curl copmress single spaces?

**Comment by themsaid** [comment] 2016-10-12 19:57
Can you please describe the issue in more detail? Also can you share steps to reproduce?

**Comment by absemetov** [comment] 2016-10-12 20:04
I have online shop, and send email for my clients.
Correct subject (99% emails)
````
Mohamed Said (without registration)
````
Dont correct
````
MohamedSaid (without registration)
````
````
MohamedSaid(without registration)
````

**Comment by GrahamCampbell** [comment] 2016-10-12 20:08
Doesn't look like a bug with us, rather with mailgun if it's intermittent?

**Comment by absemetov** [comment] 2016-10-12 20:11
Mailgun support:

We don't modify the spaces in the headers. Sounds like the spaces are being stripped prior to submission. Here's a curl request to our API that can be used to test the behavior :
````
curl -s --user api:key-API_key_here https://api.mailgun.net/v2/mail.rzk.com.ua/messages -F from='Sample Email <me@mail.rzk.com.ua>' -F to=mgbox01@gmail.com -F subject='Test Message' -F text='Testing some Mailgun awesomness!'
````

**Comment by GrahamCampbell** [comment] 2016-10-12 20:24
Well, neither does Laravel?

**Comment by GrahamCampbell** [comment] 2016-10-12 20:25
Closing this since I can't replicate this. No way it can be related to the framework.

**Closed** 2016-10-12 20:25 UTC

**Comment by sortafreel** [comment] 2018-07-06 00:19
Still has this problem on 3+ running services. Tried to replace with &#x20; and so on, but no use.

**Comment by vishaltarkar** [comment] 2019-01-23 10:37
I am facing similar issue.
Can you please open this again and look into it?

My Mail Subject is "Brand1 #4 New ticket comment"
However, When I receive an email it remove a space before #. Something like this "Brand1#4 New ticket comment"

If I put any other special character like @, it work fine. Any Idea?
