### ISSUE TITLE
Pagination redirect in apache

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#9788] opened 2015-07-30 11:58 UTC
This has been brought up before but not sure what happened.

By default Laravel will redirect all urls with a trailing `/`. All pagination links are rendered with a trailing slash `/?page=x` which means EVERY pagination link is 301ing in apache. Seems illogical that if Laravel does not support trailing slashes then why is it outputting trailing slashes for pagination links?

@taylorotwell is there any design decision why pagination links was changed in 5.0 to be a trailing slash? In 4.2 and below it was never a trailing slash so didn't have this issue....

**Comment by GrahamCampbell** [comment] 2015-08-07 16:32
Duplicate of https://github.com/laravel/framework/issues/9288.

**Closed by GrahamCampbell** 2015-08-07 16:32 UTC
