### ISSUE TITLE
Method deleteFileAfterSend() does not work while testing.

### ISSUE THREAD

**Issue by szymekjanaczek** [laravel/framework#36286] opened 2021-02-16 17:01 UTC
- Laravel Version: 8.24.0
- PHP Version: 7.4.15
- Database Driver & Version: 10.5.8 MariaDB Arch Linux

### Description:
This code `return response()->download($path)->deleteFileAfterSend();` works properly while using as the app through the API calls (returns file to download and then **delete it from server**), but when I want to run tests, the file is not deleted.
Additionally, when I've tried to found out more information about this method in Laravel Docs / Reference, I discovered that it's "not exists" - the last footprint ends at Laravel 6.

### Steps To Reproduce:
1. Create Controller with a method, which return looks like this: `return response()->download($path)->deleteFileAfterSend();`, where `$path` variable is a path to existing file.
2. Test it manually by running the API call, which will access ours before the created method. If a file was returned and then deleted from the server, proceed.
3. Now write the test class and method - simply create it via `php artisan make:test CustomNameTest`.
4. `$this->get($url_to_our_action)->assertOk();` - teoretically after this operation the file should be deleted. But it's not happens.

**Comment by Magiczne** [comment] 2021-02-16 17:06
Same with Laravel 8.27 / PHP 7.3.19

**Comment by taylorotwell** [comment] 2021-02-16 19:06
`deleteFileAfterSend` is a method that exists in Symfony.

**Comment by taylorotwell** [comment] 2021-02-16 19:07
I see that Symfony calls it within the `sendContent` method of the `BinaryFileResponse` (a Symfony class). It may be that `sendContent` is not called during testing? I'm not sure.

**Comment by jelib3an** [comment] 2021-02-24 17:14
`Illuminate\Testing\TestResponse` has a `streamedContent()` method that let's you do this in your unit tests
```php
$response = $this->get($url);
$contents = $response->streamedContent();
// assert some things about the contents
$response->assertStatus(200);
```

Not sure if this is the right approach, but if we treat `BinaryFileResponse` the same way, then calling `streamedContent()` would trigger `sendContent()` which would also handle any deletion of files after send. Just have to add a check so it doesn't error for `BinaryFileResponse`.

```diff
--- a/src/Illuminate/Testing/TestResponse.php
+++ b/src/Illuminate/Testing/TestResponse.php
@@ -15,6 +15,7 @@
 use Illuminate\Testing\Assert as PHPUnit;
 use Illuminate\Testing\Constraints\SeeInOrder;
 use LogicException;
+use Symfony\Component\HttpFoundation\BinaryFileResponse;
 use Symfony\Component\HttpFoundation\StreamedResponse;
 
 /**
@@ -1136,7 +1137,7 @@ public function streamedContent()
             return $this->streamedContent;
         }
 
-        if (! $this->baseResponse instanceof StreamedResponse) {
+        if (! ($this->baseResponse instanceof StreamedResponse || $this->baseResponse instanceof BinaryFileResponse)) {
             PHPUnit::fail('The response is not a streamed response.');
         }
```

**Comment by Magiczne** [comment] 2021-02-27 10:34
Your patch and using `$response->streamedContent()` solves the problem. But since it calls `sendContent()` the possible solution for the problem is:

```php
$response = $this->get('url/to/file/download');

// Here file is not deleted yet

$reponse->sendContent();

// Here file is deleted, we can perform assertions.
```

**Comment by taylorotwell** [comment] 2021-03-08 18:37
Closing this since it seems there are some work arounds. If any behavior on our end needs to be tweaked feel free to send in a PR.

**Closed by taylorotwell** 2021-03-08 18:37 UTC
Labels: needs more info

**Comment by jpswade** [comment] 2021-12-02 11:46
I had to encapsulate the call to sendContent(), which does delete the file, but also echo's the binary output.

```
        ob_start();
        $response->sendContent();
        ob_end_clean();
```

It would be good if this was part of the `$response->assertDownload();` method so this wasn't necessary.
