### ISSUE TITLE
Allow per-project installations for Homestead 2

### ISSUE THREAD

**Issue by joshuajabbour** [laravel/framework#6531] opened 2014-11-30 02:19 UTC
With the rewrite of Homestead v2, it is now considerably more difficult (if not impossible) to share development environment code on a project. One of the key benefits of Vagrant is committing the `Vagrantfile` to a repository and thereby having all developers working from the same environment. (Isn't that the whole point of Vagrant?) But with Homestead 2, all your config lives in your own personal `~/.homestead` directory, and is non-shareable. 

I was never really a fan of the instructions for Homestead 1 which advocated using a single, central clone of the homestead repository. (Am I really the only one who uses separate homestead boxes per project? Do other people prefer not to segregate environments? That's like developing on our own little shared hosting boxes, allowing different project code and installation requirements to co-mingle.) But at least with the original Homestead it was possible to put the homestead files inside your project's repo (I used `subtree add`, since I'd customize the provision scripts.) With Homestead 2 and `after.sh`, the ability to customize the environment is getting better (and somewhat more reproducible), but taking a huge step backwards in shareability.

While bundling homestead commands as a composer project is great, further centralizing config seems to be taking Homestead in a wrong direction...

**Comment by EwanValentine** [comment] 2015-01-02 17:58
+1 Agree with this. It's a nice idea, but it would be great to have the option to use Homestead as a standalone vagrant project as well.

**Comment by brpaz** [comment] 2015-01-11 10:42
I agree with this as well. It would be great to have a .homestead.yml file per project. It could work like Vagrant does. ```homestead init``` would create a homestead.yml in your project root folder (similar to  ```vagrant init ```) instead of using a global file.

For now, I am using only the homestead box directly with vagrant.

**Comment by ozanhazer** [comment] 2015-02-09 16:18
+1

**Comment by joearcher** [comment] 2015-02-16 16:52
Project specific Homestead environments are absolutely critical for our workflow. We will quite simply not be able to utilise Homestead as it stands at present.

**Comment by b3nl** [comment] 2015-02-27 15:21
+1

**Comment by ThatTomPerson** [comment] 2015-02-28 03:19
So question 
if you want homestead to work like vagrant why don't you just use vagrant?

**Comment by ThatTomPerson** [comment] 2015-02-28 03:43
The last commit on https://github.com/zoontek/purestead was today so it is being worked on and it uses the same Box that Homestead does so it is the exact same software stack

**Comment by b3nl** [comment] 2015-03-02 14:38
i think, the discussion "if you want homestead to work like vagrant, than use vagrant" leads to nowhere. An example?
Laravel (git)ignores the vendor dir per default but the default vm for laravel gives us no direct automatism to install the vendor dir?! Every team - my team, team of @joearcher, etc. - needs to implement provisioning additionally for getting even the minimum of loading the vendor dir.

**Comment by joearcher** [comment] 2015-03-02 14:45
@ThatTomPerson I find your "I work this way, and so should you, or go elsewhere" attitude to this issue unconstructive and opinionated. "Use another product" is not an appropriate response to this issue. 
Because the product fits your needs does not make it appropriate for everyone, especially when the issue is with functionality which has been removed.

**Comment by ozanhazer** [comment] 2015-03-02 15:22
I've experimented lot's of frameworks since ruby on rails first came out, maybe 10 years ago from today, and what I like and amazed about laravel is there's a decent answer to virtually any common problem (which is the definition of a framework), without sacrificing flexibility and with great documentation.

Homestead is a good utility for building up the dev. environment but it sacrifices some flexibility this time and I believe this is a very common case.

Yes you can always set your own vagrant box or use an alternative but that's what we do with zend framework or symfony or any other popular framework, isn't it?

**Comment by franzliedke** [comment] 2015-03-02 17:28
I agree it's a missing feature.

Vagrant supports multiple VMs per environment. Maybe this can somehow be used to allow for per-project VMs?

**Comment by ThatTomPerson** [comment] 2015-03-03 02:29
I'm not saying you cant use homestead
I'm working in a group of 3, so homestead wouldn't work for us because if one person makes a change  like installs Mongo how do you handle that??

homestead as it is, does not handle stuff like this,
so I made some changes to homestead and just copy them into the root of my project
you can see my changes at https://github.com/ThatTomPerson/homestead

this is more customisable and all configuration is now in the repo
if you want mongodb on your vm just write a create-mongo.sh in the scripts and change homestead.rb to run it

I have no idea who you would get homestead to do this

**Comment by b3nl** [comment] 2015-03-03 08:18
@ThatTomPerson You got the provisioning script in your project, which everyone uses? I don't understand, how you point invalidates provisioning per project for homestead?

**Comment by ThatTomPerson** [comment] 2015-03-03 23:24
I think the best you could get homestead to do is copy the files into you project for you
and maybe be a wrapper around vagrant to tell you when you may need to provision again

but that is a big change from how homestead works at the moment
and I would not be opposed to homestead being able to do that but it should be to do this as well as have it's original functionality

`homestead init --local`

to copy files to you current directory

then if homestead see that there is a `Homestead.yaml` or `Vagrantfile` it can go into `local mode` where is just runs vagrant in the current directory

 but if it doesn't find one of those files it runs it in the global version

that would be cool

but now this is just how vagrant works but with some sugar

**Comment by micflan** [comment] 2015-03-05 12:53
"just how vagrant works but with some sugar" sounds perfectly fine to me. Homestead was (prior to version 2) essentially a Laravel-ready Vagrant configuration with some helpful wrappers around configuration and cli commands. There's nothing wrong with that; it was very useful.

I've been happily using [Purestead](https://github.com/zoontek/purestead) on recent projects anyway, so this isn't a massive issue for me (i.e. alternatives _are_ available). I'm just not aware of a good argument for this change to a "global Homestead" in version 2.

It's a lot of extra steps now to get my team on the same environment, and I don't see what's been gained.

**Comment by RomainLanz** [comment] 2015-03-05 16:14
You can also still use Homestead 1.

**Comment by ThatTomPerson** [comment] 2015-03-05 23:22
@micflan I will have to find a source for this but the goal with Homestead was to have a way to quickly set up a new laravel site in vagrant and making a new box in vagrant is slow so put them all in the same box

I think homestead is good for personal projects and tests
eg trying out a new package or trying out a new concept

I think @taylorotwell mentioned this in the lavavel podcast ep 19 but I could be wrong
I will listen to it again and find out after work

**Comment by ThatTomPerson** [comment] 2015-03-12 09:55
If you want to have a look at how i think local installs of homestead could work have a look at
laravel/framework#173
just an idea
discuss

**Comment by dbpolito** [comment] 2015-03-13 04:20
I have been using a customized version of homestead after version 2 because of this issue, today this issue came to my attemption and made me figure other people shares this same opinion, so i open sourced my customized version:

https://github.com/dbpolito/firestead

This is basically homestead, no customizations at all, only simplified and per project based.

**Comment by theflyingwhale** [comment] 2015-03-27 19:58
I think this global homestead is a step backwards, it makes it really hard to commit the dev environment to source control and for other devs to simply vagrant up and get cracking. Plus the provisioning script is running for every homestead up? Each project has it's own provisioning requirements....

**Comment by hassankhan** [comment] 2015-04-05 23:59
Have to agree here, it seems a bit backwards. If we could add something similar to what @ThatTomPerson said above (check project folder first, then user folder) then that would be awesome.

**Comment by ThatTomPerson** [comment] 2015-04-06 06:53
I tried to talk to Taylor about it and he said that he though Homestead was ok as it is
so if we want a feature like this we will have to fork 
but there is already projects around that do this eg purestead and firestead

I also don't think another homestead fork is a good idea

![image](https://cloud.githubusercontent.com/assets/1112472/7001283/0df9aa6c-dc79-11e4-9e9e-ce9eec23c517.png)

**Comment by hassankhan** [comment] 2015-04-06 14:48
Sucks to hear that :disappointed:

**Comment by b3nl** [comment] 2015-04-06 16:04
so, no original homestead in bigger teams with multiple homestead projects for me ... -1

**Comment by dbpolito** [comment] 2015-04-06 16:12
I feel bad about this too, but there is no way to please everyone... I don't know if the majority liked this new way, but seems to, as it's simpler... That's why forks exists, someone doesn't like the direction of the main project and fork and customize.

We have two good alternatives, as @ThatTomPerson pointed, purestead and firestead, i haven't tested purestead but seems pretty good to me.

**Comment by rossedman** [comment] 2015-04-06 17:15
:+1: I agree with many of the opinions stated in this thread. I love Homestead. I think it has been a great project but with Homestead 2, the added `/.homestead` directory has caused more problems than solutions for me. I don't really like having Homestead in 2 different directories either. I have started opting for other solutions but would prefer to stick with Homestead if possible.

**Comment by ArjanSchouten** [comment] 2015-07-09 19:33
ping @GrahamCampbell this is already achieved so probably you can close this.

**Comment by GrahamCampbell** [comment] 2015-07-09 20:04
Thanks @ArjanSchouten.

**Closed** 2015-07-09 20:04 UTC
Labels: proposal
