### ISSUE TITLE
loadCount ignores $connection property in a related model when applied against a belongsToMany relation

### ISSUE THREAD

**Issue by alwintom** [laravel/framework#29125] opened 2019-07-10 06:46 UTC
- Laravel Version: 5.8.23
- PHP Version: 7.3.0
- Database Driver & Version: Mysql 5.7.17

### Description:
I have a multi tenant application with a core db connection named 'main' and multiple tenant DBs with connection name 'tenant'. The database param of 'tenant' connection is chosen dynamically using a http middleware.

I have the following two models:
Lead
````php
class Lead extends Authenticatable
{
 
    protected $connection = 'tenant';

    public function favoriteProperties() {
        $dbName =$this->getConnection('tenant')->getDatabaseName();
        return $this->belongsToMany(\App\Property::class, "$dbName.favorite_properties");
    }
}
````

Property
````php
class Property extends Model
{
    protected $connection = 'main';
}
````
There is a pivot table inside each tenant db by the name of 'favorite_properties' created with the following migraion

````php
public function up()
    {
        Schema::create('favorite_properties', function (Blueprint $table) {
            $table->unsignedInteger('property_id');
            $table->unsignedInteger('site_id');
            $table->unsignedInteger('lead_id');
            $table->timestamp('created_at');
        });
    }
````

The problem:
When I run the following code:
````php
$leads = \App\Lead::orderBy('id', 'ASC')->take(5)->get();
$leads->loadRelation('favoriteProperties');
$leads->loadCount('favoriteProperties');
````
The call to `loadRelation` works and generates the following  query:
````sql
select `properties`.*, `tenant_1`.`favorite_properties`.`lead_id` as `pivot_lead_id`, `tenant_1`.`favorite_properties`.`property_id` as `pivot_property_id` from `properties` inner join `tenant_1`.`favorite_properties` on `properties`.`id` = `tenant_1`.`favorite_properties`.`property_id` where `tenant_1`.`favorite_properties`.`lead_id` in (2, 6, 12) and `properties`.`deleted_at` is null
````
This gives me the right result.

But the second call to `loadCount` generates the following query:
````sql
select `id`, (select count(*) from `properties` inner join `tenant_1`.`favorite_properties` on `properties`.`id` = `tenant_1`.`favorite_properties`.`property_id` where `leads`.`id` = `tenant_1`.`favorite_properties`.`lead_id` and `properties`.`deleted_at` is null) as `favorite_properties_count` from `leads` where `leads`.`id` in (2, 6, 12))
````
This results in the following exception:
`Base table or view not found: 1146 Table 'tenant_1.properties' doesn't exist`.

Even though I have given the connection name in `Property` model, it is not used in neither queries.

The hacky fix:
Modifying the `Property` model and overriding the `getTable()` function fixed the issue:
````php
class Property extends Model
{
    protected $connection = 'main';

    protected $table = 'properties'; 

    public function getTable()
    {
        return $this->getConnection()->getDatabaseName() . '.' . $this->table;
    }
}
````

So the root cause of the issues is eloquent not using the connection name to find out the DB name of a related model.

**Comment by staudenmeir** [comment] 2019-07-10 17:01
This is a known limitation (`loadCount()` uses `withCount()` internally): #23042

**Comment by driesvints** [comment] 2019-07-11 14:52
Closing this as a duplicate of #23042. We're still open to PRs to help solve this problem.

**Closed by driesvints** 2019-07-11 14:52 UTC
