### ISSUE TITLE
Command::choice() displays random, unsupported, characters on Windows

### ISSUE THREAD

**Issue by samuel-fonseca** [laravel/framework#26902] opened 2018-12-18 21:34 UTC
- Laravel Version: 5.7.13
- PHP Version: 7.2.6

### Description:

I am developing the application, currently, on Window, and this has never occurred to me. When using the method `Command::choice()` I get a weird response with random characters and question marks, and what I think is a timer. This only happens on Windows (As far as I have tested). 

I ran the same script on Ubuntu and it ran with no issues at all. It prompts the user with the two options, chooses one, and does whatever next.

I should note, all is well when running the script, it runs - technically - as expected. However, a bunch of random characters pop up between the `Command::choice()` and `Command::anticipate()` response and the next line. To test if this was only on CMD I ran the command on Hyper and PowerShell as well, getting similar results.

##### CMD

![cmd](https://user-images.githubusercontent.com/17728473/50182534-94dc3c00-02dd-11e9-9174-190f2862576e.PNG)

##### Hyper

![hyper](https://user-images.githubusercontent.com/17728473/50182540-99085980-02dd-11e9-8ce3-16ca4db62924.PNG)

##### PowerShell

![powershell](https://user-images.githubusercontent.com/17728473/50182600-c05f2680-02dd-11e9-9cbf-cc428001d394.PNG)

Everything else works fine; I get no problems with `Command::info()`, `Command::error()`, `Command::secret()`, `Command::confirm()`, or `Command::line()`.

### Steps To Reproduce:

1) Create new command `php artisan make:command TestChoice`

2) Copy & paste test script below

3) Run the command `php artisan test:choices`

4) Respond to the query `0` | `1`

#### Test script

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class TestChoice extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'test:choices';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $color = $this->choice('Which color do you prefer?', ['blue', 'red']);

        $this->info("Your favorite color is $color");
    }
}
```

---

# Update

The issue does not happen on macOS:

<img width="334" alt="screen shot 2018-12-18 at 5 27 40 pm" src="https://user-images.githubusercontent.com/17728473/50186909-56994980-02ea-11e9-8f24-d2804bb676ed.png">

I ran the same script on both macOS and Ubuntu and none of those have the issue.

I got back to my macbook and ran it on windows which had the same problem as originally described. And also described in my comment:

> @staudenmeir I am having this issue on two Windows separate installs. Here's my Windows 10 Pro install on dual boot (BootCamp) with my macOS.
> 
> <img alt="cmd" width="251" src="https://user-images.githubusercontent.com/17728473/50186631-66fcf480-02e9-11e9-840b-f72b3cdb5632.PNG">
> 
> The original post where I reported the issue was also Windows 10. However, that's a native install, on a Dell machine.
> 
> Both are on the Pro version.

**Comment by staudenmeir** [comment] 2018-12-18 21:38
I can't reproduce this on Windows 10.

**Comment by samuel-fonseca** [comment] 2018-12-18 22:23
@staudenmeir I am having this issue on two Windows separate installs. Here's my Windows 10 Pro install on dual boot (BootCamp) with my macOS.

<img width="251" alt="cmd" src="https://user-images.githubusercontent.com/17728473/50186631-66fcf480-02e9-11e9-840b-f72b3cdb5632.PNG">

The original post where I reported the issue was also Windows 10. However, that's a native install, on a Dell machine.

Both are on the Pro version.

**Comment by sisve** [comment] 2018-12-19 06:04
Those characters looks similar to ansi escape codes. The K should clear the line, 32m should set the foreground color to green, and 39m should restore the foreground to default.

Watching the screenshot shows that there are ansi colors present, so the mystery is why these specific ones aren't working. And I'm afraid we're dangerously close into debugging command prompt codepages in Windows, which isn't as fun as it sounds. Try running `chcp` to check what codepage you're using, perhaps the non-working machine has some weird value there...

**Comment by samuel-fonseca** [comment] 2018-12-19 13:36
Hey @sisve thanks for the response:

I am getting `Active code page: 437` when running `chcp`.

```sh
C:\Users\samuel.fonseca>chcp
Active code page: 437
```

**Comment by koenhoeijmakers** [comment] 2018-12-20 21:22
Does seem like your terminal does not support ansi in a way, can you try adding `--no-ansi`?

**Comment by samuel-fonseca** [comment] 2018-12-21 03:34
@koenhoeijmakers I think we're getting somewhere... still showing some weird characters, as it was mentioned above by @sisve the `[K` represents a new line which makes sense:

<img width="195" alt="cmd--no-ansi" src="https://user-images.githubusercontent.com/17728473/50323296-fef40d00-04a6-11e9-94cb-429732e993b3.PNG">

Is there any permanent solution to this issue? Or is this not a real issue?

Like I said, I encountered this on two separate Windows 10 Pro installs. Both in English-US. What are some of the reasons I could be having this issue?

**Comment by devcircus** [comment] 2018-12-21 03:56
More of a terminal/os issue than a Laravel issue. Lots of results via google.

**Comment by samuel-fonseca** [comment] 2018-12-21 05:07
@devcircus yes and no... While I have observed this particular problem to be Windows only, I find it curious that it only happens in the occasion of `Command::choice()` and `Command::anticipate()`. Every other command works fine.

So you are right it's a terminal/os issue, but it's not across the board, or consistent. That's why I came here. Maybe there's a particular difference in the output which could be addressed. I have never personally dealt with this, I was hoping someone else would have some experience in it.

**Comment by samuel-fonseca** [comment] 2018-12-22 17:43
@devcircus further on whether this is an OS problem... As I mentioned on the original post, this does not happen at all when using any other `Command` method:

![ansi_works](https://user-images.githubusercontent.com/17728473/50377188-b93e5e00-05e6-11e9-9092-fdf44c6f3a16.PNG)

```php
    public function handle()
    {
        if($this->confirm('Do you want to start?')) {
            $works = $this->ask('Does ANSI work here?');
            $this->info("$works, ansi color...");
            $this->line('This is what a line looks')
            $this->error('Oh no! Something went wrong.');
        }
    }
```

Colors, new lines, and everything else works as expected... Only when using the other two commands is when I run into this issue.

![ansi_not_works](https://user-images.githubusercontent.com/17728473/50377202-0ae6e880-05e7-11e9-8bb3-f32915c6b12d.PNG)

**Comment by samuel-fonseca** [comment] 2018-12-27 13:37
@driesvints what information do you still need?

**Comment by driesvints** [comment] 2019-01-02 14:54
@samuel-fonseca heya, I'm sorry but as we didn't get any reports from other Windows users I'm going to close this. Should we get more reports we'd be happy to look into this further. Since you're the only one with this particularly problem it's going to be a bit hard to dive deeply into this like others have mentioned above. I think it's best you'd try on some support channels like the one listed below:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Closed by driesvints** 2019-01-02 14:54 UTC
Labels: needs more info

**Comment by syamsoul** [comment] 2021-04-16 05:45
![image](https://user-images.githubusercontent.com/15118790/114977227-e9961e80-9eb9-11eb-82c5-dc45c59a257a.png)

Hi... I also faced this issue... Can anyone help me?

**Comment by keverson-ms** [comment] 2022-08-07 21:53
I also face this problem, any solution?

![image](https://user-images.githubusercontent.com/65048913/183312398-563eeb2b-4d43-424a-a778-35c5eb087629.png)

**Comment by enigmatic-user** [comment] 2023-04-25 07:33
Same here on Windows 10 Professional 22H2 using CMD, PowerShell, or Take Command (https://jpsoft.com/products/take-command.html). The active codepage is 850.

I'm not sure why anything at all is written to the console there. There's no need to repeat the chosen number, and this also doesn't happen on other systems (Linux, MacOS). On Windows, the chosen number is the first character in the unwanted output, it's not only the ANSI escape code.

**Comment by enigmatic-user** [comment] 2023-04-26 10:49
It does work in Windows Terminal (https://aka.ms/terminal / https://github.com/Microsoft/Terminal), though.
