### ISSUE TITLE
[5.4][Blade] Section not rendered if bracket is not closed

### ISSUE THREAD

**Issue by Funfare1337** [laravel/framework#18591] opened 2017-03-31 10:03 UTC
- Laravel Version: 5.4.16
- PHP Version: 5.6.26
- Database Driver & Version: ---
tested with fresh laravel 5.4 installation

### Description:
Given is this code:
```
@extends('layouts.default')
@section('test', 'test(')
@section('body')
```

if the bracket in section test is not closed, blade doesn't render the php code correctly:
```
<?php $__env->startSection; ?>('test', 'test(')
<?php $__env->startSection('body'); ?>
```

if the bracket is closed, it will be rendered correctly:

```
@section('test', 'test()')
@section('body')
```

```
<?php $__env->startSection('test', 'test()'); ?>
<?php $__env->startSection('body'); ?>
```

### Steps To Reproduce:
- create blade view
- extend other blade view (not relevant for this error, but I discovered it through this way)
- use short form of @section and open a bracket inside the value and don't close it

**Comment by Dylan-DPC** [comment] 2017-03-31 10:12
Not sure how this will be of any interest to anyone. What will you achieve with an unclosed parenthesis?

**Comment by laurencei** [comment] 2017-03-31 10:14
I'm on my phone - so I cant test this myself. What does

`@section('test', 'test(o')`

give?

i.e. is the bug a `(` without a closing `)` in the string - or is the bug a `(` as the last character?

**Comment by laurencei** [comment] 2017-03-31 10:15
@dylan-DPC - what if you wanted a page title of

`Sorry - :(`

That would break

**Comment by Funfare1337** [comment] 2017-03-31 10:59
@laurencei no matter where the ( is.
`@section('page_heading','Debug Exception (none productive')`
fails too.

**Comment by themsaid** [comment] 2017-03-31 18:22
Duplicate of https://github.com/laravel/framework/issues/18317

**Closed by themsaid** 2017-03-31 18:22 UTC
