### ISSUE TITLE
Cursor pagination does not work properly on a hasManyThrough relationship.

### ISSUE THREAD

**Issue by paulandroshchuk** [laravel/framework#40270] opened 2022-01-05 20:34 UTC
- Laravel Version: 8.78.1
- PHP Version: 8.0.13
- Database Driver & Version: MySQL 8.0.27

### Description:

I noticed wrong data being returned from the database when using cursor pagination on a hasManyThrough relationship.

By default (without cursor pagination), `hasManyThrough` generates this query:
![image](https://user-images.githubusercontent.com/13240539/148283682-b4658dc9-e9ec-441e-afbd-5d0b8144c076.png)

But when using cursor pagination, it uses `SELECT *` (instead of `SELECT table.*`) along with `INNER JOIN` which ends up mixing up values from both tables:
![image](https://user-images.githubusercontent.com/13240539/148283797-16ef1f23-554b-424a-b3da-bd55f633ca8b.png)

### Steps To Reproduce:

1. Create a hasManyThrough relationship. (I used the example on [this page](https://laravel.com/docs/8.x/eloquent-relationships#has-many-through)).
2. Make sure the intermediate and final tables have a column with the same name (like `uuid`). 
3. Run `cursorPaginate` on the `hasManyThrough` relationship and dump the model's uuid (cursorPaginate()->first()->uuid), and you'll see that it put a value from the intermediate table instead of the value in the final table.

**Comment by driesvints** [comment] 2022-01-07 11:47
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

PS. I realise you have created the repo already but because you've committed all your changes in the initial commit it's hard for me to debug this. Please recreate the repo with the above command.

**Comment by paulandroshchuk** [comment] 2022-01-07 12:41
Done: https://github.com/paulandroshchuk/bug-report

@driesvints

**Comment by driesvints** [comment] 2022-01-07 15:01
Hey @paulandroshchuk, thanks for that. I sent in a PR that should fix this: https://github.com/laravel/framework/pull/40300

**Closed** 2022-01-07 15:07 UTC
Labels: bug
