### ISSUE TITLE
Using withCount() breaks some queries

### ISSUE THREAD

**Issue by mcbanderson** [laravel/framework#20571] opened 2017-08-15 04:49 UTC
- Laravel Version: 5.4.33
- PHP Version: 7.0.22
- Database Driver & Version: MySQL 5.6.27

### Description:
I recently upgraded my application to 5.4 from 5.2, and as soon as I finished upgrading I started running into this issue. I have 2 custom models, Event and Gift, which have a one to many relationship set up. Before the upgrade everything worked as expected, but after the upgrade any queries that includes ->withCount('gifts') are not working properly.

Some queries, such as the ones below, return an empty Eloquent Collection or null respectively (empty collection for ->get(), null for find(74)). For this example an id of 74 is used, which has been confirmed to exist in the database.

`Event::withCount('gifts')->where('id', 74)->get()`
`Event::withCount('gifts')->find(74)`

Other queries, such as the one below, will produce a non-empty collection, but some of the where clauses appear to be completely ignored. In this example the correct gifts_count is returned with each Event, but Events that are older than 2 days appear in the collection (the where clause appears to be completely ignored).

`Event::withCount('gifts')->whereIn('user_id', [5, 16, 18])->where('celebration_date', '>=', Carbon::now()->subDays(2))->limit(50)->get()`

The relationship appears to be setup correctly, because the query `Event::find(74)->gifts()->get()` will return an Eloquent Collection that contains all Gifts associated with that Event.

The things that I find very strange are that:

1. Everything was working as expected before the upgrade, and no changes were made to the models.
2. withCount is working for another model, Comment, that has the same relationship to Event as Gift (one Event has many Comments/Gifts).
3. The SQL generated when using ->toSql() on the faulty queries is correct. I have run the generated queries directly in the database and the correct results are returned.

### Steps To Reproduce:
I am unsure if this issue is reproducible in a stock installation of Laravel 5.4. I'm hoping to avoid having to setup a clean installation of Laravel 5.4 and manually port my application over, but if I'm unable to resolve this problem in the next day or two I think that will be my next course of action. If there is any additional information I can provide please let me know, and any guidance on possible solutions to try would be greatly appreciated.

**Comment by themsaid** [comment] 2017-08-15 07:03
Duplicate of https://github.com/laravel/framework/issues/19388

**Closed by themsaid** 2017-08-15 07:03 UTC
