### ISSUE TITLE
(Un)expected behaviour of the blade `@each` directive

### ISSUE THREAD

**Issue by n1c** [laravel/framework#13090] opened 2016-04-08 15:50 UTC
In line with how the `@include` directive works, I was expecting that data in parent templates would still be available inside the `@each` template though it seems as though they aren't.

From what I can tell the difference between the [BladeCompiler@compileInclude](https://github.com/laravel/framework/blob/5.2/src/Illuminate/View/Compilers/BladeCompiler.php#L832) and [BladeCompiler@compileEach](https://github.com/laravel/framework/blob/5.2/src/Illuminate/View/Compilers/BladeCompiler.php#L413) methods is that Include sends the `get_defined_vars` data along with the make call while the Each doesn't.

I've also made a really simple project to illustrate the problem [here](https://github.com/n1c/laravel-each-test), have a look at the routes & corresponding view. The expected behaviour would be that all 3 outputs are the same. Though the `title` variable isn't passed down into the `@each`.

![screen shot 2016-04-08 at 17 48 43](https://cloud.githubusercontent.com/assets/284075/14389265/2c577286-fdb2-11e5-9c5b-ee89e5dae8b4.png)

Thanks in advance,
Nic.

**Comment by mark86092** [comment] 2016-04-09 14:02
> is that Include sends the get_defined_vars data along with the make call while the Each doesn't.

Yes, you're right, it's the reason why `@each` doesn't inherent the data.
On doc, only `@include` explicitly says "All variables that are available to the parent view will be made available to the included view"

**Comment by n1c** [comment] 2016-09-07 08:12
@GrahamCampbell could you comment on a reason for closing this? Even if the behaviour is expected or not?

Thanks.

**Comment by GrahamCampbell** [comment] 2016-09-07 08:16
Closed since there was not a code snippet provided me for to look at and evaluate.

**Comment by RomainLanz** [comment] 2016-09-07 08:17
@GrahamCampbell So maybe you should ask instead of directly closing the issue...

**Comment by n1c** [comment] 2016-09-07 08:24
A code snippet for a solution?

The original description links to the 2 sections in the code & there's a link to a repo where you can replicate it. I haven't worked on a solution because I'm not sure yet if the behaviour is intended or not. And if the intended is correct or not?

**Comment by GrahamCampbell** [comment] 2016-09-07 08:31
Show me an example and tell me what it outputs compared to what you'd expect it to.

**Comment by n1c** [comment] 2016-09-07 10:18
Sure, as per the original comment with [code available here](https://github.com/n1c/laravel-each-test/blob/master/resources/views/welcome.blade.php#L7) I would expect all 3 lists to look the same. But the `@each` doesn't pull through the `$page` variable [sent to the view here](https://github.com/n1c/laravel-each-test/blob/master/app/Http/routes.php#L15).

![2c577286-fdb2-11e5-9c5b-ee89e5dae8b4](https://cloud.githubusercontent.com/assets/284075/18308416/c4d300b6-74f4-11e6-8c58-ec3248923172.png)

**Comment by GrahamCampbell** [comment] 2016-09-07 10:23
```
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>
    </head>
    <body>
        <h1>foreach and include</h1>
        <ul>
            @foreach ($items as $item)
                @include('partials.each')
            @endforeach
        </ul>

        <h1>foreach and include (with explicit data)</h1>
        <ul>
            @foreach ($items as $item)
                @include('partials.each', [ 'item' => $item ])
            @endforeach
        </ul>

        <h1>each</h1>
        <ul>
            @each('partials.each', $items, 'item')
        </ul>
    </body>
</html>
```

**Comment by n1c** [comment] 2016-09-07 10:37
Yes that is the view.

Now is it expected behaviour that `$page` be available in the partial that's used in the `@each`? Because it is not. While it is available when the partial is used via `@include`.

**Comment by GrahamCampbell** [comment] 2016-09-07 10:52
That looks correct I think?

**Comment by Decadence** [comment] 2016-09-16 08:07
Same issue for me. I was expecting `@each` will inherit variables as `@include` and `@extends`.

**Comment by mark86092** [comment] 2016-09-16 09:48
From the source code, I see that `@include` will inherit the data, while `@each` won't. @n1c @Decadence, that's the reason for the expected behaviors.

From my point of view, `@each` is a beautiful shortcut for simple data, it is not a bug.

You can see the code here: https://github.com/laravel/framework/blob/5.2/src/Illuminate/View/Factory.php#L266 for `@each` related

https://github.com/laravel/framework/blob/5.2/src/Illuminate/View/Compilers/BladeCompiler.php#L854 for `@include`, `get_defined_vars()` is passed.

**Comment by Decadence** [comment] 2016-09-16 10:40
I agree this is not a bug, but it would be useful to have opportunity to pass additional data at least.

**Comment by CupOfTea696** [comment] 2016-09-20 14:10
@GrahamCampbell I presume the actual code example probably looks a little more like this:

**view.blade.php:**
```blade
<?php $title = 'Hello World'; ?>
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>
    </head>
    <body>
        <h1>foreach and include</h1>
        <ul>
            @foreach ($items as $item)
                @include('partials.each')
            @endforeach
        </ul>

        <h1>foreach and include (with explicit data)</h1>
        <ul>
            @foreach ($items as $item)
                @include('partials.each', [ 'item' => $item ])
            @endforeach
        </ul>

        <h1>each</h1>
        <ul>
            @each('partials.each', $items, 'item')
        </ul>
    </body>
</html>
```

**partials/each.blade.php:**
```blade
<li>
   {{ isset($title) ? $title : 'NOTITLE' }}: {{ $item }}
</li>
```

**Comment by themsaid** [comment] 2016-09-26 21:19
@Decadence can you please share a use case where you need to pass extra data to `@each`? The thing is that it's only a shortcut to be used in a very specific situation, I believe it's actually inspired by Vue.js

If there's no real use case for this then I believe it's just fine as it is, you can use include under an `@each` method if you need more control over the rendering operation.

**Comment by Decadence** [comment] 2016-09-26 21:28
I can do without @each at all, but it's handy.
Simple case: I need output table row with three td in one case and with four in another case depending on condition from parent template. How do I handle it with @each and without copy-paste views?

**Comment by themsaid** [comment] 2016-09-26 21:47
Have been discussing the matter with Taylor, passing a *fifth* argument to `@each` seems too much, and allowing each to inherit variables from the parent view looks very complicated.

So I'll close this and suggest you use

            @foreach ($items as $item)
                @include('partials.each', [ 'item' => $item ])
            @endforeach

To get the results you want.

**Closed by themsaid** 2016-09-26 21:47 UTC

**Comment by Decadence** [comment] 2016-09-27 05:32
Ok, thanks for discussing though.

**Comment by n1c** [comment] 2016-09-27 06:09
Yeah that makes sense. Thanks for the discussion!
