### ISSUE TITLE
How to remove Restriction of 'X-Frame-Options' 

### ISSUE THREAD

**Issue by fakharkhan** [laravel/framework#18162] opened 2017-02-28 20:52 UTC
- Laravel Version: 5.3
### Description:
I am want to load a url of my laravel application on third party web site using iframe, 
but it does not allow me to load the url form there under iframe, it says the following error:
Refused to display 'http://browns.softpyramid.ca/widgets/fee-calculator' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
Need help to make it workable using via iFrame.
### Steps To Reproduce:
` <iframe src="http://browns.softpyramid.ca/widgets/fee-calculator"></iframe>`

**Comment by edenreich** [comment] 2017-02-28 21:07
The error you currently getting after I clicked on the link you posted has to do with  none object on your body-content.blade.php file.

Has to do with I frame, there are many ways to do this. You can also make an ajax request to that third party website and fetch the content with file_get_content(), later you can simply send the fetched data to your view.

Hope that helps

**Comment by fakharkhan** [comment] 2017-03-01 11:48
@edenreich yes that was local app bug, i have fixed that and the url is now working,
http://browns.softpyramid.ca/widgets/fee-calculator
and now can be tested using:
`<iframe src="http://browns.softpyramid.ca/widgets/fee-calculator"></iframe>`

The url is a component written in vue js and it has lot of things in it to do.
It would be great if community can help me to remove the restriction of iframe.
thanks

**Comment by edenreich** [comment] 2017-03-01 12:13
I have found a solution for this here:
http://stackoverflow.com/questions/20293116/override-http-headers-default-settings-x-frame-options

according to laravel 4.2 you can try App::forgetMiddleware('Illuminate\Http\FrameGuard');
if that doesnt work, you will need to override that handle method. lastly if both doesnt work just comment line 20 in Illuminate\Http\FrameGuard.

hope that helps

**Comment by edenreich** [comment] 2017-03-01 12:30
btw, shouldnt that middleware appear in App\Http in the Kernel.php file ? so people can decide if they need this middleware, or I probably missed the name of it in Kernel.php

**Comment by fakharkhan** [comment] 2017-03-01 12:37
@edenreich in 5.3 forgetMiddleware is not available, i tried to override that method and now it says:

`Multiple 'X-Frame-Options' headers with conflicting values ('ALLOW-FROM http://widgets.dev/, SAMEORIGIN') encountered when loading 'http://browns.softpyramid.ca/widgets/fee-calculator'. Falling back to 'DENY'.`

So it did not removed old header but added new one to it.

**Comment by fakharkhan** [comment] 2017-03-01 12:41
@edenreich i think in laravel 5.3 FrameGuard is not used by default, but i used it and made it to:

`$response->headers->remove('X-Frame-Options');`
`$response->headers->set('X-Frame-Options', 'ALLOW-FROM', 'http://widgets.dev/');`

also tried:
`header_remove('X-Frame-Options');`
`header('X-Frame-Options: ALLOW-FROM http://widgets.dev/');`

but no luck same error:
`Multiple 'X-Frame-Options' headers with conflicting values ('ALLOW-FROM http://widgets.dev/, SAMEORIGIN') encountered when loading 'http://browns.softpyramid.ca/widgets/fee-calculator'. Falling back to 'DENY'.`

**Comment by edenreich** [comment] 2017-03-01 12:45
I think its something to do with your .htaccess file..did you look there?

try following this steps:

http://stackoverflow.com/questions/5881139/how-to-block-iframe-call
(instead of deny write ALLOW)

**Comment by fakharkhan** [comment] 2017-03-01 13:05
No luck

**Comment by edenreich** [comment] 2017-03-01 13:17
best way to go about it is to try and set your headers X-Frame-Options: ALLOW-FROM [the-url-from-where-you-want-to-fetch-the-data] using laravel implemention. you can always modify / override the headers to your needs.

check the documentation: https://laravel.com/docs/5.4/responses

Just follow the documentation and try to return the response with this header in your controller. I havent tested it myself, but it should be overriding, im pretty sure.

so basicly it should look like this:

return response()
            ->view('hello', $data, 200) // modify it to your view
            ->header('X-Frame-Options', 'http://widgets.dev/');

**Comment by GrahamCampbell** [comment] 2017-03-01 13:24
Feel free to continue discussing here, or on the forums. Closing though, because this is not a bug report with the framework, as such. :)

**Closed** 2017-03-01 13:24 UTC

**Comment by fakharkhan** [comment] 2017-03-01 13:54
@GrahamCampbell you are right, nothing to do with framework, we removed the headers from nginx, and it worked. thanks @edenreich for the efforts.

**Comment by lucasvm** [comment] 2018-08-11 14:46
Im getting the same issue with laravel using apache, any fix for apache?

**Comment by saurabhksunny** [comment] 2019-02-18 09:52
Hi,
A simple solution is to add "Ignore X-Frame headers" extension to your chrome.

**Comment by Abhi0725** [comment] 2019-02-28 06:58
My issue was after I started using Forge. It seems that in nginx configuration 'SAMEORIGIN' policy was set by default. Just comment out that and add your own X-FRAME rule in application.

**Comment by rahulkhosla** [comment] 2019-04-14 21:29
I found a [good answer](https://wpza.net/remove-x-frame-options-to-sameorigin-from-iframe/) which uses an external library, fairly quick to implement too. Hope it helps others with the same issue.

**Comment by MindfulMe** [comment] 2020-07-14 21:49
> I found a [useful answer](https://wpza.net/remove-x-frame-options-to-sameorigin-from-iframe/) which uses an external library, fairly quick to implement too. Hope it helps others with the same issue.

I would fucking fire you right away

**Comment by infinitbility** [comment] 2021-03-31 17:52
refused to display 'url' in a frame because it set 'x-frame-options' to 'sameorigin' solution

https://infinitbility.com/refused-to-display-'url'-in-a-frame-because-it-set-'x-frame-options'-to-'sameorigin'

**Comment by abdulrehman25** [comment] 2022-07-13 18:20
This is what worked for me

`<IfModule mod_headers.c> 
Header set X-Frame-Options ALLOW 
</IfModule>`
