### ISSUE TITLE
Eloquent queries within DB::listen wipes model relation attributes

### ISSUE THREAD

**Issue by antonkomarev** [laravel/framework#25768] opened 2018-09-25 00:25 UTC
- Laravel Version: 5.7.5
- PHP Version: 7.1.20
- Database Driver & Version: MySQL 5.7.23

### Description:

Eloquent queries within `DB::listen` wipes Model's attributes filled via relation.

```php
$project = \App\Project::create();
$task = $project->tasks()->create(['title' => 'Task']);
$subtask = $task->subtasks()->create(['title' => 'Subtask']);
```
When you create subtask using `subtasks` relation, then argument `Task` which being sent to `creating` method of `TaskObserver` should have `parent_task_id` equals to `$task->id`.

But If any Eloquent query will be executed within `DB::listen` closure - in observer `created` method we will have `parent_task_id=null`. Note that `title` attribute will be passed without any issues.

### Steps To Reproduce:

1. Create migration `2018_09_25_000000_create_test_table.php`:

```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTestTable extends Migration
{
    public function up()
    {
        Schema::create('projects', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->timestamps();
        });

        Schema::create('tasks', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('parent_task_id')->nullable();
            $table->unsignedBigInteger('project_id');
            $table->string('title');
            $table->timestamps();
        });
    }
}
```

2. Create Project model:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    public function tasks()
    {
        return $this->hasMany(Task::class, 'project_id');
    }
}
```

3. Create Task model:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = ['title'];

    public function project()
    {
        return $this->belongsTo(Project::class, 'project_id');
    }

    public function parentTask()
    {
        return $this->belongsTo(Task::class, 'parent_task_id');
    }

    public function subtasks()
    {
        return $this->hasMany(Task::class, 'parent_task_id');
    }
}
```

4. Create TaskObserver

```php
<?php

namespace App\Observers;

use App\Task;

class TaskObserver
{
    public function creating(Task $task)
    {
        $parentTask = $task->parentTask()->first();
        if ($parentTask) {
            $task->project_id = $parentTask->project_id;
        }
    }
}
```
This observer will set `project_id` attribute to all subtasks.

5. Register TaskObserver & DB listener in AppServiceProvider

```php
public function boot()
{
    \App\Task::observe(\App\Observers\TaskObserver::class);

    DB::listen(function (\Illuminate\Database\Events\QueryExecuted $query) {
        if (stripos($query->sql, '`projects`') === false) {
            \App\Project::first();
        }
    });
}
```
Any eloquent query will break TaskObserver, so this is just simple example with recursion protection.

6. Try to create task and subtask

```php
$project = \App\Project::create();
$task = $project->tasks()->create(['title' => 'Task']);
$subtask = $task->subtasks()->create(['title' => 'Subtask']);
```

**Comment by staudenmeir** [comment] 2018-09-25 01:03
Why do you execute a query in `DB::listen()`?

**Comment by antonkomarev** [comment] 2018-09-25 01:04
Because I want to store debug information about the query.

**Comment by staudenmeir** [comment] 2018-09-25 01:07
Are you using the same kind of recursion protection as in this example?

**Comment by antonkomarev** [comment] 2018-09-25 01:10
@staudenmeir sure. Read description, please. There is no issue with DB::listen itself. Model's in observers lose filled relationship attributes somehow.

**Comment by staudenmeir** [comment] 2018-09-25 01:12
I read the description and I can reproduce the issue. I was just asking about the use case.

**Comment by antonkomarev** [comment] 2018-09-25 01:19
I'm making small tool for debugging queries. Initially it was used `Log::debug()` method, but then I decided to try to store it in database to have clean and easy auditing interface.
Not sure that I will keep using database for it, but reported because it could be useful for somebody else.

**Comment by staudenmeir** [comment] 2018-09-25 01:45
The issue already starts in `\App\Project::create()`: Laravel successfully inserts the project but only gets the new `AUTO_INCREMENT` id *after* the query in `DB::listen()` is executed. This replaces the original id with `0` and causes the whole problem.

**Comment by antonkomarev** [comment] 2018-09-25 02:30
Thank you for investigation @staudenmeir!
I've thought to separate debugging to its own connection to simplify recursion protection by just checking connection name. Haven't even thought it could help to avoid this bug. I'll try it tomorrow.

**Comment by antonkomarev** [comment] 2018-09-25 03:12
@staudenmeir confirming that it works!
I don't know if this issue should be closed or not. Not sure that somebody will try to fix this issue because it has really low impact.

**Comment by staudenmeir** [comment] 2018-09-25 11:48
This is such a fundamental issue, I don't think it can be fixed when you use the same database connection.

**Comment by antonkomarev** [comment] 2018-09-25 16:14
I've published the tool I've worked these days: https://github.com/cybercog/laravel-sense

Solved this issue at this moment by just copying default connection settings to my hardcoded `sense` connection name in Service Provider.

```php
if (is_null($config = config('database.connections.sense'))) {
    if (is_null($fallbackConfig = config('database.connections.' . config('database.default')))){
        throw new \Exception('Database connection [sense] has not been configured.');
    }
    config(['database.connections.sense' => $fallbackConfig]);
}
```

**Comment by laurencei** [comment] 2018-09-26 04:15
@antonkomarev @staudenmeir 

So can we close this issue? Or do we need to keep it open?

**Closed** 2018-09-26 10:17 UTC

**Comment by antonkomarev** [comment] 2018-09-26 14:53
As @staudenmeir well said - this issue is fundamental. I don't think there is good reason to refactor this part of the framework to fix really rare behavior which could be avoided without not much code.

**Comment by dzineer** [comment] 2019-04-12 10:08
I know this issue is closed but I was watching LaraCasts 

A better approach to logging DB Queries would be:

1 : 
DB::listen(function($query) { 	echo print_r($query->query, true);        echo print_r($query->bindings, true); });

2: 
DB::enableQueryLog() <---------  start logging queries
DB::getQueryLog() <------------   get current query logs since DB::enableQueryLog was called.

**Comment by Raza9798** [comment] 2021-03-14 08:12
Query Execution
    
    \Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {          
                $sql = $query->sql; 
                $time = $query->time;
                $connection = $query->connection->getName();
     
                Log::debug('query : '.$sql);
                Log::debug('time '.$time);
                Log::debug('connection '.$connection);
            });

Query

    StaffRegister::all();

Output

    [2021-03-14 08:00:57] local.DEBUG: query : select * from `staff_registers`  
    [2021-03-14 08:00:57] local.DEBUG: time 0.93  
    [2021-03-14 08:00:57] local.DEBUG: connection mysql  


complete structure 

    <?php

    namespace App\Http\Controllers;
    
    use Illuminate\Support\Facades\Log;
    use App\Models\StaffRegister;

    class AuthController extends Controller
    {
       public function index(){
       
           \Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {
          
               $sql = $query->sql; 
               $time = $query->time;
               $connection = $query->connection->getName();
 
               Log::debug('query : '.$sql);
               Log::debug('time '.$time);
               Log::debug('connection '.$connection);
           });

           $obj = StaffRegister::all(); 
        
           return $obj;
       }
    }

**Accurate Method**
