### ISSUE TITLE
Is there any reason that Model and Relatationships handle firstOrCreate differently?

### ISSUE THREAD

**Issue by paulrose** [laravel/framework#16477] opened 2016-11-19 10:58 UTC
- Laravel Version: 5.3.*

### Description:
Is there any reason that Model and Relatationships handle firstOrCreate differently?
Models allow lookup parameters (attributes) to grab the 'first' record, and also an insert parameters (values) with which to create a new record.

Wondering if theres any reason for this, before I attempt any pull-request.

### Steps To Reproduce:
Using a Todo as an example...
`some_random_lookup` would be something that isnt the primary key, but an indexed column we want to search.
`data` is our full array/object of new data we want to insert.

#### Model functionality

```php
Todo::firstOrCreate(['some_random_lookup' => $data['some_random_lookup'], $data)
```

This would behave as expected, using the first argument as the lookup, and then using the second argument to insert all data for a new Todo if none could be found.

#### Relationship functionality

```php
$user->todos()->firstOrCreate(['some_random_id' => $data['some_random_lookup']], $data)
```

The second argument here is ignored. And the new record is created solely from the first argument.

While you could just use the one parameter, there is definitely a need to use different parameters to lookup and insert.

**Comment by themsaid** [comment] 2016-11-21 12:09
That new argument was added here: https://github.com/laravel/framework/pull/13236

I guess it needs to be added for the relationship classes as well, I'd say go ahead and open a PR.

**Comment by themsaid** [comment] 2016-11-22 10:14
Closing since it's not a bug report, please ping me if you're willing to open a PR.

**Closed by themsaid** 2016-11-22 10:14 UTC
