### ISSUE TITLE
Collection::mapWithKeys() problem when key is int

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#17173] opened 2017-01-06 09:07 UTC
- Laravel Version: 5.3.28
- PHP Version: 5.6.15

### Description:
The problem when using mapWithKeys() and the key is an integer (id in my case) instead of getting the id as key i get an indexed array from 0 to N (number of teachers)

```php
Teacher::where() ...
->get()
->mapWithKeys(function ($teacher)
{
	$label = $teacher->user->name . " ({$teacher->present()->name_secondary}) ({$teacher->establishment->abbreviation})";

    return [$teacher->id => $label];
});
```

**Comment by themsaid** [comment] 2017-01-06 13:24
Duplicate of https://github.com/laravel/framework/issues/15409

**Closed by themsaid** 2017-01-06 13:24 UTC
