### ISSUE TITLE
[5.3] Add a method to assert type of values in a JSON structure

### ISSUE THREAD

**Issue by welcoMattic** [laravel/framework#15208] opened 2016-09-01 14:04 UTC
Hi,

I'm currently building a REST API, and I would like to assert that my endpoints return the right JSON using `seeJsonStructure`. Classic case. But, the point is that I use Faker to generate fixtures, and naturally my tests are broken after each `db:seed`. Of course I can use `seeJson` or `seeJsonEquals`, but IMHO we miss another method to assert the structure of the JSON and types of values (basically integer, string, boolean, array) as:

```php
$this->seeJsonTypedStructure([
  'id' => 'integer',
  'name' => 'string',
  'isActive' => 'boolean',
  'roles' => 'array',
]);
```

It's why I've started to work on `seeJsonTypedStructure` method here : https://github.com/welcoMattic/framework/commit/992a4c4524f0eddea0c3af64af26a2e32a9e3d94

It's open to discuss about the real value of this method ;)

Thanks

**Comment by JulienTant** [comment] 2016-09-01 14:28
It could be nice to valide a JSON when the data are generated by faker ! Good idea !

**Comment by lasselehtinen** [comment] 2016-09-02 11:45
Nice idea. Since we are talking about JSON I think it should cover all the JSON data types?

- Number
- String
- Boolean 
- Array
- Object
- null

**Comment by welcoMattic** [comment] 2016-09-02 12:28
@lasselehtinen Yes, I'm agree with that. I'll improve my code before opening a PR here.

**Comment by themsaid** [comment] 2016-09-08 04:09
I like the idea and suggest that you open a PR with the suggested changes.

Closing the issue since it's not a bug report, let's continue the discussion on a PR or if you'd like you can create an issue in the internals repository.
https://github.com/laravel/internals

**Closed by themsaid** 2016-09-08 04:09 UTC

**Comment by welcoMattic** [comment] 2016-09-08 09:05
@themsaid Ok thank you, I'll open an issue in internals ;) 

BTW, congrats for your job ! 🎉

**Comment by themsaid** [comment] 2016-09-08 09:06
Thank you! 😁
