### ISSUE TITLE
RegistersUsers fails to redirect to intended URL

### ISSUE THREAD

**Issue by tmaly1980** [laravel/framework#18365] opened 2017-03-15 21:26 UTC
- Laravel Version: 5.4.15
- PHP Version: 7.0
- Database Driver & Version:

### Description:

Trying to go to a private page only for logged in users, it redirects back to that page (rather than the default dashboard) if I already have an account, but trying to register will ignore what the intended URL was.

Auth's RegistersUsers::register() doesn't redirect to the url.intended . If I try to access a user private-only page, I will get redirected IF I log in with an existing account. But if I go from the Login page to the Register page, the session's url.intended is STILL set to the intended private page, but RegistersUsers simply redirects to redirectPath() rather than possibly the intended url via: redirect()->intended($this->redirectPath()) . AuthenticatesUsers works like expected, it seems the register() function in RegistersUsers trait just needs to be modified with intended()

**Comment by tmaly1980** [comment] 2017-03-15 21:27
Just need to change: 

`redirect($this->redirectPath());`

To:

`redirect()->intended($this->redirectPath());`

**Comment by lagbox** [comment] 2017-03-16 03:15
Define `protected function registered(Request $request, $user)` and have that return the redirect intended. Shouldn't have to change the `register` method to adjust that.

**Comment by tmaly1980** [comment] 2017-03-16 03:33
I'm totally aware that I can create custom versions of trait methods in my controllers, however, the point of filing this bug report is that if AuthenticatesUsers considers redirect()->intended(), so should RegistersUsers. I don't see any reason why a user should not be sent back to their intended page just because they are a new registered (versus existing) user. It's a quick fix.

**Comment by devcircus** [comment] 2017-03-16 03:48
Personally, with the types of apps I build, I've never wanted this functionality, actually, I'd want to intentionally avoid it. To me, the idea of intended comes from a relationship between an existing user and content on the site that they would normally have access to if they were logged in. Doesn't seem like such a relationship exists between a newly registered user and content on the site.

**Comment by tmaly1980** [comment] 2017-03-16 03:56
@devcircus , I have an application where I have users who register business pages, a link goes to /businesses/create . This page requires the user be logged in to complete that process. Most times in my case, they will not have an account already because most users will only manage one business page. 

I'd be more interested in hearing from the developer who made the decision to implement intended() in the first place, and whether it makes sense to either remove it altogether or make it work in both cases (my preference).

**Comment by lagbox** [comment] 2017-03-16 03:59
Implement intended where? and remove what altogether?

**Comment by tmaly1980** [comment] 2017-03-16 04:03
redirect()->intended() should work consistently whether the user is signing in to an existing account or registering a new account. If I have a link to a user-only page, new users should still go to the intended page just as existing users would if they logged in. 

The Auth\AuthenticatesUsers trait once a user is verified will redirect()->intended(), whereas Auth\RegistersUsers does not. I think it should be consistent. @devcircus was suggesting to remove intended() entirely from AuthenticatesUsers (which I disagree with).

**Comment by lagbox** [comment] 2017-03-16 04:05
That isn't what devcircus said.

And `redirect()->intended()` itself does work consistently.

**Comment by tmaly1980** [comment] 2017-03-16 04:11
@lagbox , see https://github.com/laravel/framework/pull/18369 . The function itself isn't the problem, the problem is RegistersUsers doesn't even bother to redirect to the "intended" URL. It always redirects to the same page (probably dashboard). You can repeat the problem by typing in a URL that has 'auth' middleware (users only) enabled, so it should prompt to login. Instead of signing in, register a new account and notice that it doesn't go to that private page.

**Comment by devcircus** [comment] 2017-03-16 04:27
I just don't think it makes sense to use it at the registration level by default. Too many cases where it doesn't make sense. See Taylors comment on #16432.

**Comment by lagbox** [comment] 2017-03-16 04:28
This was designed to work the way it does and it works that way, so its not a 'bug'. You just have a preference for it to act differently, in this singular example case you keep describing.
There is nothing wrong with wanting to change that, but its not a bug. :-)

**Comment by tmaly1980** [comment] 2017-03-16 12:54
I would say that it's up to the developer to decide whether or not to expose private URL's if that's the case. I don't understand what sort of URL would be non-existent if it's being generated/exposed publicly in the first place. Seems like a very rare situation and in that case, wouldn't it be up to the developer to link directly to /register or /login instead (if there is a chance the content doesn't exist)? I'd really like to see a use case for this issue that @taylorotwell  refers to. There's no guarantee that the content/page is there either even IF the user account already exists. Case in point:

1) Guest  goes to /businesses/create to create a business page
2) Guest is prompted to sign in
3) Guest doesn't have an account so they click on Register
4) Guest creates user account, then gets redirected to their dashboard page
5) New user signs out, then clicks on that same link /businesses/create again
6) New user signs in with account just created
7) New user actually lands on business creation form like expected

I would say that the issue @taylorotwell is concerned about is just as likely to happen whether the user has an account or is registering for the first time. It's up to the developer to expose the protected URL or not. I would say that if I don't want my users to do a specific user-only task immediately upon sign in, I would simply refer to /login on all my links instead of specific auth-only tasks. That's a developer decision.

**Comment by themsaid** [comment] 2017-04-06 07:06
Laravel is shipped with some conventions that may or may not suite a specific application, so it's up to the developer to change the behaviour in his own app.

Closing since it's being idle for sometime and it's not a bug.

Thanks :)

**Closed by themsaid** 2017-04-06 07:06 UTC
