### ISSUE TITLE
Error creating a new project phpunit/php-token-stream 2.0.0 requires php ^7.0

### ISSUE THREAD

**Issue by futureinvasion** [laravel/framework#20452] opened 2017-08-07 03:15 UTC
- Laravel Version: 5.4.*
- PHP Version: 5.6.30
- Database Driver & Version: 10.2.7-MariaDB Homebrew

### Description:

Error when creating new project with command `laravel new` results will show

```
Problem 1
    - Installation request for phpunit/php-token-stream 2.0.0 -> satisfiable by phpunit/php-token-stream[2.0.0].
    - phpunit/php-token-stream 2.0.0 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 2
    - phpunit/php-token-stream 2.0.0 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
    - phpunit/php-code-coverage 4.0.8 requires phpunit/php-token-stream ^1.4.2 || ^2.0 -> satisfiable by phpunit/php-token-stream[2.0.0].
    - Installation request for phpunit/php-code-coverage 4.0.8 -> satisfiable by phpunit/php-code-coverage[4.0.8].
```

### Steps To Reproduce:

```
❯ laravel new blog
Crafting application...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/php-token-stream 2.0.0 -> satisfiable by phpunit/php-token-stream[2.0.0].
    - phpunit/php-token-stream 2.0.0 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 2
    - phpunit/php-token-stream 2.0.0 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
    - phpunit/php-code-coverage 4.0.8 requires phpunit/php-token-stream ^1.4.2 || ^2.0 -> satisfiable by phpunit/php-token-stream[2.0.0].
    - Installation request for phpunit/php-code-coverage 4.0.8 -> satisfiable by phpunit/php-code-coverage[4.0.8].
```

**Comment by themsaid** [comment] 2017-08-07 19:36
Please update your installer and try again, it should be resolved by now

**Comment by JeffreyDavidson** [comment] 2017-08-08 12:24
@themsaid I have checked and my Laravel installer is the latest stable release. Is this then something PHPUnit only specific?

**Comment by jaredchu** [comment] 2017-08-08 19:34
@futureinvasion The problem is that `phpunit/php-token-stream` update 5 days ago require php ^7.0. This package is required in `phpunit/phpunit` 5.6.*. Hope they will fix this soon.
Currently you can use this command instead of `laravel new`:
```
$ composer create-project laravel/laravel myblog --no-dev
```

**Comment by isaackearl** [comment] 2017-08-09 01:28
also seeing this

**Comment by srmklive** [comment] 2017-08-10 10:09
Just checked it. I am able to create a new laravel project with PHP 5.6.30. You may need to run `composer global update` to fix this issue.

**Comment by futureinvasion** [comment] 2017-08-10 10:38
@srmklive I have tried with your solution, I can use `laravel new` now

**Comment by jaredchu** [comment] 2017-08-10 10:54
I confirm that it fixed. Cheer!

**Closed** 2017-08-10 13:37 UTC
