### ISSUE TITLE
migrate:fresh and migrate:rollback make different assumptions about postgres db schema

### ISSUE THREAD

**Issue by menasheh** [laravel/framework#23434] opened 2018-03-07 21:55 UTC
- Laravel Version: 5.5.*
- PHP Version: 7.2.0
- Database Driver & Version: Postgres 9.5.10 (in laravel/homestead box 5.1.0)

### Description:
`php artisan migrate:fresh` recreates the migrations table and runs the migrations properly on an empty database or after `php artisan migrate:rollback`. However, once the migrations have been run once, the following phenomenon occurs:
```
$ php artisan migrate:fresh
Dropped all tables successfully.
Nothing to migrate.
```
After the above command is run, the database still has retained all previous data, including the status of previous migrations:
```
$ php artisan migrate:status
+------+----------------------------------------------------------+
| Ran? | Migration                                                |
+------+----------------------------------------------------------+
| Y    | 2014_10_12_000000_create_users_table                     |
| Y    | 2014_10_12_100000_create_password_resets_table           |
| Y    | 2017_06_19_024651_create_email_confirmations_table       |
+------+----------------------------------------------------------+

```
`php artisan migrate:refresh` does work multiple times in a row, the issue is only with `migrate:fresh`. 
 Apparently, it's not actually dropping any tables, yet Laravel claims dropped all tables successfully.

Note we did not have this issue with a postgres 9.5.4 database instance. With that database version, `php artisan migrate:fresh` worked normally, even multiple times in succession.

### Steps To Reproduce:
Connect laravel to a postgres 9.5.10 database and run the following commands:
```
$ php artisan migrate:fresh
$ php artisan migrate:fresh
```
The second one will misbehave as described above.

**Comment by jonpemby** [comment] 2018-03-11 05:18
Hello! I was wondering if anyone is working on this? I want to contribute to the framework and am looking for a first issue to contribute a PR toward.

I can work on this if no one else is. :smile:

**Comment by jonpemby** [comment] 2018-03-11 18:53
@menasheh I tried the steps you mentioned and can't seem to reproduce; I used Laravel version 5.5.28 (I couldn't find a 5.5.73 release anywhere) and PostgreSQL 9.5.10.

Any luck resolving? Can you post your `create_email_confirmations_table` migration?

**Comment by menasheh** [comment] 2018-03-14 18:18
@jonpemby actually I forgot that that table wasn't part of laravel's default migrations.  The project has a bunch more.

Did you try setting that version in composer.json? I'll take a look again Thursday and double check my version.

**Comment by menasheh** [comment] 2018-03-16 05:19
I might have gotten laravel installer version or something.  composer.json just says laravel 5.5.*.

**Comment by jonpemby** [comment] 2018-03-21 13:12
@menasheh Will have some time coming up soon to investigate a bit further; thanks for confirming! :smile:

**Comment by menasheh** [comment] 2018-04-10 01:16
Why is this closed? I still have to switch back to `migrate:refresh` because fresh doesn't work twice in a row

**Comment by tillkruss** [comment] 2018-04-10 14:42
Because you're having issues with a custom migration and I can't reproduce this without you sharing the migration.

**Comment by menasheh** [comment] 2018-04-10 18:45
IMHO if it's still a problem for the OP, it shouldn't be closed. You could have mentioned that and asked me to share the migration or recreate the issue in a shareable repository...  Maybe there's a label for `needs-additional-information` instead?

**Comment by tillkruss** [comment] 2018-04-10 18:47
@jonpemby asked on March 11th to see the migration. The lack of activity often means the issue is resolved.

**Comment by menasheh** [comment] 2018-04-11 12:05
I actually have like 16 custom migrations in that project but forgot to cut out one of them.  I'll try to narrow down the issue this week, but in the meantime why would it be different based on what a particular migration does?

Would custom constraints cause it? It doesn't make sense.

**Comment by menasheh** [comment] 2018-04-12 21:46
I'm trying to recreate this in a fresh laravel repo but it's not working, even with my specific migrations.

In my real non-shareable codebase I have this problem, but not in a new codebase with just migrations copied.  What other variables are there?

**Comment by menasheh** [comment] 2018-04-12 22:07
Okay, it turns out there was was a discrepancy in my database config:

```
        'database' => [
            'driver' => 'pgsql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],

        'testing' => [
            'driver'    => 'pgsql',
            'host'      => env('DB_TEST_HOST', 'localhost'),
            'port'      => env('DB_TEST_PORT', '5432'),
            'database'  => env('DB_TEST_DATABASE', 'travis'),
            'username'  => env('DB_TEST_USERNAME', 'travis'),
            'password'  => env('DB_TEST_PASSWORD', ''),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
```

I have fixed this in my codebase, so now I explicitly set the 'schema' to public in the `testing` configuration, which I was using when I got the issue mentioned above.

However, everything besides `migrate:fresh` was working perfectly without that. 

It seems that `migrate:fresh` and `migrate:refresh` make different assumptions about schema.  Perhaps `migrate:refresh` assumes the `public` schema, and `migrate:fresh` does not?  If so, that should probably be changed.

**Comment by menasheh** [comment] 2018-04-12 22:26
I'm poking around, I see this in `Illuminate/Database/Console/Migrations/FreshCommand`:
```
    /**
     * Drop all of the database tables.
     *
     * @param  string  $database
     * @return void
     */
    protected function dropAllTables($database)
    {
        $this->laravel['db']->connection($database)
                    ->getSchemaBuilder()
                    ->dropAllTables();
    }
```

Meanwhile, `Illuminate/Database/Console/Migrations/RefreshCommand` uses `migrate:reset`... No idea where to go from here.

**Comment by SimplyCorey** [comment] 2018-06-07 13:15
I'm having the same issue with `RefreshDatabase` The trait only works on the default connection.  Any other connections have their migrations ran, but not reverse and this leads to errors such as "table already exists" on the next unit test run.

I believe this comes down to `migrate:fresh` requiring a database connection to be passed in.

https://github.com/laravel/framework/blob/f9d2bf330c823a56846f427ad1bef2df236bc072/src/Illuminate/Foundation/Testing/RefreshDatabase.php#L52

Currently, this does not pass in any connections and thus is only resetting the default connection within the trait.  A fix, is likely to foreach the connections and run the command on each connection.

**Comment by SimplyCorey** [comment] 2018-06-07 13:21
There appears to be a difference between `migrate:fresh` and `migrate:reset`

Changing the https://github.com/laravel/framework/blob/f9d2bf330c823a56846f427ad1bef2df236bc072/src/Illuminate/Foundation/Testing/RefreshDatabase.php#L53 to this fixes the issue:

```
$this->artisan('migrate:reset');
$this->artisan('migrate');
```

**Comment by menasheh** [comment] 2018-06-07 17:54
Check the definitions of the two database for any discrepancies

**Comment by laurencei** [comment] 2018-10-03 05:55
> The trait only works on the default connection.

Yes - `migrate:fresh` will only work on the default connection. If you want to use multiple connections in your testing you would need to use another option.

Ultimately this ticket does not have a reproducible set of issues from a clean install of Laravel 5.7.

If you can provide a step by step description of how to replicate - we can reopen the ticket.

**Closed by laurencei** 2018-10-03 05:55 UTC

**Comment by menasheh** [comment] 2019-02-12 15:15
@laurencei Why should `migrate:fresh` only work on the default connection? Is this documented?

**Comment by devcircus** [comment] 2019-02-12 15:25
You can pass the --database flag for any other connection.  Just run ```php artisan migrate:fresh --help```
