### ISSUE TITLE
More than one entry in failed_jobs for the same job launched once

### ISSUE THREAD

**Issue by MyFab2s** [laravel/framework#20147] opened 2017-07-19 09:56 UTC
- Laravel Version: 5.4.28
- PHP Version: PHP 7.0.18-0ubuntu0.16.04.1
- Database Driver & Version:15.1 Distrib 10.0.29-MariaDB

### Description:
Using database queues, when a job fails AND the laravel log is not writeable, we end up with two entries in failed_jobs for the same job, one for the max retry (I set it to one try) and one with the log write fail.
So if we retry the failed job, we will actually start this kind of failed job twice.

So this is an edge case, but, it may have some consequences and it may be hard to investigate afterward depending on how well the jobs are handling themselves.

[EDIT] It actually seems that this is the case whenever the job throw an exception AND you set retry to one !!!
### Steps To Reproduce:
Create a failing job. Make sure that the current log file is not writeable, and lunch it, you should see two entries in failed_jobs.

[EDIT] Create a job throwing an exception, launch the worker with one retry, you should see the same job twice in failed_jobs

**Comment by themsaid** [comment] 2017-07-19 10:54
Can't replicate, only one job is logged in the failed jobs table.

**Comment by themsaid** [comment] 2017-07-19 10:55
<img width="705" alt="screen shot 2017-07-19 at 1 02 50 pm" src="https://user-images.githubusercontent.com/4332182/28363623-7d3fee0a-6c81-11e7-8990-8c8b3632517c.png">

**Comment by MyFab2s** [comment] 2017-07-19 11:41
This is very odd.
I'm using supervisor with this command : 
`php artisan queue:work --tries=1 --queue=high,medium,low --sleep=3 --timeout=1500 --delay=0`

And after fixing the log access, I got several more failed duplicate (which I fail to reproduce ATM :1st_place_medal: ) and now I'm getting MaxAttemptsExceededException each time I feed the queue, but the job get's actually done (and it is atomic) .

Well I guess I have to investigate a lot more before I can actually call this a bug.

Another thing I noticed, is that in the payload column, the maxTries is null as well as the timeout, but I don't know yet if it is relevant to the issue.

In all cases, sorry if it's just me, I'll get back here if I find a real clue.

Thanks for replying.

**Comment by themsaid** [comment] 2017-07-19 11:44
> the maxTries is null as well as the timeout

Yes these values are job specific tries and timeout, they're null by default.

Going to close this issue then, but feel free to ping me whenever you're able to reproduce the issue, preferably in a fresh app since your project code might be altering the default behaviour.

Thanks :)

**Closed by themsaid** 2017-07-19 11:44 UTC
Labels: Unable to Replicate
