### ISSUE TITLE
[7.x] MethodNotAllowedException returns 500 code after routes caching

### ISSUE THREAD

**Issue by olegmelnik** [laravel/framework#31756] opened 2020-03-05 12:06 UTC
- Laravel Version: 7.0.4
- PHP Version: 7.2.27

### Description:
MethodNotAllowedException returns 500 code

### Steps To Reproduce:
- Execute `artisan route:cache`
- Make a request to the endpoint with an invalid method. The response returns 500 code
- Execute `artisan route:clear`
- Make the same request again. The response returns 405 code

**Comment by driesvints** [comment] 2020-03-05 12:21
Please share your routes file.

**Comment by olegmelnik** [comment] 2020-03-05 12:26
My api routes:

```
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/

Route::group(['prefix' => 'v1', 'namespace' => 'v1'], function () {
    Route::post('auth/login', 'AuthController@login');
    Route::post('auth/logout', 'AuthController@logout');

    Route::get('account', 'AccountController@show');

    Route::apiResource('users', 'UserController')->except('destroy');
    Route::apiResource('insurances', 'InsuranceController')->except('destroy');
    Route::apiResource('locations', 'LocationController')->only('index');
    
    Route::apiResource('orders', 'OrderController');
    Route::post('orders/{order}/start', 'OrderController@start');
    Route::post('orders/{order}/finish', 'OrderController@finish');

    Route::apiResource('orders.photos', 'OrderPhotoController')->except(['update', 'destroy']);
});
```

**Comment by olegmelnik** [comment] 2020-03-05 12:28
When I`m executing PUT request to `orders/{order}/start`, I get 500 code

**Comment by driesvints** [comment] 2020-03-05 12:52
@olegmelnik there's no put route defined for this?

**Comment by driesvints** [comment] 2020-03-05 12:59
@olegmelnik I can't reproduce the 500 error. How are you exactly triggering the PUT request?

**Comment by olegmelnik** [comment] 2020-03-05 13:03
> @olegmelnik there's no put route defined for this?

Yes

> @olegmelnik I can't reproduce the 500 error. How are you exactly triggering the PUT request?

I am caching routes and making request from REST client.

<img width="1229" alt="Снимок экрана 2020-03-05 в 16 03 13" src="https://user-images.githubusercontent.com/7072397/75984146-e8df3a80-5efa-11ea-9867-07d94e3d022a.png">

**Comment by driesvints** [comment] 2020-03-05 13:10
Thanks, finally managed to reproduce it. Sent in a fix for this: https://github.com/laravel/framework/pull/31762

**Comment by olegmelnik** [comment] 2020-03-05 13:12
Thanks!

**Closed** 2020-03-05 13:21 UTC
Labels: needs more info
