### ISSUE TITLE
Models with MySQL JSON fields get updated even though there was no change

### ISSUE THREAD

**Issue by ems1985** [laravel/framework#27946] opened 2019-03-20 21:56 UTC
- Laravel Version: 5.8
- PHP Version: 7.1.1
- Database Driver & Version: 8.0.15 - MySQL Community Server - GPL

### Description:
When you `update` or `->save()` a model with JSON attributes, where nothing has changed, Laravel may still still perform an update. 

I think the problem comes from using MySQL as a database driver. It seems that MySQL might change the order of your keys, when storing data in a JSON-type field.

This was taken from the MySQL documentation (https://dev.mysql.com/doc/refman/5.7/en/json.html#json-normalization):

> To make lookups more efficient, it also sorts the keys of a JSON object. You should be aware that the result of this ordering is subject to change and not guaranteed to be consistent across releases.

It appears as though Laravel doesn't account for that. So when MySQL changes the order of your JSON-data, Laravel thinks the model has changed.

Here is an example of how it looks in the model, and what it looks like after Laravel fetched it from the database (casted as an array). 

![image](https://user-images.githubusercontent.com/34405275/54721531-8dd5fb80-4b62-11e9-9fe7-ad7c55f638b8.png)

Even though nothing has changed on the model. Every time you call `->save` it will perform this query:

![image](https://user-images.githubusercontent.com/34405275/54721421-49e2f680-4b62-11e9-9f79-f9e859d27fc9.png)

## Location of code issue

The current code of `originalIsEquivalent()` in `HasAttributes.php` (https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php) will return `false`, when comparing the two values from the first figure. It doesn't matter whether you cast the JSON field or not, it will always return `false` because of the changed order.

**Comment by ed-fruty** [comment] 2019-03-20 23:12
As I can assume it going to `hasCasts`, casts `original` and `current` and after that tries to compare two objects via `===`.
So you need to do anything like php/json serialization to compare objects, depends of your attributes. 
Simplest way can be like:

```php
} elseif ($this->hasCast($key)) {
    return json_encode($this->castAttribute($key, $current)) ===
              json_encode($this->castAttribute($key, $original))
    ;
}
```

**Comment by ems1985** [comment] 2019-03-20 23:33
The problem with loose comparison is that it will also return that those two objects are identical:
```{"a":1,"b":0,"c":''} == {"a":true,"b":false,"c":0}
-> true```

So what you would need is some code, that (strict) compares the values, while ignoring the order of the attributes.

**Comment by staudenmeir** [comment] 2019-03-21 00:39
Can you provide a reproducible example?

**Comment by ems1985** [comment] 2019-03-21 09:50
sure, here is your...

### Database migration
```
Schema::create('bugs', function (Blueprint $table) {
    $table->increments('id');
    $table->json('culprit');
    $table->timestamps();
});
```

### Model
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Bug extends Model
{
    protected $casts = ['culprit' => 'array'];
}
```

### Class
```
<?php

namespace App\Services;

use App\Models\Bug;

class Reproduce
{
    protected $culpritData = ['one' => 1, 2 => 2, 'three' => '3', 'four' => 4, 5 => 5];

    public function create()
    {
        $bug = new Bug();
        $bug->culprit = $this->culpritData;
        $bug->save();
    }

    public function thisShouldNotUpdate()
    {
        $bug = Bug::first();
        $bug->culprit = $this->culpritData;
        $bug->save();

        return $bug;
    }
}
```

### Code to reproduce
```
$reproduce = new Reproduce;
$reproduce->create();
$reproduce->thisShouldNotUpdate();
```

But it does update (check out `updated_at` attribute)... 
```
=> App\Models\Bug {#3212
     id: 1,
     culprit: "{"one":1,"2":2,"three":"3","four":4,"5":5}",
     created_at: "2019-03-21 02:16:28",
     updated_at: "2019-03-21 02:17:08",
   }
```

And here is why (look at the order of the `culprit` attribute)...
```
>>> use App\Models\Bug
>>> Bug::first()
=> App\Models\Bug {#3234
     id: 1,
     culprit: "{"2": 2, "5": 5, "one": 1, "four": 4, "three": "3"}",
     created_at: "2019-03-21 02:16:28",
     updated_at: "2019-03-21 02:17:08",
   }
>>>
```

It works perfectly fine, when you use the `text` or `varchar` data type in your database.

**Comment by staudenmeir** [comment] 2019-03-22 04:12
I see the issue, but I'm not totally convinced that we should fix it.

We would have to sort the keys recursively (not available as a native function but easy to implement) which adds some overhead to using JSON attributes.

Also, this issue only occurs when updating a JSON attribute with the same value. What would be a typical case where this happens? Editing attributes with a form?

**Comment by ems1985** [comment] 2019-03-22 10:01
> I see the issue, but I'm not totally convinced that we should fix it.

I guess it should only be done if there is a good and easy solution to do it.

> We would have to sort the keys recursively (not available as a native function but easy to implement) which adds some overhead to using JSON attributes.

What if you first compare the attributes without any sorting (like it is now) and only if the comparison fails you sort the keys and compare it then?

> What would be a typical case where this happens? Editing attributes with a form?

For me the issue came up when I was trying to implement a one-way synchronization via an API from an external source to my database. I was able to solve it by simply using a text field instead, but that only works because the API (so far) always returns the data in the same order.

**Comment by staudenmeir** [comment] 2019-03-27 05:22
I've created a PR with your idea: #28029

**Comment by ems1985** [comment] 2019-03-27 08:54
Looks great :+1: 
Thanks for the quick response.

**Comment by driesvints** [comment] 2019-03-28 12:55
Since the PR was rejected and the bug deemed not worth a fix at this time I'm closing this. It's best that if this needs to be changed that an issue is opened in the ideas repo so support for the change can be gathered before a new attempt is made.

**Closed by driesvints** 2019-03-28 12:55 UTC
Labels: bug
