### ISSUE TITLE
UploadedFile::fake() become to array with single key(name) in controller

### ISSUE THREAD

**Issue by gring2** [laravel/framework#23799] opened 2018-04-04 03:40 UTC
In Test i make fake file and send with multipart/form-data to controller 

```
$image = UploadedFile::fake()->image('fake.jpg');
        $f1 = UploadedFile::fake()->create('fake.doc');
        $f2 = UploadedFile::fake()->create('fake.doc');
        $f3 = UploadedFile::fake()->create('fake.xls');

        $value=[
            'agent_id' => $agent_result->agent_id,
            'job_user_name' => '求職者さん',
            'job_user_pronun' => 'キュウショクシャサン',
            'email' => 'job@job.co.jp',
            'user_image' => $image,
            'resume_file1' => $f1,
            'resume_file2' => $f2,
            'resume_file3' => $f3,
        ];
        $response = $this->withHeaders(['CONTENT_TYPE' => 'multipart/form-data'])->post(route('jobuser.store',$value));

````
And i found fake files turn into array has 'name' the key and value.

i worked properly before and my controller work well when i try to save file from browser

my controller check if request has file or not like below
```
            if($request->hasFile('user_image')){

                $image = $request->file('user_image');
                $path = $this->openToPublic.'/'.$this->photoDirectory.'/'.$request->input('email').'.'.$image->extension();
                $resized = Image::make($image)->resize(113,151)->stream($image->extension());
                Storage::disk($this->storage)->put($path,$resized,$this->openToPublic);
                $input['user_image'] =  str_replace_first('public/','',$path);
            }

```
Version :   "laravel/framework": "5.5.*"
"phpunit/phpunit": "~6.0",

**Comment by driesvints** [comment] 2018-11-20 13:41
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Closed by driesvints** 2018-11-20 13:41 UTC

**Comment by JeffreyDavidson** [comment] 2019-04-24 22:16
If anyone comes across this issue, the problem is because in the submitted's code above he is passing the values of the post params as the second argument to the post route when he should have closed out the route helper `)` and then had the values as the second parameter of the request.
