### ISSUE TITLE
getDirty() does not handle bools right with casts set

### ISSUE THREAD

**Issue by afraca** [laravel/framework#15459] opened 2016-09-16 07:38 UTC
- Laravel Version:  5.1 / 5.2 / 5.3
- PHP Version: 7.0
- Database Driver & Version: mysql 5.7

### Description:
When a model has a boolean field that's stored as tinyint in database, one can specify this in the casts column as 'boolean'. When setting the value to `true` or `false` in the code, the attribute gets viewed as `dirty` incorrectly.

### Steps To Reproduce:
Create a model with a boolean attribute, in the table stored as TINYINT. 
In the `casts` property specify the attribute as `boolean`.
Retrieve an instance from the database, then set it to the SAME value with code
assert that `getDirty()` shows the attribute as dirty.

### Why:
`$original` gets filled with 0/1 . But when setting, `$attributes` holds true/false. Here we see how this is ignored:
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L3180

**Comment by afraca** [comment] 2016-09-16 07:39
This is very similar to a previous bug report I made, and shows how the `casts` is completely ignored in the dirty handling:

https://github.com/laravel/framework/issues/15060

**Comment by GrahamCampbell** [comment] 2016-09-16 07:59
Closing since dupe of #15060. Thanks though.

**Closed by GrahamCampbell** 2016-09-16 07:59 UTC
