### ISSUE TITLE
[v8.52.0] Invalid JSON was returned from the route.

### ISSUE THREAD

**Issue by kocoten1992** [laravel/framework#38178] opened 2021-07-29 21:54 UTC
- Laravel Version: v8.52.0
- PHP Version: PHP 8.0.8
- Database Driver & Version: not relevant

### Description:
This code work on v8.51.0, but fail on v8.52.0

### Steps To Reproduce:

On any controller:
```php
return response()->json(false);
```
On testing:
```php
$response = $this->get('/');
  
$response->assertStatus(200);
```

```
# v8.51.0
   PASS  Tests\Feature\ExampleTest
  ✓ example

  Tests:  2 passed
  Time:   0.10s

```

```
# v8.52.0
   FAIL  Tests\Feature\ExampleTest
  ⨯ example

  ---

  • Tests\Feature\ExampleTest > example
  Invalid JSON was returned from the route.

  at tests/Feature/ExampleTest.php:19
     15▕     public function test_example()
     16▕     {
     17▕         $response = $this->get('/');
     18▕ 
  ➜  19▕         $response->assertStatus(200);
     20▕     }
     21▕ }
     22▕ 
```

**Comment by derekmd** [comment] 2021-07-29 23:51
## Laravel currently can't make assertions on `response()->json(false)`

Your example shows an edge case gap in `Illuminate/Testing/TestResponse`'s ability to make assertions on `response()->json(false)`.

Running the below 3 tests with v8.51.0, the top 2 pass but the last case fails:

```php
public function testResponseJsonNull()
{
    \Illuminate\Support\Facades\Route::get(
        '/json-null',
        fn () => response()->json(null)
    );

    $response = $this->get('/json-null');
    $this->assertSame('{}', $response->content()); // passes
    dump($response->json()); // prints []
    $response->assertStatus(200); // passes
}

public function testResponseJsonTrue()
{
    \Illuminate\Support\Facades\Route::get(
        '/json-true',
        fn () => response()->json(true)
    );

    $response = $this->get('/json-true');
    $this->assertSame('true', $response->content()); // passes
    dump($response->json()); // prints true
    $response->assertStatus(200); // passes
}

public function testResponseJsonFalse()
{
    \Illuminate\Support\Facades\Route::get(
        '/json-false',
        fn () => response()->json(false)
    );

    $response = $this->get('/json-false');
    $this->assertSame('false', $response->content()); // passes
    dump($response->json()); // throws PHPUnit::fail('Invalid JSON was returned from the route.')
    $response->assertStatus(200); // assertion not reached
}
```

This is caused by the error checking in `Illuminate/Testing/TestResponse@decodeResponseJson()`:

https://github.com/laravel/framework/blob/7bd4e6dc547526d072374eb4846e31369987d66f/src/Illuminate/Testing/TestResponse.php#L851

The `$decodedResponse === false` expression is checking for `Illuminate\Testing\AssertableJsonString`'s constructor assigning `false` to property `AssertableJsonString@decoded` because `json_decode()` failed:

https://github.com/laravel/framework/blob/49ee16b9ee784d425205fa456b43581de7cf804a/src/Illuminate/Testing/AssertableJsonString.php#L45-L47

But in this API response, HTTP response body string `false` is JSON `false` that _should_ be transformed to PHP bool value `false`.

---

## v8.52.0 changes causing the exception

The exception is now occurring because v8.52.0 started showing JSON response validation errors in test output on a status code mismatch. Introduced by https://github.com/laravel/framework/pull/38088, a custom PHPUnit feedback message string is computed when asserting the status code integer match like 200 HTTP OK.

So this new code:

https://github.com/laravel/framework/blob/7bd4e6dc547526d072374eb4846e31369987d66f/src/Illuminate/Testing/TestResponse.php#L194-L200

Is now attempting to decode the response body JSON string on status code assertions before any `assert*Json()` methods are called.

---

## Possible framework code fix

I think the fix would be to add a new `AssertableJsonString` method:


```php
class AssertableJsonString implements ArrayAccess, Countable
{
    // ...
    public function hasInvalidJson()
    {
        return $this->decoded === null || (
            $this->decoded === false && $this->json !== 'false'
        );
    }
}
```

And make `TestResponse@decodeResponseJson()` only throw an exception when that returns true.

**Comment by derekmd** [comment] 2021-07-31 03:46
https://github.com/laravel/framework/compare/8.x...derekmd:assert-status-doesnt-fail-on-json-false?expand=1 will at least fix `assertStatus()` failing.

Before submitting I'll wait on today's https://github.com/laravel/framework/pull/38189 to be merged to avoid Git conflicts.

**Comment by Alilux** [comment] 2021-08-01 01:16
> Illuminate/Testing/TestResponse's

**Closed** 2021-08-01 15:09 UTC
