### ISSUE TITLE
[5.4] Bug in artisan generated controller/model/migration using resource route/binding

### ISSUE THREAD

**Issue by steveheinsch** [laravel/framework#19815] opened 2017-06-29 00:30 UTC
- Laravel Version: 5.4.27
- PHP Version: PHP 7.1.1-1+deb.sury.org~xenial+1 (homestead)
- Database Driver & Version:

### Description:
When creating a model/resourceful controller/migration with `artisan make:model -mrc DoubleWord`, in the created resourceful controller, laravel will create something like: `public function show(DoubleWord $doubleWord)`

However, the (resource) route is automatically passing `{double_word}` to the controller (not $doubleWord), so implicit binding breaks if you try to use $doubleWord. $doubleWord an empty model and not the requested one.

It should be `public function show(DoubleWord $double_word)` and then $double_word is the properly retrieved model (although I'd rather the resource route actually did use the camel-case $doubleWord and passed $doubleWord to the controller)

My route looks like:
`Route::resource('double-word', 'DoubleWordController');`

**Comment by Douglasdc3** [comment] 2017-06-29 21:00
If you look in the `Illuminate\Routing\ResourceRegistrar` you'll find the following code.

```
    /**
     * Format a resource parameter for usage.
     *
     * @param  string  $value
     * @return string
     */
    public function getResourceWildcard($value)
    {
        if (isset($this->parameters[$value])) {
            $value = $this->parameters[$value];
        } elseif (isset(static::$parameterMap[$value])) {
            $value = static::$parameterMap[$value];
        } elseif ($this->parameters === 'singular' || static::$singularParameters) {
            $value = Str::singular($value);
        }

        return str_replace('-', '_', $value);
    }
```

Maybe one of the core contributors could tell what intended logic should be. I guess we could use Str class method to convert value to camelCase.

**Comment by devcircus** [comment] 2017-06-29 23:26
I just did 
```
php artisan make:model InventoryItem -mrc
```
Then set up my routes with
```
Route::resource('inventoryItem', 'InventoryItemController');
```
Then tested the show route with
```
testapp.dev\inventoryItem\1
```
And everything worked as expected.

**Comment by ralphschindler** [comment] 2017-06-30 17:22
I can confirm @devcircus's findings, this works as expected.

**Comment by Douglasdc3** [comment] 2017-06-30 21:52
@steveheinsch I retest your sample code and both $double_word and $doubleWord work inside the controller. tested using latest 5.5 branch and php 7.1.4. Maybe worth waiting or already upgrading to 5.5?

**Comment by lagbox** [comment] 2017-07-14 03:18
@Douglasdc3 The intended logic in regards to what?

**Comment by themsaid** [comment] 2017-08-13 07:35
Closing for being unable to replicate.

**Closed by themsaid** 2017-08-13 07:35 UTC
