### ISSUE TITLE
Artisan::call migrate --database flag changes default connection

### ISSUE THREAD

**Issue by sergiz** [laravel/framework#28253] opened 2019-04-18 11:57 UTC
- Laravel Version: 5.8.12
- PHP Version: 7.2.11
- Database Driver & Version: mysql/sqlite

### Description:
If you use Artisan::call method to make a migration to a database that is not your default, it will change default database connection for the whole application. I would reasonably expect, that the --database flag would only persist for the called artisan command.

### Steps To Reproduce:
```
        logger(DB::getDefaultConnection());
        logger(DB::getDatabaseName());

Artisan::call('migrate', ['--database' => 'sqlite_cache', '--path' => 'some/path/to/migrations']);

        logger(DB::getDefaultConnection());
        logger(DB::getDatabaseName());
```

Before the Artisan::call you will get your default connection details (f.e. mysql), after the Artisan::call you will get sqlite_cache as default connection.

**Comment by driesvints** [comment] 2019-04-18 12:01
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. 

Thanks!

**Comment by Sergzy** [comment] 2019-04-18 13:13
You can put this code in your AppServiceProvider and see it for yourself. Let's say your DB_CONNECTION is set to mysql. After Artisan::call is called, your database connection will be set to sqlite.

```
class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        logger(DB::getDefaultConnection());
        logger(DB::getDatabaseName());
 
        Artisan::call('migrate', ['--database' => 'sqlite']);
 
        logger(DB::getDefaultConnection());
        logger(DB::getDatabaseName());
    }
}
```

You then need to restore your original default with DB::setDefaultConnection(...). I suppose Artisan should do that automatically when --database flag is used.

**Comment by sergiz** [comment] 2019-04-29 18:48
The problem is that when Artisan is running any database related commands, it sets the option passed with'--database' flag as the framework's default connection.

I guess, the solutions here are two:
1) It should remember what connection is actually set as the default, and after finishing with processing the command set it back to the "real" default one.

2) Use the specified connection, without changing the default connection (just like QueryBuilder already does).

**Comment by driesvints** [comment] 2019-04-30 10:02
Hmm, you're correct I believe. Although I've seen quite some issues about this I believe that the connection should be reset once the command has been run. Although this is a bit hard to do since everything's done in a single request.

**Comment by deleugpn** [comment] 2019-05-05 10:22
Last time I tried to fix this issue I sent this PR, but upon better testing I realized it didn't fix it at all. Inside the PR there's a code snippet that I use to avoid this issue.

https://github.com/laravel/framework/pull/24875

**Comment by driesvints** [comment] 2019-06-24 11:05
Since the prs which fixes this have been rejected I'm afraid this is a nofix. Sorry about this.

Please see Taylor's comments here: https://github.com/laravel/framework/pull/28644#issuecomment-498426644

**Comment by crynobone** [comment] 2019-11-25 02:00
> Since the prs which fixes this have been rejected I'm afraid this is a nofix. Sorry about this.

Just to confirm, does Laravel team still consider this a bug or an expected behaviour due to migration limitation. A `nofix` seem to indicate expected behaviour but this still being tagged as `bug`.

**Comment by driesvints** [comment] 2019-11-26 09:22
@crynobone I don't always unlabel issues which I close

**Comment by crynobone** [comment] 2019-11-26 11:19
@driesvints just wondering if Laravel still going to accept a fix to this issue or let it be?

**Comment by driesvints** [comment] 2019-11-26 13:40
@crynobone taylor let me know that we're open to a pr but perhaps it's best that it targets the next major release

**Comment by stancl** [comment] 2019-11-26 21:39
@MattStrauss's implementation of this in #28644 looks pretty solid and has tests.

**Comment by driesvints** [comment] 2019-12-06 16:14
The PR for this got merged and will be available in the next major Laravel release.

**Closed by driesvints** 2019-12-06 16:14 UTC
Labels: bug
