### ISSUE TITLE
Undefined array key 1 on line no 368 of ServeCommand.php

### ISSUE THREAD

**Issue by mrthito** [laravel/framework#53186] opened 2024-10-16 14:24 UTC
### Laravel Version

v11.3.1

### PHP Version

8.3

### Database Driver & Version

MySql

### Description

  ErrorException 

  Undefined array key 1

  at vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:368
```php
        364▕         $line = str_replace('  ', ' ', $line);
        365▕
        366▕         preg_match($regex, $line, $matches);
        367▕
  ➜    368▕         return Carbon::createFromFormat('D M d H:i:s Y', $matches[1]);
        369▕     }
        370▕
        371▕     /**
        372▕      * Get the request port from the given PHP server output.
```

  1.   **vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:368**
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}("Undefined array key 1", "C:\Users\Sushant Krishna\Desktop\Laravel\mvcommerce\vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php")

  2.   **vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:297**
      Illuminate\Foundation\Console\ServeCommand::getDateFromLine("[Wed Oct 16 19:49:25 2024] 127.0.0.1:55960 Accepted")

### Steps To Reproduce

I installed the laravel from laravel installer and serve the application. And this happened

**Comment by crynobone** [comment] 2024-10-16 14:29
Duplicate of https://github.com/laravel/framework/issues/53175#issuecomment-2415323646

**Closed by crynobone** 2024-10-16 14:29 UTC
