### ISSUE TITLE
Artisan migrate is dependent on routing and service providers

### ISSUE THREAD

**Issue by rapliandras** [laravel/framework#25613] opened 2018-09-14 02:37 UTC
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: mariadb latest

### Description:

Artisan migrate shouldn't be dependent upon anything but the schema migrations. 

### Steps To Reproduce:

Create an arbitrary service provider and refer to a model for which the migration is yet to be ran. For example I created a migration for a new `menus` table and had a reference to the model as so:
`View::share("menus",Menu::all());`

Then artisan instantly crashes without giving any hint where the problem occured.

**Comment by sisve** [comment] 2018-09-14 04:53
The problem is that your migrations may depend on something the service provider does, so we need to execute the service provider. Use class-based view composers instead, that would delay they database class until a view is composed, which means there will be no database calls for artisan commands.

**Comment by rapliandras** [comment] 2018-09-14 09:31
While view composers seem to be a better solution in this case, let me share this code extract because I think this behavior is not correct. 

`MenuServiceProvider` is registered in config/app.php providers array.

`CreateModulesTable` is not dependent on anything but Blueprint and the Schema facade. So the problem could be that artisan reads config, sets up the application and runs providers even though it has zero reason to.

Without knowing the internals of artisan, I read many cases that this happens with routing as well. If any of the routes is incorrect, artisan commands can't run. Artisan does some kind of caching on routes and other config, which is not only unnecessary now, but breaks SRP as well. 

`MenuServiceProvider.php`
 
```
class MenuServiceProvider extends ServiceProvider
{
    public function boot()
    {
        View::share("modules", Module::all());
    }
}

```

`CreateModulesTable.php` 

```
class CreateModulesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('modules', function (Blueprint $table) {
            $table->increments('id');
            $table->boolean('is_enabled')->default(0);
            $table->string('name');
            $table->integer('position')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('modules');
    }
}
```

**Comment by sisve** [comment] 2018-09-14 10:17
> CreateModulesTable is not dependent on anything but Blueprint and the Schema facade. So the problem could be that artisan reads config, sets up the application and runs providers even though it has zero reason to.

That configuration contains database credentials. Those providers initiate the database system, and some call the (in my view evil) defaultStringLength setting that affects migrations. And how are you so sure that _my_ migration isn't using other facades? Or how would you know that my providers aren't doing changes to the Blueprint or Schema stuff? Point is that all those things can affect the migration, and Laravel has no way of knowing if that is the case. Thus it initializes and boots the entire application just in case.

> Without knowing the internals of artisan, I read many cases that this happens with routing as well. If any of the routes is incorrect, artisan commands can't run.

This is an implementation detail, the routes are setup by the RouteServiceProvider. A failing provider means the application failed to boot correctly. This is the case for any artisan commands or web requests.

> Artisan does some kind of caching on routes and other config, which is not only unnecessary now, but breaks SRP as well.

Artisan is just the name of the command-line tool/entrypoint that executes registered commands. The `db:migrate` command, for example, is usually registered to the [MigrateCommand class](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Database/Console/Migrations/MigrateCommand.php). The command in turn calls the [Migrator](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Database/Migrations/Migrator.php). There are many parts involved, and just claiming it breaks SRP seems to be as a obvious blanket statement. Would you like to expand on your argument explaining how Artisan breaks SRP?

Your comments about "some kind of caching" is a bit vague. It sounds like you're describing the `config:cache` and `route:cache` commands, but you haven't explained why that is unnecessary. Can you expand on this and provide any arguments on why they are unnecessary?

**Comment by laurencei** [comment] 2018-09-17 23:48
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Closed by laurencei** 2018-09-17 23:48 UTC
