### ISSUE TITLE
[5.4] Local Storage::url() returns incorrect path

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#18395] opened 2017-03-17 15:40 UTC
- Laravel Version: 5.4.15
- PHP Version: 7.1

### Description:

`Storage::url()` does not prepend the disks's root relative to storage to the given path.

### Steps to reproduce:
```php
$path = Storage::url('data.json');
echo $path;
```

#### Expected result:

```
/storage/app/data.json
```

#### Actual result:

```
/storage/data.json
```

I can get the expected result by using the command below, but that seems a bit of a roundabout way of getting there.

```php
str_replace(
    Storage::getAdapter()->applyPathPrefix(''),
    '',
    Storage::getAdapter()->applyPathPrefix('data.json')
);
```

**Comment by lagbox** [comment] 2017-03-18 14:12
The symlink created from storage to public is `storage/app/public` => `public/storage`. So if you try to get a url to something in the base of this, why would you expect it to add `app`? The base is `public/storage` .. which would be `yoursite.com/storage`, not `yoursite.com/storage/app`.

**Comment by CupOfTea696** [comment] 2017-03-20 12:31
Ooh I get it now, it's not supposed to return a path relative to the project root, but rather an actual URL the would be accessible if you made the symlink. 

In that case, I have a question: Is there a way to easily get a file's path relative to the project root, depending on which disk you're using?

**Comment by themsaid** [comment] 2017-03-26 14:48
> path relative to the project root

`/storage/data.json` is the relative public path, that's all you need to get access to the file in the browser.

Using the local driver you know files are stored in `storage/app/public`, you can use this path to find the file on the filesystem.

Closing since it's not a bug report, please ask questions on the forums :) You'll get more replies there.

**Closed by themsaid** 2017-03-26 14:48 UTC
