### ISSUE TITLE
[5.2.24] Redis "WRONGTYPE Operation against a key holding the wrong kind of value"

### ISSUE THREAD

**Issue by j-hibbard** [laravel/framework#12840] opened 2016-03-24 14:41 UTC
Having a strange redis issue that I have narrowed down to only occurring in 5.2.24 and not 5.2.23 on several sites running it.

Essentially my Redis will say "WRONGTYPE Operation against a key holding the wrong kind of value" so long as a certain set of entries exist, the entire site will fail to load.

I am no redis expert but essentially if I delete all keys in a folder formatted like...

RPUSH "sitename:56d99b0eabbae432130125:standard" "sitename:c4cc2edf974ffbce026addb49eed14dd25abed43:product_8687_colors"

The site comes back online, These redis keys seem to reference other redis tags which exist in other redis folders, these problematic tags however, do not have an associated tag.  "c4cc2edf974ffbce026addb49eed14dd25abed43" is nowhere to be found. 

I can reproduce and test this by restoring a backup of this corrupt redis cache and running 5.2.24, I can restore the corrupt redis cache on 5.2.23 and everything works fine and new working keys are created. 

I have had this happen to many sites in a similar way, but this is the first redis keystore I have isolated exactly which keys are problematic. 

Does this perhaps have something to do with recent changes to... https://github.com/laravel/framework/commit/58f4041323245037a599b5814a3c889da1b64f5b

**Comment by GrahamCampbell** [comment] 2016-03-24 14:43
Ping @taylorotwell.

**Comment by GrahamCampbell** [comment] 2016-03-24 14:44
Ping @mstephens.

**Comment by mstephens** [comment] 2016-03-24 16:13
@j-hibbard the key type changes in 5.2.24 and as a result Redis will throw an error, hence a flush of the cache solving this. Can this instruction be added to 5.2.23 > 5.2.24 migrate to flush tags() @taylorotwell?

**Comment by jmfleming** [comment] 2016-03-24 17:14
@mstephens We have seen this error happening when doing nothing BUT flushing a tag.  I.E. 

Cache::tags('layout)->flush();

will produce this error consistently for us.  The only solution was to physically go into Redis and remove them.

**Comment by j-hibbard** [comment] 2016-03-24 17:15
Ah I assumed that might be the case, as a note flush tags within the framework my not work, as flushing tags is part of the problem we are experiencing. 

We have this error occuring when the only action we are calling is to flush the tags to try to start fresh. Unless of course you meant manually issuing the command to redis directly.

As a side note, @mstephens Could this or any of the recent changes possibly impacting "unserialize(): Error at offset 163 of 163 bytes" when calling Redis keys, I'm trying to debug that at the moment, we seem to be having some new redis keys created with lengths that don't match with what is claimed by the key, but not 100% confident in the cause to submit an issue on that yet, but once the bad key is created reverting to .23 and earlier does not solve this issue.

**Comment by themsaid** [comment] 2017-05-25 15:04
Closing since it was caused by an old breaking change so it won't affect applications at the moment.

**Closed by themsaid** 2017-05-25 15:04 UTC
