### ISSUE TITLE
Issue in hasAttributes::castAttribute

### ISSUE THREAD

**Issue by CrixuAMG** [laravel/framework#20731] opened 2017-08-24 14:03 UTC
- Laravel Version: v5.4.30
- PHP Version:7.1
- Database Driver & Version:MYSQL 5.7

### Description:
If I look at line 475 of class `hasAttributes`, I can see some things that are unexpected (for me at least).
`json_decode` uses a string and an optional boolean, but it is never checked what type of value is provided.
This causes some issues, since it should (probably), if it is an array or object, just return the `$value` variable as set in `default`.

There is no validation for variable types here and it should have some at least.

Here is the method, my changes are the (at least for now) commented code.

```
    protected function castAttribute($key, $value)
    {
        if (is_null($value)) {
            return $value;
        }

        switch ($this->getCastType($key)) {
            case 'int':
            case 'integer':
                return (int) $value;
            case 'real':
            case 'float':
            case 'double':
                return (float) $value;
            case 'string':
                return (string) $value;
            case 'bool':
            case 'boolean':
                return (bool) $value;
//            case 'object':
//                return $this->fromJson($value, true);
//            case 'array':
            case 'json':
                return $this->fromJson($value);
            case 'collection':
                return new BaseCollection($this->fromJson($value));
            case 'date':
                return $this->asDate($value);
            case 'datetime':
                return $this->asDateTime($value);
            case 'timestamp':
                return $this->asTimestamp($value);
            default:
                return $value;
        }
    }
```

**Comment by themsaid** [comment] 2017-08-24 18:25
What's the bug you're trying to solve?

**Comment by CrixuAMG** [comment] 2017-08-25 06:44
The issue I have is that when it triggers `return $this->fromJson($value, true);` the `$value` is already an object or array.
It happens after I did a query (using an Eloquent model) and put the data in a transformer. I don't parse/cast anything in between these points.
The value in one of the columns is JSON, like this: `{"en":"hello world"}`, and when I change the `fromJson` method to the following I do see a decoded array.
```
public function fromJson($value, $asObject = false)
    {
        if (!is_string($value)) {
            dd($value);
        }

        return json_decode($value, ! $asObject);
    }

```

**Comment by themsaid** [comment] 2017-08-25 15:22
Can you share some code I can use in a fresh laravel application to replicate the issue? There's no steps to reproduce in your issue report and I find it hard to understand what it is about.

**Comment by CrixuAMG** [comment] 2017-08-25 15:28
For reference, this is the exception full message and stack:
```
[2017-08-24 13:43:20] testing.ERROR: ErrorException: json_decode() expects parameter 1 to be string, array given in /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:653
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'json_decode() e...', '/home/vagrant/d...', 653, Array)
#1 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(653): json_decode(Array, true)
#2 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(479): Illuminate\Database\Eloquent\Model->fromJson(Array)
#3 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(175): Illuminate\Database\Eloquent\Model->castAttribute('unlock_title', Array)
#4 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(95): Illuminate\Database\Eloquent\Model->addCastAttributesToArray(Array, Array)
#5 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(900): Illuminate\Database\Eloquent\Model->attributesToArray()
#6 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(929): Illuminate\Database\Eloquent\Model->toArray()
#7 [internal function]: Illuminate\Database\Eloquent\Model->jsonSerialize()
#8 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(67): json_encode(Array, 0)
#9 /home/vagrant/dev/tricktrack-v2/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\Http\JsonResponse->setData(Array)
#10 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(27): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array, 400, Array)
#11 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(83): Illuminate\Http\JsonResponse->__construct(Array, 400, Array, 0)
#12 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Routing\ResponseFactory->json(Array, 400)
#13 /home/vagrant/dev/tricktrack-v2/app/Providers/ResponseServiceProvider.php(26): Illuminate\Support\Facades\Facade::__callStatic('json', Array)
#14 [internal function]: Illuminate\Routing\ResponseFactory->TrickTrack\Providers\{closure}(Array, 400)
#15 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php(78): call_user_func_array(Object(Closure), Array)
#16 /home/vagrant/dev/tricktrack-v2/app/Exceptions/Handler.php(88): Illuminate\Routing\ResponseFactory->__call('error', Array)
#17 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(82): TrickTrack\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(BadMethodCallException))
#18 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): Illuminate\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(BadMethodCallException))
#19 /home/vagrant/dev/tricktrack-v2/app/Http/Middleware/PermissionMiddleware.php(22): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): TrickTrack\Http\Middleware\PermissionMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure), 'tricks.index')
#21 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /home/vagrant/dev/tricktrack-v2/app/Http/Middleware/OrganisationMiddleware.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): TrickTrack\Http\Middleware\OrganisationMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure), 'trick')
#24 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /home/vagrant/dev/tricktrack-v2/app/Http/Middleware/OrganisationCheckMiddleware.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): TrickTrack\Http\Middleware\OrganisationCheckMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /home/vagrant/dev/tricktrack-v2/app/Http/Middleware/LabelMiddleware.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): TrickTrack\Http\Middleware\LabelMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/vagrant/dev/tricktrack-v2/app/Http/Middleware/LocaleMiddleware.php(39): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): TrickTrack\Http\Middleware\LocaleMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#39 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '120', '1')
#42 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(576): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(535): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#46 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(513): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#47 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#48 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#49 /home/vagrant/dev/tricktrack-v2/vendor/barryvdh/laravel-cors/src/HandleCors.php(36): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /home/vagrant/dev/tricktrack-v2/app/Http/Middleware/EtagMiddleware.php(19): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): TrickTrack\Http\Middleware\EtagMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /home/vagrant/dev/tricktrack-v2/app/Http/Middleware/ContentLengthMiddleware.php(19): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): TrickTrack\Http\Middleware\ContentLengthMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#65 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#68 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#69 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#71 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#72 /home/vagrant/dev/tricktrack-v2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#73 /home/vagrant/dev/tricktrack-v2/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#74 {main}  
```

In here you can see that `json_decode` throws an error because `$value` is a array, instead of a string.

**Comment by themsaid** [comment] 2017-08-25 15:29
Please share steps to reproduce in a fresh laravel application so we understand what the issue is.

**Comment by CrixuAMG** [comment] 2017-08-25 15:34
- Create a table with a title column, type string
- Insert for example `{"en":"Quis labore quos sed minus quia quos"}` (created by the awesome formfiller extension in Chrome :) )
- Retrieve the results in a controller method or in a callback function in your routes file.

**Comment by themsaid** [comment] 2017-08-25 15:35
Retrieve it how? `$model->title`? That's not broken, you get the value. How to reach the broken state?

**Comment by CrixuAMG** [comment] 2017-08-25 16:47
I use a transformer that takes the object and puts some of the data into an array. 
```
return [
  'name' => $obj->name,
  'id' => 2
];
```

Aside from this I have literally no idea what could be causing it.

We've been using JSON encoded data before in our database, but that went alright so far.

The data in the database (I've debugged the query using the `toSql()` method and using in in Sequel Pro) is valid JSON (validated using a JSON formatter).

**Comment by themsaid** [comment] 2017-09-05 11:17
Closing for being unable to replicate, please open a new issue with more clear steps to reproduce.

**Closed by themsaid** 2017-09-05 11:17 UTC
Labels: more info?

**Comment by madrussa** [comment] 2019-05-21 07:36
This bug can easily be reproduced with the following:

TestModel.php
```php
<?php

namespace App\Models;

class TestModel extends AbstractModel
{
    /** @var array */
    protected $casts = [
        'test' => 'array',
    ];

    /** @var array */
    protected $attributes = [
        'test' => ['value' => 'I am a default attribute'],
    ];
}
```

test.php
```php
$test = new TestModel();
var_dump($test);
```

Exception raised
```
In HasAttributes.php line 711:
  json_decode() expects parameter 1 to be string, array given
```

This will always result in an exception because the HasAttributes trait doesn't check what type of value is stored in the attributes before trying to decode it as JSON. This is undesired behaviour as one would expect to be able to store default array values and not have them being cast from a string. To work around this, you would have to store the "test" attribute as a JSON encoded string.

This is still an issue in: Laravel 5.8 / Lumen 5.8 (PHP 7.3.3)

**Comment by mfn** [comment] 2019-05-21 08:20
> This is undesired behaviour as one would expect to be able to store default array values and not have them being cast from a string. To work around this, you would have to store the "test" attribute as a JSON encoded string.

I cannot vouch what is "expected" here but a fact is: all the values in `$attributes` (and `$original` for that matter) are supposed to be in the literal format to be sent to whatever SQL server.

The casting translation only happens on the boundaries, i.e. getter/setter but after that, the native format for SQL has to be there as no further transformation (*) will happen at this state.

And this is a pretty hard implementation fact unlikely to change and we could as well call it "expected" at this point.

So, back to your example, yes, if you set default values that way for JSON fields, they need already to be encoded. Not only for your cast example but also for the database. Using the array there you would not be able to save the model and would get a hard SQL error.

*) maybe not exactly true, there _might_ be done some magic with boolean values, but I can't verify this right now.
