### ISSUE TITLE
ErrorException: DOMDocument::loadHTML(): Empty string supplied as input

### ISSUE THREAD

**Issue by chimit** [laravel/framework#21493] opened 2017-10-02 05:00 UTC
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version:

### Description:
I send emails using markdown and caught a strange problem with rendering. My email template:
```blade
@component('mail::message')
# Email confirmation

Please, confirm your email address by clicking the button below:

{{ env('APP_URL') }}/v1/confirm?token={{ $user->token }}

Thanks,<br>
{{ env('APP_NAME') }}
@endcomponent
```
I get an exception on the server:
```
[2017-10-02 04:09:45] lumen.ERROR: ErrorException: DOMDocument::loadHTML(): Empty string supplied as input in /var/www/test/vendor/tijsverkoyen/css-to-inline-styles/src/CssToInlineStyles.php:113
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'DOMDocument::lo...', '/var/www/testio...', 113, Array)
#1 /var/www/test/vendor/tijsverkoyen/css-to-inline-styles/src/CssToInlineStyles.php(113): DOMDocument->loadHTML('')
#2 /var/www/test/vendor/tijsverkoyen/css-to-inline-styles/src/CssToInlineStyles.php(36): TijsVerkoyen\CssToInlineStyles\CssToInlineStyles->createDomDocumentFromHtml('')
#3 /var/www/test/vendor/illuminate/mail/Markdown.php(65): TijsVerkoyen\CssToInlineStyles\CssToInlineStyles->convert('', '/* Base */\n\nbod...')
#4 /var/www/test/vendor/illuminate/mail/Mailable.php(194): Illuminate\Mail\Markdown->render('emails.email-co...', Array)
#5 /var/www/test/vendor/illuminate/mail/Mailable.php(170): Illuminate\Mail\Mailable->buildMarkdownView()
#6 /var/www/test/vendor/illuminate/mail/Mailable.php(118): Illuminate\Mail\Mailable->buildView()
#7 /var/www/test/vendor/illuminate/mail/Mailer.php(225): Illuminate\Mail\Mailable->send(Object(Illuminate\Mail\Mailer))
#8 /var/www/test/vendor/illuminate/mail/Mailer.php(187): Illuminate\Mail\Mailer->sendMailable(Object(App\Mail\EmailConfirm))
#9 /var/www/test/vendor/illuminate/mail/PendingMail.php(99): Illuminate\Mail\Mailer->send(Object(App\Mail\EmailConfirm))
#10 /var/www/test/app/Http/Controllers/v1/UserController.php(58): Illuminate\Mail\PendingMail->send(Object(App\Mail\EmailConfirm))
#11 [internal function]: App\Http\Controllers\v1\UserController->create(Object(Illuminate\Http\Request))
#12 /var/www/test/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#13 /var/www/test/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /var/www/test/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#15 /var/www/test/vendor/illuminate/container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#16 /var/www/test/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#17 /var/www/test/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#18 /var/www/test/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\v1\UserController), 'create', Array)
#19 /var/www/test/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#20 /var/www/test/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(623): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#21 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/test/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /var/www/test/app/Http/Middleware/AuthMiddleware.php(50): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/test/vendor/illuminate/pipeline/Pipeline.php(148): App\Http\Middleware\AuthMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure), 'client')
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/test/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /var/www/test/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/test/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /var/www/test/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(624): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#30 /var/www/test/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#31 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/test/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /var/www/test/vendor/neomerx/cors-illuminate/src/CorsMiddleware.php(67): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/test/vendor/illuminate/pipeline/Pipeline.php(148): Neomerx\CorsIlluminate\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/test/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 /var/www/test/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/test/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /var/www/test/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#40 /var/www/test/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#41 /var/www/test/public/index.php(28): Laravel\Lumen\Application->run()
#42 {main}  
```
But if I change the URL to a button component the error is gone:
```blade
@component('mail::message')
# Email confirmation

Please, confirm your email address by clicking the button below:

@component('mail::button', ['url' => env('APP_URL') . '/v1/confirm?token=' . $user->token])
Confirm email
@endcomponent

Thanks,<br>
{{ env('APP_NAME') }}
@endcomponent
```

**Comment by sisve** [comment] 2017-10-02 07:49
A quick notice, using `env()` outside the config files will break when you cache your configuration files with `php artisan config:cache`.

**Comment by sakerrr** [comment] 2017-10-05 06:13
+1, I started to get this randomly this morning on our production, cant even identify what seems to be the problem. (works on local tho)

**Comment by themsaid** [comment] 2017-10-20 12:21
Closing since 5.4 is not supported anymore, please upgrade your app and report back if the issue still exists.

**Closed by themsaid** 2017-10-20 12:21 UTC

**Comment by donotnoot** [comment] 2018-10-08 21:35
I just had this with 5.6.39, as soon as the template contained `@component('mail::message)` I got the exact same exception as OP.

It stopped happening after I published the mail assets with `php artisan vendor:publish --tag=laravel-mail`, for some reason.

Hopefully this comment will index well and the next one encountering this won't have to waste a few hours like I just did.

**Comment by delino12** [comment] 2020-02-25 09:39
If you are using markdown as template build, do not include inline styling. But if you're using view you can include inline css styling.

**Comment by coolsam726** [comment] 2020-06-02 09:18
> I just had this with 5.6.39, as soon as the template contained `@component('mail::message)` I got the exact same exception as OP.
> 
> It stopped happening after I published the mail assets with `php artisan vendor:publish --tag=laravel-mail`, for some reason.
> 
> Hopefully this comment will index well and the next one encountering this won't have to waste a few hours like I just did.

Confirmed. When using markdown, laravel uses layouts from the default laravel mail templates which you will have to publish and then customize if you would like to .
