### ISSUE TITLE
Serialization of Closures is not allowed

### ISSUE THREAD

**Issue by nash-smspark** [laravel/framework#23501] opened 2018-03-12 10:16 UTC
- Laravel Version: 5.6
- PHP Version:7.1

### Description:
When laravel tries to serialize an object with closures it throws an exception "Serialization of 'Closure' is not allowed". We need to be able to serialize objects with closures in order to use League Events.

**Comment by browner12** [comment] 2018-03-12 14:10
This is a limitation of PHP. Nothing Laravel can do about it.

**Comment by m1guelpf** [comment] 2018-03-12 14:37
github.com/opis/closure

**Comment by nash-smspark** [comment] 2018-03-12 14:39
It can be done: https://github.com/jeremeamia/super_closure

**Comment by browner12** [comment] 2018-03-12 14:40
don't mind me, just talking out of my ass.

**Comment by cfv1000** [comment] 2018-06-11 16:39
The problem is not that we have an exception, but that we can't really handle it. 
This throws a generic \Exception. 

![image](https://user-images.githubusercontent.com/3073353/41244888-258f0db4-6daf-11e8-9862-c732858599df.png)

Even something as simple as this would be of help, imho. 
I can handle that :)

**Comment by laurencei** [comment] 2018-09-18 01:51
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Closed by laurencei** 2018-09-18 01:51 UTC

**Comment by danrichards** [comment] 2018-10-09 03:55
You can also work around this by using constructor args in your jobs with static callables. A string or a tuple (of strings).

So long as `serialize` in `Illuminate\Queue\Queue::createObjectPayload` doesn't eat it, you should be ok.
