### ISSUE TITLE
[5.3] MemcacheStore toTimestamp issues

### ISSUE THREAD

**Issue by segadora** [laravel/framework#16654] opened 2016-12-05 07:22 UTC
- Laravel Version: 5.3.*
- PHP Version: any
- Database Driver & Version: any

### Description:

Implementing Carbon::now() in MemcacheStore is causing problems in UnitTests when using the dates back in time.

The problem is caused by this commit https://github.com/laravel/framework/commit/c5984af3757e492c6e79cef161169ea09b5b9c7a

### Steps To Reproduce:

```
Carbon::setTestNow(Carbon::create(2014, 1, 1, 12, 0, 0));
Cache::put('banana', 'phone', 10);
var_dump(Cache::get('banana'));
```

The var_dump returns null.

![image](https://cloud.githubusercontent.com/assets/6637534/20876644/cc9a9286-bac3-11e6-9daf-acca51e94572.png)

**Comment by themsaid** [comment] 2016-12-21 18:40
@segadora If you have identified the issue please open a PR with a proposed fix.

**Comment by segadora** [comment] 2016-12-21 20:59
@themsaid I would just reverse his commit, but I dont know the affect on Memcached?

**Comment by themsaid** [comment] 2016-12-21 21:01
We can't simply reverse a 3 month old commit :) Can you please share more details about the issue? why do you think this commit is the cause of the issue?

**Comment by segadora** [comment] 2016-12-21 21:08
Before the commit. The expire was set to a (number * 60) which I think resolved in a timestamp in the future on memcached no matter what test date was set on Carbon

After the patch, it uses Carbon which can be manipulated by Carbon::setTestNow();

If I have a test time in the past, and then says the cache should expire after 10min as exampled:

Carbon Test Date: 2016-01-01 00:00:00
Expire would be set to : 2016-01-01 00:10:00

but the server time is 2016-12-21 22:07:00, so the cache has already expired.

Just as exampled in the image.

Do you understand?

**Comment by segadora** [comment] 2017-01-03 13:50
I will provide a pull request asap.

- Been on vacation.

**Comment by GrahamCampbell** [comment] 2017-01-04 14:05
Thanks for the report. Closing since discussion can now move to the PR. :)

**Closed** 2017-01-04 14:04 UTC
