### ISSUE TITLE
`sortBy` function of Collection will throw error when used with `sort` key

### ISSUE THREAD

**Issue by louis222220** [laravel/framework#40203] opened 2021-12-29 17:11 UTC
- Laravel Version: 8.48.2
- PHP Version: 7.4.26
- Database Driver & Version: mysql  Ver 8.0.27 for macos11.6 on x86_64 (Homebrew)

### Description:

`sortBy` function of Collection can not be used with `sort` key. It will throw `ErrorException`.

Following is the error message:
```
ErrorException

sort() expects parameter 2 to be int, array given

at vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1227
  1223▕
  1224▕                 $result = 0;
  1225▕
  1226▕                 if (is_callable($prop)) {
➜ 1227▕                     $result = $prop($a, $b);
  1228▕                 } else {
  1229▕                     $values = [data_get($a, $prop), data_get($b, $prop)];
  1230▕
  1231▕                     if (! $ascending) {

    +1 vendor frames
2   [internal]:0
    Illuminate\Support\Collection::Illuminate\Support\{closure}(["Taylor Otwell"], ["Abigail Otwell"])

    +2 vendor frames
5   tests/Feature/TmpTest.php:133
    Illuminate\Support\Collection::sortBy()

```

### Steps To Reproduce:

- Instantiate a collection with multiple elements. (The value of collection can be any array.)
- sort it by function `sortBy` with the string `sort`

```php
$sorted = (new Collection([1, 2]))
	->sortBy([
		['sort', 'asc'],
	]);
```

I also tried with latest Laravel version (v8.77.1), and the same error is thrown.

**Comment by cheryllium** [comment] 2021-12-29 19:57
Reproduced and this seems to give a clue as to what is happening... 

```
  sort(): Argument #1 ($array) must be of type array, int given

  at vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1310
    1306▕ 
    1307▕                 $result = 0;
    1308▕ 
    1309▕                 if (is_callable($prop)) {
  ➜ 1310▕                     $result = $prop($a, $b);
    1311▕                 } else {
    1312▕                     $values = [data_get($a, $prop), data_get($b, $prop)];
    1313▕ 
    1314▕                     if (! $ascending) {
```

It's going into this branch because `sort()` is a built-in function and thus callable. So it's trying to call `sort(1, 2)` (assuming 1 and 2 are the elements in the array, like in your example.)

What do you think would be the desired behavior in this case @louis222220 ? I can give this a shot.

**Comment by cheryllium** [comment] 2021-12-29 20:00
Wait, I wonder if it could be fixed by checking if it's a string first? So that if you pass in a user-defined function, it will work, but a string will be treated as a key. That is, what if we changed that conditional to: `if (!is_string($prop) && is_callable($prop)) { ... }`

**Comment by louis222220** [comment] 2021-12-30 02:18
@cheryllium 
Thank you for the reply.

Following is an example modified from [Laravel Docs - Collections](https://laravel.com/docs/8.x/collections#method-sortby) to show my expected behavior.
I would like to sort an array with a column named `sort` and one other column.
And then I found this problem with `sortBy` function.

```php
$collection = collect([
    ['name' => 'Taylor Otwell', 'sort' => 34],
    ['name' => 'Abigail Otwell', 'sort' => 30],
    ['name' => 'Taylor Otwell', 'sort' => 36],
    ['name' => 'Abigail Otwell', 'sort' => 32],
]);

$sorted = $collection->sortBy([
    ['name', 'asc'],
    ['sort', 'desc'],
]);

$sorted->values()->all();

/*
    [
        ['name' => 'Abigail Otwell', 'sort' => 32],
        ['name' => 'Abigail Otwell', 'sort' => 30],
        ['name' => 'Taylor Otwell', 'sort' => 36],
        ['name' => 'Taylor Otwell', 'sort' => 34],
    ]
*/
```

**Comment by driesvints** [comment] 2022-01-03 08:32
The related PR was merged. Thanks

**Closed by driesvints** 2022-01-03 08:32 UTC
