### ISSUE TITLE
Models passed to Artisan::call() are serialized to arrays

### ISSUE THREAD

**Issue by ingria** [laravel/framework#22331] opened 2017-12-06 18:39 UTC
- Laravel Version: 5.5.22
- PHP Version: 7.0.22-0ubuntu0.16.04.1
- Database Driver & Version: -

### Description:

Though it is possible to pass objects to commands from other commands, it is impossible to do when using `Artisan` facade. Not sure if this a bug or a feature.

### Steps To Reproduce:

Imagine this command:
```php
// app/Console/MyCommand.php, AKA mycommand:
dd(gettype($this->argument('input')));
```

This works:
```php
// Fragment from another command, say app/Console/MyAnotherCommand.php
$this->call('mycommand', [
    'input' => MyModel::find(1),
]);

>>> "object"
```
This won't:
```php
// Any place, for example in Tinker:
Artisan::call('mycommand', [
    'input' => MyModel::find(1),
]);

>>> "array"
```

**Comment by ingria** [comment] 2017-12-06 18:43
UPD: this problem occurs only with models, other objects are OK:

```php
$input = new \stdClass;
$input->test = 1;

Artisan::call('mycommand', [
    'input' => $input,
]);

>>> "object"
```

**Comment by sisve** [comment] 2017-12-06 20:52
Here's the offending line:

https://github.com/laravel/framework/blob/90a8fafd6b70d8f059e86010de996c5db6da4c37/src/Illuminate/Console/Application.php#L177

It's sneaky, but Collection->toArray() may also transform the items it contains if they are in turn Arrayable.

https://github.com/laravel/framework/blob/90a8fafd6b70d8f059e86010de996c5db6da4c37/src/Illuminate/Support/Collection.php#L1592-L1597

We would need some way to call Collection::toArray() here without transforming the contained items. Or stop using Collection in Console/Application.php.

**Comment by laurencei** [comment] 2017-12-06 22:41
Artisan commands are generally meant for command based calling though - i.e. so you can fire commands from your command line. Logicially it does not *really* make sense to be trying to pass in objects to them? Just "options", "parameters" etc.

If you want to pass objects to a command - you should be doing it via a Job. You can then run the job from your application - or call it via an Artisan command.

Or worse case - you pass a model reference ID to artisan - and then it retrieves the model itself.

**Comment by ingria** [comment] 2017-12-07 00:26
Actually, I'm firing an `Artisan::call`s from the jobs.

I have to make different sequences of RPC calls, read the output and sometimes handle errors. So it's convenient for me to encapsulate them in Artisan commands – so that I could execute them directly (from the console, passing ID) or asynchronously (with queued job, passing model).

Using reference ID is not a good idea IMO, because every time some command calls another command (`$this->call(...)`), that another command will have to make an additional DB call to restore the model.

**Comment by laurencei** [comment] 2017-12-07 00:37
At the minimum though it's not a bug. It's just a design limitation (but personally I think it is an intended consequence).

So either you can discuss it in https://github.com/laravel/internals as a suggestion and see what other people think, or you could do a PR to the framework and see if Taylor wants to pull it in.

But IMO I dont think qualifies as a bug/issue for the framework as is.

**Comment by ingria** [comment] 2017-12-07 01:47
I think this _is_ a bug, because:

A. `Artisan::call` has unpredictable behaviour (some objects are transformed to arrays, some are not)
B. `Artisan::call` and `$this->call()` are expected to be synonymic, but they are not (`$this->call()` doesn't serialize the model for some reason)

So the possible solution are:

A. Don't serialize models passed to `Artisan::call`
B. Serialize models passed to `$this->call`

**Comment by laurencei** [comment] 2017-12-07 01:49
Is it because Eloquent serializes itself to only a model ID when passed to queues - so when Artisan runs the same effect is applied.

i.e. the issue is in Eloquent - not Artisan?

**Comment by themsaid** [comment] 2017-12-07 07:03
For suggestions and changes please use the https://github.com/laravel/internals repo, we keep this repo for bug reporting only, your issue here might need sometime to be discussed as it seems breaking to me, thus moving it to the internals repo is better.

**Closed by themsaid** 2017-12-07 07:03 UTC
