### ISSUE TITLE
Scheduling: runInBackground always fire onFailure and emailOutputOnFailure methods

### ISSUE THREAD

**Issue by pavelforever** [laravel/framework#30392] opened 2019-10-23 02:37 UTC
- Laravel Version: 6.3
- PHP Version: 7.3.9

### Description:
When I run a schedule with runInBackground parameter it's always fire onFailure and emailOutputOnFailure events though no errors happen. Why?

### Steps To Reproduce:
In routes/console.php
```
Artisan::command('hi', function () {
    echo 'hi';
});
```

In Console/Kernel.php
`$schedule->command('hi')->everyMinute()->emailOutputOnFailure('MY_EMAIL@GMAIL.COM')->runInBackground();`

**Comment by driesvints** [comment] 2019-10-29 10:45
This is a duplicate of https://github.com/laravel/framework/issues/28992

**Closed by driesvints** 2019-10-29 10:45 UTC

**Comment by pavelforever** [comment] 2019-10-29 22:27
maybe it's a duplicate, but the problem still exists

**Comment by driesvints** [comment] 2019-10-31 08:43
@pavelforever you're free to help out by sending in a PR if you can
