### ISSUE TITLE
In API resource, ConditionallyLoadsAttributes::attributes() improperly converts Carbon objects to strings

### ISSUE THREAD

**Issue by hackel** [laravel/framework#26313] opened 2018-10-30 17:59 UTC
- Laravel Version: 5.7.3
- PHP Version: 7.2.10

### Description:
When using `$this->attributes()` in an API resource, it calls `$this->resource->toArray()` which converts Carbon objects to strings using the model's `serializeDate` method instead of Carbon's native `serializeJson` method.  This is not the expected behaviour.  The date serialization format (e.g. for MySQL) is not necessarily what one would want to use for an API response (ISO8601).

Example Resource:
```php
public function toArray($request)
{
    return [
        $this->attributes([
            'created_at',
        ]),
    ];
}
```
This returns `{"created_at":"2018-10-02 05:59:58"}` by default, which doesn't include the timezone so is not suitable for an API response.
```php
public function toArray($request)
{
    return [
        'created_at' => $this->created_at,
    ];
}
```
This returns the correct response: `{"created_at":"2018-10-02T05:59:58Z"}`.

The work-around is easy, but it took me some time debugging to figure out what was going on.
`attributes` is convenient for keeping the resource code clean and not repetitive.  I believe it should return Carbon objects, so that their underlying serializeJson methods can be called instead of making assumptions about the desired format.

**Comment by driesvints** [comment] 2018-11-09 11:52
Don't you just need to serialize the value the way you want in the `toArray` method?

**Comment by LastDragon-ru** [comment] 2018-11-30 06:41
> This is not the expected behaviour. 

This is expected design bug, and there are many closed issue about...

**Comment by driesvints** [comment] 2018-11-30 09:59
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by hackel** [comment] 2018-12-05 01:54
The issue is still very much relevant.  The only solution is to not use the resource attributes method at all.

In case it wasn't clear, the `attributes` method takes an array of field names, so there's no way to customize the format while using it.  With a date field like like 'created_at', instead of returning the Carbon object, it behaves as if you were going to insert it into a database, and returns the Eloquent-serialized date (as defined in the model, defaults to MySQL format without timezone).  That's not the purpose of Resource classes, however.  If it didn't do any conversion and simply returned the Carbon object, Carbon's own `jsonSerialize` method would be called to correctly convert it to a JSON string.

**Comment by kylekatarnls** [comment] 2018-12-13 06:18
Hi @hackel it's the expected behavior and the most relevant way to convert a date in JSON since if you do: `new Date("2018-10-02T05:59:58Z")` you get the equivalent object in JS.

It's not the Eloquent-serialized (no T or Z to insert into the database).

You can choose you own way to convert Carbon object into any JSON-compatible value using `serializeUsing` or `settings`.

See the documentation, it's explained: https://carbon.nesbot.com/docs/#api-json

But I don't understand what you expect.  I guess you realize that the Carbon object cannot be returned in a JSON. JSON can only have plain objects, or primitives, it does not support instances of classes and mostly not PHP classes.

**Comment by kylekatarnls** [comment] 2018-12-13 06:33
Hi @hackel I guess `->attributes()` method is not dedicated to JSON output. There is no particular reason for the method `->toArray` to output JSON-compatible values. You should use `->toJson` instead. And it's what says the doc: https://laravel.com/docs/5.7/eloquent-serialization#serializing-to-json

**Comment by LastDragon-ru** [comment] 2018-12-13 06:52
> You should use ->toJson instead

```php
    public function toJson($options = 0)
    {
        $json = json_encode($this->jsonSerialize(), $options);

        if (JSON_ERROR_NONE !== json_last_error()) {
            throw JsonEncodingException::forModel($this, json_last_error_msg());
        }

        return $json;
    }

    /**
     * Convert the object into something JSON serializable.
     *
     * @return array
     */
    public function jsonSerialize()
    {
        return $this->toArray();
    }
```
🤣

**Comment by kylekatarnls** [comment] 2018-12-13 07:52
@LastDragon-ru I understand your reaction but it's not because `jsonSerialize` calls `toArray` that you can override one or the other indifferently. `toArray`, `jsonSerialize` and `toJson` can all be used in different places, that's why you should override the higher level. Override `toJson` if you want a JSON override not `toArray` because it has a wider impact.

The native `toArray` is:
```php
public function toArray()
{
  return $this->attributes;
}
```

By default, there is no change at all to attributes properties. So @hackel what you should do may simply be:

```php
public function toArray()
{
  return array_only($this->attributes, [
    'created_at',
  ]);
}
```

But if your only concern is about JSON, override `jsonSerialize` instead with this code and let `toArray` unchanged.

**Comment by miklcct** [comment] 2018-12-21 09:58
This is not a bug. You have to code what you would want to be returned as API response if you are not satisfied with the default. For example, on one of the app my company produces, all the clients accept the "2018-10-02 05:59:58" happily and the app is designed to work in a single geographical location only so time zone is not my concern.

**Comment by kylekatarnls** [comment] 2018-12-22 09:38
I agree this is not a bug. Still it can be a considered as a feature request. As both `jsonSerialize` and `toArray` exist, they could both try to guess for each type the best conversion. `toArray` would be a string cast (strval so __toString called on classes), and `jsonSerialize` should try first to detect if the type implement `JsonSerializable`, if so, call `jsonSerialize` on it, else fallback to the string cast, this seems to me like a smarter behavior that could be implemented in a future version of Laravel.

I made a deeper study here: https://github.com/laravel/framework/issues/21703#issuecomment-446921134

I plan to submit this on https://github.com/laravel/ideas soon.

**Comment by driesvints** [comment] 2019-01-21 13:07
I'm closing this as I also agree with the comments above that this isn't a bug. You can overwrite the methods and return whatever you want.

**Comment by kylekatarnls** [comment] 2019-01-21 14:02
Hi @driesvints still you get an inconsistent output since the `jsonSerialize` of Carbon is not called when you `json_encode` a model, it's a bit sad Carbon has a JSON support but it's not called when nested Carbon objects of a model are sent via JSON. So please consider: https://github.com/laravel/ideas/issues/1481

**Comment by driesvints** [comment] 2019-01-21 14:07
@kylekatarnls I think it can be considered but currently don't have the time to deep dive into it. You could always whip up a PR to see if it would get accepted by Taylor.

**Comment by driesvints** [comment] 2019-02-08 15:06
I'm re-opening this to give this some more thought at a later time. I feel like we should get to the bottom of this but currently don't have the time to check into it.

**Comment by kylekatarnls** [comment] 2019-02-08 15:30
Great, please take a look at this other (but very related) topic: https://github.com/laravel/framework/issues/21703#issuecomment-446921134

And this: https://github.com/laravel/ideas/issues/1481

I could make a PR, but I do not want to spend a lot of time if we're not first OK about what to do.

Main expectations to meet IMO:
- By default a Carbon object sent inside a JSON string should be the same as `json_encode($thisCarbonDate)` (means call the `->toJSON` method of Carbon).
- Dy default, a Carbon object dump as string (in SQL query for example) should be the same as `strval($thisCarbonDate)` (`->__toString()`)
- We should be able to customize separately the dateJsonFormat (so `->format($dateJsonFormat)` would be called instead of `->toJSON`) and the dateStringFormat (so `->format($dateStringFormat )` would be called instead of `->__toString`)

**Comment by driesvints** [comment] 2019-12-02 14:39
In Laravel 7, a new default for date serialization will be used: https://github.com/laravel/framework/pull/30715

**Closed by driesvints** 2019-12-02 14:39 UTC
Labels: bug
