### ISSUE TITLE
[5.5] cache::put(key, value) not the same as cache::forever(key, value)

### ISSUE THREAD

**Issue by spaceemotion** [laravel/framework#22138] opened 2017-11-19 18:10 UTC
- Laravel Version: 5.5.21
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.19 (Homestead)

### Description:
Using `Cache::put($key, $value)` is not the same as `Cache::forever($key, $value)`. The value never gets added to the cache if no minutes are set when using the "put" method. The default is set to null, which makes the system ignore the put call. If it helps, I'm using the array driver to test this.

The code responsible to ignore null values is in `Illuminate\Cache\Repository:194`.

### Steps To Reproduce:
0. (Use array cache driver)
1. Use `Cache::put($key, $value)` without any minutes specified
2. Expect object added to cache
3. Use `Cache::forever($key, $value)`
4. See object added to cache

**Comment by GrahamCampbell** [comment] 2017-11-19 23:18
This is known, and the behaviour has been changed in L5.6. :)

**Comment by GrahamCampbell** [comment] 2017-11-19 23:19
Oh, it seems it actually wasn't: https://github.com/laravel/framework/pull/22013. I assumed that was merged.

**Comment by GrahamCampbell** [comment] 2017-11-19 23:20
Ping @taylorotwell. What is the desired behaviour here?

**Comment by themsaid** [comment] 2017-11-22 14:37
The current behaviour is agreed to be the intended behaviour.

**Closed by themsaid** 2017-11-22 14:37 UTC
