### ISSUE TITLE
Eloquent and eager loading relations

### ISSUE THREAD

**Issue by kzweb** [laravel/framework#15169] opened 2016-08-31 06:58 UTC
Something that is often asked is an option or by default when calling a query as "User :: with ('profile') -> get (), 'the relationship' profile 'is present in the main query This is useful to filter out columns. in relationships or commandest for relationships, for example, have a grid which shows the column 'username' the 'users' table and displays 'address' table 'profiles'. In a grid I can sort by alphabetical order and the column 'address' or sort by 'username'.

To get around this, now I do the following:

```php
$query = (new User)
            ->with('profile')
            ->join('profiles', 'profiles.id', '=', 'users.id');
```

Instead of using 'profile.nickname' I use 'profiles.nickname', but the code is ugly, it is repetitive. This is one of many examples. If it were possible to do a sort the relation 'profile' would be better, joining the two tables with leftJoin. This affects mainly the one to one relationship.

A good example of this is the [ActiveRecord Yii2](http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#joining-with-relations) see 'joinWith', uses the interface configuration to create a join, it would be good to have this method in the framework.

**Comment by themsaid** [comment] 2016-09-06 17:52
Using this `User::with('profile')->get()`, you can display the fields as `$user->name` `$user->profile->address`, I wonder what the issue is exactly.

**Comment by kzweb** [comment] 2016-09-07 04:38
Thanks for answering. But the question is not exactly this, I gave an example of use in datagrid, for example, we have to filter fields, for example by date range, to filter a text field, sort by another field, etc...

To have a more streamlined code might have some method as 'joinWith'.

For example:

```php
$users = User::joinWith(['profile' => function($query) {
     $query
           ->where('id', '>', 10);
})->get();
```

The query would be:

```sql
SELECT * FROM `users` LEFT OUTER JOIN `profiles` ON `profiles`.ìd` = `users`.ìd` WHERE  `profiles`.ìd` > 10;
SELECT * FROM `profiles` WHERE `profiles`.ìd` IN (ids) AND `profiles`.`id` > 10;
```

OR

```php
$users = User::joinWith(['profile' => function($query) {
     $query
          ->from('profiles as p')
          ->where('id', '>', 10);
})->get();
```

The query would be:

```sql
SELECT * FROM `users` LEFT OUTER JOIN `profiles` `p` ON `p`.ìd` = `users`.ìd` WHERE  `p`.ìd` > 10;
SELECT * FROM `profiles` WHERE `profiles`.ìd` IN (ids) AND `profiles`.`id` > 10;
```

**Comment by themsaid** [comment] 2016-09-08 04:13
I'd say you can use joins for such case, but feel free to open a PR with the suggested changes when you have time :)

I'll close this since it's not really a bug report, for suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Closed by themsaid** 2016-09-08 04:13 UTC

**Comment by salarmehr** [comment] 2021-07-29 07:31
Afte many years still that very fundamental feature has not found its way into Laravel?
