### ISSUE TITLE
JsonException in registerPsrRequest method - "Control character error, possibly incorrectly encoded."

### ISSUE THREAD

**Issue by marekfri** [laravel/framework#48997] opened 2023-11-13 21:26 UTC
### Laravel Version

10.29.0

### PHP Version

8.1.2

### Description

We have updated laravel/framework to latest stable version and encountered an issue, that originally occurred in version 10.29.0. When communicating with server API, following error occurs:

```
Symfony\Component\HttpFoundation\Exception\JsonException
Could not decode request body.
```
It happens in Illuminate\Routing\RoutingServiceProvider class:

```
protected function registerPsrRequest()
    {
        $this->app->bind(ServerRequestInterface::class, function ($app) {
            if (class_exists(Psr17Factory::class) && class_exists(PsrHttpFactory::class)) {
                $psr17Factory = new Psr17Factory;

                return with((new PsrHttpFactory($psr17Factory, $psr17Factory, $psr17Factory, $psr17Factory))
                    ->createRequest($illuminateRequest = $app->make('request')), fn ($request) => $request->withParsedBody(
                        array_merge($request->getParsedBody() ?? [], $illuminateRequest->getPayload()->all())
                    ));
            }

            throw new BindingResolutionException('Unable to resolve PSR request. Please install the symfony/psr-http-message-bridge and nyholm/psr7 packages.');
        });
    }
```

Functionality was OK until version 10.28.0, but all newer version are causing us this error. The issue is in the getPayload() method, which handles the data as JSON, but in our case it is not a JSON, hence the error. The change originated in this pull request: https://github.com/laravel/framework/pull/48696/files

We haven't found any information in the release notes / migration guide, which could help us fix this issue, so we assume this might be a bug to report. If this is not an error, please advise how to fix this on our side.

Link to Sentry issue: https://crystal-missions.sentry.io/share/issue/5c43f0cf13e34684bf845dec4e123197/

Thank you.

### Steps To Reproduce

We are sending a gziped JSON data to our server API endpoint.

**Comment by crynobone** [comment] 2023-11-14 10:31
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by marekfri** [comment] 2023-11-14 19:16
Hi,

I've created the repository as suggested + created there a single controller with one method, which just tries to decode the gzipped json data from request body.
Link to repo: https://github.com/marekfri/laravel-bug-report

The issue is, I think, that in the _getPayload()_ method, if data from getContent() is not empty, it is always tried to be json_decoded. But I don't think that we can just assume that the data will always be a json string.

Let me know if I can do anything further to help resolve this.

Thank you.

**Comment by timacdonald** [comment] 2023-11-14 21:02
Thanks for reporting this. We made some changes in this area due to some upstream breaking changes.

I’ll investigate this, likely on Monday, and see if we can get it fixed for you.

**Comment by timacdonald** [comment] 2023-11-19 23:32
I've created a fix for this. Thanks for reporting it.

https://github.com/laravel/framework/pull/49047

**Closed by timacdonald** 2023-11-19 23:32 UTC
Labels: needs more info
