### ISSUE TITLE
PostgreSQL model with timestamps crashes on update()

### ISSUE THREAD

**Issue by meijdenmedia** [laravel/framework#29469] opened 2019-08-08 19:40 UTC
- Laravel Version: v5.8.31
- PHP Version: 7.2.11
- Database Driver & Version: PostgreSQL 10.5

### Description:
When I update a model in a namespace the generated query is incorrect which triggers an error. The `"table".` prefix should not be added before the updated_at column.

```
SQLSTATE[42703]: Undefined column: 7 ERROR:  column "table" of relation "table" does not exist
LINE 1: update "s_test"."table" set "column" = $1, "table"."updated_...
                                                   ^ (SQL: update "s_test"."table" set "column" = Changed!, "table"."updated_at" = 2019-08-08 19:32:46 where "id" = 2)
```

### Steps To Reproduce:
I created a small repository so you can test it yourself and see what i've done: https://github.com/meijdenmedia/laravel-updated-at-bug/commits/master it should be really easy to setup in Homestead.

**Comment by driesvints** [comment] 2019-08-08 19:44
Duplicate of https://github.com/laravel/framework/issues/29443

Will be fixed in the next release on Tuesday.

**Closed by driesvints** 2019-08-08 19:44 UTC
