### ISSUE TITLE
WithoutMiddleware doesn't work on global middleware

### ISSUE THREAD

**Issue by nmokkenstorm** [laravel/framework#32384] opened 2020-04-15 10:24 UTC
- Laravel Version: 7.6.1
- PHP Version: 7.3.16
- Database Driver & Version: N/A

### Description:
A recent [commit](https://github.com/laravel/framework/commit/6364f258860c846140675bc34468ab345be8af43) added the option to skip/disable middleware for specific routes, which works for Route Groups and the like, but the [implementation ](https://github.com/laravel/framework/blob/cac4a74cc6613ab4d413a17276334b8d2f4f324c/src/Illuminate/Foundation/Http/Kernel.php#L139) for global middleware doesn't actually check for it yet. I'm willing to look into a fix for this, but wanted to raise an issue first to check if such a fix would be welcome.

### Steps To Reproduce:
Require a Auth middleware for all your routes in the App\Http\Kernel, try to call ->withoutMiddleware on login.

**Comment by driesvints** [comment] 2020-04-16 09:11
I'm not sure if it was intended to skip global middleware. You're free to attempt a pr however.

**Comment by driesvints** [comment] 2020-04-16 09:34
Heya. I'm gonna re-open this as it indeed seems to be expected to work with global middleware as well. Thanks for reporting.

**Comment by nmokkenstorm** [comment] 2020-04-16 09:56
@driesvints , @dsazup thanks for the feedback, I'd love to work on a PR for this tonight, will keep you both in the loop.

**Comment by driesvints** [comment] 2020-04-17 08:26
Closing this as the PR was rejected. Please see the explanation by Taylor here: https://github.com/laravel/framework/pull/32404#issuecomment-614808543

**Closed by driesvints** 2020-04-17 08:26 UTC
Labels: bug

**Comment by matiaslauriti** [comment] 2020-05-05 07:43
@driesvints I am sorry for re opening this issue, but before creating an issue that maybe is not an issue, I would like to quickly as here and depending on your answer, I will create a new issue or not.

I am trying to use `withoutMiddleware` method, but I was not able to use it in any part when declaring a route... I also done a search on `vendor` folder for it and did not find it, except for testing purposes... Can you confirm this is somehow not working anymore if it was before ? (I read the documentation and said to use it straight away, but I am even copying the example and when doing `php artisan route:list` it is giving me a `method not found`)

**Comment by bernardwiesner** [comment] 2021-12-20 06:21
btw you can exclude a global middleware like this inside Kernel.php

`
    public function handle($request)
    {
        if($request->is('/your/route')){
            $index = array_search(SomeMiddleware::class, $this->middleware);
            unset($this->middleware[$index]);
        }
        return parent::handle($request);
    }
`

**Comment by Zephni** [comment] 2025-05-07 19:15
Does anyone know whether  there still no official way to exclude globally added middleware in routes?
