### ISSUE TITLE
Asterisk in email address

### ISSUE THREAD

**Issue by NadsonKT** [laravel/framework#46372] opened 2023-03-06 22:06 UTC
- Laravel Version: v10.1.4
- PHP Version:8.1.15
- Database Driver & Version: Mysql 8.0.27

### Description:
I believe that the bug itself is not in Laravel, but in **PHP** itself!

There is something interesting about the native php email validation function (filter_var, FILTER_VALIDATE_EMAIL), the same is used in Laravel Validation.

### Steps To Reproduce:

```php
<?php
	$email = "**************@gmail.com";
	
	if (filter_var($email, FILTER_VALIDATE_EMAIL)) {
		echo("$email is a valid email address");
	}
?>
```

**Comment by timacdonald** [comment] 2023-03-06 22:24
Closing this one as it is not a bug or issue with Laravel.

**Closed by timacdonald** 2023-03-06 22:24 UTC
