### ISSUE TITLE
Blueprint ->foreign should use db prefix where used to prevent duplicate indexes

### ISSUE THREAD

**Issue by leemason** [laravel/framework#9040] opened 2015-06-03 17:20 UTC
im working on a multi tenant app right now. im not going to go into it all but basically each tenant is a new db connection, which can be on the same db (with different prefix) or different db all together.

problem im having is when running migrations on a tenant AFTER the first tenant on the same db is migrated is get a mysql error becuse its trying to create an index with the same name.

the blueprint class doesnt take the into account which is really dissapointing.

ideally this:

```php
protected function createIndexName($type, array $columns)
	{
		$index = strtolower($this->table.'_'.implode('_', $columns).'_'.$type);

		return str_replace(array('-', '.'), '_', $index);
	}
```

should be this:

```php
protected function createIndexName($type, array $columns)
	{
		$index = strtolower($this->table.'_'.implode('_', $columns).'_'.$type);
                $dbPrefix = $this->someMethodToGetPrefix();
		return $dbPrefix.str_replace(array('-', '.'), '_', $index);
	}
```

i know i can get round it by adding a second parameter to the foreign() method which is what ive had to resort to, but would be nice if this was default.

or change the protected createIndexName method to public so we could just append the prefix to the generated name and keep conventions.

**Comment by lukasgeiter** [comment] 2015-06-03 17:47
I agree, this should totally take the table prefix into account.

**Comment by mvdstam** [comment] 2015-07-27 07:33
Going to resurrect this issue, as this got me into trouble as well.

@GrahamCampbell: thoughts on the matter? I suggest simply prefixing the index with the current DB connection prefix:

```php
protected function createIndexName($type, array $columns)
    {
        $index = strtolower($this->table.'_'.implode('_', $columns).'_'.$type);

        return app('db')->connection()->getTablePrefix() . str_replace(['-', '.'], '_', $index);
    }
```

That should be more than sufficient.

**Comment by fisharebest** [comment] 2015-09-01 12:56
Duplicate of #7889 ?

**Closed** 2015-09-01 14:36 UTC
