### ISSUE TITLE
selectRaw vs whereRaw

### ISSUE THREAD

**Issue by lloy0076** [laravel/framework#16634] opened 2016-12-02 18:52 UTC
- Laravel Version: 5.3.^
- PHP Version: 5.6.27 (but it's not really limited to just 5)
- Database Driver & Version: N/A

### Description:

whereRaw accepts the binding as a non-array but selectRaw doesn't - should this be more consistent?

### Steps To Reproduce:

$thing = 1;
SomeModel::whereRaw('`some_column` = ?', $1)->get();

....works.

$thing = 1;
SomeModel::selectRaw('MATCH(`some_column`) AGAINST (?)', $1)->get();

...gets

 Argument 2 passed to Illuminate\Database\Query\Builder::selectRaw() must be of the type array, string given in /data/var/www/html/shop/vendor/illuminate/database/Query/Builder.php on line 245

...I *think* it's because the type annotation on whereRaw is 'mixed $bindings' but on selectRaw is 'array $bindings).

The addbindings method on the builder seems to check for either an array or string already.

**Comment by KKSzymanowski** [comment] 2016-12-03 18:30
The `whereRaw` method also accepts an array by default, but if `$bindings` is not an array it substitutes is with `[$bindings]` [here](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Query/Builder.php#L656).

I suppose it can be done the same way in the `selectRaw` method.

**Comment by themsaid** [comment] 2016-12-05 13:10
It's a nice feature to have I believe, feel free to open a PR on master since it'll be a breaking change because you'll have to change the method signature.

Closing this since it's not a bug report, for suggestions and feature requests please use the https://github.com/laravel/internals repo.

Thanks buddy :)

**Closed by themsaid** 2016-12-05 13:10 UTC
