### ISSUE TITLE
[5.8]  CacheSchedulingMutex has hardcoded time limit to 3600sec and not released (jobs with onOneServer)

### ISSUE THREAD

**Issue by devbazilio** [laravel/framework#28016] opened 2019-03-26 10:32 UTC
- Laravel Version: 5.8
- PHP Version: 7.2

### Description:
Mutex for jobs, scheduled with attribute `onOneServer` will released only after 3600secs

### Steps To Reproduce:
I setted up in .env
```
QUEUE_CONNECTION=database
CACHE_DRIVER=database
```

In console kernel.php I have a job
```
    class Kernel extends ConsoleKernel
    ...
    protected function schedule(Schedule $schedule)
    {
        $schedule->job(new MyJob)
            ->everyMinute()
            ->withoutOverlapping()
            ->onOneServer();
    }
```
Then I ran `php artisan schedule:run`
```
Running scheduled command: App\Jobs\MyJob
```
Then I ran `php artisan queue:work`
```
[2019-03-26 21:20:45][527] Processing: App\Jobs\MyJob
[2019-03-26 21:20:45][527] Processed:  App\Jobs\MyJob
```
as I see the mutex had not removed from DB as it has hardcoded value of 3600 seconds (https://github.com/illuminate/console/blob/master/Scheduling/CacheSchedulingMutex.php#L45) as timeout
Next calls of `php artisan schedule:run` fails with the error 
```
Skipping command (has already run on another server): App\Jobs\MyJob
```
The mutex needs to be released/removed when job will have finished own work

**Comment by driesvints** [comment] 2019-03-26 12:08
Can you please fill out the issue template?

**Comment by devbazilio** [comment] 2019-03-26 12:18
Updated header, thanks

**Comment by driesvints** [comment] 2019-03-26 13:57
Ok so what "Skipping command" means is that it's not really an error, just an informative message that it's skipping the command because, like it says, it's already run on another server. You can just ignore this message.

**Comment by devbazilio** [comment] 2019-03-26 14:09
right, but it refuses to insert any job within current hour because it considers that the job runs for 1h.
E.g. I can insert three same jobs - at 15, 30 and 45 minute - all next call (after insertion of first job at 15th minute) fails with this error message and actually doesn't added into `jobs` table

**Comment by driesvints** [comment] 2019-03-26 14:43
Ah, I think I understand what you mean. This is indeed something that probably should be looked into. Thanks for reporting!

**Comment by laurencei** [comment] 2019-03-27 10:05
I wrote the `onOneServer()` function - and it is a very specific intended behavior that the mutex remains for an hour. This is because the mutex is coded to the minute the scheduler was called, and is not a mutex for the job itself.

i.e. the mutex for `0900` is different to `0901`

If the mutex was removed immediately after the job runs, then the other servers dont know it was run, and could run the job a second time.

The more likely issue here is that `->withoutOverlapping()` is causing the issue, perhaps because your job is failing or not completing correctly, and that mutex (which is a different mutex) would prevent the job running again.

**Comment by laurencei** [comment] 2019-04-15 07:41
I'm going to close this. As mentioned, the `3600` is intentionally hardcoded, and doesnt describe the issue above. If anyone comes across this and has similar issues, please feel free to give some further information, but the first place to look is your `->withoutOverlapping()` calls.

**Closed by laurencei** 2019-04-15 07:41 UTC
Labels: bug

**Comment by devbazilio** [comment] 2019-04-20 14:15
ok, no problem, I will not use laravel scheduler at all in all projects as all issues are stupidly closed without resolving the problems.

**Comment by laurencei** [comment] 2019-04-20 23:09
What exactly is the issue though? I’ve already explained that the 3600
is intentional.

Have you tried removing withoutOverlapping as I suggested?

We can’t help you if you don’t reply after 20 days.

**Comment by mart-vitaly** [comment] 2020-07-13 18:23
Same problem even without `withoutOverlapping`. It's just the problem of `onOneServer` functionality

I've tried to figure out what is going here step by step 

We have command with `onOneServer` method
`
$schedule->command(DeleteMediaLiveInput::class)
            ->everyFiveMinutes()
            ->onOneServer();
`

The only thing this method do - is set class variable to true
**vendor/laravel/framework/src/Illuminate/Console/Scheduling/Event.php:656**
`
    /**
     * Allow the event to only run on one server for each cron expression.
     *
     * @return $this
     */
    public function onOneServer()
    {
        $this->onOneServer = true;

        return $this;
    }
`

This variable is used only in one place:
**vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php:85**
`
    /**
     * Execute the console command.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @param  \Illuminate\Contracts\Events\Dispatcher  $dispatcher
     * @param  \Illuminate\Contracts\Debug\ExceptionHandler  $handler
     * @return void
     */
    public function handle(Schedule $schedule, Dispatcher $dispatcher, ExceptionHandler $handler)
    {
        $this->schedule = $schedule;
        $this->dispatcher = $dispatcher;
        $this->handler = $handler;

        foreach ($this->schedule->dueEvents($this->laravel) as $event) {
            if (! $event->filtersPass($this->laravel)) {
                $this->dispatcher->dispatch(new ScheduledTaskSkipped($event));

                continue;
            }

            if ($event->onOneServer) {
                $this->runSingleServerEvent($event);
            } else {
                $this->runEvent($event);
            }

            $this->eventsRan = true;
        }

        if (! $this->eventsRan) {
            $this->info('No scheduled commands are ready to run.');
        }
    }
`

In runSingleServerEvent method we have
**vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php:112**
`
    /**
     * Run the given single server event.
     *
     * @param  \Illuminate\Console\Scheduling\Event  $event
     * @return void
     */
    protected function runSingleServerEvent($event)
    {
        if ($this->schedule->serverShouldRun($event, $this->startedAt)) {
            $this->runEvent($event);
        } else {
            $this->line('<info>Skipping command (has already run on another server):</info> '.$event->getSummaryForDisplay());
        }
    }
`

Dive in serverShouldRun:
**vendor/laravel/framework/src/Illuminate/Console/Scheduling/Schedule.php:240**
`
    /**
     * Determine if the server is allowed to run this event.
     *
     * @param  \Illuminate\Console\Scheduling\Event  $event
     * @param  \DateTimeInterface  $time
     * @return bool
     */
    public function serverShouldRun(Event $event, DateTimeInterface $time)
    {
        return $this->schedulingMutex->create($event, $time);
    }
`
`$this->schedulingMutex` is a class  `Illuminate\Console\Scheduling\CacheSchedulingMutex`

Method `create`
vendor/laravel/framework/src/Illuminate/Console/Scheduling/CacheSchedulingMutex.php:35
`
    /**
     * Attempt to obtain a scheduling mutex for the given event.
     *
     * @param  \Illuminate\Console\Scheduling\Event  $event
     * @param  \DateTimeInterface  $time
     * @return bool
     */
    public function create(Event $event, DateTimeInterface $time)
    {
        return $this->cache->store($this->store)->add(
            $event->mutexName().$time->format('Hi'), true, 3600
        );
    }
`

`$this->cache` is actually Cache facade and according Laravel documentation
`
Store If Not Present
The add method will only add the item to the cache if it does not already exist in the cache store. The method will return true if the item is actually added to the cache. Otherwise, the method will return false:
Cache::add('key', 'value', $seconds);
`
And of course next calls of CacheSchedulingMutex::create will return false for the same event in next 3600 seconds

As the result: every time schedules tries to run same command with `onOneServer` method - mutex created in Redis for 3600 second. As we have no any places where this mutex is removed - **Command is blocked on ANY server(including one, that save this mutex) for 1 hour**. It seems like this bug was here from the beginning(when this functionality was added to framework) and Laravel 7.* also has it.

**Comment by mart-vitaly** [comment] 2020-07-13 18:26
Same problem even without `withoutOverlapping`. It's just the problem of `onOneServer` functionality

I've tried to figure out what is going here step by step 

We have command with `onOneServer` method
```
$schedule->command(DeleteMediaLiveInput::class)
            ->everyFiveMinutes()
            ->onOneServer();
```

The only thing this method do - is set class variable to true
**vendor/laravel/framework/src/Illuminate/Console/Scheduling/Event.php:656**
```
    /**
     * Allow the event to only run on one server for each cron expression.
     *
     * @return $this
     */
    public function onOneServer()
    {
        $this->onOneServer = true;

        return $this;
    }
```

This variable is used only in one place:
**vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php:85**
```
    /**
     * Execute the console command.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @param  \Illuminate\Contracts\Events\Dispatcher  $dispatcher
     * @param  \Illuminate\Contracts\Debug\ExceptionHandler  $handler
     * @return void
     */
    public function handle(Schedule $schedule, Dispatcher $dispatcher, ExceptionHandler $handler)
    {
        $this->schedule = $schedule;
        $this->dispatcher = $dispatcher;
        $this->handler = $handler;

        foreach ($this->schedule->dueEvents($this->laravel) as $event) {
            if (! $event->filtersPass($this->laravel)) {
                $this->dispatcher->dispatch(new ScheduledTaskSkipped($event));

                continue;
            }

            if ($event->onOneServer) {
                $this->runSingleServerEvent($event);
            } else {
                $this->runEvent($event);
            }

            $this->eventsRan = true;
        }

        if (! $this->eventsRan) {
            $this->info('No scheduled commands are ready to run.');
        }
    }
```

In runSingleServerEvent method we have
**vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php:112**
```
    /**
     * Run the given single server event.
     *
     * @param  \Illuminate\Console\Scheduling\Event  $event
     * @return void
     */
    protected function runSingleServerEvent($event)
    {
        if ($this->schedule->serverShouldRun($event, $this->startedAt)) {
            $this->runEvent($event);
        } else {
            $this->line('<info>Skipping command (has already run on another server):</info> '.$event->getSummaryForDisplay());
        }
    }
```

Dive in serverShouldRun:
**vendor/laravel/framework/src/Illuminate/Console/Scheduling/Schedule.php:240**
```
    /**
     * Determine if the server is allowed to run this event.
     *
     * @param  \Illuminate\Console\Scheduling\Event  $event
     * @param  \DateTimeInterface  $time
     * @return bool
     */
    public function serverShouldRun(Event $event, DateTimeInterface $time)
    {
        return $this->schedulingMutex->create($event, $time);
    }
```
`$this->schedulingMutex` is a class  `Illuminate\Console\Scheduling\CacheSchedulingMutex`

Method `create`
vendor/laravel/framework/src/Illuminate/Console/Scheduling/CacheSchedulingMutex.php:35
```
    /**
     * Attempt to obtain a scheduling mutex for the given event.
     *
     * @param  \Illuminate\Console\Scheduling\Event  $event
     * @param  \DateTimeInterface  $time
     * @return bool
     */
    public function create(Event $event, DateTimeInterface $time)
    {
        return $this->cache->store($this->store)->add(
            $event->mutexName().$time->format('Hi'), true, 3600
        );
    }
```

`$this->cache` is actually Cache facade and according Laravel documentation
```
Store If Not Present
The add method will only add the item to the cache if it does not already exist in the cache store. The method will return true if the item is actually added to the cache. Otherwise, the method will return false:
Cache::add('key', 'value', $seconds);
```
And of course next calls of CacheSchedulingMutex::create will return false for the same event in next 3600 seconds

As the result: every time schedules tries to run same command with `onOneServer` method - mutex created in Redis for 3600 second. As we have no any places where this mutex is removed - **Command is blocked on ANY server(including one, that save this mutex) for 1 hour**. It seems like this bug was here from the beginning(when this functionality was added to framework) and Laravel 7.* also has it.
