### ISSUE TITLE
Finding batch by ID causes exception: Class __PHP_Incomplete_Class has no unserializer

### ISSUE THREAD

**Issue by bandgeekndb** [laravel/framework#41894] opened 2022-04-08 19:56 UTC
- Laravel Version: 9.7.0
- PHP Version: 8.1.4
- Database Driver & Version: Microsoft SQL Server PHP Driver 5.10

### Description:
When calling Bus::findBatch to find a batch by ID, after upgrading to Laravel 9 and PHP 8.1 (previously Laravel 8 and PHP 7.4), I now get `Class __PHP_Incomplete_Class has no unserializer` when calling `unserialize()` on the DatabaseBatchRepository class.

### Steps To Reproduce:

1. Create a batch
2. Attempt to retrieve the batch by ID using Bus::findBatch()

**Comment by ahmedash95** [comment] 2022-04-10 12:53
have you tried running ‘composer update’? I had the same issue and updating dependencies fixed it

**Comment by driesvints** [comment] 2022-04-11 07:17
Think you'll need to update your dependencies indeed to pull in laravel/serializable-closure.

**Comment by bandgeekndb** [comment] 2022-04-11 15:34
I believe I have the necessary updated dependencies though. I'm running laravel/framework v9.7.0, which includes the laravel/serializable-closure package.

I can confirm this by running composer show laravel/serializable-closure and it tells me I have v1.1.1 installed. I can also confirm the serializable-closure package is installed in my app's vendor directory.

Is there some other dependency that I need to update? Thanks!

**Comment by driesvints** [comment] 2022-04-11 15:36
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by bandgeekndb** [comment] 2022-04-11 17:01
Hi Dries! So, in attempting to reproduce this in a separate repository, I actually found the root cause. When upgrading an app that has batches in the job_batches table, they have references to Illuminate\Queue\SerializableClosure in the options field in the database. This class doesn't exist in L9, and any new batches have references to the new Laravel\SerializableClosure.

Is there any way this can be aliased for backwards compatibility, or will it just be mandatory to flush the batches table when upgrading to Laravel 9?

**Comment by driesvints** [comment] 2022-04-12 15:52
We'll try to check into making this a bit smoother. Unfortunately we cannot give a time frame for this right now. For now, it's best that you clear this table before migrating.

**Comment by bandgeekndb** [comment] 2022-04-12 16:00
Understood, thanks for following up! At this point, I just want to make sure if it's a breaking change, it makes it into docs / upgrade guide so it doesn't surprise anyone else.

**Comment by driesvints** [comment] 2022-05-06 08:21
Hi there, since this is an edge case really and we only have gotten one report for this we're going to close this one now. Thanks for reporting this but right now we don't feel it's wanted to dedicate a lot of time to this. We would accept a note to the upgrade guide though so people know to process all of their batches before upgrading. Thanks

**Closed by driesvints** 2022-05-06 08:21 UTC
Labels: enhancement

**Comment by michael-rubel** [comment] 2022-07-15 14:13
@driesvints Faced the same issue.

**Comment by driesvints** [comment] 2022-07-15 14:15
We're currently not going to invest time into solving this sorry. Please clear your batches before upgrading. 

If you can, a PR is appreciated.
