### ISSUE TITLE
Rate Limit doesn't reset after decay

### ISSUE THREAD

**Issue by chargefield** [laravel/framework#16056] opened 2016-10-22 21:15 UTC
- Laravel Version: 5.3.19
- PHP Version: 7
- Database Driver & Version: MySQL
- Cache Driver: Memcached
### Description:

L5.3.11 to L5.3.19 - Rate limit does not reset after reaching decay. Eventually you get locked out.
L5.3.10 - Works fine!

**Comment by coolynx** [comment] 2016-11-05 21:22
Probably the same issue here.

- laravel/framework (v5.3.22)
- PHP 7.0.11
- Cache Driver: memcached 1.4.15 (the main issue is here)

I'm using plain Laravel Passport (without Vue components) for API that uses throttle middleware.

Here is the story as I understand.

[Rate limiter](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Cache/RateLimiter.php#L36) puts hits in Cache `$key` and uses it every time it hits the API route. 

When it reaches the limit it does two things:

1. Bans a user for some time - creates a new key `$key:lockout` and gives this key a time to live
2. resets the previous key `$key`

When the wait time, that was set in 1., is over, it checks again and [here it fails](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Cache/RateLimiter.php#L38). 😏 

A user gets a nice message that in a negative time or in the past she could use this route but unfortunately can not.

> 23:09:34.094 Server: nginx/1.11.5
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> X-Powered-By: PHP/7.0.11
> Cache-Control: no-cache
> X-RateLimit-Limit: 3
> X-RateLimit-Remaining: 0
> **Retry-After: -1923**
> X-RateLimit-Reset: 1478378251
> phpdebugbar-id: 1fb94283160429e64d94a4b67250af6b
> Date: Sat, 05 Nov 2016 21:09:34 GMT

This Cache key `$key:lockout` is still set, time is over and user is banned or blocked.

Here the story ends. And it never gets cleared. I could not find the place where this key is cleared. I found the [clear()](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Cache/RateLimiter.php#L109) function that could do it, but did not find any place where it is called.

Here is my solution that does the job.

```php
    public function tooManyAttempts($key, $maxAttempts, $decayMinutes = 1)
    {
        if ($this->cache->has($key.':lockout')) {
            // check if the time is not negative (not in the past)
            if ($this->availableIn($key) > 0) {
                // continue to fail if it is positive
                return true;
            } else {
                // if the time is passed then clear the locout key
                $this->cache->forget($key.':lockout');
            }
        }
...
```

If it is from Vue components or somewhere else, then please - provide some HOWTO. 🙇

**Comment by themsaid** [comment] 2016-11-06 09:15
So the latest version where this used to work is `L5.3.10`? `5.3.11` is broken? can you confirm?

**Comment by coolynx** [comment] 2016-11-06 09:24
I reinstalled various Laravel versions and  it started to work on all of them. 👍
I no more can confirm that it does not work.

`laravel/framework (v5.3.10)` - works (resets the time limit)
`laravel/framework (v5.3.11)` - works (resets the time limit)
`laravel/framework (v5.3.22)` - works (resets the time limit)

So, my guess is that I had some kind of cache in local repository that caused it. Sorry. 😊

**Comment by coolynx** [comment] 2016-11-06 09:24
I reinstalled various Laravel versions and  it started to work on all of them. 👍
I no more can confirm that it does not work.

`laravel/framework (v5.3.10)` - works (resets the time limit)
`laravel/framework (v5.3.11)` - works (resets the time limit)
`laravel/framework (v5.3.22)` - works (resets the time limit)

So, my guess is that I had some kind of cache in local repository that caused it. Sorry. 😊

**Comment by coolynx** [comment] 2016-11-06 09:48
@hemsaid yes, I'm using the latest `laravel/framework (v5.3.22)` and tested there.

**Comment by GrahamCampbell** [comment] 2016-11-06 09:55
Not a bug in that change. It's something in the memcached driver. Same issue was reported at https://github.com/GrahamCampbell/Laravel-Throttle/issues/46.

**Comment by GrahamCampbell** [comment] 2016-11-06 09:55
Not a bug in that change. It's something in the memcached driver. Same issue was reported at GrahamCampbell/Laravel-Throttle#46.

**Comment by GrahamCampbell** [comment] 2016-11-06 09:56
Also, something's up with ur system time :P 

![image](https://cloud.githubusercontent.com/assets/2829600/20036694/3d658f58-a407-11e6-8dc9-f5642c9bf78d.png)

**Comment by themsaid** [comment] 2016-11-06 09:58
The issue seems to be related to Memcached because it works as expected using the file & database drivers, I'm trying to figure out what changes were made to the memcached driver between release that might have caused this behaviour and this was the only change:

https://github.com/laravel/framework/pull/15549/files#diff-2264a8010d8f05fa1e9b160c1b9431f4L185

But it shouldn't be breaking, no?

**Comment by coolynx** [comment] 2016-11-06 10:02
@GrahamCampbell it was my report. I just started trying to find some answers and then came here. Since I thought that this was the issue for me, too. 😏 

But now it works fine.

**Comment by themsaid** [comment] 2016-11-07 14:05
Closing the issue then since further testing shows no issues, @chargefield please feel free to ping me if you ever have any updates regarding this issue.

**Closed by themsaid** 2016-11-07 14:05 UTC

**Comment by ursuleacv** [comment] 2018-11-21 17:09
It does happen from time to time

* laravel/framework (v5.4.36)
* PHP 5.6
* File cache

```
Date                    Limit
2018-11-21 10:59:33     239 - reset
2018-11-21 10:58:33     0
2018-11-21 10:58:13     0
2018-11-21 10:57:12     0
2018-11-21 10:56:12     1
2018-11-21 10:55:12     2
2018-11-21 10:54:12     3
2018-11-21 10:53:12     4
2018-11-21 10:52:12     5
2018-11-21 10:51:12     6
2018-11-21 10:50:13     7
...
2018-11-21 06:59:20     239 - first request
```

You can see that limit doesn't get reset for a long period
