### ISSUE TITLE
JSON localization files not working from laravel package

### ISSUE THREAD

**Issue by ahmeddabak** [laravel/framework#19980] opened 2017-07-10 13:54 UTC
- Laravel Version: 5.4.2
- PHP Version: 7.0.10

### Description:

inside my package service provider in the boot method i have loaded my translation files

```
$this->loadTranslationsFrom(__DIR__.'/../resources/lang/', 'ideenkonzept');
```

and when i try to echo a translation ```{{ __('ideenkonzept::URL') }}``` it does not work

sine the namespace is not being extracted from the key and passed to the file Translator->Fileloader

i managed to get it to work by hard coding my namespace in the Fileloader which is wrong todo

```
/vendor/laravel/framework/src/Illuminate/Translation/FileLoader.php
```

```
 public function load($locale, $group, $namespace = null)
    {
        if ($group == '*' && $namespace == '*') {
            // before editing return $this->loadJsonPath($this->path, $locale);
            // the translation file array is saved in $this->hints[namespace]
            // but the name space is not passed to the loader and the loader
            // always return default translation path
            return $this->loadJsonPath($this->hints['ideenkonzept'], $locale);
        }

        if (is_null($namespace) || $namespace == '*') {
            return $this->loadPath($this->path, $locale, $group);
        }

        return $this->loadNamespaced($locale, $group, $namespace);
    }
```

**Comment by themsaid** [comment] 2017-07-19 07:57
Duplicate of https://github.com/laravel/framework/issues/17923

**Closed by themsaid** 2017-07-19 07:57 UTC
