### ISSUE TITLE
Arr::prepend($value) changes array indexes

### ISSUE THREAD

**Issue by topcu** [laravel/framework#14101] opened 2016-06-22 11:49 UTC
id|title|status
----- | ------ | ------
1|Alpha|1
2|Bravo|0
10|Charlie|1

`$items = XModel::where('status', '=', 1)->lists("title",id");`
returns:
```
[
  1 => "Alpha",
  10 => "Charlie"
]
```
while
`$items = XModel::where('status', '=', 1)->lists("title",id")->prepend("Select One");`
```
[
  0 => "Select One",
  1 => "Alpha",
  2 => "Charlie"
]
```
prepend method uses array_unshift - which recreates indexes - if no key is given.
I wonder if this behavior is for a reason?

**Comment by dattz** [comment] 2016-06-26 13:22
I agree. Why are we using `array_unshift` ?
About `array_unshift` from [php.net](http://php.net/manual/en/function.array-unshift.php) :

> All numerical array keys will be modified to start counting from zero while literal keys won't be touched.

**Comment by GrahamCampbell** [comment] 2016-06-26 13:27
This is the correct behaviour. If you are appending to a numerically indexed array, it must be without gaps.

**Comment by GrahamCampbell** [comment] 2016-06-26 13:28
I guess we could consider PRs to 5.3 if you have a different implementation you'd prefer.

**Comment by fhb12345** [comment] 2016-07-04 20:24
First off, IMO you should'nt be using prepend to add a blank option to your select like on the example above. 
Also i can't see any other reason to add an element without a key to an array that has information on it's keys.

---
You could generate an unique key and add it to your array, so there's no need to modify this function since you could do your own implementation and pass the key to the function.

This way we can keep the function as is, IMO it's better for the framework to reindex the array and add an element with the 0 key by default than to add it with a random unique key or anything like that.

**Comment by topcu** [comment] 2016-07-04 22:32
In the scenario above, I'm prepending "Select One" option to resultset to use it in generating selectboxes.
Yes you're right, There are tons of ways accomplishing that like doing it in the view.

But isn't reindexing is acting way over its head for a function called prepend?
Adding element with "0" key sounds ok for me. Not a random key though.
May be using empty string for default $key parameter? That way, programmer will know the outcome before using the function.

**Comment by themsaid** [comment] 2016-09-06 21:25
I guess you can just define a key, having a default key that might override an existing value if seems confusing to me.
Closing since it's not a bug report, but feel free to open a PR in case you have a different form of implementation.

**Closed by themsaid** 2016-09-06 21:25 UTC
