### ISSUE TITLE
Observer priority

### ISSUE THREAD

**Issue by deviouspk** [laravel/framework#26088] opened 2018-10-11 13:17 UTC
As of laravel 5.4 the parameter $priority does not exist on the model::observe() method anymore. 

![image](https://user-images.githubusercontent.com/7100315/46806829-e4940980-cd68-11e8-9365-1c1b61d543df.png)

How do we prioritize observers?

**Comment by bhulsman** [comment] 2018-10-11 13:28
Seems to be intentionally removed, doesn't say why: https://github.com/laravel/framework/pull/17303

**Comment by erdemkeren** [comment] 2018-10-11 13:28
From docs (https://laravel.com/docs/5.4/upgrade):

**Event Priority**

Support for event handler "priorities" has been removed. This undocumented feature typically indicates an abuse of the event feature. Instead, consider using a series of synchronous method calls. Alternatively, you may dispatch a new event from within the handler of another event in order to ensure that a given event's handler fires after an unrelated handler.

**Comment by deviouspk** [comment] 2018-10-11 13:52
Hmm,
I'm writing a generic Schema validator Observer that validates the model before it gets saved to the database (using mongodb so it does not have any predefined schema). 

But in order to do that i need to make sure that the events that the observer triggers will be the last ones to be fired. For example another observer could modify the data first so that the schema suddenly becomes valid. But that wouldn't work when the SchemaValidatorObserver gets executed first.

![image](https://user-images.githubusercontent.com/7100315/46808812-7271f380-cd6d-11e8-904a-e1262ae56bf3.png)


I'm not sure how to implement that with the advice from taylor:

> Event Priority
> 
> Support for event handler "priorities" has been removed. This undocumented feature typically indicates an abuse of the event feature. Instead, consider using a series of synchronous method calls. Alternatively, you may dispatch a new event from within the handler of another event in order to ensure that a given event's handler fires after an unrelated handler.

**Comment by erdemkeren** [comment] 2018-10-11 18:42
Validating model data consistency with observers looks weird to me. If I were you, I would consider trying another way around than observers.

**Comment by deviouspk** [comment] 2018-10-11 18:59
It’s not weird at all. It’s the last place in laravel before data gets written away to the database (apart from overriding eloquent methods).For the project im currently working on it is crucial that no invalid data goes into the database (working with states).

**Comment by mfn** [comment] 2018-10-11 19:33
>  For example another observer could modify the data first so that the schema suddenly becomes valid.

I assume you are in control of all the observers running. In that case, you can make a single observer _for your_ application and use a customized observer within, guaranteeing your execution order.

Or you could override `save()`

Or you could override the the Builders `insert` and `update` methods.

I think eventually you've to come up with your own solution as priorities are not coming back.

**Comment by erdemkeren** [comment] 2018-10-11 19:36
Because of the intentional removal of the feature you were using, I don't want to discuss at length here. 

I understand your perspective. However, in general, events keep track of interesting things happen in unpredictable times like a button click, a timer expiration or a change in file system. Like `$('#button').click()`. But you say that you need to make sure that the events that the observer triggers will be the last ones to be fired. That looks like an abuse to me.

Best wishes!

**Comment by laurencei** [comment] 2018-10-12 01:11
I'll be closing this, as it is clear the feature was intentionally removed from the framework by Taylor and is not a bug.

**Closed by laurencei** 2018-10-12 01:11 UTC
