### ISSUE TITLE
Query Builder making wrong query when using UNION with ->paginate()

### ISSUE THREAD

**Issue by d0minationPT** [laravel/framework#16261] opened 2016-11-04 03:42 UTC
Previous issue was closed #2968 with no actual fix.
In my case I needed to unify two queries of the same table, auction products and non auction products, which are a bit different.
The problem is you get a Cardinality  error when calling paginate after doing some unions which is wrong. This happens because laravel calls the aggregate function, which is not effective in this case, which clears the select etc, what you would like to do is create an aggregate wrapping the query.
This is the solution I found, by changing builder.php -> getCountForPagination();

public function getCountForPagination($columns = ['*'])
    {
        //Change begins here
        if(count($this->unions) < 1){
            $this->backupFieldsForCount();
            $this->aggregate = ['function' => 'count', 'columns' => $this->clearSelectAliases($columns)];
            $results = $this->get()->all();
            $this->aggregate = null;
            $this->restoreFieldsForCount();
        }else{
            $results = $this->newQuery()
                    ->selectRaw("COUNT(*) as aggregate FROM (".$this->toSql().") as aggregate_query")
                    ->mergeBindings($this)
                    ->get()->all();
        }
        //Change ends here
        if (isset($this->groups)) {
            return count($results);
        }

        if (! isset($results[0])) {
            return 0;
        }

        $item = $results[0];

        if (is_object($item)) {
            return (int) $item->aggregate;
        }

        return (int) array_change_key_case((array) $item)['aggregate'];
    }

Let's see if this is the best solution so we can push this and fix the issue with union in query builders.

**Comment by d0minationPT** [comment] 2016-11-04 03:44
``

**Comment by themsaid** [comment] 2016-11-04 16:40
duplicate of https://github.com/laravel/framework/issues/14837

**Closed by themsaid** 2016-11-04 16:40 UTC

**Comment by Sadee** [comment] 2016-12-02 16:08
Is this for Laravel 5.3?

**Comment by d0minationPT** [comment] 2016-12-02 17:14
Yes

**Comment by NullPatrol** [comment] 2017-08-23 22:11
Still an issue

**Comment by Porrapat** [comment] 2018-03-27 08:48
Use this one instead until bug is fixed. 
It's worked for now.
https://itsolutionstuff.com/post/how-to-add-pagination-with-union-in-laravel-4-and-laravel-5

**Comment by 4levels** [comment] 2018-05-24 10:01
Still an issue in latest version.. :-(

**Comment by Porrapat** [comment] 2018-05-24 13:04
https://github.com/kaizer666/LaravelUnionPaginator

**Comment by Mechazawa** [comment] 2018-07-23 10:16
>https://github.com/kaizer666/LaravelUnionPaginator
Sadly this is a workaround not a fix
