### ISSUE TITLE
Cache not being flushed when specified with tags

### ISSUE THREAD

**Issue by mstephens** [laravel/framework#11676] opened 2016-01-04 16:49 UTC
Hi guys

When creating cache defined with tags they are being stored correctly, however, when flushing they are simply ignored and remain in cache storage. For example:

    Cache::tags(['hello'])->put('world', 'testing', 10);
    Cache::tags(['hello'])->flush();

I have seen issues related to cache events but not to this problem. 

For reference I am using 5.2 and Redis as my cache backend.

Thanks

**Comment by dhardtke** [comment] 2016-01-04 19:15
Possible duplicate of https://github.com/laravel/framework/issues/9967?

**Closed** 2016-01-04 21:54 UTC
