### ISSUE TITLE
Request::getPayload(): Return value must be of type InputBag, ParameterBag returned

### ISSUE THREAD

**Issue by Gummibeer** [laravel/framework#47834] opened 2023-07-25 15:26 UTC
### Laravel Version

10.16.0

### PHP Version

8.1.19

### Description

> Symfony\Component\HttpFoundation\Request::getPayload(): Return value must be of type Symfony\Component\HttpFoundation\InputBag, Symfony\Component\HttpFoundation\ParameterBag returned

This error now occurs as soon as Laravel tries to handle any JSON request. This seems to be based on the new `symfony/psr-http-message-bridge` v2.3.0 release.

But originally it seems like a far longer problem just never detected. With Symfony 6 types were added - so also to the `Symfony\Component\HttpFoundation\Request::getPayload()` method. But for Laravel 9 the payload of JSON requests was filled into a `ParameterBag`. All places not checking for explicit type won't have any problem as these classes have nearly identical APIs. 

* https://github.com/symfony/psr-http-message-bridge/pull/117
* https://github.com/laravel/framework/blob/55ccc3a9579f8f58435ec391c38b0a9fc78bb89e/src/Illuminate/Http/Request.php#L489-L491
* https://github.com/laravel/framework/pull/37921
* https://github.com/symfony/symfony/blob/86c41bb42594e59bfec16df29e0829eb7e850431/src/Symfony/Component/HttpFoundation/Request.php#L1514

### Steps To Reproduce

Send a JSON request to the server with `"symfony/psr-http-message-bridge": "2.3.0"` installed.

**Comment by Gummibeer** [comment] 2023-07-25 15:28
PS: it could be that the [sentry/sentry-laravel](https://github.com/getsentry/sentry-laravel) is needed as well as that resolves the PSR request.

**Comment by deonthomasgy** [comment] 2023-07-25 15:56
this change break laravel, https://github.com/symfony/http-foundation/commit/76002b1213314cb1f123f67eee2e8ddfe6b53997

**Comment by yusufalper** [comment] 2023-07-25 16:07
same error here, after 10.16 update.

**Comment by deonthomasgy** [comment] 2023-07-25 16:12
quick workaround. add to composer.json
under require:
"symfony/http-foundation": "6.2",

**Comment by looksystems** [comment] 2023-07-25 16:43
same error, again, after 10.16 update.

**Comment by Ben-Gallienne** [comment] 2023-07-25 16:45
Can confirm this is happening for us too.

**Comment by LeVadim** [comment] 2023-07-25 19:20
Same error, confirming that downgrading had helped
"symfony/http-foundation": "6.2",
Thank you

**Comment by wilsenhc** [comment] 2023-07-25 19:40
Same error here, the downgrade to `"symfony/http-foundation": "6.2"` fixed it

**Comment by ericksonlargura** [comment] 2023-07-25 20:16
Same error, fixed with ```"symfony/http-foundation": "6.2"```

**Comment by relaypilot** [comment] 2023-07-25 21:55
Temporary fix for me was to require `"symfony/http-foundation": "^6.2.0",`

But also downgrading the recent Laravel updates:

```
  - Downgrade laravel/framework (v10.16.0 => v10.15.0)
  - Downgrade laravel/horizon (v5.19.0 => v5.18.0)
  - Downgrade laravel/jetstream (v3.2.5 => v3.2.4)
  - Downgrade laravel/serializable-closure (v1.3.1 => v1.3.0)
  - Downgrade symfony/psr-http-message-bridge (v2.3.0 => v2.2.0)
```

**Comment by timacdonald** [comment] 2023-07-25 23:35
Could someone please provide the minimal steps to reproduce this?

I've created a fresh install with breeze, installed `symfony/psr-http-message-bridge` and `sentry/sentry-laravel` and another bridge, but been unable to reproduce this error.

Also, on first glace this looks like a Symfony issue rather than a Laravel issue?

**Comment by prattcmp** [comment] 2023-07-26 00:04
I don't have minimal steps, but here is a full stack trace:

```
Symfony\Component\HttpFoundation\Request::getPayload(): Return value must be of type Symfony\Component\HttpFoundation\InputBag, Symfony\Component\HttpFoundation\ParameterBag returned {"exception":"[object] (TypeError(code: 0): Symfony\\Component\\HttpFoundation\\Request::getPayload(): Return value must be of type Symfony\\Component\\HttpFoundation\\InputBag, Symfony\\Component\\HttpFoundation\\ParameterBag returned at /var/www/html/vendor/symfony/http-foundation/Request.php:1517)
[stacktrace]
#0 /var/www/html/vendor/symfony/psr-http-message-bridge/Factory/PsrHttpFactory.php(84): Symfony\\Component\\HttpFoundation\\Request->getPayload()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(141): Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory->createRequest(Object(Illuminate\\Http\\Request))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Illuminate\\Routing\\RoutingServiceProvider->Illuminate\\Routing\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build(Object(Closure))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(933): Illuminate\\Container\\Container->resolve('Psr\\\\Http\\\\Messag...', Array, true)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve('Psr\\\\Http\\\\Messag...', Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(918): Illuminate\\Container\\Container->make('Psr\\\\Http\\\\Messag...', Array)
#7 /var/www/html/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestMiddleware.php(36): Illuminate\\Foundation\\Application->make('Psr\\\\Http\\\\Messag...')
#8 /var/www/html/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestMiddleware.php(23): Sentry\\Laravel\\Http\\SetRequestMiddleware->resolvePsrRequest(Object(Illuminate\\Foundation\\Application))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Sentry\\Laravel\\Http\\SetRequestMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /var/www/html/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Middleware.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Sentry\\Laravel\\Tracing\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#29 /var/www/html/vendor/laravel/octane/src/ApplicationGateway.php(37): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#30 /var/www/html/vendor/laravel/octane/src/Worker.php(92): Laravel\\Octane\\ApplicationGateway->handle(Object(Illuminate\\Http\\Request))
#31 /var/www/html/vendor/laravel/octane/bin/swoole-server(124): Laravel\\Octane\\Worker->handle(Object(Illuminate\\Http\\Request), Object(Laravel\\Octane\\RequestContext))
#32 [internal function]: {closure}(Object(Swoole\\Http\\Request), Object(Swoole\\Http\\Response))
#33 /var/www/html/vendor/laravel/octane/bin/swoole-server(170): Swoole\\Server->start()
#34 {main}
"} 
```

**Comment by prattcmp** [comment] 2023-07-26 00:11
I can't repro when I use `artisan serve`. Is it related to Octane/Swoole?

**Comment by jkuster** [comment] 2023-07-26 00:23
> Could someone please provide the minimal steps to reproduce this?
> 
> I've created a fresh install with breeze, installed `symfony/psr-http-message-bridge` but been unable to reproduce this error.
> 
> Sending a request with `Content-type: application/json` and a JSON body and then calling `request()->all()` to have the JSON parsed.
> 
> Also, on first glace this looks like a Symfony issue rather than a Laravel issue?

I don't have minimal steps, but I noticed it on a POST request trying to authenticate with a YubiKey using laravel-webauthn. Also on Laravel 9.

**Comment by cosmastech** [comment] 2023-07-26 00:27
> Also, on first glace this looks like a Symfony issue rather than a Laravel issue?

I looked at this earlier to submit a PR, and wasn't sure how this would be resolved. It seemed to me (with minimal digging) that Symfony should return the parent class from getPayload() like you have suggested.

The other thought I had was to override the getPayload() method in Illuminate's Request class.

**Comment by timacdonald** [comment] 2023-07-26 00:30
I've managed to replicate. Still investigating.

**Comment by timacdonald** [comment] 2023-07-26 00:35
I've found the issue. Putting together a PR to fix the issue.

**Comment by wilsenhc** [comment] 2023-07-26 00:38
Thanks for the hard work @timacdonald 👏🏼

**Comment by timacdonald** [comment] 2023-07-26 00:52
See: https://github.com/laravel/framework/pull/47838

Would love someone to make this small change locally and confirm the fix gets you out of trouble.

**Comment by jkuster** [comment] 2023-07-26 00:59
I made the change on 9.x and it fixed my issue with webauthn.

**Comment by timacdonald** [comment] 2023-07-26 01:00
Thank you, @jkuster

**Closed** 2023-07-26 03:12 UTC

**Comment by vaites** [comment] 2023-07-26 06:25
@timacdonald, @taylorotwell this bug will be fixed for 9.x branch?

**Comment by timacdonald** [comment] 2023-07-26 07:10
See: https://github.com/laravel/framework/pull/47840

**Comment by emielmolenaar** [comment] 2023-07-26 14:47
Thanks for the quick fixes! 👍🏻
