### ISSUE TITLE
Test using `$this->mock(Request::class)` always returning empty GET request

### ISSUE THREAD

**Issue by trovster** [laravel/framework#37789] opened 2021-06-23 15:05 UTC
- Laravel Version: 8.48.1
- PHP Version: 7.4.13

### Description:

In a Unit test for a Controller I mocked the request using the following;

```php
$request = $this->mock(Request::class, static function (MockInterface $mock) use ($valid): void {
    $mock->shouldReceive('validated')->once()->andReturn($valid);
});
```

Which gave a valid result until updating Laravel from 8.47 to 8.48.

It seems that the introduction of the `singletonInstance` in the commit [bind mock instances as singletons so they are not overwritten ](https://github.com/laravel/framework/commit/8debb3b34fac26085496dc5a32aad1950a8b3510) and the use of that in the `mock()`, `partialMock()` and `spy()` methods of the `InteractsWithContainer` trait. This seems to mean that an empty `GET` request is always used.

I have been able to resolve my failing tests by going back to the [longer version of the code to mock an object](https://laravel.com/docs/8.x/mocking#mocking-objects), as found in the documentation.

```php
$request = $this->instance(
    Request::class,
    Mockery::mock(Request::class, static function (MockInterface $mock) use ($valid): void {
        $mock->shouldReceive('validated')->once()->andReturn($valid);
    })
);
```

### Steps To Reproduce:

```php
$request = $this->mock(Request::class, static function (MockInterface $mock) use ($valid): void {
    $mock->shouldReceive('validated')->once()->andReturn($valid);
});
```

returns different `$request` compared to 

```php
$request = $this->instance(
    Request::class,
    Mockery::mock(Request::class, static function (MockInterface $mock) use ($valid): void {
        $mock->shouldReceive('validated')->once()->andReturn($valid);
    })
);
```

**Comment by driesvints** [comment] 2021-06-24 08:55
This is indeed caused by https://github.com/laravel/framework/pull/37746 which was sent in to address https://github.com/laravel/framework/issues/37706. I can indeed see this being problematic now.

I got a different solution for the mocking problem here: https://github.com/laravel/framework/issues/37706#issuecomment-863938095. But not sure if that's the path we want to go into.

Ping @Nacoma @osteel @donnysim

**Comment by osteel** [comment] 2021-06-24 10:51
@driesvints yeah you'd probably want some sort of abstracted Laravel mock interface instead of wiring the Mockery one to the Laravel container

**Comment by taylorotwell** [comment] 2021-06-24 14:33
Well, I'm a little confused it ever behaved any other way. You mocked request? Why would the framework not use the mock you specified? Is there a reason you are mocking the request at all instead of just making a request using `$this->get()` or `$this->post()`, etc?

**Comment by taylorotwell** [comment] 2021-06-24 14:34
Can you please share your entire test as well as the controller?

**Comment by trovster** [comment] 2021-06-24 14:55
Using `$this->instance(...)` directly continues to work how I expect it to, with the mocked request. I am mocking the request, as I am testing a simple controller in a Unit test, so didn't want to make the full request using `$this->get()`.

When I was investigating this, I was simply getting back an empty GET request. I am guessing this gets setup somewhere, and the singleton then just re-uses whenever you make another `Request` object. This was happening if I also used `Request::create('/example', 'POST', ['key' => 'value'])`.

**Comment by driesvints** [comment] 2021-06-24 14:56
@trovster can you please provide the code to reproduce this?

**Comment by Nacoma** [comment] 2021-06-24 21:51
The issue can be reproduced like so:

```php
$this->app->instance('request', Request::create('/example'));

$this->mock(Request::class, function (MockInterface $mock) {

});

// works
$this->assertInstanceOf(MockInterface::class, resolve(Request::class));
// fails
$this->assertInstanceOf(MockInterface::class, resolve('request'));
```

This version works in both cases:

```php
$this->app->instance('request', Request::create('/example'));

$this->mock('request', function (MockInterface $mock) {

});

$this->assertInstanceOf(MockInterface::class, resolve(Request::class)); // works
$this->assertInstanceOf(MockInterface::class, resolve('request'));
```

It appears that when re-binding the new singleton closure that we're not re-binding it for the alias `'request'`.

**Comment by Nacoma** [comment] 2021-06-24 22:03
I'm unsure if this is the correct approach for solving this. However, it does resolve this particular issue - assuming that my reproduction (above) is accurate.

**Comment by taylorotwell** [comment] 2021-06-25 13:22
Will be fixed here: https://github.com/laravel/framework/pull/37810

**Comment by trovster** [comment] 2021-06-28 07:23
@Nacoma that is actually an entirely different bug you have solved. I will write a test case.

**Comment by mpyw** [comment] 2021-06-28 10:40
In contrary v8.48.1 → v8.48.2 breaks my test...

- [Update README.md · mpyw/laravel-cached-database-stickiness@10dc8c7](https://github.com/mpyw/laravel-cached-database-stickiness/runs/2930590198?check_suite_focus=true)
- [laravel-cached-database-stickiness/InitializingTest.php at master · mpyw/laravel-cached-database-stickiness](https://github.com/mpyw/laravel-cached-database-stickiness/blob/10dc8c70f1303b977985a845774eff10ef6b16e9/tests/Feature/InitializingTest.php)

```php
    public function testInitializationForMailables(): void
    {
        $this->mock(Mailer::class)->shouldReceive('send');

        // [7.x] Multiple Mailers Per App
        // https://github.com/laravel/framework/pull/31073
        if (interface_exists(MailerFactory::class)) {
            $this->mock(MailerFactory::class)
                ->shouldReceive('mailer')
                ->andReturn($this->app->make(Mailer::class));
        }

        DB::connection();

        $this->assertFalse($this->getRecordsModifiedViaReflection());

        Mail::send(new GeneralMailable());

        // ...
}
```

**Comment by driesvints** [comment] 2021-06-28 11:46
@mpyw you're misusing that it seems. You need to provide a callback with the assertions so they're bound to the container: https://laravel.com/docs/8.x/mocking#mocking-objects

**Comment by mpyw** [comment] 2021-06-28 12:05
@driesvints In short, the following fix doesn't work.

```php
$this->mock(Mailer::class, function (MockInterface $mock) {
    $mock->shouldReceive('send');
});

// [7.x] Multiple Mailers Per App
// https://github.com/laravel/framework/pull/31073
if (interface_exists(MailerFactory::class)) {
    $this->mock(MailerFactory::class, function (MockInterface $mock) {
        $mock
            ->shouldReceive('mailer')
            ->andReturn($this->app->make(Mailer::class));
    });
}
```

---

As you may know, `Mockery::mock()` has many signature. The following usages are both valid.

- `Mockery::mock(string $class): MockInterface`
- `Mockery::mock(string $class, Closure $mockDefiner): MockInterface`

And `InteractsWithContainer::mock()` implementation looks like this:

```php
protected function singletonInstance($abstract, $instance)
{
    $abstract = $this->app->getAlias($abstract);

    $this->app->singleton($abstract, function () use ($instance) {
        return $instance;
    });

    // Returns second argument. So this returns MockInterface.
    return $instance;
}

protected function mock($abstract, Closure $mock = null)
{
    // This returns also MockInterface.
    return $this->singletonInstance($abstract, Mockery::mock(...array_filter(func_get_args())));
}
```

So my original usage is valid.

**Comment by driesvints** [comment] 2021-06-28 12:19
@mpyw I'm sorry but I still believe you're not correctly using that. Please try a support channel.

**Comment by mpyw** [comment] 2021-06-28 12:22
@Nacoma 

https://github.com/laravel/framework/issues/37789#issuecomment-867982886 

> I'm unsure if this is the correct approach for solving this. However, it does resolve this particular issue - assuming that my reproduction (above) is accurate.

I'll appreciate if you investigate my issue when you have a moment. Thanks

**Comment by trovster** [comment] 2021-06-28 13:22
This is a simple custom Form Request;

```php
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class TestRequest extends FormRequest
{
    public function rules(): array
    {
        return [
            'key' => [
                'required',
                'string',
            ],
        ];
    }
}
```

The following test was run using Laravel **8.47.0**. `php artisan test --group=mock`

```php
<?php

namespace Tests\Unit;

use App\Http\Requests\TestRequest;
use Illuminate\Routing\Controller as BaseController;
use Mockery;
use Mockery\MockInterface;
use Tests\TestCase as BaseTestCase;

/** @group mock */
class MockSingletonTest extends BaseTestCase
{
    /** @test */
    public function usingInstance(): void
    {
        $data = [
            'key' => $this->faker->word,
        ];

        /** @var \App\Http\Requests\TestRequest $request */
        $request = $this->instance(
            TestRequest::class,
            Mockery::mock(TestRequest::class, static function (MockInterface $mock) use ($data): void {
                $mock->shouldReceive('validated')->andReturn($data);
            })
        );

        $controller = $this->controller();
        $response = $this->app->call($controller, [
            $request,
        ]);

        $this->assertSame('8.47.0', $this->app->version());
        $this->assertSame($data, $request->validated());
        $this->assertSame($data, $response);
    }

    /**
     * @test
     * This test throws \Illuminate\Validation\ValidationException
     * It should work the same way as above.
    */
    public function usingPartialMock(): void
    {
        $data = [
            'key' => $this->faker->word,
        ];

        /** @var \App\Http\Requests\TestRequest $request */
        $request = $this->partialMock(
            TestRequest::class,
            static function (MockInterface $mock) use ($data): void {
                $mock->shouldReceive('validated')->andReturn($data);
            }
        );

        $controller = $this->controller();
        $response = $this->app->call($controller, [
            $request,
        ]);

        $this->assertSame('8.47.0', $this->app->version());
        $this->assertSame($data, $request->validated());
        $this->assertSame($data, $response);
    }

    protected function controller(): BaseController
    {
        return new class extends BaseController {
            public function __invoke(TestRequest $request): array
            {
                return $request->validated();
            }
        };
    }
}
```

>    PASS  Tests\Unit\MockSingletonTest
  ✓ using instance
  ✓ using partial mock

>  Tests:  2 passed
  Time:   0.46s

---

I then updated to **Laravel 8.48.2** and re-run the test (changing the version number). `php artisan test --group=mock`

```php
<?php

namespace Tests\Unit;

use App\Http\Requests\TestRequest;
use Illuminate\Routing\Controller as BaseController;
use Mockery;
use Mockery\MockInterface;
use Tests\TestCase as BaseTestCase;

/** @group mock */
class MockSingletonTest extends BaseTestCase
{
    /** @test */
    public function usingInstance(): void
    {
        $data = [
            'key' => $this->faker->word,
        ];

        /** @var \App\Http\Requests\TestRequest $request */
        $request = $this->instance(
            TestRequest::class,
            Mockery::mock(TestRequest::class, static function (MockInterface $mock) use ($data): void {
                $mock->shouldReceive('validated')->andReturn($data);
            })
        );

        $controller = $this->controller();
        $response = $this->app->call($controller, [
            $request,
        ]);

        $this->assertSame('8.48.2', $this->app->version());
        $this->assertSame($data, $request->validated());
        $this->assertSame($data, $response);
    }

    /**
     * @test
     * This test throws \Illuminate\Validation\ValidationException
     * It should work the same way as above.
    */
    public function usingPartialMock(): void
    {
        $data = [
            'key' => $this->faker->word,
        ];

        /** @var \App\Http\Requests\TestRequest $request */
        $request = $this->partialMock(
            TestRequest::class,
            static function (MockInterface $mock) use ($data): void {
                $mock->shouldReceive('validated')->andReturn($data);
            }
        );

        $controller = $this->controller();
        $response = $this->app->call($controller, [
            $request,
        ]);

        $this->assertSame('8.48.2', $this->app->version());
        $this->assertSame($data, $request->validated());
        $this->assertSame($data, $response);
    }

    protected function controller(): BaseController
    {
        return new class extends BaseController {
            public function __invoke(TestRequest $request): array
            {
                return $request->validated();
            }
        };
    }
}
```

>    FAIL  Tests\Unit\MockSingletonTest
  ✓ using instance
  ⨯ using partial mock

>   Tests:  1 failed, 1 passed
  Time:   0.47s

  ---

The error is as below;

```
  • Tests\Unit\MockSingletonTest > using partial mock
   Illuminate\Validation\ValidationException 

  The given data was invalid.

  at vendor/laravel/framework/src/Illuminate/Foundation/Http/FormRequest.php:137
    133▕      * @throws \Illuminate\Validation\ValidationException
    134▕      */
    135▕     protected function failedValidation(Validator $validator)
    136▕     {
  ➜ 137▕         throw (new ValidationException($validator))
    138▕                     ->errorBag($this->errorBag)
    139▕                     ->redirectTo($this->getRedirectUrl());
    140▕     }
    141▕ 

      +16 vendor frames 
  17  tests/Unit/MockSingletonTest.php:60
      Illuminate\Container\Container::call(Object(class@anonymous/tests/Unit/MockSingletonTest.php:70$21b))
```

**Comment by mpyw** [comment] 2021-06-28 14:54
I got it!

- @Nacoma's [fix](https://github.com/laravel/framework/commit/ef420d193308ef86bff5417f16472db79f82b94d) is still correct. 
- We can't mock **drivers delegated by manager's magic methods and macros**.
  - In my previous test, `MailerFactory` was not correctly mocked.

```php
// Without Mocking
Mail::send($mailable);
↓
$mailManager = Mailer::getFacadeRoot();
$mailManager->send($mailable);
↓
$mailManager = Mailer::getFacadeRoot();
$mailManager->__call('send', [$mailable]);
↓
$mailManager = Mailer::getFacadeRoot();
$mailManager->mailer()->send($mailable);
```

```php
// With Mocking
Mail::send($mailable);
↓
$mailManagerMock = Mailer::getFacadeRoot();
$mailManagerMock->send($mailable);
↓
// Mockery can't find `Mailer::send()` method under `MailManager::__call()` delegation.
```

How do we get correct approach (not workarounds) for this problem...? @taylorotwell

**Comment by trovster** [comment] 2021-07-02 08:40
Is this ticket no longer being looked at? I was closed before I provided my test case and the merged code actually solved a different bug/inconsitency.

**Comment by driesvints** [comment] 2021-07-02 09:10
I'll re-open this to have another look.

**Comment by driesvints** [comment] 2021-07-02 16:41
I can't figure it out. I'm just going to send in a PR to revert the PR that's causing this.

**Comment by driesvints** [comment] 2021-07-02 16:48
We're tagging a new release for this.

**Closed** 2021-07-02 16:47 UTC
Labels: bug

**Comment by Nacoma** [comment] 2021-07-06 20:41
@trovster @driesvints 

There are a couple reasons that the example isn't working:

The `call` method attempts to bind parameters using reflection. Because the example is not passing an associative array, the container attempts to create a new `request` instance from the container. The fix for this is to name the arguments to avoid collisions with the container:

```php
$this->app->call($controller, [
    'request' => $request,
]);
```

Tests will pass and the application will be avoiding the container for the purpose of testing.

**IF** this test case is attempting to consider that `FormRequest`s are resolved from the container then we have another issue altogether. While it did work using the `instance` binding method, it's entirely by accident. When a `FormRequest` is resolved from the container naturally, the `FormRequestServiceProvider` is actually where the validation happens. Because the data is not actually bound to the underlying request instance, validation fails. 

The `instance` binding method short circuits the `afterResolving` callbacks. This is not the behavior that would be seen in the application - only under test circumstances where the `FormRequest` is being mocked and bound as an `instance` in userland.

**Comment by driesvints** [comment] 2021-07-08 12:11
Thanks @Nacoma. I'm gonna let this one rest. Anyone can attempt a new PR if they want which isn't breaking.
