### ISSUE TITLE
ForceCreate through relationship

### ISSUE THREAD

**Issue by atoff** [laravel/framework#42273] opened 2022-05-05 14:41 UTC
- Laravel Version: 9.11.0
- PHP Version: 8.1.1
- Database Driver & Version: MySQL 8.0

### Description:
When creating a model through a relationship (e.g. `$book->reviews()->create(['text' => '...'])`), you expect that relation foreign attributes will be populated (in this example, `book_id` should be auto-populated when we create the Review instance through the book instance).

However, when using `forceCreate` instead of `create`, this behaviour does not occur as might be expected (at least by me!). This seems to be due to `create` being implemented for relationships to have this behaviour (https://github.com/laravel/framework/blob/3ec1e4ce0c10f6414b7ef3c4f42dd85cd5102d07/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php), but `forceCreate` is not and as such it gets forwarded to `Builder` where this setting of foreign attributes doesn't occur.

Either this behaviour is intended but misleading, or it has just been missed?

### Steps To Reproduce:

1. Create two models, one with a HasMany/HasOne relation to the other
2. Attempt to `forceCreate` a model through the HasMany/HasOne relation
3. Watch as either the query fails because the foreign id is not nullable, or the foreign id is set to null

MVP showing this behaviour: https://github.com/atoff/laravel-demo-forcecreate - run `php artisan bug:demo`
![image](https://user-images.githubusercontent.com/17804618/166948223-6e263f8d-274f-4feb-b696-b9fa823dfead.png)

**Comment by driesvints** [comment] 2022-05-05 15:03
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by atoff** [comment] 2022-05-05 17:25
@driesvints thanks for checking this out - I've included an MVP at the bottom of the description that was created using the steps you reported - is more required for this?

**Comment by driesvints** [comment] 2022-05-05 18:22
It's easier for me to test this if you can recreate it in a fresh Laravel app

**Comment by atoff** [comment] 2022-05-05 18:47
> It's easier for me to test this if you can recreate it in a fresh Laravel app

Absolutely understand and agree, but I generated that repository with the exact process you provided - it is a fresh laravel repo with only one commit that adds the behaviour I described

**Comment by driesvints** [comment] 2022-05-05 20:47
@atoff  Omg sorry I totally looked that over 🤦🏻‍♂️ I'll try to check into it tomorrow!

**Comment by rodrigopedra** [comment] 2022-05-06 06:44
Hey @driesvints , I agree with @atoff this is unexpected behavior, and I've had some head scratching moments myself due to this unmatched behavior.

So I already sent PR #42280 which adds a `forceCreate` method to the `HasOneOrMany` abstract class.

**Comment by driesvints** [comment] 2022-05-06 14:07
Will be in Tuesday's release. Thanks all.

**Closed by driesvints** 2022-05-06 14:07 UTC
Labels: needs more info
