### ISSUE TITLE
[6.0] - Multiple OS Testing With Travis CI - Windows Symlink

### ISSUE THREAD

**Issue by jspringe** [laravel/framework#29669] opened 2019-08-20 18:44 UTC
- Laravel Version: 6.0
- PHP Version: 7.2+
- Database Driver & Version: (not relevant)

### Description:
Sorry to open this issue again, but I'm hoping to make some final headway here. This has been brought up time and time again across Laravel and PHP.

[Reference Pull Request](https://github.com/laravel/framework/pull/26965)

[Symfony Reference](https://github.com/symfony/symfony/blob/4bffa042719e673a30cb4c9abfed779ec62c5ab9/src/Symfony/Component/Filesystem/Filesystem.php#L315) (mentioned below)

I'm going to quote myself from the reference PR:

> I've been working on getting Travis CI working with a Windows instance (on the 6.0 branch), and this bug is basically a non-starter. Is there any interest in fixing it or having it fixed? (The short term would be a PHP_OS check and skip - I'm also open to a PHP version check as well in case internals ever gives Windows some love).
> 
> To be honest - there are several issues around this set of tests causing problems with Windows testing, but I don't want to waste any more of my time if there is no chance or interest in fixing this. Symlink is basically broken on Windows unless you want to run your application/testsuite as Administrator (or something equally elevated).
> 
> Symfony works around this issue here it seems.

I understand the hesitation with taking ownership of more code that hasn't been written by the team, but maybe having a testsuite across all of the OSes would ease that burden?

Either way the functionality of `symlink` is inconsistent at the very core of PHP (or rather Windows implementation of `symlink` does not fully follow the *nix implementation).

### Steps To Reproduce:
See my Travis CI report [here](https://travis-ci.org/jspringe/framework/jobs/574105831#L449) (Line 449)

EDIT: I understand that I'm not at 100% with the Windows instance (still need to get Redis tests working), but I figured I would address this in the meantime.

**Comment by jspringe** [comment] 2019-08-20 19:10
[Here](https://github.com/jspringe/framework/commit/b458d7af17cfe0d69e8d3480405394f8c3c8f93c) is an example of what I am proposing short term.

**Comment by jspringe** [comment] 2019-08-20 23:05
I'm basically at a point where the only known issues are the issues that dismiss the Windows environment.

Also, there is a MacOS consideration for `pcntl` [here](https://github.com/laravel/framework/blob/83073b93100345691dc0bc1e824a2f020068094a/tests/Filesystem/FilesystemTest.php#L435), but ignored [here](https://github.com/laravel/framework/blob/83073b93100345691dc0bc1e824a2f020068094a/tests/Queue/RedisQueueIntegrationTest.php#L75).

[.travis.yml](https://github.com/jspringe/framework/blob/415338154c5fbf685cc310c2767603902e878ebe/.travis.yml) 

[Windows PHP 7.2 Results](https://travis-ci.org/jspringe/framework/jobs/574596615)

[Windows PHP 7.3 Results](https://travis-ci.org/jspringe/framework/jobs/574596616)

**Comment by driesvints** [comment] 2019-08-22 10:23
Heya, I'm gonna have to close this as a duplicate of https://github.com/laravel/framework/issues/27004

Appreciating all the info though. Maybe cross-post everything on the other issue? Thanks!

**Closed by driesvints** 2019-08-22 10:23 UTC
