### ISSUE TITLE
All attributes instead of explicitly defined ones

### ISSUE THREAD

**Issue by meNESS** [laravel/framework#18911] opened 2017-04-23 11:09 UTC
- Laravel Version: 5.4.19
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.17

### Description:
Model `X` has 3 attributes (`id`, `user_id`, and `stage`), the `stage` column has a default value, so I don't define it explicitly. After a successful insertion, the `$model` variable doesn't have the `stage` attribute! but those explicitly defined (`id` and `user_id`).

### Steps To Reproduce:
```
$model = new X();
$model->user()->associate($user);
$model->save();

dd($model);
```

**Comment by meNESS** [comment] 2017-04-23 11:25
As a workaround, defining default values for attributes:
```php
$attributes = ['stage' => 'pending'];
```
It's good to return all attributes instead of any workarounds.

**Comment by Dylan-DPC** [comment] 2017-04-23 12:47
This is not a bug. Open an issue on the laravel/internals repo (for a proposal)

**Comment by caiquecastro** [comment] 2017-04-23 13:25
Some sgbd have a RETURNING statements on SQL query, but others like MySQL don't. So you would have to query (select) the row again.

I think you could use $user->fresh()

**Comment by meNESS** [comment] 2017-04-23 14:24
@caiquecastro `fresh()` method does what I need, thanks. Why not make a new refresh by default after each insertion?

**Comment by stemis** [comment] 2017-04-23 19:33
@meNESS Because some applications don't want another SELECT query after the INSERT because you may not need the 'fresh' model after insertion. Making less queries is preferred over making more queries, hence why it is not default.

You could however have a Model 'Saved' Event that does a refresh for you, but I didn't test it yet

**Comment by themsaid** [comment] 2017-04-24 13:36
> Because some applications don't want another SELECT query after the INSERT because you may not need the 'fresh' model after insertion

Exactly, it's up to the developer to use the existing instance or fetch a new one from the DB.

Closing then, thanks everyone.

**Closed by themsaid** 2017-04-24 13:36 UTC
