### ISSUE TITLE
[Feature] User Registration event

### ISSUE THREAD

**Issue by lukasoppermann** [laravel/framework#15378] opened 2016-09-09 21:03 UTC
Hey,

I did not find this in the framework files, nor in the docs. I think it could be very useful to add an event when a new user registers. This could for example be used to send a welcome email.

I guess it would simply be `auth.register`.

**Comment by themsaid** [comment] 2016-09-09 21:20
You can add this event in your app easily, not sure if that's something to add to the framework.

Closing this since it's not a bug report, for suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Closed by themsaid** 2016-09-09 21:20 UTC

**Comment by lukasoppermann** [comment] 2016-09-10 06:08
Okay, I will move it to internals, sorry, did not no about this.
