### ISSUE TITLE
Routing: Method whereArray() must be defined as public

### ISSUE THREAD

**Issue by texnikru** [laravel/framework#22408] opened 2017-12-13 11:53 UTC
https://github.com/laravel/framework/blob/242d438700597aa6bdcbc8a21a14fe3a241c91a3/src/Illuminate/Routing/Route.php#L485

Method whereArray() looks like can be used instead of lot where() calls but protected and not used anywhere.

**Comment by 36864** [comment] 2017-12-13 12:19
This repo is for bug tracking. What you're describing is not a bug, so it would be better placed in the laravel/internals repo.

Also, can't you just pass an array into `where()` as it is? The implementation of `parseWhere()` seems to suggest `where()` can work as `whereArray()` just fine.

**Comment by Dylan-DPC** [comment] 2017-12-13 12:19
This repo is for bug tracking. You can open a proposal in the laravel/internals repo

**Comment by GrahamCampbell** [comment] 2017-12-16 10:22
Feel free to send a PR to master, and see if it is merged. :)

**Closed by GrahamCampbell** 2017-12-16 10:22 UTC
