### ISSUE TITLE
Eager loading on polymophic modal's relations

### ISSUE THREAD

**Issue by Jono20201** [laravel/framework#15248] opened 2016-09-02 20:47 UTC
This issue started occurring with release v5.2.40. v5.2.39 and prior work as I expected. I have tested this on v5.3.6 and the issue still persists.

We have a model that has a polymophic relation to two other models. Those two models have relationships of there own, but they are different relationships. In our application we need to eager load these relationships to reduce database queries. Every since changes made in v5.2.40 we have been unable to do this as it is erroring when trying to load the relationships on models where it doesn't exist. Before this the relationship was ignored if it doesn't exist.

I have an example project:

- Cloud9 IDE: https://ide.c9.io/jono20202/polymorphic-example
- GitHub: https://github.com/HireALite/polymorphic-example

I have 4 models:

1. Note, which has a 'creator' relationship which can either go to Staff model, or Customer model.
2. Staff
3. Custom, which has an 'organisation' relationship to an organisation model.

I have a table which shows the note title, and the creator name with their organisation if they're a customer. However, I am unable to solve the N+1 problem because I cannot eager load the organisation relationship.

In v5.2.39 I could do `Note::all()->load(['creator', 'creator.organisation'])`. I couldn't use `with`.
In v5.2.40 I can do neither.

Thanks for reading, hope this is fairly clear.

Stack trace: http://pastebin.com/5TUssxHz

**Comment by themsaid** [comment] 2016-09-02 22:11
You're missing this in your Staff model:

```php
public function organisation()
{
    return $this->belongsTo(Organisation::class);
}
```

**Comment by themsaid** [comment] 2016-09-02 22:21
I think the commit that caused the change in behaviour is from this PR: https://github.com/laravel/framework/pull/14190/files

@acasar to brief you:
The morph relation points to 2 possible models, Customer and Staff, Customer belongs to an organisation but Staff doesn't have an organisation.

Before your PR eager loading this `['creator', 'creator.organisation']` would work on both types of creators (Customer and Staff), but after your PR an exception is thrown since Staff doesn't have a method `organisation`.

Not sure if that change was intended and that this is part of the fix.

**Comment by alkalineb** [comment] 2016-09-02 22:41
@themsaid Thanks for your reply, I'm on the same team and you understand the issue we have perfectly. Looking at it now.

**Comment by acasar** [comment] 2016-09-03 00:03
@themsaid @alkalineb Before that fix, eager loading of polymorphic chained relationships using ``with()`` method or ``$with`` property on the model didn't work at all (as @alkalineb noted as well). But yeah, I didn't account for the case where relationship doesn't exist at all since I presumed it shouldn't work anyway.

Of course we could just fail silently in this case but I'm not sure we want that - we probably should fail if the relationship doesn't exist. The other option is to revert back to the old code, but this fix was also backported to 5.1 so many people are probably already using it.

Not really sure what's the best thing to do in this case.

**Comment by Jono20201** [comment] 2016-09-03 17:44
Could we either add a new method which you could chain onto eloquent chains like ->ignoreMissingRelationships() or pass a second value to the load() and with() methods?

`public function load($relationships, $ignoreMissing = false);`?

Or something like that? Shouldn't break backwards compatibility either.

@taylorotwell - Hope you don't mind me tagging you in, but we would be willing to contribute a PR if we can get clarification on the approach.

**Comment by carlcassar** [comment] 2016-09-21 13:04
@themsaid any updates on this? Any suggestions? We are unable to upgrade to 5.3 until we are able to resolve this issue.

Thank you for your time.

**Comment by taylorotwell** [comment] 2016-09-21 14:34
I really don't think this is a bug. You can't eager load a relationship that doesn't exist.

**Comment by Jono20201** [comment] 2016-09-21 14:50
@taylorotwell,

Thanks for your reply.

I agree that you cannot eager load a relationship that doesn't exist. However, this isn't really what we're asking for in this issue.

What we're looking for is for there to (maybe?) be a flag where you can gracefully ignore missing relationships in cases were the relationship doesn't exist on a polymorphic relationship, but load it if it does exist in another instance.

I think there are some really valid use cases for this type of usage with polymorphic relations. For instance, say that I had two types of users ('customers' and 'staff'). The customer has a relationship of 'organisation' that they belong to. But staff does not (as its not necessary).

Then, say I wanted to have a list of tasks that are 'created_by' (polymorphic) that lists the user that created it and their organisation ONLY IF they are a customer.

Please see the example project. (https://github.com/HireALite/polymorphic-example/blob/master/app/Http/routes.php)

Before v5.2.40 it used to allow and work like this.

Thanks, hope I have explained this well enough.

**Comment by acasar** [comment] 2016-09-21 16:13
@Jono20201 @taylorotwell Another way to solve this issue would be to allow nullable relations. This could be done with this tiny change: https://github.com/acasar/framework/commit/c19470c96eaeb61275e776017e451ec8ce24fc14

That way you could add a nullable relation to your ``Staff`` model making both ``Staff`` and ``Customer`` truly polymorphic (i.e. they would behave the same).

```php
public function organisation()
{
    return null;
}
```

@Jono20201 If @taylorotwell agrees with this change could you prepare a PR with some tests? I tested in your example app and it works, but currently I don't have time to write official tests.

**Comment by Jono20201** [comment] 2016-09-21 16:25
@acasar My only concern is this could be messy on models that don't need this type of relationship?

**Comment by acasar** [comment] 2016-09-21 16:32
I think that if you wish to use different models in a polymorphic way then it kinda makes sense for them to have the same method signatures.

I don't particularly like the idea of adding a method like ``ignoreMissingRelationships()`` since you would always need to worry about which relations exist and which don't when dealing with them in a polymorphic context.

**Comment by themsaid** [comment] 2016-09-22 18:57
Looks like bringing this behaviour back to Laravel is not an easy thing, the fact is that it used to work before doesn't really mean it should keep working.

Closing this issue then :)

**Closed by themsaid** 2016-09-22 18:57 UTC

**Comment by acasar** [comment] 2016-09-22 20:37
@themsaid @Jono20201 And also, I checked - it didn't work before. I downgraded the example project to Laravel 5.2.39 and only the first level was eager loaded, second level was ignored.

So really, nothing was even broken in 5.2.40 - just a bug was fixed so that second level relationships are no longer ignored.

**Comment by Jono20201** [comment] 2016-09-22 20:52
Hi there.

With doesn't work,  but the load function does work as described.

Thanks.

**Comment by acasar** [comment] 2016-09-22 20:55
In 5.2.39 I get the same result in both cases - 13 queries, with first level eager loaded, second level lazy loaded:

![image](https://cloud.githubusercontent.com/assets/6329543/18765824/a96baec0-8117-11e6-8f30-30c0134df043.png)

**Comment by Jono20201** [comment] 2016-09-22 21:03
Hi,

I'm not totally sure then. I know it works as I expected in a version as we
use it in our production application to quite a large degree which has
prevented us upgrading. Without it we would be doing a serious amount of
queries.

My home Internet has a fault that my Internet company is taking their time
to fix so can't investigate at the moment so can't look until tomorrow.

As this has been closed I'm not sure if there is any point in further
trying to demonstrate the issue however as it appears its been classed as a
wontfix.

If we were to find a solution in house (which is ultimately what we will
have to do) then is there much point in submitting a PR?

I appreciate everyone's time and attention to this matter however,  so
thank you.

**Comment by acasar** [comment] 2016-09-22 22:41
I went as far back as Laravel 5.2.20 and still the same. Are you sure this worked at any point? Maybe your setup is different in the actual application?

I really don't see any clean solution for this problem which makes a potential PR unlikely to be merged. In your case I'd probably just create a trait (e.g. ``IgnoreMissingRelationships``) which would override the ``Builder`` and handle this edge case.
