### ISSUE TITLE
Method to Clone Collections

### ISSUE THREAD

**Issue by jaschweder** [laravel/framework#15286] opened 2016-09-05 18:06 UTC
- Laravel Version: 5.2.8
- PHP Version: 5.6.25
- Database Driver & Version: not applied

### Description:
One method that is important do Illuminate/Collection have is ```clone()```, this method generate a copy of the current collection.

Can anyone make some comments here why or why not this is a bad idea ?

Thanks.

### Steps To Reproduce:
```php
$collection = collect();
$clone = $collection->clone();
// or
$clone = clone $collection;
```

**Comment by alexbowers** [comment] 2016-09-06 09:43
Why are you not able to use the `$clone = clone $collection;` example?

For me that works:

```php
$collection = collect([1, 2, 3]);

    dd(
        $collection,
        clone $collection
    );
```

![image](https://cloud.githubusercontent.com/assets/842974/18269088/8e8216b8-741e-11e6-972a-5e5bb644b560.png)

Or is this a feature request?

If it is, its pretty simple to complete with a macro;

```php
\Illuminate\Support\Collection::macro('clone', function() {
        return clone $this;
    });
```

**Comment by jaschweder** [comment] 2016-09-06 12:43
@alexbowers this works with simple internals, but test this with objects that are passed has references, the clone method obviously don't copy the objects, only the references, is correct to copy all object's in the collection or mantain the references to them original objects ?

**Comment by alexbowers** [comment] 2016-09-06 12:47
I'd say if you were cloning a reference, you'd expect it to still reference the same thing. A clone should be an exact replica.

**Comment by GrahamCampbell** [comment] 2016-09-06 12:48
> I'd say if you were cloning a reference, you'd expect it to still reference the same thing

That's not the definition of cloning.

**Comment by GrahamCampbell** [comment] 2016-09-06 12:48
Cloning a collection will give a shallow clone. Are you asking for a way to do a deep clone?

**Comment by alexbowers** [comment] 2016-09-06 12:49
You could always traverse the object and clone each item individually if it is itself an object.  Doing this recursively would be a deep clone I guess

**Comment by jaschweder** [comment] 2016-09-09 00:02
@GrahamCampbell @alexbowers yes deep-copy is what I mean, any chance to have some native stuff in Laravel for this ? or is more application like feature ?

**Comment by themsaid** [comment] 2016-09-16 20:38
Well I'm going to close this Issue since it's not a bug report, I suggest that you open a PR with the suggested changes or open an issue on the internals repository, it's where we keep all our discussions & feature requests.

Thanks for the suggestion though :)

**Closed by themsaid** 2016-09-16 20:38 UTC
