### ISSUE TITLE
Cannot install Laravel: continue targeting switch is equivalent to break. Did you mean to use continue 2?

### ISSUE THREAD

**Issue by PieterjanDeClippel** [laravel/framework#26549] opened 2018-11-18 09:02 UTC
- **PHP Version:** 7.3
- **Database Driver & Version:** 10.1.23-MariaDB-9+deb9u1 Raspbian 9.0
- **Apache Version:**
* Server version: Apache/2.4.25 (Raspbian)
* Server built:   2018-11-03T18:46:19
- **uname -r:** 4.14.80-v7+
- **node:** 8.12.0

### Description:
I'm trying to pull laravel from composer. When I do I'm getting this error
`"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?`

### Steps To Reproduce:
`composer create-project laravel/laravel --prefer-dist Internal`

It would be nice if php7.3 was supported so we don't need to fallback on PHP 7.2

**Comment by staudenmeir** [comment] 2018-11-18 16:38
I can't reproduce this, PHP 7.3 works for me. Does the error provide a stacktrace?

**Comment by sisve** [comment] 2018-11-18 21:06
This sounds like something a code analysis tool would say. Do you perhaps have any code analysis setup in any git hooks?

**Comment by laurencei** [comment] 2018-11-19 00:40
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Closed by laurencei** 2018-11-19 00:40 UTC

**Comment by lindyhopchris** [comment] 2019-01-04 10:11
FYI for anyone who encounters this - I ran into this on a separate problem and doing `composer selfupdate` solved it.

**Comment by vikastyagi87** [comment] 2019-01-30 05:33
First reinstall composer, after then again try to install composer, i also faced same problem but after reinstall composer with latest version it worked for me. I have explain that issue here https://www.thecodedeveloper.com/install-laravel-with-xampp-using-composer/

**Comment by maxmonteiro** [comment] 2019-04-17 12:46
Maybe the composer is outdated.

Remove the composer:
`sudo apt-get remove composer`

Reinstall it:
`php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"`

`php -r "if (hash_file('sha384', 'composer-setup.php') ==='48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"`

`php composer-setup.php`

`php -r "unlink('composer-setup.php');"`

Now move the composer:
`sudo mv composer.phar /usr/local/bin/composer`

font: https://getcomposer.org/download/
