### ISSUE TITLE
MultiServer onOneServer sometimes executed twice when cache has been cleared on deploy

### ISSUE THREAD

**Issue by matrad** [laravel/framework#29447] opened 2019-08-07 09:52 UTC
- Laravel Version: 5.8
- PHP Version: 7.2
- Cache Driver: [Redis Sentinel](https://github.com/monospice/laravel-redis-sentinel-drivers)
- Database Driver & Version: MariaDB

### Description:

The method ```->onOneServer()``` in the ```Kernel.php``` laravel scheduler works perfectly, but at the time we make a depploy and run the command ```php artisan cache:clear``` some onOneServer commands are executed twice on the same time.

I think a possible solution is to define a separate redis connection for the onOneServer cache to prevent this behaviour?

### Steps To Reproduce:

- Set up three hosts running the Laravel Cronjob with Redis Sentinel and the redis-sentinel-driver (we also reproduced this with the predis driver)
- Create a Job what runs every minute and creates an entry in a logfile with a timestamp
- If you execute ```php artisan cache:clear``` during deploy on multiple servers some commands will be executed twice, you'll receive logs from different hosts nearly at the same time.

**Comment by laurencei** [comment] 2019-08-07 12:40
To be honest - this is kind of expected behaviour. It's not a bug.

**Comment by laurencei** [comment] 2019-08-07 12:40
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Closed by laurencei** 2019-08-07 12:40 UTC

**Comment by matrad** [comment] 2019-08-07 12:45
@laurencei ok, I'll submit a PR, I think a separate cache handler for the onOneServer would solve this problem.
