### ISSUE TITLE
[5.2] Should Model::unguard()/reguard() still be called in DatabaseSeeder class?

### ISSUE THREAD

**Issue by danieliancu** [laravel/framework#11786] opened 2016-01-09 12:56 UTC
I saw that in L 5.2 the calls to `Model::unguard()` and `Model::reguard()` were removed from the DatabaseSeeder class, but they are still mentioned in docs.

**Comment by GrahamCampbell** [comment] 2016-01-09 15:02
Thanks for the report. We're open to PRs to the docs. Since this not a bug in the framework, I'm going to close this.

**Closed** 2016-01-09 15:01 UTC

**Comment by danieliancu** [comment] 2016-01-11 00:05
I will asume the answer is no.
