### ISSUE TITLE
auth()->check() returns false after successful login

### ISSUE THREAD

**Issue by htulibacki** [laravel/framework#16725] opened 2016-12-09 12:09 UTC
- Laravel Version: 5.3.26
- PHP Version: 7.0.5

### Description:

I discovered that in my application redirecting to the intended path after succesfull login is not working. After some investigation i figured out, that auth()->check() method returns false in the redirected action. When I refreshed the page, auth()->check() returned true. So after every login I was redirected to the intended path, where auth middleware redirected me back to my login path (becouse auth()->check() returned false there) and where guest middleware redirected me to my dashboard route (becouse auth()->check() was true).

I reproduced this behavior on clean Laravel install. Is this a bug or am I doing something wrong?

I'm using session guard driver and database session driver.

### Steps To Reproduce:

1. Log in
2. Log out
3. Log in again
4. Run auth()->check() right after redirect.

**Comment by htulibacki** [comment] 2016-12-09 13:08
And now I discovered that this behaviour is only reproducible after logout, when you try to log in again. So I updated steps to reproduce above.

**Comment by HSPDev** [comment] 2016-12-18 09:57
Have you check using Chrome developer console that the cookie is actually being set by Laravel?

Are you running the latest version of homestead? Both the vagrant box and the Homestead script itself? 
I've seen quite a few issues with newer version of Laravel not setting cookeis correctly. For me, the login system worked, but every single session and cookie had to have a Session::save() call. Maybe you are running into the same issue? Mine went away by upgrading to the latest Homestead.

I also had a redirect() right after setting some session data btw.

**Comment by themsaid** [comment] 2016-12-21 13:46
@htulibacki I can't reproduce the issue on a fresh 5.3 installation. Can you please check @HSPDev's comment?

**Comment by htulibacki** [comment] 2016-12-22 10:29
I can't reproduce it on a diffrent machine either. I'm using my own development server (not Homestead or any virtual machine). I had problems with database session driver in the past. With file driver this problem disappears - so it may be database related. The cookie is set correctly, but the user_id field in database is null.

**Comment by themsaid** [comment] 2016-12-22 10:32
I did test using the database session driver and couldn't reproduce, I guess it's an environment specific issue rather than an issue in the core.

**Comment by htulibacki** [comment] 2016-12-22 10:34
Yo're propably right. Thank you for you effort.

**Comment by themsaid** [comment] 2016-12-22 10:58
Closing this then, feel free to ping me though if it turned out to be a problem in the core. Thanks :)

**Closed by themsaid** 2016-12-22 10:58 UTC

**Comment by grabix123** [comment] 2018-06-19 03:40
auth()->check() returns false after successful login in my application. After login it have redirect index page but it returns to login page because auth()->check() returns false after  login

**Comment by Wikiki** [comment] 2018-12-02 17:43
Same here :-(
exact same behavior than @grabix123

**Comment by afernandesgoahead** [comment] 2019-08-07 20:50
I'm in the same issue too.

Right after register it works fine, but once I logout and then log back in, auth->check returns false and redirects to login.

(Laravel 5.8)

**Comment by linhdv96** [comment] 2023-10-11 02:25
I encountered a similar error, at login then redirest, `Auth::user() returned null`.

I discovered the culprit is the data type of `created_at, updated_at which is string`. The solution is to convert the `string` data type to `mongoDB date`

In other cases I suggest checking the data type in your user table, there may be a mistake somewhere
