### ISSUE TITLE
Possible blade bug using HTML comments

### ISSUE THREAD

**Issue by RobinBertilsson** [laravel/framework#26189] opened 2018-10-19 12:20 UTC
- Laravel Version: 5.4, 5.6, 5.7 (tested by myself)
- PHP Version: PHP 7.1.23 (cli) (built: Oct 11 2018 16:19:26) ( NTS )

### Description:
When i'm using a comment in blade with an # (hashtag) in it - the comment transform into the following message "an error occurred while processing the directive".

It doesn't throw an error, it's just the text that's beeing displayed.
Reason i found it is because we're currently using Storyblok (Headless CMS), which returns and _editable property, that contains the following comment:

`<!--#storyblok#{"name": "text", "space": "abc", "uid": "abc-abc-abc-abc-abc", "id": "123"}-->`

### Steps To Reproduce:

1. `composer create-project laravel/laravel test-hash-comments-2 --prefer-dist`
2. Open `welcome.blade.php` and add `<!--#test-->` somethere, preferable in `.content > .title.m-b-md` (line 82).
3. Reload the browser and face the error message.

**EDIT:**
Seems to be a Nginx related problem, don't have the same issue in my php-7.1.18-apache2 docker environment.

**Comment by staudenmeir** [comment] 2018-10-19 14:11
I can't reproduce this in Homestead (which uses nginx).

**Comment by browner12** [comment] 2018-10-19 15:00
also unable to reproduce on Homestead.

**Comment by laurencei** [comment] 2018-10-19 23:16
I'll close this, as appears to be a local issue. If you can provide code to reproduce on a fresh Laravel install, let us know,

**Closed by laurencei** 2018-10-19 23:16 UTC

**Comment by RobinBertilsson** [comment] 2018-10-20 14:40
We had two computers facing the same issue, both running Valet 2.1.1

**Comment by Brotzka** [comment] 2020-05-15 12:42
Faced this problem today with Laravel 5.8, OSX and Laravel Valet.

@RobinBertilsson did you found a solution?

**Comment by WL1981** [comment] 2021-01-29 16:17
This is my solution for the timebeing
{!! str_replace("<!--#", "<!-- #", "YOUR-STRING") !!}

**Comment by RobinBertilsson** [comment] 2021-01-29 16:23
Sorry for late answer @Brotzka, missed it for some reason...
I found a temporary solution close to what @WL1981 did.

Creating a "partial" view named `editable.blade.php` and just reference that like the following `@include('partials.editable', ['blok' => $blok])`

editable.blade.php
`{!! isset($blok['_editable']) ? str_replace('<!--', '<!-- ', $blok['_editable']) : '' !!}`
