### ISSUE TITLE
Does not return the correct file location

### ISSUE THREAD

**Issue by ronaldotn** [laravel/framework#14739] opened 2016-08-10 12:39 UTC
## Problem
```
Storage :: disk function ('local') -> url ($ file); 
```
does not return the correct path if you have configured in the **filesystems.php** the field 'root' => storage_path ('app') , returns a path without the app folder. 

## Solution
The solution I found is that in the Illuminate/Filesystem/FilesystemAdapter.php file. 
```
} elseif ($adapter instanceof LocalAdapter) {
	return '/storage/'.$path; 
} 
```
extacamente in this line of code, extracts an address erroneous for Storage, I corrected as follows 
```
} elseif ($adapter instanceof LocalAdapter) { 
	return $adapter->getPathPrefix().$path; 
}
```
I wonder if my solution is right or not present to the same mistake, I'm using laravel 5.2 Thanks

**Comment by themsaid** [comment] 2016-09-06 16:33
This is just the convention, when you run `php artisan storage:link` a symbolic link from `public/storage` to `storage/app/public`, which is the root of the local driver by default.

In case you want to change the root make sure you update the symbolic link to point to your new root instead of `storage/app/public`.

I'm closing this issue since it's not a bug report.

**Closed by themsaid** 2016-09-06 16:33 UTC
