### ISSUE TITLE
Alias orderBy on collections

### ISSUE THREAD

**Issue by TheShiftExchange** [laravel/framework#15897] opened 2016-10-13 19:22 UTC
- Laravel Version: 5.3.*
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:

Would it be ok to create an alias for `orderBy()` on the collection class?

Currently you have to do `sortBy()` - but we use `orderBy()` in eloquent. They both perform roughly the same function, but are different names. And there are already a lot of similar function names between the two. Having an `orderBy()` on the collection class just makes life easier and code simpler IMO...

Just a thought...

**Comment by themsaid** [comment] 2016-10-13 19:41
I'd say go ahead and open a PR with your suggestion :) 

Closing this since it's not a bug report, for suggestions and feature requests please use the https://github.com/laravel/internals repo.

Thanks :)

**Closed by themsaid** 2016-10-13 19:41 UTC
