### ISSUE TITLE
Validator Error message not being created correctly

### ISSUE THREAD

**Issue by timack** [laravel/framework#51849] opened 2024-06-20 04:30 UTC
### Laravel Version

11.11.0

### PHP Version

8.2

### Database Driver & Version

n/a

### Description

The validator is not generating error messages correctly.

Might be related to this MR - https://github.com/laravel/framework/pull/51805 - will investigate further tonight if time.

### Steps To Reproduce

In version 11.10.0: 
```
> Validator::make(['total' => 0], ['total' => ['gt:0']])->messages()->all();
= [
    "The total field must be greater than 0.",
  ]
```

 
 In 11.11.0 the same code produces:
```
 > Validator::make(['total' => 0], ['total' => ['gt:0']])->messages()->all();
= [
    "The total field must be greater than validation.attributes.",
  ]
```

**Comment by driesvints** [comment] 2024-06-20 08:03
Ping @owenandrews

**Comment by driesvints** [comment] 2024-06-20 10:51
Might be best if we work out a test for this so we can actually verify a fix.

**Comment by seriquynh** [comment] 2024-06-21 05:03
I figure out why this happens. I'll try my best to explain. Let's take a look at this code.

```php
<?php

namespace Illuminate\Validation\Concerns;

// imports

trait FormatsMessages
{
    protected function getAttributeFromTranslations($name)
    {
        return $this->getAttributeFromLocalArray(
            $name, Arr::dot((array) $this->translator->get('validation.attributes'))
        );
    }
}
```

When validation messages are formatted, all fields or rule parameters are finally passed through the `getAttributeFromTranslations` method.

In this example, when formatting the message **"The :attribute field must be greater than :value."**
1. "total" is passed through `getAttributeFromTranslations`, it returns "total" and ":field" must be replaces with "total".

2. "0" is passed through `getAttributeFromTranslations`, it has to return "0" and ":value" must be replaces with "0". But it does not work as expected due to "validation.attributes" from the translator.

If `lang/en/validation.php` does not define `attributes` or define it as an emty array. It means `$this->translator->get('validation.attributes')` returns "validation.attributes" as a string instead of an array.

```php
<?php

// $source = [0 => 'validation.attributes'];
$source = Arr::dot((array) $this->translator->get('validation.attributes'));

// $name = '0'; as key accidently exists in the array above and getAttributeFromLocalArray returns "validation.attributes"

// That's why it replaces :value with "validation.attributes" and the final message is
$this->getAttributeFromLocalArray($name, $source); "The total field must be greater than validation.attributes."
```

I create these [examples](https://github.com/seriquynh/framework/blob/ac673026e2015ff65eddbb4a59e2901b8918a263/tests/Validation/ValidationValidatorTest.php#L595) to show how replacements are done.

### Example 1 - attributes are not empty in locale validation.php file.

```php
<?php

namespace Illuminate\Tests\Validation;

class ValidationValidatorTest extends TestCase
{
    public function test_validation_attributes_are_set()
    {
        // $source = ['foo' => 'bar'];
        // $name = '0'; as key does not exists in $source. -> ":value" is replaced with "0".
        $trans = $this->getIlluminateArrayTranslator();
        $trans->addLines(['validation.gt.numeric' => ':attribute is greater than :value.'], 'en');
        $trans->addLines(['validation.attributes' => ['foo' => 'bar']], 'en');
        $v = new Validator($trans, ['total' => 0], ['total' => 'gt:0']);
        $this->assertSame("total is greater than 0.", $v->messages()->first('total'));
    }
}
```

### Example 2 - comparison value is not zero.

```php
<?php

namespace Illuminate\Tests\Validation;

class ValidationValidatorTest extends TestCase
{
    public function test_comparison_value_is_not_zero()
    {
        // $source = [0 => 'validation.attributes'];
        // $name = '1' or '-1'; as key does not exists in $source. -> ":value" is replaced with "1" or "-1".

        $trans = $this->getIlluminateArrayTranslator();
        $trans->addLines(['validation.gt.numeric' => ':attribute is greater than :value.'], 'en');

        $v = new Validator($trans, ['total' => 1], ['total' => 'gt:1']);
        $this->assertSame("total is greater than 1.", $v->messages()->first('total'));

        $v = new Validator($trans, ['total' => -1], ['total' => 'gt:-1']);
        $this->assertSame("total is greater than -1.", $v->messages()->first('total'));
    }
}
```

### Example 3 - validtion attributes contains "0" or 0 as key.

```php
<?php

namespace Illuminate\Tests\Validation;

class ValidationValidatorTest extends TestCase
{
    public function test_validation_attributes_contain_0_as_key()
    {
        // $source = [0 => 'Integer Zero'];
        // $name = '0'; as key exists in $source. -> ":value" is replaced with "Integer Zero"
        $trans = $this->getIlluminateArrayTranslator();
        $trans->addLines(['validation.gt.numeric' => ':attribute is greater than :value.'], 'en');
        $trans->addLines(['validation.attributes' => [0 => 'Integer Zero']], 'en');
        $v = new Validator($trans, ['total' => 0], ['total' => 'gt:0']);
        $this->assertSame("total is greater than Integer Zero.", $v->messages()->first('total'));

// $source = ['0' => 'String Zero'];
        // $name = '0'; as key exists in $source. -> ":value" is replaced with "String Zero"
        $trans = $this->getIlluminateArrayTranslator();
        $trans->addLines(['validation.gt.numeric' => ':attribute is greater than :value.'], 'en');
        $trans->addLines(['validation.attributes' => ['0' => 'String Zero']], 'en');
        $v = new Validator($trans, ['total' => 0], ['total' => 'gt:0']);
        $this->assertSame("total is greater than String Zero.", $v->messages()->first('total'));
    }
}
```

**Comment by owenandrews** [comment] 2024-06-21 23:48
Thanks for the test @seriquynh, I'll get it reproduced locally and get back to you.

**Comment by owenandrews** [comment] 2024-06-22 03:11
@seriquynh I've created a [branch here](https://github.com/owenandrews/laravel-framework/blob/90763f50ffff7ebb635b3728970f70ca6f049b90/src/Illuminate/Validation/Concerns/FormatsMessages.php#L308) that I think resolves this issue. I've also added a test to check that messages are returned correctly when the translated attributes array is empty or missing. You can see that failing against the current branch [here](https://github.com/owenandrews/laravel-framework/actions/runs/9622396291/job/26543605031#step:9:198).

Could you confirm this resolves this issue and if so I'll create a PR.

**Comment by seriquynh** [comment] 2024-06-24 03:29
I think your fix's good for this specific situation. But I'm not sure there are any other use cases in which we need to add more tests. It's fine for me. Let's wait for other thoughts, use cases or recommendations.

**Comment by timack** [comment] 2024-06-24 11:26
@owenandrews Can confirm issue is resolved for me when using that branch. Nice work 👍

**Comment by driesvints** [comment] 2024-06-25 08:15
Will be in today's release.

**Closed by driesvints** 2024-06-25 08:16 UTC
Labels: bug
