### ISSUE TITLE
Laravel Sail on Windows is not installing new project

### ISSUE THREAD

**Issue by Akash-manna** [laravel/framework#49452] opened 2023-12-20 20:26 UTC
### Laravel Version

10

### PHP Version

sail

### Description

When I try to create a new project using Laravel sail in my windows WSL, it throws the following error and stops. 
 I have followed the instructions as per the [documentation](https://laravel.com/docs/10.x#sail-on-windows) of Laravel 10

The Command Outputs:
```
akash@Awish-Dell:~$ docker -v
Docker version 24.0.6, build ed223bc
akash@Awish-Dell:~$ curl -s https://laravel.build/dummy-api-app | bash
latest: Pulling from laravelsail/php83-composer
Digest: sha256:bf8d87c943cacab0e04ead85e8c1db440e345fd1456714f736786ef4d18ba7b7
Status: Image is up to date for laravelsail/php83-composer:latest

   _                               _
  | |                             | |
  | |     __ _ _ __ __ ___   _____| |
  | |    / _` | '__/ _` \ \ / / _ \ |
  | |___| (_| | | | (_| |\ V /  __/ |
  |______\__,_|_|  \__,_| \_/ \___|_|


In Interactivity.php line 32:

  Required.


new [--dev] [--git] [--branch BRANCH] [--github [GITHUB]] [--organization ORGANIZATION] [--stack [STACK]] [--breeze] [--jet] [--dark] [--typescript] [--ssr] [--api] [--teams] [--verification] [--pest] [--phpunit] [--prompt-breeze] [--prompt-jetstream] [-f|--force] [--] <name>

bash: line 17: cd: dummy-api-app: No such file or directory
bash: line 23: ./vendor/bin/sail: No such file or directory
bash: line 24: ./vendor/bin/sail: No such file or directory

Get started with: cd dummy-api-app && ./vendor/bin/sail up
akash@Awish-Dell:~$ cd dummy-api-app
-bash: cd: dummy-api-app: No such file or directory
akash@Awish-Dell:~$

``` 

### Steps To Reproduce

Step 1: 
```
PS C:\Users\akash> wsl
``` 
Step 2: 
```
akash@Awish-Dell:~$ curl -s https://laravel.build/dummy-api-app | bash
```

**Comment by crynobone** [comment] 2023-12-20 23:13
Duplicate of laravel/sail#643

**Closed by crynobone** 2023-12-20 23:13 UTC
