### ISSUE TITLE
Call to a member function setTimezone() on null for favicon.ico

### ISSUE THREAD

**Issue by pascalvgemert** [laravel/framework#47600] opened 2023-06-28 07:45 UTC
### Laravel Version

10.14.0

### PHP Version

8.2

### Database Driver & Version

MySQL 8

### Description

The following feature has a breaking change for Vapor:
https://github.com/laravel/framework/pull/47567

When the request is a `favicon.ico` the pipeline in `vendor/laravel/vapor-core/src/Runtime/HttpKernel::sendRequest` will exit and call the `terminate()` method below. This will try to set a timezone on the `requestStartedAt` which is still `null` because the request hasn't been handled yet. This causes a 500 error at the moment.

### Possible solution

Easy fix would be to add a null safe operator I guess. 

<img width="1045" alt="image" src="https://github.com/laravel/framework/assets/1567379/7b833bfd-98cd-4da1-b0a1-b6f8244698bf">

### Temporary solution:

Publish vapor config and add `'redirect_favicon' => false,`

### Steps To Reproduce

See image in description.

Vapor request to `example-domain.com/favicon.ico` which wants to redirect.

**Comment by timacdonald** [comment] 2023-06-28 08:00
Duplicate of https://github.com/laravel/framework/issues/47591

**Closed by timacdonald** 2023-06-28 08:00 UTC
