### ISSUE TITLE
Passing an empty array to BelongsToMany::detach() provides unintuitive behaviour

### ISSUE THREAD

**Issue by alexleonard** [laravel/framework#13046] opened 2016-04-06 15:28 UTC
I just discovered the hard way that if you pass an empty array to `detach()` everything is detached from the pivot table.

Personally that feels a little unintuitive to me.

I might do something like:

```
$photoIds = $photo->whereSomething()->lists('id')->toArray();

$user->photos()->detach($photoIds);
```

My assumption here is that if the first query returns no results, then nothing untoward would occur. But in actual fact all photos would be detached from the user if the first query returns an empty array.

Naturally now I'm aware of this behaviour (which is documented - it was just my error), I can avoid the issue by checking the array isn't empty before passing it to the detach method, but if just feels counter-intuitive.

It feels like it might be better to have an explicit `detachAll()` method and for the `detach()` method to do nothing when passed an empty array.

What do you think?

**Comment by vlakoff** [comment] 2016-04-06 17:18
Entirely agree, this should be proposed for 5.3 though (BC break).

**Comment by heisian** [comment] 2016-04-13 00:00
I think when the documented behavior of `->detach()` is to detach all model instances from the parent, it should follow that an empty array, which is essentially `null` should cause the same behavior.

Yeah, it requires extra logic to say:
```
if (count($photoIds) > 0) {
    $user->photos()->detach($photoIds);
}
```
but honestly, it's not that bad.

**Comment by alexleonard** [comment] 2016-04-13 11:46
I definitely appreciate the documented approach is for this behaviour, but I still say it feels counter-intuitive. 

`$user->photos()->attach([]);` doesn't attach all the photos to the user, it attaches none. 

It feels logical to me that `$user->photos()->detach([]);` should also detach nothing.

Perhaps there's no need for a `detachAll()` method. Just if you want to detach all you pass no arguments to the detach method.

But it does feel logical to me that passing an empty array to detach should result in no detachments.

I would think that detach is more often used for detaching specific instances, rather than detaching everything - it's not often that I want to completely empty all related instances.

**Comment by heisian** [comment] 2016-04-13 17:50
True but the logic for `->detach` really translates to `->detachAnyAttachedPhotos`

while doing the same for `->attach` would be `->detachAllUnattachedPhotos` which is highly ambiguous.  What if you have a billion photos? That's a lot of writes.  What if some photos are already attached to another user and can only have one parent?  You run into foreign key constraint issues here.

There is a lot more at stake when doing an arbitrary `->attach` than there is with an arbitrary `->detach` I feel like.

**Comment by alexleonard** [comment] 2016-04-14 15:01
I'm not arguing in favour of changing `->attach()` behaviour at all, just using it as an example.

I just think if `->detach()` receives an empty array, the correct assumption is that no detachments should be made. The same way that if `->attach()` receives an empty array, no attachments are made.

If it receives no arguments, then it could be read as detach all.

This sort of thing, although there is probably a neater way to write this.

    /**
     * Detach models from the relationship.
     *
     * @param  int|array  $ids
     * @param  bool  $touch
     * @return int
     */
    public function detach($ids = null, $touch = true)
    {
        if ($ids instanceof Model) {
            $ids = (array) $ids->getKey();
        }

        $query = $this->newPivotQuery();
        // If the $ids are not null, then process them, but if no $ids were passed then we will just detach all
        if (!is_null($ids)) {

            $ids = (array) $ids;
            // If the array isn't empty, mod the query to query specific ids
            if (count($ids) > 0) {
                $query->whereIn($this->otherKey, (array) $ids);

            // But if the array is empty, detach nothing
            } else {
                return 0;
            }
        }

        $results = $query->delete();

        if ($touch) {
            $this->touchIfTouching();
        }

        return $results;
    }

**Comment by alexleonard** [comment] 2016-04-14 15:04
@taylorotwell what do you think?

**Comment by heisian** [comment] 2016-04-14 17:52
@alexleonard i can see how issuing the command in a production situation could be relatively disastrous, but then I would think that function behavior would be verified & tested before being used in a critical environment.

I see it as a "gotcha," something one would need to know beforehand because it is a potentially destructive operation.  But you didn't notice its behavior during development, before it actually went to production?

I do think your edit is useful and valid, however, and it doesn't seem like it would make any breaking changes...

**Comment by themsaid** [comment] 2016-09-26 21:01
based on the method signature:

```
function detach($ids = [], $touch = true) {}
```

It's clear that it's an intended behaviour, if no IDs given then it'll wipe all. Changing this would be considered breaking.

Please feel free to open a PR for 5.4 which is scheduled for November, closing this issue though since it doesn't feel like a bug :)

**Closed by themsaid** 2016-09-26 21:01 UTC
