### ISSUE TITLE
Laravel Horizon is scaling the wrong way (auto + max-processes)

### ISSUE THREAD

**Issue by michabbb** [laravel/framework#51765] opened 2024-06-10 23:17 UTC
### Laravel Version

any 

### PHP Version

any

### Database Driver & Version

any

### Description

Since nobody cares, I am trying to get some attention here.

everything is explained here https://github.com/laravel/framework/discussions/48431

TLDR; when horizon starts max worker get started, even they have nothing to do and get scaled down afterwards.
this concept is terribly wrong. a "balancer" should always scale up, and not down.

i hope that someone understands this simple logic and even this is not a software bug, it´s a "failed by concept" thing
and because of that, it needs to be changed.

thanks!

### Steps To Reproduce

start horizon with 500 worker + auto + max-processes balance logic. 
what happens ? horizon starts 500 worker even nothing is in the queue. 
then all workers will be stopped till only one is running.

what should happen?
actually NONE worker needs to be started (or at least one) if horizon starts.
based on the queue horizon needs to scale up.

again: the concept of a scaler should be: scale UP, not scale down 😏

**Comment by crynobone** [comment] 2024-06-11 00:33
Duplicate of https://github.com/laravel/horizon/issues/1295, feel free to attempt a PR again.

**Closed by crynobone** 2024-06-11 00:33 UTC

**Comment by michabbb** [comment] 2024-06-11 01:34
@crynobone the last PR got rejected. What do I have to do differently to avoid the same frustration the other person had to feel after investing time and afford into this?
