### ISSUE TITLE
.env.local stopped working, "php artisan serve --env=local" command is not loading the proper environment

### ISSUE THREAD

**Issue by laravelbear123** [laravel/framework#34217] opened 2020-09-09 08:47 UTC
- Laravel Version: 8.0.0
- PHP Version: 7.4.2
- Database Driver & Version: MySQL

### Description:
Today i've upgraded to Laravel 8.0 from Laravel 7 (latest).

Environments stopped working, without any change of code.

I have 2 .env files :
- .env
- .env.local

I've noticed, that both files had "APP_ENV" set to "local", but still were working fine in previous Laravel versions.

Now, i've changed the .env "APP_ENV" -> "production", and .env.local "APP_ENV" => "local".

I'm running the following command:
"php artisan serve --env=local"

But my production .env file is being loaded. No matter what i do, i've tried printing via "env('APP_ENV')" and i got "production" even when i was running --env=local.

I've tried to artisan config:cache, config:clear, cache:clear -> nothing worked.

This stopped working right after the upgrade and i'm sure it was working before the upgrade, so it has to do something with Laravel 8.0.0.

**Comment by laravelbear123** [comment] 2020-09-09 09:14
I've even created new .env.testenv with "APP_ENV" => 'testenv', ran "php artisan serve --env=testenv".

And still, loaded production......

**Comment by laravelbear123** [comment] 2020-09-09 09:43
So, i've done some additional testing.

As i've said, i have 2 .env files : 
- .env
- .env.local

The problem is, that even though i specify "--env=local" in my artisan serve, the .env file gets loaded.

Anyway, i've tried to rename .env -> .env.local, .env.local -> .env

It works. So the config is not cached or anything like that, it just loads from the wrong environmental file.

Also, i've noticed a very WEIRD thing : 
- "php artisan serve --env=local" -> doesn't load .env.local where APP_ENV=local, instead loads .env
- the application is served and config is loaded from .env, not .env.local, BUT ->
- when i change a setting in .env.local, it gets shutdown for "environment modified", the settings are loaded from .env, but this only happens when i change something in .env.local, which was the desired .env specified in php artisan --env argument

I really don't know what this is....

**Comment by laravelbear123** [comment] 2020-09-09 10:07
"php artisan db:seed --env=local" -> works fine, uses DB connection specified in .env.local -> loading .env.local 👍 

"php artisan serve --env=local" -> doesn't work, uses DB connection specificed in .env -> thus loading .env 👎

**Comment by laravelbear123** [comment] 2020-09-09 10:30
When i dump App::environment() -> i get "production", even though i load local "php artisan serve --env=local".

But even when the app prints "production" environment and i change the .env.local file where APP_ENV=local, it gets shutdown and restarted because of "environment modified".

How the hell is that possible?

**Comment by Harti** [comment] 2020-09-09 11:38
FWIW, while I haven't had these issues, I can confirm that there are some oddities with environment variables with 8.0.

In my case, most/all of the `<env>` values in my phpunit.xml got either ignored, or overridden by the contents of .env. 
Adding an .env.testing injects the variables correctly into `$_ENV` while phpunit.xml wasn't being interpreted correctly. (Interestingly, this only worked when phpunit.xml set the APP_ENV to "testing".)

I was unable to track down the issue nor have a shareable reproduction case ready, but the DotEnv integration does seem to need some looking into.

**Comment by laravelbear123** [comment] 2020-09-09 11:52
@Harti Are you able to load different ".env.something" file via "--env=env" parameter.

For example, create new .env.local file, add some variables and try to server "php artisan serve --env=local".

The thing is, that the env.local is being somehow used, because if you change it while running the app, it shutdowns and restarts itself for "environment edit".

So it probably gets overwritten by the .env file, that might be the case.

**Comment by Harti** [comment] 2020-09-09 11:54
@laravelbear123 I fixed my issue otherwise, thanks though. I just wanted to back this issue because my DotEnv setup broke after upgrading from 7.25 to 8.0.

**Comment by taylorotwell** [comment] 2020-09-09 12:47
Fixed in next patch.

**Closed by taylorotwell** 2020-09-09 12:47 UTC
