### ISSUE TITLE
Cached routes are broken in some cases

### ISSUE THREAD

**Issue by Veratyr** [laravel/framework#31926] opened 2020-03-12 07:58 UTC
- Laravel Version: 7.1.0
- PHP Version: 7.4.3

### Description:
In some cases, routes are broken after using `artisan route:cache`.

### Steps To Reproduce:

1. routes/web.php:
```
Route::middleware('locale')->prefix('{locale}')->group( function () {
    Route::get('/{player_id}/{vehicles}/{start_date?}', 'PlayersController@show')->prefix('parts');
});
```

2. The correct route in the `artisan route:list` output:
```
+--------+----------+-----------------------------------------------------+------+---------------------------------------------+------------+
| Domain | Method   | URI                                                 | Name | Action                                      | Middleware |
+--------+----------+-----------------------------------------------------+------+---------------------------------------------+------------+
|        | GET|HEAD | parts/{locale}/{player_id}/{vehicles}/{start_date?} |      | App\Http\Controllers\PlayersController@show | web,locale |
+--------+----------+-----------------------------------------------------+------+---------------------------------------------+------------+
```

3. Run `artisan route:cache`, and get broken route. `artisan route:list` output after caching:
```
+--------+----------+--------------------------------------------------------+-----------------------------+---------------------------------------------+------------+
| Domain | Method   | URI                                                    | Name                        | Action                                      | Middleware |
+--------+----------+--------------------------------------------------------+-----------------------------+---------------------------------------------+------------+
|        | GET|HEAD | {locale}/{locale}/{player_id}/{vehicles}/{start_date?} | generated::PgyGEeBpyEewqRs0 | App\Http\Controllers\PlayersController@show | web,locale |
+--------+----------+--------------------------------------------------------+-----------------------------+---------------------------------------------+------------+
```

Please pay attention to what `->prefix()` is used on the group and on the route itself. It looks like it the reason why cache goes crazy.

As you can see, in the cached route there is two `{locale}/{locale}` prefixes instead of `parts/{locale}`.

**Comment by dwightwatson** [comment] 2020-03-12 10:56
Both of these seem weird to me, I'd expect the route to be `{locale}/parts/{player_id}/{vehicles}/{start_date?}` - I would think the group prefix would proceed the route prefix. Is there a reason you don't just include `parts` in the route rather than using `prefix()`?

**Comment by Veratyr** [comment] 2020-03-12 11:55
> Is there a reason you don't just include parts in the route rather than using

Yes. I need the `parts` placed before the `{locale}` (which is comes from the group prefix).

Without the cache it works as expected, the problem is related only to the route cache in the Laravel 7+.
In 6.x it works as expected even when cached.

**Comment by rodrigopedra** [comment] 2020-03-12 14:36
I guess what @dwightwatson meant was to move the prefix to the group definition, like this:

~~~php
Route::middleware('locale')->prefix('/parts/{locale}')->group( function () {
    Route::get('/{player_id}/{vehicles}/{start_date?}', 'PlayersController@show');
});
~~~

It might work on L7 this way

**Comment by vakisp** [comment] 2020-03-13 12:37
I am having a similar issue, my routes looks like this:

Route::prefix('student')->group(function () {
    Route::namespace('Training\Student')->group(function () {
        Route::get('/login', 'StudentLoginController@login')->name('student.login');

without cache I get the correct routes:

| PATCH     | student/auth
 | GET|HEAD  | student/dashboard
| GET|HEAD  | student/login

With cache i get:


| PATCH     | student/student/auth
 | GET|HEAD  | student/student/dashboard
| GET|HEAD  | student/student/login

**Comment by driesvints** [comment] 2020-03-16 17:39
I can reproduce this. Not sure what the ideal solution is here though.

**Comment by taylorotwell** [comment] 2020-03-16 18:49
Will be fixed in next release. https://github.com/laravel/framework/commit/449c8056cc0f13e7e20428700045339bae6bdca2

**Closed by taylorotwell** 2020-03-16 18:49 UTC
Labels: bug
