### ISSUE TITLE
Eloquent where() clause casting string to int

### ISSUE THREAD

**Issue by clawrence121** [laravel/framework#47956] opened 2023-08-04 02:46 UTC
### Laravel Version

10.16.1

### PHP Version

8.1.18

### Database Driver & Version

MySQL 8.0.19

### Description

When attempting to pass a string representing an int to an Eloquent where() clause, the string is cast to an int, thus causing any indexes on the underlying `varchar` column to be missed.

The table was created via a Laravel migration:
```
$table->string('shopify_order_id')->nullable()->index('idx_shopify_order_id');
```
<img width="245" alt="Screenshot 2023-08-04 at 12 37 59" src="https://github.com/laravel/framework/assets/23254373/a925d261-4526-4a58-a445-99e888b8a94c">
<img width="314" alt="Screenshot 2023-08-04 at 12 46 38" src="https://github.com/laravel/framework/assets/23254373/38d13524-ed3e-4e5b-bafd-d03a11a2a1bc">

The records in this column typically are an integer value, though not always and often require a 0 at the start, thus needing to be represented as a string.

When attempting to do a simple where lookup:
```
Order::query()
  ->where('shopify_order_id', '123456789')
  ->first()
```
The raw SQL becomes:
```
select * from `orders` where `shopify_order_id` = 123456789 and `orders`.`deleted_at` is null limit 1
```
Causing the Index to be missed:
<img width="1191" alt="Screenshot 2023-08-04 at 12 40 37" src="https://github.com/laravel/framework/assets/23254373/d7718c47-d628-4f9a-ba0c-71b013a4087c">
<img width="1064" alt="Screenshot 2023-08-04 at 12 40 46" src="https://github.com/laravel/framework/assets/23254373/38b97b9c-0fd7-451c-ac9b-821cfc14276c">

This also happens when casting to a string, and using strict_types.
<img width="325" alt="Screenshot 2023-08-04 at 12 41 41" src="https://github.com/laravel/framework/assets/23254373/66234443-5a1c-425b-b5d7-d50291c9a0da">

I am able to get around this using ->whereRaw() but would rather not have to.

Expected behaviour:
When passing a string to the where clause, it is passed as a string to the underlying query:
```
select * from `orders` where `shopify_order_id` = '123456789' and `orders`.`deleted_at` is null limit 1
```

I would assume this happens because of some sort of SQLi protection that is mapping it to a string?

### Steps To Reproduce

Create a new model, table and DB migration with a string column and index.

Add a DB query log to AppServiceProvider:
```
DB::listen(function ($query) {
            Log::debug('Query', [
                'sql' => Str::replaceArray('?', $query->bindings, $query->sql),
                'time' => $query->time,
            ]);
        });
```

Perform a query in Tinker to get the raw SQL:
```
Model::where('column', '12345')->first()
```

Fetch the SQL from logs:
```
select * from `model` where `column` = 12345 limit 1
```

Run the query in SQL client with explain.

**Comment by crynobone** [comment] 2023-08-04 03:27
I don't believe this a reliable way to get the correct SQL:

Give the following example:

```php
// first
Post::where('name', 'foo')->first();

// second
Post::where('name', '123')->first();
```

![CleanShot 2023-08-04 at 11 26 17](https://github.com/laravel/framework/assets/172966/8328541f-6c97-4c95-93d0-1d9833f15169)

**Comment by crynobone** [comment] 2023-08-04 03:55
Also this seems like a duplicate of #46278

**Closed by crynobone** 2023-08-04 03:55 UTC
