### ISSUE TITLE
Using Redis on shared server with multiple Laravel application

### ISSUE THREAD

**Issue by vijaysebastian** [laravel/framework#22140] opened 2017-11-20 07:10 UTC
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: Mysql

We have hosted two Laravel application on one server. Installed Redis & Supervisor.
In supervisor configuration (/etc/supervisord.conf) added two configuration

Application 1 configuration

```
[program:app1-supervisor]
process_name=%(program_name)s_%(process_num)02d
command=php //path/to/application/1/artisan queue:work redis --sleep=3 --tries=3 --daemon
autostart=true
autorestart=true
user=ladybirq
numprocs=8
redirect_stderr=true
stdout_logfile=/path/to/application/1/worker.log
```

Application 2 configuration

```
[program:app2-supervisor]
process_name=%(program_name)s_%(process_num)02d
command=php //path/to/application/2/artisan queue:work redis --sleep=3 --tries=3 --daemon
autostart=true
autorestart=true
user=ladybirq
numprocs=8
redirect_stderr=true
stdout_logfile=/path/to/application/2/worker.log
```

When application 1 sends email, It sends from application 2 mail configuration.
Email configuration is stored in database and on fly application set in the configuration

Example

```
$email = Email::first();
config(“mail.driver.$email->driver”);

```
So some values in the application 1 email get replaced with application 2 values.
Not sure where I am going wrong.

Have anyone configured Redis on the single server with multiple applications. Both our application are same.

We are using cPanel on this server and both the application are hosted in different cPanel account on the same server

**Comment by it-can** [comment] 2017-11-20 07:30
Try setting a different value for this setting

https://github.com/laravel/laravel/blob/master/config/queue.php#L63

**Comment by laurencei** [comment] 2017-11-20 08:36
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself. In this case - the problem is you are using the same queue tube name for both applications.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Closed** 2017-11-20 15:36 UTC
