### ISSUE TITLE
The `associate` function of morphTo relation get wrong owner key

### ISSUE THREAD

**Issue by locnguyen1842** [laravel/framework#37054] opened 2021-04-20 09:20 UTC
- Laravel Version: 8.1.19
- PHP Version: 7.4.16
- Database Driver & Version: MySQL

### Description:
When using the `associate` function of morphTo relation, the ownerKey did not get the model key name passed to the `associate` function. Currently, it's got the previous ownerKey.

### Steps To Reproduce:

my_requests (table)

|  my_request_id  | created_by | created_by_type |
| ----------------| ------------|------------------|
| 1                       | 1  | App\Models\Admin |

MyRequestModel
```php
protected $primaryKey = 'my_request_id';

public function createdBy()
{
    return $this->morphTo(null, null, 'created_by', null);
}
```

AdminModel
```php
protected $primaryKey = 'agent_id';

public function createdMyRequests()
{
    return $this->morphMany(MyRequestModel::class, 'createdBy');
}
```

TenantModel
```php
protected $primaryKey = 'tenant_id';

public function createdMyRequests()
{
    return $this->morphMany(MyRequestModel::class, 'createdBy');
}
```

MyRequestController
```php
$modifier = TenantModel::find(1);

$myRequest = MyRequestModel::find(1);

$myRequest->createdBy()->associate($modifier);
```

When I'm dumping the $myRequest, the `created_by` attribute is null but the `created_by_type` was changed, so i was checked the `associate` function on `Illuminate\Database\Eloquent\Relations\MorphTo`

```php

public function associate($model)
{
        $this->parent->setAttribute(
             $this->foreignKey, $model instanceof Model ? $model->{$this->ownerKey ?: $model->getKeyName()} : null
        );

        $this->parent->setAttribute(
            $this->morphType, $model instanceof Model ? $model->getMorphClass() : null
        );

        return $this->parent->setRelation($this->relationName, $model);
}
```

At the line `$this->foreignKey, $model instanceof Model ? $model->{$this->ownerKey ?: $model->getKeyName()}` the property `$this->ownerKey` currently return the previous ownerKey (`admin_id`) not the model passed to the function (`tenant_id`)

**Comment by driesvints** [comment] 2021-04-20 09:41
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new laravel-issue-37054 --github="--public"
```

After you've posted the repository, I'll try to reproduce the issue.

Thanks!

**Comment by locnguyen1842** [comment] 2021-04-21 13:51
> Heya, thanks for reporting.
> 
> I'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.
> 
> ```shell
> laravel new laravel-issue-37054 --github="--public"
> ```
> 
> After you've posted the repository, I'll try to reproduce the issue.
> 
> Thanks!

Hey, this is the repository of the issue, please take a look:
https://github.com/locnguyen1842/laravel-issue-37054

Thanks !

**Comment by driesvints** [comment] 2021-04-22 14:32
This seems like a legitimate bug to me. I'm not sure how to solve this one though. Adjusting the `associate` method is an option maybe but it could imply a breaking change.

**Comment by taylorotwell** [comment] 2021-04-22 14:47
Duplicate of https://github.com/laravel/framework/issues/36644

Use the `disassociate` method before associating with an entirely new model.

**Closed by taylorotwell** 2021-04-22 14:47 UTC
Labels: bug
