### ISSUE TITLE
Overriding .env values for PHPUnit fails when it comes to booleans

### ISSUE THREAD

**Issue by fgreinus** [laravel/framework#18822] opened 2017-04-17 11:26 UTC
- Laravel Version: 5.4.18
- PHP Version: 7.1.4
- Database Driver & Version: MySQL (not related)

### Description:
I was trying to override a .env config value that can either be true or false. While staying within the application everything works just fine. So for my PHPUnit test runs, i want to "hardcode" this value using the env-configuration in my phpunit.xml (just like it's possible for APP_ENV etc.).
But it seems, that the value somehow gets badly parsed (when my env is set to "true" it results in being "1" within the application, "false" results in "").
I found an issue at the phpunit-project: https://github.com/sebastianbergmann/phpunit/issues/2331.
I don't know if this has something to to with the problem I described, but as this has been closed a while ago, i'm unsure how to go on.

### Steps To Reproduce:
Add a .env config (i.e. ACTIVATE_FEATURE_X=true). When you want to override it for your phpunit environment, add it in phpunit.xml (phpunit->php is the xml path where to add it):
`<env name="ACTIVATE_FEATURE_X" value="false"/>`

Now, when you run tests and request env('ACTIVATE_FEATURE_X') it returns "", but should return false. When you set ACTIVATE_FEATURE_X to true in phpunit.xml it returns "1".

**Comment by themsaid** [comment] 2017-04-17 12:03
It looks like that's related to the issue you shared on PHPUnit Repo, looks like you'll need to run your boolean values through a filter before using the stored values.

Closing since the issue is in PHPUnit.

**Closed by themsaid** 2017-04-17 12:03 UTC

**Comment by fgreinus** [comment] 2017-04-17 12:12
Okay, thanks for the super fast reply 👍

**Comment by zlanich** [comment] 2018-05-09 05:45
I know this issue is old, but for those who stumble upon it like I did looking for clarity, I solved the issue by doing the following:

`phpunit.xml`:
```xml
...
    <php>
        <env name="APP_ENV" value="testing"/>
    </php>
</phpunit>
```

`.env.testing`:
```
YOUR_OTHER_ENV_VARS=stuff
YOUR_BOOLEAN_ENV_VARS=true
```

That way Laravel handles the env vars correctly. Just don't use `artisan config:cache` as that severely messes things up in phpunit. I actually do the following to make sure everything is cleared for reliability in my tests because I went through hours of headache only to realize my tests were failing because I ran `config:cache` at some point.:
```php
abstract class TestCase extends BaseTestCase
{
    //...
    public function createApplication()
    {
        //...
        $this->clearCache();

        return $app;
    }

    protected function clearCache()
    {
        $commands = ['clear-compiled', 'cache:clear', 'view:clear', 'route:clear', 'config:clear'];
        foreach ($commands as $command) {
            \Illuminate\Support\Facades\Artisan::call($command);
        }
    }
}
```
