### ISSUE TITLE
Why HasOneOrMany doesn't update relations on parent?

### ISSUE THREAD

**Issue by romulets** [laravel/framework#14719] opened 2016-08-09 15:38 UTC
Hi,

We are developing an e-commerce cart, which has items. So our cart has a 1:n relationship to items.

When we add some product to cart using `Illuminate\Database\Eloquent\Relations\HasOneOrMany::save()` it doesn't push the new item to our `$cart->items` collection, it has to be done manually using `Collection::push()` method.

We are asking this because the `Illuminate\Database\Eloquent\Relations\BelongsTo::associate()` method does that, so we don't know if this is a bug.

Just for better understanding: 

Now we need to do this:
``` php
$cart = Cart::first();

$cartItem = new CartItem();
$cartItem->quantity = 1;
$cartItem->base_price = 1;
$cartItem->paid_price = 1;

$cart->items()->save($cartItem);
print($cart->items->count()); # returns 0
$cart->items->push($cartItem);
print($cart->items->count()); # returns 1
```

What we want to do is this code above, and then be able to interate with our list (for example update order values), without calling other methods.
``` php
$cart = Cart::first();

$cartItem = new CartItem();
$cartItem->quantity = 1;
$cartItem->base_price = 1;
$cartItem->paid_price = 1;

$cart->items()->save($cartItem);
print($cart->items->count()); # returns 1
```

We saw the code and it can be done, but is it correct?

Thanks

**Comment by patrickcarlohickman** [comment] 2016-08-25 08:29
This is discussed on issue #12180.

Basically, it would be very complicated to attempt to update a relationship `Collection` with new items, since you'd have to parse any constraints on the relationship to determine if it should exist in the `Collection`, and if so, where in the `Collection` to put it.

**Comment by themsaid** [comment] 2016-09-06 20:23
Looks like a duplicate of #12180. Closing then :)

**Closed by themsaid** 2016-09-06 20:23 UTC
