### ISSUE TITLE
DB query incorrectly returning NOW() as created_at column value

### ISSUE THREAD

**Issue by jtallant** [laravel/framework#18455] opened 2017-03-22 23:06 UTC
- Laravel Version: 5.4.14
- PHP Version: 5.6.14
- Database Driver & Version: MySQL 5.7.9 InnoDB 

### Description:
When I perform a query, all returned models show a created at value of NOW() (whatever time I ran the query), when the actual values are not NOW()

If I add an extra column to the query (manually adding a created column), it returns the correct date.

I am using twig for templating engine but it has nothing to do with that. I can see the incorrect values if I dump right from the controller.

I tried with and w/o paginate, still same problem.

### Steps To Reproduce:

```php
$users = \DB::table('users as u')
    ->join('addresses as a', 'u.id', '=', 'a.user_id')
    ->join('attendances as atts', 'u.id', '=', 'atts.user_id')
    ->select('u.*', 'a.*', \DB::raw('COUNT(atts.user_id) as attendance_count'), 'u.created_at as created')
    ->groupBy('u.id', 'a.id')
    ->latest('u.created_at')
    ->simplePaginate(50)
;
```

```twig
{% for user in users %}
    <tr>
        <td>{{ user.id }}</td>
        <td><a href="{{ route('users.show', user.id) }}">{{ user.first_name }} {{ user.last_name }}</a></td>
        <td>{{ user.email }}</td>
        <td>{{ user.city }}, {{ user.state }}</td>
        <td>{{ user.zip }}</td>
        <td>{{ user.created|date('m/d/Y') }}    {# show correct #}
        <td>{{ user.created_at|date('m/d/Y') }} {# shows now #}
        <td>{{ user.attendance_count }}
    </tr>
{% endfor %}
```

user data is fake:

<img width="563" alt="screen shot 2017-03-22 at 5 52 52 pm" src="https://cloud.githubusercontent.com/assets/857110/24224617/0477f314-0f2a-11e7-8442-8f40443fdfd2.png">

**Comment by jtallant** [comment] 2017-03-22 23:44
I see what is going on. Both users and addresses have a created_at column, eloquent is favoring the most recently joined column value as the one that gets populated in the object. Not sure if that is the desired behavior or not.

**Comment by Dylan-DPC** [comment] 2017-03-23 07:55
what's the value in the db?

**Comment by stefanoruth** [comment] 2017-03-23 09:01
The problem lies in the a.* and u.* you should be more specefik that using star when both tables have the same column names. either that or use eloquent relations instead

**Comment by Dylan-DPC** [comment] 2017-03-23 11:24
@stefanoruth he has done a select query and aliased the `created_at` columns. So there is something else that is wrong here (which could be in code that he hasn't shared here)

**Comment by kudm761** [comment] 2017-03-23 14:53
@jtallant hi, you should explicitly specify list of columns to select, because how eloquent (or other application) will know which column: `addresses.created_at` or `users.created_at` use to form an object from set of fields ? :)
Also it is a good practice to specify columns and not use `*` - less amount of data will be transferred from mysql-server to mysql-client; it decreases amount of data reading from disk; covering indexes may be used.
Also you use `group by` - it is good practice to follow [standard](https://dev.mysql.com/doc/refman/5.6/en/group-by-handling.html)  and specify all columns from `SELECT` in `GROUP BY` or use aggregate functions because you can receive unexpected values otherwise.
For example - if you will group by some not unique field (e.g. `first_name`) mysql will not know what `created_at` value get from each group to form final result.

**Comment by themsaid** [comment] 2017-03-23 17:06
@jtallant yes you need to specify which table you'd like to get the column value from in case the tables joined has the same column.

Closing the issue as not a bug in the framework.

**Closed by themsaid** 2017-03-23 17:06 UTC
