### ISSUE TITLE
Laravel Pagination does not support display all record

### ISSUE THREAD

**Issue by joko-wandiro** [laravel/framework#16578] opened 2016-11-29 03:39 UTC
- Laravel Version: 5.2
- PHP Version: PHP 5.6.8
- Database Driver & Version: 5.6.24 MySQL Community Server

### Description:
Laravel Pagination does not support display all record. If record per page is not set it will set default record per page to 15. Do Laravel Pagination have method to display all record ?

**Comment by themsaid** [comment] 2016-11-29 13:03
If you need to display all why use Pagination at all?

Anyway closing since this is not a bug report, feel free to ping me though.

**Closed by themsaid** 2016-11-29 13:03 UTC

**Comment by joko-wandiro** [comment] 2016-12-01 02:01
It support select record per page using select box and can display all record

**Comment by ArielPremiumSupply** [comment] 2018-03-15 16:14
The reason it seems to me would be so that the user could toggle between paginated view and viewing all without having to throw a view all button awkwardly outside the pagination links list. The right behavior would be to have the "view all" button just before the next  » link and to be shown as the active selected state. This is an interface design issue to solve without having to go outside of the laravel native pagination methods.

**Comment by dotZoki** [comment] 2018-03-19 13:30
I also have situation where results can be paged or a client could request all records.  i.e. passing per-page param with -1 value to paginator would keep controller code shorter and simpler.

**Comment by Blair2004** [comment] 2018-05-04 01:35
Well, i was looking for a solution about displaying all record using the paginate method. It seems like i'll have to count that manually on the script.

**Comment by Blair2004** [comment] 2018-05-04 01:38
@joko-wandiro here is that, 2 years later :)
```php
// $query is an instance of Illuminate\Support\Facades\DB;
if ( $perPage == false ) {
     $perPage    =   $query->count();
}

return $query->paginate( $perPage );
```

**Comment by browner12** [comment] 2019-06-13 16:00
https://github.com/laravel/framework/pull/28834  if you guys are interested.

**Comment by mrb2590** [comment] 2019-06-21 15:49
> @joko-wandiro here is that, 2 years later :)
> 
> ```
> // $query is an instance of Illuminate\Support\Facades\DB;
> if ( $perPage == false ) {
>      $perPage    =   $query->count();
> }
> 
> return $query->paginate( $perPage );
> ```

I believe the issue with this is the paginator also performs a count() to see how many pages, so this would do two count queries.

**Comment by hemmy6894** [comment] 2019-07-15 08:11
```
class PaginatorHelper{
public static function per_page_helper($perPage){
        if(isset($_GET['per_page'])){
            if(!empty($_GET['per_page'])){
                $per_page = $_GET['per_page'];
                if(is_numeric($per_page)){
                    if($per_page > 0){
                        return $per_page;
                    }else{
                        return 999999999;
                    }
                }else if($per_page == 'all'){
                    return 999999999;
                }else{
                    return 0;
                }
            }
        }
        
        if(is_numeric($perPage)){
            if($perPage > 0){
                return $perPage;
            }else{
                return 999999999;
            }
        }
    }
}
```





Call this function on Model::paginate(PaginatorHelper::per_page_helper($perPage))

not safe to change since on update will be removed
or update Model (..\vendor\illuminate\database\Eloquent\Model.php)


from 

```
public function getPerPage()
    {
        return $this->perPage;
    }
```

to 

```
public function getPerPage()
    {
        return DatabaseHelper::per_page_helper($this->perPage);
    }
```

**Comment by EngBett** [comment] 2020-01-16 07:46
`$alldata = Data::where('id','>',0)->paginate(10);`

**Comment by goldnetonline** [comment] 2020-02-05 15:03
Old post but here's a valid use case.

You are building an api and you have a set data schema which is the output of `Illuminate\Paginator\LengthAwarePaginator` which you can always throw the limit parameter to. But you want to get all data and still maintain same schema.

@joko-wandiro solution might run a repetitive query but it works.

I believe its a valid feature request.

**Comment by jariesdev** [comment] 2020-05-13 15:38
@mrb2590 If you are concern with query roundtrips you can get all the data then make pagination out of it. Please note this will be very slow for large records. 

```
$query = User::query();
$perPage = $request->get('perPage', 20);

if ($perPage === -1) {
   $results = $query->get();
   return new LengthAwarePaginator($results, $results->count(), -1);
} else {
   return $query->paginate($perPage);
}
```

**Comment by maximogithub** [comment] 2020-09-11 13:59
using livewire  i check the variable in the select option 

{{ ($perPage == 'all') ? '' : $users->links() }}

i hope may help

**Comment by acirinelli** [comment] 2021-03-11 01:00
Probably a pointless comment by now, but I also have a use case for this. I am passing filter parameters to a function that paginates the results. I need to sum/calculate values from all of the results to show on the first page, while still being able to click through pages with vue.js and not have the sums change by page.

**Comment by Healyhatman** [comment] 2021-08-18 06:30
I don't know if it's SUPPOSED to do it, but paginate(-1) gives me all items which works just fine for me thanks
