### ISSUE TITLE
makeVisible() after pagination change structure of toJson() (or toArray()) 

### ISSUE THREAD

**Issue by mvsvolkov** [laravel/framework#16501] opened 2016-11-22 15:08 UTC
- Laravel Version: 5.3
- PHP Version: 7.0

### Description:
after _paginate()_ method it normally return's json object, with "_total_", "_per_page_" and other params and "_data_" key, collecting Users Collection

after _paginate()->makeVisible('field')_ result contain's only Users Collection

### Steps To Reproduce:
Fresh Laravel 5.3 installation

```php
Route::get('/', function () {
    return \App\User::where('id', '>', '1')->paginate(5);
});
```
it return's normal pagination json object

```json
{
    "total": 23,
    "per_page": 2,
    "....other_fields": "valuesssss",
    "data": [
        {
            "id": 4,
            "name": "Susie Leuschke I",
            "email": "othiel@example.com"
        },
        {
            "id": 5,
            "name": "Pearl Schneider II",
            "email": "eullrich@example.org"
        }
    ]
}
```

after cast _makeVisible()_ method  
```php
Route::get('/', function () {
    return \App\User::where('id', '>', '1')->paginate(5)->makeVisible('password');
});
```

only Users Collection

```json
[
    {
        "id": 4,
        "name": "Susie Leuschke I",
        "email": "othiel@example.com",
        "password": "blabla"
    },
    {
        "id": 5,
        "name": "Pearl Schneider II",
        "email": "eullrich@example.org",
        "password": "blabla"
    }
]
```

i use stupid _where_ condition for example, because it's return **Builder** object, which has no method to make fields visible

**Comment by themsaid** [comment] 2016-11-22 20:26
That's because `makevisible()` returns a Collection not a LengthAwarePaginator instance, so this is an intended behaviour, if you want to alter the collection inside the paginator but still have access to the paginator instance you can use `getCollection`, alter it, and put it back into `setCollection()`.

Closing this issue since it's not a bug, but feel free to open a PR with a proposed change if you have any.

**Closed by themsaid** 2016-11-22 20:26 UTC

**Comment by armavion** [comment] 2018-09-23 04:56
@themsaid Thanks a lot!

**Comment by JBtje** [comment] 2019-03-05 12:36
I think a small example would be in place, since `setCollection` is not well documented...

```
    $query = Task::where( 'tasktype', 'Eat' );
    $resource = $query->paginate( 15 );
    $resource->setCollection( $resource->getCollection()->makeVisible( 'created_at' ) );
```

Note, `setCollection` is only available for instances of `AbstractPaginator`

**Comment by OrkhanAlikhanov** [comment] 2021-05-06 18:17
Following works as well:
```php
$query = Task::where('tasktype', 'Eat');
$resource = $query->paginate(15);
$resource->makeVisible('created_at');
```
