### ISSUE TITLE
make() and save() methods behavior changes in 5.4.27? 

### ISSUE THREAD

**Issue by chimit** [laravel/framework#20408] opened 2017-08-03 10:22 UTC
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
In my unit tests (with API testing) I always used this construction to create models and relationships:
```php
$this->user = factory('App\Models\User')->make();
$this->organization->users()->save($this->user);

$this->actingAs($this->user)
    ->put('/v1/some', [
        'name' => 'Someone',
    ])
```
In `illuminate/database` 5.4.19 it worked perfectly. The user model and its relationship with the organization were persisted in the DB, but after upgrade to 5.4.27 my unit tests started failing. I discovered that unlike `create` method `make` and `save` methods together don't persist data in the DB anymore.

So the only way I found to solve this problem is to replace `make` with `create`:
```php
$this->user = factory('App\Models\User')->create();
$this->organization->users()->save($this->user);

$this->actingAs($this->user)
    ->put('/v1/some', [
        'name' => 'Someone',
    ])
```
Can anybody clarify? Is it a bug?

**Comment by Dylan-DPC** [comment] 2017-08-04 06:02
From docblocks of `make` method: 

> Create and return an un-saved model instance.

**Comment by chimit** [comment] 2017-08-04 06:25
@Dylan-DPC yes, because of it I save it on the next line with `save()`.

The problem was caused by this pull request https://github.com/laravel/framework/pull/19568/files which changed the `contains()` method behavior. Currently, the `contains()` method works incorrectly.

**Comment by chimit** [comment] 2017-08-04 09:57
Apparently, the bug appears when you use model factories:
```php
$device = factory('App\Models\Device')->create();
$user = factory('App\Models\User')->make();
$device->users()->save($user);
dd($device->users->contains($user)); // false, but should be true
```

**Comment by themsaid** [comment] 2017-08-04 18:52
Sorry the bug is unclear:

```
$device = factory('App\Models\Device')->create();
$user = factory('App\Models\User')->make();
$device->users()->save($user);
```
testing this, the user is stored and attached to the device correctly, what's the issue?

**Comment by djh101** [comment] 2017-08-04 21:34
The issue is `$this->getConnectionName()`. When you create a model using the factory it seems that it doesn't set the connection name. _contains_ then fails because it uses the _is_ method which checks not just the keys but also the table name and the connection name.

**Comment by djh101** [comment] 2017-08-04 21:59
Apparently if you create a model using _create_ the connection gets set during _newInstance_ but if you use _new_ or a factory then it doesn't get set during creation.

**Comment by chimit** [comment] 2017-08-10 10:36
So how should I pass my old unit tests? Is replacing `make` with `create` a right way?

From
```php
$this->user = factory('App\Models\User')->make();
$this->organization->users()->save($this->user);
```
To
```php
$this->user = factory('App\Models\User')->create();
$this->organization->users()->save($this->user);
```

**Comment by themsaid** [comment] 2017-08-10 10:42
@chimit yes I see nothing wrong about that, the thing is the change fixed another part in Laravel, so if we revert we'll be breaking it as well. that's the dilemma :)

**Comment by djh101** [comment] 2017-08-10 19:14
If #20466 makes it into 5.6 without getting reverted it should fix your issue.

**Comment by themsaid** [comment] 2017-08-11 16:40
Closing since there's no intention in rolling this back, I'm sorry I know it's frustrating to have a breaking change like that but seems like a revert would break multiple other places :)

As @djh101 in 5.5 this has been taken care of.

**Closed by themsaid** 2017-08-11 16:40 UTC
Labels: more info?
