### ISSUE TITLE
[Potential Bug] Gate with policies doesn't work as intented

### ISSUE THREAD

**Issue by dejan7** [laravel/framework#14135] opened 2016-06-24 21:59 UTC
In the docs here 

https://laravel.com/docs/5.2/authorization#checking-policies

it says that when a policy is defined like this:

```
class PostPolicy
{
    /**
     * Determine if the given post can be updated by the user.
     *
     * @param  \App\User  $user
     * @param  \App\Post  $post
     * @return bool
     */
    public function update(User $user, Post $post)
    {
        return $user->id === $post->user_id;
    }
}
```

we can use

```
Gate::denies('update', $post)
```

So i assumed that i can use

```
Gate::forUser($user)->denies('update', $post)
```

However this ALWAYS returns false

Because firstArgumentCorrespondsToPolicy() in Illuminate\Auth\Access\Gate always returns false:

```
protected function firstArgumentCorrespondsToPolicy(array $arguments)
{
    if (! isset($arguments[0])) {
        return false;
    }

    if (is_object($arguments[0])) {
        return isset($this->policies[get_class($arguments[0])]);
    }

    return is_string($arguments[0]) && isset($this->policies[$arguments[0]]);
}
```

It basically checks arguments i.e. it checks if the first argument is a class of a Model that has policies registered. So basically we could make the Gate call to work by rewritting the "denies" into:

```
Gate::forUser($user)->denies('update', [User::class, $post])
```

But i'm pretty sure that this is not the intended use? 

Now i'm not sure if i missed something or if it's caused by the forUser method. But if it is a bug indeed i'd be happy to try to fix and and to submit a pull request.

**Comment by ctf0** [comment] 2016-06-26 09:54
i believe the issue is related to the `forUser` , also the `firstArgumentCorrespondsToPolicy` it means its related to the model policy, so ex. `user is user policy & user model , post is post policy & post model` ,

also in the policy the `User $user` will always return the currently logged in user, so no need to pass it from the controller but anyway i think what is more related to ur needs is either `$this->authorizeForUser($user, 'update', $post);` or `Via The User Model`

**Comment by ewstefan** [comment] 2016-07-21 16:04
In case you were trying to bind a policy to your user class, like so

```
class AuthServiceProvider extends ServiceProvider
{
    protected $policies = [
        \App\User::class => \App\Policies\UserPolicy::class
    ];
...
```

then calling
`Gate::forUser($user)->allows(...) `
or calling
$user->can($ability)

will always return false, as firstArgumentCorrespondsToPolicy returns false as you mentioned.

In my case, I wanted to have general user privileges, which I first intended to check via a UserPolicy that is bound to the User Class.

But apparently there is no such thing like binding a policy to the user class. You always check policies in the context of another class, such as a post.

So I ended up introducing a Privileges object and a policy for it:

```
class AuthServiceProvider extends ServiceProvider
{
    protected $policies = [
        \App\Domain\User\Privileges::class => \App\Domain\User\PrivilegesPolicy::class
    ];
...
```

```
class Privileges
{
	static $privileges = array(
		'can-do-something' => array(

			Role::ROLE_A	=> true,
			Role::ROLE_B	=> false,
		),
	);


	public function get($privilege, $user)
	{
		return static::$privileges[$privilege][$user->role()];
	}

}


<?php

class User extends Authenticatable
{
...
    public function can($ability, $arguments = [])
    {
        if ($arguments) {
            return parent::can($ability, $arguments);
        }
        else {
            return parent::can($ability, $this->getPrivileges());
        }
    }

    public function has($privilege)
    {
        // syntactic sugar to allow for calls like $user->has('searchMenu');
        return parent::can($privilege, $this->getPrivileges());
    }

    private function getPrivileges()
    {
        if (! $this->privileges) {
            $this->privileges = new Privileges();
        }

        return $this->privileges;
    }
}

```

**Comment by malhal** [comment] 2016-09-06 15:07
Just wondering...why are you trying to use a different user from the default?

**Comment by thachp** [comment] 2016-09-20 18:55
I am having similar issues; it seems the methods in policy class never got execute.   I followed the example in the tutorial, except that I never "got here" in the update() method.

    public function update(User $user, Post $post)
    {
    	die("got here");
        return $user->id === $post->user_id;
    }

https://laravel.com/docs/5.3/authorization#generating-policies

**Comment by MladenJanjetovic** [comment] 2016-09-26 12:01
Take a look at this one https://github.com/laravel/framework/issues/13788
It could be the default guard issue.

**Comment by Dylan-DPC** [comment] 2017-10-16 21:20
Hi. Can you try this on a 5.5 install and see if the issue still arises? If not you can close this issue

**Comment by themsaid** [comment] 2017-11-29 11:41
Closing this issue since we made lots of changes in 5.4 and 5.5 regarding this, please ping me if anyone was able to tell if the issue still exists in 5.5

**Closed by themsaid** 2017-11-29 11:41 UTC
