### ISSUE TITLE
Single-quoted strings with [ ] in Laravel Log interpreting escape characters (\r \n)

### ISSUE THREAD

**Issue by Yousha** [laravel/framework#53482] opened 2024-11-12 15:49 UTC
### Laravel Version

11.30.0

### PHP Version

8.3.13 64bit TS

### Description

When logging with **single-quoted** `'` strings that containing **escape characters** like `\r ` and `[ ]`, they are being **interpreted** in the log output. This results in unexpected behavior, such as `\r` being converted to a **carriage return**, even though single-quoted strings in PHP treat backslashes as literal characters.

Using **Illuminate\Support\Facades\Log**
With default logging configuration.

### Steps To Reproduce

**1-** Download and create a Laravel 11 application project. (https://laravel.com/docs/11.x)

**2-** In any route, controller, or model file, log a string using single-quotes with a backslash `\r` and bracket `[ ]`.
Example:
`Log::info('[MyNamespace\routes\non-web\application]');`

**3-** Check the Laravel log file.

**Expected output**
> local.INFO: [MyNamespace\routes\non-web\application]

**Actual output**
> local.INFO: [MyNamespace
> outes
> on-web\application]

**Comment by cosmastech** [comment] 2024-11-15 19:06
I think the issue here is caused by this: https://github.com/Seldaek/monolog/blob/32e515fdc02cdafbe4593e30a9350d486b125b67/src/Monolog/Formatter/LineFormatter.php#L241

If the first character in the log is `[` or `{` then it replaces those substrings with `"\n"`

**Comment by crynobone** [comment] 2024-12-05 09:33
Since the formatting is handled by Monolog, I don't see anything we can do on our end here. Closing this for now.

**Closed by crynobone** 2024-12-05 09:33 UTC
Labels: help wanted

**Comment by yousha-eleganthoopoe** [comment] 2024-12-06 15:15
I just tested Monolog 3.8 and 3.0, and it works like a charm.

It seems some wrappers in Laravel or other libraries are affecting the logging mechanism.
