### ISSUE TITLE
[5.3] Notifications mark all as read

### ISSUE THREAD

**Issue by alexbowers** [laravel/framework#14788] opened 2016-08-12 14:12 UTC
The ability to mark all as read in a clean readable way will be useful.

Two ideas currently:

```php
 $user->notifications->markAllAsRead(); // Will affect all
 $user->notifications->markAsRead(); // If on collection will affect all, if on individual will affect one.
```

I'll work on a PR for this tonight.

**Comment by kevdotbadger** [comment] 2016-08-19 10:19
Seems that this has been added in https://github.com/illuminate/notifications/commit/dc564dc6b20c4633010c67cdd5ece5d1c550999f, `Illuminate\Notifications\DatabaseNotificationCollection`, so you can call `->markAsRead()` on a collection of notifications - like `$user->notifications->markAsRead()`.

**Comment by alexbowers** [comment] 2016-08-19 10:25
The issue there is that it is not an efficient way to do it.

If it is a collection, it shouldn't really do an `each`, since it will perform a query for each notification rather than an update query to update all notifications at once.

**Comment by fgambino** [comment] 2016-08-20 05:39
I agree that the collection method is encouraging bad practices with obvious performance implications. Most users won't know that it's doing that.

**Comment by themsaid** [comment] 2016-09-06 08:29
Hey Alex, did you get the chance to create a PR with this enhancement?

I'm closing this since it's not a bug report, but you can create the PR and continue discussion there :)

**Closed by themsaid** 2016-09-06 08:29 UTC

**Comment by alexbowers** [comment] 2016-09-06 08:31
This was only an efficiency style thing, but i couldn't figure out a way to get the events to fire, so figured it was better to not change anything.

**Comment by themsaid** [comment] 2016-09-06 08:32
Yeah, that's a good point. The events are really useful in such case.
