### ISSUE TITLE
The environment file is .env.local when octane started, why is not .env?

### ISSUE THREAD

**Issue by ToogleLiu** [laravel/framework#42730] opened 2022-05-27 06:20 UTC
- Octane Version: 1.2.9
- Laravel Version: 8.83.12
- PHP Version: 8.1.6
- Server & Version: Swoole 4.8.9
- Database Driver & Version: MySQL 8.0.26

### Description:

In my project directory, it has two environment files: *.env* and *.env.local*. The APP_ENV is *local* in env file: 

`APP_ENV=local`

When I run: 

`/usr/local/bin/php /var/www/laravel/artisan octane:start --host=0.0.0.0 --port=8080`

Then octane is running. And I run this codes in octane: 

`return json_encode(['env' => app()->environment(), 'env_file' => app()->environmentFile()]);`

It's return: 

`{"env":"local","env_file":".env.local"}`

But, when I run the same codes in tinker or commands, it's return: 

`{"env":"local","env_file":".env"}`

This is my steps about tinker: 

```shell
php artisan tinker
 >>> return json_encode(['env' => app()->environment(), 'env_file' => app()->environmentFile()]);
 => "{"env":"local","env_file":".env"}"
```

This is my steps about commands: 

```shell
 php artisan run:test
 {"env":"local","env_file":".env"}
```

**The environment file is *.env.local* in octane, but it's *.env* in tinker or commands. This is the problem.** 

Thanks.

**Comment by driesvints** [comment] 2022-06-09 10:14
Moving this to the framework repo for now. I'll have a look soon. Something tells me this is expected with the artisan serve command.

**Comment by fahad-imran** [comment] 2022-06-10 11:02
### **bnbmbn**

**Comment by MrMohamedAbdallah** [comment] 2022-06-29 11:55
I believe that's the expected results. To use `.env` that matches the environment.

https://github.com/laravel/framework/blob/9362a29ce298428591369be8d101d51876406fc8/src/Illuminate/Foundation/Bootstrap/LoadEnvironmentVariables.php#L41

The part on the docs: https://laravel.com/docs/9.x/configuration#additional-environment-files

Related discussion on Laracasts: https://laracasts.com/discuss/channels/laravel/laravel-8-is-using-envlocal-instead-of-env?page=1&replyId=743176

**Comment by driesvints** [comment] 2022-06-30 12:05
@MrMohamedAbdallah the problem is that `artisan tinker` doesn't returns the correct env file.

**Closed** 2022-06-30 12:11 UTC
Labels: needs more info, help wanted
