### ISSUE TITLE
[5.8.15] Trait method credentials has not been applied, because there are collisions with other trait methods

### ISSUE THREAD

**Issue by bobbybouwmann** [laravel/framework#28377] opened 2019-04-30 20:20 UTC
- Laravel Version: 5.8.15
- PHP Version: 7.2

### Description:
The merged PR #28370 is a breaking change for Spark applications. In spark we have the following code:
```
class PasswordController extends Controller
{
    use SendsPasswordResetEmails, ResetsPasswords {
        SendsPasswordResetEmails::broker insteadof ResetsPasswords;
    }

    // ...
}
```
Because both traits now have a credentials method we get the following error
```
Whoops\Exception\ErrorException : Trait method credentials has not been applied, because there are collisions with other trait methods on Laravel\Spark\Http\Controllers\Auth\PasswordController
```
For extra context: https://laracasts.com/discuss/channels/spark/trait-method-credentials-has-not-been-applied-because-there-are-collisions-with-other-trait-methods

I think we either have to revert this PR or rename the method to something else. 

> Note: this is only a problem in the 5.8 branch, not in master

**Comment by driesvints** [comment] 2019-04-30 20:33
I don't consider this a bug in the framework tbh but rather an update should be done to spark instead. Another override like the one above should be applied to the traits I believe.

**Comment by bobbybouwmann** [comment] 2019-04-30 20:39
It's at least a bug in Spark itself, because both traits are included there and they both have the same method. But overriding the method in Spark should fix this as well ;)

**Comment by driesvints** [comment] 2019-04-30 20:59
Going to close this. It's best that you open up an issue on the Spark repo for this.

**Closed by driesvints** 2019-04-30 20:59 UTC
Labels: needs more info

**Comment by rickmacgillis** [comment] 2019-04-30 22:38
I can confirm this bug on my end, and have sent an email to support. I encourage everyone who has this issue to write a message to Spark's support as they don't have issues on GitHub. If you own a license for Spark Aurelius, you'll be able to see the private repo at https://github.com/laravel/spark-aurelius along with their email address.

The more people who report it, the sooner this will get resolved.

**Comment by nbyloff** [comment] 2019-05-01 12:38
I am keeping my version locked at 5.8.14 until Spark addresses it. I imagine since this is a new addition to `SendPasswordResetEmails` a fix could be as simple as:

````
class PasswordController extends Controller
{
    use SendsPasswordResetEmails, ResetsPasswords {
        SendsPasswordResetEmails::broker insteadof ResetsPasswords;
        ResetsPasswords::credentials instead of SendsPasswordResetEmails;
    }

    // ...
}
````

**Comment by driesvints** [comment] 2019-05-01 12:45
I've sent in a PR for this: https://github.com/laravel/spark-aurelius/pull/324

**Comment by driesvints** [comment] 2019-05-01 13:00
Spark 8.1.0 is released now.

**Comment by rickmacgillis** [comment] 2019-05-01 13:07
Thank you, @driesvints!

**Comment by driesvints** [comment] 2019-05-01 13:20
Thanks go to @themsaid as well :)

**Comment by bobbybouwmann** [comment] 2019-05-01 21:26
Thanks @driesvints @themsaid for the quick fix! You guys rock!

**Comment by adam1010** [comment] 2019-05-02 02:22
For those of us that don't have access to going Spark updates, here's the patch:

```php
    use SendsPasswordResetEmails, ResetsPassword {
        SendsPasswordResetEmails::broker insteadof ResetsPassword;
        ResetsPassword::credentials insteadof SendsPasswordResetEmails;
    }
```

**Comment by khanof89** [comment] 2019-05-27 10:44
I am not sure right or wrong but simply creating a credentials function in spark/src/Http/Controllers/Auth/PasswordController.php did the trick 

public function credentials(Request $request) {
        return $request->only('email');
    }

**Comment by danisjohn99** [comment] 2019-08-19 06:12
For those of us that don't have access to going Spark updates, here's the patch:

    use SendsPasswordResetEmails, ResetsPassword {
        SendsPasswordResetEmails::broker insteadof ResetsPassword;
        ResetsPassword::credentials insteadof SendsPasswordResetEmails;
    }
----------------------------------------------------------------------------------------------
change to  "ResetsPasswords" not "ResetsPassword"

use SendsPasswordResetEmails, ResetsPasswords {
        SendsPasswordResetEmails::broker insteadof ResetsPasswords;
        ResetsPasswords::credentials insteadof SendsPasswordResetEmails;
    }

then it will work .otherwise exception will come
