### ISSUE TITLE
Laravel Route parameter whereIn

### ISSUE THREAD

**Issue by LSDx** [laravel/framework#18097] opened 2017-02-24 11:55 UTC
- Laravel Version: 5.4
- PHP Version:  7.1
- Database Driver & Version: MySQL

### Description:
I have route: /{locale}/{page?}
Is it possible to match {page?} with something like ->whereIn('{page}', ['articles', 'contacts', ...]) ?

**Comment by themsaid** [comment] 2017-02-24 13:57
You can use regex for that.

Closing since it's not a bug report.

**Closed by themsaid** 2017-02-24 13:57 UTC

**Comment by sdeav** [comment] 2022-06-01 14:14
I think, now you can do it...
