### ISSUE TITLE
[5.4] Eloquent mutators fail in queue class.

### ISSUE THREAD

**Issue by ac1982** [laravel/framework#17870] opened 2017-02-10 13:37 UTC
- Laravel Version: 5.4.*
- PHP Version:7.1.1
- Database Driver & Version:MySQL 5.7

### Description:
get attribute mutator fail when using it in queue.

### Steps To Reproduce:
set a sample` $payment=['name'=>'Jason','email'=>'abc@abc.com']`

Define accessors first in User Eloquent.
```


    public function setPaymentAttribute($value)
    {
        $this->attributes['payment'] = encrypt(json_encode($value));
    }

    public function getPaymentAttribute($value)
    {
        $decryptJson = decrypt($value);
        return $this->attributes['payment'] = json_decode($decryptJson, true);
    }
```

Get the instance in Queue SendMail.php 
```
    public function __construct($userId)
    {
        $this->user = User::find($userId);
    }

    public function handle()
    {
        Log::info($this->user['payment']); 
 //if in controller or blade, it works fine and return ['name'=>'Jason','email'=>'abc@abc.com']
//but use it here,  local.ERROR: ErrorException: base64_decode()
// expects parameter 1 to be string, array given in 
//vendor\laravel\framework\src\Illuminate\Encryption\Encrypter.php:174
// it is the same if use it in SimpleXMLElement addAttribute method as value.
    }
```

**Comment by themsaid** [comment] 2017-02-10 13:53
Please log `$user->getAttributes()` and share the results.

**Comment by ac1982** [comment] 2017-02-10 15:17
this is my test code in queue handle
 ```
public function handle()
    {
        Log::info($this->user['payment']);
        Log::info($this->user->getAttributes());
        $abc=$this->reservation['payment'];  //remove this line works fine.
        return;
    }
```
[log.txt](https://github.com/laravel/framework/files/767056/log.txt)

**Comment by themsaid** [comment] 2017-02-10 15:49
You said the problem is with `$this->user['payment']` not `$this->reservation['payment']`, I don't think there's something wrong with the framework, I'm sure there's something wrong in your code or the data coming from the DB.

**Comment by themsaid** [comment] 2017-02-10 15:50
It's impossible to find what's wrong when all we can see is just a few lines, please take a deep look into your code base and if you can't find any problems please try to replicate the issue on a fresh laravel installation in a public repo that we can look at.

**Comment by ac1982** [comment] 2017-02-10 16:00
I change the key, it is just test env. so the reservation === user.

**Comment by ac1982** [comment] 2017-02-10 16:02
And I also find
$this->user->update['key'=>'value'];  //local.ERROR: ErrorException: Array to string conversion in vendor\laravel\framework\src\Illuminate\Database\MySqlConnection.php:80

User::where('id',$this->user->id)->update['key'=>'value']; //works fine.

**Comment by themsaid** [comment] 2017-02-10 16:17
Sorry but there seems to be a problem with your code, try to replicate the issue on a public repo that we can look at and ping me when you do it.

Closing the issue for now.

**Closed by themsaid** 2017-02-10 16:17 UTC

**Comment by ac1982** [comment] 2017-02-11 00:31
I figure it out. 
$this->user->payment;   // use this instead of $this->user['payment'], even it could be right in other place.
