### ISSUE TITLE
[5.5] Problem with new many to many relationship (attach, save...)

### ISSUE THREAD

**Issue by ighour** [laravel/framework#20996] opened 2017-09-05 04:29 UTC
- Laravel Version: 5.5.1
- PHP Version: PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper

### Description:
On a Many to Many relationship structure (Model A : Model B), when i instantiate an object of Model A ($objA) and an object of Model B ($objB) and create the relationship between them ($objA->relationship()->attach($objB->id) or $objA->relationship()->save($objB) ), immediately after that, i can use $objB->relationship and get a collection with $objA inside, but when i use $objA->relationship, it always returns an empty collection.

The only way i found to resolve that is to query the $objA again (A::find($objA->id)) after the relationship creation (after that, when i use $objA->relationship it shows a collection with $objB).

I've tried this with artisan tinker and with some tests. The result is the same.

### Steps To Reproduce:

In case, the related models are User and Establishment.

1. [Migration (User x Establishment)](https://gist.github.com/ighour/9d04d1541443f000c82f2c246a36ed2e)
```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class MakeRelationshipOfEstablishmentAndUserAdmin extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('establishment_user', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->unsigned();
            $table->integer('establishment_id')->unsigned();
            $table->timestamps();
            $table->softDeletes();

            $table->unique(['user_id', 'establishment_id']);
            
            $table->foreign('user_id')->references('id')->on('users');
            $table->foreign('establishment_id')->references('id')->on('establishments');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::disableForeignKeyConstraints();
        Schema::dropIfExists('establishment_user');
        Schema::enableForeignKeyConstraints();
    }
}
```

2. [User Model](https://gist.github.com/ighour/15fecd661a8d1aa91935288b76de067a): the relationship is named "establishments".
```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Hashes the password attribute before saving it
     *
     * @param [String] $value
     * @return void
     */
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }
    
    /**
     * Get the role of user
     *
     * @return void
     */
    public function role()
    {
        return $this->belongsTo('App\Role');
    }

    /**
     * Get establishments created by the user
     *
     * @return void
     */
    public function createdEstablishments()
    {
        return $this->hasMany('App\Establishment', 'id');
    }

    public function establishments()
    {
        return $this->belongsToMany('App\Establishment')
                    ->withTimestamps();
    }
}
```

3. [Establishment Model](https://gist.github.com/ighour/de3455a22680cd5b7fe7ae0ebdb9c351): the relationship is named "users".
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Establishment extends Model
{
    use SoftDeletes;
    
    /**
     * Get the establishment creator
     *
     * @return void
     */
    public function creator()
    {
        return $this->belongsTo('App\User');
    }

    public function users()
    {
        return $this->belongsToMany('App\User')
                    ->withTimestamps();
    }
}
```

4. [Factories (User and Establishment)](https://gist.github.com/ighour/e7cedf733c7bf3125876352c65db138e).
```
<?php

use Faker\Generator as Faker;

$factory->define(App\Establishment::class, function (Faker $faker) {
    return [
        'name' => $faker->company,
        'cnpj' => function(){
            $cnpj = mt_rand(10000000000000, 99999999999999);
            return substr($cnpj, 0, 2).'.'.substr($cnpj, 2, 3).'.'.substr($cnpj, 5, 3)
                        .'/'.substr($cnpj, 8, 4).'-'.substr($cnpj, 12, 2);
        },
        'banner' => mt_rand(0,1) == 1 ? $faker->imageUrl($width = 640, $height = 480) : null,
        'views' => mt_rand(0,1) == 1 ? mt_rand(1,2000) : 0
    ];
});
```
```
<?php

use Faker\Generator as Faker;

$factory->define(App\User::class, function (Faker $faker) {
    static $password;

    return [
        'name' => $faker->name,
        'email' => $faker->unique()->safeEmail,
        'username' => $faker->unique()->userName,
        'password' => $password ?: $password = 'secret',
        'cpf' => function(){
            $cpf = mt_rand(10000000000, 99999999999);
            return substr($cpf, 0, 3).'.'.substr($cpf, 3, 3).'.'.substr($cpf, 6, 3).'-'.substr($cpf, 9, 2);
        },
        'birthday' => $faker->date($format = 'Y-m-d', $max = '2010-12-31'),
        'sex' => mt_rand(0,2) == 0 ? null : (mt_rand(0,1) == 0 ? 'M' : 'F'),
        'confirmed' => 1,
        'remember_token' => str_random(10),
        'role_id' => function(){
            if(!\App\Role::where('name', 'Admin')->first())
                \App\Role::create(['name' => 'Admin']);
            if(!\App\Role::where('name', 'Client')->first())
                \App\Role::create(['name' => 'Client']);
            if(!\App\Role::where('name', 'Establishment')->first())
                \App\Role::create(['name' => 'Establishment']);

            return \App\Role::inRandomOrder()->first()->id;
        }
    ];
});
```

5. (Try 1) Using Artisan Tinker:
```
php artisan tinker
$u = factory('App\User')->create();
$e = factory('App\Establishment')->create();
$e->users()->attach($u->id);
$u->establishments;
$e->users;
$e = \App\Establishment::find($e->id);
$e->users;
```
->It only works with the 2nd ($e->users;).

6. (Try 2) [Using Tests](https://gist.github.com/ighour/d2e73cddf8d8d4fefc434cb1ad0492c0).
->Not working:
```
<?php

namespace Tests\Unit\Relationships;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class UserEstablishmentTest extends TestCase
{

    use RefreshDatabase;

    /** @test */
    public function an_establishment_may_have_admins_or_not()
    {
        $establishment = factory('App\Establishment')->create();

        $this->assertEquals($establishment->users->count(), 0);

        $user = factory('App\User')->create();

        $establishment->users()->save($user);

        $this->assertEquals($establishment->users->first()->id, $user->id);
    }

}
```
->Working:
```
<?php

namespace Tests\Unit\Relationships;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class UserEstablishmentTest extends TestCase
{

    use RefreshDatabase;

    /** @test */
    public function an_establishment_may_have_admins_or_not()
    {
        $establishment = factory('App\Establishment')->create();

        $this->assertEquals($establishment->users->count(), 0);

        $user = factory('App\User')->create();

        $establishment->users()->save($user);

        $establishment = \App\Establishment::find($establishment->id);

        $this->assertEquals($establishment->users->first()->id, $user->id);
    }

}
```

**Comment by themsaid** [comment] 2017-09-05 10:20
Yes you need to reload the relationship after attaching/detaching.

Closing since it's not a bug but feel free to ping me for further discussion.

**Closed by themsaid** 2017-09-05 10:20 UTC
