### ISSUE TITLE
Route cache not recognizing routes with trailing '/'

### ISSUE THREAD

**Issue by Elena0308** [laravel/framework#31802] opened 2020-03-06 15:27 UTC
- Laravel Version: 7.0.5
- PHP Version: 7.4.2
- Database Driver & Version:

### Description:
When the routes are not cached, the framework is resolving a given route with and without a trailing '/', but after caching the same route is not recognized when having a '/' at the end. Interesting thing is that if I try doing a GET request to a POST route, including a trailing '/', I am getting HTTP 405.

**Comment by driesvints** [comment] 2020-03-06 15:28
Duplicate of https://github.com/laravel/framework/issues/31768

**Closed by driesvints** 2020-03-06 15:28 UTC
