### ISSUE TITLE
Nullable MorphTo problem since 5.7.20

### ISSUE THREAD

**Issue by dtvmedia** [laravel/framework#27175] opened 2019-01-15 14:16 UTC
- Laravel Version: 5.7.20
- PHP Version: 7.2.10

### Description:
Since the update to 5.7.20 we have problems with our nullable morphTo relations. For example we have an relation for the last editor of an record which uses such relation because we support different kind of users. Means we have these 2 columns:
```
- updated_from_id
- updated_from_model
```

Our relation looks like the following:
```
public function updatedFrom()
{
     return $this->morphTo( null , 'updated_from_model' , 'updated_from_id' );
}
```

Due to the fact that the database columns are nullable we expect that we can set the updated_from_model column to NULL. But if we do so, we get an SQL Error by calling the relation (e.g. for an article):
```
ErrorException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'articles.' in 'where clause'
(SQL: select * from `articles` where `articles`.`` = 0 and `articles`.`deleted_at` is null limit 1)
```
If we set the update_from_model to a valid model and leave the updated_from_id column 0 it works fine again.

### Expected Result
Up to version 5.7.19 the result would be just NULL when calling the relation if the update_from_model is NULL.

**Comment by driesvints** [comment] 2019-01-15 15:50
@staudenmeir is this related to https://github.com/laravel/framework/pull/27031 ?

**Comment by dallincoons** [comment] 2019-01-15 21:39
We've had the same problem which we fixed by explicitly passing the key, but it's a shame that a minor release had breaking changes like this.

**Comment by staudenmeir** [comment] 2019-01-16 01:16
You have a model where `updated_from_model` is `null` but `updated_from_id` isn't?

**Comment by bastian-schur** [comment] 2019-01-16 08:38
> You have a model where `updated_from_model` is `null` but `updated_from_id` isn't?

This is a very good idea, if I set the updated_from_id to null the problem is solved for me

**Comment by dtvmedia** [comment] 2019-01-16 11:17
> 
> 
> You have a model where `updated_from_model` is `null` but `updated_from_id` isn't?

Yeah I admit that's probably not 100% correctly on our end because the `updated_from_id` is `0` in this specific case. Nevertheless I think it shouldn't fail if with the given morph combination no model could be retrieved (which should include that `updated_from_model` is `null`). Instead it should return just `null` as before or is there a particular reason for this new behaviour?

**Comment by y-morozov** [comment] 2019-01-28 15:11
The problem is $ownerKey is never assigned in case of type field is null.

Here:
```
return empty($class = $this->{$type})
    ? $this->morphEagerTo($name, $type, $id, $ownerKey)
    : $this->morphInstanceTo($class, $name, $type, $id, $ownerKey);
```

`morphInstanceTo()` fills `$ownerKey` by calling `$instance->getKeyName()`, and `morphEagerTo` is not.

**Comment by noahzgard** [comment] 2020-02-18 13:12
As i understand problem happens after changes in src/Illuminate/Database/Eloquent/Relations/MorphTo.php, to be precise after removing of this function `
    /**	
     * Get the results of the relationship.	
     *	
     * @return mixed	
     */	
    public function getResults()	
    {	
        return $this->ownerKey ? parent::getResults() : null;	
    }
`

**Comment by driesvints** [comment] 2020-04-09 10:30
@dtvmedia I'm re-looking into this. Can anyone please post full steps to reproduce this problem?

**Comment by dtvmedia** [comment] 2020-04-09 11:20
@driesvints Back then the problem was that in case `updated_from_id` was `0` and `updated_from_model` was `null` the morphTo relation would fail (see initial example). Before the Update to version 5.7.20 this combination would return just `null`. As this issue is over an year old I have no current test case. Back then we switched the `updated_from_id` to `null` as suggested which "fixed" it for us.

**Comment by driesvints** [comment] 2020-04-09 11:21
I think that's indeed the proper solution.

**Closed by driesvints** 2020-04-09 11:21 UTC
Labels: needs more info

**Comment by gbradley** [comment] 2021-07-08 10:37
I've come across this issue in a legacy application which uses morphTo in a slightly odd way that can't be fixed by setting the column to `0`. Essentially there is a `tags` table with a `value` column. These values can sometimes be IDs refering to other models - in which case `$ownerKey` is non-null - or in other cases are just arbitrary strings like `"Foo"`, in which case `$ownerKey` is null.

Prior to #26992 this worked as the `MorphTo` class checked for a nullable `$ownerKey` and just returned null in this case. The removal of this check now breaks this, admittedly rare, use-case. 

Is there a good reason the above check could not be re-instated?

**Comment by sinemacula** [comment] 2022-03-18 11:52
> I think that's indeed the proper solution.

Hi @driesvints - I do not believe this issue is fixed, and if I have understood the suggested solution correctly, this does not resolve the issue.

The issue is quite easy to replicate; Just create a `nullableUuidMorphs` in a migration, and then try to query that relation (use `morphTo` to define the relation).

For example, this is my relation on my `Referral` model:

```
/**
 * Get the referrer.
 *
 * @return \Illuminate\Database\Eloquent\Relations\MorphTo
 */
public function referrer(): MorphTo
{
    return $this->morphTo();
}
```

Let's assume that my `Referral` model does not have a `referrer` i.e. `referral_type` and `referral_id` are both `null`...

If I call `$referral->referrer`, the expected result would be `null` - this WORKS
If I call `$referral->referrer()->first()` - this throws the following exception

> ^ "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'referrals.' in 'where clause' (SQL: select * from `referrals` where `referrals`.`` is null limit 1)"

I'm slightly surprised that no one else has run into this over the past few years, surely nullable morphs are not that uncommon? Anyway, is this intended behaviour or is it a bug with Laravel? Or dare I say it, have I done something wrong?

I am actually using Lumen but I don't think that makes a difference as they both use Eloquent... I am currently using version 8.3.4 (Lumen)

**Comment by sinemacula** [comment] 2022-03-18 12:02
@driesvints - further to my above comment, I have managed to make some progress. As @y-morozov mentioned, it appears to be to do with the `$ownerKey`. If update my relation to the following:

```
/**
 * Get the referrer.
 *
 * @return \Illuminate\Database\Eloquent\Relations\MorphTo
 */
public function referrer(): MorphTo
{
    return $this->morphTo(null, null, null, 'id');
}
```

It no longer throws the exception... This seems odd but I guess it may be the solution...

**Comment by mokhosh** [comment] 2024-06-19 15:58
@driesvints I had this issue and fixed it using `sinemacula`'s approach. 

Will there be a cleaner approach to fix this?
Should we create a new issue for this?
