### ISSUE TITLE
Duplicated row when using eloquent creation methods

### ISSUE THREAD

**Issue by abada** [laravel/framework#20138] opened 2017-07-18 21:41 UTC
- Laravel Version: 5.3.31
- PHP Version: 7.1
- Database Driver & Version: MySQL  5.7.17

### Description:
Some times eloquent create method duplicated data row with the same created_at field.

### Steps To Reproduce:
Just submitting a form (Registration form).

**Comment by browner12** [comment] 2017-07-18 21:49
The repo is for reporting framework bugs. Please use a forum to get help with your application, and provide a much more detailed explanation of what you have done.

**Comment by abada** [comment] 2017-07-18 21:54
@browner12 I think my problem is a framework bug! 
There is nothing to explain more! 

Please check this screen shot  

![screen shot 2017-07-18 at 7 02 21 pm](https://user-images.githubusercontent.com/180586/28341515-653a60fa-6c14-11e7-9c02-934badb1d24d.png)

`created_at` field is the same of the two records!.

**Comment by browner12** [comment] 2017-07-18 21:57
There is **a lot** more to explain. Post your code, this is most likely a simple user error. We can't debug anything if you don't post any code.

**Comment by abada** [comment] 2017-07-18 22:07
Thank you @browner12  here is my code 
https://gist.github.com/abada/7a05996904d740a071b89470e565b839
Please note this not full of the code but the bug scope.

**Comment by browner12** [comment] 2017-07-18 22:24
please close this issue and move it to a forum like Stackoverflow. People can help you debug your issue there.

**Comment by fernandobandeira** [comment] 2017-07-19 00:36
Your code seems fine, can you reproduce this or it happened once and you can't reproduce it anymore?
I've seen that you've used the word ``` sometimes ``` so it should be an edge case for you...

Maybe the user is hitting the save button multiple times (double click) calling the create method twice, I think that's probably your issue here, disabling the button after the first click would prevent that.

**Closed** 2017-07-19 07:54 UTC
