### ISSUE TITLE
Parse error for curly braces in string

### ISSUE THREAD

**Issue by sinall** [laravel/framework#13655] opened 2016-05-23 07:11 UTC
{{ "@{{angularjs_obj}}" }}

However, below works fine
{!! "@{{angularjs_obj}}" !!}

**Comment by JeroenVanOort** [comment] 2016-05-23 12:21
Why would you want the plain string to be echo'd instead of simply displayed?

Simply use `@{{ angularjs_obj }}` in the template.

**Comment by sinall** [comment] 2016-05-24 04:33
The real case is using the above code in url function like:
{{ url("/user/@{{user.id}}/home") }}

**Comment by minhchu** [comment] 2016-05-26 18:37
What are the details about the error ?
I assume that `{{` escapes your inside `{{`

**Comment by themsaid** [comment] 2016-06-11 17:51
@sinall what are you trying to achieve with this?

`{{ url("/user/@{{user.id}}/home") }}`

**Comment by sinall** [comment] 2016-06-14 02:56
Binding the javascript object user.id to the url. {{ }} is the AngularJS syntax.

**Comment by GrahamCampbell** [comment] 2016-06-14 08:17
Still a bug either way. You shouldn't need to make adjustments to work around it.

**Comment by themsaid** [comment] 2016-06-14 12:51
The problem is that the closing characters `}}` of the js thing is compiled as the closing tag of blade:

`{{ url("/user/@{{user.id}}/home") }}` is read by blade as `{{ url("/user/@{{user.id}}` which is compiled to `<?php echo e(url("/user/@{{user.id); ?>`

As far as I thought the way to solve this is by introducing an escape character, for example:
`{{ "Something {{user.id\}}" }}`

So that blade recognises the closing tag as the first `}}` without a preceding `\` that comes after a `{{`.

It currently recognises it as the first `}}` after a `{{`.

**Comment by GrahamCampbell** [comment] 2016-06-14 14:21
Note that we can never properly fix this due the nature of regular expressions. They cannot represent languages with matching brackets. The hack we have here only works up to a finite number of nester brackets, 256 I think.

**Closed** 2016-06-14 14:20 UTC
Labels: bug
