### ISSUE TITLE
Mail view has $message, but $message cannot give subject

### ISSUE THREAD

**Issue by afraca** [laravel/framework#14831] opened 2016-08-15 13:17 UTC
If we use 

    Mail::send('templ.blade.php', [], function($message) {
     $message->subject('foo bar baz');
     }

The mail template gets a variable $message to use for attachments. One call also call `$message->getSubject()` in the template, but this will always return null. 

I think this has to do with the order that send() uses for the callback and the template processing:

https://github.com/laravel/framework/blob/781719746271098ed5049023921c084392494102/src/Illuminate/Mail/Mailer.php#L163

That's rather unfortunate and counter-intuitive. Of course one can use a variable for the subject, and pass it to the view like in other situations, but sometimes you have to do this a lot of times and this gets cumbersome, but more importantly, in theory the subject could depend on the $message.

**Comment by themsaid** [comment] 2016-09-05 22:54
We're open to Pull Requests if you wish to make it work that way.

Closing this since it's not a bug report, but feel free to open a discussion on the [Internals Repo](https://github.com/laravel/internals), it's the place for proposals and discussions.

**Closed by themsaid** 2016-09-05 22:54 UTC
