### ISSUE TITLE
Inverting validation rules

### ISSUE THREAD

**Issue by david-ridgeonnet** [laravel/framework#14297] opened 2016-07-13 13:23 UTC
A useful enhancement would be the ability to invert a validation rule, for example it could work like:

```
$rules = [
    'file' => '!mimes:exe',
];
```

The `!` indicates the result of the validation rule should be flipped so false becomes true and vice versa. This would be helpful for things like `mimes` so you can specify a blacklist of file types instead of a whitelist.

**Comment by fernandobandeira** [comment] 2016-07-14 11:46
:+1: 
This would be handy;

But:
Proposals shoud go in the internals slack channel or the internal repository here under laravel namespace.

So i suggest you create an issue there, this one will probably be closed eventually...

**Comment by themsaid** [comment] 2016-09-09 21:32
It seems like a useful feature, feel free to open a PR to suggest the change or open an issue in the internals repository as it's the place for feature requests.

Closing since it's not a bug report :) But thanks for the suggestion.

**Closed by themsaid** 2016-09-09 21:32 UTC
