### ISSUE TITLE
Laravel RESTful Route Issue: destroy(Link $name) must equal to the restful name.

### ISSUE THREAD

**Issue by fbens** [laravel/framework#19896] opened 2017-07-04 14:04 UTC
- Laravel Version: 5.4.23
- PHP Version: 7.1.4
- Database Driver & Version: mysql 5.1.7

### Description:
When I use Laravel resource restful route,I find a problem.
```
# routes/web.php
Route::resource('flink', 'FriendLinkController');
```

```
# app/Http/Controllers/Admin/FriendLinkController.php
    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Model\Link $link
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Link $flink)
    {
        var_dump($flink);

        return;
    }

```
I can't change the name of variable `$flink`, It took three hours to find out that variable name after Model  must be `$flink` as the restful name, otherwise  not working,,,,

**Comment by Douglasdc3** [comment] 2017-07-04 18:22
This has changed in Laravel 5.5 is indeed still an issue on 5.4 is a duplicate of #19815

**Comment by fernandobandeira** [comment] 2017-07-05 12:30
Yes, you'll get an empty model if the variable name doesn't match the name of the route parameter, not sure if this is working differently on 5.5 but it's how it works on <=5.4

**Comment by fbens** [comment] 2017-07-06 03:31
@fernandobandeira 
Great! 

I am very confused, how laravel achieve such function without need instance a object `FriendLink::find(request()->id)`, automatically find the record and pass it to action. Which file is implemented?

```
public function destroy(\App\Model\FriendLink $flink){
	var_dump($flink);
}
```

**Comment by devcircus** [comment] 2017-07-06 03:41
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Routing/ImplicitRouteBinding.php

**Comment by Dylan-DPC** [comment] 2017-10-09 19:44
@fbens this isn't a bug and you can close this issue :smile:

**Closed** 2017-10-23 13:00 UTC
