### ISSUE TITLE
Cannot test multiple notifications when using `Notification::fake`

### ISSUE THREAD

**Issue by davidhemphill** [laravel/framework#29486] opened 2019-08-09 18:16 UTC
- Laravel Version: 5.8.31
- PHP Version: 7.3.7
- Database Driver & Version: N/A

### Description:

When trying to test multiple calls to the Notification facade, it appears one can't assert against both of the notifications using `Notification::fake()`. There seems to be no way one could reliably access one of the single notifications to check against it as the one passed to `assertSentTo` could be any of them. 

#### 1. Fire off several separate notifications in your code 
```php
// Fire off a single notification
Notification::route(TelegramChannel::class)->notify(new ExampleNotification);

// Then fire off another notification
Notification::route(SlackChannel::class)->notify(new ExampleNotification);
```
#### 2. Attempt to assert against the notification

```php
Notification::assertSentTo(new AnonymousNotifiable, ExampleNotification::class, function ($notification, $channels, $notifiable) {
    // The route could be either the Slack one or the Telegram one as the order is random
    dd($notifiable->routes);
});
```

**Comment by tw99** [comment] 2019-08-09 19:56
```php
Notification::assertSentTo(new AnonymousNotifiable, ExampleNotification::class, function ($notification, $channels, $notifiable) {
    return $notifiable->routeNotificationFor('slack') && ...
});

Notification::assertSentTo(new AnonymousNotifiable, ExampleNotification::class, function ($notification, $channels, $notifiable) {
    return $notifiable->routeNotificationFor('telegram') && ...
});
```

or specify the multiple delivery channels on `ExampleNotification::class`, and make assertions against the notification

```
public function via($notifiable)
{
    return [SlackChannel::class, TelegramChannel::class];
}
```

**Comment by davidhemphill** [comment] 2019-08-09 20:20
Hi there. Your first option would allow for checking the routing information for a given channel, but still wouldn't allow for asserting specific data was set on the channel.

The second option is not available in this use case. We have to use on-demand notifications because we need to pass in channel-specific data in the constructor. It's this data that we wish to assert against.

**Comment by driesvints** [comment] 2019-08-12 13:02
@davidhemphill can you maybe post your `ExampleNotification` class as well? Currently getting the following below when I scaffold a default one: 

```
Error: Call to undefined method Illuminate\Notifications\Channels\MailChannel::assertSentTo()

/Users/driesvints/Sites/test-app/vendor/laravel/framework/src/Illuminate/Support/Manager.php:146
/Users/driesvints/Sites/test-app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:237
/Users/driesvints/Sites/test-app/tests/Feature/ExampleTest.php:27
```

**Comment by davidhemphill** [comment] 2019-08-12 15:57
Sure! Here's a slightly stripped-down example. In our domain, the notification channels (slack, telegram, mail, etc) are store in the database and passed into the `Notification`.

```php
<?php

class ExampleNotification
{
    public $notificationChannel;

    public function __construct($notificationChannel)
    {
        $this->notificationChannel = $notificationChannel;
    }

    public function via($notifiable)
    {
        // The provider comes from the Notification Channel and is something like `slack` or `telegram`
        return [$this->notificationChannel->provider];
    }

    public function toSlack($notifiable)
    {
        return (new SlackMessage)
            ->to($this->channel->config['url'])
            ->attachment(function (SlackAttachment $attachment) {
                $attachment
                    ->content('View Example!')
                    ->color('#4299e1');
            });
    }

    public function toTelegram($notifiable)
    {
        return TelegramMessage::create()
            ->to($this->channel->config['chat_id'])
            ->content($content)
            ->button('View Example', 'http://yahoo.com');
    }
}
```

**Comment by driesvints** [comment] 2019-08-13 14:07
Hey @davidhemphill. I still think we need a little more code to reproduce this. I see you have a dependency in your `ExampleNotification` class but your original example doesn't takes one in. Can you add some more code to have a fully reproducible example? If I can reproduce it I can look into how we can improve or what a better solution might be. Thanks!

**Comment by driesvints** [comment] 2019-08-16 11:33
Hey @davidhemphill. I saw your video and think I have a solution. What you basically will have to do is differentiate between channels within the callback. The notifications should definitely all pass through:

```php
Notification::assertSentTo(new AnonymousNotifiable, ExampleNotification::class, function ($notification, $channels, $notifiable) {
    if ($notification->notificationChannel === 'slack') {
        // perform assertions for slack
    } elseif ($notification->channel === 'nexmo') {
        // perform assertions for nexmo
    }

    return false;
});
```

If you want a "hacky" way to assert that both channels were definitely called you can do something like this:

```php
$calledChannels = [];

Notification::assertSentTo(new AnonymousNotifiable, ExampleNotification::class, function ($notification, $channels, $notifiable) use (&$calledChannels) {
    if ($notification->notificationChannel === 'slack') {
        $calledChannels[] = 'slack';
    } elseif ($notification->channel === 'nexmo') {
        $calledChannels[] = 'nexmo';
    }

    return false;
});

$this->assertArraySubset(['slack', 'nexmo'], $calledChannels);
```

There indeed doesn't seems to be a better way to do that atm 🤔

**Comment by driesvints** [comment] 2019-09-02 15:57
Hey @davidhemphill I'm gonna close this but feel free to reply whenever you get the chance.

**Closed by driesvints** 2019-09-02 15:57 UTC
Labels: needs more info
