### ISSUE TITLE
src/Illuminate/Foundation/Console/ModelMakeCommand.php and error "An option with shortcut "s" already exists."

### ISSUE THREAD

**Issue by orukaz** [laravel/framework#30868] opened 2019-12-18 00:46 UTC
- Laravel Version: **v6.8.0** (updated from v6.7.0)
- PHP Version: **7.4.0**

### Description:

I updated Laravel version **v6.7.0 to v6.8.0** and now running **"php artisan ..."** gives me an **error**:

**"An option with shortcut "s" already exists."**

### Steps To Reproduce:

I searched looked the code and found the Laravel v6.8.0 change in the file **"src/Illuminate/Foundation/Console/ModelMakeCommand.php"** which has caused that. Laravel v6.8.0 added new "seed" definition: 

```
['seed', 's', InputOption::VALUE_NONE, 'Create a new seeder file for the model'],
```

**Laravel v6.7.0 code:**

```
protected function getOptions()
    {
        return [
            ['all', 'a', InputOption::VALUE_NONE, 'Generate a migration, factory, and resource controller for the model'],

            ['controller', 'c', InputOption::VALUE_NONE, 'Create a new controller for the model'],

            ['factory', 'f', InputOption::VALUE_NONE, 'Create a new factory for the model'],

            ['force', null, InputOption::VALUE_NONE, 'Create the class even if the model already exists'],

            ['migration', 'm', InputOption::VALUE_NONE, 'Create a new migration file for the model'],

            ['pivot', 'p', InputOption::VALUE_NONE, 'Indicates if the generated model should be a custom intermediate table model'],

            ['resource', 'r', InputOption::VALUE_NONE, 'Indicates if the generated controller should be a resource controller'],
        ];
    }
```

**Laravel v6.8.0 code:**

```
protected function getOptions()
    {
        return [
            ['all', 'a', InputOption::VALUE_NONE, 'Generate a migration, factory, and resource controller for the model'],
            ['controller', 'c', InputOption::VALUE_NONE, 'Create a new controller for the model'],
            ['factory', 'f', InputOption::VALUE_NONE, 'Create a new factory for the model'],
            ['force', null, InputOption::VALUE_NONE, 'Create the class even if the model already exists'],
            ['migration', 'm', InputOption::VALUE_NONE, 'Create a new migration file for the model'],
            ['seed', 's', InputOption::VALUE_NONE, 'Create a new seeder file for the model'],
            ['pivot', 'p', InputOption::VALUE_NONE, 'Indicates if the generated model should be a custom intermediate table model'],
            ['resource', 'r', InputOption::VALUE_NONE, 'Indicates if the generated controller should be a resource controller'],
        ];
    }
```

**If I rename 's' to 'se' (for example), then everything works fine:**

```
            ['seed', 'se', InputOption::VALUE_NONE, 'Create a new seeder file for the model'],
```

Is it possible that command “php artisan make:model User -s” conflicts with php serve command “php -S localhost:8000” ???

Is it possible that “-s” is reserved from php?

One has “-s” and other has “-S”. 

- What causes that error?
- How to bypass that error?
- Can I somehow disable that 's' ?

Please fix that or help me with that ;)

**Comment by orukaz** [comment] 2019-12-18 01:28
Is it possible that command “php artisan make:model User -s” conflicts with php serve command “php -S localhost:8000” ???

Is it possible that “-s” is reserved from php?

One has “-s” and other has “-S”.

**Comment by julienarcin** [comment] 2019-12-18 02:01
I have the same error. It is a package problem.

You should check that none of your package file inherits the ModelMakeCommand (for model generation) and use -s option. 

Details :
For me, it is conflicting with a package (babenkoivan/scout-elasticsearch-driver).

Here : 
https://github.com/babenkoivan/scout-elasticsearch-driver/blob/master/src/Console/SearchableModelMakeCommand.php

The SearchableModelMakeCommand use -s option to specify search rule.
It conflicts with the new inherited ModelMakeCommand class.

When I delete this option in the package, the error disappears and everything works fine.

**Comment by iamthefreeman** [comment] 2019-12-18 08:31
I posted this report yesterday but it got marked as not a bug: #30866.

**Comment by mvalee** [comment] 2019-12-18 09:26
Same issue here, conflict with package babenkoivan/scout-elasticsearch-driver .

**Comment by iamthefreeman** [comment] 2019-12-18 09:39
@julienarcin and I have proposed changes on the `babenkoivan/scout-elasticsearch-driver` repo. Just waiting for a review.

**Comment by oixan** [comment] 2019-12-18 13:36
same problem for me. I m using scout-elasticsearch-driver too.
How can i run my project now?

**Comment by devcircus** [comment] 2019-12-18 16:11
It would probably be best to revert to the previous Laravel version until the changes are made to the scout-elasticsearch library.

**Comment by driesvints** [comment] 2019-12-19 11:45
Please open up an issue on the related package that's causing the problem. Revert back to `v6.7.0` until they've addressed the issue.

**Closed by driesvints** 2019-12-19 11:45 UTC
