### ISSUE TITLE
AWS S3 - Missing required client configuration options

### ISSUE THREAD

**Issue by marlongichie** [laravel/framework#28070] opened 2019-03-30 16:15 UTC
- Laravel Version: 5.8.*
- PHP Version: 7.3.1
- Database Driver & Version:

### Description:

When trying to upload files to AWS S3, the following error is reported:

```
A "region" configuration value is required for the "s3" service
  (e.g., "us-west-2"). A list of available public regions and endpoints can be
  found at http://docs.aws.amazon.com/general/latest/gr/rande.html.  
```

### Steps To Reproduce:

Configure environment variables as follows:

```
FILESYSTEM_DRIVER=s3
FILESYSTEM_CLOUD=s3

AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxx
AWS_DEFAULT_REGION=us-east-2
AWS_BUCKET=bucketname
AWS_URL=https://apigateway.us-east-2.amazonaws.com
```

Has anyone else come across this issue? Am I missing something?

**Comment by staudenmeir** [comment] 2019-03-30 17:10
Have you cached your configuration?

Does `dd(config('filesystems.disks.s3.region'));` show the correct value?

**Comment by marlongichie** [comment] 2019-03-30 18:14
@staudenmeir No. `dd(config('filesystems.disks.s3.region'));` returns null

See below output of `dd(config('filesystems.disks.s3'));`

```
array:6 [▼
  "driver" => "s3"
  "key" => null
  "secret" => null
  "region" => null
  "bucket" => null
  "url" => null
]
```

**Comment by staudenmeir** [comment] 2019-03-30 18:16
What does your `config/filesystems.php` file look like?

**Comment by marlongichie** [comment] 2019-03-30 18:19
I'm using the default `config/filesystems.php`. See below:

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default filesystem disk that should be used
    | by the framework. The "local" disk, as well as a variety of cloud
    | based disks are available to your application. Just store away!
    |
    */

    'default' => env('FILESYSTEM_DRIVER', 'local'),

    /*
    |--------------------------------------------------------------------------
    | Default Cloud Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Many applications store files both locally and in the cloud. For this
    | reason, you may specify a default "cloud" driver here. This driver
    | will be bound as the Cloud disk implementation in the container.
    |
    */

    'cloud' => env('FILESYSTEM_CLOUD', 's3'),

    /*
    |--------------------------------------------------------------------------
    | Filesystem Disks
    |--------------------------------------------------------------------------
    |
    | Here you may configure as many filesystem "disks" as you wish, and you
    | may even configure multiple disks of the same driver. Defaults have
    | been setup for each driver as an example of the required options.
    |
    | Supported Drivers: "local", "ftp", "sftp", "s3", "rackspace"
    |
    */

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
        ],

    ],

];

```

**Comment by staudenmeir** [comment] 2019-03-30 18:22
Are your environment variables configured in the `.env` file?

What does `dd(env('AWS_DEFAULT_REGION'));` show you?

**Comment by marlongichie** [comment] 2019-03-30 18:35
Snippet from `.env` file below
APP_NAME="My App Name"

FILESYSTEM_DRIVER=s3
FILESYSTEM_CLOUD=s3

AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
AWS_DEFAULT_REGION=us-east-2
AWS_BUCKET=bucketname
AWS_URL=https://apigateway.us-east-2.amazonaws.com

`dd(env('AWS_DEFAULT_REGION'))` returns `null`

`dd()` for all variables associated with FILESYSTEM_ & AWS_ returns `null`

However other env variables return expected values:
`dd(env('APP_NAME'))` returns `My App Name` also `dd(config('app.name'))` returns `My App Name`

**Comment by staudenmeir** [comment] 2019-03-30 18:36
Can you reproduce this on a fresh installation of Laravel?

**Comment by marlongichie** [comment] 2019-03-30 18:57
Did a fresh install of Laravel just now.

Configured the following:

```
FILESYSTEM_DRIVER=s3
FILESYSTEM_CLOUD=s3

AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
AWS_DEFAULT_REGION=us-east-2
AWS_BUCKET=bucketname
AWS_URL=https://apigateway.us-east-2.amazonaws.com
```

See below output of `dd(config('filesystems.disks.s3'))`

```
array:6 [▼
  "driver" => "s3"
  "key" => ""
  "secret" => ""
  "region" => "us-east-1"
  "bucket" => ""
  "url" => "https://apigateway.us-east-2.amazonaws.com"
]
```

Output from `dd(env('AWS_DEFAULT_REGION'))` is `"us-east-1"`

Looks like there is a default region that is overwriting the value I set in the `.env` file. Also, the other values return an empty string in this case.

Strange behavior. Your thoughts?

**Comment by marlongichie** [comment] 2019-03-30 19:28
I was able to solve this in my existing project. It seems there was a missing closing quote in the `.env` file before the FILESYSTEM_ variables which affected everything that came after it.

```
MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER <--missing closing quote

FILESYSTEM_DRIVER=s3
FILESYSTEM_CLOUD=s3
...
```

But, I'm not sure what issue was causing the variable to be overwritten in the fresh Laravel install project. 

Thanks @staudenmeir .

**Comment by staudenmeir** [comment] 2019-03-30 19:45
Regarding the fresh installation: The sample `.env` file already contains [default values](https://github.com/laravel/laravel/blob/master/.env.example#L35) for `AWS_DEFAULT_REGION` and others. Did you remove/replace those?

**Comment by marlongichie** [comment] 2019-03-30 20:09
You're absolutely right @staudenmeir .

Looks to be configuration error rather than an issue with Laravel itself. I think it's fair to close this out at this point.

Thank you again for helping with this issue.

Best.

**Comment by staudenmeir** [comment] 2019-03-30 20:25
Please close the issue.

**Closed** 2019-03-30 20:52 UTC

**Comment by dukesnuz** [comment] 2020-03-14 21:34
I know this is closed. i had same issue and different problem.
I had copied the .env AWS configuration from one Laravel version to another version.
Turns out the config/filesystem AWS variables were different from each Laravel version
One version used AWS_DEFAULT_REGION=
and
Other used AWS_REGION=

**Comment by Natfan** [comment] 2020-05-10 13:21
For reference my fix was to run `php artisan config:cache`, which wiped the current version of my .env cache and replaced it with the live values.

**Comment by jessiesiat** [comment] 2020-10-02 08:35
if `php artisan clear:cache` doesnt work.

It can be that you already have media in your database that points to s3, and when retrieve it tries to resolve the url.
When you don't already have the s3 credentials or commented it out because you switch to another disk, you will get that error. 

In my case, I was using spatie/laravel-medialibrary that I encounter that error.

**Comment by Fitmavincent** [comment] 2021-02-22 04:40
> if `php artisan config:clear` doesnt work.
> 
> It can be that you already have media in your database that points to s3, and when retrieve it tries to resolve the url.
> When you don't already have the s3 credentials or commented it out in `.env` because you switch to another disk, you will get that error.
> 
> I encountered that error using `spatie/laravel-medialibrary`

Hi Jessie, 

I'm using the ```spatie/laravel-medialibrary``` and I got the error when hosting the app on Laravel Forge. Checked every config from tinker and looks correct to me but getting missing configuration error regardless, which local is totally fine. Wondering how do you solve this problem? If there's something in DB point to S3, what tables I should check? Thank you.

**Comment by Enaah** [comment] 2022-08-26 17:41
> > if `php artisan config:clear` doesnt work.
> > It can be that you already have media in your database that points to s3, and when retrieve it tries to resolve the url.
> > When you don't already have the s3 credentials or commented it out in `.env` because you switch to another disk, you will get that error.
> > I encountered that error using `spatie/laravel-medialibrary`
> 
> Hi Jessie,
> 
> I'm using the `spatie/laravel-medialibrary` and I got the error when hosting the app on Laravel Forge. Checked every config from tinker and looks correct to me but getting missing configuration error regardless, which local is totally fine. Wondering how do you solve this problem? If there's something in DB point to S3, what tables I should check? Thank you.

Hey there @Fitmavincent,

I am running into this issue myself, could you solve it?
