### ISSUE TITLE
After installing Laravel version 11, I encountered an error stating that the SQLite driver was missing. Upon investigation, I realized that in Laravel 11, the .env file includes SQLite as the default database driver.

### ISSUE THREAD

**Issue by Kashif-Kframe** [laravel/framework#50484] opened 2024-03-12 16:51 UTC
### Laravel Version

11

### PHP Version

8.3.2

### Database Driver & Version

mysql

### Description

After installing Laravel version 11, I encountered an error stating that the SQLite driver was missing. Upon investigation, I realized that in Laravel 11, the .env file includes SQLite as the default database driver. However, as I only intended to use MySQL, this caused confusion initially.

Upon switching the database driver from SQLite to MySQL in the .env file, I noticed that the variables for the database username and password were commented out. This led to further confusion on my part.

I apologize for any confusion, but I'm unsure why these variables were commented out. It seems there might have been an oversight during the configuration process.

To resolve this, I've uncommented the lines for the database username and password, providing the necessary credentials for MySQL. This ensures that Laravel can connect to the MySQL database successfully.

### Steps To Reproduce

Install fresh Laravel 11 using php 8.3.2 version, after finishing the installation composer gave me the sqlite driver error says 

   Illuminate\Database\QueryException

  could not find driver (Connection: sqlite, SQL: PRAGMA foreign_keys = ON;)

  at vendor\laravel\framework\src\Illuminate\Database\Connection.php:813
    809▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    810▕                 );
    811▕             }
    812▕
  ➜ 813▕             throw new QueryException(
    814▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    815▕             );
    816▕         }
    817▕     }

  1   vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:65
      PDOException::("could not find driver")

  2   vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:65
      PDO::__construct("sqlite:C:\laragon\www\L11\database\database.sqlite", Object(SensitiveParameterValue), ])
![sqlite](https://github.com/laravel/framework/assets/10650083/0971bc56-7294-4dc4-b37d-9afea31da07e)

**Comment by nunomaduro** [comment] 2024-03-12 16:55
What command did you use to create your Laravel application?

**Comment by Kashif-Kframe** [comment] 2024-03-12 16:57
@nunomaduro 
I used the below command as mentioned in Laravel documentation.
`composer create-project laravel/laravel example-app`

**Comment by nunomaduro** [comment] 2024-03-12 16:58
Working on the fix.

**Comment by PAXANDDOS** [comment] 2024-03-12 17:00
Got the same issue there!
Was using `laravel/installer`:`v5.6.0` with the command `laravel new <name>` and it failed on the migration step. Options for the installer are: `breeze`, `react`, `typescript,dark`, `PHPUnit`, and no git repository.

Using:
- Windows 11 Pro (Build 22631)
- PHP 8.2.9 (cli)
- Composer version 2.6.6

**Comment by nunomaduro** [comment] 2024-03-12 18:21
This is now fixed.

**Closed by nunomaduro** 2024-03-12 18:21 UTC
Labels: bug

**Comment by satrianovember** [comment] 2024-03-13 05:06
> This is now fixed.

how to fixed?

**Comment by rostislavjadavan** [comment] 2024-03-13 21:21
I encountered the same issue, and it was simply because the `pdo_sqlite` extension was missing.

Check if it is installed, for example like this:
```
$ php --ini | grep sqlite

/etc/php/8.2/cli/conf.d/20-pdo_sqlite.ini,
/etc/php/8.2/cli/conf.d/20-sqlite3.ini,
```

**Comment by saintadjie** [comment] 2024-03-14 07:27
same here, It's happening to me

**Comment by saintadjie** [comment] 2024-03-15 01:40
> @satrianovember @rostislavjadavan @saintadjie which OS are you all using? And which PHP version?

PHP 8.3.4
I am using windows 11 locally

**Comment by rostislavjadavan** [comment] 2024-03-15 07:46
> @satrianovember @rostislavjadavan @saintadjie which OS are you all using? And which PHP version?

```
PHP 8.2.10-2ubuntu1 (cli) (built: Sep  5 2023 14:37:47) (NTS)
```

```
Ubuntu 23.10 (Mantic Minotaur), kernel 6.5.0-25-generic
```

**Comment by nunomaduro** [comment] 2024-03-15 08:32
@saintadjie @rostislavjadavan What's exactly is "happening" now? Can you share screenshots of the commands and issues you are getting?

**Comment by rostislavjadavan** [comment] 2024-03-15 08:55
> @saintadjie @rostislavjadavan What's exactly is "happening" now? Can you share screenshots of the commands and issues you are getting?

I no longer have any issues. I encountered the same error that was reported earlier, but in my case, it was due to a missing SQLite extension. I resolved the issue by installing it via `apt install php-sqlite3`, and then I posted my solution.

Apologies if my initial post was unclear.

**Comment by pabloripoll** [comment] 2024-03-15 21:54
> @saintadjie @rostislavjadavan What's exactly is "happening" now? Can you share screenshots of the commands and issues you are getting?

![Screenshot from 2024-03-15 22-53-48](https://github.com/laravel/framework/assets/53290870/8b125dc4-f176-4022-8847-2fe97cda3a58)

**Comment by pabloripoll** [comment] 2024-03-15 21:56
> @saintadjie @rostislavjadavan What's exactly is "happening" now? Can you share screenshots of the commands and issues you are getting?

![Screenshot from 2024-03-15 22-55-46](https://github.com/laravel/framework/assets/53290870/0493f090-cb84-4b03-a661-238113f3415c)

**Comment by pabloripoll** [comment] 2024-03-15 21:57
> @saintadjie @rostislavjadavan What's exactly is "happening" now? Can you share screenshots of the commands and issues you are getting?

Many directories and files are missing comparing with latest Laravel 10

**Comment by fabiomota-br** [comment] 2024-03-20 00:14
sudo apt install php8.3-sqlite3 

Fix!

**Comment by radu-lefter** [comment] 2024-03-20 14:21
I have the same issue, but on Windows. I have uncommented the "extension=sqlite3" line in the php.ini file, but the problem persists.  The sqlite dlls are in the ext folder of the php installation, but when I run "php -m | findstr pdo_sqlite", nothing is returned. How do I install those drivers on Windows?

**Comment by mood48** [comment] 2024-03-20 14:24
The easiest way is to modify the php.ini file and uncomment ;extension=pdo_sqlite. just remove ;(semi colon) and save the file.

**Comment by radu-lefter** [comment] 2024-03-20 14:26
> The easiest way is to modify the php.ini file and uncomment ;extension=pdo_sqlite. just remove ;(semi colon) and save the file.

It was the first thing I did, no success

**Comment by radu-lefter** [comment] 2024-03-20 14:56
> The easiest way is to modify the php.ini file and uncomment ;extension=pdo_sqlite. just remove ;(semi colon) and save the file.

Thank you, it worked, I was using the wrong php.ini

**Comment by ibrarjadoonproject** [comment] 2024-03-22 00:02
I got the same error follow the below steps to fix 

1 : change the default DB connection to MySQL in the .env file
2: run PHP artisan migrate in command
3: change default collection from utf8mb4_0900_ai_ci to utf8mb4_unicode_ci in config/database.php file 

It worked at my side

**Comment by ampats04** [comment] 2024-03-26 12:10
Thanks for this! This worked

**Comment by aghoshsuraj555** [comment] 2024-03-29 10:16
How to fix this in windows ?

**Comment by aghoshsuraj555** [comment] 2024-03-29 10:21
> This is now fixed.

How this is fixed could you please explain

**Comment by akhelij** [comment] 2024-05-03 16:51
How can I avoid launching the migration during my first installation of laravel 11, or at least define mysql as my default database connection

**Comment by AbdullahKhalide** [comment] 2024-05-26 20:36
I have same error but comment is not here mean your solve is it but the problem in my project  what the solve

**Comment by zll600** [comment] 2024-07-01 09:41
I use following requirements, and encountered similiar problem
- php: 8.2
- larvel/framework: 11.9
- os: Archlinux

reproduce step

1. `composer create-project laravel/laravel example-app`
2. `cd example-app`
3. `php artisan migrate`

the problem will happen
````text
~/Code/php/example-app ❯ php artisan migrate                                                                                                                           ✘ INT

   Illuminate\Database\QueryException 

  could not find driver (Connection: sqlite, SQL: PRAGMA foreign_keys = ON;)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:813
    809▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    810▕                 );
    811▕             }
    812▕ 
  ➜ 813▕             throw new QueryException(
    814▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    815▕             );
    816▕         }
    817▕     }

      +42 vendor frames 

  43  artisan:13
      Illuminate\Foundation\Application::handleCommand()
````

I fixed by using https://wiki.archlinux.org/title/PHP#Sqlite

**Comment by AbdullahKhalide** [comment] 2024-07-01 20:07
> I use following requirements, and encountered similiar problem
> 
> * php: 8.2
> * larvel/framework: 11.9
> * os: Archlinux
> 
> reproduce step
> 
> 1. `composer create-project laravel/laravel example-app`
> 2. `cd example-app`
> 3. `php artisan migrate`
> 
> the problem will happen
> 
> ```
> ~/Code/php/example-app ❯ php artisan migrate                                                                                                                           ✘ INT
> 
>    Illuminate\Database\QueryException 
> 
>   could not find driver (Connection: sqlite, SQL: PRAGMA foreign_keys = ON;)
> 
>   at vendor/laravel/framework/src/Illuminate/Database/Connection.php:813
>     809▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
>     810▕                 );
>     811▕             }
>     812▕ 
>   ➜ 813▕             throw new QueryException(
>     814▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
>     815▕             );
>     816▕         }
>     817▕     }
> 
>       +42 vendor frames 
> 
>   43  artisan:13
>       Illuminate\Foundation\Application::handleCommand()
> ```
> 
> I fixed by using https://wiki.archlinux.org/title/PHP#Sqlite

thank you dear

**Comment by munkeywolf00** [comment] 2024-08-02 12:06
If you are having this issue, check if the PHP version you using matches the php.ini you are editing. Make a new terminal instance if you are switching from different PHP version.

**Comment by LJunnil** [comment] 2024-08-06 05:27
Not working

**Comment by codinginbarn** [comment] 2024-09-19 02:06
If you are using Windows (10 in my case), have PHP installed and in your path env, it appears that you must have `extension=sqlite3` uncommented in your Windows php.ini

**Comment by abdullahilashik** [comment] 2024-10-03 03:56
It was resolved for me adding  `extension=pdo_sqlite ` in `php.ini` . If this line is already in your `php.ini` file check if there is comment added. If so remove the comment

**Comment by flpdev** [comment] 2024-10-28 14:20
Hello guys!

I came across to the same problem. Even i switched the default database to mysql, on run php artisan comands i found this error. i tried same solutions posted before but to my surprise i found the problem on my case. I was editing the .env.example file rsrs on change the default db to mysql in my .evn production file no more error are showed.

**Comment by Menjadianjay** [comment] 2024-12-14 07:13
i used to get the same error, and everytime i just erase ";" in front of extension=pdo_sqlite and extension=sqlite3 on file php.ini. And serve laravel project like usual.

**Comment by N-Mehroj** [comment] 2025-01-16 05:22
The error indicates that the required SQLite driver is missing from your PHP installation, which Laravel 11 defaults to using in its `.env` file. Here’s how to resolve the issue:

---

### 1. **Verify the Current PHP Setup**
Run the following command to confirm if SQLite is installed and enabled:
```bash
php -m | grep sqlite
```

If SQLite does not appear in the output, it is not installed.

---

### 2. **Install the SQLite Extension**
Depending on your operating system, you can install SQLite using the following commands:

#### **For Ubuntu/Debian**
```bash
sudo apt update
sudo apt install php-sqlite3
```

#### **For Red Hat/CentOS/AlmaLinux**
```bash
sudo yum install php-sqlite3
```

#### **For macOS (Homebrew)**
```bash
brew install php
brew reinstall php
```

#### **For Windows**
1. Locate the `php.ini` file in your PHP installation directory.
2. Uncomment the following line by removing the semicolon (`;`):
   ```ini
   ;extension=sqlite3
   ```
3. Restart your web server (Apache, Nginx, etc.).

---

### 3. **Restart PHP and Web Server**
After installing or enabling SQLite, restart your PHP process and web server:

#### Apache
```bash
sudo service apache2 restart
```

#### Nginx with PHP-FPM
```bash
sudo service php-fpm restart
sudo service nginx restart
```

---

### 4. **Verify SQLite Installation**
Run the following command to check if the SQLite extension is enabled:
```bash
php -m | grep sqlite
```
You should see `sqlite3` in the output.

---

### 5. **Configure Laravel for SQLite**
Laravel 11 uses SQLite as the default database. Update your `.env` file to ensure it's correctly configured:
```env
DB_CONNECTION=sqlite
DB_DATABASE=/absolute/path/to/database.sqlite
```

#### Create the SQLite Database File
If it doesn't already exist, create a database file:
```bash
touch database/database.sqlite
```

Update your `.env` file with the correct path to this file.

---

### 6. **Check Laravel Dependencies**
Ensure Laravel dependencies are up to date:
```bash
composer install
```

---

### 7. **Verify Laravel Database Connection**
Run a migration to test the SQLite setup:
```bash
php artisan migrate
```

If no errors occur, the SQLite driver is properly installed and Laravel is configured correctly.

---

If you still encounter issues, let me know the error message or any specific details, and I’ll assist further!

**Comment by jeffdunham754-gif** [comment] 2025-10-04 05:40
ARE YOU INTERESTED IN THE WORLD OF FAME?? GETTING RICH. POWERFUL AND FAMOUS? JOIN THE ILLUMINATI TODAY AND BECOME RICH.ILLUMINATI BRINGS YOU INTO THE LIMELIGHT OF THE WORLD IN WHICH YOU LIVE IN TODAY. YOUR FINANCIAL DIFFICULTIES ARE BROUGHT TO AN END IF YOU JOIN. WE SUPPORT YOU BOTH FINANCIALLY AND MATERIALLY TO ENSURE YOU LIVE A COMFORTABLE LIFE.JOIN ILLUMINATI AND GET YOUR SELF A HOUSE AND A CAR AND ALSO WITH THE SUM OF (ONE MILLION DOLLARS) BENEFITS GIVEN TO NEW MEMBERS WHO JOIN ILLUMINATI. 1. A Cash Reward of one million dollars 2.A Dream House bought in the country of your own choice and a car 3.A V.I.P treatment in all Airports in the World 4.A total Lifestyle change 5.Monthly payment of $500,000.00 USD into your bank account every month as a member If you are interested of joining us in the great brotherhood Illuminati riches satanic hand symbol Add us on whatsapp with this +2347036991712
 or email [greatilluminatibrotherhood537@gmail.com](mailto:greatilluminatibrotherhood537@gmail.com)
