### ISSUE TITLE
how to access session data in repositories

### ISSUE THREAD

**Issue by lorvent** [laravel/framework#20322] opened 2017-07-30 08:02 UTC
- Laravel Version: 5.4
- PHP Version:7
- Database Driver & Version: mysql
- Original application version: 5.1 LTS
- Auth driver: Cartalyst/Sentinel

### Description:
Hello,
I know we can't access session data directly in controllers from 5.3 and there is a workaround.

we have developed an application having around 50 repository files and now we are upgrading it to 5.4
and we use sentinel for authentication.

since all repository methods depends on current logged in user, we had `$this->user = Sentinel::getUser()` in `__construct()` method in 5.1 and its working fine for now.

but now it has become a big problem for us and writing `$this->user = Sentinel::getUser()` in every repository method which is not a good idea IMHO.

is there any workaround for this situation?

We have been post-poning upgradation for months but now client is forcing as he wants to use 5.5LTS when released.

PS: i know this is not the best place to post issues like this but i searched all locations like SO, latacasts and other famous laravel sites but there is no information on this anywhere, if anyone can point a URL addressing this, i would be grateful.

**Comment by sisve** [comment] 2017-07-30 09:04
You can get the current user in your controller actions (`$request->user()`, `Auth::user()`) and pass it to the repository as a normal parameter (`$repository->getPostsAccessibleByUser($user)`).

This issue is not a bug report, but asking for help. Use the forums instead.

> In previous versions of Laravel, you could access session variables or the authenticated user in your controller's constructor. This was never intended to be an explicit feature of the framework. In Laravel 5.3, you can't access the session or authenticated user in your controller's constructor because the middleware has not run yet.
Source: https://laravel.com/docs/5.3/upgrade

**Comment by lorvent** [comment] 2017-07-30 09:51
Hello,
thanks for the answer.

yes, thats a solution but like i said we have around 50 repositories and 100+ controllers for all user roles so instead of changing all of them... i was wondering if there is any elegant/easy solution.

**Comment by lk77** [comment] 2017-07-30 15:55
the best way would be to use dependency injection and inject AuthManager in your repository i think.

**Comment by srmklive** [comment] 2017-07-31 08:27
I normally use the `auth` global helper in this regard. `auth()->user()`. 

However, in your case i would create a base controller class with a protected variable like `$authUser`. In the constructor, i would put the following:

```
namespace App\Http\Controllers;

class AppController extends Controller
{
    protected $authUser;

    public function __construct()
    {
        $this->authUser = Sentinel::getUser();
    }
}
```

So, any controller you create should extend the `BaseController` like:

```
class HomeController extends BaseController
{
    public function __construct()
    {
        parent::__construct();
    }
}
```

@lorvent The above is perhaps not the ideal solution. But that's how i would go about it in the case you mentioned.

**Comment by sisve** [comment] 2017-07-31 13:23
@srmklive This issue is about the authentication data not being available in the constructor of the controller, there's even a comment that quotes the upgrade notes that specifically says "you can't access the session or authenticated user in your controller's constructor".

Why on Kerbin did you write a suggestion that tries to retrieve the authenticated user in the constructor even when it's clearly not allowed?

Also, wouldn't he still have to modify all those repositories to accept the user as a parameter?

Why is this issue still open? It's clearly not a bug report and belongs to the forums.

**Comment by srmklive** [comment] 2017-07-31 14:01
@sisve sorry for suggesting a solution that the framework doesn't support. My bad. I have removed that part from the reply.

**Comment by srmklive** [comment] 2017-07-31 14:08
@lorvent As per my original comment in which @sisve pointed out my mistake in advising a solution not supported by framework. I would perhaps do it through a global helper. You can simply create a file `app/functions.php` & add it to autoload section in `composer.json`.

```
function activeUser()
{
    return app(Sentinel::class)::getUser(); 
}
```
Something like the above may be helpful for you. Don't know whether everyone would agree with this or not.

**Comment by lk77** [comment] 2017-07-31 14:16
it's not the solution i think, because it will need to rewrite too much code i think

**Comment by srmklive** [comment] 2017-07-31 14:23
Too much code is already written. That's the only way i believe. If you have a better solution do tell.

**Comment by lk77** [comment] 2017-07-31 14:40
it's done already :
```
public function __get($field) {
    if($field == 'user') {
      return Sentinel::getUser();
    }
```
it's the best solution since the author wants to change a minimal amount of lines,
but it's clearly againt OOP

**Comment by lorvent** [comment] 2017-07-31 15:33
Thanks everyone for response.

@lk77 I have tried your solution but its not working (using php7.x)

**Comment by lk77** [comment] 2017-07-31 15:37
the final } si missing : 
`public function __get($field) {
    if($field == 'user') {
      return Sentinel::getUser();
    }`

**Comment by sisve** [comment] 2017-08-01 07:27
Once again, this is not a bug report. Close this issue and move it to the forums instead.

**Closed** 2017-08-01 13:21 UTC
