### ISSUE TITLE
Queue Deadlock error

### ISSUE THREAD

**Issue by xyrintech** [laravel/framework#25052] opened 2018-08-01 18:01 UTC
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: MySQL & 5.6

### Description:
Queue deadlock error when using database and 8 processes. 
Error: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (SQL: delete from `jobs` where `id` = 34)

### Steps To Reproduce:
Executing queues with 8 processes sometimes raises an error for deadlock.

**Comment by sisve** [comment] 2018-08-02 18:18
Can you show us the table structure of the jobs table?

**Comment by laurencei** [comment] 2018-08-04 03:03
Taylor has consistency said that Database Queue driver is not suited to large queue processes, for this exact reason.

You'll need to switch to Redis or Beanstalkd etc for a proper queue system.

**Comment by xyrintech** [comment] 2018-08-09 09:48
I believe this issue is there for the jobs which take long time to process i.e. 10 hours, 11 hours etc. 

Is this something we can handle?

I have tried setting the TTR to 172800 i.e. 48 hours.

**Comment by sisve** [comment] 2018-08-09 10:31
@xyrintech I asked for the table structure of your jobs table, can you provide it?

Can you also tell us if you've setup a separate connection in config/database.php for the queue, or using the default one?

**Comment by xyrintech** [comment] 2018-08-09 10:48
PFA
![screen shot 2018-08-09 at 4 17 05 pm](https://user-images.githubusercontent.com/7784136/43894456-b4b99d38-9bef-11e8-91aa-9be2d7fa62c4.png)

Its a default database connection.


I tried with beanstalkd and same issue with this well.

**Comment by sisve** [comment] 2018-08-09 11:10
Are you sure you get the same error when using beanstalkd? It doesn't make sense to get a sql error when using beanstalkd...

Can you export the structure as a CREATE TABLE statement? I'm not sure how to read the existing index information from phpmyadmin.

**Comment by xyrintech** [comment] 2018-08-09 12:05
php artisan queue:table - use this command and this is gonna give you the same structure :)

**Comment by xyrintech** [comment] 2018-08-09 12:07
I tried https://github.com/ph4r05/laravel-queue-database-ph4 and getting one issue with this. This is the one - 
https://github.com/ph4r05/laravel-queue-database-ph4/issues/5

**Comment by sisve** [comment] 2018-08-09 17:10
Please share the bugsnag details, it sounds really wonky to get this sql error from beanstalkd.

I asked about a CREATE TABLE statement. There is a purpose behind that. If I run the job without a custom string-length setup, then I would get another column length (and not 191). You have also not given us the exact Laravel version you're using.

An obvious attempt at a fix would be to move the queue system to a separate connection so that any transactions caused by the job or your application code does not affect the queue.

Next time you get the deadlock, get back to us with 1) a `CREATE TABLE jobs ...` statement to reproduce the structure, 2) the output of `SHOW ENGINE innodb STATUS`, and the exact Laravel version you're on.

I cannot help you further without these three pieces of information.

**Comment by laurencei** [comment] 2018-09-18 01:42
I'm going to close this issue. It's outside the scope of what Taylor has previously said is supported.

Although I can see in this thread some potential to solve the problem, but then it's more suited to the Laravel/Ideas area.

**Closed by laurencei** 2018-09-18 01:42 UTC
