### ISSUE TITLE
Route numeric parameter, additional chars allowed?

### ISSUE THREAD

**Issue by royduin** [laravel/framework#12566] opened 2016-03-01 17:21 UTC
With Laravel 5.2:

Route:
```
Route::get('/test/{test}','TestController@test');
```

Controller:
```
<?php
namespace App\Http\Controllers;

class TestController extends Controller
{
    public function test(\App\Test $test)
    {
    	echo $test->name;
    }
}

```

`/test/1` works but `/test/1something` also! I think somewhere `(int)$uriParam` is done which casts the variable to a integer. But this causes duplicated urls if someone links to it (I know I can use a meta canonical for this). Bug? Or just a nice to have?

**Comment by GrahamCampbell** [comment] 2016-03-01 19:39
I can't replicate?

**Comment by GrahamCampbell** [comment] 2016-03-01 19:39
Can anyone else?

**Comment by royduin** [comment] 2016-03-01 20:03
I'll create a demo to show you tomorrow.

**Comment by boynet** [comment] 2016-03-01 21:04
I can replicate just like he said laravel 5.2 php 5.5.9

**Comment by royduin** [comment] 2016-03-01 21:12
I'm using PHP 7, shall I still create a demo now it's confirmed by @boynet?

**Comment by boynet** [comment] 2016-03-01 21:15
sorry i am Unconfirim this.. living it to others to take look at, as laravel is actually producing sql like:
````
select * from `test` where `id` = '1something' limit 1
````
but mysql some why casting it to int and return a results

**Comment by royduin** [comment] 2016-03-01 21:19
Which MySQL version are you using? I'm on 5.6.

**Comment by boynet** [comment] 2016-03-01 21:22
seemse like knows feature for example http://dba.stackexchange.com/questions/89760/prevent-mysql-from-mangling-queries-by-casting-string-to-int
I think that if its really annoying you just don't use the automatic route model binding

**Comment by lagbox** [comment] 2016-03-02 06:37
>/test/1 works but /test/1something also!

What does that mean? I am having a hard time following what you are saying the problem is here.

**Comment by ksassnowski** [comment] 2016-03-02 10:02
@lagbox He's saying that the routes `/test/1` and `/test/1something` would both return the same model. He's assuming that this happens because somewhere along the line the `something` from the `1something` gets dropped from the URI which would leave us with `/test/1` again hence causing duplicate URIs. @royduin Correct me if I got that wrong.

**Comment by royduin** [comment] 2016-03-02 10:12
@ksassnowski, that's right!

I've used the [Laravel Debugbar](https://github.com/barryvdh/laravel-debugbar) to inspect the MySQL queries and I can confirm that Laravel is performing the query as @boynet said. So it's a MySQL "issue" or "feature". Maybe Laravel can "protect" us from this MySQL behavior because it's unwanted?

**Comment by GrahamCampbell** [comment] 2016-03-02 10:21
It doesn't seem like a laravel bug. It's just looking up the value, and the database is saying, yes, that exists, and here it is.

**Comment by GrahamCampbell** [comment] 2016-03-02 10:21
You'll need to chanage the database config to avoid this.

**Comment by royduin** [comment] 2016-03-02 10:33
So far I've not found a solution/option to disable this behavior through the configuration, anyone? Only by customizing the MySQL where clause as suggested on [Stack Exchange](http://dba.stackexchange.com/a/89813). If that's the only option, maybe Laravel can do something here?

**Comment by boynet** [comment] 2016-03-02 10:40
as temporary fix you can add route pattern like $router->pattern('text', '[0-9]+');
the question is if eloquent has a way to know if the primary id is int only?

**Comment by vlakoff** [comment] 2016-03-02 11:08
This *might* be fixed by adding the following test in `Router::substituteImplicitBindings` after the model is retrieved:

    $model->getRouteKey() == $parameters[$parameter->name]

Can you think of possible caveats?

**Comment by royduin** [comment] 2016-03-02 11:15
Nice @boynet, I've added `$router->pattern('test', '[0-9]+');` to the `boot()` function in the `app/Providers/RouteServiceProvider.php` file, that's working great! It would be nice if Laravel could do this implicit with every model primary key or as @vlakoff suggested by verifying the route key with the results from the database.

**Comment by boynet** [comment] 2016-03-02 11:23
@vlakoff we can also add pretest like if the model $incrementing is true, than we can assume that the primary key id int only, and in case of string return NotFoundHttpException before reaching the database

**Comment by vlakoff** [comment] 2016-05-11 16:38
Bump :)

**Comment by GrahamCampbell** [comment] 2016-09-07 08:09
We're open to PRs to fix this.

**Comment by theTrip73** [comment] 2016-09-13 17:57
Maybe this can be best accomplished by something that allows you to pass along a pattern in the $route->model() call, it could default to the integer pattern '[0-9]+' and be overloadable.

```
$router->model('user', 'App\User', '[0-9]+');
```

**Comment by themsaid** [comment] 2016-09-26 20:38
Hello Everyone,
I'm going to close this since it's not really a bug in the framework, but please feel free to open a PR in case you have an idea on how to deal with this MySQL behaviour.

Sorry :)

**Closed by themsaid** 2016-09-26 20:38 UTC

**Comment by theTrip73** [comment] 2016-09-27 06:10
I disagree. The general and most common use case for route model binding -- a feature of the framework -- is a numeric key, generally in the form of an integer database field. The only way around this behavior using the framework is to use character-based fields for all of your model keys.

If you are using a numeric key for your routes, you should not 500 errors when a bad URL is entered. The only solution other than the one previously mentioned is "don't use this feature".

This should remain open until a PR is submitted.

**Comment by lagbox** [comment] 2016-09-27 06:52
An idea, but perhaps not a good one (for implicit bindings):

What if we added another variable to the model for routing purposes, since we already have them for routing, and another method.

```php
protected $routeKeyPattern = '[0-9]+';
// or maybe also simply int, string, etc ... as well

public function getRouteKeyPattern() { ... }
```
Then you could have the `substituteImplicitBindings` check that pattern and throw a 404 if it doesn't match. 

This way you can at least define that pattern or 'lack' of one I suppose. I use slugs and hashes a lot so I would want to be able to adjust that away from checking for integers easily. You could say if there is no pattern defined, you could do as others are saying and perhaps check if its incrementing then force an int pattern.

Perhaps that doesn't belong on the model, but its another idea, at least for implicit bindings.

**Comment by themsaid** [comment] 2016-09-27 08:06
@theTrip73 It's a MySQL issue more than a laravel one, moreover you can easily get around this using something like:

```
$router->pattern('user', '[0-9]+');
```

I don't think we can auto cast it to integer or anything, it has to be done in the app code. Have a better idea?

**Comment by boynet** [comment] 2016-09-27 08:10
@themsaid its can be solved by looking at model $incrementing, if its true than auto apply the numeric pattern

**Comment by royduin** [comment] 2016-09-27 08:12
@themsaid, yes it is a MySQL issue, however there is no option in MySQL to disable this behavior so it would be nice if Laravel can "protect" us from it. I think @boynet his solution is great or if more people disagree then agree maybe just put it somewhere in the docs? So people are aware of this?

**Comment by themsaid** [comment] 2016-09-27 08:28
What if it's not true but the field is an integer? `patch_number`, `sku`, `barcode`, etc...

**Comment by boynet** [comment] 2016-09-27 08:33
yap its only 50% solving it, Its most be combination of protection from the core + a few words about it in the docs, maybe some warning that explain that mysql bug

**Comment by themsaid** [comment] 2016-09-27 08:36
IMHO I think it's something that can be left to the developer to deal with, anyway please feel free to open a PR or a docs PR or both with your suggestions.

Sorry to be the one closing issues :) but I'm just trying to keep only framework related issues so that we can start looking at them and try to fix.

**Comment by theTrip73** [comment] 2016-09-27 14:32
I'm willing to accept the $route->pattern() answer as the preferred solution to this problem, but that should come with two points:

(1) It *feels* disconnected. Being able to attach the pattern while creating the binding (via my proposed solution) or having it handled automatically somehow (via one of the other proposed solutions) feels like a more "whole" way to handle this.

(2) The documentation for Route Model Binding should be explicit about the need for a separate route pattern to prevent 500 errors that should be 404 errors when using numeric keys. (When you read that, does it *really* sound like it isn't a framework issue?)

**Comment by theTrip73** [comment] 2016-09-28 21:25
I have discovered an issue with the proposed developer solution by @themsaid. The suggestion to declare a global pattern has the explicit problem of being a *global* pattern. This can and will wreck routes that use the same route parameter name for a different value.

A decent example is an API route vs a front-end route, in which the front-end route references {my-parameter} as a slug-string and the API route references {my-parameter} as an integer. I think this is a fairly reasonable design pattern that won't work without having to get needlessly creative with one of the parameter names (i.e. {my-api-parameter}).

@GrahamCampbell, @taylorotwell -- do you agree with @themsaid that this *isn't* a framework issue?
