### ISSUE TITLE
SQLServer Date

### ISSUE THREAD

**Issue by totomakers** [laravel/framework#19595] opened 2017-06-14 09:34 UTC
- Laravel Version: 5.4.26
- PHP Version: 5.26.7
- Database Driver & Version:  sqlsrv - php_pdo_sqlsrv_56.dll

### Description:

When i tried to insert a date in SQLServer i got the following exception
`SQLSTATE[22007]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]`
nvarchar convertion to date time failed

When i debug the raw sql i got 

`insert into [dbo].[LMB 30-05-17$Job Journal Line] ([Journal Template Name], [Line No_], [Job No_], [Posting Date]) values (?, ?, ?, ?)', array('POINT', 50000, 'AF00007', '2017-06-13 00:00:00.000')`

`2017-06-13 00:00:00.000` look like valid when i run the following SQL Statement directly in SQLServer Manager

`insert into [dbo].[LMB 30-05-17$Job Journal Line] ([Journal Template Name], [Line No_], [Job No_], [Posting Date]) values ('POINT', 50000, 'AF00007', '2017-06-13 00:00:00.000')`

I go a query OK

### Steps To Reproduce:

+ Use a SQLServer database
+ Create table with a `datetime, not null` colum
+ Make a default model
+ Try insert a new line with a Carbon object

**Comment by themsaid** [comment] 2017-06-14 12:42
Duplicate of https://github.com/laravel/framework/issues/18991

Please look into previous issues, this was discussed several times.

**Closed by themsaid** 2017-06-14 12:42 UTC

**Comment by totomakers** [comment] 2017-06-14 12:51
I don't think is the same issue.

I added : 

```
   public function getDateFormat()
  {
    return 'd/m/Y H:i:s.000';
  }
```

Solve my issue for save, but break GET

```
 InvalidArgumentException

The separation symbol could not be found
Unexpected data found.
Unexpected data found.
Unexpected data found.
The format separator does not match
Trailing data
```

If i remove the getDateFormat, reading work.
