### ISSUE TITLE
PHPUnit 5.1 WithoutMiddleware Trait Issue

### ISSUE THREAD

**Issue by TheoKouzelis** [laravel/framework#11199] opened 2015-12-04 15:51 UTC
Hi 

Not sure if this is a issue, but today we updated from phpunit 5.0.10 to 5.1 in our Laravel 5.1 app and we got the error below. After a bit of debuging I think problem is the laravel TestCase class isn't being called for some reason, even though the test class is extending it. This meant that createApplication() was never called and the $app object was never created, which the trait then tries to use. 

I rolled phpunit back to 5.0.10 and everything worked again. Is this issue worth looking into further?
```
PHP Fatal error:  Call to a member function instance() on null in /vagrant/api/vendor/laravel/framework/src/Illuminate/Foundation/Testing/ApplicationTrait.php on line 189
PHP Stack trace:
PHP   1. {main}() /home/vagrant/.composer/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/vagrant/.composer/vendor/phpunit/phpunit/phpunit:56
PHP   3. PHPUnit_TextUI_Command->run() /home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:138
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:186
PHP   5. PHPUnit_Framework_TestSuite->run() /vagrant/api/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:429
PHP   6. PHPUnit_Framework_TestSuite->run() /vagrant/api/vendor/phpunit/phpunit/src/Framework/TestSuite.php:747
PHP   7. PHPUnit_Framework_TestSuite->run() /vagrant/api/vendor/phpunit/phpunit/src/Framework/TestSuite.php:747
PHP   8. PHPUnit_Framework_TestCase->run() /vagrant/api/vendor/phpunit/phpunit/src/Framework/TestSuite.php:747
PHP   9. PHPUnit_Framework_TestResult->run() /vagrant/api/vendor/phpunit/phpunit/src/Framework/TestCase.php:726
PHP  10. PHPUnit_Framework_TestCase->runBare() /vagrant/api/vendor/phpunit/phpunit/src/Framework/TestResult.php:681
PHP  11. ArticlesTest->disableMiddlewareForAllTests() /vagrant/api/vendor/phpunit/phpunit/src/Framework/TestCase.php:766
PHP  12. Illuminate\Foundation\Testing\TestCase->withoutMiddleware() /vagrant/api/vendor/laravel/framework/src/Illuminate/Foundation/Testing/WithoutMiddleware.php:15
```

**Comment by darthmaim** [comment] 2015-12-04 15:59
duplicate of #11197

**Comment by TheoKouzelis** [comment] 2015-12-04 16:16
Oops sorry didn't search the closed issues

**Comment by GrahamCampbell** [comment] 2015-12-04 16:18
https://github.com/laravel/laravel/blob/master/composer.json#L14

**Comment by GrahamCampbell** [comment] 2015-12-04 16:18
There's a reason we put 4.x in there. ;)

**Closed** 2015-12-04 16:18 UTC
