### ISSUE TITLE
CookieJar not working in 5.3.19

### ISSUE THREAD

**Issue by litan1106** [laravel/framework#16047] opened 2016-10-21 20:05 UTC
- Laravel Version: 5.3.19
- PHP Version: 7.0
- Database Driver & Version:

### Description:
Cookie queue not working in Laravel Version 5.3.19
`Cookie::queue('voted', true, 2628000);`

I reverted back to Laravel Version 5.3.18, everything works fine.

**Comment by themsaid** [comment] 2016-10-21 21:08
How does it not work? Please show a complete example we can use to replicate the issue.

**Comment by JC5** [comment] 2016-10-22 05:49
I have similar issues. I cannot flash data, it doesn't arrive. Can't reproduce it yet though.

**Comment by GrahamCampbell** [comment] 2016-10-22 09:20
What driver?

**Comment by JC5** [comment] 2016-10-22 09:35
Memcached, PHP7.0.8, memcached 1.4.25 Ubuntu

**Comment by amrelnaggar** [comment] 2016-10-22 23:35
Same issue here, I cannot flash data and cannot reproduce it. 
I reverted back to 5.3.18 and it works fine.

Laravel version: 5.3.19
Session driver: Cookie
PHP Version: 5.6.10

**Comment by GrahamCampbell** [comment] 2016-10-23 09:09
5.3.18's session and cookie components are identical to 5.3.19.

**Comment by themsaid** [comment] 2016-10-23 18:02
ping @litan1106

**Comment by sunscreem** [comment] 2016-10-23 18:10
Not sure if related but my `error`'s were empty, and `old` was empty until I went back to 5.3.18.

**Comment by litan1106** [comment] 2016-10-24 14:04
I couldn't reproduce it with a fresh install either.

**Comment by sunscreem** [comment] 2016-10-24 14:05
Could it be something like bugsnag or clockwork causing it?

**Comment by themsaid** [comment] 2016-10-25 11:24
> I couldn't reproduce it with a fresh install either.

Closing then, for other commenters please open new issues stating the problem in details with a simple example that would help others replicate the problem.

**Closed by themsaid** 2016-10-25 11:24 UTC
