### ISSUE TITLE
Eloquent: renameColumn doesn't work on columns with '-' in it with MariaDB

### ISSUE THREAD

**Issue by FSMaxB** [laravel/framework#22402] opened 2017-12-12 23:38 UTC
- Laravel Version: Lumen 5.5.2
- PHP Version: 7.0.22-0ubuntu0.16.04.1
- Database Driver & Version: 10.0.31-MariaDB

### Description:
When trying to rename a column with a `-`, the database throws a syntax error:
```
$ php artisan migrate

In Connection.php line 664:
                                                                                                        
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check   
  the manual that corresponds to your MariaDB server version for the right syntax to use near '-name g  
  ood_name VARCHAR(255) NOT NULL' at line 1 (SQL: ALTER TABLE bug CHANGE weird-name good_name VARCHAR(  
  255) NOT NULL)                                                                                        
                                                                                                        

In PDOConnection.php line 79:
                                                                                                        
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check   
  the manual that corresponds to your MariaDB server version for the right syntax to use near '-name g  
  ood_name VARCHAR(255) NOT NULL' at line 1                                                             
                                                                                                        

In PDOConnection.php line 77:
                                                                                                        
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check   
  the manual that corresponds to your MariaDB server version for the right syntax to use near '-name g  
  ood_name VARCHAR(255) NOT NULL' at line 1                                                             
                                                                                                        
```

I think the problem is that column name is not quoted, so the `-` is a syntax error. Maybe dbal is misbehaving?

### Steps To Reproduce:
```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class RenameBug extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('bug', function (Blueprint $table) {
            $table->string('weird-name');
        });

        Schema::table('bug', function (Blueprint $table) {
            $table->renameColumn('weird-name', 'good_name');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
```

**Comment by armandsar** [comment] 2017-12-13 15:23
I don’t think MariaDB is supported

**Comment by FSMaxB** [comment] 2017-12-13 15:29
MariaDB is essentially MySQL and I don't think it matters for my problem, because it clearly looks like the name is not escaped properly in the Query.

**Comment by FSMaxB** [comment] 2017-12-13 15:30
See also [here](https://mariadb.com/kb/en/library/mariadb-vs-mysql-compatibility/)

**Comment by FSMaxB** [comment] 2017-12-13 15:53
The query is:
```SQL
ALTER TABLE bug CHANGE weird-name good_name VARCHAR(  
  255) NOT NULL;
```

But it should be:
```SQL
ALTER TABLE bug CHANGE `weird-name` good_name VARCHAR(  
  255) NOT NULL;
```

See also [here](https://dba.stackexchange.com/questions/62051/alter-table-rename-a-column#62052).

This means that this bug happens exactly the same with MySQL.

I've tried chasing the Query through the laravel source code, but I couldn't find where it is actually using PDO to talk to the database.

**Comment by FSMaxB** [comment] 2017-12-13 16:02
Looks like the exception comes from [DBAL](https://github.com/doctrine/dbal/blob/73b2ad52389072ced2ecb85131ab5e22c7d88e07/lib/Doctrine/DBAL/Driver/PDOConnection.php#L77), so maybe it is their bug. But since I have no idea how Laravel uses DBAL, I'd like to get some help here.

**Comment by FSMaxB** [comment] 2017-12-15 09:36
I found [this](https://github.com/laravel/framework/blob/bd352a0d2ca93775fce8ef02365b03fc4fb8cbb0/src/Illuminate/Database/Schema/Grammars/RenameColumn.php) but I absolutely do not understand it!

**Comment by staudenmeir** [comment] 2018-10-06 22:06
As a workaround, you can quote the column name yourself:

```php
$table->renameColumn('`weird-name`', 'good_name');
```

**Comment by FSMaxB** [comment] 2018-10-10 21:47
But won't that break once the bug is fixed?

**Comment by staudenmeir** [comment] 2018-10-10 22:05
It doesn't like it's going to be fixed anytime soon.

**Comment by driesvints** [comment] 2018-11-22 14:02
Since MariaDB isn't a supported driver this won't be fixed in the core anytime soon.

**Comment by driesvints** [comment] 2018-11-22 14:33
I'll mark this as a bug for now and check later if we can solve this.

**Comment by staudenmeir** [comment] 2018-11-22 17:30
@driesvints This also affects MySQL, PostgreSQL and SQLite (and Laravel 5.7).

The issue is that `doctrine/dbal` only quotes identifiers if they are keywords. I find that rather weird, but they apparently have no plans to change this.

We could fix it by quoting the column names ourselves. This would work because `dbal` checks whether they are already quoted.

**Comment by driesvints** [comment] 2020-04-24 11:25
I'm gonna close this as this is more a dbal issue than a Laravel issue. For now you can work around it with the suggestion from staudenmeir above.

**Closed by driesvints** 2020-04-24 11:25 UTC
Labels: bug

**Comment by driesvints** [comment] 2020-04-24 11:27
There's a pr on dbal btw but it's for spaces: https://github.com/doctrine/dbal/pull/3876
