### ISSUE TITLE
`php artisan serve` showing server started but failed and then connects

### ISSUE THREAD

**Issue by gopalvirat** [laravel/framework#29231] opened 2019-07-19 07:59 UTC
- Laravel Version: 5.8.29
- PHP Version: 7.2.20
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.1.38-MariaDB

### Description:
Whenever `php artisan serve` command is run `Laravel development server started: <http://127.0.0.1:8000>` message is shown no matter if the default port is open or closed, either it should show the error message first and then connect to the open port or just connects to the next available port without showing any error.

### Steps To Reproduce:

- Make sure the default port(8000) is already in use.
- Install the laravel if not already installed, run `php artisan serve` in the console under the root directory.
- The console will show the `Laravel development server started: <http://127.0.0.1:8000>` message
![laravel](https://user-images.githubusercontent.com/35100967/61519220-f954aa80-aa28-11e9-8d6e-5298de90ad2d.png)

**Comment by driesvints** [comment] 2019-07-19 10:28
The problem is that we can't put the info message after we've attempted the serve because then the message isn't even shown:

![Screen Shot 2019-07-19 at 12 27 34](https://user-images.githubusercontent.com/594614/61529044-a24ad780-aa20-11e9-9ac7-8fac14c1b44f.png)

Here's the handle method:

https://github.com/laravel/framework/blob/1003c27b73f11472c1ebdb9238b839aefddfb048/src/Illuminate/Foundation/Console/ServeCommand.php#L40-L55

I don't think there's any way to solve this really. Sorry.

**Comment by gopalvirat** [comment] 2019-07-19 10:33
We can use 
```php
$connection = @fsockopen($this->host(), $this->port());

        if (is_resource($connection)) {
            fclose($connection);
            $this->portOffset += 1;
            return $this->handle();
        } else {
            $this->line("<info>Laravel development server started:</info> <http://{$this->host()}:{$this->port()}>");
            passthru($this->serverCommand(), $status);
        }

```
code to fix the issue you are saying.

**Comment by driesvints** [comment] 2019-07-19 10:47
@gopalvirat that works! Feel free to send in a PR. Thanks!

**Comment by gopalvirat** [comment] 2019-07-19 11:00
@driesvints on which branch should I sent a pull request?

**Comment by driesvints** [comment] 2019-07-19 11:08
This can be sent to 5.8 because I don't see any breaking changes afaik.

**Comment by driesvints** [comment] 2019-07-19 14:58
Taylor considers this a no-fix so closing this. Sorry.

**Closed by driesvints** 2019-07-19 14:58 UTC
Labels: bug

**Comment by AbrarAli14** [comment] 2023-01-17 20:23
this because of multiple server is running in your device 
for example: 2SERVERS 1.XAMMP AND File Zeila
