### ISSUE TITLE
Eloquent - Do not run relationship query if column value is NULL or 0

### ISSUE THREAD

**Issue by gthedev** [laravel/framework#20838] opened 2017-08-30 16:04 UTC
- Laravel Version: 5.2
- PHP Version: 7.0
- Database Driver & Version:

### Description:
I have various relationships within my Eloquent Models that look like this:

```
public function main_image()
{
    return $this->hasOne(Media::class, 'id', 'main_image_id');
}
```
_(I do realise that the relation here should be `belongsTo` but this is legacy code and I believe the relation type does not affect the issue at question here)_

However, it will run a SQL query if the `main_image_id` is `null` or `0`, so I end up with a number of queries like this:

`select * from `media` where `media`.`id` is null and `media`.`id` is not null limit 1`

Which obviously will not return anything, but still wastes resources. Is there any way of automatically checking for that?

I have tried to add the check myself:

```
public function main_image()
{
    if (!$this->main_image_id) {
        return null;
    }

    return $this->hasOne('App\Modules\Media\Models\Media', 'id', 'main_image_id');
}
```

But that gives me an error when trying to eager load:
`Call to a member function addEagerConstraints() on null`

I do realise that checking should not have an effect when eager loading, but it would be nice if we could have that sort of check when retrieving the relation for a single instance.

**Comment by Dylan-DPC** [comment] 2017-08-30 18:50
possible duplicate of #20616

**Comment by Dylan-DPC** [comment] 2017-08-30 18:50
possible duplicate of #20616

**Closed** 2017-08-30 21:02 UTC
