### ISSUE TITLE
sqlserver datetime

### ISSUE THREAD

**Issue by aisartag** [laravel/framework#19406] opened 2017-05-30 12:27 UTC
- Laravel Version: 5.4
- PHP Version: 7+
- Database Driver & Version:
  sql server 2016  php_pdo_sqlsrv_71_ts.dll 
### Description:
sql server datetime format

### Steps To Reproduce:
in migrations : error convert nvarchar to datetime relate fields created_at updated_at

tested patch's
in Illuminate\Database\Schema\Grammars\SqlServerGrammar class
methods  typeDateTime / typeTimestamp  return 'datetime2'

in Illuminate\Database\Query\Grammars\SqlServerGrammar class
public function getDateFormat()
    {
        return 'Y-m-d H:i:s.0000000';
    }

**Comment by ConnorVG** [comment] 2017-05-30 12:50
Could you please describe the issue and the steps to reproduce it? It's hard to understand, from what you've posted:
 - What the issue actually is;
 - How to reproduce said issue.

**Comment by aisartag** [comment] 2017-05-30 13:25
on launch db:seed user
[Illuminate\Database\QueryException]                                                                                                                         
  SQLSTATE[22007]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]La conversione di un tipo di dati nvarchar in datetime ha generato un valore non com  
  preso nell'intervallo dei valori consentiti. (SQL: insert into [users] ([name], [email], [password], [remember_token], [updated_at], [created_at]) values (  
  Ms. Jeanette Lind, mozell67@example.com, $2y$10$W2YmpsJKE2w6QXg4Z97WYuiy1ZMHBoAdznUPMpP7bFyAkWm3MN9IG, XqwisFf3Em, 2017-05-30 13:24:31.000, 2017-05-30 13:2  
  4:31.000))

**Comment by themsaid** [comment] 2017-05-30 13:45
Possible duplicate of: https://github.com/laravel/framework/issues/18991

**Comment by aisartag** [comment] 2017-05-31 12:16
sql server 2016
setting results at audit login :
set quoted_identifier on
set arithabort off
set numeric_roundabort off
set ansi_warnings on
set ansi_padding on
set ansi_nulls on
set concat_null_yields_null on
set cursor_close_on_commit off
set implicit_transactions off
set language Italiano
set dateformat dmy
set datefirst 1
set transaction isolation level read committed

the dateformat [dmy] conflict with 
public function getDateFormat()
    {
        return 'Y-m-d H:i:s.000';
    }

How to not reconfiguring db ?

**Comment by themsaid** [comment] 2017-06-12 20:42
Closing since it's a duplicate of an old issue.

**Closed by themsaid** 2017-06-12 20:42 UTC

**Comment by mgutierrez-ei** [comment] 2020-08-03 17:30
Hello there, I just came across this problem on my laravel (passport) - sqlserver configuration and I noticed the problem was that when running "php artisan migrate:refresh --seed" or "php artisan passport:install" the error "SQLSTATE[22007]:" appeared for the reason that laravel sends this date format "Y-m-d H:m:s.v" but sqlserver recevies "Y-d-m H:m:s.v" so I change the order of the format from 'Y-m-d H:m:s.v' to 'Y-d-m H:m:s.v' on SqlServerGrammar.php file

public function getDateFormat()
{
return 'Y-d-m H:m:s.v';
}

Worked from me!
Im commeting here too just in case

**Comment by darday** [comment] 2022-06-14 07:23
> Hello there, I just came across this problem on my laravel (passport) - sqlserver configuration and I noticed the problem was that when running "php artisan migrate:refresh --seed" or "php artisan passport:install" the error "SQLSTATE[22007]:" appeared for the reason that laravel sends this date format "Y-m-d HⓂ️s.v" but sqlserver recevies "Y-d-m HⓂ️s.v" so I change the order of the format from 'Y-m-d HⓂ️s.v' to 'Y-d-m HⓂ️s.v' on SqlServerGrammar.php file
> 
> public function getDateFormat() { return 'Y-d-m HⓂ️s.v'; }
> 
> Worked from me! Im commeting here too just in case

This Work Well, thanks so much 👍
