### ISSUE TITLE
Eloquent aggregation with soft delete.

### ISSUE THREAD

**Issue by vipaction** [laravel/framework#25419] opened 2018-09-03 07:58 UTC
- Laravel Version: 5.6.23
- PHP Version: 7.1.12
- Database Driver & Version: MySQL 5.7.21

### Description:
I want to get max position field value from related model. Both models, parent and related used soft delete trait.

```php
class Group extends Model
{
    use SoftDeletes;

    public function pages()
    {
        return $this->hasMany(Page::class)->orderBy('position');
    }
}
```
```php
class Page extends Model
{
    use SoftDeletes;

    public function group()
    {
        return $this->belongsTo(Group::class);
    }
}
```

### Steps To Reproduce:
```php
$position = Group::find(1)->pages()->max('position');
```
SQL query result: 
```php
select max(`position`) as aggregate from `pages` where `pages`.`group_id` = '2' and `pages`.`group_id` is not null
```

Expected: 
```php
select max(`position`) as aggregate from `pages` where `pages`.`group_id` = '2' and `pages`.`group_id` is not null and `pages`.`deleted_at` is null
```

**Comment by staudenmeir** [comment] 2018-09-03 11:50
It works for me, I get the expected SQL. Can you reproduce the issue on a fresh Laravel installation?

**Comment by driesvints** [comment] 2018-11-15 15:03
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Closed by driesvints** 2018-11-15 15:03 UTC
