### ISSUE TITLE
get error every second with predis 2.2

### ISSUE THREAD

**Issue by Rasoul-Karimi** [laravel/framework#51700] opened 2024-06-03 22:06 UTC
### Laravel Version

10.48.12

### PHP Version

8.2.5

### Database Driver & Version

postgresql 15

### Description

i get error after update predis to : "predis/predis": "^2.2"

`vendor/composer/../predis/predis/src/Command/ZSetRemove.php): Failed to open stream: No such file or directory`
`vendor/composer/ClassLoader.php:571)`

every second get this error

### Steps To Reproduce

laravel new bug-report --github="--public"

**Comment by crynobone** [comment] 2024-06-04 03:45
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment] 2024-06-05 12:05
duplicate of https://github.com/laravel/horizon/issues/1459

**Closed by crynobone** 2024-06-05 12:05 UTC
Labels: needs more info
