### ISSUE TITLE
Aborting in a controller constructor causes the controller to be constructed again.

### ISSUE THREAD

**Issue by malhal** [laravel/framework#14982] opened 2016-08-23 23:12 UTC
Put an abort in a controller constructor and you will find it will be called again, this causes the exception to be rendered twice. Below is an example stack trace from the second time the controller was constructed. It would appear to me that during the terminate process it attempts to gather the middleware which includes controller middleware so to get that it does need to construct the controller again. 

```
construct{"error":"HttpException","reason":"test"}construct
#0  App\Http\Controllers\RestController->__construct()
#1  ReflectionClass->newInstanceArgs(Array ()) called at [/Users/mh/Development/Laravel/wfff-passwords/vendor/laravel/framework/src/Illuminate/Container/Container.php:779]
#2  Illuminate\Container\Container->build(App\Http\Controllers\RestController, Array ()) called at [/Users/mh/Development/Laravel/wfff-passwords/vendor/laravel/framework/src/Illuminate/Container/Container.php:629]
#3  Illuminate\Container\Container->make(App\Http\Controllers\RestController, Array ()) called at [/Users/mh/Development/Laravel/wfff-passwords/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:699]
#4  Illuminate\Foundation\Application->make(App\Http\Controllers\RestController) called at [/Users/mh/Development/Laravel/wfff-passwords/vendor/laravel/framework/src/Illuminate/Routing/Route.php:203]
#5  Illuminate\Routing\Route->getController() called at [/Users/mh/Development/Laravel/wfff-passwords/vendor/laravel/framework/src/Illuminate/Routing/Route.php:316]
#6  Illuminate\Routing\Route->controllerMiddleware() called at [/Users/mh/Development/Laravel/wfff-passwords/vendor/laravel/framework/src/Illuminate/Routing/Route.php:278]
#7  Illuminate\Routing\Route->gatherMiddleware() called at [/Users/mh/Development/Laravel/wfff-passwords/vendor/laravel/framework/src/Illuminate/Routing/Router.php:655]
#8  Illuminate\Routing\Router->gatherRouteMiddleware(Illuminate\Routing\Route Object called at [/Users/mh/Development/Laravel/wfff-passwords/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:188]
#9  Illuminate\Foundation\Http\Kernel->gatherRouteMiddleware(Illuminate\Http\Request Object called at [/Users/mh/Development/Laravel/wfff-passwords/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:162]
#10 Illuminate\Foundation\Http\Kernel->terminate(Illuminate\Http\Request Object  Symfony\Component\HttpKernel\Exception\HttpException: test in /Users/mh/Development/Laravel/wfff-passwords/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line <i>907</i></th></tr>
called at [/Users/mh/Development/Laravel/wfff-passwords/public/index.php:58]
```

I discovered this when trying to make a validation result which applied to every POST method like this:

  ```
  public function __construct()
    {
        echo 'construct';
        if(\Illuminate\Support\Facades\Request::method() == 'POST'){
            if(Input::has('id')){
                throw new BadRequestHttpException('id must not be in the body');
            }
        }
```

however the actual example that generated the trace above was this:

    static $x = -1;
    public function __construct()
    {
        echo 'construct';
        self::$x = self::$x +1;
        if( self::$x){
            debug_print_backtrace();
            die();
        }
        abort(500, 'test');

    }

I could investigate this more if you like, or I could just workaround it and remember never to abort in a controller constructor.

**Comment by KKSzymanowski** [comment] 2016-08-25 11:11
The first exception comes from `$kernel->handle` executing normally(passing request through middleware, to controller and all that) and the second comes from `$kernel->terminate` trying to instantiate a controller to fetch all the middleware it requires and failing on `abort`.

Apart from the main issue here, I think you should use middleware for this kind of validation:

Middleware `FooMiddleware.php`
```php
public function handle($request, Closure $next)
{
    if($request->method() == 'POST' && $request->has('id')) {
        throw new BadRequestHttpException('id must not be in the body');
    }

    return $next($request);
}
```

`App\Http\Kernel.php`
```php
protected $routeMiddleware = [
    // previous declarations
    'foo' => \App\Http\Middleware\FooMiddleware::class
];
```

Controller:
```php
public function __construct()
{
    $this->middleware('foo');
}
```

Another approach(depends on your logic) would be to register `FooMiddleware` in `App\Http\Kernel::$middleware` in order to run on every request.

**Comment by GrahamCampbell** [comment] 2016-08-25 11:14
You should never use constructors in controllers to do things like this. For example, we instantiate them when you run the route:list command. However, there does remain a bug here where by if an exception was thrown for a genuine reason, we get double errors.

**Comment by GrahamCampbell** [comment] 2016-08-25 11:15
Hmm, but being constructed again is not a bug. Closing this.

**Closed** 2016-08-25 11:15 UTC

**Comment by malhal** [comment] 2016-08-25 11:29
Double exception is the bug, I can either rename this one or created another?
