### ISSUE TITLE
Queues - available_at is being set to exact same time next day, rate limiters not working

### ISSUE THREAD

**Issue by tadeas-j** [laravel/framework#35098] opened 2020-11-04 21:15 UTC
- Laravel Version: 8.13.0
- PHP Version: 7.4.1
- Database Driver & Version: MySQL

### Description:
RateLimited Middleware for Queues is not working properly.

I'm trying to rate limit a job for dispatching emails to 5 per minute.
Unfortunately, i'm not able to send even one email and i'm not able to do so even if i wait for 10 minutes.

It only works when i increase the rate limit to some higher number such as 30.

What is also very odd is that the available_at column is being updated to **+1 day** and **exact same time** no matter how long the jobs are apart from each other.

Even if the job fails, attempts are increased, available_at is changed, i get the message "processing & processed".

It does not try again even if i specify the retryUntil, it still sets the available_at to next day same time.

### Steps To Reproduce:

To Job : 

```
use Illuminate\Queue\Middleware\RateLimited;
public function middleware(){

    return [new RateLimited('send-mail')];

}
```
To AppServiceProvider boot method : 

```
use Illuminate\Cache\RateLimiting\Limit;
RateLimiter::for('send-mail', function($job){

     return Limit::perMinute(1);

});
```

Then when i dispatch new job and run `php artisan queue:work`, it will work maybe once, but all the other jobs will be available_at + 1 day.

**Comment by tadeas-j** [comment] 2020-11-04 23:59
I've just tested with 6 jobs.

Firstly, i've set the limit per minute to 5. It didn't process a single job as it should, all jobs got that exact same timestamp.

Then i've tried with setting it to 20, that started processing all the jobs one by one as it should.

**Comment by selcukcukur** [comment] 2020-11-05 00:10
> I've just tested with 6 jobs.
> 
> Firstly, i've set the limit per minute to 5. It didn't process a single job as it should, all jobs got that exact same timestamp.
> 
> Then i've tried with setting it to 20, that started processing all the jobs one by one as it should.

Given what you said, the problem is that in Laravel's structure, I think the job in a job queue may be stuck at a certain limit. Did I get it right?

**Comment by tadeas-j** [comment] 2020-11-05 00:17
> 
> 
> > I've just tested with 6 jobs.
> > Firstly, i've set the limit per minute to 5. It didn't process a single job as it should, all jobs got that exact same timestamp.
> > Then i've tried with setting it to 20, that started processing all the jobs one by one as it should.
> 
> Given what you said, the problem is that in Laravel's structure, I think the job in a job queue may be stuck at a certain limit. Did I get it right?

Maybe yes. Maybe something with the cache and retrieval of the timestamp of last run. Most certainly somewhere in the releasing back to queue functionality.

The weirdest thing here is that the job's **available_at** is updated to exact same time for all jobs, even for jobs which were ran apart several hours.

I understand that it's a vital part of the functionality to update the available_at in order to try to process the job only after the rate limit time elapses, but that is where the problem is i guess.

Definitely something within the **RateLimited middleware**.

**Comment by tadeas-j** [comment] 2020-11-05 00:24
I'm basically sending emails to MailTrap with rate limit of 2 emails per minute.

I've now discovered, that if you append sleep at least for 20 seconds to the end of the handle method, it will work as it should.

**Comment by selcukcukur** [comment] 2020-11-05 00:31
I think I understand the incident. When you add a RateLimited it gets stuck at $decayMinutes. This seems to be causing problems in the queue. Would you try to send it as Unlimited limit so that we can understand this?

**Comment by selcukcukur** [comment] 2020-11-05 00:33
Is everything ok when the limit is unlimited?

**Comment by tadeas-j** [comment] 2020-11-05 00:40
When i was running without the middleware, meaning without the limit, it worked just perfectly.

I'm blown away because it started behaving as it should randomly. I did not edit a thing at all but now the **available_at** is set correctly and only the jobs that should be rate limited actually are.

**Comment by tadeas-j** [comment] 2020-11-05 00:42
Just today i've updated from 8.6 to 8.13.0 to get the RateLimited middleware update. It seems that there is a bug.

The fact that it got somehow resolved on it's own is not a pleasing one, as it concerns me even more that i'm not able to investigate what was causing it and get a fix...

But this could be a huge problem in production.

**Comment by selcukcukur** [comment] 2020-11-05 00:44
@tadeas-j When I find that I will perform a check now, I will report the Commit where the relevant PR or Correction is found.

**Comment by tadeas-j** [comment] 2020-11-05 00:47
I know for sure that different jobs were set to same **available_at** even when hours apart. Also the **available_at** didn't change, it was always the same timestamp. (next day 5:40 pm - +1 days or something).

The thing was that sometimes even the first job processed was rate limited, which was just not possible. So we should take a look there too.

**Comment by tadeas-j** [comment] 2020-11-05 00:48
> 
> 
> @tadeas-j When I find that I will perform a check now, I will report the Commit where the relevant PR or Correction is found.

Okay, thank you. I will start digging into it tomorrow.

**Comment by selcukcukur** [comment] 2020-11-05 00:53
@tadeas-j Try it like this, I guess the problem is a recently added pr.

Job : 
```php
use Illuminate\Queue\Middleware\RateLimited;

public function middleware(){
    return [(new RateLimited('send-mail'))->dontRelease()];
}
```
AppServiceProvider
```php
use Illuminate\Cache\RateLimiting\Limit;

RateLimiter::for('send-mail', function($job){
     return Limit::perMinute(1);
});
```

**Comment by tadeas-j** [comment] 2020-11-05 01:02
@selcukcukur I'm not missing anything, the dontRelease call will remove the job from queue completely.

**Comment by selcukcukur** [comment] 2020-11-05 01:06
@tadeas-j dontRelease() Tells not to queue when limit is exceeded.

**Comment by tadeas-j** [comment] 2020-11-05 01:18
> 
> 
> @tadeas-j dontRelease() Tells not to queue when limit is exceeded. Got it, now I realized. This does not change the operation, it only reports the situation. I will try to find this situation interesting problem.

Were you able to reproduce it?

**Comment by selcukcukur** [comment] 2020-11-05 01:44
@tadeas-j PR : https://github.com/laravel/framework/pull/35100

Can you apply this and give it a try? I suspect there is an incorrect value return for the last added "$ shouldRelease". If my guess is correct, this PR will return that false value correctly.

**Comment by tadeas-j** [comment] 2020-11-05 01:51
> 
> 
> @tadeas-j PR : #35100
> 
> Can you apply this and give it a try? I suspect there is an incorrect value return for the last added "$ shouldRelease". If my guess is correct, this PR will return that false value correctly.

First, were you able to reproduce the bug at all?

Your changes won't work, they will break things. Now, when you will call dontRelease -> shouldRelease = false -> it will release, which is obviously not how it should work.

**Comment by selcukcukur** [comment] 2020-11-05 01:57
No I couldn't reproduce the error. It was probably a bug that occurred <8.13 ago, and it was fixed with a PR. When you get an update. I couldn't even encounter it, that's why I had it tested with the error screen.If everything is fine now, the best thing is not to overdo it.

**Comment by tadeas-j** [comment] 2020-11-05 01:59
Well, it happend to me once i've updated to 8.13, so the bug is here for this version.

**Comment by paras-malhotra** [comment] 2020-11-05 10:37
I'm unable to reproduce the bug on a fresh Laravel installation.

@selcukcukur your PR would produce an error. The ternary operator requires a second statement after the colon. Also, the the current code is fine because it is returning false to avoid the `$next($job)` to be called (so that the job is not processed).

**Comment by tadeas-j** [comment] 2020-11-05 14:18
Okay, figured out how it happened, steps to reproduce : 

1) Create composed RateLimiter such as this one : 
```
RateLimiter::for('emails', function($query){
  return [
     Limit::perDay(1),
     Limit::perMinute(1)
   ];
});
```

2.) Simply attach the RateLimiter to the Job class using RateLimited middleware : 
```
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Cache\RateLimiting\Limit;
public function middleware(){
    return [RateLimited('emails')];
}
```

Now go ahead and create 2 jobs and run `php artisan queue:work`, the behaviour we should get is that the first job should be processed and the second one should be rate limited.

What happens is that both jobs get rate limited and the **available_at** is set to **+1 day (perDay)**.

Then when you remove perDay : 
```
return [
   Limit::perMinute(1)
];
```

And wait several minutes, you can try to create 2 jobs and run `php artisan queue:work`. Both will get rate limited again and set to **available_at** same as the previous ones.

But if you set the perMinute to 200 for example, it will go through....

This is obviously not how it should work.

Please, investigate this thoroughly.

**Comment by taylorotwell** [comment] 2020-11-05 15:20
Give them different keys:

```php
Limit::perDay(1)->by('day-limit'),
Limit::perDay(1)->by('minute-limit'),
```

This will make the limits essentially use different "buckets" for counting.

**Closed by taylorotwell** 2020-11-05 15:20 UTC
