### ISSUE TITLE
getAttribute allows arbitrary method execution on a model

### ISSUE THREAD

**Issue by gmox** [laravel/framework#18238] opened 2017-03-07 12:56 UTC
- Laravel Version: 4.2+
- PHP Version: 5.6, 7.0
- Database Driver & Version: N/A

### Description: getAttribute()'s steps to get an attribute and otherwise attempt a relation allow any method that exists on `Model` to be executed.

https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L400

Now, assume that `delete` isn't an attribute on the Model, and let's call `getAttribute('delete')`:

1. Key is defined;
2. The array key does not exist;
3. The method does exist on self::class, but when calling on a class that extends Model, it's false.
4. This leaves the return call with `getRelationValue` left, which in turn calls `getRelationshipFromMethod` which will execute any arbitrary method passed into `getAttribute` that is not an attribute.

### Steps To Reproduce:

1. Create a model
2. Create an entity with that model `$user = Model::create(['data']);`
3. Call `$user->getAttribute('delete')` (or `$user->delete;`).

**Comment by themsaid** [comment] 2017-03-07 20:21
> The method does exist on self::class, but when calling on a class that extends Model, it's false.

`self::class` will return true since it's called inside the abstract Model class, and a delete method EXISTS in the abstract Model class.

**Comment by themsaid** [comment] 2017-03-07 20:21
`$user = Model::create(['data']);` is wrong, Model is an abstract class it can't be instantiated like this.

**Comment by gmox** [comment] 2017-03-07 20:22
It was `Model` as a palceholder for any given extension of `Model`. It could be `User` or `Product` or `FooBar`.

**Comment by themsaid** [comment] 2017-03-07 20:25
`if (method_exists(self::class, $key))` will always return true for a method that exists in the Model abstract class.

**Comment by gmox** [comment] 2017-03-07 20:31
Hm, so you're right. Either way:

`    >>> $userLogin = \App\Entities\UserLogin::first();
    => App\Entities\UserLogin {#1314
         id: 1,
         user_id: 2,
         ip_address: "127.0.0.1",
         created_at: "2017-03-02 12:54:36",
       }
    >>> $userLogin->getAttribute('delete');
    LogicException with message 'Relationship method must return an object of type Illuminate\Database\Eloquent\Relations\Relation'
    >>> $userLogin->exists
    => false`

**Comment by themsaid** [comment] 2017-03-07 20:42
Does `UserLogin` extend the `Model` class?

**Comment by themsaid** [comment] 2017-03-07 21:01
Looks like something is worn at your end, closing the issue since it's not a bug in the core. feel free to ping me if you need to continue the discussion though.

**Closed by themsaid** 2017-03-07 21:01 UTC
