### ISSUE TITLE
Laravel 5.5 - Left Join with find_in_set generates invalid sql???

### ISSUE THREAD

**Issue by Adam-78** [laravel/framework#23488] opened 2018-03-11 08:16 UTC
I have upgraded from laravel 5.2 to 5.5

However the following query with a left join using find_in_set generates invalid sql:

    return $this->model->from('job_alerts as a')
         ->leftJoin('locations as l', 'l.id', '=', DB::Raw("JSON_UNQUOTE(JSON_EXTRACT(a.criteria, '$.locationId'))"))
         ->leftJoin('industries as i', DB::raw("find_in_set(i.id, JSON_UNQUOTE(JSON_EXTRACT(a.criteria, '$.industries')))"), DB::raw(''),DB::raw(''))
         ->leftJoin('salaries as s', DB::raw("find_in_set(s.id, JSON_UNQUOTE(JSON_EXTRACT(a.criteria, '$.salaries')))"), DB::raw(''),DB::raw(''))
         ->where('user_id', '=', $userId)
         ->selectRaw("a.id
                    , a.name
                    , a.criteria
                    , JSON_OBJECT('Location',  l.name,
                                  'Industries', GROUP_CONCAT(DISTINCT(i.name) SEPARATOR ', '),
                                  'Salary', GROUP_CONCAT(DISTINCT(s.name) SEPARATOR ', ')) as formatted_criteria ")
         ->groupBy('a.id')
         ->orderBy('a.created_at', 'desc');

The resulting sql is now generating something as follows - as you can see it is adding `=` after each left join that contains find_in_set (where the 3rd and 4th parameter of the join is set to null or empty string)?

    select a.id 
         , a.name
         , a.criteria
         , JSON_OBJECT(
             'Location',  l.name,
             'Industries', GROUP_CONCAT(DISTINCT(i.name) SEPARATOR ', '),
             'Salary', GROUP_CONCAT(DISTINCT(s.name) SEPARATOR ', '),
                                 ) as formatted_criteria
    from `job_alerts` as `a` 
    left join `locations` as `l` on `l`.`id` = JSON_UNQUOTE(JSON_EXTRACT(a.criteria, '$.locationId')) 
    left join `industries` as `i` on find_in_set(i.id, JSON_UNQUOTE(JSON_EXTRACT(a.criteria, '$.industries'))) = 
    left join `salaries` as `s` on find_in_set(s.id, JSON_UNQUOTE(JSON_EXTRACT(a.criteria, '$.salaries'))) =
    where `a`.`user_id` = 1 group by `a`.`id` order by `a`.`created_at` asc)

This query was working fine in 5.2. Whats changed in 5.5? So basically omitting or setting the 3rd and 4th parameter of the `leftJoin` is causing this behaviour?

any ideas how to fix?

**Comment by staudenmeir** [comment] 2018-03-11 16:22
This was caused by #13576.

Can you solve it with a closure and `whereRaw()`?

    ->leftJoin('industries as i', function($query) {
        $query->whereRaw("find_in_set(...)");
    })

**Comment by Adam-78** [comment] 2018-03-11 17:25
@staudenmeir  yes, using the closure and where() seems to solve it. Many thanks.

**Comment by staudenmeir** [comment] 2018-03-11 17:33
Can you close the issue?

**Closed** 2018-03-11 17:50 UTC

**Comment by L-Y** [comment] 2018-08-28 07:39
I got this question too, good answer, thank you
