### ISSUE TITLE
[5.5.45] Method addMinutes does not exist.

### ISSUE THREAD

**Issue by ZUBAT** [laravel/framework#28404] opened 2019-05-03 08:51 UTC
Updating nesbot/carbon (1.36.2 => 1.37.0)
After this update session in Laravel stopped working.
BadMethodCallExceptionMethod addMinutes does not exist.
in Macroable.php line 96
at Carbon->__call('addMinutes', array(120))in StartSession.php line 203
at StartSession->getCookieExpirationDate()in StartSession.php line 177
at StartSession->addCookieToResponse(object(JsonResponse), object(Store))in StartSession.php line 71
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 149

**Comment by afridlund85** [comment] 2019-05-03 09:35
I have the same issue on a fresh laravel 5.5.45 install. Downgraded nesbot/carbon to 1.36.2 but still persists.

**Comment by driesvints** [comment] 2019-05-03 09:40
Please fill out the issue template when posting bug reports.

**Comment by Okipa** [comment] 2019-05-03 12:33
+1, just after a composer update, the problem has reappeared.  
I tries to smash the vendor and to rebuild it but it does not change anything.  
To reproduce the problem, you just have to execute a `php artisan queue:restart` in Laravel 5.5 for example.  
The following error is thrown :
```
In Macroable.php line 96:

  Method addSeconds does not exist.
```

**Comment by afridlund85** [comment] 2019-05-03 12:35
It has something to do with Carbon version 1.37.0. Installing 1.36.2 and clearing the `bootstrap/cache` folder fixes it. Have not found out what it is in Carbon 1.37.0 that causes it yet.

**Comment by kylekatarnls** [comment] 2019-05-03 13:05
Carbon tag removed, a new tag will replace it soon

**Comment by kylekatarnls** [comment] 2019-05-03 13:28
Patch released. Run `composer update` to get it.

**Comment by driesvints** [comment] 2019-05-03 13:32
Going to close this then since it's a carbon issue.

@kylekatarnls thanks for looking into this so quickly 👍

**Closed by driesvints** 2019-05-03 13:32 UTC
Labels: needs more info
