### ISSUE TITLE
queue jobs column out of range (integer)

### ISSUE THREAD

**Issue by erlangp** [laravel/framework#25612] opened 2018-09-13 21:59 UTC
#bugs

- Laravel Version: 5.6.33
- PHP Version: 7.1.20
- Database Driver & Version: mysql 5.7.19

### Description:
```
local.ERROR: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'attempts' at row 1 (SQL: update `jobs` set `reserved_at` = 1536874943, `attempts` = 256 where `id` = 256) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'attempts' at row 1 (SQL: update `jobs` set `reserved_at` = 1536874943, `attempts` = 256 where `id` = 256) at C:\\laragon\\www\\web1\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'attempts' at row 1 at C:\\laragon\\www\\web1\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:144, PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'attempts' at row 1 at C:\\laragon\\www\\web1\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:142)
```
### Steps To Reproduce:
run command
```bash
php artisan queue:work
```

**Comment by sisve** [comment] 2018-09-14 04:58
This happens if a job fails a lot of times and you haven't defined the maximum amount of times to retry it. Try `php artisan queue:work --tries=5` to try a job 5 times before classifying it as failed.

**Comment by sisve** [comment] 2018-09-14 12:48
Yes, you log errors, and you had a lot of them in a very fast loop. That results in a large log file. I'm not sure what the problem is, you could just remove the file and pretend this never happened.

**Comment by laurencei** [comment] 2018-09-17 23:49
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by laurencei** [comment] 2018-09-17 23:50
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

I'll be closing this ticket as it looks like the issue has been resolved.

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Closed by laurencei** 2018-09-17 23:49 UTC
