### ISSUE TITLE
[Bug] Failure to properly parse all valid URLs

### ISSUE THREAD

**Issue by csga5000** [laravel/framework#27133] opened 2019-01-11 01:12 UTC
- Laravel Version: Any
- PHP Version: Any
- Database Driver & Version: Any

### Description:
When doing routing based on the URL Laravel parses hex values in the URL which should not happen.  Other frameworks like Symfony don't have this issue.  This means that your routing system isn't using the "URL" for routing you're "decoding" the URL, so it's routing is done on the string produced when the the entire URL has been decoded (which makes no sense, why would you ever want to urldecode an entire URL rather than it's individual parameters separately?).

### Steps To Reproduce:
Pass url encoded strings are parameters in a URL and your route will note match

Ex:
```
Route::get('pdf_header/{patient}/{mrn}', 'TranscriptionController@pdf_header')
```

Navigate to `http://app.com/pdf_header/johnsmith/123%2F123`

**Comment by ahinkle** [comment] 2019-01-11 05:15
Duplicate of #22125

**Comment by driesvints** [comment] 2019-01-11 13:45
The encoded `%2F` problem you're showing above is indeed a duplicate of the issue linked above. At the moment the behavior should be the same as in Symfony. As noted in the issue linked above we won't be changing this any time soon.

There is a documented way to circumvent this though: https://laravel.com/docs/5.7/routing#parameters-encoded-forward-slashes

**Closed by driesvints** 2019-01-11 13:45 UTC

**Comment by ahinkle** [comment] 2019-01-14 02:41
If you “don’t have time” to upgrade your project to the latest security and patches that have solutions to your problem; that’s a problem within itself. 

I would recommend using https://laravelshift.com/ to upgrade your project to the latest version. It’s quick and painless.

**Comment by csga5000** [comment] 2019-01-14 07:58
And ignore any other good point made here.  It's not a great solution and actually does not solve my problem because I'm using two arugments, and is there even a guarantee the version is why it's not working?
