### ISSUE TITLE
Validation passes if a rule returns "false" without a message

### ISSUE THREAD

**Issue by NaturalBornCamper** [laravel/framework#29171] opened 2019-07-15 18:19 UTC
- Laravel Version: 5.8.21
- PHP Version: 7.1

### Description:
If creating a custom validation rule, in the `passes()` method, try returning `false` without setting `$this->message = 'this is my error message'` and validation will still pass. Same happens if returning `null` in the `message()` method.

Not sure if it's a feature or a bug, but it seems dangerous to leave it like that. For example I would prefer an error with no message than a successful login because of a missing message

### Steps To Reproduce:
1- Create a validation class
2- In the `passes()` method, just return `false` without setting the message
3-Submit the form and watch it validate

#### Controller

```
use App\Rules\ApiMemberPassword;
class ApiAuthController extends Controller
    public function password_post(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'password' => ['bail', 'required', new ApiMemberPassword],
        ]);

        if ($validator->fails()) {
            exit('invalid');
        }
        exit('valid');
    }
}
```

#### Validation Rule

```
namespace App\Rules;
class ApiMemberPassword implements Rule
{
    private $message;

    public function passes($attribute, $value)
    {
        return false;
    }

    public function message()
    {
        return $this->message;
        // The line below would do the same
        // return null;
    }
}
```

**Comment by stevebauman** [comment] 2019-07-15 18:30
Please show your code and usage - I'm not able to reproduce this.

Also, please include the patch version you are using in Laravel - i.e. `<major>.<minor>.<patch>`

**Comment by NaturalBornCamper** [comment] 2019-07-15 18:43
Didn't realize I had a patch version, I added it, with some code

**Comment by stevebauman** [comment] 2019-07-15 19:18
Yup I'm able to reproduce this as well on 5.8.19.

**Comment by stevebauman** [comment] 2019-07-15 19:25
Issue is with `validateUsingCustomRule()` method here:

https://github.com/laravel/framework/blob/4b0cdaf46174aa933aff69789f89e9aa435645cb/src/Illuminate/Validation/Validator.php#L570-L583

Since the `message()` method returns `null`, the array is empty and the message does not get added into the validator which allows it to pass.

**Comment by driesvints** [comment] 2019-07-16 10:12
PR was merged.

**Closed by driesvints** 2019-07-16 10:12 UTC
