### ISSUE TITLE
Eager loading relations of a polymorphic relation

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#20475] opened 2017-08-08 10:11 UTC
Hi,

The issue has been raised before https://github.com/laravel/framework/issues/15248 and it's a valid point.

For me i have a meeting model that has a `reviewables` polymorphic relation.

The problem is that each one of the polymorphic related model have their own relations as well that i want to eager load to reduce the number of queries.

But if i do

```php
$query->with(['reviewables.student', 'reviewables.teacher' ...])
```

I'll get an error since the `student` relation exist on some of the models, the same goes for `teacher` relation

I really hope that laravel core team revisit the idea of checking relation existance when eager loading relations on a polymorphic relation.

**Comment by themsaid** [comment] 2017-08-08 16:38
duplicate of https://github.com/laravel/framework/issues/15248

No point for keeping 2 issues for the same reported matter, I don't think there's an easy way to implement this but feel free to open a PR :)

**Closed by themsaid** 2017-08-08 16:38 UTC
