### ISSUE TITLE
table()->join()->where()->delete() generates incorrect SQL using Query Builder

### ISSUE THREAD

**Issue by cbj4074** [laravel/framework#16573] opened 2016-11-28 18:31 UTC
- Laravel Version: 5.1.45
- PHP Version: 7.0.13
- Database Driver & Version: PostgreSQL(libpq) Version 9.5.5

@benubird reported this in the form of a PR, back in 2014:

https://github.com/laravel/framework/pull/5652

The PR was submitted to the wrong branch and later closed (presumably because the submitter never followed-up).

Relative to some of Query Builder's other feats, this seems like pretty basic functionality that should be implemented.

@sporchia submitted a subsequent PR, https://github.com/laravel/framework/pull/5703 , which appears to have addressed the same issue in Eloquent, so perhaps the same logic could be applied to Query Builder.

**Comment by fernandobandeira** [comment] 2016-11-29 11:03
We could use #5652 but it works only for mysql, you said that you are working on postgresql, your database doesn't support inner joins on delete.

The best thing here would be to provide support for the ``` using ``` syntax since it works on more databases.

Some databases like sqlite works only with subselects so this is something that we should think before rushing a PR.

**Comment by srmklive** [comment] 2016-11-29 13:47
@cbj4074 #5703 was later reverted in #5711.

**Comment by srmklive** [comment] 2016-11-29 13:49
@fernandobandeira The change you are suggesting might break the Query Builder implementation for Postgres :simple_smile:  That's my only worry.

**Comment by fernandobandeira** [comment] 2016-11-29 15:13
Yeah we need to treat sqlite and Postgres differently, #5703 was moved to affect just MySQL as it broke Postgres https://github.com/laravel/framework/pull/5703#issuecomment-55357789

> I moved it to the MySQL grammar.

**Comment by cbj4074** [comment] 2016-12-02 19:00
Thanks so much for taking a look, @srmklive and @fernandobandeira .

Excellent point regarding the lack of support for inner joins with delete in PostgreSQL.

I lack any direct experience with the grammar engine... are you comfortable implementing this, @fernandobandeira ? I'd be most appreciative. :+1:

**Comment by fernandobandeira** [comment] 2016-12-02 19:34
Yes i'll take a look into it, but the using syntax is also used in MySQL and it behaves differently on selects and update so it's something that should be implemented with care, but I should create a PR for 5.4, i've created one to add the support for joins on Sqlserver, so we will support the joins in all possible drivers, this issue will turn into a feature request after that merge, not sure if it should remain open... Maybe we should create one on the internals and close this one 😄 ...

**Comment by themsaid** [comment] 2017-03-02 14:23
I wonder if https://github.com/laravel/framework/pull/18156 fixes this issue?

**Comment by fernandobandeira** [comment] 2017-03-02 14:26
@themsaid This one is actually a feature request to include support for joins when deleting using the postgres driver, currently we don't support it, we can't support it since postgres doesn't allow you to use joins on delete queries... IMO we can close this since it's not a bug and we can't really add support for it...

**Comment by themsaid** [comment] 2017-03-02 14:27
Thank you @fernandobandeira

**Closed by themsaid** 2017-03-02 14:27 UTC
Labels: database
