### ISSUE TITLE
Event expression not matching cron. Simplify reading of scheduled tasks

### ISSUE THREAD

**Issue by jaumesala** [laravel/framework#20555] opened 2017-08-14 11:38 UTC
I've just realized that the methods `between()` and `unlessBeteen()` do not store the value in the schedule's expression property. I guess this is because the `artisan schedule:run` command is executed every minute so we only need to evaluate if we are between that time interval (calling the method `inTimeInterval()`). Still is there any other reason for not storing the "hours" value in the schedule's expression property?

https://github.com/laravel/framework/blob/23b8d992ea1f35b346a62024ebeb4af6969b161a/src/Illuminate/Console/Scheduling/ManagesFrequencies.php#L29-L32

```php
$schedule
    ->command('inspire')
    ->cron('*,30 3-7 * * 1,2');

dd($schedule->events()[0]->getExpression()); 
// artisan schedule:run -> "*,30 3-7 * * 1,2" (correct)
```
```php
$schedule
    ->command('inspire')
    ->weekly()
    ->days(1,2)
    ->between('3:00', '7:00')
    ->everyThirtyMinutes();

dd($schedule->events()[0]->getExpression()); 
// artisan schedule:run -> "0,30 0 * * 1,2 *" (incorrect)
```
The reason behind this question is that I was thinking about the idea of implementing an artisan command to list the scheduled tasks and their cron expression in the terminal, something like `schedule:list`: What do you think @themsaid

```
+-------------------+-----------------+-----------------+----------------+---------------------+
| Expression        | Command         | Prevent Overlap | On Maintenance | Task Output         |
+-------------------+-----------------+-----------------+----------------+---------------------+
| *,30 3-7 * * 1,2  | database:backup | true            | false          | app/logs/backup.log |
| 0 3,15 * * * *    | Inspire         | false           | false          |                     |
+-------------------+-----------------+-----------------+----------------+---------------------+
```

**Comment by laurencei** [comment] 2017-08-14 11:44
This is intended. The "between" is an adjutant to the expression - not a replacement.

It would be seriously difficult to modify an existing expression and magically add the expected times into it. There are too many variables.

The options are to either hard code your cron expression with the times, or use the dynamic properties of the scheduler.

**Comment by jaumesala** [comment] 2017-08-14 12:09
Thanks @laurencei for your reply. I agree with you about modifying an existing expression, but what about overwriting the "hours" value?

I mean, in the example above, let's say we have `->between('3:00', '7:00')` that adds '3-7' to the expression, and later on  we call `->hourlyAt(17)`. The final results could just be '17' overwriting the value... The days work in the same way right now, you can't concatenate two days `->mondays()->turesdays()` = '2' (instead of '1,2').

My point here is to find a way to "store" the full expression of the task so we can output its value if we want to build a table, or read the value for whatever reason...
Thanks again @laurencei

**Comment by laurencei** [comment] 2017-08-14 13:21
The problem is that works for hours - but not minutes.

There is no way in the expression to store `->between('3:30', '7:30')`

**Comment by themsaid** [comment] 2017-08-14 15:50
@laurencei point is a concern, there's no way we can consider minutes that's why it's just used as an extra condition not included in the actual cron expression. I suggest that you just ignore this edge case and show the cron expression as is, it'll be hard to list extra conditions on the event in the table so you may consider this case of them.

**Comment by jaumesala** [comment] 2017-08-15 22:17
I've updated the title to reflect the discussion. As a reference, here's a sample output of ```schedule:list``` implemented in the PR. Opinions needed.

![schedule-list2](https://user-images.githubusercontent.com/385551/29338066-04312602-8214-11e7-997d-ddd880f802be.png)

**Comment by themsaid** [comment] 2017-08-16 09:24
Well since there are no plans to change this at the moment I'm going to close the issue, but please feel free to open a PR with your proposed change or use https://github.com/laravel/internals to discuss a change proposal.

Thanks :)

**Closed by themsaid** 2017-08-16 09:24 UTC
Labels: Under Discussion
