### ISSUE TITLE
event:generate command namespace issue

### ISSUE THREAD

**Issue by ankurk91** [laravel/framework#27468] opened 2019-02-09 16:04 UTC
- Laravel Version: 5.7.25 || 5.8.2
- PHP Version: 7.2.13
- Database Driver & Version: NA

### Description:
`php artisan event:generate` command assumes that event class exists in `app\Events`

### Steps To Reproduce:
Update your `EventServiceProvider` with event class that is coming from vendor, for [example](https://laravel.com/docs/5.7/passport#events)
```php
protected $listen = [
    'Laravel\Passport\Events\AccessTokenCreated' => [
        'App\Listeners\RevokeOldTokens',
    ],
];
```
Run `php artisan event:generate`
Check your `app/Listeners/PruneOldTokens.php` file, it should have wrong namespace imported.
```
use App\Events\Laravel\Passport\Events\RefreshTokenCreated;
```

**Comment by devcircus** [comment] 2019-02-09 16:20
Seems like a job for the make:listener command.

**Comment by driesvints** [comment] 2019-02-11 11:19
What happens when you use the `::class` notation instead?

**Comment by ankurk91** [comment] 2019-02-11 12:15
Tried this 
```php
    protected $listen = [
        \Laravel\Passport\Events\AccessTokenCreated::class => [
            'App\Listeners\RevokeOldTokens',
        ],
    ];
```
But same results

**Comment by imanghafoori1** [comment] 2019-02-11 22:52
I can not reproduce it on laravel 5.7.x

**Comment by ankurk91** [comment] 2019-02-12 06:52
@imanghafoori1
I have laravel passport installed, so i am sure that 
`
Laravel\Passport\Events\AccessTokenCreated
`
event class exists

**Comment by setkyar** [comment] 2019-02-28 13:08
I can not reproduce the bug on 5.7.x It does successfully import like the following

```
use App\Providers\Laravel\Passport\Events\AccessTokenCreated;
```

But, if you don't install `passport` it seems like the behavior you described. Please make sure for us.

**Comment by stancl** [comment] 2019-03-01 15:05
5.7.28

```php
'Foo\Bar\Nonexisting\Event' => [
    'App\Listeners\Foo',
],
```

```bash
$ cat Events/Foo/Bar/Nonexisting/Event.php
<?php

namespace App\Events\Foo\Bar\Nonexisting;
```

I think the correct behavior in the case of nonexisting non-`\App` events would be throwing an error?

**Comment by ankurk91** [comment] 2019-03-03 04:56
Another finding -
The command work well with [event](https://laravel.com/docs/5.7/notifications#notification-events) from `Illuminate` namespace
```
// EventServiceProvider
protected $listen = [
    'Illuminate\Notifications\Events\NotificationSent' => [
        'App\Listeners\LogNotification',
    ],
];
```

**Comment by devcircus** [comment] 2019-03-25 15:47
I've looked over the code involved with ```event:generate``` and believe I've come up with the problem and a solution. Looking for feedback before making a PR.

It all happens in the ListenerMakeCommand class.

There is a check to see if the given event namespace starts with (1)your project namespace(App), (2)"Illuminate", or (3)"\\".

So it looks like the command expects 3 situations:
1. Your event is somewhere in your project's namespace.
2. Your event is in the Illuminate namespace.
3. Your event is elsewhere and you are showing that by starting with a '\\'.

If those assumptions are true, then you should be able to generate listeners from events in third party namespaces by adding a starting '\\' to your event in the ```$listen``` array of your EventServiceProvider. 
However, if you do that, then the '\\' doesn't get dropped and the namespace at the top of the generated listener for your event, will still have the starting '\\'.

I propose a simple call to ```trim``` when replacing the 'DummyFullEvent' at the top of the listener class. 
So instead of:
```php
    return str_replace(
        'DummyFullEvent', $event, $stub
    );
```
We can do:
```php
    return str_replace(
        'DummyFullEvent', trim($event, '\\'), $stub
    );
```
And the Event namespace will be correct in the Listener class.

Thoughts?

I've ran several test scenarios with this change in place and everything seems to work as expected?

**Comment by driesvints** [comment] 2019-03-25 15:59
@devcircus lgtm 👍

**Comment by driesvints** [comment] 2019-03-26 17:20
PR was merged.

**Closed by driesvints** 2019-03-26 17:20 UTC
Labels: bug

**Comment by devcircus** [comment] 2019-03-26 17:24
#28007 was merged.

> Note: Using ```event:generate``` as described by the OP, will still not work. 

The command expects one of three event namespace styles:
1. Your event is in your local project's namespace (eg. App)
    - In this case, either import your event at the top of the service provider, or if it doesn't exist yet, just use the string version(eg. 'App\Events\MyEvent').
2. Your event is in the Illuminate namespace. 
    - You can either import the event class or use the string version starting with 'Illuminate'.
3. Your event is in a third-party namespace. 
    - You must use the string version and start it with a '\\'. (eg. '\MyGreatVendor\\MyGreatPackage\\MyGreatEvent')

I guess this could be looked at in the future for a better way to handle all of these cases without having to differentiate, but for now, this should work.

**Comment by ac1982** [comment] 2019-12-11 01:41
#30796 I'v open a new issure for my problem. 
Three ways only one could be work, and the others would not.
I do not think the problems were solved.
