### ISSUE TITLE
Send $value as second param to when() callback on query builder

### ISSUE THREAD

**Issue by mblarsen** [laravel/framework#14892] opened 2016-08-19 03:41 UTC
Just a suggestion. What about sending $value as second parameter to query builders when() callback.

    $query->when($someValueThatMightExist, function ($query, $someValueThatMightExist) { ... });

This is to avoid having to use use:

    function () use ($someValueThatMightExist) { ... }

Ps: I know it is not solely for data-values, but an expression in general, however the test is left to a truthy value rather than strict bool:

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Query/Builder.php#L471

**Comment by kasparsklavins** [comment] 2016-08-19 11:03
I'm against this. 
Php already provides a way for closures to use variables from an upper scope.

**Comment by themsaid** [comment] 2016-09-05 22:17
Closing since it's not a bug report and the suggestion seems to be disliked by members of the community, however you're free to open an issue in https://github.com/laravel/internals repo if you wish to continue discussions.

**Closed by themsaid** 2016-09-05 22:17 UTC
