### ISSUE TITLE
Unable to migrate database using sqlsrv (could not find driver)

### ISSUE THREAD

**Issue by mrkalmdn** [laravel/framework#19403] opened 2017-05-30 08:15 UTC
- Laravel Version: 5.4.23
- PHP Version: 7.0.10
- Database Driver & Version: SQLSRV 2008 r2

### Description:
Hi! I can access all of the existing tables but when migrating (creating a new one), I'm getting this error.

Here is an example of my .env

DB_CONNECTION=sqlsrv
DB_HOST=xxx.xxx.x.xx
DB_PORT=1433
DB_DATABASE=database
DB_USERNAME=username
DB_PASSWORD=password

![image](https://cloud.githubusercontent.com/assets/10385316/26573920/12a96982-4552-11e7-969c-086e6d386167.png)

Thanks!

**Comment by themsaid** [comment] 2017-05-30 09:00
Maybe related to: https://stackoverflow.com/questions/2852748/pdoexception-could-not-find-driver

Closing since it's not a bug in the core but feel free to ping me if you need further assistance.

**Closed by themsaid** 2017-05-30 09:00 UTC

**Comment by mrkalmdn** [comment] 2017-05-30 13:30
@themsaid Thank you for your response. But I have already configured the extensions in php.ini and still getting this error.

**Comment by mrkalmdn** [comment] 2017-05-31 00:13
@themsaid Should I re-open this issue? I still can't migrate.

Here's a screenshot of my phpinfo

![phpinfo](https://cloud.githubusercontent.com/assets/10385316/26610231/e67e212c-45d8-11e7-818e-e049796bfba3.png)

Thanks

**Comment by N30** [comment] 2018-03-07 16:10
I was not able to fix this with PDO_ODBC or the Microsoft Official PDO_SQLSRV. The solution for me was to install the PDO_SQLSRV drivers from a 3rd party website. I found the drivers through http://robsphp.blogspot.nl/2012/06/unofficial-microsoft-sql-server-driver.html

**Comment by flik** [comment] 2018-04-01 04:43
I have fixed this issue with:

I have to enable mysql and pdo extentions in my linux server then after restart apache
I executed commands: 
```
php artisan key:generate
php artisan config:clear
php artisan config:cache
```
Then everything fixed:

**Comment by mrkalmdn** [comment] 2018-04-03 02:28
@flik, I'm using SQL Server not MySQL. I only experience this issue when using the Express Edition.

**Comment by flik** [comment] 2018-04-03 03:55
@mrkalmdn  This issue come when your SQL or Mysql drivers are not installed and enabled properly. so you just need to confirm. It will be fixed automatically

**Comment by Afzalafu** [comment] 2018-10-12 14:22
test

**Comment by Roldification** [comment] 2019-02-27 06:32
is this already solved? i am facing the same issue right now.

**Comment by bunday** [comment] 2019-03-29 17:44
Well, I had a different issue. I can interract with my DB on the browser but i cant through php artisan on my terminal. What i did is to have a route to make my artisan calls 

`Route::get("/test", function(){
Artisan::call("migrate:refresh");
//Or any other Artisan call
});`

**Comment by dimahali** [comment] 2019-10-01 12:01
I am running into same problem, I can connect to the sqlsrv database in the browser but cannot in CMD. I am using the same PHP both in apache and CMD using environment variables. Any updates?

**Comment by martinsagat** [comment] 2021-04-27 00:58
Please make sure you download the right driver depending on which PHP version you are using:
https://pecl.php.net/package/pdo_sqlsrv
copy to php ext folder, and include it in your php.ini

**Comment by shankarGdev** [comment] 2021-05-19 11:13
The problem is two different php.ini files used by apache and cmd. To solve it, add those extension in php.ini file inside respective PHP version. It's working for me.
