### ISSUE TITLE
maximum function nesting reached after laravel update 5.1.35 to 5.1.36

### ISSUE THREAD

**Issue by dietercoopman** [laravel/framework#13790] opened 2016-05-31 12:55 UTC
After the update from 5.1.35 to 5.1.36 our application was broken, did some research and found that when i overwrite Model.php of Illuminate with the previous version everything works fine. This commit broke our code https://github.com/laravel/framework/commit/45fb88125fc931127804c1da111b72798565e9a7

we are using PHP 5.5.9

**Comment by GrahamCampbell** [comment] 2016-05-31 14:25
Thank you. This is a duplicate of https://github.com/laravel/framework/issues/13768.

**Closed** 2016-05-31 14:25 UTC
