### ISSUE TITLE
Mail customization callbacks are invoked too late

### ISSUE THREAD

**Issue by Alexander--** [laravel/framework#22982] opened 2018-02-01 10:23 UTC
- Laravel Version: 5.5
- PHP Version: 7

### Description:
I am trying to customize the way Laravel composes my email messages. For example, I'd like to encode the message and embedded text files with base64 (because default quoted-printable encoding wastes too much space with non-ascii text).

Unfortunately, Laravel/Illuminate hooks for customizing SwiftMessage are applied too late, after many properties of message are set in stone.

### Steps To Reproduce:

I have extended the `Mailable` class:

````php
class BaseMessage extends Mailable
{
    public function build() {
        return $this
            ->withSwiftMessage(function(\Swift_Message $msg) {
                $msg->setEncoder(new \Swift_Mime_ContentEncoder_Base64ContentEncoder());
            });
            ->view('_mail.sample_email');
    }
}
````

Unfortunately, the code above does not accomplish anything (the non-ascii parts of mail are still encoded with quoted-printable).

Quick research shows, that `send` function of `Mailable` is calling `runCallbacks` after the message is already built.

Here goes a second try: I override `send` and try to register callbacks as early as possible:

````php
public function send(MailerContract $mailer)
    {
        Container::getInstance()->call([$this, 'build']);

        $this->withSwiftMessage(function(\Swift_Message $msg) {
            $msg->setEncoder(new \Swift_Mime_ContentEncoder_Base64ContentEncoder());
        });

        $mailer->send($this->buildView(), $this->buildViewData(), function ($message) {
            $this
                ->runCallbacks($message)
                ->buildFrom($message)
                ->buildRecipients($message)
                ->buildSubject($message)
                ->buildAttachments($message);
        });
    }
````

The code above successfully encodes attachments, but primary message body (contained in `_mail.sample_email'`) is still encoded in quoted-printable instead of base64.

This appears to happen because `Illuminate\Mail\Mailer` [calls user-supplied callback](https://github.com/laravel/framework/blob/7553c0b/src/Illuminate/Mail/Mailer.php#L220) *after* invoking addContent on SwiftMailer message.

Perhaps, I might be able to implement my custom mailer, and/or muck around with internal structure of SwiftMessages but that's way too much setup to customize few emails.

Seems like the ability to customize emails is more or less broken, so maybe there is no harm in changing the code to invoke `call_user_func` a couple lines earlier.

**Comment by themsaid** [comment] 2018-02-01 16:45
Feel free to open a PR with your suggested changes, however as far as I understand this might be a breaking change so you'd need to target 5.6

**Comment by themsaid** [comment] 2018-02-01 16:45
Closing since it's not a bug but rather a feature/enhancement.

**Closed by themsaid** 2018-02-01 16:45 UTC
