### ISSUE TITLE
Feature Request: firstOrFail but for the full result set

### ISSUE THREAD

**Issue by jacobfogg** [laravel/framework#14753] opened 2016-08-10 23:16 UTC
So I am using:

`return self::where('somefield', $someValue)->firstOrFail() `

in my models. I would love a similar feature for returning all results. Something like

`return self::where('somefield', $someValue)->allOrFail()`

The end result would be that if 1 or more results were found, it would return them, otherwise it would return the same exception as firstOrFail.

If there is a better place for me to post this request, I am happy to do so. I might also be willing to take a stab at developing the method...

**Comment by themsaid** [comment] 2016-09-06 08:46
You can post this on the internals channel, https://github.com/laravel/internals it's the place for proposals and discussions.

I'm closing this since it's not a bug a bug report but please feel free to create an issue in the internals repo or create a PR.

**Closed by themsaid** 2016-09-06 08:46 UTC
