### ISSUE TITLE
Doctrine\Common\Inflector\Inflector is deprecated and will be removed in Symfony 4.0

### ISSUE THREAD

**Issue by MyIgel** [laravel/framework#32730] opened 2020-05-08 23:35 UTC
- Laravel Version: master
- PHP Version: 7.4.5
- Database Driver & Version: not relevant

### Description:
The `Doctrine\Common\Inflector\Inflector` class is deprecated, [Symfony\Component\Inflector\Inflector](https://symfony.com/components/Inflector) should be used instead)

### Steps To Reproduce:
Set error reporting to warning and have a look at the error log

**Comment by MyIgel** [comment] 2020-05-08 23:38
A fix was available in https://github.com/laravel/framework/pull/32724 but that PR got closed

**Comment by GrahamCampbell** [comment] 2020-05-08 23:40
Thanks for getting in touch. Deprecation warnings are not considered bugs, however we will be moving to the new code in this case, because we can (there are other examples where we use deprecated code but cannot upgrade within Laravel 6). Once a replacement PR to Laravel 6.x has been submitted, this issue will be resolved.

**Comment by Theremsoe** [comment] 2020-05-09 01:03
In addition, this warning affects at `Illuminate\Support\Str::singular` method generating bad singular string.

 - Example: `status` => `statu`

<img width="1207" alt="Captura de Pantalla 2020-05-08 a la(s) 8 02 47 p m" src="https://user-images.githubusercontent.com/1402411/81459719-edc4a280-9166-11ea-9fac-9832caa2821a.png">

**Comment by MyIgel** [comment] 2020-05-09 08:45
So make it a feature request or whatever but it breaks tests (if warnings get converted to exceptions for example during unit tests) or at least shows warning messages in them and i personally prefer to have none of them in my projects (and yeah, i could pin `"doctrine/inflector": "1.3.*"` but thats even worse) :D

**Comment by andrey-helldar** [comment] 2020-05-09 08:53
@Theremsoe, this is the problem of the package used ([see](https://github.com/doctrine/inflector/blob/master/lib/Doctrine/Inflector/Rules/English/Inflectible.php)). Write them about it.

**Comment by GrahamCampbell** [comment] 2020-05-09 09:36
The bug with status is a problem upstream, and will be fixed soon I hope.

The deprecation is not a bug, but will be addressed all the same, soon.

**Comment by GrahamCampbell** [comment] 2020-05-09 09:37
> Symfony\Component\Inflector\Inflector should be used instead

I don't think so?

**Closed by GrahamCampbell** 2020-05-09 09:36 UTC

**Comment by mfn** [comment] 2020-05-11 06:15
When I deployed a project which utilizes the `illuminate/database` component amongst others, I was greeted with the following reports in sentry:
> The "Doctrine\Common\Inflector\Inflector::pluralize" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API.

The reason why the project was "affected" (nothing "broke" but sentry was flooded a bit) is that the custom built-in error handler was not checking if the current `error_reporting()` is `0` which it is when the `@`-operator is used.

> Set error reporting to warning and have a look at the error log

> So make it a feature request or whatever but it breaks tests (if warnings get converted to exceptions for example during unit tests) or at least

My Laravel projects as well as my other projects _using laravel components_ where not affected by the tests, which I'm running via PHPUnit. Simply because PHPUnits error handler exactly does the same thing as Laravel:
- in case of `trigger_error` being encountered
- it explicitly checks if `error_reporting()` is `0` and if so, ignore it and just continues

I'm just mildly curious what setup you have which achieved which did the exception conversation when PHPUnit intercepts that flow. Are you using a custom error handler, overriding the one of PHPUnit or running next to it?

**Comment by MartinsOnuoha** [comment] 2020-05-14 12:07
It appears that this also affects the static method ```::all(..)``` on Models

![image](https://user-images.githubusercontent.com/29035007/81932476-c9901800-95e3-11ea-9d4d-8c7d00a8ae6f.png)

**Comment by GrahamCampbell** [comment] 2020-05-14 13:07
@MartinsOnuoha Run `composer update`.

**Comment by GrahamCampbell** [comment] 2020-05-14 13:08
Locking this because all the discussions are caused by people using old code because they haven't updated to the latest version of Laravel.
