### ISSUE TITLE
[5.4] Illuminate/Session/Middleware/AuthenticateSession.php breaks remember me functionality

### ISSUE THREAD

**Issue by anhvun** [laravel/framework#18689] opened 2017-04-06 10:17 UTC
- Laravel Version: latest 5.4.18
- PHP Version: 7
- Database Driver & Version: 

### Description:
Including the commented
\Illuminate\Session\Middleware\AuthenticateSession::class in the
'web'-middleware-group breaks the remember me functionality from make:auth-implementation.

### Steps To Reproduce:
Use laravel's make:auth with a proper database configured in .env file.
Include the commented
\Illuminate\Session\Middleware\AuthenticateSession::class,
in 
app/Http/Kernel.php into $middlewareGroups-'web' -section.

Set session lifetime to 1 minute in config/session.php and
log in with remember me checkbox checked, and wait over 1 minute.
Refresh the page.
Results : 
Without the AuthenticateSession-middleware home-page reloads normally and user is still signed in.
With the middleware however, the user will be kicked back to login page and is no longer signed in, even when going to homepage -url manually. 

Shouldn't the remember me token still make sure that the user is signed in? The AuthenticateSession-middleware merely checks if the session-hash-password is the same as user-hash-password, and kicks out if user-hash-password has changed while still logged in.

**Comment by Dylan-DPC** [comment] 2017-04-11 18:43
5.3 is no longer supported. You need to check if bug still exists in 5.4

**Comment by anhvun** [comment] 2017-04-13 09:04
Referencing https://laracasts.com/discuss/channels/laravel/authenticatesession-middleware
Will test it with Laravel 5.4 then

**Comment by anhvun** [comment] 2017-04-14 19:50
Tested with latest 5.4. Same problem.

**Comment by pix2D** [comment] 2017-05-27 10:13
Having the same issue on 5.4.

**Comment by antoine1302** [comment] 2017-05-28 01:38
+1 here. It looks like the "password_hash" session keys is not set during loggin resulting to logout the current user (Line 51 in AuthenticateSession Middleware). So do we need to manually set the "password_hash" value into the session ?

**Comment by Azirius** [comment] 2017-06-12 08:38
I also seem to be suffering with this problem 👍  Not sure of a way to get around it at the moment. Anyone have any temporary fixes?

**Comment by aocneanu** [comment] 2017-06-17 12:08
Same issue.

**Comment by TenMediaBln** [comment] 2017-07-19 14:46
Same here on latest 5.4.

**Comment by devcircus** [comment] 2017-07-19 15:03
#19843 related?

**Comment by elasticsteve** [comment] 2018-02-15 15:35
In the other threat you've closed it, pointing to this one, and in this threat you closed it, pointing to the other one! This is going in circles! Where is the fix?

**Comment by Riari** [comment] 2018-02-15 15:46
@elasticsteve this issue is not closed.

**Comment by DanielDarrenJones** [comment] 2018-03-02 13:45
+1, is this issue fixed in later laravel versions?

**Comment by barryvanveen** [comment] 2018-03-07 10:07
I've tested this in Laravel 5.5.28 and it seems to work just fine for me. I'm not sure when this was fixed or how, but I cannot reproduce the problem.

**Closed** 2018-04-08 15:44 UTC

**Comment by pedrofurtado** [comment] 2018-09-14 19:20
https://github.com/laravel/framework/issues/16311
