### ISSUE TITLE
[5.1] Concurrent requests wiping out the session 

### ISSUE THREAD

**Issue by vikasddun** [laravel/framework#14385] opened 2016-07-20 08:04 UTC
We are using Laravel( framework version - 5.1.37) to create REST APIs which are then consumed by a NodeJS server. We are using file driver for session storage. On some of the pages, we need to make 5-6 API requests almost simultaneously, all of which are read requests not making any write on session. Most of the times, this cause the removal of session and hence user gets logged out.

I have seen the similar problems mentioned in #7549 #5416 , but haven't found any solution yet. Any suggestions ?

**Comment by rreynier** [comment] 2016-07-20 14:06
Though this likely should be fixed, I suggest using Redis or Memcache driver if possible. As mentioned in other issues, there may be some file corruption going on when 4-5 things are trying to read/write the same file on the disk.

**Comment by GrahamCampbell** [comment] 2016-07-20 16:49
The only true way to fix this is to not allow concurrent requests, since how do you know which request actually has the session data you want. A way to achieve this could be by making yourself a locking middleware. I've implemented on that only uses redis as a lock server.

**Closed** 2016-07-20 16:48 UTC

**Comment by GrahamCampbell** [comment] 2016-07-20 16:49
https://github.com/AltThree/Locker/blob/master/src/Http/Middleware/LockingMiddleware.php

**Comment by GrahamCampbell** [comment] 2016-07-20 16:49
It only locks for "non-safe" requests, but could be modified to lock all requests per IP.

**Comment by Bonobomagno** [comment] 2016-10-06 13:59
What about a delay? Something like occ?

**Comment by denjaland** [comment] 2017-03-02 15:46
Sorry about not noticing this issue earlier - @GrahamCampbell could you perhaps have a look at my description for #18187?  This issue was referenced, but I'm thinking the issue is q bit different.
I think my proposed solution does in fact fix (part) of the problems in the various use cases I've noticed.

Thanks!

**Comment by dsandber** [comment] 2018-11-30 23:03
Am I correct that this issue (multiple concurrent requests will overwrite the session and thus cause token mismatches or unauthorized access errors) still exists in Laravel 5.7?  And that using Redis or Cookies for session storage won't help since the session will still be non-atomically updated on requests?
