### ISSUE TITLE
Errorexception rename operation not permitted

### ISSUE THREAD

**Issue by AndreaRunner** [laravel/framework#26462] opened 2018-11-09 17:22 UTC
- Laravel Version: 5.7.13
- PHP Version: 7.2.9
- Database Driver & Version: mysql

### Description:
Hi,
after a laravel fresh installation :
composer create-project --prefer-dist laravel/laravel example
and install same packages:
composer require barryvdh/laravel-debugbar 
composer require adldap2/adldap2-laravel 
...
if i make composer update, i have this error:
 ErrorException  : rename(/home/vagrant/sites/example/bootstrap/cache/packages.php0xeFNI,/home/vagrant/sites/example/bootstrap/cache/packages.php): Operation not permitted
Exception trace:

  1   rename("/home/vagrant/sites/example/bootstrap/cache/packages.php0xeFNI", "/home/vagrant/sites/example/bootstrap/cache/packages.php")
      /home/vagrant/sites/example/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:146

  2   Illuminate\Filesystem\Filesystem::replace("/home/vagrant/sites/example/bootstrap/cache/packages.php", "<?php return array (
  'adldap2/adldap2-laravel' =>
  array (
...

@php artisan package:discover works fine without error

How to resolve this issue ?
Andrea

**Comment by driesvints** [comment] 2018-11-12 10:17
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by mfn** [comment] 2018-11-12 11:44
I believe this is yet another problem with the `PackageManifest` issue, latest PR which is on 5.7 is https://github.com/laravel/framework/pull/26254

- First added in https://github.com/laravel/framework/issues/25898
- Reverted in https://github.com/laravel/framework/pull/26231 because of all the problems
- Again added in https://github.com/laravel/framework/pull/26254

ping @driesvints

**Comment by driesvints** [comment] 2018-11-12 11:57
Heya, sorry. Might have been a bit too quick with thinking this was a mere permission error. 

From what I can understand is that the rename fails because of a permission error. This means the update is done with a different user than the user which cloned or installed the app in the first place?

I can't reproduce this locally so it should be something specific to your setup @AndreaRunner? Can you provide more info: is this using Homestead? Where are you running the commands? Inside or outside your Vagrant box?

**Comment by mfn** [comment] 2018-11-12 12:06
What I also meant/tried to say (but obviously didn't): these permission errors may do surface because of the way the PackageManfist works, by using the new `replace` method.

It creates a new file and tries to replace the old one.

The old code simply tried to overwrite.

_Might_ be the users problem exists without this, but: the new `replace` code does manually change the permissions, that's why I'm hinting at it => https://github.com/laravel/framework/blob/96d4ece0e2494da90f6ecc338fe4a39f0fe1aa43/src/Illuminate/Filesystem/Filesystem.php#L142

**Comment by AndreaRunner** [comment] 2018-11-12 13:06
@driesvints 
I use Homstead, make vagrant ssh and all commands are issued with vagrant user
remember that @php artisan package:discover works fine without error

**Comment by driesvints** [comment] 2018-11-13 13:49
Ok well gonna close this then as your problem was resolved.

**Closed by driesvints** 2018-11-13 13:49 UTC
Labels: needs more info

**Comment by AndreaRunner** [comment] 2018-11-13 13:51
ok thanks !

**Comment by kjfdebruin** [comment] 2018-11-20 07:05
I'm getting the same error with a fresh install of  5.7.* Laravel.

I'm on Homestead 4.0.0 ( Ubuntu 16.04.3 LTS) on Windows 10.

`vagrant halt` followed by `vagrant up` solved it for me.

**Comment by mohammad6006** [comment] 2018-12-11 17:18
same error but when I close Sublime text 3 problem solved;

I don't know which setting of sublime should I change to solve this problem

**Comment by RossTsachev** [comment] 2019-03-09 09:44
@mohammad6006 I have exactly the same issue with Sublime Text 3, have you found a solution?

**Comment by pavlix** [comment] 2019-11-18 11:57
Similar issue with Linux kernel build, looks like a bug in vboxsf file system.
