### ISSUE TITLE
Prefixed Redis Connections not working as expected for scan command

### ISSUE THREAD

**Issue by ragingdave** [laravel/framework#24257] opened 2018-05-20 01:16 UTC
- Laravel Version: 5.6.22
- PHP Version: 7.1.17
- Database Driver & Version: 4.0.2

### Description:
In both PhpRedis and Predis connections when running a scan command, the prefix doesn't appear to function as expected. In a non-prefixed predis connection, scanning with a match of `test` on a prefilled redis database like:
```
test
test1
test2
```
I get the expected single result of test.
When running that same test will prefixed entries in the database like:
```
pre:test
pre:test1
pre:test2
```
and the same match condition, I get no results.

I would assume the expectation would be that any command run on a prefixed connection would only operate on that prefix and that the prefix usage would basically just be invisible like:

```
// Both prefixed and non-prefixed connections
$redis->set('key1', 'value');
$result = $redis->scan('key*');
// $result = ['key1'];
```
This is even backed up by the Predis client options (https://github.com/nrk/predis/wiki/Client-Options)
> Specifies a string used to automatically prefix all the keys contained in a command issued to Redis.)

### Steps To Reproduce:
1. Create 2 connections, one prefixed and one not.
2. Before each run of the scan command, prefill the redis database like shown above, where the prefix is never manually added other than in the connection options.
3. Note that a scan command does not return the same results and scan calls to the prefixed connection yields no results.

**Comment by driesvints** [comment] 2018-11-19 16:53
@ragingdave gonna close this due to inactivity. Feel free to reply if this is still an issue.

**Comment by matt-allan** [comment] 2020-02-18 17:57
I just ran into this same issue. @driesvints could you reopen this please?

Reproduction steps using `php artisan tinker` and the `phpredis` driver:

```
>>> RedisFacade::set('example:123', '1')
=> true
>>> RedisFacade::scan('', 'example:*')
=> []
```

If you open `redis-cli` in another terminal and run `MONITOR` you can see the following commands being executed:

```
1582048092.501213 [0 127.0.0.1:57806] "SET" "laravel_database_example:123" "1"
1582048101.392400 [0 127.0.0.1:57806] "SCAN" "0" "MATCH" "example:*"
```

The same issue occurs when using the `Redis` class directly so I think we need to implement [a similar solution to the `ZADD` command](https://github.com/laravel/framework/blob/b47217e41868d3049ec545cbb713aa94c6f39e55/src/Illuminate/Redis/Connections/PhpRedisConnection.php#L225).

**Comment by driesvints** [comment] 2020-02-20 09:40
@matt-allan does anything from the attempted PR help? https://github.com/laravel/framework/pull/24299

**Comment by matt-allan** [comment] 2020-02-20 14:32
@driesvints thanks for reopening this. There have been a lot of changes since #24299 in both the connection class and the tests that should make fixing this easier. I will try and put a PR together today or early next week.

**Comment by AegirLeet** [comment] 2020-02-20 14:37
There's also a PhpRedis issue for this at https://github.com/phpredis/phpredis/issues/548. Might be better to fix it there instead of creating a workaround that breaks as soon as PhpRedis starts respecting the prefix.

**Comment by AegirLeet** [comment] 2020-02-21 09:08
See https://github.com/phpredis/phpredis/issues/548#issuecomment-589533853.

**Comment by ragingdave** [comment] 2020-02-21 13:34
That comment would seem to suggest that we would then need versioned phpredis connections to account for that difference?

**Comment by AegirLeet** [comment] 2020-02-21 13:50
It sounds like it's going to be an optional feature you have to specifically opt-in to (for BC reasons), so we don't **have** to take it into account. Although it might make sense to add a version check and delegate prefix handing to PhpRedis in the future.

**Comment by driesvints** [comment] 2020-04-23 14:14
Closing this as this seems like a PhpRedis issue rather than a Laravel issue.

**Closed by driesvints** 2020-04-23 14:14 UTC
Labels: bug

**Comment by AegirLeet** [comment] 2020-05-19 08:43
FYI PhpRedis has merged support for a new `SCAN_PREFIX` option which will automatically prepend the prefix to SCAN commands. Once a version with this feature is released, Laravel could add (optional) support for it.
