### ISSUE TITLE
Laravel new app with phpunit error

### ISSUE THREAD

**Issue by JeffreyDavidson** [laravel/framework#20461] opened 2017-08-07 15:30 UTC
- Laravel Version: 5.4.*
- PHP Version: 7.1
- Database Driver & Version:

### Description: When I am creating a new laravel application within my terminal and run phpunit with my global command I get the following error.

PHP Warning:  is_dir() expects parameter 1 to be a valid path, object given in /Users/jeffreydavidson/.composer/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php on line 56

```
➜  Code laravel new test
Crafting application...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 59 installs, 0 updates, 0 removals
  - Installing doctrine/inflector (v1.1.0) Loading from cache
  - Installing erusev/parsedown (1.6.3) Loading from cache
  - Installing jakub-onderka/php-console-color (0.1) Loading from cache
  - Installing symfony/polyfill-mbstring (v1.4.0) Loading from cache
  - Installing symfony/var-dumper (v3.3.6) Loading from cache
  - Installing psr/log (1.0.2) Loading from cache
  - Installing symfony/debug (v3.3.6) Loading from cache
  - Installing symfony/console (v3.3.6) Loading from cache
  - Installing nikic/php-parser (v3.1.0) Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2) Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1) Loading from cache
  - Installing psy/psysh (v0.8.11) Loading from cache
  - Installing vlucas/phpdotenv (v2.4.0) Loading from cache
  - Installing symfony/css-selector (v3.3.6) Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.0) Loading from cache
  - Installing symfony/routing (v3.3.6) Loading from cache
  - Installing symfony/process (v3.3.6) Loading from cache
  - Installing symfony/http-foundation (v3.3.6) Loading from cache
  - Installing symfony/event-dispatcher (v3.3.6) Loading from cache
  - Installing symfony/http-kernel (v3.3.6) Loading from cache
  - Installing symfony/finder (v3.3.6) Loading from cache
  - Installing swiftmailer/swiftmailer (v5.4.8) Loading from cache
  - Installing paragonie/random_compat (v2.0.10) Loading from cache
  - Installing ramsey/uuid (3.7.0) Loading from cache
  - Installing symfony/translation (v3.3.6) Loading from cache
  - Installing nesbot/carbon (1.22.1) Loading from cache
  - Installing mtdowling/cron-expression (v1.2.0) Loading from cache
  - Installing monolog/monolog (1.23.0) Loading from cache
  - Installing league/flysystem (1.0.41) Loading from cache
  - Installing laravel/framework (v5.4.32) Loading from cache
  - Installing laravel/tinker (v1.0.2) Loading from cache
  - Installing fzaninotto/faker (v1.6.0) Loading from cache
  - Installing hamcrest/hamcrest-php (v1.2.2) Loading from cache
  - Installing mockery/mockery (0.9.9) Loading from cache
  - Installing webmozart/assert (1.2.0) Loading from cache
  - Installing phpdocumentor/reflection-common (1.0) Loading from cache
  - Installing phpdocumentor/type-resolver (0.3.0) Loading from cache
  - Installing phpdocumentor/reflection-docblock (3.2.1) Loading from cache
  - Installing phpunit/php-token-stream (2.0.0) Loading from cache
  - Installing symfony/yaml (v3.3.6) Loading from cache
  - Installing sebastian/version (2.0.1) Loading from cache
  - Installing sebastian/resource-operations (1.0.0) Loading from cache
  - Installing sebastian/recursion-context (2.0.0) Loading from cache
  - Installing sebastian/object-enumerator (2.0.1) Loading from cache
  - Installing sebastian/global-state (1.1.1) Loading from cache
  - Installing sebastian/exporter (2.0.0) Loading from cache
  - Installing sebastian/environment (2.0.0) Loading from cache
  - Installing sebastian/diff (1.4.3) Loading from cache
  - Installing sebastian/comparator (1.2.4) Loading from cache
  - Installing phpunit/php-text-template (1.2.1) Loading from cache
  - Installing doctrine/instantiator (1.0.5) Loading from cache
  - Installing phpunit/phpunit-mock-objects (3.4.4) Loading from cache
  - Installing phpunit/php-timer (1.0.9) Loading from cache
  - Installing phpunit/php-file-iterator (1.4.2) Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1) Loading from cache
  - Installing phpunit/php-code-coverage (4.0.8) Loading from cache
  - Installing phpspec/prophecy (v1.7.0) Loading from cache
  - Installing myclabs/deep-copy (1.6.1) Loading from cache
  - Installing phpunit/phpunit (5.7.21) Loading from cache
symfony/var-dumper suggests installing ext-symfony_debug ()
symfony/console suggests installing symfony/filesystem ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/class-loader ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
symfony/translation suggests installing symfony/config ()
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (~3.0).)
laravel/framework suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (~2.5).)
laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun and Mandrill mail drivers and the ping methods on schedules (~6.0).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
laravel/framework suggests installing nexmo/client (Required to use the Nexmo transport (~1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (~2.0).)
laravel/framework suggests installing symfony/dom-crawler (Required to use most of the crawler integration testing tools (~3.2).)
laravel/framework suggests installing symfony/psr-http-message-bridge (Required to psr7 bridging features (0.2.*).)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.1)
phpunit/phpunit suggests installing ext-xdebug (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Generating optimized autoload files
> php -r "file_exists('.env') || copy('.env.example', '.env');"
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
> php artisan key:generate
Application key [base64:ALfHrEPSwEGMhA2nGhN/8JChyiLeabXdVF2NqDe+4nU=] set successfully.
Application ready! Build something amazing.
➜  Code cd test
➜  test phpunit
PHP Warning:  is_dir() expects parameter 1 to be a valid path, object given in /Users/jeffreydavidson/.composer/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php on line 56

Warning: is_dir() expects parameter 1 to be a valid path, object given in /Users/jeffreydavidson/.composer/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php on line 56
PHP Recoverable fatal error:  Object of class PHPUnit\Framework\TestSuite could not be converted to string in /Users/jeffreydavidson/.composer/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php on line 32

Recoverable fatal error: Object of class PHPUnit\Framework\TestSuite could not be converted to string in /Users/jeffreydavidson/.composer/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php on line 32
```

**Comment by themsaid** [comment] 2017-08-07 19:16
duplicate of https://github.com/laravel/framework/issues/20452

**Closed by themsaid** 2017-08-07 19:16 UTC
