### ISSUE TITLE
Illuminate/Workbench with Laravel 5.1

### ISSUE THREAD

**Issue by camilstaps** [laravel/framework#9115] opened 2015-06-07 10:21 UTC
The combination

    "require": {
         "laravel/framework": "~5.1.0@dev",
         "illuminate/workbench": "dev-master"
     },

results in update errors:

      Problem 1
        - Conclusion: remove symfony/finder v2.7.0
        - Conclusion: remove laravel/framework 5.1.x-dev
        - Conclusion: don't install symfony/finder v2.7.0
        - Conclusion: don't install symfony/finder v2.6.9
        - Conclusion: don't install symfony/finder v2.7.0-BETA2|install symfony/finder v2.6.9
        - Conclusion: don't install symfony/finder v2.6.8
        - Installation request for laravel/framework ~5.1.0@dev -> satisfiable by laravel/framework[5.1.x-dev].
        - Installation request for illuminate/workbench dev-master -> satisfiable by illuminate/workbench[dev-master].
        - illuminate/workbench dev-master requires symfony/finder 2.6.* -> satisfiable by symfony/finder[2.6.x-dev, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9].
        - Can only install one of: symfony/finder[2.7.x-dev, 2.6.x-dev].
        - Can only install one of: symfony/finder[v2.6.0, 2.7.x-dev].
        - Can only install one of: symfony/finder[v2.6.0-BETA1, 2.7.x-dev].
        - Can only install one of: symfony/finder[v2.6.0-BETA2, 2.7.x-dev].
        - Can only install one of: symfony/finder[v2.6.1, 2.7.x-dev].
        - Can only install one of: symfony/finder[v2.6.2, 2.7.x-dev].
        - Can only install one of: symfony/finder[v2.6.3, 2.7.x-dev].
        - Can only install one of: symfony/finder[v2.6.4, 2.7.x-dev].
        - Can only install one of: symfony/finder[v2.6.5, 2.7.x-dev].
        - Can only install one of: symfony/finder[v2.6.6, 2.7.x-dev].
        - Can only install one of: symfony/finder[v2.6.7, 2.7.x-dev].
        - laravel/framework 5.1.x-dev requires symfony/finder 2.7.* -> satisfiable by symfony/finder[v2.7.0, 2.7.x-dev, v2.7.0-BETA1, v2.7.0-BETA2].
        - Conclusion: don't install symfony/finder v2.7.0-BETA1

Will it be possible to use illuminate/workbench in Laravel 5.1?

**Comment by rkgrep** [comment] 2015-06-07 12:27
Duplicate of https://github.com/illuminate/workbench/pull/9

Use https://github.com/franzliedke/studio instead.

**Comment by camilstaps** [comment] 2015-06-07 12:35
Thanks, sorry for the duplicate.

**Closed** 2015-06-07 12:34 UTC

**Comment by smithfoto** [comment] 2015-08-08 15:55
try my packages https://github.com/smithfoto/AdminZ
