### ISSUE TITLE
Can't initialize Blade-directive with custom variable

### ISSUE THREAD

**Issue by Husky110** [laravel/framework#18569] opened 2017-03-30 09:40 UTC
- Laravel Version: 5.4.16
- PHP Version: 7.1.2

### Description:
I'm trying to extend Blade like this:  
```
public function boot()
    {
        \Blade::directive('convertMinutesToTimeString', function($min){
            return '<?= App\Http\Controllers\MyController::convertMinutesIntoTimeString($min); ?>';
        });
        \Blade::directive('checkAdmin', function(){
            return '<?php $isAdmin = App\Http\Controllers\Auth\MyController::getUserIsAdmin() ?>';
        });
    }
```
Now whatever I do, I get 

> Undefined variable: min

Whereas the version without a custom variable works fine...
### Steps To Reproduce:
Add the line above like the docs suggest

**Comment by sakjawea** [comment] 2017-03-30 14:45
Hi there, its giving you undefined variable $min because you are sending $min to the view as part of the return, i assume you want something like this:

`return '<?= App\Http\Controllers\MyController::convertMinutesIntoTimeString('.$min.'); ?>';`

notice i concatenated the $min variable to the string you want to return.

Good Luck!

**Comment by Husky110** [comment] 2017-03-30 15:10
The docs suggest to do it like this:
```
Blade::directive('datetime', function ($expression) {
            return "<?php echo ($expression)->format('m/d/Y H:i'); ?>";
        });
```
see [https://laravel.com/docs/5.4/blade#extending-blade](https://laravel.com/docs/5.4/blade#extending-blade)  
What I want is that blade echoes the return-value of the convertMinutesIntoTimeString-Function which works fine for the getUserIsAdmin() is far, but not the convertMinutesIntoTimeString-Function.  
The docs read to me like "add php-code you write normaly but wrap it into a string".  
But is that assumption false?

**Comment by themsaid** [comment] 2017-03-30 15:16
@sakjawea's answer is the way to go.

Closing since it's not a bug in the core, we try to keep this repo for bug reporting only. Sorry :)

**Closed by themsaid** 2017-03-30 15:16 UTC

**Comment by mikemosz** [comment] 2017-08-24 05:05
Few months late, but I just had this problem - it's because you're using single quotes instead of double quotes. With double quotes, the '$expression' is replaced by its contents immediately in the string, the $expression variable does not exist outside the function.
