### ISSUE TITLE
Eloquent Builder's setEagerLoads() not adding constraint

### ISSUE THREAD

**Issue by sijones-uk** [laravel/framework#16463] opened 2016-11-18 11:53 UTC
- Laravel Version: 5.3.21
- PHP Version: 7.0.5
- Database Driver & Version: MySQL 5.7.12

### Description:
When using `setEagerLoads()` to set an eager load with a constraint via Eloquent Builder, the eager load is added, but the constraint is not.

### Steps To Reproduce:
I've got two models: Campaign and CampaignSession. The campaign_sessions table has a foreign key column (campaign_id) to the id column on the campaigns table.

**Models**
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Campaign extends Model
{
    public function campaignSessions()
    {
        return $this->hasMany('App\Models\CampaignSession');
    }
}
```

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CampaignSession extends Model
{
    public function campaign()
    {
        return $this->belongsTo('App\Models\Campaign');
    }
}
```

Example code from my controller method:

```
$myQueryBuilder = \DB::table('campaigns')->select('id', 'name');
$myEloquentBuilder = new \Illuminate\Database\Eloquent\Builder($myQueryBuilder);
$myEloquentBuilder->setModel(Campaign::find(1));
$myEloquentBuilder->setEagerLoads(['campaignSessions' => function ($query) {
	$query->limit(1);
}]);

dd($myEloquentBuilder->getEagerLoads());
```

When the controller method is called, the output from the `dd()` is:

![laravel_backpack_eager_load](https://cloud.githubusercontent.com/assets/13103339/20429119/8ae80982-ad84-11e6-9c8d-783ca88efe4f.gif)

In the above output, the `$query` in the `eagerLoad` parameters is empty, but I was expecting it to contain the `limit(1)` eager load constraint.

**Comment by themsaid** [comment] 2016-11-18 12:13
Duplicate of https://github.com/laravel/framework/issues/16217

**Comment by sijones-uk** [comment] 2016-11-18 12:14
I used `limit()` as an example, but I also couldn't get `where()` to work either. Is it expected to work?

**Closed by themsaid** 2016-11-18 12:13 UTC

**Comment by themsaid** [comment] 2016-11-18 13:12
yes but it needs parsing, better use `with` as it'll do the parsing under the hood.
