### ISSUE TITLE
[5.8.13] 'SQLSTATE[HY000] [2002] Connection refused' if docktrine/dbal installed

### ISSUE THREAD

**Issue by et-nik** [laravel/framework#28282] opened 2019-04-20 14:39 UTC
- Laravel Version: 5.8.13
- PHP Version: 7.2.15
- Database Driver & Version: none

### Description:

You can't run `composer update` and call `artisan` commands if add `Schema::defaultStringLength` calling to `AppServiceProvider` and you have `doctrine/dbal` package. 

On running `composer require doctrine/dbal`:
```
In PDOConnection.php line 31:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

In PDOConnection.php line 27:
                                             
  SQLSTATE[HY000] [2002] Connection refused 
```

On 5.8.12 works fine.

### Steps To Reproduce:

1. Create new project:
```
composer create-project --prefer-dist laravel/laravel blog
```

2. Fix `1071 Specified key was too long` error:
Using official documentation: https://laravel.com/docs/5.8/migrations#indexes

Add `Schema::defaultStringLength` calling to `AppServiceProvider`

```
use Illuminate\Support\Facades\Schema;

/**
 * Bootstrap any application services.
 *
 * @return void
 */
public function boot()
{
    Schema::defaultStringLength(191);
}
```

3. Try to install `doctrine/dbal` package:
```
composer require doctrine/dbal
```

You will get error:
```
In PDOConnection.php line 31:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

In PDOConnection.php line 27:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by staudenmeir** [comment] 2019-04-20 15:15
This is caused by #28214. /cc @JacksonIV 

We should only call `registerCustomDBALTypes()` when we are actually running migrations.

**Comment by JacksonIV** [comment] 2019-04-20 18:42
@staudenmeir I’ll look into this. 👍🏼

**Comment by JacksonIV** [comment] 2019-04-20 20:51
I have tried a few things but I can't seem to reproduce this on a new laravel installation. Could you please provide me with some more information as where you encounter this error? Are you sure your database credentials and settings are correct?

Also, please make sure you are running:

`composer require doctrine/dbal`

instead of:

`composer require docktrine/dbal`

**Comment by staudenmeir** [comment] 2019-04-20 20:57
The error only happens when a database connection is *not* available.

Something like `Schema::defaultStringLength(191);` doesn't access the database and should work without a connection.

**Comment by JacksonIV** [comment] 2019-04-20 21:18
@staudenmeir Everything seems to work fine here, even without a connection. Did you reproduce this?

**Comment by staudenmeir** [comment] 2019-04-20 21:29
Yes, I can reproduce it:

- Laravel 5.8.13
- `doctrine/dbal` installed
- `Schema::defaultStringLength(191);` in `AppServiceProvider::boot()`
- `DB_CONNECTION=mysql` in `.env`

I can trigger the error with `composer dump` or `php artisan serve`.

**Comment by staudenmeir** [comment] 2019-04-20 21:32
The constructor does get called. Take a look at `Illuminate\Support\Facades::getFacadeAccessor()`.

**Comment by driesvints** [comment] 2019-04-22 12:33
@staudenmeir I still have a hard time understanding how this can happen since the connection is first instantiated there?

**Comment by JacksonIV** [comment] 2019-04-22 14:02
@driesvints When the custom DBAL types get registered in the builder’s constructor it tries to find a Doctrine connection. If there’s no Doctrine connection, it will try to instantiate one. But if the database credentials or settings are incorrect it will throw a PDO exception. 

If the database settings and credentials are correct, there’s no problem though. This could indeed be fixed by moving the actual registration to the migrator. 

I will try to fix this as soon as i can, but unfortunately i’m a little short on time currently.

**Comment by JacksonIV** [comment] 2019-04-22 14:18
On the other hand, if you are calling the schema facade, you’d probably want a working database connection, right?

**Comment by staudenmeir** [comment] 2019-04-22 14:21
@driesvints The facade only instantiates an instance of the `Connection` class, but doesn't actually connect to the database. This happens in `getPdo()`.

Is that what you mean?

**Comment by staudenmeir** [comment] 2019-04-22 14:26
@JacksonIV Probably, but not necessarily immediately. Only instantiating an instance of a class like `MySqlBuilder` (or any other class) should never open an actual database connection.

**Comment by driesvints** [comment] 2019-04-22 14:44
@staudenmeir I see what you mean. It's imperative that we get this fixed soon though. Otherwise it's best that we revert for now.

**Comment by JacksonIV** [comment] 2019-04-22 15:27
@driesvints Instead of reverting everything, i could make a PR which removes the registration of the custom DBAL types in the constructor of the MySQL builder. This way people can still call the `registerCustomDBALType` method manually without any problems.

**Comment by staudenmeir** [comment] 2019-04-22 15:35
I would revert it. Then we can take the time to fix this properly and also cover the other databases (https://github.com/laravel/framework/pull/28214#issuecomment-483012555).

**Comment by JacksonIV** [comment] 2019-04-22 15:39
@staudenmeir You're right, i'll start working on a proper fix as soon as possible. I'll also try to cover the other databases simultaneously!

Sorry for the hassle!

**Comment by driesvints** [comment] 2019-04-22 19:43
I've removed the method call in the constructor for now and this will be released tomorrow. Please send in a better solution as soon as you're able to, thanks!

https://github.com/laravel/framework/pull/28301

**Closed by driesvints** 2019-04-22 19:43 UTC
Labels: bug

**Comment by jasperjorna** [comment] 2019-04-23 10:11
@driesvints this also breaks the `package:discover` command that runs after `composer install`.  I noticed this because our build process started failing as there is now `.env` and no database available yet at the `composer install` step in our build process.

After applying your revert from https://github.com/laravel/framework/pull/28301 it started working again.

Hopefully this can be tagged soon and properly addressed later. :)

**Comment by renepardon** [comment] 2020-04-14 13:19
I also receive this error if I call getDoctrineSchemaManager() within my console command constructor with laravel 6.2 and doctrine/dbal ^2.10

> Doctrine\DBAL\Driver\PDOException  : SQLSTATE[HY000] [2002] Connection refused

As soon as I move this call to the handle() method, it works as expected.

**Comment by shqear-mawdoo3** [comment] 2020-09-01 18:59
I receive this error when I call composer install! any solution for this??
