### ISSUE TITLE
Excluded routes are not respected in maintenance mode, in case of custom template

### ISSUE THREAD

**Issue by GeoSot** [laravel/framework#38038] opened 2021-07-16 13:32 UTC
- Laravel Version:  8.48.1
- PHP Version: 7.4
- Database Driver & Version: N/A

### Description:

While being in maintenance mode having a custom template, the excluded URIs are not served.

It works fine in case of template = null

### Steps To Reproduce:

* Go to  ->`App\Http\Middleware\PreventRequestsDuringMaintenance`
* Set some internal URIs to `$except`property
* Write on cli `artisan down --render={any template}` and visit the excluded URls
* You will still see the custom template

In opposite case, if you write on cli `artisan down` (without render option)  and visit the excluded URls, they will be served

Info: the issue seems to be on: https://github.com/laravel/framework/blob/83b70546fc43fa3278d5d101141033fd37edb4c6/src/Illuminate/Foundation/Console/stubs/maintenance-mode.stub#L12

**Comment by driesvints** [comment] 2021-07-16 13:56
Thanks for reporting. Managed to reproduce this one but the way I see it is that this is intended from how things work. The framework is never booted when a custom template is set so the exclude array cannot be reached. 

I do think it's possible to solve this by adding the exclude list to the `down` file so it can be checked in the `maintenance.php` file. 

Gonna wait for @taylorotwell's reply.

**Comment by driesvints** [comment] 2021-07-16 14:37
I sent in a PR here: https://github.com/laravel/framework/pull/38041

**Closed** 2021-07-18 15:57 UTC
Labels: needs more info
