### ISSUE TITLE
[Homestead] enhancement fork and possible PR

### ISSUE THREAD

**Issue by KernelFolla** [laravel/framework#15199] opened 2016-09-01 10:58 UTC
Hello,

i've just pushed my fork of laravel homestead [here](https://github.com/kernelfolla/homestead)

I rewrote it a lot with a complete list of changes in readme.md, unfortunately there isn't a complete backward compatibily but I think perhaps there is material that can be part of a PR but i'm an unsure person and I'd rather get a bit of opinions:)

thanks in advance
Marino
PS. Sorry if this isn't the right place to ask

**Comment by themsaid** [comment] 2016-09-05 18:14
I think it's better to create a PR if you feel part of the changes you made could be useful to the main repository.

I'll close this issue as it's not a bug report :)

**Closed by themsaid** 2016-09-05 18:14 UTC
