### ISSUE TITLE
Outsourcing validation rules to validationRules() method in FormRequest@createDefaultValidator() method breaks validation

### ISSUE THREAD

**Issue by lakkes-ra** [laravel/framework#50083] opened 2024-02-14 08:49 UTC
### Laravel Version

10.43 

### PHP Version

8.2.14

### Database Driver & Version

Docker MySQL image mysql:8.0 

### Description

References #49860 

This change breaks my custom FormRequest rules where I use the merge() function. 

```
class CategoryAvailabilityRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        $dateRange = explode(' - ', $this->date_range);
        $this->merge([
            'start_date' => $dateRange[0],
            'end_date' => $dateRange[1],
        ]);

        return [
            'start_date' => ['required'],
            'end_date' => ['required', 'after_or_equal:start_date'],
        ];
    }
}
```
With Update 10.43 it returns validation errors "start date must be filled" and "end date must be filled". When I revert the changes made in FormRequest@createDefaultValidator(ValidationFactory $factory) in #49860, it works again. 

It is kinda weird, since the problem only seems to be coming from outsourcing `$rules = method_exists($this, 'rules') ? $this->container->call([$this, 'rules']) : [];` into a method. It all works fine, if I do it inside the `createDefaultValidator()` method

### Steps To Reproduce

Create a custom FormRequest and use merge inside the rules() function like written above.

**Comment by driesvints** [comment] 2024-02-14 09:07
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by lakkes-ra** [comment] 2024-02-14 09:45
Hi @driesvints, thanks for the fast response!

I followed your instructions reproduced the issue in this repository: https://github.com/lakkes-ra/bug-report. 
This is the exact commit: https://github.com/lakkes-ra/bug-report/commit/1c8fe067aaa16ee6d15714bfd0d32416209a63bc

**Comment by rojtjo** [comment] 2024-02-14 10:17
This is happening because the PR changed switched the order in which the rules and data are retrieved.

While this is a breaking change, I don't think the merging of data is supposed to happen in the rules method. You should be using the `prepareForValidation` method on your form request for that.

See: https://laravel.com/docs/10.x/validation#preparing-input-for-validation

**Comment by driesvints** [comment] 2024-02-14 10:44
@rojtjo thanks for noting that! I do think this is a breaking change. I've sent in an easy fix for this here: https://github.com/laravel/framework/pull/50084

**Comment by lakkes-ra** [comment] 2024-02-14 10:57
@rojtjo that works, thanks for pointing out & thanks to @driesvints for fixing!

**Closed** 2024-02-14 15:13 UTC
Labels: bug
