### ISSUE TITLE
Model::save() does not work with Custom Auto Increment Primary key

### ISSUE THREAD

**Issue by sourov06** [laravel/framework#9999] opened 2015-08-20 14:10 UTC
I have added custom primary key 'UserId' in my model. First I query a row usign model.Then I change data in that model. I tried to save that model using Model::save() function but that save was not working.when I view the raw query I found that 

update `newusers` set `CustomerId` = ?, `Verified` = ? where `UserId` is null

But UserId was 7767 in that model object.

**Comment by GrahamCampbell** [comment] 2015-08-20 14:11
Need way more information.

**Comment by sourov06** [comment] 2015-08-20 14:20
First I fetch a model: Here is the screenshot of that model

http://www.screencast.com/t/urgonrrgPty

Then I tried save the model by following code:

        $anUser->Verified   = 1;
        $anUser->CustomerId = $request->input('customer_id');
        $anUser->save();

But data was not saving reason.I run query log function and found that following query is running:

http://www.screencast.com/t/OdDRrO1B

**Comment by GrahamCampbell** [comment] 2015-08-20 14:34
What Laravel version? What PHP version?

**Comment by sourov06** [comment] 2015-08-20 14:37
php vrsion 5.5.12
Laravel version 5.1.9 (LTS)

**Comment by sourov06** [comment] 2015-08-20 16:06
one more update to the error $anUser->UserId always returns null but it contains data always. :S :S

**Comment by lukasgeiter** [comment] 2015-08-20 18:05
I'm guessing you have `UserId` property in your model class. Remove that and it should work. If that's not the case, please post your model code.

**Comment by sourov06** [comment] 2015-08-21 01:19
UserId is my primary key. I don't have any other property named UserId.Here is my code of model.

class User extends Model
    {
        protected $table = 'newusers';
        protected $primaryKey = 'UserId';
        public $timestamps = false;
        
        public function CreateUser($request)
        {
            $all_parameters = $request->all();
            
            $salt = $this->CreateRandomSalt();
            $encryptedPassword = $this->createSaltedHash($all_parameters['password'], $salt);
            
            $this->FirstName         = $all_parameters['first_name'];
            $this->LastName          = $all_parameters['last_name'];
            $this->Email             = $all_parameters['Email'];
            $this->Username          = $all_parameters['Email'];
            $this->PasswordHash      = $encryptedPassword;
            $this->PasswordSalt      = $salt;
            $this->CompanyName       = $all_parameters['company_name'];
            $this->ASI               = $all_parameters['asi'];
            $this->UPIC              = $all_parameters['upic'];
            $this->PPAI              = $all_parameters['ppai'];
            $this->PPAC              = $all_parameters['ppac'];
            $this->SAGE              = $all_parameters['sage'];
            $this->CustomerId        = $all_parameters['customer_id'];
            $this->TaxID             = $all_parameters['tax_id'];
            $this->BillAddress1      = $all_parameters['bill_address'];
            $this->BillAddress2      = $all_parameters['bill_address2'];
            $this->BillCity          = $all_parameters['bill_city'];
            $this->BillState         = $all_parameters['bill_state'];
            $this->BillPostal        = $all_parameters['bill_postal'];
            $this->BillCountry       = $all_parameters['bill_country'];
            $this->SalesContactPhone = $all_parameters['contact_phone'];
            if($request->has('subscribe_specials_newproducts'))
                $this->SubscribeSpecialsNewproducts = '1';
            $this->SignupDate = date("Y-m-d H:i:s");
            $this->save();
        }
        
        
        
        
        public function CreateRandomSalt()
        {
            $saltBytes = mcrypt_create_iv(4, MCRYPT_DEV_URANDOM);
            return base64_encode($saltBytes);
        }
        
        public function createSaltedHash($password, $salt) 
        {
            return base64_encode(hash_hmac('sha512', base64_decode($salt) . $password, base64_decode($salt), true));
        }
        
        public function GenerateRandomPassword()
        {
            $newPassword = "";
            $alphanum = "abcdefghijklmnopqrstuvwxyz0123456789";
            for ($i=0; $i <= 10; $i++)
            {
                $num = rand() % 33;
                $tmp = substr($alphanum, $num, 1);
                $newPassword .= $tmp;
            }
            
            $salt = $this->CreateRandomSalt();
            $encryptedPassword = $this->createSaltedHash( $newPassword, $salt);
            $this->PasswordHash = $encryptedPassword;
            $this->PasswordSalt = $salt;
            $this->save(); //this save does not work
            
            
            $templateList = array( 
                                'text' => 'mail_message.user_password_reset_text', 
                                'html' => 'mail_message.user_password_reset_html'
                            );
            $parameterList = array(
                                    'first_name' => $this->FirstName,
                                    'username'   => $this->Username,
                                    'newpass'    => $newPassword
                                );
            $newUser = $this;
            Mail::send( $templateList , $parameterList , function($message) use ($newUser)
            {
               //not important
            });
        }
        
    }

**Comment by dmgawel** [comment] 2015-08-28 12:35
According to your model and provided screenshot: you have primary key set to UserId (note the "d"). On the other hand in your attributes list "7167" is a value of "UserID" (note the "D").

When saving, ORM looks for your custom primary key "UserId" in the atributes but founds nothing (null).

Standarize your key (changing primary key to "UserID" will do the job).

**Comment by GrahamCampbell** [comment] 2015-08-28 12:36
Feel free to continue this. Just closing to mark it as not a bug.

**Closed** 2015-08-28 12:36 UTC

**Comment by sfdk74** [comment] 2019-07-23 13:44
I have this problem too but my table "id" is correct and finally, I found that `DB::beginTransaction();` before `try` prevent inserting record to the database.
