### ISSUE TITLE
route problem with url encoded forward slashes

### ISSUE THREAD

**Issue by gharabaghi** [laravel/framework#22945] opened 2018-01-28 11:45 UTC
I wrote a route for test sending hashed values in url. and it doesnt work!
 My route:

`Route::get('/test/{value}','Controller@index2');`

My controller function:
`public function index2(Request $request , $value){
		dd(urldecode($value));}`
If i send for example '$' character which is encoded ('%24') index2 function shows it. but with '/' character ('%2f') it returns 404 page.

**Comment by X-Coder264** [comment] 2018-01-28 12:18
https://github.com/laravel/framework/issues/22125 😉

**Comment by themsaid** [comment] 2018-01-29 14:09
duplicate of https://github.com/laravel/framework/issues/22125

**Closed by themsaid** 2018-01-29 14:09 UTC
