### ISSUE TITLE
Except options not working on apiResource()

### ISSUE THREAD

**Issue by nmfzone** [laravel/framework#21479] opened 2017-10-01 05:36 UTC
- Laravel Version: 5.5.13 (and possibly previous version as well)
- PHP Version: 7.1.4
- Database Driver & Version: Mysql Ver 14.14 Distrib 5.7.16, for osx10.11 (x86_64)

### Description:
The `except` methods passed in options not getting excluded from route registrar.

### Steps To Reproduce:
Create something like this in `routes/api.php` : 

```
Route::apiResource('todo', 'TodoController', ['except' => ['index', 'show']]);
```
And voila!

**Comment by devcircus** [comment] 2017-10-01 07:36
apiResource already utilizes the 'only' option internally with [index, show, store, update, destroy]. If you need to customize it further, just use resource. The only thing apiResource provides is dropping 'edit' and 'create'. So just use 'resource' and customize as you need.

**Comment by nmfzone** [comment] 2017-10-01 10:05
@devcircus Yeah, I know. But, apiResource has `except` options, that it should work, but It doesn't. So It means that's an issue.

**Comment by devcircus** [comment] 2017-10-01 12:30
It's been discussed here before. That's not how it was intended to work. Submit a PR if you have a way to make it better.

**Comment by nmfzone** [comment] 2017-10-01 13:56
@devcircus Woah, interesting. I don't find the same discussion on this repo issue tracker with keyword `apiResource`, so I thought there is no discussion before. Ok, I'll submit a PR.

**Comment by devcircus** [comment] 2017-10-01 14:21
My apologies. It must've been on one of the forums where it was discussed. My point was that this was designed to simply be a shortcut for Route::resource except 'edit' and 'create'. It gives you nothing else. So if you don't need all api actions, you simply use Route::resource with all the exceptions you need. I guess if you can roll it altogether in a elegant PR, then go for it.

**Comment by nmfzone** [comment] 2017-10-01 15:02
@devcircus Ah, that's it. No problem, I'm just clarifying if I've checked the issue tracker and no one discussed it.

**Comment by themsaid** [comment] 2017-10-02 13:44
Closing since PR proposal was rejected for the moment.

**Closed** 2017-10-02 13:44 UTC

**Comment by pierrocknroll** [comment] 2018-02-22 13:56
Well, since "only" works with apiResource... there is a consistency problem.
If you want to be strict with ApiResource, don't make "only" work with it.
