### ISSUE TITLE
Explicit Model in Database Validations dont work 

### ISSUE THREAD

**Issue by hersan** [laravel/framework#30726] opened 2019-12-02 01:39 UTC
- Laravel Version: 6.6.0
- PHP Version: 7,2.19
- Database Driver & Version: 

### Description:
Documentation says I can do something like the following:
email' => 'unique:App\User,email_address'

But I do a simple test and it fails!

### Steps To Reproduce:
Test:
/** @test */
    public function it_check_unique_validation()
    {
        $user = factory(User::class)->create();

        $validator = Validator::make(['email' => $user->email],[
            'email' => 'unique:App\User',
        ]);

        $this->assertTrue($validator->fails());
        $this->assertEquals(
            'The email has already been taken.',
            $validator->errors()->first()
        );
    }
Result:
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lara6
.app\user' doesn't exist

**Comment by gocanto** [comment] 2019-12-02 02:34
> PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lara6
.app\user' doesn't exist

This seems to be related to a misconfiguration of the given model. Also, you would need to specify what column to query against.

**Comment by clugg** [comment] 2019-12-02 04:05
> This seems to be related to a misconfiguration of the given model.

Could you provide some more information about this? I have been having similar issues. I wrote a more comprehensive explanation in the [pull request](https://github.com/laravel/framework/pull/30653#issuecomment-559053200).

> Also, you would need to specify what column to query against.

This is incorrect - if you don't specify a column, the docs state that it will by default query the column with the same name as the input key (i.e. an input named 'email' will query the 'email' column if you don't specify a custom one).

**Comment by hersan** [comment] 2019-12-02 04:51
Hi, Take a closer look at the code and I think the problem is here:
https://github.com/laravel/framework/blob/6.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L816
I also found that there are only tests for the Rule class. This makes me think that this PR was intended only for the use of the Rule class. And that may indicate that the documentation has an error.

**Comment by ahinkle** [comment] 2019-12-07 16:57
Hey there, I would love to investigate this issue further. Do you have an example application you can share that will replicate this issue? - or even a unit test against the framework?

**Comment by clugg** [comment] 2019-12-08 05:50
@ahinkle 
I started a project from scratch to reproduce the issue. You can find it at [clugg/laravel-model-validation](https://github.com/clugg/laravel-model-validation). All of the validation code is in the [`routes/api.php`](https://github.com/clugg/laravel-model-validation/blob/master/routes/api.php) file. The welcome view contains a link to every route for you to see the output, the red links are those that aren't functioning as expected.

There are a fair few routes, as per [my comment on the PR](https://github.com/laravel/framework/pull/30653#issuecomment-559053200): option 1 is using validation rules as a single string delimited by a pipe | (notated by "delimited"), option 2 is using validation rules as strings in an array (notated by "array") and option 3 is using the exists/unique rules as instances of the class (notated by "instance"). For complete transparency I've also included examples where the column is explicitly defined as opposed to implied by the rule's name (notated by "explicit").

Options 1 and 2 both produce the same output:

`"SQLSTATE[HY000]: General error: 1 no such table: App\\Models\\User (SQL: select count(*) as aggregate from \"App\\Models\\User\" where \"id\" = 1)"`

Option 3 produces the expected output, given the database is in-memory and hasn't been migrated:

`"SQLSTATE[HY000]: General error: 1 no such table: users (SQL: select count(*) as aggregate from \"users\" where \"id\" = 1)"`

As you can see, option 3 correctly resolves the table name.

**Comment by driesvints** [comment] 2019-12-09 13:56
PR was merged.

**Closed by driesvints** 2019-12-09 13:56 UTC
Labels: bug

**Comment by hersan** [comment] 2019-12-10 21:16
@driesvints thanks
