### ISSUE TITLE
[Laravel 5.2] belongsToMany() ignored the joining table's soft deletes on Laravel 5.2

### ISSUE THREAD

**Issue by krpr** [laravel/framework#13376] opened 2016-04-29 14:19 UTC
SoftDeletes doesn't work well with belongsToMany() when the joining table using SoftDeletes.
`belongsToMany('App\Model', 'joining_table', 'foreign_key', 'other_key');`
It just work on the initiator model's table and the model which result collection used, but not work on the third joining table.

**Comment by krpr** [comment] 2016-04-29 14:34
```
select `users`.*, `role_user`.`user_id` as `pivot_user_id`, `role_user`.`role_id` as `pivot_role_id` from `users` inner join `role_user` on `users`.`id` = `role_user`.`role_id` where `role_user`.`user_id` = 1 and `users`.`deleted_at` is null
```

Well, in its sql, it doesn't verify table 'roles' and table 'role_user' 's `deleted_at`.

**Comment by themsaid** [comment] 2016-04-29 21:50
hmm I don't think there's nothing wrong with Eloquent, here's the generated query:

```
select `tags`.*, `product_tags`.`product_id` as `pivot_product_id`, `product_tags`.`tag_id` as `pivot_tag_id` from `tags` inner join `product_tags` on `tags`.`id` = `product_tags`.`tag_id` where `product_tags`.`product_id` = ? and `tags`.`deleted_at` is null
```

For:

```
Products\Product::first()->tags
```

**Comment by krpr** [comment] 2016-04-30 00:41
When table `product_tags` use SoftDeletes, Eloquent doesn't query table `product_tags`'s `deleted_at`, but only table `tags`'s `deleted_at`.

**Comment by dwightwatson** [comment] 2016-04-30 03:53
This is because `belongsToMany` simply uses the joining table as a joining table - it doesn't load up a model for it.

If you want your joining table to be it's own model (for which soft deletes would work) you should look at the `hasManyThrough` relation.

**Comment by krpr** [comment] 2016-04-30 04:55
@dwightwatson Thank you!
I've tried `hasManyThrough`, but it can't cater to the need of the relation among User, Role, User-Role.
Cause `hasManyThrough` is just an 'A->B->C' relation solution, it just runs a query for A via B's column which depend on C's column.

**Comment by GrahamCampbell** [comment] 2016-04-30 07:58
> hmm I don't think there's something wrong with Eloquent

Closing since there's not a bug here, just a question. Feel free to keep discussing though.

**Closed by GrahamCampbell** 2016-04-30 07:58 UTC
