### ISSUE TITLE
simplePaginate(1)

### ISSUE THREAD

**Issue by fox4obg** [laravel/framework#13117] opened 2016-04-11 19:14 UTC
Hi all,
when i tested my app with 
simplePaginate(1)
it return on page 1 and 2 same result
with paginate(1)
all work correct

**Comment by GrahamCampbell** [comment] 2016-04-11 19:17
How can we reproduce this? What Laravel version?

**Comment by fox4obg** [comment] 2016-04-13 19:47
controller code
...
$in_range=$location->inRange()->simplePaginate(1);
...
view code
{!! $in_range->render() !!}

that return on page 1 and 2 same result.
with:
$in_range=$location->inRange()->paginate(1);
return correct result

10x

**Comment by GrahamCampbell** [comment] 2016-04-13 19:49
> What Laravel version?

**Comment by fox4obg** [comment] 2016-04-13 20:04
const VERSION = '5.2.23';

**Comment by GrahamCampbell** [comment] 2016-04-13 20:36
Please update to the latest.

**Comment by fox4obg** [comment] 2016-04-16 18:17
after update to:
const VERSION = '5.2.29';
same result

**Comment by Jimbolino** [comment] 2016-08-30 13:43
`$this->query->skip(($page - 1) * $perPage)->take($perPage + 1);`

So if you use:
`simplePaginate(10)`
It will "take" 11 results ?

**Comment by strainovic** [comment] 2016-09-21 20:12
I have the same problem.

paginate() method works fine.

**Comment by themsaid** [comment] 2016-09-22 10:41
I can't replicate this in 5.3, @strainovic how do you replicate?

```
\App\Foodics\Users\User::simplePaginate(1)->first()->id
```

Returns a different id in every page.

**Comment by themsaid** [comment] 2016-09-22 11:01
@Jimbolino you say the problem is in `$in_range->render()`, what do you mean by that?

**Comment by strainovic** [comment] 2016-09-22 12:10
@themsaid

I'm using 5.2 and I didn't try 5.3

**Comment by themsaid** [comment] 2016-09-22 13:00
@strainovic can you please share steps to reproduce?

**Comment by strainovic** [comment] 2016-09-25 18:30
@themsaid Yes, you are right but try to log those two queries, one from paginate(1) and another from simplePaginate(1).

For the paginate(1), in my case, I'm getting this:

select * from `cards` where `cards`.`deleted_at` is null limit 1 offset 0

and for simplePaginate(1) I'm getting this:

select * from `cards` where `cards`.`deleted_at` is null limit 2 offset 0

You see that limit 1 become limit 2. Laravel somehow handle this by himself and I'm getting only one object in both cases, but for other query you'll actually get two results from database.

**Comment by themsaid** [comment] 2016-09-25 19:21
Well the second object helps us to decide if we should display a next button or not.

**Comment by strainovic** [comment] 2016-09-25 19:29
Hm, I didn't count on it. Is it posible to fetch second object without relations? If I have few relations, it will grab a lot of unessesery data?

**Comment by themsaid** [comment] 2016-09-26 21:02
@strainovic that would require calling a second query, which is technically, IMHO, more expensive than bringing an extra object.

Closing then since it's not actually a bug in the framework :)

**Closed by themsaid** 2016-09-26 21:02 UTC

**Comment by Jimbolino** [comment] 2016-09-26 23:05
I think my problem was with the sequence of the fluent functions:
```
Route::get('/auto/brands', function(){
    $query = \App\Models\Auto\Brands::whereNotNull('name');
    $query->simplePaginate(1);

    return $query->get(); // responds to the ?page=2 parameter as expected, but returns 2 brands
});
```
The simplePaginate() returns a Paginator, and not a Query/Builder object. So i was actually discarding the new Paginator instance, and continued to use the query. Which will get you unexpected results.

So make sure that simplePaginate() is the last function in the chain (and not somewhere in between):
```
Route::get('/auto/brands', function(){
    return \App\Models\Auto\Brands::whereNotNull('name')->simplePaginate(1);
});
```
