### ISSUE TITLE
Schedule event broke after callbacks functionality

### ISSUE THREAD

**Issue by webmake** [laravel/framework#19567] opened 2017-06-12 12:33 UTC
- Laravel Version: 5.4

### Description:

Seems since [commit](https://github.com/laravel/framework/commit/f09a72289dd097ee8b89fdfcd3f6c0542fc3c1a9) broken `afterCallbacks` functionality, because it runs successfully `then` commands.

Why re-throw exceptions was removed?

### Steps To Reproduce:
```
$schedule->command(CustomCommand::class)
            ->everyMinute()
            ->then(function() {
                $this->call('other:command');
            });
```
For me it looks natural to not call then if first command failed, if we would take a look at javascript promises.

**Comment by themsaid** [comment] 2017-06-12 14:06
`afterCallbacks` works fine, can you please share more details, I don't seem to understand your issue.

**Comment by webmake** [comment] 2017-06-12 18:03
simplified POC on fresh laravel project:

\app\Console\Commands\HelloCommand.php
```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class HelloCommand extends Command
{
    protected $signature = 'say:hello';
    protected $description = 'Say hello';

    public function handle()
    {
        logger('hello');
        throw new \Exception();// read comment below
        logger('my');
    }
}
```

\app\Console\Commands\WorldCommand.php
```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class WorldCommand extends Command
{
    protected $signature = 'say:world';
    protected $description = 'Say World';

    public function handle()
    {
        logger('world');
    }
}
```

\app\Console\Kernel.php
```
<?php

namespace App\Console;

use App\Console\Commands\HelloCommand;
use App\Console\Commands\WorldCommand;
use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;

class Kernel extends ConsoleKernel
{
    protected $commands = [
        HelloCommand::class,
        WorldCommand::class,
    ];

    protected function schedule(Schedule $schedule)
    {
        $schedule->command(HelloCommand::class)
            ->everyMinute()
            ->then(function() {
                $this->call('say:world');
            });
    }
}
```
Such example output:
```
[2017-06-12 18:01:29] local.DEBUG: hello  
[2017-06-12 18:01:29] local.ERROR: Exception in /commands/app/Console/Commands/HelloCommand.php:15
Stack trace:
#0 [internal function]: App\Console\Commands\HelloCommand->handle()
.......
#13 {main}  
[2017-06-12 18:01:29] local.DEBUG: world  
```

as you can see output is hello (exception) world
That means, no matter that command `Hello` has exception, **then** command is **executed**

**Comment by webmake** [comment] 2017-06-12 18:12
As I mentioned, [64 line](https://github.com/laravel/framework/commit/f09a722#diff-dc33b115806d4b2fa1499d3fc46bbd4fL64) allows execute any command callback, which is bad, let's say, importing some data, and when second depends on first, real example, import is made on tmp table, then second command switch with real table, and if first command fail, it can switch to empty table

**Comment by themsaid** [comment] 2017-06-12 18:19
It's a commit from 2 years ago, can't consider this breaking at all :)

The callbacks will run whether or not the command succeeded or not, that's by design, the task scheduler only schedules tasks and shouldn't be used to chain them like this, you need to implement a check in the second command to make sure it only runs when it should run.

**Comment by webmake** [comment] 2017-06-12 18:30
So how to chain it?
I understand, that ugly solution is in HelloCommand call directly WorldCommand, but there is multiple examples that, there is no possibility to inject module1 in module2, (this was only very minimalistic application POC).
Another example, log cron start, finish, but if command would fail, there is no option to log it, because I have 3rd party cron, so after callbacks is also executed and there is no option to extract successfull or not command was. Any suggestions?

**Comment by webmake** [comment] 2017-06-12 18:33
Maybe there should be added new function callback to reach that? Because now, `after`/`then` is doing the same. BTW, javascript example has 2parameters, on success and on failure.
```
    .then(function (greeting) {
        console.log(greeting);
    }, function(error) {
        console.error('uh oh: ', error);
    });
```
[at](https://spring.io/understanding/javascript-promises)

**Comment by themsaid** [comment] 2017-06-12 18:57
This is not the same as JS promises, the task scheduler simply runs a command at a given time and that's it, the use case you're trying to approach should be handled in your application code.

Going to close this issue since it's not a bug in the framework, but feel free to ping me if u need more help.

**Closed by themsaid** 2017-06-12 18:57 UTC
Labels: Unable to Replicate
