### ISSUE TITLE
Unvalidated data passing from validation

### ISSUE THREAD

**Issue by taliptako** [laravel/framework#23641] opened 2018-03-21 10:28 UTC
- Laravel Version: 5.6.12
- PHP Version: 7.2.3

### Steps To Reproduce:
Create validation with this rule
`'number.*' => 'required|integer',`
and post string value without array like this `<input name="number" value="string" >`
after try to get all validated data from request you will have number field passing as a validated value but it should not pass or there should be a error because it is not integer.

**Comment by staudenmeir** [comment] 2018-03-21 13:46
Please add a code example with actual data so that we can reproduce it.

**Comment by jonpemby** [comment] 2018-03-21 14:10
I reproduced with the following, testing for an expected `422` status:

### Request

```php
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreNumber extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'number.*' => 'required|integer',
        ];
    }
}
```

### Controller

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreNumber;

class TestController extends Controller
{
    public function create(StoreNumber $request)
    {
        return response()->json(['success' => true]);
    }
}
```

### Test

```php
<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class StoreNumberTest extends TestCase
{
    /**
     * Testing number validation.
     *
     * @return void
     */
    public function testStoreNumberValidation()
    {
        $response = $this->json('POST', '/numbers', ['number' => '']);

        $response->assertStatus(422);
    }
}
```

And got this output on terminal:

<img width="910" alt="screenshot 2018-03-21 09 09 44" src="https://user-images.githubusercontent.com/8012318/37714479-9e1fff76-2ce7-11e8-8324-161f8290a9e2.png">

**Comment by taliptako** [comment] 2018-03-21 14:48
@jonpemby In the controller get validated data with $request->validated(); and you will see number field is there as a validated data

**Comment by jonpemby** [comment] 2018-03-21 16:27
@taliptako I'm testing for response failure (which is what we want it to do) but we're getting response success (as you've described).

If I `var_dump` the `request->validated()` in a manual browser test, I get the following:

![screenshot 2018-03-21 11 26 18](https://user-images.githubusercontent.com/8012318/37722740-c62db0ea-2cfa-11e8-8aba-7a1c38d59aca.png)

Is this what you're experiencing?

**Comment by taliptako** [comment] 2018-03-22 15:13
@jonpemby Question is why number field show up as a validated data  ?

**Comment by staudenmeir** [comment] 2018-03-22 23:31
@anishdcruz: This issue was discussed in #23612.

**Comment by anishdcruz** [comment] 2018-03-24 09:15
@staudenmeir i can see that issue was close. Is there any workaround for this issue.

**Comment by staudenmeir** [comment] 2018-03-27 16:01
It will be fixed in 5.7: #23708

If you don't have any array rules (`foo.*.bar`), you can use this workaround:

    $data = $request->only(array_keys($rules));

**Comment by jonpemby** [comment] 2018-03-29 23:21
Okay, so after investigating what's going on, it looks like there's some (perhaps) unintentional filtering happening in this method:

### Illuminate\Validation\ValidationRuleParser.php
```php
/**
     * Define a set of rules that apply to each element in an array attribute.
     *
     * @param  array  $results
     * @param  string  $attribute
     * @param  string|array  $rules
     * @return array
     */
    protected function explodeWildcardRules($results, $attribute, $rules)
    {
        $pattern = str_replace('\*', '[^\.]*', preg_quote($attribute));

        $data = ValidationData::initializeAndGatherData($attribute, $this->data);

        foreach ($data as $key => $value) {
            if (Str::startsWith($key, $attribute) || (bool) preg_match('/^'.$pattern.'\z/', $key)) {
                foreach ((array) $rules as $rule) {
                    $this->implicitAttributes[$attribute][] = $key;

                    $results = $this->mergeRules($results, $key, $rule);
                }
            }
        }

        return $results;
    }
```

The rules are built for the array of data its expecting and then the wildcards are unset here:

```php
/**
     * Explode the rules into an array of explicit rules.
     *
     * @param  array  $rules
     * @return array
     */
    protected function explodeRules($rules)
    {
        foreach ($rules as $key => $rule) {
            if (Str::contains($key, '*')) {
                $rules = $this->explodeWildcardRules($rules, $key, [$rule]);

                unset($rules[$key]);
            } else {
                $rules[$key] = $this->explodeExplicitRule($rule);
            }
        }

        return $rules;
    }
```

The `number` key is being unset from the `$rules` and is, therefore, allowing the validator to pass. At least, that's what I'm seeing after just walking through each step of the process with the help of a hacked together test:

```php
public function testArrayRequiredValidation()
    {
        $post = ['number' => ''];

        $v = new Validator($this->getIlluminateArrayTranslator(), $post, [
            'number.*' => 'required|integer',
        ]);

        $this->assertFalse($v->passes());
    }
```

@staudenmeir am I on the right track, here? You seem to be more familiar with the validator stuff.

**Comment by staudenmeir** [comment] 2018-03-30 22:49
Adding an extra rule fixes it for me:

    'number' => 'required', 'number.*' => 'required|integer'

@taliptako Does this solve your problem?

**Comment by jonpemby** [comment] 2018-04-02 15:51
@staudenmeir I think that's an awesome and simple solution as a workaround, but if we're expecting an array of data shouldn't it at least flag a validation error for the request because we didn't get one?

I'm just trying to make sense of what's going on. 🤔

**Comment by staudenmeir** [comment] 2018-04-02 17:31
I think the idea is that for validating arrays you have to add a rule for every "level". I assume it would be difficult change (if you would want to).

(@jonpemby I updated my previous post.)

**Comment by jonpemby** [comment] 2018-04-02 18:20
Ahhh I see now :smile: that seems to be the best way to do it

Thanks for the insight, there!

**Comment by themsaid** [comment] 2018-04-04 08:46
This is the expected behaviour, if you add wildcard rules you'll get the parent key as validated always.

**Closed by themsaid** 2018-04-04 08:46 UTC

**Comment by taliptako** [comment] 2018-04-09 16:44
@themsaid Can you explain me why this is a expected behaviour ? 
I'm trying to get only validated data and they are array like title[en] = "English Title" - title[sp] = "Spanish Title"
If someone send a data only without array like this name = "I dont care about your rules i'm in your database hahaha"
it will be inserted to the db.
I'm using spatie/translatable which is same with your this package [](https://github.com/themsaid/laravel-multilingual)
When you post a data without array it will be automatically inserted to db with default language of your app..

**Comment by taliptako** [comment] 2020-10-16 12:11
@themsaid You said this is expected but when I test this in laravel 8 it is no more same
