### ISSUE TITLE
[5.3] Polymorphic Relation using whereHas  return column not found

### ISSUE THREAD

**Issue by ssuhat** [laravel/framework#15514] opened 2016-09-20 08:32 UTC
- Laravel Version: 5.3.9
- PHP Version: 7
- Database Driver & Version: MariaDB 10

My current model structure:

       Image.php

	public function imageable()
	    {
	        return $this->morphTo();
	    }

	User.php

	public function images()
	    {
	        return $this->morphMany(Image::class, 'imageable');
	    }

### Steps To Reproduce:

I query it like this:
        
        $gender = 1;
	$lookIds = Image::whereHas('imageable' , function($query) use($gender){
                $query->where('gender', $gender);
            })->get();

It return me: 

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'gender' in 'where clause`

Any suggestion or better solution to get all Image within user with gender 0?

**Comment by themsaid** [comment] 2016-09-20 13:38
@ssuhat can you please share the full query?

**Comment by themsaid** [comment] 2016-09-20 13:40
Looks like a duplicate of https://github.com/laravel/framework/issues/5429, it seems that there's no fix for this issue, the way the queries are built under the hood doesn't make it easy to adapt for the morphing relation.

**Closed by themsaid** 2016-09-20 13:40 UTC
