### ISSUE TITLE
Default value for Cache::increment() varies accross drivers 

### ISSUE THREAD

**Issue by halaei** [laravel/framework#20643] opened 2017-08-20 12:25 UTC
The following code have different result depending on the cache driver.
```php
Cache::increment('x');
echo Cache::get('x');
```
Output:

1. Redis: 1
2. Dababase: null
3. Memcached: null
4. APCu: 1
5. File: 1

I guess the best is for all to have the same results.

**Comment by themsaid** [comment] 2017-08-21 08:55
fell free to open a PR :)

Closing since it's not a bug.

**Closed by themsaid** 2017-08-21 08:55 UTC

**Comment by halaei** [comment] 2017-08-21 09:11
It violates Liskov substitution principle.

**Comment by patrickcarlohickman** [comment] 2018-03-13 15:07
@themsaid I just noticed this while looking at something else in the cache. I was going to work on a PR, but then realized I didn't know which way the framework would want to go with it.

It would be great to normalize the behavior so that all cache drivers act the same. So, what would the expected behavior be? Should the value be added to the cache, or should the increment request be ignored and return `null`?

The majority of the drivers (including the array driver) add the value to the cache, so that would be my assumption, but I think it would be good to nail down what the framework owners actually want. :)
