### ISSUE TITLE
Route:cache breaks closure-based routes that use route model binding

### ISSUE THREAD

**Issue by misenhower** [laravel/framework#35339] opened 2020-11-24 00:49 UTC
- Laravel Version: 8.15.0
- PHP Version: 7.4.12
- Database Driver & Version: N/A (SQLite, MySQL, etc.)

### Description:
If you use `artisan route:cache` with a route that a) is defined as a closure and b) uses route model binding, the model isn't fully hydrated when the route is accessed. It seems like in some cases only a few of the attributes will be made available, and in other cases, none of them will be available (I think this difference might be related to `$casts`, but the main issue still stands).

### Steps To Reproduce:
1. Create a new Laravel application.
2. Run DB migrations and create a sample User record to test with.
3. Add some routes to `routes/web.php`:
```php
<?php

use App\Models\User;
use Illuminate\Support\Facades\Route;

// Route model binding
Route::get('test1/{user}', function (User $user) {
    return $user;
});

// Normal attributes
Route::get('test2/{user}', function ($user) {
    return User::findOrFail($user);
});
```
4. Serve the application and access `/test1/1` and `/test2/1` -- both should return the user attributes as JSON, e.g.,
```json
{
  "id": 1,
  "name": "test",
  "email": "test@example.com",
  "email_verified_at": null,
  "created_at": "2020-11-24T00:27:44.000000Z",
  "updated_at": "2020-11-24T00:27:44.000000Z"
}
```
4. Run `php artisan route:cache`
5. Serve the application and access `/test1/1` -- this now returns a blank response like `[]`. The other route that didn't use route model binding (`/test2/1`) should still work as expected.

**Comment by taylorotwell** [comment] 2020-11-24 14:18
I can confirm this. Oddly the user is injected into the route because if I `dd` it then I can see the full user instance.

**Comment by taylorotwell** [comment] 2020-11-24 14:48
Fixed in next patch release.

**Closed by taylorotwell** 2020-11-24 14:48 UTC

**Comment by misenhower** [comment] 2020-11-24 16:50
Thanks Taylor! Definitely a strange one 😃
