### ISSUE TITLE
propose when deleting a file with Filesystem class

### ISSUE THREAD

**Issue by atefBB** [laravel/framework#21105] opened 2017-09-09 14:10 UTC
https://github.com/laravel/framework/blob/7bfe4a10387d726569856bb4ceaec576e60ae7bb/src/Illuminate/Filesystem/Filesystem.php#L114 
if there's an error while deleting a file in such path why not to simply `return false` and not to complete `looping` ?

**Comment by Dylan-DPC** [comment] 2017-09-09 14:49
This is not a bug. You can open a proposal in the laravel/internals repo

**Comment by atefBB** [comment] 2017-09-09 14:52
just a view point for discussion.

**Comment by Dylan-DPC** [comment] 2017-09-09 14:58
Open the issue here instead: https://github.com/laravel/internals/issues

**Comment by atefBB** [comment] 2017-09-09 15:53
thx !

**Comment by Dylan-DPC** [comment] 2017-09-09 20:33
@atefBB you can close this issue

**Closed** 2017-09-10 08:32 UTC
