### ISSUE TITLE
Blade sections override issue

### ISSUE THREAD

**Issue by mpociot** [laravel/framework#18788] opened 2017-04-12 09:16 UTC
- Laravel Version: 5.4.18
- PHP Version: 7.1.3
- Database Driver & Version: None

### Description:
Blade seems to be unable to override sections that were already defined in the extended layout. It seems like Blade is first including / executing the extended layout before overriding the sections.

### Steps To Reproduce:
You need 3 views:

#### index.blade.php

```html
@extends('layout')
@section('remove-me', '')
```

#### layout.blade.php

```html
@section('remove-me')
	@include('include')
@show
```

#### include.blade.php

```html
{{ $iDoNotExist }}
```

### Expected behavior
Empty HTML page

### Actual behavior
> Undefined variable: iDoNotExist

**Comment by deleugpn** [comment] 2017-04-12 10:06
Give `include.blade.php` the variable it needs

**Comment by mpociot** [comment] 2017-04-12 10:07
Well, the point is - in the example it should not get included at all, because I overwrite the section in the beginning.

**Comment by deleugpn** [comment] 2017-04-12 10:18
Now I got it.

**Comment by themsaid** [comment] 2017-04-12 16:02
Yes blade compiles all section content in order to be able to replace `@parent` with the parent section content, so yes the all section code is actually included using PHP's `include`, section content are collected in a stack, and then on render Blade manages the output based on the different sections you have.

**Comment by themsaid** [comment] 2017-05-05 06:37
Closing since it's not actually a bug, this behaviour is by design, sections are compiled in order to be able to use the `@parent` directive.

**Closed by themsaid** 2017-05-05 06:37 UTC
Labels: Under Discussion
