### ISSUE TITLE
[BUG] Pagination not working if query contain HAVING statement

### ISSUE THREAD

**Issue by rolandas-valantinas** [laravel/framework#18468] opened 2017-03-23 22:17 UTC
- Laravel Version: `5.4.9`
- PHP Version: `7.0.15`
- Database Driver & Version: `mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64)`

### Description:
return of bug from https://github.com/laravel/framework/issues/3105

### Steps To Reproduce:
Code
```php
$users = User::selectRaw(
                'users.*, ROUND(? * DEGREES(ACOS(COS(RADIANS(?))
                * COS(RADIANS(postcodes.latitude))
                * COS(RADIANS(? - postcodes.longitude))
                + SIN(RADIANS(?))
                * SIN(RADIANS(postcodes.latitude))))) as distance',
                [$typeOfDistance, $latitude, $longitude, $latitude]
            )
            ->join('postcodes', 'postcodes.id', '=', 'users.postcode_id')
            ->havingRaw("distance < ?", [$radius])
            ->orderBy('distance')->paginate(30);
```
Produces error
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'distance' in 'having clause' (SQL: select count(*) as aggregate from `users` inner join `postcodes` on `postcodes`.`id` = `users`.`postcode_id` having distance < 100)
```
Works fine if `->paginate(30)` is changed to `->get()`. Basically `paginate` started dropping `select` if query builder contains `having` again!

**Comment by themsaid** [comment] 2017-03-24 07:32
Duplicate of https://github.com/laravel/framework/issues/16320

**Closed by themsaid** 2017-03-24 07:32 UTC
