### ISSUE TITLE
Migration fails in test after upgrading to 9.52

### ISSUE THREAD

**Issue by rooselle** [laravel/framework#46205] opened 2023-02-21 15:20 UTC
- Laravel Version: 9.52.0
- PHP Version: 8.1
- Database Driver & Version: sqlite

### Description:
After updating Laravel to 9.52, I get following error when running the tests that use RefreshDatabase trait:
`SQLSTATE[HY000]: General error: 1 table "telescope_entries" already exists`

The migration which creates "telescope_entries" is the fifth to be run, before that there's the "users" table which is recreated without problem.

The first test that uses RefreshDatabase works, it's the second (and all the following) that fail.

Could this be linked to this PR which appears in the Changelog? https://github.com/laravel/framework/pull/46073

### Steps To Reproduce:

I guess that you could reproduce like that (but I didn't try yet):
- Create a new Laravel project that has users and telescope (https://laravel.com/docs/9.x/telescope)
- Add a test class that uses RefreshDatabase trait
- Run tests

**Comment by nunomaduro** [comment] 2023-02-22 11:13
Can't reproduce this issue, on Laravel 9 or Laravel 10, and using Telescope 4.14. Can please really double check if you are using Telescope 4.14?

**Comment by nunomaduro** [comment] 2023-02-22 14:44
Fixed on Laravel v10.1.3.

**Closed by nunomaduro** 2023-02-22 14:44 UTC

**Comment by potsky** [comment] 2023-02-22 20:05
Thank you @nunomaduro, it works on `9.52.4` 👍
