### ISSUE TITLE
[L5.1] Migrations - Cannot change an existing column to type char

### ISSUE THREAD

**Issue by hskrasek** [laravel/framework#9636] opened 2015-07-15 17:48 UTC
Trying to write a migration to change a column from VARCHAR to CHAR, but when I run the migration it throws the following error:

```
[Doctrine\DBAL\DBALException]
  Unknown column type "char" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this err
  or occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes
  (). If the type name is empty you might have a problem with the cache or forgot some mapping information.
```

Here is what my `up` function looks like
```php
 public function up()
    {
//        dd(\Doctrine\DBAL\Types\Type::getTypesMap());
        Schema::table('perk_word_search_boards', function (Blueprint $table) {
            $table->char('uuid', 36)->change();
        });
    }
```

Interestingly though if I add a new column of type char, the migration runs just fine.

**Comment by nicolasbeauvais** [comment] 2015-07-21 15:16
I have the same problem when I whant to set the nullable property to an existing char field:

```php
Schema::table('table', function (Blueprint $table) {
    $table->char('language')->nullable()->change();
});
```

**Comment by mikebronner** [comment] 2015-07-23 18:27
This is possibly related, so I'll post it here (please let me know if not, and I'll create a new issue):

When trying to change a CHAR(36) column to a VARCHAR(50) column it changes the length but not the type. This column is also indexed, so it may be related to the above comment.

```php
        Schema::table('table_name', function ($table) {
            $table->string('field_name', 50)->nullable()->change();
        });
```

I noticed that running a SQL statement also did not work, so it is probably a database limitation.

```php
        DB::statement("
            ALTER TABLE `table_name`
            CHANGE `field_name` `field_name` VARCHAR(50) NOT NULL DEFAULT '0'
        ");
```

However, using the change() method still does not work with the indexes removed. Running the sql statement with the indexes removed did indeed change the field type to VARCHAR.

**Comment by lriggle-strib** [comment] 2015-07-30 14:18
I am also experiencing the issue describe in https://github.com/laravel/framework/issues/9636#issuecomment-123366513. Trying to set nullable on an already existing char field produces the following error

>[Doctrine\DBAL\DBALException]                                                                                                                                                                          
>  Unknown column type "char" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.

**Comment by phroggyy** [comment] 2015-08-06 21:07
I'm quite certain Doctrine does not support the char type and that this would be the issue. Any confirmation from @taylorotwell would be great though.

**Comment by 7talents** [comment] 2015-08-07 09:37
For me, changing "text" columns to "mediumText" or "longText" like this 
$table->mediumText('field_name')->change() 
does not have an effect in migrations. Changing them to other types (like for example "string") works.

Should I make a new issue out of this or is it OK here?

**Comment by phroggyy** [comment] 2015-08-07 09:48
@7talents again, this is no bug with Laravel but rather how Doctrine (of the Symfony framework) works. If you check the docs at http://doctrine-dbal.readthedocs.org/en/latest/reference/types.html#mapping-matrix, it's pretty clear that in doctrine, no difference is made between a `mediumText` or `text`. Rather, Doctrine relies on the size you set on the field. If you set the size <= 65535, `TEXT` will be used. If `size <= 16777215`, `MEDIUMTEXT` is used, and lastly, if the column length `<= 4294967295` or empty, the field will be `LONGTEXT`.

**Comment by 7talents** [comment] 2015-08-07 09:55
@phroggyy Thank you very much for the explanation. Although, creating the the table with migration, I just used "text" and there is nothing in the Laravel docs that says anything about text length (like for "string" or for "char"). And does make a "text" column, while just "mediumText" makes a "mediumText" column. The problem ist, using "->change()" does not have an effect, if you want to switch between "text" and "mediumText". So maybe there is something that should/could be optimized here...

**Comment by phroggyy** [comment] 2015-08-07 09:59
@7talents. That's because standard laravel migrations don't use Doctrine. However, to use the `change` command, you must have, at some point, included Doctrine DBAL. There is nothing in the docs about this because it's not part of the Laravel migrations. However, Laravel migrations do not support `change`. Or perhaps it was changed in 5.1, but nonetheless, it's `Doctrine DBAL` being used for all `change` operations, hence the lack of documentation from Laravel's side.

**Comment by bobbybouwmann** [comment] 2015-08-07 14:02
@phroggyy The function `change()` is included: http://laravel.com/docs/5.1/migrations#modifying-columns

However the documentation also says you need to have the package `doctrine/dbal` installed.

**Comment by phroggyy** [comment] 2015-08-07 14:05
@bobbybouwmann yep, I'm very well aware that the method itself is part of Laravel. However, all limitations as far as migration capability goes are part of Doctrine DBAL :)

**Comment by bobbybouwmann** [comment] 2015-08-07 14:06
@phroggyy You said there is nothing about it in the docs, now there is ;)

**Comment by 7talents** [comment] 2015-08-07 14:07
I think I will propose a change of in the docs mentioning the limitations, when I find the time...

**Comment by phroggyy** [comment] 2015-08-07 14:09
@bobbybouwmann: what I intended to get across was that there is no docs, on Laravel, about the inability of switching between TEXT and LONGTEXT because of how Doctrine works. Sorry if that didn't come across clearly

**Comment by bobbybouwmann** [comment] 2015-08-07 14:09
@phroggyy Fair enough! Then the documentation needs some updating ;)

**Comment by GrahamCampbell** [comment] 2015-08-07 14:10
We're open to PRs to the documentation.

**Comment by GrahamCampbell** [comment] 2015-08-07 14:10
Closing this as it's not an issue with laravel/framework.

**Closed** 2015-08-07 14:10 UTC
Labels: bug, database

**Comment by salarmehr** [comment] 2015-10-11 03:02
@hskrasek What did you do for the mentioned error?

**Comment by hskrasek** [comment] 2015-10-13 17:29
@salarmehr I don't have the query handy, but in the migration I just did a raw DB::statement()

**Comment by salarmehr** [comment] 2016-06-08 05:18
@phroggyy any reference from doctorine for that?

**Comment by phroggyy** [comment] 2016-06-08 10:28
@salarmehr: for what exactly? This is a fairly old issue so I can't say I have everything readily available

**Comment by andfelzapata** [comment] 2016-08-02 08:00
I was having this exact problem trying to change $table->string('...')  to $table->longText('..'), it didn't work in Laravel 5.0. 

But trying out: 

`$table->string('column', 4294967295)->change();`

updated the field to LONGTEXT(4294967295).

**Comment by dalenguyen** [comment] 2016-08-10 15:57
Hi, I updated from 
`$table->float('amount');`
to
`$table->decimal('amount', 10, 2)->change();`

When I run **php artisan migrate**, it says **nothing to migrate**. Is there anything that I should do to make it right? Thanks,

**Comment by andfelzapata** [comment] 2016-08-10 16:55
@dalenguyen You you have to do migrate:rollback, that is if you have the down method defined in the corresponding migration. If you don't have that method setup, with care delete de corresponding row for the migration in your migrations table.

**Comment by dalenguyen** [comment] 2016-08-10 17:43
Thank @andfelzapata . I am editing an existing file. I managed to change the column type with out rollback. You can read it here: http://techcater.com/update-column-types-laravel-5-2/

**Comment by Kender2** [comment] 2016-10-29 09:10
Opened pull request [2788](https://github.com/laravel/docs/pull/2788) to document unchangeable column types.

**Comment by subratpalhar92** [comment] 2020-05-08 19:20
use Doctrine\DBAL\Types\StringType; use Doctrine\DBAL\Types\Type;

public function up() {
    if (!Type::hasType('char')) {
        Type::addType('char', StringType::class);
    }

    Schema::table('tablename', function (Blueprint $table) {
        $table->char('field', 1)->nullable()->change();
    });
}

**Comment by ankerdev** [comment] 2020-06-02 01:16
@subratpalhar92 That solved the issue I was having. Cheers!

**Comment by IllyaMoskvin** [comment] 2020-06-09 19:24
@subratpalhar92 Pretty sure that results in a `VARCHAR` column being created, not `CHAR`.

**Comment by baijunyao** [comment] 2020-06-11 06:58
@IllyaMoskvin  is right, I use the following method.
```php
DB::statement('ALTER TABLE oauth_clients CHANGE id id CHAR(36) NOT NULL');
```

**Comment by wturrell** [comment] 2020-07-07 14:09
Could I just confirm this is still not possible with `->change()` in Laravel 7+ too?
(I have an application still running 5.8.38 with doctrine/dbal 2.10.2)

**Comment by therealSMAT** [comment] 2021-03-16 11:00
Changing `->char('name', 1)->nullable()->change()` to `->string('name', 1)->nullable()->change()` worked for me.
