### ISSUE TITLE
File upload, FormRequest validation missing if breaks php upload_max_filesize

### ISSUE THREAD

**Issue by mgrulich** [laravel/framework#12095] opened 2016-01-31 13:11 UTC
Laravel-Version: 5.2.12

This issue is discussed first here: https://laracasts.com/discuss/channels/laravel/file-upload-validation-works-unexpected

The following settings are active in php.ini
```
post_max_size: 8M
upload_max_filesize: 2M
```

I try to upload a file named "test.file" with a size ~4M

My Form-Request looks like this:
```php
<?php namespace App\Http\Requests;

class FileRequest extends Request {
    public function authorize(){
        return true;
    }

    public function rules(){
        return [
            'file' => 'required|image|max:300'
        ];
    }
}
```
My Test-Controller like this:
```php
public function storeUpload(FileRequest $request, $id){
        $inputFile = $request->file('file');

        if ($inputFile->isValid()) {
            dd('All is fine');
        } else {
            dd($inputFile->getErrorMessage());
        }
    }
```
In this case (with required validation) I'll be redirected and the message for the file-Field is: "The file field is required." instead of "The file "test.file" exceeds your upload_max_filesize ini directive (limit is 2048 KiB)."

If I remove the required check from the form-request it passes the form-request validation (also with image and max:300 validation) and my controller needs to check the file again and I receive the correct error message: "The file "testfile-for.upload" exceeds your upload_max_filesize ini directive (limit is 2048 KiB).".

Someone helped me on laracasts forum tells the following at last:

> * The method isValidatable() returns false on a failed upload (instance of UploadedFile with error == 1).
> * If you look at the method isValidatable() you will see that it performs three checks and the culprit is presentOrRuleIsImplicit().
> * presentOrRuleIsImplicit() performs two checks, validateRequired() and isImplicit(), both return false.
> * The problem is within validateRequired(): In case of an instance of File it checks whether the object contains a path. Since it does not contain a path this method returns false.
> * This is the reason why isValidatable() returns false which in turn results in the validation rules not being evaluated / the actual validation not being performed.
> This looks intentional even though I would consider it a bug. If a file object is present and it does not contain a path but there are rules defined for it then the validation should fail.

With a test file smaller than php limit but greater than allowed within form-request validator all works fine.

**Comment by GrahamCampbell** [comment] 2016-01-31 13:15
Thank you, but this is actually a duplicate of https://github.com/laravel/framework/issues/8203.

**Closed** 2016-01-31 13:15 UTC
