### ISSUE TITLE
Error Page Repeats twice with 2 different errors.

### ISSUE THREAD

**Issue by MrMashy** [laravel/framework#17095] opened 2017-01-03 10:28 UTC
- Laravel Version: 5.3
- PHP Version: 7
- Database Driver & Version: SQL

### Description:
Laravel App Returns 2 error pages (head & body twice) with different errors both named ReflectionException

It seems like **index.php** is creating the problem at `$kernel->terminate($request, $response);`

When I remove this, the page is only created once. What is the purpose of terminate and why is it sending another content to the browser?

Using laravel error generator
![](http://imgur.com/cdEVyCD.png)

Using my custom error generator
![](http://imgur.com/RPskHSb.png)

### Steps To Reproduce:
In the main routes file add this: 
`Route::get('test', 'TestingController@test');`
and have no TestingController to create the exception

**Comment by themsaid** [comment] 2017-01-03 12:01
Duplicate of https://github.com/laravel/framework/issues/17007

**Closed by themsaid** 2017-01-03 12:01 UTC

**Comment by MrMashy** [comment] 2017-01-03 12:03
Thanks

**Comment by GrahamCampbell** [comment] 2017-01-03 12:40
This is fixed in L5.4. :)
