### ISSUE TITLE
UPDATED_AT constant is ignored on pivot model for BelongsToMany relation

### ISSUE THREAD

**Issue by alsma** [laravel/framework#31012] opened 2020-01-03 11:57 UTC
- Laravel Version: 6.9.0
- PHP Version: 7.3
- Database Driver & Version: 5.7.26-29 Percona Server

### Description:
Eloquent ignores `const UPDATED_AT = null;` for pivot models during attach. 
The issue was introduced in this [commit](https://github.com/laravel/framework/commit/93b5068214ddd1c1aa33bb09aea645fc916aed86) 

### Steps To Reproduce:
1. Let's assume we have 3 models: Hotel, User, UserReservation. `Hotel` model has `users()` belongs to many relation to `User` using `UserReservation` model.
2. Define `UPDATED_AT` constant on `UserReservation` equals to `null`
3. Try to save relation following way `$hotel->users()->save($user)`
4. **Expected**: `updated_at` field should not appear in SQL query. **Actual**: SQL query contains `updated_at` field which is not in table schema

**Comment by alsma** [comment] 2020-01-03 12:07
Minimal example:
```

class Hotel extends \Illuminate\Database\Eloquent\Model
{
    public function users(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(User::class)
            ->using(UserReservation::class)
            ->withPivot(['created_at']);
    }
}

class User extends \Illuminate\Database\Eloquent\Model
{
}

class UserReservation extends \Illuminate\Database\Eloquent\Relations\Pivot
{
    const UPDATED_AT = null;
}

\Illuminate\Database\Eloquent\Model::unguarded(function () {
    $hotel = new Hotel(['id' => 1]);
    $hotel->exists = true;
    $user = new User(['id' => 1]);
    $user->exists = true;

    $hotel->users()->save($user);

    // Laravel 5.8
    // insert into `hotel_user` (`user_id`, `hotel_id`, `created_at`) values (1, 1, 2020-01-03 12:05:10)
    // Laravel 6.9
    // insert into `hotel_user` (`user_id`, `hotel_id`, `created_at`, `updated_at`) values (1, 1, 2020-01-03 12:07:22, 2020-01-03 12:07:22)
});

```

**Comment by driesvints** [comment] 2020-01-03 13:03
Duplicate of https://github.com/laravel/framework/issues/30573

**Closed by driesvints** 2020-01-03 13:03 UTC
