### ISSUE TITLE
Session variable desappearing and reappearing randomly

### ISSUE THREAD

**Issue by sn0opr** [laravel/framework#8590] opened 2015-04-28 19:05 UTC
I recently discovered a strange behavior in my app. I have a session variable called 'operator' (which is an array that contains some key => value data) that desappear and reappear randomly, but not usually, just sometime!!!! which make no sense.

I made a '/test' route and did a dd(Session::all()); in it just to check the session content, and refreshing many (like 15 times each sec) times in the browser to see if this variable is really desappearing, and reappearing, and YES! it is!, but, how!, how can a session variable do that!!!

knowing that in my app I'm making a long polling ajax request for a sort of a notification system, but I'm not playing with this variable, (Note that I'm using the session_write_close(); in this action)

I'm using the *file* driver for the session

**Comment by GrahamCampbell** [comment] 2015-04-28 20:26
Dupe of #8172.

**Closed** 2015-04-28 20:26 UTC
