### ISSUE TITLE
no reconnection attempted when runnning a db queue and db goes away during commit

### ISSUE THREAD

**Issue by cosmok** [laravel/framework#17785] opened 2017-02-06 06:00 UTC
- Laravel Version: 5.3.9
- PHP Version: 7.0.11
- Database Driver & Version: mysqlnd 5.0.12, mysql 5.7.12

### Description:

When using the DB Queue Driver I am noticing that when server connection goes away while committing, transactions count remains the same. (function below):

https://github.com/laravel/framework/blob/7212b1e9620c36bf806e444f6931cf5f379c68ff/src/Illuminate/Database/Concerns/ManagesTransactions.php#L153

During the next iteration (of the queue/loop) there are more server connection errors (General error: 2006 MySQL server has gone away) (as the db connection is not reconnected and because connection obj is being reused in daemon mode) (function below):

https://github.com/laravel/framework/blob/7212b1e9620c36bf806e444f6931cf5f379c68ff/src/Illuminate/Database/Concerns/ManagesTransactions.php#L112

The behavior has been verified in 5.3. 5.4 appears to be no different in handling this scenario.

How should I handle this?

**Comment by barryvdh** [comment] 2017-02-14 11:59
I'm also getting a similar error on Laravel 5.3.30

I'm running 10 queue workers, and sometimes they seem to crash and take down the mysql server (needs to restart to function again). Not sure if the queue works are the cause or just showing up in the logs as result..

Stacktrace:
<details><summary>exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away'</summary>
[2017-02-14 12:38:19] production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /home/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
Stack trace:
#0 /home/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): PDO->exec('SAVEPOINT trans...')
#1 /home/app/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(175): Illuminate\Database\Connection->beginTransaction()
#2 /home/app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(175): Illuminate\Queue\DatabaseQueue->pop('default')
#3 /home/app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(146): Illuminate\Queue\Worker->getNextJob(Object(Illuminate\Queue\DatabaseQueue), 'default')
#4 /home/app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(75): Illuminate\Queue\Worker->runNextJob('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#5 /home/app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#6 /home/app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#7 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
<details>

**Comment by barryvdh** [comment] 2017-02-15 09:55
As observation, I had a lot of errors in my logs, every 3 seconds (the sleep duration) about not being able to connect, while the mysql connection was available for other processes. So it seems that no reconnection was attempted but the script kept running (but failing).
A restart of the supervisor processes made it work again.

So it should either kill the queue worker process or restart, not keep failing..

**Comment by barryvdh** [comment] 2017-02-15 10:09
So basically; not sure where it started, but now it does the following according to stack trace:

 - beginTransaction() calls createTransaction(); https://github.com/laravel/framework/blob/7212b1e9620c36bf806e444f6931cf5f379c68ff/src/Illuminate/Database/Concerns/ManagesTransactions.php#L92
 - Because transaction > 0, it creates a savepoint; https://github.com/laravel/framework/blob/7212b1e9620c36bf806e444f6931cf5f379c68ff/src/Illuminate/Database/Concerns/ManagesTransactions.php#L113
- This fails because it can't connect; throws exception which is not caught.
- $transactions-- is never reached; https://github.com/laravel/framework/blob/7212b1e9620c36bf806e444f6931cf5f379c68ff/src/Illuminate/Database/Concerns/ManagesTransactions.php#L94

But probably an error occurred first during the commit; https://github.com/laravel/framework/blob/7212b1e9620c36bf806e444f6931cf5f379c68ff/src/Illuminate/Database/Concerns/ManagesTransactions.php#L156
Which didn't reach the transactions change; https://github.com/laravel/framework/blob/7212b1e9620c36bf806e444f6931cf5f379c68ff/src/Illuminate/Database/Concerns/ManagesTransactions.php#L159

So should we wrap all `$this->getPdo()->...` with a try/catch and check `causedByLostConnection($e)` ?

**Comment by cosmok** [comment] 2017-02-21 06:23
This is what I ended up doing in app/Exceptions/Handler.php

inside report function:
<pre>

use Illuminate\Database\DetectsLostConnections;

if ('cli' === php_sapi_name() && $e instanceof PDOException && $this->causedByLostConnection($e)) {
     sleep(1);
     try {
         DB::reconnect('smsgateway');
      } catch (Exception $exceptionOnReConnect) {
      }
}   
</pre>

**Comment by barryvdh** [comment] 2017-02-22 09:33
So is that working reliably? Seems a bit hacky..

**Comment by cosmok** [comment] 2017-02-23 01:23
Appears to be working as expected during tests.

**Comment by rap2hpoutre** [comment] 2017-03-17 09:36
Not sure but maybe similar: https://github.com/laravel/framework/issues/18384

**Comment by barryvdh** [comment] 2017-05-10 08:16
I think this might be fixed with https://github.com/laravel/framework/pull/19080 ?
(I switched to Redis, which also solved it..)

**Closed** 2017-06-13 13:24 UTC
