### ISSUE TITLE
UploadedFile not working with store method from the request's uploaded file

### ISSUE THREAD

**Issue by caiquecastro** [laravel/framework#18724] opened 2017-04-07 22:44 UTC
- Laravel Version: 5.4.17
- PHP Version: 7.1.12

### Description:
Storage fake doesn't work when uploading files from the request.
`$request->file('avatar')->store('avatars');`

### Steps To Reproduce:
my controller:

```sh
    ....
    $request->file('avatar')->store('avatars');
    ....
```

My test
```sh
Storage::fake('avatars');
$user = factory(\App\User::class)->create();

$response = $this->actingAs($user)
                            ->post('/api/users', [
                                'name' => 'John Doe',
                                'avatar' => UploadedFile::fake()->image('john-doe.jpg'),
                             ]);

$response->assertStatus(201);
Storage::disk('avatars')->assertExists('john-doe.jpg');
```

**Comment by alhoqbani** [comment] 2017-04-10 01:39
I have the same issue. 

Basically, the controller will store the file in your default disk ('local'). However, your test is testing against the fake disk ('avatars'). 
If you check your default disk, you should see the image presents.

There should be a way to set the default desk for the testing environment to the fake storage.

**Comment by alhoqbani** [comment] 2017-04-10 03:19
try this:
[https://laracasts.com/discuss/channels/testing/changing-default-disk-for-testing/replies/331158](url)

**Comment by caiquecastro** [comment] 2017-04-10 12:50
Thanks @alhoqbani. I think it's a good idea to open a PR to laravel/laravel with this solution, but I don't know if @taylorotwell or other core member have another solution.

**Comment by themsaid** [comment] 2017-04-10 18:56
You can use `Storage::disk('local')->assertExists('john-doe.jpg')` if you store the image in the local disk in the controller, also `store()` saves the file using a generated hashname not the actual name of the uploaded file, that will cause your tests to fail too.

**Comment by alhoqbani** [comment] 2017-04-10 23:08
That's a possible soultion, but it will leave the fake file on the local disk. Unless, you delete them after each test the disk will be full of fake files.

**Comment by themsaid** [comment] 2017-04-11 07:15
Next time the tests are run the directory will be cleaned and all files will be removed.

**Comment by caiquecastro** [comment] 2017-04-11 18:57
I'm using the `storeAs` method

**Comment by themsaid** [comment] 2017-04-12 12:22
Then all what you need to do is to fake the local driver since you store the avatars on it.

Closing since it's not a bug, since you store the file on local driver you need to look for it on your local driver :)

**Closed by themsaid** 2017-04-12 12:22 UTC
Labels: Under Discussion

**Comment by caiquecastro** [comment] 2017-04-14 15:46
So there is no use case for `Storage::fake('fake-local');`, right?

**Comment by mtanmay** [comment] 2019-08-19 07:39
The only use case for `Storage::fake('test-disk-name')` that I can see is cleaning up the test disk directory when the test is run next time. It doesn't change the filesystem driver on-the-fly. So this `env` tag needs to be added in `phpunit.xml`: `<env name="FILESYSTEM_DRIVER" value="test-disk-name"/>`

**Comment by oliiix** [comment] 2020-04-15 13:36
i think it's no mistake. the files are being stored (at least at v6 and 7) outside in the /storage/xyz directory which is identical to the one you specified! you have to make a link between a folder in public/storage or /public/upload or however you call it and it's counterpart under /storage/xyz

**Comment by Iguet** [comment] 2020-07-09 19:19
I got the same issue, with Storage::fake the file keeps in the directory, I'd like to know if there's a way to clean up the directory after each test
