### ISSUE TITLE
Resource Collections breaks when manipulating underlying collection

### ISSUE THREAD

**Issue by philcross** [laravel/framework#35906] opened 2021-01-15 10:54 UTC
- Laravel Version: 8.22.0
- PHP Version: 7.3.18
- Database Driver & Version: mysql & 5.6.50

### Description:

I previously ran a composer update and updated to the latest minor release of Laravel, during which a resource collection stopped working as expected.
I tracked down the issue to a section of code where in the `toArray()` method of a resource collection, i was doing:

```
// QuestionCollection.php

'some_key' => $this->collection->map(function (QuestionModel $question) {
    return QuestionResource::make($question)->foobar();
})->toArray()
```

Prior to running composer update, (was running a version <8.22.0) this worked as expected, and `some_key` could contain an array generated  collection of `QuestionResource` resource objects.

After updating, I would get the error `Argument 1 passed to App\Http\Resources\QuestionCollection::App\Http\Resources\{closure}() must be an instance of App\Models\Question, instance of App\Http\Resources\QuestionResource given`

I've tracked the error down to this commit: https://github.com/laravel/framework/commit/1fa20dd356af21af6e38d95e9ff2b1d444344fbe

Commenting out line 51 makes the collection map work again as expected.

I understand my code may have been incorrect to begin with, and I shouldn't have been using `$this->collection` originally, so attempted to change it to `$this->resource` and still got the same error. I think this is because in `Illuminate\Http\Resources\Json\ResourceCollection.php` the constructor is calling `parent::__construct($resource)`, which is setting `$this->resource` to the underlying eloquent collection, but then immediately after, the constructor does `$this->resource = $this->collectResource($resource)`, which overrides the underlying eloquent collection to the resource collection instead.

With the updated commit, there's not a way (that I can find) that allows me to manipulate the underlying eloquent collection before the resource is converted to an array.

I feel like `$this->resource` should contain the eloquent collection, and `$this->collection` should contain the resource collection (or collection of individual resource objects).

If I'm doing wrong and i should be manipulating the resource differently I'm happy to change my code, otherwise, I'm happy to create a PR myself with guidance on what properties should be expected to contain what values.

### Steps To Reproduce:

I've created a project to reproduce this error:

https://github.com/philcross/laravel-8.22.1-bug

`master` branch contains a working example - see `app/Http/Controller.php` which returns a normal `UserCollection` instance
branch `framework-8.22.1` contains the exact same code, but has been updated to use the latest framework version and fails.

I've added a feature test in `tests/Feature/UserTest.php` which again is the same code in both branches. In master it returns the collection successfully, in the latest framework branch it returns a 500 error.

**Comment by taylorotwell** [comment] 2021-01-15 15:31
I'm trying to figure out how that change would cause your issue and I'm not sure I'm understanding it? Do you?

**Comment by taylorotwell** [comment] 2021-01-15 15:32
I don't totally understand your example repository either. Why are you passing an array of `UserResource` instances into UserCollection within your UserCollection class? Don't collections accept arrays or collections of models - not resources?

**Comment by philcross** [comment] 2021-01-15 16:04
Sorry I purposefully made the example repo more simplistic than my actual code, but I've updated my examples `UserCollection` resource to hopefully show a more real life example - if I wanted to list all of a users emails separately from the individual user resources.

Previously, if I had a `UserResource` class and a `UserCollection` class, because the `CollectsResources` trait only seemed to look for `User(.php)` resources instead of `UserResource`, then `$collects` would be null, and the `$resource->toBase()` method would be called. 

With the addition of the extra line to see if the `UserResource` class exists, `$collects` now matches `UserResource::class`, so `CollectsResources` uses `$resource->mapInto($collects)`, which in turn maps the models in the eloquent collection, into resources in the eloquent collection.

To me, the addition of checking for the Resource class definitely makes sense, but `$this->collection` and `$this->resource` in the `UserCollection` class now both reference the collection which only contains user resource objects instead of a collection with the underlying models.

I'm hoping this makes sense, but if it doesn't, or I'm not understanding the collection properly please feel free to let me know. As in the description, I'm more than happy to submit a PR, or anything else that might help.

**Comment by taylorotwell** [comment] 2021-01-15 16:23
I'm still pretty lost honestly.

**Comment by taylorotwell** [comment] 2021-01-15 16:23
The correct way to customize the resource class for a collection to a non-default class was this:

![Uploading image.png…]()

**Comment by philcross** [comment] 2021-01-18 08:25
In my example, my `UserCollection` class is looping through each user model to build up an array of emails as well as displaying the normal user resource. It's the email part that's currently broke.

In a normal resource class, you can access whatever was passed into the resource using `$this->resource`
In a resource collection class you could previously access whatever was passed into the collection by using `$this->resource`, which in my example is an eloquent collection of eloquent user models.
After the change, instead of it being an eloquent collection of eloquent user models, it's now an eloquent collection of user resources.

However having the weekend to think about it, I could rewrite my code to access the model via the resource instead. So instead of this:

```
// Resources/UserCollection.php
// $this->resource is the eloquent collection, of eloquent user models

'emails' => $this->resource->map(function (User $user) {
    return $user->email;
});
```

I could /would have to write it like this instead:
```
// Resources/UserCollection.php
// $this->resource is now an eloquent collection of user resource objects
'emails' => $this->resource->map(function (UserResource $user) {
    return $user->resource->email;
});
```

I'll try to put a PR together today, and leave it up to you whether you see benefit in it.
Thank you again.

**Comment by toyi** [comment] 2021-01-18 13:18
I had the exact same problem today, as i was iterating through the collection like @philcross did in his example:

```php
'users' => $this->collection->map(function (User $user) {
     //do something to $user...
}),
```

Before, `$user` would have been an `User` instance. But since https://github.com/laravel/framework/commit/1fa20dd356af21af6e38d95e9ff2b1d444344fbe, if `UserResource` exists, it becomes an `UserResource` instance (and therefore fail the type check).

Fixed it quickly by rewriting the code like that:

```php
'users' => $this->collection->map(function (UserResource $user) {
     //do something to the underlying User instance using $user->resource
}),
```
I understand it was probably the way it was intended to work at first, but it is confusing when something that hasn't been touched for ages breaks after a minor update like this.

**Comment by taylorotwell** [comment] 2021-01-18 16:05
Closing this for now as this mainly just surfaced a couple instances of using the collections and resources in an undocumented way.

**Closed by taylorotwell** 2021-01-18 16:05 UTC
Labels: needs more info

**Comment by cretueusebiu** [comment] 2021-01-26 18:27
My resource collections usually return just a few properties:

```php
// UserCollection
public function toArray($request)
{
    $this->collection->map(fn (User $user) => [
        'id' => $user->id,
        'name' => $user->name, 
   ]);
}
```

Now if I have a `UserResource` resource the `$user` argument is an instance of `UserResource` instead of `User`.
And you can't use `$this->collects = null;` in the model to disable it.

A quick fix was to override the `collects` method on my resource collection:

```php
protected function collects()
{
    return null;
}
```

But this just feels wrong 😟
