### ISSUE TITLE
Performance issues when doing multiple queries to the database

### ISSUE THREAD

**Issue by malhayek2014** [laravel/framework#14122] opened 2016-06-24 00:00 UTC
I have an application developed using Laravel 5.2 and Eloquent ORM. The application is connected to a MS SQL Server to read/write to data.

I am running into performance issues where the application sometime slows down "the page takes 5+ seconds to respond"

I installed "Clockwork" to try to see what is taking long time to execute. After digging into multiple requests I noticed that some queries that are taking long time to finish .

Here is an example of a query that took about 1600ms to finish. (1600ms include perpetration and network latency, and database executing time.)

```
INSERT into [items] ([control_id], [created_at], [interview_id], [is_default], [item_id], [item_title], [item_type], [reporting_value], [updated_at])
values ('328', '2016-06-23 23:12:02', '6278', 'No', '1105', '1 (Poor)', 'Answer', '1', '2016-06-23 23:12:02'), 
('328', '2016-06-23 23:12:02', '6278', 'No', '1106', '2', 'Answer', '2', '2016-06-23 23:12:02'), 
('328', '2016-06-23 23:12:02', '6278', 'No', '1107', '3', 'Answer', '3', '2016-06-23 23:12:02'), 
('328', '2016-06-23 23:12:02', '6278', 'No', '1108', '4', 'Answer', '4', '2016-06-23 23:12:02'), 
('328', '2016-06-23 23:12:02', '6278', 'No', '1109', '5', 'Answer', '5', '2016-06-23 23:12:02'), 
('328', '2016-06-23 23:12:02', '6278', 'No', '1110', '6', 'Answer', '6', '2016-06-23 23:12:02'), 
('328', '2016-06-23 23:12:02', '6278', 'No', '1111', '7', 'Answer', '7', '2016-06-23 23:12:02'), 
('328', '2016-06-23 23:12:02', '6278', 'No', '1112', '8', 'Answer', '8', '2016-06-23 23:12:02'), 
('328', '2016-06-23 23:12:02', '6278', 'No', '1113', '9', 'Answer', '9', '2016-06-23 23:12:02'), 
('328', '2016-06-23 23:12:02', '6278', 'No', '1114', '10 (Excellent)', 'Answer', '10', '2016-06-23 23:12:02'), 
('328', '2016-06-23 23:12:02', '6278', 'No', '1608', 'Don''t Know', 'Others', '98', '2016-06-23 23:12:02'), 
('328', '2016-06-23 23:12:02', '6278', 'No', '1708', 'Does not have item/department', 'Answer', '99', '2016-06-23 23:12:02'), 
('338', '2016-06-23 23:12:02', '6278', 'No', '1205', '1 (Poor)', 'Answer', '1', '2016-06-23 23:12:02'), 
('338', '2016-06-23 23:12:02', '6278', 'No', '1206', '2', 'Answer', '2', '2016-06-23 23:12:02'), 
('338', '2016-06-23 23:12:02', '6278', 'No', '1207', '3', 'Answer', '3', '2016-06-23 23:12:02'), 
('338', '2016-06-23 23:12:02', '6278', 'No', '1208', '4', 'Answer', '4', '2016-06-23 23:12:02'), 
('338', '2016-06-23 23:12:02', '6278', 'No', '1209', '5', 'Answer', '5', '2016-06-23 23:12:02'), 
('338', '2016-06-23 23:12:02', '6278', 'No', '1210', '6', 'Answer', '6', '2016-06-23 23:12:02'), 
('338', '2016-06-23 23:12:02', '6278', 'No', '1211', '7', 'Answer', '7', '2016-06-23 23:12:02'), 
('338', '2016-06-23 23:12:02', '6278', 'No', '1212', '8', 'Answer', '8', '2016-06-23 23:12:02'), 
('338', '2016-06-23 23:12:02', '6278', 'No', '1213', '9', 'Answer', '9', '2016-06-23 23:12:02'), 
('338', '2016-06-23 23:12:02', '6278', 'No', '1214', '10 (Excellent)', 'Answer', '10', '2016-06-23 23:12:02'), 
('338', '2016-06-23 23:12:02', '6278', 'No', '1618', 'Don''t Know', 'Others', '98', '2016-06-23 23:12:02'), 
('338', '2016-06-23 23:12:02', '6278', 'No', '1721', 'Does not have item/department', 'Answer', '99', '2016-06-23 23:12:02'), 
('408', '2016-06-23 23:12:02', '6278', 'No', '1472', '1 (Poor)', 'Answer', '1', '2016-06-23 23:12:02'), 
('408', '2016-06-23 23:12:02', '6278', 'No', '1473', '2', 'Answer', '2', '2016-06-23 23:12:02'), 
('408', '2016-06-23 23:12:02', '6278', 'No', '1474', '3', 'Answer', '3', '2016-06-23 23:12:02'), 
('408', '2016-06-23 23:12:02', '6278', 'No', '1475', '4', 'Answer', '4', '2016-06-23 23:12:02'), 
('408', '2016-06-23 23:12:02', '6278', 'No', '1476', '5', 'Answer', '5', '2016-06-23 23:12:02'), 
('408', '2016-06-23 23:12:02', '6278', 'No', '1477', '6', 'Answer', '6', '2016-06-23 23:12:02'), 
('408', '2016-06-23 23:12:02', '6278', 'No', '1478', '7', 'Answer', '7', '2016-06-23 23:12:02'), 
('408', '2016-06-23 23:12:02', '6278', 'No', '1479', '8', 'Answer', '8', '2016-06-23 23:12:02'), 
('408', '2016-06-23 23:12:02', '6278', 'No', '1480', '9', 'Answer', '9', '2016-06-23 23:12:02'), 
('408', '2016-06-23 23:12:02', '6278', 'No', '1481', '10 (Excellent)', 'Answer', '10', '2016-06-23 23:12:02'), 
('408', '2016-06-23 23:12:02', '6278', 'No', '1648', 'Don''t Know', 'Others', '98', '2016-06-23 23:12:02'), 
('408', '2016-06-23 23:12:02', '6278', 'No', '1733', 'Does not have item/department', 'Answer', '99', '2016-06-23 23:12:02')
```
When I execute this query directly using MS SQL Server Management Studio it finishes in 00:00:00 which tells me that the database server is running fine and there are no delays on the data server side.

Since there are lots of data being inserted I am thinking the PDO/Eloquent is taking long time to prepare the statement which is causing a delay for the simple fact that there are 36 rows being prepared here. But, also the problem could be that PDO takes a while to connect database which is why I see a delay is a query which will delay the entire application.

Here is another simple query that took over 1300ms to return 1 row which was completed in 00:00:01 when executing it in MS SQL Management studio.
```
SELECT * FROM [stext] WHERE [interview_id] = '6278' and [control_id] in ('306') ORDER BY [id] ASC
```
This query does not have much to prepare but still took over 1300ms to complete.

Both the Web server and the data server are on the same network and host. Both are located in the same physical room so there should not be any network issues (the is only one hub between the two machines). I even tried to ping the servers and the ping looks very normal.

Is this a performance issues caused by Eloquent/Laravel, PDO issue or a different issue?

**Comment by spencerdeinum** [comment] 2016-06-24 00:24
Strange, have you tried checking the query plan for the second query?

I'm not sure how many people use MS SQL with Laravel so it is possible there might be some weirdness with PDO.

Your best bet is to fire up Xhprof or PHPDebug's profiler and see generate some flamegraphs / profiling information.

**Comment by malhayek2014** [comment] 2016-06-24 21:04
I finally got xDebug profiler installed on my PHP version 5.6.23.

When I open the files that were generated by the profiler in QCachegrind 0.5.1 I don't see any of my functions/classes in there. I am having hard time trying to understand the output. Can you offer any guidance here?

**Comment by spencerdeinum** [comment] 2016-06-24 21:09
So usually you want to hit the web url that you want to profile and grab that profiler output and load it like you've done. For some reason the last time I used Xhprof it was generating two dumps per request but only one had the relevant info.

You should be able to sort by time and see where your application is spending most of its cpu time, if the sql queries are taking as long as you say you should be able to see it.

The different time columns measure the execution time differently, like it will show you how much time the code spent in that function, including functions that function called, or just the time spent in that function alone.

If you find one that looks like the queries you ran you could try uploading it here or in a gist.

**Comment by malhayek2014** [comment] 2016-06-24 21:23
But none of my code is being included in the file. all of my code is located in `\vendor\malhayek\` and I can't see any of the classes inside that folder being called. Is there a setting that I need to enable to see all of my classes in the profiler?

**Comment by spencerdeinum** [comment] 2016-06-24 21:40
That is strange... there is no setting needed really, are you sure its the right dump?

Also I haven't had the chance to try this but https://blackfire.io/ is also an option.

**Comment by malhayek2014** [comment] 2016-06-24 23:34
Okay. you are right I had the wrong file. After opening the correct file I don't see a very long query but the page still take 2+ seconds to load. Attached are the files from the profiler I hope you can view it and  see if you can see any problems.

**Comment by spencerdeinum** [comment] 2016-06-25 18:09
You should know that when the profiler is active the requests can take a longer time too, so clockwork might show confusing output for that.

The second profile seems fine, most of the time is spent autoloading with composer which is pretty typical during development.

As for the first two dumps it seems like most of the time is being spent in `php::PDOStatement->execute`. At first glance I'm going to say its either the DB being slow or just returning a lot of data.

If you look at the code you can see a lot of time is spent inside the `hasCast` and `getCasts` code for Illuminate... do you have attributes for all of the attributes enabled? I'm not sure about MSSQL but you might be able to switch the database driver used... For example the mysqlnd driver actually handles the attribute casting in driver itself instead of having to cast everything in Laravel.

**Comment by spencerdeinum** [comment] 2016-06-25 18:19
As a side note, there seems to be a ton of calls in this stack trace to `Illuminate\Database\DatabaseManager->parseConnectionName` which results in a lot of calls to `Illuminate\Support\Str::endsWith`.

It might be worth caching the results of that @taylorotwell but I'm not sure if thats actually a big issue for most workloads. I could look at it if he thinks its an issue.

**Comment by malhayek2014** [comment] 2016-06-25 20:57
You mentioned that autoloading typical to take longer time in development. Why would that be the case? How can I improve that during production? Just before I generated the results, I executed the following commands
```
php artisan optimize --force
php artisan route:cache
php artiasn config:cache
```

regarding `php::PDOStatement->execute` that is definitely an issue. I the database is very very light and the results are very little. I even run SQL Server profiler on the server and all the queries seems to be running very quick. Its either a network latency or the driver does not work well.

It is interesting that you are seeing lots of casting. I submitted another issue related to casting here https://github.com/laravel/framework/issues/11780

Where are the `hasCast` and `getCasts` are called? I am not using lots of mutaturs in my code. The only time I cast is when converting eloquent collection to Illuminate collection. like the following example
```
$articles = article::with('comments')->all();

foreach($articles as $article)
{
   $article= (object) $article;
   foreach($article->comments as $comment)
   {
      $comment= (object) $comment;
      //do something
   }
}
```

**Comment by spencerdeinum** [comment] 2016-06-25 21:05
No it would be casting the attributes of your models not the collection.

https://laravel.com/docs/5.2/eloquent-mutators#attribute-casting

> You also asked "Do you have attributes for all of the attributes enabled?" I am not sure exactly what you mean.

I can't type today apparently, I mean to ask if you had many of your attributes defined using the attribute casting above.

**Comment by malhayek2014** [comment] 2016-06-25 21:13
Thank you for your feedback. No I am not doing any attribute casting. 

However, I am using the following trait in all my models to change the datetime format to have milliseconds 
```
<?php

trait SqlServerDateTime {

	/**
	 * Get the format for database stored dates.
	 *
	 * @return string
	 */
	public function getDateFormat()
	{
	    return 'Y-m-d H:i:s.u';
	}

	/**
	 * Convert a DateTime to a storable string.
	 * SQL Server will not accept 6 digit second fragment (PHP default: see getDateFormat Y-m-d H:i:s.u)
	 * trim three digits off the value returned from the parent.
	 *
	 * @param  \DateTime|int  $value
	 * @return string
	 */
	public function fromDateTime($value)
	{
	    return substr(parent::fromDateTime($value), 0, -3);
	}

}
```

Other than that my models are straight forward. Here is one of my models and most of them look the same

```

class SurveyQuestion extends Model 
{

	/**
	 * {@inheritDoc}
	 */
	protected $table = 'survey_questions';

	/**
	 * {@inheritDoc}
	 */
	protected $guarded = [
		'id',
	];

	/**
	 * {@inheritDoc}
	 */
	protected $with = [

	];

    protected $dates = [
      
    ];

     /**
     * Get survey that owns the question
     */
    public function survey()
    {
        return $this->belongsTo(Survey::class, 'survey_id', 'id');
    }

     /**
     * Get controls for the question
     */
    public function controls()
    {
        return $this->hasMany(SurveyQuestionControl::class, 'question_id', 'id');
    }

     /**
     * Get pool relations for the question
     */
    public function pool_relations()
    {
        return $this->hasMany(QuestionToPool::class, 'question_id', 'id');
    }

    public function used()
    {
        return $this->belongsTo(SurveyUsedQuestion::class, 'id','question_id');
    }


    public function display_logic()
    {
        return $this->hasOne(DisplayLogic::class, 'target_id')->where('target', 'Question');
    }
    

    public function used_controls()
    {
        return $this->hasManyThrough(SurveyUsedControl::class, SurveyQuestionControl::class, 'question_id', 'control_id');
    }
   

    public function scopeSurveyAndPageAndStatus($query, $surveyId, $pageId, $status = 'Active')
    {
        return $query->where('survey_id', $surveyId)
                     ->where('page_id', $pageId)
                     ->where('status', $status);

    }   
    

}

```

**Comment by malhayek2014** [comment] 2016-06-25 21:22
Regarding casting the data in the driver itself, here are the available options for MSSQL connection I am not sure if you can see an option that will force casting in the driver 
http://php.net/manual/en/ref.pdo-sqlsrv.php

**Comment by belisarh** [comment] 2016-06-27 04:18
If `PDO::ATTR_PERSISTENT => true` improves your performance then some connection pooling implementation might be a better long terms solution.

**Comment by malhayek2014** [comment] 2016-06-27 16:28
@belisarh I have 2 main requests one for get and another for post and in both requests, I use transaction when I execute all of my queries. I have added `PDO::ATTR_PERSISTENT => true` but have not yet noticed a big difference. I actually tried to turn on ConnectionPooling when connecting but it may be an issue is Laravel where you can turn that open on.

in the SqlServerConnector.php in laravel I found this code 

        if (isset($config['pooling']) && $config['pooling'] === false) {
            $arguments['ConnectionPooling'] = '0';
        }

it seems that you can disable ConnectionPooling but you can't really turn it on. I would think the above code should be something like this


        if (isset($config['pooling']) ) {
            $arguments['ConnectionPooling'] = $config['pooling'] === false ? '0' : '1';
        }

and in the config I should be able to turn ConnectionPooling on by adding the following key to the config array

        'base' => [
            'driver'   => 'sqlsrv',
            'host'     => env('DB_HOST', 'localhost'),
            'database' => env('DB_DATABASE', ''),
            'username' => env('DB_USERNAME', ''),
            'password' => env('DB_PASSWORD', ''),
            'charset'  => 'utf8',
            'pooling'  => '1',
            'prefix'   => '',
            'pooling' => true,
            'options'  => [
                            PDO::ATTR_PERSISTENT => true
                          ],
        ],

**Comment by themsaid** [comment] 2016-10-04 09:07
Hello everyone, can you please share you dealt with the problem? Found any performance issues in the core?

**Comment by themsaid** [comment] 2016-10-04 18:32
For large queries like this I'd personally prefer using the query builder not Eloquent, this gives you better control over the query and involves less preparation.

Closing this issue then since it's not a bug in the framework after all, thank you for getting back to us :)

**Closed by themsaid** 2016-10-04 18:32 UTC
