### ISSUE TITLE
This mornings update to 5.5.16 breaks our Lumen site

### ISSUE THREAD

**Issue by edwardsides** [laravel/framework#21697] opened 2017-10-16 15:51 UTC
Good morning,

- Laravel Version: Lumen (5.5.1) (Laravel Components 5.5.*)
- PHP Version: 7.1
- Database Driver & Version:

### Description:
Receiving this issue from our Lumen site after this AMs update to 5.5.16.  I think it is due to having no views defined.
at Application->Laravel\Lumen\Concerns\{closure}(2, 'Invalid argument supplied for foreach()', '/var/www/bmc-api/vendor/illuminate/support/ServiceProvider.php', 84, array('path' => '/var/www/bmc-api/vendor/illuminate/pagination/resources/views', 'namespace' => 'pagination'))
in ServiceProvider.php (line 84)

    protected function loadViewsFrom($path, $namespace)
    {
        foreach ($this->app->config['view']['paths'] as $viewPath) {
            if (is_dir($appPath = $viewPath.'/vendor/'.$namespace)) {
                $this->app['view']->addNamespace($namespace, $appPath);
            }
        }

        $this->app['view']->addNamespace($namespace, $path);
    }

I commented out the code of the function to get back online.

### Steps To Reproduce:
Composer update and run.

**Comment by themsaid** [comment] 2017-10-16 17:47
Can't replicate this in a fresh lumen installation, can you please share more information on the issue?

**Comment by edwardsides** [comment] 2017-10-16 17:50
Thanks for the update.  I had to roll back.  I will try to reproduce again tomorrow with a fresh install.

**Comment by fracon** [comment] 2017-10-16 21:44
Got the same error after run composer update.

**Comment by adalytic-cj** [comment] 2017-10-16 22:48
In order to reproduce this on a default Lumen installation you must enable eloquent so that the Application actually tries to load the PaginationServiceProvider. This ultimately causes the error because the loadViewsFrom method changed in 5.5.15 ([in this commit](https://github.com/laravel/framework/commit/7f084cd964894c62b7c11f76f1f244439a1ae4d2)) from

```php
protected function loadViewsFrom($path, $namespace)
    {
        if (is_dir($appPath = $this->app->resourcePath().'/views/vendor/'.$namespace)) {
            $this->app['view']->addNamespace($namespace, $appPath);
        }
        $this->app['view']->addNamespace($namespace, $path);
    }
```

to

```php
protected function loadViewsFrom($path, $namespace)
    {
        foreach ($this->app->config['view']['paths'] as $viewPath) {
            if (is_dir($appPath = $viewPath.'/vendor/'.$namespace)) {
                $this->app['view']->addNamespace($namespace, $appPath);
            }
        }

        $this->app['view']->addNamespace($namespace, $path);
    }
```

Until a patch is released you can add a 'view.php' configuration file, define paths as an empty array, and configure it before making the call to enable eloquent.

```php
<?php
return [
    'paths' => []
];
```

**Comment by rg1220** [comment] 2017-10-17 04:43
I am also seeing this on a clean lumen install but without any modifications besides copy `.env.example` to `.env`.

**Comment by persevereVon** [comment] 2017-10-17 08:11
same error.

**Comment by BarnettZhou** [comment] 2017-10-17 08:39
same error in lumen.

**Comment by ykocaman** [comment] 2017-10-17 09:03
@adalytic-cj  your solution works. but also i added `$app->configure('view');` to **bootstrap/app.php** before `$app->withEloquent();`

**Comment by TrungVuDang** [comment] 2017-10-17 09:15
I got the same issue on fresh lumen install

**Comment by pkeatingcrossflow** [comment] 2017-10-17 09:16
Add this file to your config folder to fix the issue: [view.php](https://github.com/laravel/lumen-framework/blob/5.5/config/view.php) and add 
```php
$app->configure('view')
```
 to **bootstrap/app.php**

**Comment by namgua** [comment] 2017-10-17 10:20
Same here.
After running composer update on my 3 microservices, got error

<img width="491" alt="screen shot 2017-10-17 at 13 20 21" src="https://user-images.githubusercontent.com/32553949/31659815-fee07116-b33d-11e7-9e17-b636a7ef49af.png">

**Comment by isak-glans** [comment] 2017-10-17 10:31
I hav the same error, when trying to open a fresh Lumen installation; and after updating composer.
I am new to Lumen, but I cant find any config folder.

**Comment by nandhikawph** [comment] 2017-10-17 11:22
@ykocaman 
Putting this without having view configuration file also works, so essentialy you only need to put this two line 
$app->configure('view');
$app->withEloquent();

**Comment by themsaid** [comment] 2017-10-17 13:23
Fixed in https://github.com/laravel/framework/pull/21705

**Closed by themsaid** 2017-10-17 13:23 UTC
Labels: Unable to Replicate
