### ISSUE TITLE
ConvertEmptyStringsToNull middleware + input vaildation 'required_if' along with other validations is not working correctly

### ISSUE THREAD

**Issue by arunvkumarkc** [laravel/framework#17818] opened 2017-02-08 08:17 UTC
- Laravel Version: 5.4.8
- PHP Version: 7.1.0

### Description:
input vaildation 'required_if' along with other conditions is not working as expected when ConvertEmptyStringsToNull middleware  is enabled. 
I have used min validation condition along with required_if, as per laravel doc its expected to trigger min validation only if required_if input filed is equal to some value. I have given rules in following order
'name' => 'required_if:check_required,1|min:3'
But its giving validation error for min even if check_required field is not equal to 1
When I disable **ConvertEmptyStringsToNull** all works fine. 

### Steps To Reproduce:
clone this repo
https://github.com/arunvkumarkc/required_if_validation_bug
and access /test route. Validation rules are in TestController.php

**Comment by themsaid** [comment] 2017-02-08 13:10
Duplicate of https://github.com/laravel/framework/issues/17817

Please don't duplicate your issues, the middleware is optional, you can use it if you want or completely drop it if you don't.

**Closed by themsaid** 2017-02-08 13:10 UTC
