### ISSUE TITLE
Feature Request: allow delimited values for the preset validator rules

### ISSUE THREAD

**Issue by sadnub** [laravel/framework#15311] opened 2016-09-06 21:28 UTC
I'm using Laravel 5.3

I am having to use many lengthy regular expressions to validate text area fields in my application. I thought it may be easier to be able to include a validation rule that takes a default validator rule and allows it to be delimited by a set value. Something like this:

```
'field' => 'required|ip|delimitor:\n',
```

This will validate something like this:

12.12.12.12
13.13.13.13
14.14.14.14

The regex I am using to validate this is
```
/^(((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)(\/(3[0-2]|[1-2]?\d))?(\r\n?|\n?))*$/
```

Would this be possible?

**Comment by themsaid** [comment] 2016-09-06 21:35
I don't think it's correct to use the validator to alter the input data, the validator's job is to validate only IMO.

Anyway, I'm closing this since it's not a bug report :)
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Closed by themsaid** 2016-09-06 21:35 UTC

**Comment by sadnub** [comment] 2016-09-07 00:08
Thanks for showing me where to put in feature requests! Actually the Validator wouldn't change anything. It would be nice to be able to validate newline and comma delimited data that you would normally find in a textarea field with multiple rows. Just a thought.
