### ISSUE TITLE
When i use api as route method, i can't get the session values.  

### ISSUE THREAD

**Issue by Bevis-Liao** [laravel/framework#22320] opened 2017-12-06 03:04 UTC
- Laravel Version: 5.5.*
- PHP Version: 7.1.12
- Database Driver & Version: MySQL 5.7

### Description:
When i request url is 'api/test' , i can't get the session values.  my test code: 
```
Route::get('session/test',function(){
    if (session()->has('test'))
    {
        echo 'session storage , data:' . session('test');
    }else{
        session('test','this is test');
        dd(session('test'));
    }
});

### Steps To Reproduce:
```
the base method session_start() and $_SESSION['test'] are access values.

**Comment by laurencei** [comment] 2017-12-06 03:11
Hi @Bevis-Liao,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself. The lack of session data in the API is an intended and correct behaviour of the framework.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by Bevis-Liao** [comment] 2017-12-06 03:20
@laurencei  Many thanks for your reply.

**Comment by sisve** [comment] 2017-12-06 06:40
This is not a bug. Check the [$middlewareGroups in your app/Http/Kernel.php](https://github.com/laravel/laravel/blob/3f0e742421d8a922ba8a3b075189aa1bfd103ab6/app/Http/Kernel.php#L29-L44) and you'll find that the api does not have sessions enabled.

**Closed** 2017-12-06 07:31 UTC

**Comment by manojibcarockers** [comment] 2019-08-29 08:16
Solved by adding `\Illuminate\Session\Middleware\StartSession::class,`

In Kernel.php

Before
'api' => [
            'throttle:60,1',
            'bindings',
        ],

After
'api' => [
            \Illuminate\Session\Middleware\StartSession::class,
            'throttle:60,1',
            'bindings',
        ],

**Comment by adampatterson** [comment] 2019-12-01 01:43
> This is not a bug. Check the [$middlewareGroups in your app/Http/Kernel.php](https://github.com/laravel/laravel/blob/3f0e742421d8a922ba8a3b075189aa1bfd103ab6/app/Http/Kernel.php#L29-L44) and you'll find that the api does not have sessions enabled.

I know this is an old post, but would there be some negative outcomes form enabling sessions in the API routes?

**Comment by marcosdipaolo** [comment] 2020-04-12 22:27
@adampatterson I enabled them but it still didn't work

**Comment by gwaixin** [comment] 2020-04-20 12:18
> Solved by adding `\Illuminate\Session\Middleware\StartSession::class,`
> 
> In Kernel.php
> 
> Before
> 'api' => [
> 'throttle:60,1',
> 'bindings',
> ],
> 
> After
> 'api' => [
> \Illuminate\Session\Middleware\StartSession::class,
> 'throttle:60,1',
> 'bindings',
> ],

It didn't work for me at first but when i cleared my config it now works.
`php artisan config:clear`

**Comment by bhavinzwt** [comment] 2022-02-11 07:46
It is still not working for me after the above changed

**Comment by adampatterson** [comment] 2022-02-11 14:35
@marcosdipaolo  I can't even remember what project I was working on at the time but have a look at using [Laravel Sanctum](https://laravel.com/docs/8.x/sanctum)
