### ISSUE TITLE
Hardcoded exception message

### ISSUE THREAD

**Issue by sv3tli0** [laravel/framework#25339] opened 2018-08-26 08:55 UTC
https://github.com/laravel/framework/blob/4c0f7abdcc3ddbc4eac8694e793dc91cba548c85/src/Illuminate/Validation/ValidationException.php#L56

We are at the same time unable to set proper exception message, translate it or what ever and by default it is not changable.
A good option is to make that message translatable or some how setable.

**Comment by alexleeelkins** [comment] 2018-08-27 18:37
You are able to set validation exception messages via the public static function withMessages. An example of this can be found @ https://stackoverflow.com/a/47223679

**Comment by sv3tli0** [comment] 2018-08-27 20:44
It is not about the error messages > 
If you have created custom Request lets say for Contact form, on failed validation this exception message is added to the response "The given data was invalid.". 

> {"message":"The given data was invalid.", "errors":{}}

**Comment by devcircus** [comment] 2018-08-27 21:47
It's been discussed a few  times here, and so far, a few workarounds have been suggested, such as [this one](https://github.com/laravel/framework/issues/21059#issuecomment-350793827). There's also been a [few pull requests](https://github.com/laravel/framework/pulls?q=is%3Apr+validationexception+message+is%3Aclosed) to change the behavior, but none merged.

**Comment by kjdion84** [comment] 2018-09-03 23:53
Someone get Scooby Doo on this case. Makes zero sense why something like this would be hard-coded (and as a constructor parameter at that) when extreme care and flexibility in other aspects of the framework exist.

**Comment by laurencei** [comment] 2018-09-18 01:17
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Closed by laurencei** 2018-09-18 01:17 UTC

**Comment by sv3tli0** [comment] 2018-09-18 04:57
This is not an idea.. 
In case you have a non english API sending this automatic hardcoded message by default is an issue !

**Comment by laurencei** [comment] 2018-09-18 07:33
Its not a bug, it's a design decision. You are more than welcome to submit a PR to allow that exception to be translated like the others 😄

**Comment by kjdion84** [comment] 2018-09-18 08:43
It's not a design decision, it's what appears to be a temporary quick fix to a problem that came up while working on it. Using a hard-coded language string in a constructor is probably the worst thing I've seen in this framework, and it appears to be due to the limitations of another package.

Here are some PR's that have been outright closed:

https://github.com/laravel/framework/pull/22112
https://github.com/laravel/framework/pull/22045

Taylor said:

> We can't use a foundation helper from a component.

Which confirms everything I've stated.
