### ISSUE TITLE
Register anonymous components from a package

### ISSUE THREAD

**Issue by devfaysal** [laravel/framework#32154] opened 2020-03-29 00:51 UTC
- Laravel Version: 7.3.0

### Description:
If I have a package that has some anonymous components, the only way I can make them available is to create a class for them and register them individually. There is no way to register anonymous components without writing a class for it.

For reference,
`spatie/laravel-blade-x` had `BladeX::component('components.myAlert');` to register a component which is just a blade file.

**Comment by mojtabaahn** [comment] 2020-03-29 06:43
+1

**Comment by driesvints** [comment] 2020-03-30 08:29
I actually had to do this yesterday myself and it's easier than having to create a class for it. 

First you'll have to place your components in a `views` directory in your package. Then you load those views in the boot method of your service provider:

```php
$this->loadViewsFrom(__DIR__.'/../views', 'package-name');
```

Notice the "package-name" name there. You can now use these to register the components in your service provider:

```php
Blade::component('package-name::your-component', 'your-component');
```

No class needed. I've been thinking of maybe doing some auto loading so the `package-name::` notation works out of the box:

```blade
<x:package-name::your-component/>
```

Which could be cool. Anyway, that's a feature request and not a bug so closing this.

**Closed by driesvints** 2020-03-30 08:29 UTC

**Comment by devfaysal** [comment] 2020-03-30 11:30
@driesvints Thank you very much.
Yeah `<x:package-name::your-component/>` would be great, but your current solution is also good.

I think your solution can be added to the documentation. I found few more people were looking for this too.

**Comment by driesvints** [comment] 2020-03-31 10:44
@devfaysal feel free to send in a pr.

**Comment by devfaysal** [comment] 2020-03-31 11:04
Thanks. Done https://github.com/laravel/docs/pull/5929

**Comment by gavinhewitt** [comment] 2020-05-18 01:13
> I actually had to do this yesterday myself and it's easier than having to create a class for it.
> 
> First you'll have to place your components in a `views` directory in your package. Then you load those views in the boot method of your service provider:
> 
> ```
> $this->loadViewsFrom(__DIR__.'/../views', 'package-name');
> ```
> 
> Notice the "package-name" name there. You can now use these to register the components in your service provider:
> 
> ```
> Blade::component('package-name::your-component', 'your-component');
> ```
> 
> No class needed. I've been thinking of maybe doing some auto loading so the `package-name::` notation works out of the box:
> 
> ```
> <x:package-name::your-component/>
> ```
> 
> Which could be cool. Anyway, that's a feature request and not a bug so closing this.

@driesvints 
Does not seem to be working for me. Did everything as described but keep getting "Unable to locate class or view" :-(

**Comment by driesvints** [comment] 2020-05-18 10:58
@gavinhewitt works fine for me. Share some code?

**Comment by gavinhewitt** [comment] 2020-05-18 19:32
@driesvints Umm yeah, it works. Turns out it was an incomplete path that I somehow missed. Whoops! ;-)

Thanks!

**Comment by Butochnikov** [comment] 2020-07-02 23:13
@driesvints
i try
```php
$this->loadViewsFrom(__DIR__.'/../Views', 'admin');
...
<x:admin::test/>
```
but not working
`Unable to locate a class or view for component [admin::test]`

**Comment by driesvints** [comment] 2020-07-03 10:29
@Butochnikov you need to use `Blade::component`. See https://github.com/laravel/framework/issues/32154#issuecomment-605858282

**Comment by Butochnikov** [comment] 2020-07-03 10:58
@driesvints 
But how to automatically register all the components from the package folder?

**Comment by driesvints** [comment] 2020-07-03 10:59
That's not possible atm.
