### ISSUE TITLE
Str::afterLast()

### ISSUE THREAD

**Issue by m8d3** [laravel/framework#31085] opened 2020-01-09 14:28 UTC
- Laravel Version: v6.10.1
- PHP Version: 7.2

### Description:
I think there is a bug in Str::afterLast(). 

### Steps To Reproduce:
The statement `Str::afterLast('----Foo','---')` delivers "-Foo" instead of "Foo".

**Comment by devcircus** [comment] 2020-01-09 14:42
Which, to me, would be correct. Explain your expectation. 
It says "give me everything after the last occurrence of "---". Which in the given case, is "-Foo"

**Comment by m8d3** [comment] 2020-01-09 14:48
strpos 0: -
strpos 1: -
strpos 2: -
strpos 3: -
strpos 4: F
strpos 5: o
strpos 6: o

My expectation is, that the last occurrence of "---" is at strpos 1-3. So the Result has to be "Foo".

**Comment by 36864** [comment] 2020-01-09 14:58
This does indeed look odd.

I would expect `Str::afterLast($subject, $search)` to be the equivalent of `substr($string, strrpos($string, $search) + strlen($search))`. Instead, it explodes the string by search and then returns the last part.

This is only a problem when the search string is only one character and there is a sequence of the same character in the subject string of a length that is not a multiple of the search string's length.

**Comment by driesvints** [comment] 2020-01-09 15:08
This works as expected.

**Comment by devcircus** [comment] 2020-01-09 19:53
Definitely see the issue now upon further inspection. 🤷🏻‍♂️

**Comment by m8d3** [comment] 2020-01-10 07:53
@devcircus Could you please explain, why the last occurrence of "---" is not at strpos 1-3?

**Comment by m8d3** [comment] 2020-01-10 08:01
@driesvints Could you please explain, why the last occurrence of "---" is not at strpos 1-3?

**Comment by narwy** [comment] 2020-01-10 11:00
> Which, to me, would be correct. Explain your expectation.
> It says "give me everything after the last occurrence of "---". Which in the given case, is "-Foo"

@devcircus This is how it's intended to be built and used if I believe. It's easy to understand and work that way.

**Comment by driesvints** [comment] 2020-01-10 11:36
Hmm, you're indeed correct. I misread this. Wondering what's causing this.

**Comment by 36864** [comment] 2020-01-10 11:45
I tried to explain the cause in my first post.

The current implementation explodes the string using the search string as a delimiter. This works fine for almost all cases.

It only breaks when the search string is a sequence of the same character and there is a sequence of that character of length greater than the search string and not a multiple of the length of the search string, because the string explodes on the *first* occurrence of the search string. `----Foo` explodes into `[ '', '-Foo']`.

For the example being used here, the search string `--` would work fine, because the length of the sequence `----` in `----Foo` is a multiple of the length of `--`.

If we want to fix this edge case, `Str::last` could just return `substr($string, strrpos($string, $search) + strlen($search))`. I don't know the performance impact.

**Comment by driesvints** [comment] 2020-01-10 12:09
I tried `substr($string, strrpos($string, $search) + strlen($search))` but that breaks some of the other use cases unfortunately.

**Comment by driesvints** [comment] 2020-01-10 12:16
I've sent in a fix for this. Thanks for reporting 👍

**Closed** 2020-01-10 14:30 UTC
Labels: bug
