### ISSUE TITLE
withCount() on belongsToMany will include Pivot table

### ISSUE THREAD

**Issue by manmohanjit1** [laravel/framework#15204] opened 2016-09-01 12:36 UTC
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Builder.php#L1050

I'm using many-to-many relationship with belongsToMany() on both models.

**TLDR:**
withCount vs with gives me two different results
https://gist.github.com/manmohanjit1/6662ad8060c1f2b202f6798a32cd3691

When I use withCount(['relation']), it includes relation_count and also all the Pivot table values in the same object. However when I use with(['relation']) it puts the Pivot table values in a separate variable in the object as how it's documented.

In my User model:

`return $this->belongsToMany('App\Bibliography')->withTimestamps()->withPivot('is_admin', 'can_create', 'can_update', 'can_destroy')`

Is this intended behavior?

`$bibs = $user->bibliographies()->withCount(['users'])->get();`

vs

`$bibs = $user->bibliographies()->with(['users'])->get();`

https://gist.github.com/manmohanjit1/6662ad8060c1f2b202f6798a32cd3691

I was just curious if this was an bug or is intended behavior, thanks!

**Comment by acasar** [comment] 2016-09-01 19:35
I think this is not intended, only total count should be attached to the model. Any idea why this happens @barryvdh?

**Comment by srmklive** [comment] 2016-09-02 06:50
Yeah i agree. Only total count should be attached.

**Comment by barryvdh** [comment] 2016-09-02 06:51
Sorry, no idea. It's not intended behaviour imho. Perhaps because of the `select(['*'])`, but I'm not sure.

**Comment by manmohanjit1** [comment] 2016-09-05 13:33
It's overwritting the parents values

**Comment by srmklive** [comment] 2016-09-13 15:49
I can't seem to replicate the issue @manmohanjit1 has reported here. I created a database with some tables having the following relationship between them:

* A category has many posts.
* A post has many tags.
* A tag has many posts.

When i write the following code:

        $category = \App\Category::with(['posts'])->find(5);
        dd($category->posts()->withCount('tags')->first()->toArray());

I get the following sample output:

```
array:8 [▼
  "id" => 1
  "category_id" => 5
  "title" => "Edwardo Gislason"
  "slug" => "edwardo-gislason"
  "body" => "Nemo ipsam molestiae velit laudantium maiores sit aut. Magni possimus repellat eum ut perspiciatis similique. Ipsa officia modi illo sequi."
  "created_at" => "2016-09-13 14:28:53"
  "updated_at" => "2016-09-13 14:28:53"
  "tags_count" => 5
]        
```
I belive `withCount` exhibits the exact behavior what it is supposed to do.

**Comment by manmohanjit1** [comment] 2016-09-15 01:40
Hmm it looks like it's only happening if I use the method injection for Request. So for example:

    
    public function index(Request $request)
    {
		$user = $request->user();
		
		// this would reproduce it
		$notes1 = $user->notes()->withCount(['users'])->get();
		$notes2 = $user->notes()->with(['users'])->get();
		
		// this wouldn't
		$notes3 = \App\Note::withCount(['users'])->find($user->id);
		$notes4 = \App\Note::with(['users'])->find($user->id);

        return [$notes1, $notes2];
    }

Results 1 (using the `$user` variable: `$notes1` and `$notes2`)

    [
       [
          {
             "id":2,
             "created_at":"2016-09-15 01:18:17",
             "updated_at":"2016-09-15 01:18:17",
             "name":"Laurianne Corkery",
             "user_id":2,
             "note_id":2,
             "can_update":1,
             "can_destroy":1,
             "users_count":1,
             "pivot":{
                "user_id":2,
                "note_id":2,
                "can_update":1,
                "can_destroy":1
             }
          }
       ],
       [
          {
             "id":2,
             "created_at":"2016-09-15 01:18:17",
             "updated_at":"2016-09-15 01:18:17",
             "name":"Laurianne Corkery",
             "pivot":{
                "user_id":2,
                "note_id":2,
                "can_update":1,
                "can_destroy":1
             },
             "users":[
                {
                   "id":2,
                   "name":"Desiree Roberts",
                   "email":"xaufderhar@example.com",
                   "created_at":"2016-09-15 01:18:17",
                   "updated_at":"2016-09-15 01:18:17",
                   "pivot":{
                      "note_id":2,
                      "user_id":2,
                      "can_update":1,
                      "can_destroy":1
                   }
                }
             ]
          }
       ]
    ]
    
Result 2 (directly searching from the model: `$notes3` and `$notes4`)

    [
       {
          "id":2,
          "created_at":"2016-09-15 01:18:17",
          "updated_at":"2016-09-15 01:18:17",
          "name":"Laurianne Corkery",
          "users_count":1
       },
       {
          "id":2,
          "created_at":"2016-09-15 01:18:17",
          "updated_at":"2016-09-15 01:18:17",
          "name":"Laurianne Corkery",
          "users":[
             {
                "id":2,
                "name":"Desiree Roberts",
                "email":"xaufderhar@example.com",
                "created_at":"2016-09-15 01:18:17",
                "updated_at":"2016-09-15 01:18:17",
                "pivot":{
                   "note_id":2,
                   "user_id":2,
                   "can_update":1,
                   "can_destroy":1
                }
             }
          ]
       }
    ]

**Comment by manmohanjit1** [comment] 2016-09-15 01:43
This also seems to reproduce it:

		$notes1 = \App\User::find($user->id)->notes()->withCount(['users'])->get();

**Comment by srmklive** [comment] 2016-09-15 06:05
@manmohanjit1 What you are referencing is that a user has many notes whereas a note has many users. To me that is utterly wrong. The logical representation should be:

* A user has many notes.
* A note belongs to a user.
* A note has many revisions.
* A revision belongs to a note

If what you are referencing is incorrect in the first place, then there is nothing wrong with Eloquent. Its an issue with database representation that you have setup.

**Comment by Dylan-DPC** [comment] 2017-10-10 22:16
@manmohanjit1 Does this behaviour persist on 5.5? If it doesn't then you can close this issue.

**Comment by themsaid** [comment] 2017-11-29 11:41
Closing for lack of activity, please report if issue still exists in 5.5

**Closed by themsaid** 2017-11-29 11:41 UTC
