### ISSUE TITLE
Infinite loop when a model is updated in an event listener, and that event is cuased by a preceding update on that same model.

### ISSUE THREAD

**Issue by matthewgoslett** [laravel/framework#23973] opened 2018-04-23 10:22 UTC
- Laravel Version: 5.6.12
- PHP Version: docker image php:7.1-fpm-alpine
- Database Driver & Version: docker image mysql:5.7

### Description:

When a model is updated in an event listener, and that event is caused by a preceding update on that same model, an infinite loop occurs.
This is only the case when the event listener runs synchronously, not asynchronously on a queue.

### Steps To Reproduce:

1. Create a dummy model.

In the model, listen for a model updated event; and if the "status" attribute changes, trigger a `MyModelStatusChangedEvent` event.

App\Models\MyModel.php
```php
<?php

namespace App\Models;

use App\Events\MyModelStatusChangedEvent;
use Illuminate\Database\Eloquent\Model;

class MyModel extends Model
{
    public static function boot()
    {
        static::updated(function (MyModel $model) {
            if ($model->isDirty('status')) {
                event(
                    new MyModelStatusChangedEvent(
                        $model,
                        $model->getOriginal('status'),
                        $model->status
                    )
                );
            }
        });

        parent::boot();
    }
}
```

App\Events\MyModelStatusChangedEvent.php
```php
<?php

namespace App\Events;

use App\Models\MyModel;
use Illuminate\Queue\SerializesModels;
use Illuminate\Foundation\Events\Dispatchable;

class MyModelStatusChangedEvent
{
    use Dispatchable, SerializesModels;

    /**
     * @var MyModel
     */
    public $model;

    /**
     * @var string
     */
    public $oldStatus;

    /**
     * @var string
     */
    public $newStatus;

    /**
     * @param MyModel $model
     * @param string $oldStatus
     * @param string $newStatus
     */
    public function __construct(MyModel $model, $oldStatus, $newStatus)
    {
        $this->model = $model;
        $this->oldStatus = $oldStatus;
        $this->newStatus = $newStatus;
    }
}
```

2. Create a listener which triggers an update to the same model when the status changes to 'APPROVED'.

App\Listeners\TouchMyModelStatusChangedDate.php
```php
<?php

namespace App\Listeners;

use App\Events\MyModelStatusChangedEvent;

class TouchMyModelStatusChangedDate
{
    /**
     * Handle the event.
     *
     * @param MyModelStatusChangedEvent $event
     */
    public function handle(MyModelStatusChangedEvent $event)
    {
        if ($event->oldStatus === 'APPROVED') {
            \Log::info('Updating blah to bleh after status change to APPROVED.');
            $event->model->update(['blah' => 'bleh']);
        }
    }
}
```

3. In your `EventServiceProvider.php`, bind the listener to the event:
```php
/**
 * The event listener mappings for the application.
 *
 * @var array
 */
protected $listen = [
    // ....

    MyModelStatusChangedEvent::class => [
        TouchMyModelStatusChangedDate::class,
    ],
];
```

4. Trigger an update to the status of a dummy model.
```php
$model = \App\Models\MyModel::find(1);
$model->update(['status' => 'APPROVED']);
```

You would expect the listener to trigger a single update, but it fires multiple times.
This is because the update happens in a listener, on the same model, between the model firing the "updated" event and a call to both `syncChanges` and `syncOriginal`.

The `status` field is seen as dirty in the 2nd update `$event->model->update(['blah' => 'bleh'])`, even though it's already been updated, so this causes a subsequent `MyModelStatusChangedEvent` to fire, and so on...

**Comment by matthewgoslett** [comment] 2018-04-24 08:08
It feels weird that this is expected behaviour?

I would expect this behaviour on an `updating` event, as the entity isn't updated yet.  In `updated`, the data should no longer be dirty.

**Comment by themsaid** [comment] 2018-04-24 16:54
Closing as it's the expected behaviour.

**Closed by themsaid** 2018-04-24 16:54 UTC

**Comment by royduin** [comment] 2019-07-13 13:21
How did you fix this @matthewgoslett?

**Comment by matthewgoslett** [comment] 2019-07-13 16:11
> How did you fix this @matthewgoslett?

There's no pretty solution here unfortunately.

Here's a snippet from a current code base which prevents this unexpected behaviour.

<img width="595" alt="screenshot_1363" src="https://user-images.githubusercontent.com/1571743/61173884-74d1da00-a599-11e9-876b-32cc22942e5b.png">

I do a `clone` and `syncOriginal` on the cloned event, which then gets passed to custom events.

**Comment by ijasxyz** [comment] 2021-08-31 12:06
A workaround I grabbed from the latest version of Laravel.  Please note the example is based on the solution for my problem.

Add this to the base model.

`public static function withoutEvents (callable $callback)
  {
      $dispatcher = static::getEventDispatcher();
  
      if ($dispatcher) {
          static::unsetEventDispatcher();
      }
  
      try {
          return $callback();
      } finally {
          if ($dispatcher) {
              static::setEventDispatcher($dispatcher);
          }
      }
  }`

Use above as,

` static::saved(function (Leads $lead) {
    static::withoutEvents(function() use($lead){
        $lead->quotation_no = Leads::quotationNo($lead);
        $lead->save();
    });
});`

**Comment by ijasxyz** [comment] 2022-03-21 20:03
@techdaddies-kevin Np.

**Comment by bert-w** [comment] 2022-04-15 22:25
Interesting. I just came across this "intended behaviour" as well. I knew of the obvious issue of calling `update()` inside a `static::updating(...)` hook, but it still does not make sense to me why an infinite-loop happens inside `static::updated` hook, because I expect that hook to have completed the update-task.

That being said, the `static::updated` hook can also freely use `$model->isDirty()` but that's strange since at that moment it's not actually dirty anymore. It would need a `$model->wasDirty('someprop')` function to be completely clear, but that will undoubtedly overcomplicate things.

Note to self in the future:
- If you are going to call `update()` inside a `static::updated` hook, you can probably just move the logic and "set" the properties (`$user->username = 'Foobar'`) in the `static::update` hook. This also saves a query.

**Comment by al33mahmad1** [comment] 2022-09-24 00:54
Thank you @ijasxyz for the solution. I was about to write a custom query to update the record which would also have avoided the update event of laravel.
