### ISSUE TITLE
Carbon::setTestNow ignored during validation

### ISSUE THREAD

**Issue by CSigelmann** [laravel/framework#19520] opened 2017-06-07 18:55 UTC
- Laravel Version: 5.4.25
- PHP Version: 5.6.30

### Description:
There are a few places where strtotime() is used in Laravel, for example in getDateTimestamp in ValidatesAttributes.php. This makes it so that Carbon::setTestNow() is ignored for validation. 

I feel like this should be changed in a similar manner to https://github.com/laravel/framework/pull/15544

### Steps To Reproduce:
```
Carbon::setTestNow(Carbon::parse('2000-01-01', 'UTC'));
$validator = Validator::make(['date' => '2005-06-06 12:00:00Z'], ['date' => 'after:now']);
dd($validator->errors()->all()); // "The date must be a date after now."
```

**Comment by themsaid** [comment] 2017-06-07 18:58
Feel free to open a PR :)

Closing since it's not a bug report but rather a change request, we're open to PRs on this.

**Closed by themsaid** 2017-06-07 18:58 UTC
