### ISSUE TITLE
[5.3] Need to add markAsUnRead() method in DatabaseNotification model

### ISSUE THREAD

**Issue by DesmondPang** [laravel/framework#15035] opened 2016-08-25 09:11 UTC
There is a markAsRead() method in the DatabaseNotification but I suggest that you can add the markAsUnRead() method to toggle that state. Thanks

**Comment by themsaid** [comment] 2016-09-05 21:25
We're open to Pull Requests. Closing this since it's not a bug report, but please feel free to continue discussions in the [Internals Repository](https://github.com/laravel/internals)

**Closed by themsaid** 2016-09-05 21:25 UTC
