### ISSUE TITLE
Method "extension" provides incorrect information for uploaded HTML file on Chrome

### ISSUE THREAD

**Issue by raffLHS** [laravel/framework#20210] opened 2017-07-21 17:51 UTC
- Laravel Version: 5.3.31
- PHP Version: 7.0.16 (cli)
- Database Driver & Version: N/A

### Description:

Client OS: Windows 10
Client Browser: Chrome 59.0.3071.115 (Official Build) (64-bit)

Obtaining a file from an upload HTML form.
Method "extension" provides incorrect information

This functionality works correctly on Ubuntu (Chrome and Firefox)

### Steps To Reproduce:

// retrieve uploaded file
// $request is an instance of "Request"
$file = $request->file('document_file');
error_log("FILE = ".$file->getClientOriginalName());
error_log("document_file extension = ".$request->file('document_file')->extension());

// apache log
[Fri Jul 21 17:34:49.544657 2017] [:error] [pid 14178] [client ] FILE = **test.html**
[Fri Jul 21 17:34:49.546536 2017] [:error] [pid 14178] [client ] **document_file extension = txt**

**Comment by ankurk91** [comment] 2017-07-23 03:49
@raffLHS 

> Method "extension" provides incorrect information
And what is that ?

Apache log belongs to which platform ?

**Comment by sausin** [comment] 2017-07-23 20:46
@raffLHS The `extension()` method in `Illuminate\Http\FileHelpers` which refers to `guessExtension` in a Symfony component `Symfony\Component\HttpFoundation\File`

What it does is that it tries to guess the file extension based on file mimetype. This is to cover scenarios when the uploaded file may not have the "correct" extension and you may want to store it with the one that corresponds to the mimetype.

Now I have not checked into this thoroughly, but assuming it behaves similarly to `file` on linux, it will recognize both, a normal `text` file and an `html` file, as an 'ASCII text` type and hence suggest the `txt` extension. (note that the recognition is actually `HTML document, ASCII text`, but it probably just cares about the last part)

If you want to keep the extension of the uploaded file, you can just parse it from the filename of the uploaded file (with a simple regex looking for the last `.` and taking the remaining text as extension, for eg).

**Comment by themsaid** [comment] 2017-07-24 11:54
> What it does is that it tries to guess the file extension based on file mimetype. This is to cover scenarios when the uploaded file may not have the "correct" extension and you may want to store it with the one that corresponds to the mimetype.

This has been reported several times that it behaves differently on different environments, this is not a bug in the framework itself and for that reason I'm going to close this issue. Please search the issues history to find more information.

**Closed by themsaid** 2017-07-24 11:54 UTC
