### ISSUE TITLE
TokenMismatchException in Microsoft edge browser

### ISSUE THREAD

**Issue by basherr** [laravel/framework#10846] opened 2015-11-07 09:29 UTC
The edge browser throws error on TokenMismatchException on form submission.

**Comment by GrahamCampbell** [comment] 2015-11-07 09:55
Duplicate of the internet explorer issues.

**Comment by GrahamCampbell** [comment] 2015-11-07 09:56
Using a session driver like redis and making sure there are no 404 requests on page load usually fix this.

**Closed** 2015-11-07 09:55 UTC
