### ISSUE TITLE
updated_at ambiguous on using delete() on hasManyThrough relation with softDeletes

### ISSUE THREAD

**Issue by funyug** [laravel/framework#15798] opened 2016-10-07 07:37 UTC
- Laravel Version: 5.1.45
- PHP Version: 7.0.1
- Database Driver & Version:
Mysql

### Description:
You receive an error that the updated_at field is ambiguous while running a delete() function on a hasManyThrough relationship having softDelete.

### Steps To Reproduce:
Create a hasManyThrough relationship on a model. For eg.

Make a function in the model User.php 

public function commuteDistances() {
return $this->hasManyThrough('App\Models\CommuteDistance','App\UserPropertyListing','user_id','user_property_listing_id','id');
}

Try running
$user->commuteDistances()->delete();

The query generated is 
update `commute_distances` inner join `user_property_listings` on `user_property_listings`.`id` = `commute_distances`.`user_property_listing_id` set `commute_distances`.`deleted_at` = 2016-10-07 15:33:41, `updated_at` = 2016-10-07 15:33:41 where `commute_distances`.`deleted_at` is null and `user_property_listings`.`deleted_at` is null and `user_property_listings`.`user_id` = 3

Error
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'updated_at' in field list is ambiguous

**Comment by themsaid** [comment] 2016-10-12 08:30
Duplicate of https://github.com/laravel/framework/issues/13909

**Closed by themsaid** 2016-10-12 08:30 UTC
