### ISSUE TITLE
Generating many queries into database

### ISSUE THREAD

**Issue by ax-ross** [laravel/framework#46275] opened 2023-02-25 23:03 UTC
- Laravel Version: 10.1.4
- PHP Version: 8.1.16
- Database Driver & Version: Mysql 8

### Description:
I have 2 models: User and Course. User have one of two roles - student or teacher.
Course have 2 relationships with User:
1. One to Many relationship. User with role teacher can have many courses. In my courses table I have FK teacher_id and in my models I have hasMany and belongsTo relationships;
2. Many to Many relationship. User with role student can learn on many courses and on one course can be many students. I have pivot table course_student w/o additional field expect id, course_id and student_id. In my models I have belongsToMany relationships.

I have CourseSeeder (see screenshot) where I create 5 teachers and 20 student, then I create 10 courses and associate courses with teachers. Next step I attach 20 student to every course. I have two way to implement this:
Way 1:
For attaching students to courses I use foreach loop and attach() method of belongsToMany relationship where I pass array of student ids. This way seemed me so-so. And I read docs and tried to improve code.
Way 2:
I use method hasAttached of factory for attaching students to courses. 
**NB!** I can't use has method for 2 reasons: 
first, I can't pass into has method collection, only factory
second, most important, I can't pass my relationship name (in my case many to many relationship between user and course model name course_student, not course_user).
I'm not sure that if I use has method instead of hasAttached method my problem was resolved, but I decided to describe this point.

Now, I describe problem: 
I have same good result from both ways. But second way spending much more time. And I found why. 
In first way I have 50 queries into db like: 
insert into
  `course_student` (`course_id`, `user_id`)
values
  (50, 6),
  (50, 7),
  (50, 8),
  (50, 9),
  (50, 10),
  (50, 11),
  (50, 12),
  (50, 13),
  (50, 14),
  (50, 15),
  (50, 16),
  (50, 17),
  (50, 18),
  (50, 19),
  (50, 20),
  (50, 21),
  (50, 22),
  (50, 23),
  (50, 24),
  (50, 25)
In second way I have 1000 queries (20 * 50) like:
insert into
  `course_student` (`course_id`, `user_id`)
values
  (50, 25)

insert into
  `course_student` (`course_id`, `user_id`)
values
  (50, 24)

etc.

It's so bad for performance and I think it possible to fix. 
![image](https://user-images.githubusercontent.com/103892341/221383561-f4db4f80-7798-4e9e-a835-d89e8e25a4e1.png)

**Comment by Mdhesari** [comment] 2023-02-26 14:03
steps to reproduce : ?!

**Comment by rodrigopedra** [comment] 2023-02-26 20:21
First, please use backticks when posting code, not screenshots. Not everyone uses the same theme as you, and they become hard to read on a mobile device, but mainly, are impossible to copy and paste to do any test.

If you don't know how to properly format code, please refer to this post from GitHub:

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

It is not clear what the issue is, steps to reproduce is missing, and poor performance (debatable from the referred data size)  on a seeder is not a big deal, as seeders are not actually production code.

It seems, to me, you are after advice on how to improve your code and not reporting an issue.

If that is the case, please ask for help in one of the discussion forums, as highlighted on the official docs:

> Laravel's GitHub issue trackers are not intended to provide Laravel help or support. Instead, use one of the following channels:

see: https://laravel.com/docs/10.x/contributions#support-questions

If that is not the case, please apologize. I'd try to better clarify why you think this is an issue that should be fixed in the framework level. And, if possible, please suggest a solution you consider feasible.

Lastly, as @Mdhesari already suggested, the "steps to reproduce" is missing. A screenshot that one should retype character by character, and a high level description, are not easy, nor motivating, for one chiming in to help you out.

If possible, create a public repo that is easy for one to clone and clearly reproduce the issue. As it is suggested on the issue template.

**Comment by ax-ross** [comment] 2023-02-26 20:31
> First, please use backticks when posting code, not screenshots. Not everyone uses the same theme as you, and they become hard to read on a mobile device, but mainly, are impossible to copy and paste to do any test.
> 
> If you don't know how to properly format code, please refer to this post from GitHub:
> 
> https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
> 
> It is not clear what the issue is, steps to reproduce is missing, and poor performance (debatable from the referred data size) on a seeder is not a big deal, as seeders are not actually production code.
> 
> It seems, to me, you are after advice on how to improve your code and not reporting an issue.
> 
> If that is the case, please ask for help in one of the discussion forums, as highlighted on the official docs:
> 
> > Laravel's GitHub issue trackers are not intended to provide Laravel help or support. Instead, use one of the following channels:
> 
> see: https://laravel.com/docs/10.x/contributions#support-questions
> 
> If that is not the case, please apologize. I'd try to better clarify why you think this is an issue that should be fixed in the framework level. And, if possible, please suggest a solution you consider feasible.
> 
> Lastly, as @Mdhesari already suggested, the "steps to reproduce" is missing. A screenshot that one should retype character by character, and a high level description, are not easy, nor motivating, for one chiming in to help you out.
> 
> If possible, create a public repo that is easy for one to clone and clearly reproduce the issue. As it is suggested on the issue template.

It's for reproduce:
1. git clone https://github.com/ax-ross/laravel_issue_demo_project.git
2. cd laravel_issue_demo_project
3. composer install
4. cp .env.example .env
5. php artisan migrate (answer yes when you will see Would you like to create it or create database.sqlite manually)
6. php arisan serve (for telescope)
7. In another terminal:
php artisan db:seed --class=FastCourseSeeder 
now go http://127.0.0.1:8001/telescope/queries and count queries (around 4 pages of queries)

php artisan migrate:fresh
php artisan db:seed --class=SlowCourseSeeder
now go http://127.0.0.1:8001/telescope/queries and count queries (many pages of queries and time high diff) 

Reason of this diff I described in description section, hasAttached generating many queries.

and poor performance (debatable from the referred data size) on a seeder is not a big deal, as seeders are not actually production code - if you think so, it's really not important, but I think time which developers spending for testing and seeding also important.

For example, can allow to pass relation name for has() method of factory (not sure that it will help), or create new method for factory which can attach models collection (or array of model ids) in one query.

**Comment by rodrigopedra** [comment] 2023-02-26 21:07
```php
<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::factory()
            ->count(5)
            ->teacher()
            ->has(Course::factory()->count(10))
            ->create();

        $students = User::factory()
            ->count(20)
            ->student()
            ->create();

        // skip if your pivot does not uses timestamps
        $now = now()->toDateTimeString();

        $pairs = collect($students->modelKeys())
            ->crossJoin(Course::all()->modelKeys())
            ->map(fn ($record) => [
                'user_id' => $record[0],
                'course_id' => $record[1],

                // skip if your pivot does not uses timestamps
                'created_at' => $now,
                'updated_at' => $now,
            ]);

        DB::table('course_user')->insert($pairs->all());
    }
}
```

Before (using slightly modified way 1, see code below)

```bash
$ time php artisan migrate:fresh --seed

  Dropping all tables ..................................................................................................................... 6ms DONE

   INFO  Preparing database.  

  Creating migration table ................................................................................................................ 3ms DONE

   INFO  Running migrations.  

  2014_10_12_000000_create_users_table .................................................................................................... 3ms DONE
  2014_10_12_100000_create_password_reset_tokens_table .................................................................................... 1ms DONE
  2019_08_19_000000_create_failed_jobs_table .............................................................................................. 3ms DONE
  2019_12_14_000001_create_personal_access_tokens_table ................................................................................... 4ms DONE
  2023_02_26_202355_create_courses_table .................................................................................................. 4ms DONE
  2023_02_26_202438_create_enrollments_table .............................................................................................. 2ms DONE

   INFO  Seeding database.  


real    0m1,354s
user    0m0,356s
sys     0m0,137s
```

After (using code above)

```bash
$ time php artisan migrate:fresh --seed

  Dropping all tables ..................................................................................................................... 6ms DONE

   INFO  Preparing database.  

  Creating migration table ................................................................................................................ 2ms DONE

   INFO  Running migrations.  

  2014_10_12_000000_create_users_table .................................................................................................... 3ms DONE
  2014_10_12_100000_create_password_reset_tokens_table .................................................................................... 1ms DONE
  2019_08_19_000000_create_failed_jobs_table .............................................................................................. 2ms DONE
  2019_12_14_000001_create_personal_access_tokens_table ................................................................................... 4ms DONE
  2023_02_26_202355_create_courses_table .................................................................................................. 3ms DONE
  2023_02_26_202438_create_course_user_table .............................................................................................. 1ms DONE

   INFO  Seeding database.  


real    0m0,379s
user    0m0,262s
sys     0m0,032s
```

Code used for way 1

```php
<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $teachers = User::factory()
            ->count(5)
            ->teacher()
            ->create();

        $students = User::factory()
            ->count(20)
            ->student()
            ->create();

        /** @var \App\Models\User $teacher */
        foreach ($teachers as $teacher) {
            $courses = $teacher->courses()->saveMany(Course::factory()->count(10)->make());

            /** @var \App\Models\Course $course */
            foreach ($courses as $course) {
                $course->students()->attach($students->modelKeys());
            }
        }
    }
}
```

**Comment by rodrigopedra** [comment] 2023-02-26 21:11
```php
<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::factory()
            ->count(5)
            ->teacher()
            ->has(Course::factory()->count(10))
            ->create();

        $students = User::factory()
            ->count(20)
            ->student()
            ->create();

        // skip if your pivot does not uses timestamps
        $now = now()->toDateTimeString();

        $pairs = collect($students->modelKeys())
            ->crossJoin(Course::all()->modelKeys())
            ->map(fn ($record) => [
                'user_id' => $record[0],
                'course_id' => $record[1],

                // skip if your pivot does not uses timestamps
                'created_at' => $now,
                'updated_at' => $now,
            ]);

        DB::table('course_user')->insert($pairs->all());
    }
}
```

Time with code above 

```bash
~/code/playground/issue-46275 $ rm storage/logs/*.log && time php artisan migrate:fresh --seed

  Dropping all tables ..................................................................................................................... 6ms DONE

   INFO  Preparing database.  

  Creating migration table ................................................................................................................ 2ms DONE

   INFO  Running migrations.  

  2014_10_12_000000_create_users_table .................................................................................................... 3ms DONE
  2014_10_12_100000_create_password_reset_tokens_table .................................................................................... 1ms DONE
  2019_08_19_000000_create_failed_jobs_table .............................................................................................. 2ms DONE
  2019_12_14_000001_create_personal_access_tokens_table ................................................................................... 4ms DONE
  2023_02_26_202355_create_courses_table .................................................................................................. 3ms DONE
  2023_02_26_202438_create_course_user_table .............................................................................................. 1ms DONE

   INFO  Seeding database.  


real    0m0,339s
user    0m0,240s
sys     0m0,025s
```

Time with code based on way 1 (see code below)

```bash
$ time php artisan migrate:fresh --seed

  Dropping all tables ..................................................................................................................... 5ms DONE

   INFO  Preparing database.  

  Creating migration table ................................................................................................................ 3ms DONE

   INFO  Running migrations.  

  2014_10_12_000000_create_users_table .................................................................................................... 3ms DONE
  2014_10_12_100000_create_password_reset_tokens_table .................................................................................... 1ms DONE
  2019_08_19_000000_create_failed_jobs_table .............................................................................................. 3ms DONE
  2019_12_14_000001_create_personal_access_tokens_table ................................................................................... 4ms DONE
  2023_02_26_202355_create_courses_table .................................................................................................. 3ms DONE
  2023_02_26_202438_create_course_user_table .............................................................................................. 1ms DONE

   INFO  Seeding database.  


real    0m1,511s
user    0m0,417s
sys     0m0,122s
```

```php
<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::factory()
            ->count(5)
            ->teacher()
            ->has(Course::factory()->count(10))
            ->create();

        $courses = Course::all();

        // skip if your pivot does not uses timestamps
        $now = now()->toDateTimeString();

        User::factory()
            ->count(20)
            ->student()
            ->hasAttached($courses, ['created_at' => $now, 'updated_at' => $now], 'course_user')
            ->create();
    }
}
```

**Comment by rodrigopedra** [comment] 2023-02-26 21:13
```php
<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::factory()
            ->count(5)
            ->teacher()
            ->has(Course::factory()->count(10))
            ->create();

        $students = User::factory()
            ->count(20)
            ->student()
            ->create();

        // skip if your pivot does not use timestamps
        $now = now()->toDateTimeString();

        $pairs = collect($students->modelKeys())
            ->crossJoin(Course::all()->modelKeys())
            ->map(fn ($record) => [
                'user_id' => $record[0],
                'course_id' => $record[1],

                // skip if your pivot does not use timestamps
                'created_at' => $now,
                'updated_at' => $now,
            ]);

        DB::table('course_user')->insert($pairs->all());
    }
}
```

Time with code above 

```bash
$ time php artisan migrate:fresh --seed

  Dropping all tables ..................................................................................................................... 6ms DONE

   INFO  Preparing database.  

  Creating migration table ................................................................................................................ 2ms DONE

   INFO  Running migrations.  

  2014_10_12_000000_create_users_table .................................................................................................... 3ms DONE
  2014_10_12_100000_create_password_reset_tokens_table .................................................................................... 1ms DONE
  2019_08_19_000000_create_failed_jobs_table .............................................................................................. 2ms DONE
  2019_12_14_000001_create_personal_access_tokens_table ................................................................................... 4ms DONE
  2023_02_26_202355_create_courses_table .................................................................................................. 3ms DONE
  2023_02_26_202438_create_course_user_table .............................................................................................. 1ms DONE

   INFO  Seeding database.  


real    0m0,339s
user    0m0,240s
sys     0m0,025s
```

Time with code based on way 1 (see code below)

```bash
$ time php artisan migrate:fresh --seed

  Dropping all tables ..................................................................................................................... 5ms DONE

   INFO  Preparing database.  

  Creating migration table ................................................................................................................ 3ms DONE

   INFO  Running migrations.  

  2014_10_12_000000_create_users_table .................................................................................................... 3ms DONE
  2014_10_12_100000_create_password_reset_tokens_table .................................................................................... 1ms DONE
  2019_08_19_000000_create_failed_jobs_table .............................................................................................. 3ms DONE
  2019_12_14_000001_create_personal_access_tokens_table ................................................................................... 4ms DONE
  2023_02_26_202355_create_courses_table .................................................................................................. 3ms DONE
  2023_02_26_202438_create_course_user_table .............................................................................................. 1ms DONE

   INFO  Seeding database.  


real    0m1,511s
user    0m0,417s
sys     0m0,122s
```

```php
<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::factory()
            ->count(5)
            ->teacher()
            ->has(Course::factory()->count(10))
            ->create();

        $courses = Course::all();

        // skip if your pivot does not use timestamps
        $now = now()->toDateTimeString();

        User::factory()
            ->count(20)
            ->student()
            ->hasAttached($courses, ['created_at' => $now, 'updated_at' => $now], 'course_user')
            ->create();
    }
}
```

**Comment by ax-ross** [comment] 2023-02-26 22:02
`$ time php artisan migrate:fresh --seed

  Dropping all tables ..................................................................................................................... 6ms DONE

   INFO  Preparing database.  

  Creating migration table ................................................................................................................ 2ms DONE

   INFO  Running migrations.  

  2014_10_12_000000_create_users_table .................................................................................................... 3ms DONE
  2014_10_12_100000_create_password_reset_tokens_table .................................................................................... 1ms DONE
  2019_08_19_000000_create_failed_jobs_table .............................................................................................. 2ms DONE
  2019_12_14_000001_create_personal_access_tokens_table ................................................................................... 4ms DONE
  2023_02_26_202355_create_courses_table .................................................................................................. 3ms DONE
  2023_02_26_202438_create_course_user_table .............................................................................................. 1ms DONE

   INFO  Seeding database.  


real    0m0,339s
user    0m0,240s
sys     0m0,025s`

It's great result. And it's a reason  why I created issue. It's impossible to achieve such performance using built-in Laravel methods for factory like hasAttached().

**Comment by rodrigopedra** [comment] 2023-02-26 22:14
I still don't think this is a problem that should be solved by the framework, it seems a user land use-case.

Better wait for the maintainers to chime in.

**Comment by driesvints** [comment] 2023-03-01 10:33
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Closed by driesvints** 2023-03-01 10:33 UTC
