### ISSUE TITLE
Attributes not specified in component constructor are not available inside the class

### ISSUE THREAD

**Issue by panda-madness** [laravel/framework#32497] opened 2020-04-22 19:38 UTC
- Laravel Version: 7.7.1
- PHP Version: 7.4.3
- Database Driver & Version: Not applicable

### Description:

Currently, if you create a class based Blade component and pass it attributes, only attributes specified in the class constructor are available from the class itself, and the rest only from the template via the `$attributes` bag. I would imagine that them being available at some point in the component's class would be the expected behavior.

### Steps To Reproduce:

Create a class component.

```blade
<div {{ $attributes }}>
    ...
</div>
```

```php
class TestSubject extends Component
{
    public function __construct()
    {
        dump($this->attributes); // produces null, should be ['test1' => 'asd', 'test2' => 'asdads' ...]
    }

    public function render()
    {
        dump($this->attributes); // still null
        return $this->view('components.test-subject');
    }
}
```

Attempt to insert it with any number of attributes:
```blade
<x-test-subject :test1="'asd'" test2="asdads" test3="asdads" />
```

**Comment by devcircus** [comment] 2020-04-22 21:19
Seems like that's how it is designed. If you pass something in, you must accept it. Same thing with vue. Passed props must be declared or they're not accessible.

**Comment by panda-madness** [comment] 2020-04-23 05:35
@devcircus Vue components have access to all attributes not specifically declared as props via `this.$attr` property. I'm looking for similar behavior here.

**Comment by devcircus** [comment] 2020-04-23 06:33
True, but I would still say that, as this was how the components were designed, accessing implicitly received attributes would be a feature request and not a bug report. Probably best to open an issue on the ideas repo and see what the community thinks, or try a PR.

**Comment by panda-madness** [comment] 2020-04-23 07:24
I've created a small PR to fix this issue: #32505

**Comment by driesvints** [comment] 2020-04-23 10:24
This isn't a bug so closing this. Let's see how the pr goes.

**Closed by driesvints** 2020-04-23 10:24 UTC

**Comment by samlovescoding** [comment] 2020-08-04 04:04
Attributes and slots should be available inside the component class.

**Comment by driesvints** [comment] 2020-08-04 09:18
@samlovescoding you can. If you return a closure from a component you'll get an array with:

1. Component name
2. Attributes
3. Slot

I'll send in a PR to document this.

```php
    public function render()
    {
        return function (array $data) {
            return view('components.foo');
        };
    }
```

**Comment by driesvints** [comment] 2020-08-04 09:35
CFR: https://github.com/laravel/docs/pull/6221

**Comment by earvinpiamonte** [comment] 2020-09-12 19:10
> @samlovescoding you can in a more recent Laravel version. If you return a closure from a component you'll get an array with:
> 
> 1. Component name
> 2. Attributes
> 3. Slot
> 
> I'll send in a PR to document this.
> 
> ```
>     public function render()
>     {
>         return function (array $data) {
>             return view('components.foo');
>         };
>     }
> ```

Hi @driesvints, I get an `ErrorException` in returning a view on a closure from a component's `render` method.

PHP version: 7.4.10
Laravel version: 8.0.3

### ErrorException
```
Illegal offset type in isset or empty (View: ../resources/views/welcome.blade.php)
```

### Component class
```
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Test extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return function (array $data) {
            return view('components.test');
           // return '<p>this works though</p>';
        };
    }
}
```

### Component view
```
<div style="color: red;">
    {{ $slot }}
</div>
```

### View
```
<x-test>Hello</x-test>
```

**Comment by earvinpiamonte** [comment] 2020-09-13 07:54
> @samlovescoding you can in a more recent Laravel version. If you return a closure from a component you'll get an array with:
> 
> 1. Component name
> 2. Attributes
> 3. Slot
> 
> I'll send in a PR to document this.
> 
> ```
>     public function render()
>     {
>         return function (array $data) {
>             return view('components.foo');
>         };
>     }
> ```

I get an exception in simply returning `view('components.foo')`. Passing the `$data` and chaining the `render()` method to get the view contents worked for me.

```php
public function render()
{
    return function (array $data) {
        return view('components.foo', $data)->render();
    };
}
```

**Comment by driesvints** [comment] 2020-09-13 18:22
@earvinpiamonte docs have been updated for that in the meantime already.

**Comment by bastinald** [comment] 2021-04-25 21:06
it would still be better if attributes were available in the class constructor so we could use them to set other property values.

e.g.:

```php
class Input extends Component
{
    public $model;

    public function __construct()
    {
        $this->model = $this->attributes->whereStartsWith('wire:model')->first();
    }

    public function render()
    {
        return <<<'HTML'
            <div class="mb-4 space-y-1">
                <input {{ 
                    $attributes->class([
                        'w-full placeholder-gray-400 rounded-lg',
                        'border-gray-400' => !$errors->has($model),
                        'border-red-600' => $errors->has($model),
                    ])->merge([
                        'type' => 'text',
                    ])
                }}>

                @error($model)
                    <p class="text-sm text-red-600">{{ $message }}</p>
                @enderror
            </div>
        HTML;
    }
}

```

**Comment by PH7-Jack** [comment] 2022-09-08 04:27
I believe if we have hooks into the component to be called after the attributes are set will be nice

@taylorotwell @driesvints I can create a PR to add a "init" or similar hook to be called after the attributes is set into the component, or add it into the constructor parameters via dependency injection. 

Another great feature is to add rendering events like livewire does
https://github.com/livewire/livewire/blob/master/src/Features/Placeholder.php#L13

example
```
Blade::listen('component.init', function ($component, $attributes) {
   // some stuff here
});

```
