### ISSUE TITLE
"the given data was invalid" is hard coded

### ISSUE THREAD

**Issue by kjdion84** [laravel/framework#25436] opened 2018-09-03 23:45 UTC
Wouldn't it make more sense to use trans() for this and include it in the default language files?

**Comment by staudenmeir** [comment] 2018-09-03 23:49
See #25339.

**Comment by lk77** [comment] 2018-09-07 15:14
If we could override it in custom requests, it will be cool.

In this moment the only workaround it's to override ValidationException by a custom one,
and overriding failedValidation in the form request

**Comment by laurencei** [comment] 2018-09-18 00:38
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Closed by laurencei** 2018-09-18 00:38 UTC

**Comment by lk77** [comment] 2018-09-18 07:35
Well,
for me this is clearly an issue,
since it's not the expected behaviour to have hard coded strings,
that can't be changed without overriding.
And it's not the only one, there is some hard coded strings elsewhere,
like in Response, with hardcoded status text.

**Comment by laurencei** [comment] 2018-09-18 07:51
Yep - so please feel free to create PR(s) that remove any hard coding to be translatable fields. You are welcome to submit them if/when you find any that you need to customize.

**Comment by kjdion84** [comment] 2018-09-18 08:44
https://github.com/laravel/framework/issues/25339#issuecomment-422308758
