### ISSUE TITLE
Table command tests will break

### ISSUE THREAD

**Issue by Brenneisen** [laravel/framework#29521] opened 2019-08-12 08:53 UTC
- Laravel Version: 5.8.29
- PHP Version: 7.3.7
- Database Driver & Version: MySQL 8.0

### Description:

After the commit 42c19bd tests like these will break:

```
$this->artisan('command:list')
            ->expectsOutput('+----+------+---------------+')
            ->expectsOutput('| ID | Name | Params        |')
            ->expectsOutput('+----+------+---------------+')
            ->expectsOutput('| 1  | Test | {"foo":"bar"} |')
            ->expectsOutput('+----+------+---------------+')
            ->assertExitCode(0);
```

### Steps To Reproduce:

Write a test for a command, which expects a table output:

```
$this->artisan('command:list')
            ->expectsOutput('+----+------+---------------+')
            ->expectsOutput('| ID | Name | Params        |')
            ->expectsOutput('+----+------+---------------+')
            ->expectsOutput('| 1  | Test | {"foo":"bar"} |')
            ->expectsOutput('+----+------+---------------+')
            ->assertExitCode(0);
```

**Comment by driesvints** [comment] 2019-08-12 10:20
Can you provide the `command:list` code as well?

**Comment by Brenneisen** [comment] 2019-08-12 13:18
Command Example:

```
use Illuminate\Console\Command;

class ListCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'command:list';

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $this->table(['ID', 'Name', 'Params'], [
            [1, 'Test', '{"foo":"bar"}'],
        ]);
    }
}
```

**Comment by driesvints** [comment] 2019-08-13 09:49
I can indeed reproduce this. From what I can tell it's probably best to revert it but that'll break the new behavior again.

**Comment by prwnr** [comment] 2019-08-15 07:23
This doesn't only affect table command tests, but other 'ordered' expected outputs as well.
We are facing a problem with commands tests after https://github.com/laravel/framework/commit/42c19bd4482ef1c2f850851cf607badeff111a8d . 

In our case it's a question that is being asked in a loop, so it can appear more than once in the output, but when the question is being expected for the second time, the test breaks.

```php
 $this->artisan('create:admin')
            ->expectsQuestion('Please provide name for your admin.', 'first')
            ->expectsOutput("Admin with 'first' name successfully created. Admin ID: 1")
            ->expectsQuestion('Would you like to create another admin?', true)
            ->expectsQuestion('Please provide name for your admin.', 'second')
            ->expectsOutput("Admin with 'second' name successfully created. Admin ID: 2")
            ->expectsQuestion('Would you like to create another admin?', false)
            ->assertExitCode(0);
```
So here the second 'Please provide name for your admin' will break the code due to mockery error: 
`Method Mockery_1_Illuminate_Console_OutputStyle::askQuestion(<Closure===true>)() called out of order: expected order 1, was 2`

**Comment by driesvints** [comment] 2019-08-15 11:45
@prwnr can you try with the patch provided by mohamed and let us know if that fixes your issues? https://github.com/laravel/framework/pull/29580

**Comment by prwnr** [comment] 2019-08-15 12:43
@driesvints works fine with my tests as it was working with v5.8.29 
I did additional test with the same question being asked 3 times, works regardless of how many times same question appears.

**Comment by driesvints** [comment] 2019-08-16 11:47
Mohamed's PR was merged and will be in the next minor release for Laravel.

**Closed by driesvints** 2019-08-16 11:47 UTC
Labels: bug
