### ISSUE TITLE
laravel dynamic route problem.

### ISSUE THREAD

**Issue by AGhasemzadeh** [laravel/framework#24479] opened 2018-06-06 09:15 UTC
- Laravel Version: 5.6.24
- PHP Version:7.2
- Database Driver & Version:MySQL

### Description:
I want to use route() helper to build dynamic menus.
when I use `route('user')` everything work when but when I use `route($routeName)` I build route url base on current url.
For example:
My current url is: https://shirazsoft.com/admin/   with route('user')  I get:  https://shirazsoft.com/user/
My current url is: https://shirazsoft.com/admin/   with `$routeName='user';` `route($routeName)`  I get:  https://shirazsoft.com/admin/user/

Both url() and route() and action() have problems.

**Comment by browner12** [comment] 2018-06-06 13:30
I am unable to duplicate.

Could you `echo` the value of `$routeName` after the method call to make sure it is passing in correctly?

Could you then go into the `UrlGenerator`, and make sure `$name` parameter is passing in correctly in both scenarios?

**Comment by AGhasemzadeh** [comment] 2018-06-06 15:42
@browner12 
Yes I could echo $routeName and output is `user`

**Comment by 36864** [comment] 2018-06-06 15:44
It'll be hard to determine what the problem is without your full controller code.

**Comment by browner12** [comment] 2018-06-06 15:47
I would suggest creating a new Laravel installation and testing this on that fresh install.  If you are unable to replicate the issue on there, I would guess this is some kind of problem specific to your application, and would suggest moving this discussion over to StackOverflow.

**Comment by AGhasemzadeh** [comment] 2018-06-06 15:47
@36864 
In AppServiceProvider.php I have View::share
``
        if (Schema::hasTable('menus')) {
            if(Cache::has('menus')) {
                $menus = Cache::get('menus');
            } else {
                $menus = Menu::active()->get();
                Cache::put('menus', $menus, now()->addMinutes(config('platform.menus-cache-time')));
            }
            View::share('menus', $menus);
        }
``
and in view I have:

``
                @foreach($menus as $menu)
                    @if($menu->position == 'navbar-bottom')
                        @if($menu->register == 'yes' && Auth::check())
                                @if($menu->register == 'route')
                                    <li><a class="nav-link{{ Route::currentRouteName() == $menu->route ? ' active' : '' }}" href="{{ route($menu->route) }}"><i class="{{ $menu->icon }}"></i> {{ $menu->title }}</a></li>
                                @else
                                    <li><a class="nav-link" href="{{ $menu->route }}"><i class="{{ $menu->icon }}"></i> {{ $menu->title }}</a></li>
                                @endif
                        @else
                                @if($menu->register == 'route')
                                    <li><a class="nav-link{{ Route::currentRouteName() == $menu->route ? ' active' : '' }}" href="{{ route($menu->route) }}"><i class="{{ $menu->icon }}"></i> {{ $menu->title }}</a></li>
                                @else
                                    <li><a class="nav-link" href="{{ $menu->route }}"><i class="{{ $menu->icon }}"></i> {{ $menu->title }}</a></li>
                                @endif
                        @endif
                    @endif
                @endforeach
``

**Comment by browner12** [comment] 2018-06-06 15:51
You are missing `route()` method calls in you `else` blocks.  If you just echo `$menu-route` it's going to build a relative URL from the current URL, just like you're seeing.

**Comment by AGhasemzadeh** [comment] 2018-06-06 16:19
@browner12 I have to type of routing:
1-A URL which is `{{ $menu->route }}`
2-A Route which is `{{ route($menu->route) }}`

**Comment by sisve** [comment] 2018-06-06 16:57
What you've told is is wrong. Both invocations `return route('user');` and `$routeName='user'; return route($routeName);` will return identical values. Anything else would be a failure in the php engine, or your description. I think it's in your description.

You've provided a large code snippet involving several faces (Menu, Cache, ...). This is unnecessary. Reduce the code snippets provided to reproduce the problem. You could use hardcoded arrays or anything that doesn't require us to install and configure software to try it out on our end.

This sounds like a case of someone standing in '/admin/' and having a `<a href="user">` which ends up in `/admin/user`.

So, give us ...

1. View code that shows how you call the routing system. You have told us about two different calls to route, so I would expect this to be two lines of code. Perhaps three.
2. The _generated html code_ from point 1 that shows the problem. Once again, this will probably be 2-3 lines of code.

**Closed** 2018-06-08 23:50 UTC
