### ISSUE TITLE
php artisan migrate error

### ISSUE THREAD

**Issue by mianshargeel** [laravel/framework#19522] opened 2017-06-07 21:19 UTC
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version:mysql

### Description:
i m running command: php artisan migrate
and getting such like Exception as
 [Illuminate\Database\QueryException]                                                            
  SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables  
   where table_schema = laravel3 and table_name = migrations)

**Comment by rossjcooper** [comment] 2017-06-07 21:58
Are you on Mac or Linux?

**Comment by mianshargeel** [comment] 2017-06-08 00:21
I m on mac

**Comment by sisve** [comment] 2017-06-08 03:01
Could you update this issue with your mysql version?

**Comment by amadeann** [comment] 2017-06-08 05:39
If this is a fresh install, do you see the migrations table in the DB (i.e. what happens when you execute the query from the exception directly in mysql)? I had once a similar issue and it was caused by the wrong configuration of DB connection parameters (in my case it was hostname).

**Comment by mianshargeel** [comment] 2017-06-08 07:43
Sisve I have already updated mysql

**Comment by rossjcooper** [comment] 2017-06-08 08:09
You may have to specify a connection socket in your config or use `127.0.0.1` as your `DB_HOST` rather than `localhost`

**Comment by hakuno** [comment] 2017-06-08 14:15
It seems a database schema issue. Can you test without schema or whatever? By the way, does MySQL have schema like PostgreSQL?

**Comment by mianshargeel** [comment] 2017-06-08 16:36
this is my config/database.php
'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],

and this is my .env file

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=laravel_5
DB_USERNAME=root
DB_PASSWORD=root

**Comment by mianshargeel** [comment] 2017-06-08 17:22
i also tried to submit all connection data(DB_name, username, pass etc) in my database.php but i did't works

**Comment by znsstudio** [comment] 2017-06-08 17:32
As far as I know you can not have both .env file and environment settings done via shell.

**Comment by NestorAcevedo** [comment] 2017-06-08 17:33
```
'host' =>  '127.0.0.1:3306', //or localhost
'database' =>  'forge',
'username' =>  'forge',
'password' =>  '',
```
Without unix_socket. In my case works for migrations and commands. Just I tried to log a server custom variable on command and it goes empty, so .env files on >=L5 I think we will need to do something like [this StackOverflow question](https://stackoverflow.com/questions/10731183/set-server-variable-when-calling-php-from-command-line)

**Comment by themsaid** [comment] 2017-06-08 22:05
Looks like a configuration issue, the query you shared is for postgres grammar not MySQL, please double check your config because a fresh laravel installation works with no issues.

Closing but feel free to continue discussion.

**Closed by themsaid** 2017-06-08 22:05 UTC

**Comment by mianshargeel** [comment] 2017-06-08 22:33
again getting thie kind of error
[Illuminate\Database\QueryException]                                                  
  SQLSTATE[HY000] [1049] Unknown database 'blog' (SQL: select * from information_schem  
  a.tables where table_schema = blog and table_name = migrations)                       
                                                                                        

                                                  
  [PDOException]                                  
  SQLSTATE[HY000] [1049] Unknown database 'blog'

**Comment by NowNewStart** [comment] 2017-06-09 00:49
Your database 'blog' does not exist.

**Comment by mianshargeel** [comment] 2017-06-09 08:57
NowNewStart but I created database 'blog' myself​ in mysql it is existing but when I run php artisan migrate I m getting that error, actually I m very junior in Laravel maybe I m missing something ... ?

**Comment by bujashaka** [comment] 2017-10-08 12:30
I have similar issue, php artisan migrate thinks that databasse name is information_schema even i specified database name in .env and it tries to use sqlite even i have mysql specified.

**Comment by kennblvnp** [comment] 2018-01-05 14:35
No one is answering this? Having the same problem.

@mianshargeel @bujashaka Have you already solved it?

**Comment by kevdotbadger** [comment] 2018-01-05 14:52
@kennblvnp This error is pretty generic, there's a chance your issue is completely different.

**Comment by kennblvnp** [comment] 2018-01-05 15:24
There is something weird that I noticed.

@kevdotbadger my localhost link is this: http://localhost:8888/phpmyadmin/index.php

but displayed in website phpmyadmin is: Server: localhost:8889

What does that mean?

This is my .env file by the way

```

> APP_NAME=Laravel
> APP_ENV=local
> APP_KEY=base64:cmB21VLopjlYMSrCrmuWlKYx22cUDUm5jbXXYBu71ks=
> APP_DEBUG=true
> APP_LOG_LEVEL=debug
> APP_URL=
> 
> DB_CONNECTION=mysql
> DB_HOST=localhost
> DB_PORT=3306
> DB_DATABASE=ppp
> DB_USERNAME=root
> DB_PASSWORD=root
> 
> BROADCAST_DRIVER=log
> CACHE_DRIVER=file
> SESSION_DRIVER=file
> SESSION_LIFETIME=120
> QUEUE_DRIVER=database
> 
> REDIS_HOST=127.0.0.1
> REDIS_PASSWORD=null
> REDIS_PORT=6379
> 
> MAIL_DRIVER=smtp
> MAIL_HOST=smtp.mailtrap.io
> MAIL_PORT=2525
> MAIL_USERNAME=null
> MAIL_PASSWORD=null
> MAIL_ENCRYPTION=null
> 
> PUSHER_APP_ID=
> PUSHER_APP_KEY=
> PUSHER_APP_SECRET=
> 

```

**Comment by kennblvnp** [comment] 2018-01-05 15:24
What is port on 8888 and then shows up 8889? @kevdotbadger

**Comment by mianshargeel** [comment] 2018-01-05 16:03
Hi sorry I didn't solve it.

**Comment by kennblvnp** [comment] 2018-01-05 16:21
@mianshargeel  @kevdotbadger It was already answered a scroll up.

Solution: https://stackoverflow.com/questions/27365473/mamp-with-laravel-unix-socket

Quick solution: DB_HOST=localhost;unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock


Thanks!

**Comment by NestorAcevedo** [comment] 2018-01-05 17:19
I think for .env file on Laravel should be needed https://github.com/vlucas/phpdotenv on artisan migrations.

**Comment by devamit2018** [comment] 2018-01-17 06:15
i too have same issue while installing crudbooster.

In Connection.php line 664:

  SQLSTATE[HY000] [1049] Unknown database 'project1' (SQL: select * from information_schema.tables w
  here table_schema = project1 and table_name = migrations)


In PDOConnection.php line 47:

  SQLSTATE[HY000] [1049] Unknown database 'project1'


In PDOConnection.php line 43:

  SQLSTATE[HY000] [1049] Unknown database 'project1'


but migrations file are created in databse

**Comment by kennblvnp** [comment] 2018-01-17 07:17
@devamit2018 u need to first create a database called project1 in phpmyadmin

**Comment by devamit2018** [comment] 2018-01-17 16:28
generally i create laravel from laragon and install crudbooster.it was working fine since crudbooster would automatically create database after changing in env file..

**Comment by kennblvnp** [comment] 2018-01-18 07:51
I think you should report this issue to:
https://github.com/crocodic-studio/crudbooster

**Comment by huykon** [comment] 2018-01-28 09:21
Can anyone resolved this problem? I have same it :((
Help meeeeee

**Comment by kennblvnp** [comment] 2018-01-29 00:50
have you read all the conversation? there are solutions you can try if you read it. @huykon

**Comment by ravsourabh** [comment] 2018-01-30 02:00
@mianshargeel I had the exact problem. I needed mysql driver. So just install php-mysql

**Comment by huykon** [comment] 2018-01-30 12:56
@kennblvnp I have read all and changing DB_HOST in your .env to 127.0.0.1 but this is not resolve.
Can you help me?

**Comment by neoacevedo** [comment] 2018-01-31 19:39
Try using `get_cfg_val`

**Comment by kennblvnp** [comment] 2018-02-01 02:34
Hey @huykon have you already tried this? 

DB_HOST=localhost;unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock

**Comment by starttoweb** [comment] 2018-03-04 07:55
I solved the same issue by verifying in /config/database.php the lines 50/51
'charset' => 'utf8',
'collation' => 'utf8_general_ci',
Make sure the values correspond to your Database settings.

**Comment by rotaralek** [comment] 2018-03-29 08:50
Just dont't use sleeping owl base ".env" file, use laravel ".env".
Here is example of correct data:
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:Bzu2Qk1vQ2WahfXJeuPSV95dpEGNmmjJ30aB9ZNmdHA=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=laraveladmin
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=rotaralek@gmail.com
MAIL_PASSWORD=newrotar
MAIL_ENCRYPTION=tls

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

**Comment by 36864** [comment] 2018-03-29 09:02
@rotaralek You might want to edit your post and remove your gmail credentials.

**Comment by alloyking** [comment] 2018-04-05 19:35
Using 127.0.0.1 worked for me.  I was a little surprised as to why, as it worked under localhost until recently.  I traced it back to me enabling the Firewall on my Mac.

**Comment by ganyuciha** [comment] 2018-04-29 16:40
I had this issue too on fresh Laravel 5.6,

lluminate\Database\QueryException  : SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = projectLDM and table_name = migrations)

**Comment by beidilu** [comment] 2018-05-13 04:52
Same Problem.
SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table  
  _schema = test and table_name = migrations)

**Comment by ganyuciha** [comment] 2018-05-14 03:51
hi @beidilu, i've solved this problem, don't use PHP 7.2.5, after i downgrade PHP version to 7.1.17, the error does not show up. i don't know why

**Comment by beidilu** [comment] 2018-05-14 03:57
Thanks, ganyuciha. That's good to know. I just switched to Windows :(

**Comment by megamindAT** [comment] 2018-05-22 17:20
see below
https://stackoverflow.com/questions/42909397/laravel-5-4-on-php-7-0-pdo-exception-could-not-find-driver-mysqlc/42925908

**Comment by Shrekie** [comment] 2018-05-27 13:54
`DB_PORT=3306`
to
`DB_PORT=33060`

You might not have the "0" on the end 🤷.

**Comment by ggdal** [comment] 2018-07-11 03:33
uncomment extension=php_pdo_mysql.dll in php.ini

**Comment by polinadev** [comment] 2018-07-23 20:04
This solution worked for me: 

`mysql -uroot -p`
`ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';`

_Source: https://laracasts.com/discuss/channels/laravel/caching-sha2-password-error-when-running-php-artisan-migrate_

I am on Mac and my info is: 
`Laravel: 5.6.28`
`PHP: 7.2.7`
`mysql: 8.0.11`
`DB_HOST=localhost`
`DB_PORT=3306`

Notes: database created and I didn't uncomment extension=php_pdo_mysql.dll in php.ini

**Comment by zaynbuksh** [comment] 2018-09-07 06:17
The fix that worked for me 
===================
As a MAMP user, firstly to use 127.0.0.1 and also to specify '/Applications/MAMP/tmp/mysql/mysql.sock' in socket. Oddly, this was unnecessary in the past, but became an issue after updating to MAMP 5 and upgrading my DBs to mysql 5.7 with mb4.

**Comment by seakleng2016** [comment] 2018-10-05 04:18
i fix by add DB_SOCKET=/Applications/MAMP/tmp/mysql/mysql.sock in .env 
thank @kennblvnp

**Comment by xSkArx** [comment] 2018-10-30 14:48
@mianshargeel you need to uncomment some lines on 'bootstrap/app.php'

`$app->withFacades();

$app->withEloquent();`

**Comment by BenjaminHoegh** [comment] 2018-11-09 10:07
is this issue something there will be fixed? or do we have to use the workaround?

**Comment by enhendrickson** [comment] 2018-11-12 05:02
thanks to @chrisparma, I realized I needed to clear my config cache after commenting out the unix_socket - all fixed after a ```php artisan config:cache```

**Comment by abbddkr** [comment] 2018-12-09 09:13
it's work for me

Solved Here: https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by abbddkr** [comment] 2018-12-09 09:14
it works for me
solved here: https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by firstmentor** [comment] 2018-12-21 21:34
Illuminate\Database\QueryException  : could not find driver (SQL: select * from information_schema.tables where table_schema = sneha and table_name = migrations)

  at /opt/lampp/htdocs/pn1/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   PDOException::("could not find driver")
      /opt/lampp/htdocs/pn1/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  2   PDO::__construct("mysql:host=localhost;port=3306;dbname=sneha", "root", "", [])
      /opt/lampp/htdocs/pn1/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  Please use the argument -v to see more details.

**Comment by firstmentor** [comment] 2018-12-21 21:35
plz solve problem

**Comment by skyvondave** [comment] 2019-01-24 23:20
Why is this issue closed? It's still not working for a bunch of people.

I'm getting this error on a fresh Laravel 5.7 install, going through this tutorial: https://www.toptal.com/laravel/restful-laravel-api-tutorial

 I get the following error when running `php artisan migrate` (even with the  `--step` option):

`Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = restapi and table_name = migrations)

  at /Users/dave/Sites/restapi/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   PDOException::("SQLSTATE[HY000] [2002] No such file or directory")
      /Users/dave/Sites/restapi/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  2   PDO::__construct("mysql:host=localhost;port=8889;dbname=restapi", "restapi", "vOIUHDEqHjwrqvze", [])
      /Users/dave/Sites/restapi/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  Please use the argument -v to see more details.`

I'm using MAMP 5.2. I created the restapi "schema" in MAMP's phpMyAdmin (localhost:8889, as a "new database"), and config'd the .env file to point to it:

`
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=8889
DB_DATABASE=restapi
DB_USERNAME=restapi
DB_PASSWORD=vOIUHDEqHjwrqvze
`

Changing localhost to 127.0.0.1 doesn't fix it; adding `DB_SOCKET=/Applications/MAMP/tmp/mysql/mysql.sock` doesn't fix it (the file exists under my username and group `admin` with permissions `srwxrwxrwx`); changing `DB_HOST` to `127.0.0.1` doesn't fix it; changing `DB_HOST` to `localhost;unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock` doesn't fix it; running `php artisan config:cache` didn't fix it; adding lines `$app->withFacades();` and `$app->withEloquent();` to bootstrap/app.php doesn't fix it; changing `'charset'` to `'utf8'` and `'collation'` to `'utf8_general_ci'` in config/database.php under the `mysql` connection didn't fix it; no combinations I'm trying are fixing it.

Everything looks fine except for this strange error of "No such file or directory" when running a SELECT query... that makes no sense. I'd think it'd be the socket issue but the fixes suggested here aren't working and I'm not sure what to try. A lot of fixes here are for different errors, so I'm only trying the ones for this error or from whom didn't specify.

So what's the deal? Seems like an issue from mid-2017 across multiple Laravel versions is still a problem.

**Comment by bdemirpolat** [comment] 2019-01-27 21:04
`SQLSTATE[HY000] [2002] No such file or directory` this error occured you are trying connect with network. If you are try connect with UNIX the issue will fixed.
UNIX connection ;
`$user = 'root';
$password = 'root';
$db = 'inventory';
$host = '127.0.0.1';
$port = 8889;
$socket = 'localhost:/Applications/MAMP/tmp/mysql/mysql.sock';`

Check out the mamp home page.
