### ISSUE TITLE
The throttle middleware don't limit the specific api? Only limit domain and ip?

### ISSUE THREAD

**Issue by haofrank** [laravel/framework#21271] opened 2017-09-20 08:16 UTC
- Laravel Version: 5.5.*
- PHP Version: 7.1
- Database Driver & Version:

### Description:
I update laravel from 5.4 to 5.5.Then I find the throttle middleware don't limit the specific api.All requests from a single ip use the same maxAttempts.
I want to limit single specific api.
How can I add different restrictions for each interface?

`if ($route = $request->route()) {
    return sha1($route->getDomain().'|'.$request->ip());
}`

**Comment by themsaid** [comment] 2017-09-20 09:58
I can't understand what you're saying, can you please rephrase?

Check `Illuminate\Routing\Middleware\resolveRequestSignature`, that's how request signature is resolved.

**Comment by ConnorVG** [comment] 2017-09-20 10:05
I think @haofrank wants to limit endpoints _separately_ from eachother. IE: you may exceed the limit on one endpoint without affecting the rate limit of another endpoint.

**Comment by themsaid** [comment] 2017-09-20 10:06
You can extend the `ThrottleRequests` middleware and override the `resolveRequestSignature` method as you wish :)

Closing since it's not a bug.

**Closed by themsaid** 2017-09-20 10:06 UTC
Labels: more info?
