### ISSUE TITLE
Output buffer

### ISSUE THREAD

**Issue by BartHuis** [laravel/framework#18687] opened 2017-04-06 08:31 UTC
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:
There's a problem with the http/response: http://simpledeveloper.com/how-to-fix-laravel-response-image-download-in-laravel/
this causes problems with: https://github.com/Intervention/imagecache/issues/80#issuecomment-292100218

### Steps To Reproduce:
see links above

**Comment by themsaid** [comment] 2017-04-06 09:36
I don't seem to be able to replicate this issue, this works just fine:

```
Route::get('/', function () {
    return Response::download(storage_path('test.png'), 'photo.png');
});
```

How can I replicate?

**Comment by BartHuis** [comment] 2017-04-06 10:05
@themsaid didn't try this one myself, but i think this can replacate it? http://simpledeveloper.com/how-to-fix-laravel-response-image-download-in-laravel/

**Comment by BartHuis** [comment] 2017-04-06 10:05
@themsaid and thanks for the quick reply, again :D

**Comment by themsaid** [comment] 2017-04-06 10:06
@BartHuis so you're reporting something you're not experiencing? :D I don't see opening an issue leading to anywhere while nobody knows how to replicate it.

**Comment by BartHuis** [comment] 2017-04-06 10:07
i'm experiencing it with the package thats using laravel: https://github.com/Intervention/imagecache/issues/80#issuecomment-292100218

**Comment by themsaid** [comment] 2017-04-06 10:09
I believe this is not a core issue then since we can't replicate it without using that library.

**Comment by BartHuis** [comment] 2017-04-06 10:10
i can try the http://simpledeveloper.com/how-to-fix-laravel-response-image-download-in-laravel/ case if you want... one moment

**Comment by codemonkeynorth** [comment] 2017-04-06 10:11
adapted example from:
http://image.intervention.io/getting_started/installation#laravel

```php
// usage inside a laravel route
Route::get('/', function()
{
     $img = Image::canvas(792, 50, '#FF0000');
     // ob_end_clean(); // uncommenting this fixes it
     return $img->response('jpg');
});
```

now whilst that might seem like an Intervention issue it appears , this is the response builder from Intervention.. it seems the issue appears from `Response::make` ?

```php
public function make()
    {
        $this->image->encode($this->format, $this->quality);
        $data = $this->image->getEncoded();
        $mime = finfo_buffer(finfo_open(FILEINFO_MIME_TYPE), $data);
        $length = strlen($data);

        if (function_exists('app') && is_a($app = app(), 'Illuminate\Foundation\Application')) {

            $response = \Illuminate\Support\Facades\Response::make($data);
            $response->header('Content-Type', $mime);
            $response->header('Content-Length', $length);

        } else {

            header('Content-Type: ' . $mime);
            header('Content-Length: ' . $length);
            $response = $data;
        }

        return $response;
    }
```

**Comment by BartHuis** [comment] 2017-04-06 10:14
thanks @codemonkeynorth , ill skip the reproducing then ;)

**Comment by codemonkeynorth** [comment] 2017-04-06 10:14
basically that line..

```php
$response = \Illuminate\Support\Facades\Response::make($data);
```
I can fix the corrupt output, by putting this straight after it...
```php
ob_end_clean();
```

that seems like Response::make is causing the issue?

**Comment by BartHuis** [comment] 2017-04-06 10:14
@themsaid you can use @codemonkeynorth 's version?

**Comment by themsaid** [comment] 2017-04-06 10:15
@codemonkeynorth is using a package code, I need to be able to replicate it without the package :)

**Comment by codemonkeynorth** [comment] 2017-04-06 10:16
you can also recreate it by using gd2 directly i believe

**Comment by themsaid** [comment] 2017-04-06 10:16
Also looking at the package documentation it looks like what you say works, it was tested by the package maintainers and written in the docs, there might be something that changed that caused the issue.

**Comment by codemonkeynorth** [comment] 2017-04-06 10:19
you can try creating a gd2 image and calling this from within your controller and it'll break

```imagejpeg($img);```

i think also if you try

```return Response::make($img, 200,  array('Content-Type' => 'image/jpeg'));```

it also breaks

both can be fixed by calling `ob_end_clean();`

**Comment by themsaid** [comment] 2017-04-06 10:21
This works:

```php
Route::get('/image2', function () {
    $im = imagecreatetruecolor(120, 20);
    $text_color = imagecolorallocate($im, 233, 14, 91);
    imagestring($im, 1, 5, 5,  'A Simple Text String', $text_color);
    header('Content-Type: image/jpeg');
    imagejpeg($im);

    return Response::make($im, 200, array('Content-Type' => 'image/jpeg'));
});


Route::get('/test', function(){
    return '<img src="/image2">';
});
```

**Comment by codemonkeynorth** [comment] 2017-04-06 10:24
imagejpeg returns the image without needing to make the response?

also i just get
����JF 
etc

if i leave in the Response::make line, I then get..
```php
UnexpectedValueException in Response.php line 444:
The Response content must be a string or object implementing __toString(), "resource" given.
```

**Comment by themsaid** [comment] 2017-04-06 10:25
So please, somebody, show me some code I can use to replicate the issue.

**Comment by codemonkeynorth** [comment] 2017-04-06 10:31
i dont think you can do Response::make($im...) since $im is a resource and doesnt have a __toString() function

i think the problem is that generating the image is already outputting a buffer that needs cleaning.

how do you pass a resource object to laravel response otherwise?

**Comment by BartHuis** [comment] 2017-04-06 10:37
![themsaidcoderesponse](https://cloud.githubusercontent.com/assets/7609629/24750057/c4cc3fe8-1ac5-11e7-95ce-428f4ca81796.png)

**Comment by BartHuis** [comment] 2017-04-06 10:37
@themsaid getting this when visiting /image2

**Comment by themsaid** [comment] 2017-04-06 10:39
Yes my code was wrong I'm just following your suggestions on how to replicate the issue.

**Comment by BartHuis** [comment] 2017-04-06 10:40
:)

**Comment by codemonkeynorth** [comment] 2017-04-06 10:41
@BartHuis . yes you need to take Response::make out of image2 function and put ob_end_clean() after imagejpeg

i dont know how you can get the gd2 resource into an object you can pass to Response::make

imagejpeg outputs an image. I assume that is the underlying part of Intervention too, but you can see the issues lies with how to deal with the library ouput.

It may need to be dealt with in the intervention package as it could just be an issue with using the gd2 functions. I'm not sure theres a $gd2Image->toRespondableOuput() function as such

**Comment by BartHuis** [comment] 2017-04-06 10:43
@codemonkeynorth http://simpledeveloper.com/how-to-fix-laravel-response-image-download-in-laravel/ isn't using gd2? but i'll wait for a response of @themsaid before further trying.

**Comment by themsaid** [comment] 2017-04-06 10:44
I'm not sure what response you're expecting :) I'm just unable to replicate the issue, just going to leave the issue open for a few days maybe someone can help further. Sorry :)

**Comment by BartHuis** [comment] 2017-04-06 10:46
@themsaid oh, i thought with "Yes my code was wrong I'm just following your suggestions on how to replicate the issue." you meant that you were trying the way of simpledeveloper site ;) You have a working version of your code, so we can try to make a not working version of it?

**Comment by BartHuis** [comment] 2017-04-06 11:00
@themsaid i've got you something ;)

```
Route::get('/image2', function () {
    
    //since you want to ouput this photo to your browser, you set the header stuff
    $headers = array('Content-Type' => 'image/jpeg');
    
    //now create your new response here
    $response = \Response::download('/home/vagrant/Code/website/public/images/boxed-bg.jpg', 'boxed-bg.jpg', $headers);
    // ob_end_clean(); uncommenting this line downloads the file
    
    //simply returning $response here will NOT work;
    return $response; // just go get some coffee or even tea;
});
```

didn't get it work with make() instead of download, but i think thats my lack of knowledge about how files are served.

**Comment by codemonkeynorth** [comment] 2017-04-06 11:09
probably worth checking this though!

http://stackoverflow.com/questions/36922166/gd-library-cant-output-to-browser-laravel

_"Found a space before the php tag in my package's config file"_

**Comment by BartHuis** [comment] 2017-04-06 11:24
i've no configs with spaces? :S sounds as a totally other problem?

**Comment by codemonkeynorth** [comment] 2017-04-06 11:28
you may be interested in the output to the browser from laravel just using imagejpeg in the route (and not using Response::make after)

there's an extra byte (the whitespace?) and also a cookie.. which presumably the browser doesn't expect for an image response?

**with ob_end_clean:**
```
Connection:Keep-Alive
Content-Length:1303
Content-Type:image/jpeg
Date:Thu, 06 Apr 2017 11:26:12 GMT
Keep-Alive:timeout=5, max=100
Server:Apache/2.4.23 (Win32) PHP/5.6.25
X-Powered-By:PHP/5.6.25
```

**without ob_end_clean:**
```
Cache-Control:no-cache, private
Connection:Keep-Alive
Content-Length:1304
Content-Type:text/html; charset=UTF-8
Date:Thu, 06 Apr 2017 11:26:36 GMT
Keep-Alive:timeout=5, max=100
Server:Apache/2.4.23 (Win32) PHP/5.6.25
Set-Cookie:laravel_session=eyJpdiI6ImgwUzZrK3RCU2I5UTkxa0k2V1wvWFwvdz09IiwidmFsdWUiOiJcLzhvU0Vqcm5xbjJDT1wvbWJzeEJBVmh4TTA0MFNxU2JnQTJGRDJla3V0MVRLdXpBM3hQc0tsa1FVMDZwZno3TmhaRmxxNVAwTW16NWRNVUttVG1cL2xsUT09IiwibWFjIjoiN2Q5OWRiNjBhMDZhNWU5OWIzZDU3MTQ1MDNlZTk2OGQyMDYwZTNhM2JjMzI5MTUyYmQ5MWQ2NDdkYjZlZDU3ZiJ9; expires=Thu, 06-Apr-2017 13:26:36 GMT; Max-Age=7200; path=/; httponly
X-Powered-By:PHP/5.6.25
```

**Comment by codemonkeynorth** [comment] 2017-04-06 11:31
@BartHuis .. *any* vendor file outputting a space at the start of the returned output would presumably break the image

**Comment by codemonkeynorth** [comment] 2017-04-06 11:35
just to complicate matters, i wasn't getting this a couple of days ago on a different machine, with an older version of laravel 5.4 and an older version of Intervention... but when i say older I mean not updated in the last few days, which I think both packages were)

that said, if the issue can be made with just larvael+gd2 (and possibly some combination of php settings), maybe it's *just* a PHP issue rather than any specific package or framework

either way something is creeping into the output before the image data (headers, cookies or whitespace etc)

and laravel is ignoring the header images/jpeg in that code above.

probably because it sent it beforehand? or the Route:: function adds it? etc

**Comment by BartHuis** [comment] 2017-04-06 12:11
hmm, do you use an frash install @themsaid ? and what happens if you try one of our codes?

**Comment by themsaid** [comment] 2017-04-06 13:38
This is still working for me:

```
Route::get('/image2', function () {
    
    //since you want to ouput this photo to your browser, you set the header stuff
    $headers = array('Content-Type' => 'image/jpeg');
    
    //now create your new response here
    $response = \Response::download('/home/vagrant/Code/website/public/images/boxed-bg.jpg', 'boxed-bg.jpg', $headers);
    // ob_end_clean(); uncommenting this line downloads the file
    
    //simply returning $response here will NOT work;
    return $response; // just go get some coffee or even tea;
});
```

Sorry but I can't spend more time on this at the moment since apparently it's not laravel core related, and yes I'm on a fresh laravel installation with latest 5.4

**Comment by codemonkeynorth** [comment] 2017-04-06 13:39
I'm also getting white space in front of my json responses, so I'm trying to determine why

![image](https://cloud.githubusercontent.com/assets/20189985/24757321/c7f7244c-1ad6-11e7-92c2-144ff5e979d2.png)

**Comment by themsaid** [comment] 2017-04-06 13:40
@codemonkeynorth Don't install the package, check on a fresh laravel installation.

**Comment by codemonkeynorth** [comment] 2017-04-06 13:59
I can confirm there are 2 separate issues involved here.

that initial whitespace not added on my fresh install for json or my image... (which suggests it could be a package returning whitespace)

BUT...

I still have to ob clean my output eg for this for it to show an image rather than ����JFIF��

```php
Route::get('test2', function() {
    ob_get_clean(); // <== presumably somewhere in laravel something was added before the output
    $im = imagecreatetruecolor(120, 20);
    $text_color = imagecolorallocate($im, 233, 14, 91);
    imagestring($im, 1, 5, 5,  'A Simple Text String', $text_color);
    header('Content-Type: image/jpeg');
    $im = imagejpeg($im);
});
```

therefore i would suggest

1) the broken image (white square people are seeing) is due to the whitespace, which I need to track down a cause of

2) the "����JFIF��>" etc getting output directly to the browser is due to imagejpeg already sending buffers and conflicting with laravels route/renderer
(since you can't output a gd2 image resource with **Response::make**, I think you need to clean the output buffer to pass your own headers instead)

**Comment by BartHuis** [comment] 2017-04-06 14:02
@themsaid i can understand there is a bigger investigation needed here, so you can't put your time into this :)
@codemonkeynorth love to hear if you find a package generating the space. For now maybe it's wise for @olivervogel to add the clean ;)

**Comment by codemonkeynorth** [comment] 2017-04-06 14:04
well if it's a vendor package adding the space it's one of these

"require": {
        "php": ">=5.6.4",
        "anhskohbo/no-captcha": "^2.3",
        "barryvdh/laravel-cors": "^0.9.2",
        "barryvdh/laravel-debugbar": "^2.3",
        "bogardo/mailgun": "^5.0",
        "fedeisas/laravel-mail-css-inliner": "^2.0",
        "flynsarmy/csv-seeder": "^1.0",
        "guzzlehttp/guzzle": "^6.2",
        "intervention/image": "^2.3",
        "intervention/imagecache": "^2.3",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.4",
        "laravelgems/blade-escape": "^1.0",
        "maatwebsite/excel": "^2.1",
        "olssonm/l5-very-basic-auth": "^3.0",
        "php-http/guzzle6-adapter": "^1.1",
        "pragmarx/firewall": "^1.0",
        "proengsoft/laravel-jsvalidation": "^1.6.0-dev",
        "tijsverkoyen/css-to-inline-styles": "^2.2",
        "torann/hashids": "^2.0"
    },


    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/reganjohnson/laravel-jsvalidation"
        }
    ]

**Comment by codemonkeynorth** [comment] 2017-04-06 14:27
ok . so i made the same mistake and had some whitespace in one of my custom config files :S

that removes one issue.

**Comment by BartHuis** [comment] 2017-04-06 14:45
also before your first php tag?

**Comment by stevebauman** [comment] 2017-04-06 15:32
Just to chime in here, this issue actually occurs to me only when I have **multiple** images on the same page that are being downloaded from the same download route using `Response::download()`.

It happens sporadically, meaning some images appear on one request, and on another some don't.

I resolved this by implementing a javascript lazy loader for all the images on the page. Not sure where the exact issue lies, but it seems when you're loading a lot of images from Laravel in a short period of time, it freaks out and causes an exception.

**Comment by codemonkeynorth** [comment] 2017-04-06 15:37
i had extra whitespace in **app/config/constants.php** which is my own file

![image](https://cloud.githubusercontent.com/assets/20189985/24761048/3a6db1d4-1ae2-11e7-908a-0f56ee7514b6.png)

again that doesn't stop the output headers being wrong. that just fixes the corruption not the buffering

**Comment by BartHuis** [comment] 2017-04-10 10:49
@themsaid if we look at the base of this problem, shouldn't laravel just remove all spaces before the response in the case any third party package is adding that? i even see the space before my responses from html pages.

**Comment by themsaid** [comment] 2017-04-10 13:07
@BartHuis that means a package is buggy and has to be fixed :) Anyway feel free to open a PR if you think a change is needed, but I'm not quite sure on this one really.

**Comment by codemonkeynorth** [comment] 2017-04-10 15:15
i think now we've identified the problems, the package space thing is a side-issue ... 

this is mainly about the output buffer, in terms of what automatically GD2 generates (and hence intervention) and the response headers being wrapped with laravel html/utf-8

**Comment by themsaid** [comment] 2017-04-13 10:25
If someone has a proposed change please feel free to open a PR, it's better to discuss implementation since it's an edge case.

Going to close this issue since it's not really a bug, but again please feel free to open a PR.

**Closed by themsaid** 2017-04-13 10:25 UTC
Labels: Unable to Replicate
