### ISSUE TITLE
Order by multiple columns: orderBy([$col1 => 'desc', $col2 => 'asc', ... ])

### ISSUE THREAD

**Issue by FilipQL** [laravel/framework#14813] opened 2016-08-13 22:27 UTC
Hi,

It would be nice to have an option to order by multiple columns - by keys of one array that is an argument. For example, something like this:

`orderBy(['col1' => 'desc', 'col2' => 'asc', ... ])`

**Comment by themsaid** [comment] 2016-09-05 22:55
We're open to Pull Requests if you're willing to propose such functionality.

Closing this since it's not a bug report, but feel free to open a discussion on the [Internals Repo](https://github.com/laravel/internals), it's the place for proposals and discussions.

**Closed by themsaid** 2016-09-05 22:55 UTC
