### ISSUE TITLE
Custom Error Messages in Array (size, max, min) are not displayed

### ISSUE THREAD

**Issue by kagagnon** [laravel/framework#20754] opened 2017-08-25 13:27 UTC
- Laravel Version: 5.4.32
- PHP Version: 7

When using custom validation error messages in a file separated from the default one of Laravel error message in an array such as `size` or `max` are not picked up. 

# To reproduce the problem

Duplicated the file validation file in `lang`, change the values (do not touch the keys), load it. Do a validation in the controller and pass the new file as the `$message`value. Base validations such as `required`, `numeric`, `email`, etc will display the text in the file, but rules like `size`will not works since the error messages are in an array, it gives this Exception when using `$errors->get( 'content.reasons' )`:

    Array to string conversion in MessageBag.php (line 246)

### Controller

    $validator = Validator::make( $request->all(), $rules, trans( 'admin::validation' ) );
    if ( $validator->fails() ){
        return redirect()
            ->back()
            ->withInput()
            ->withErrors( $validator );
    }

#### `$request->all()`

    [
        // ...
        "content" => [
            "reasons" => [
                [...],
                [...]
            ]
        ],
        // ...
    ]

#### `$rules`

    [
        // ...
        "content.reasons" => "required|size:3"
        // ...
    ]

#### `trans( 'admin::validation' )`

    // Exact structure of Laravel validation.php
    [
        // ...
        'size'                 => [
            'numeric' => 'The field must be :size.',
            'file'    => 'The field must be :size kilobytes.',
            'string'  => 'The field must be :size characters.',
            'array'   => 'The field must contain :size items.',
        ],
        // ...
    ]

---

### After the redirect

    $errors = session()->get('errors') ?: new ViewErrorBag;
    $field[ 'errors' ] = $errors->get( $dot_name ); // Exception thrown when $dot_name
                                                    // equals `content.reasons`.

#### `$errors`

    Illuminate\Support\ViewErrorBag {
        #bags: array:1 [
            "default" => Illuminate\Support\MessageBag {
                #messages: array:4 [
                    "content.why_title" => array:1 [
                        0 => "The field is required."
                    ]
                    "content.reasons" => array:1 [
                        0 => array:4 [
                            "numeric" => "The field must be 3."
                            "file" => "The field must be 3 kilobytes."
                            "string" => "The field must be 3 characters."
                            "array" => "The field must contain 3 items."
                        ]
                    ]
                    "content.reasons.0.icon" => array:1 [
                        0 => "The field is required."
                    ]
                    "content.reasons.0.text" => array:1 [
                        0 => "The field is required."
                    ]
                ]
                #format: ":message"
            }
        ]
    }

--- 

It works when passing no messages (use Laravel's defaults), but sometimes, generic custom messages are required.

# Suggestion

Make the validator act the same way when passing a custom array of messages than when using the Laravel's defaults.

I've seen the issue #12562, but sometimes, we need generic messages base on different validation (in packages for example).

**Comment by royduin** [comment] 2017-11-14 10:11
Just encountered the same issue with Laravel 5.5.19.

**Comment by lderkzen** [comment] 2018-04-10 17:00
I'm still experiencing this issue

**Comment by devcircus** [comment] 2018-04-10 17:36
@tillkruss It looks like the original issue raised here was fixed in #22518.

@lderkzen If you're having a similar problem, it would probably be best to open a new issue with exact steps to reproduce. Be sure to include the version of Laravel and PHP you are using.

**Closed** 2018-04-10 17:56 UTC
